// Chapter 18 — "Simple Medicine".
//
// THE HEART OF THE BOOK (CLAUDE.md, operator thesis of 26.08.2026):
// The treatment of chronic diseases is really quite simple —
// 1) movement, 2) a balanced, healthy diet (little processed food),
// 3) a good social environment and little stress.
// "Anyone can do these things on their own responsibility — it
// takes no rocket science. With these simple lifestyle adjustments,
// far more health could probably be bought than with the newest
// chemical preparations."
//
// The chapter's guiding question (operator requirement): Why does
// medicine prescribe pills instead of lifestyle?
//
// THE TONE RULE (binding): BOTH sides treated fairly. Conventional
// medicine gets its successes (acute medicine saves lives, diagnostics
// are excellent) AND its dark spots (a pill instead of advice, the
// financial interests, the limits with chronic diseases). Lifestyle
// medicine gets its evidence AND its limits: not everyone can choose
// their lifestyle (money, time, shift work, where they live), the
// lifestyle accusation must not stigmatise the sick, and the study
// that speaks against the thesis (Look AHEAD, 2013) stands explicitly
// in the text.
//
// THE NO-RUMOURS RULE (operator decision 25.08.2026): Only what is
// documented, with name and year. Framingham 1948, Morris 1953, Seven
// Countries Study 1958, Roseto from 1961, North Karelia from 1972,
// Whitehall II from 1985, Diabetes Prevention Program 2002, INTERHEART
// 2004, Blue Zones 2004/05, EPIC-Potsdam 2009, Holt-Lunstad 2010/2015,
// Look AHEAD 2013, DiRECT 2018, Hall 2019, WHO figures on
// non-communicable diseases. Where a figure is disputed (the
// centenarian rates of the Blue Zones, the withdrawn and re-published
// PREDIMED study), the text says so.
//
// THE INNOVATION CYCLE (operator observation 26.08.2026, red thread):
// Here the pattern stands on its head. Simple medicine is ancient and
// has never caused mass harm — it was displaced by the expensive,
// complex medicine that saves lives acutely but often only manages
// chronic diseases. The cycle only shows itself when the simple idea
// becomes a commodity: the wellness economy, the diet market, dietary
// supplements, self-tracking. The first voice names this itself
// (section "When the simple becomes a commodity").
//
// LENGTH RULE (operator feedback 24.08.2026): From the modern era
// onwards the opposite applies — complete and detailed. Measured in
// tests/karte-einfache-medizin.mjs.
//
// Voices (round 19): The FIRST perspective — "The Voice of Everyday
// Life", simple medicine from within, from people's lives — was
// written by Opus. The SECOND ("The Voice of Circumstances": industry,
// advertising, the world of work, a pill instead of advice — what
// makes a healthy lifestyle hard) and the final synthesis were added
// by Hermes in the second pass (Hermes pass, 29.08.2026: "added").
// Perspective workflow: CLAUDE.md. Both voices are equal; the order is
// arbitrary and no ranking.
//
// NO REPETITIONS (operator decision of 21.08.2026): Chapter 1 is
// structured by "who speaks here", chapter 2 begins with a scene,
// chapter 3 recounts a day, chapter 4 is an exchange of letters,
// chapter 5 the journey of a book, chapter 6 a tour, chapter 7 a
// trial, chapter 8 an invoice, chapter 9 a clock, chapter 10 a chain,
// chapter 11 a lens, chapter 12 an interview, chapter 13 a file,
// chapter 14 a package insert, chapter 15 a press conference, chapter
// 16 the telephone, chapter 17 the water itself. This chapter chooses
// the nineteenth dramaturgy: THE HOURS. A person with a chronic
// disease spends about two hours a year with doctors — and 8,758
// hours elsewhere. The voice of everyday life is the voice of those
// 8,758 hours. The second voice can step into the same form: the same
// hours, but from outside — who they belong to, who divides them up,
// and who earns from them.
//
// The texts are stored as line arrays with `.join('\n')` — that way
// they stay readable in the repo at ~72 characters (the operator reads
// them here), and utils/markdown.js turns them back into flowing text
// in the app.
//
// CommonJS without UI imports (architecture rule): checkable with bare `node`.

const stimmeDesAlltags = [
  '## The two hours',
  '',
  'Work out once how much medicine there is in your year.',
  '',
  'A person in Germany with a chronic disease — high blood pressure,',
  'type 2 diabetes, back pain, a tired heart — visits a practice maybe',
  'four or five times a year. A family doctor consultation lasts here on',
  'average **about seven and a half minutes**; a 2017 study that compared',
  'consultation times in 67 countries put Germany at **7.6 minutes**',
  '(Irving et al., BMJ Open 2017). Take out the waiting time, add the',
  'blood draw, add two specialist appointments and one X-ray. Then you',
  'reach roughly **two hours of medicine** in a year.',
  '',
  'A year has 8,760 hours.',
  '',
  '**I am the other 8,758.**',
  '',
  '## The 8,758 hours',
  '',
  'I am no procedure, no school, no profession. I am what happens between',
  'two appointments: the stairs in the hallway, the plate in the',
  'evening, the four hours on the office chair, the walk to the bus',
  'stop, the night in which you wake three times, the call you never',
  'got. I am inconspicuous, and that is exactly my problem: nobody',
  'prescribes me, nobody bills for me, nobody researches me without',
  'cause — and yet I am where most chronic diseases are made, and',
  'sometimes taken back again.',
  '',
  '**What you read here is a way of thinking, not a truth.** I speak for',
  'the side whose means cost nothing and therefore belong to almost no',
  'one: walking, simple food, sleep, other people. I will present my',
  'best reasons as strongly as I can, and I will give every figure a',
  'name and a year so you can look it up. And I will name the places',
  'where I look bad myself, instead of waiting for someone else to do',
  'it. They exist — and they are not few.',
  '',
  'The question at stake is not whether exercise is healthy. Nobody',
  'disputes that. The question is:',
  '',
  '**If the three simplest things in the world — moving, eating sensibly,',
  'not being alone — affect the largest part of the disease burden of',
  'our time, why are they so rarely prescribed and so easily',
  'overlooked?**',
  '',
  '## What "chronic" actually means',
  '',
  'So that we do not misunderstand each other, I will first say what I',
  'am NOT talking about.',
  '',
  'I am not talking about appendicitis, not about pneumonia, not about',
  'the broken femur, not about sepsis, and not about the heart attack in',
  'the second hour. There, modern medicine is superb, and I say that',
  'without grinding my teeth: whoever is driven into a catheter lab with',
  'a blocked coronary artery owes their life not to the walk, but to',
  'the technology. Chapters 11 to 14 of this book have told what it',
  'cost to get there.',
  '',
  '**I am talking about the diseases you do not catch but live your way',
  'into.** High blood pressure. Type 2 diabetes. Calcified arteries.',
  'Fatty liver. Most back pain. A large share of strokes. A',
  'considerable share of cancers. These diseases have no beginning you',
  'could date. They have a twenty-year prehistory.',
  '',
  'The World Health Organization groups them under the unwieldy name',
  '"non-communicable diseases". Its figures: **around 41 million people',
  'die from them every year — about 74 percent of all deaths',
  'worldwide.** As the four common behaviour-related risks, the WHO',
  'names tobacco, unhealthy diet, lack of exercise and harmful alcohol',
  'consumption; on top of that comes air pollution as an external',
  'factor.',
  '',
  'That is the ground I stand on. **The most common cause of death of',
  'our time has a prehistory that lies in the 8,758 hours.**',
  '',
  'And from this follows the uncomfortable sentence this chapter works',
  'with: a medicine built on the acute hour — diagnosis, intervention,',
  'prescription — meets a disease that consists of twenty years at a',
  'point where it can change almost nothing anymore. It can then manage',
  'it. Managing is not nothing. But it is something other than healing,',
  'and the two should not be confused.',
  '',
  '## The first pillar: the body that wants to move',
  '',
  '### How the knowledge came to be',
  '',
  'It began on a London double-decker bus.',
  '',
  'In the early 1950s, the doctor **Jeremy Morris** was looking for an',
  'explanation for why heart attacks were becoming ever more frequent in',
  'England. He found two occupational groups that resembled each other',
  'in almost everything and differed in one point: **the bus drivers',
  'sat all day. The conductors ran up and down the double-decker',
  'stairs** — by his counts, a few hundred steps per shift. Same',
  'company, same city, same noise, similar background.',
  '',
  '**In 1953 he published the result in the Lancet: the conductors had',
  'about half as many heart attacks as the drivers** — and when they did',
  'have one, they survived it more often. Morris checked the objection',
  'that immediately arises (perhaps the stronger men became conductors)',
  'against a second group: postmen versus counter clerks of the same',
  'post office. The same picture.',
  '',
  'That was the birth of an entire field of research. Since then it has',
  'produced hundreds of studies. The finding is one of the most stable',
  'in medicine.',
  '',
  '### The assumption behind it',
  '',
  'My assumption is simple: **the body is a device that distributes its',
  'parts according to use.** What is used is preserved. What is not used',
  'is broken down — not out of malice, but because maintenance costs',
  'energy and the body is frugal.',
  '',
  'That is not nature philosophy, it is observable. A leg in a cast',
  'visibly loses muscle in three weeks. Someone who becomes bedridden',
  'loses bone density. Someone who stops walking loses balance, and',
  'with it comes the fall that triggers the chain in old age: fractured',
  'neck of the femur, hospital, confusion, nursing home.',
  '',
  'New — and important for my argument — is an insight of the last',
  'twenty-five years: **the muscle is not only a motor, it is also an',
  'organ that releases messenger substances.** From around 2000, the',
  'Copenhagen research group around Bente Klarlund Pedersen showed that',
  'the working muscle sends signalling molecules into the blood (they',
  'called them myokines) that act elsewhere in the body — on sugar',
  'metabolism, on inflammatory processes, on the brain. Exercise,',
  'according to this, is not calorie expenditure. **It is a message to',
  'the whole body.**',
  '',
  '### What it does — and what it does not',
  '',
  'The effects that are documented are unspectacular and large at the',
  'same time. Regular exercise lowers blood pressure, improves the use',
  'of sugar, measurably lifts mood, preserves the ability to walk in',
  'old age, and is more effective against back pain than rest — which',
  'was once taught exactly the other way round. **The working group',
  'around I-Min Lee estimated in the Lancet in 2012 that a lack of',
  'exercise is responsible for about 9 percent of premature deaths',
  'worldwide.** The WHO recommends 150 to 300 minutes of moderate',
  'exercise per week and found in 2024 that about 31 percent of adults',
  'worldwide — around 1.8 billion people — do not reach that amount.',
  '',
  'And now the limit I draw myself, because it is constantly',
  'overstepped:',
  '',
  '**Exercise is a poor way to lose weight.** Those who only do sport',
  'and change nothing else usually lose a few kilos in studies — and',
  'often put them back on. The body compensates: it becomes more',
  'frugal, and hunger makes itself felt. Whoever tells you that you',
  'only need to run enough is selling you something. Exercise works on',
  'blood pressure, sugar, mood, strength, balance — on the scales it',
  'works least. That is part of the honesty.',
  '',
  '## The second pillar: what goes in every day',
  '',
  '### How the knowledge came to be',
  '',
  'The second strand begins in Naples.',
  '',
  'The American physiologist **Ancel Keys** came to the city in the early',
  '1950s and wondered: in the hospitals of the poor districts he saw',
  'hardly any heart attacks, in the clubs of the wealthy merchants he',
  'did. From that grew **from 1958 on the Seven Countries Study: 12,763',
  'men between 40 and 59, 16 cohorts in Finland, Greece, Italy, Japan,',
  'the Netherlands, the USA and Yugoslavia.** Followed, weighed,',
  'questioned and counted over decades.',
  '',
  'The result was a gradient nobody had expected: **the fewest heart',
  'deaths were on Crete and in Japan, the most in eastern Finland** —',
  'among men of the same age. The word "Mediterranean diet" dates from',
  'this time.',
  '',
  'I will immediately say what wobbles about it, because it is gladly',
  'concealed: the study compared **places, not people.** Where two',
  'regions differ in a thousand things, you cannot say with certainty',
  'that it was the olive oil and not the walking, the wine, the',
  'poverty, the family or the heredity. And Keys was accused of paying',
  'too little attention to sugar compared with fat. The criticism is',
  'justified. What remains is nevertheless not nothing: the differences',
  'between the places were enormous, and they disappeared when people',
  'moved from one place to another and began to eat differently there.',
  '**That speaks against heredity and for the way of life.**',
  '',
  '### The assumption behind it',
  '',
  'My assumption is this: **what goes into a person every day acts more',
  'strongly than any medicine they rarely take.** Three meals a day,',
  'seven times a week, for fifty years — that is over fifty thousand',
  'occasions. No tablet comes anywhere near that order of magnitude.',
  '',
  'It follows that eating is not about individual substances. The',
  'dispute over fat versus carbohydrates, over butter versus margarine,',
  'over the one vitamin has been going on for seventy years and has',
  'achieved little. **What shows up most clearly in the data is not a',
  'nutrient but a degree of processing.**',
  '',
  'The Brazilian nutrition researcher **Carlos Monteiro** from São Paulo',
  'proposed from 2009 on sorting foods not by nutrients but by how far',
  'they had been industrially rebuilt — the so-called NOVA',
  'classification. At the very bottom: apple, potato, lentil, egg. At',
  'the very top: products reassembled from broken-down base',
  'ingredients, with flavourings, emulsifiers, colourings — things that',
  'could not be made in any kitchen in the world.',
  '',
  '### What it does — and what it does not',
  '',
  'The most beautiful evidence for this is a small but cleanly built',
  'experiment.',
  '',
  '**In 2019, the working group around Kevin Hall at the US National',
  'Institutes of Health published a study in which twenty adults lived',
  'as inpatients for four weeks** — two weeks on an ultra-processed, two',
  'weeks on an unprocessed diet. Both menus were balanced by nutrients:',
  'the same amount of fat, sugar, salt and fibre on offer. The people',
  'were allowed to eat as much as they wanted.',
  '',
  '**Result: in the ultra-processed weeks the same people ate around 500',
  'kilocalories more per day and gained almost a kilo on average; in',
  'the unprocessed weeks they lost almost a kilo.** Without rules,',
  'without a diet, without willpower. It was the difference between two',
  'kitchens — not between two characters.',
  '',
  'For me this is the most important single finding of this chapter,',
  'because it defuses an accusation: **it is not the weakness of people',
  'that explains the weight gain. The nature of the food explains a',
  'good part of it.**',
  '',
  'And then there is the finding that matters most to my side: **type 2',
  'diabetes can recede.** In the British DiRECT study (Lean et al.,',
  'Lancet 2018), people with type 2 diabetes of at most six years',
  'standing were cared for in ordinary family doctor practices in',
  'Scotland and northern England: medication off, for some months a',
  'strictly limited formula diet, then gradually normal food again,',
  'with support along the way. **After twelve months the disease was in',
  'remission in 46 percent of participants — versus 4 percent in usual',
  'care. After 24 months it was 36 versus 3 percent.** Those who had',
  'lost more than 15 kilograms were in remission in about four-fifths',
  'of cases.',
  '',
  'A disease that was regarded as irreversible for decades is',
  'reversible in a part of those affected — not through a new',
  'preparation, but through food and support.',
  '',
  'The limits I name myself:',
  '',
  '- **Nutrition research is the weakest research in medicine.** It is',
  '  based mostly on questionnaires in which people write down what they',
  '  ate yesterday — and people remember badly and like to embellish. A',
  '  double-blind trial is hardly possible with food: you taste what you',
  '  eat.',
  '- **Even the most famous nutrition study has a flaw.** The Spanish',
  '  PREDIMED study (Estruch et al., 2013), which found around 30',
  '  percent fewer serious cardiovascular events for the Mediterranean',
  '  diet, was withdrawn in 2018 and re-published because in some',
  '  centres the random allocation had not run cleanly. The main result',
  '  survived the recalculation — but a study that had to be withdrawn',
  '  is a weaker witness than one that did not.',
  '- **The DiRECT study was not blinded**, it ran over two years, and a',
  '  part of the people regained the weight. Remission is not cure. It',
  '  lasts as long as the weight lasts.',
  '',
  '## The third pillar: the others — and the calm',
  '',
  '### How the knowledge came to be',
  '',
  'The third pillar is the least expected one, and it has a place name:',
  '**Roseto, Pennsylvania.**',
  '',
  'In the 1960s, doctors noticed that in this small town founded by',
  'Italian immigrants, strikingly few men died of heart attacks — even',
  'though they smoked, drank wine, worked hard in the quarries and',
  'cooked with lard. **Stewart Wolf and his colleagues investigated this',
  'from 1961 on.** They found no difference in food, none in smoking,',
  'none in heredity — the relatives in the neighbouring towns died',
  'normally.',
  '',
  'What they found was a social order: three generations under one',
  'roof, clubs, mutual help, no displayed differences between rich and',
  'poor. Their thesis was that this community protected.',
  '',
  '**The test came by itself.** In the following decades the young moved',
  'away, the houses grew bigger, the clubs emptied. A follow-up study',
  'of 1992 compared fifty years of mortality: **the heart attack rate in',
  'Roseto had risen and aligned itself with that of the neighbouring',
  'towns.** The advantage was gone when the community was gone.',
  '',
  'I say to that: this is a place, not an experiment. You cannot',
  'randomise a community by lot. But it was a natural experiment, and',
  'it is one of the few that could be followed over fifty years.',
  '',
  '### The assumption behind it',
  '',
  'My assumption: **the human being is a herd animal, and being alone is',
  'an alarm state for the body.** Whoever did not belong was in mortal',
  'danger in the history of this species; the body treats loneliness',
  'accordingly — with vigilance, worse sleep, higher blood pressure,',
  'persistent tension.',
  '',
  'The same applies to chronic stress. The stress response is a',
  'splendid device for the emergency: heart faster, sugar into the',
  'blood, digestion off, attention narrowed. It is built for minutes.',
  '**It is not built for seven years.** If it runs for seven years, a',
  'rescue becomes wear and tear.',
  '',
  '### What it does — and what it does not',
  '',
  'Here the figures are surprisingly clear.',
  '',
  '**In 2010, Julianne Holt-Lunstad and her colleagues evaluated 148',
  'studies with 308,849 people in PLoS Medicine. Result: those who had',
  'strong social relationships survived the observation period with',
  'roughly 50 percent higher probability.** A second analysis by the',
  'same group from 2015 found a death risk about 26 percent higher for',
  'loneliness, 29 percent for social isolation and 32 percent for',
  'living alone. The often-cited comparison with "fifteen cigarettes a',
  'day" comes from this work; it is an illustration, not a measured',
  'value, and I only pass it on here as such.',
  '',
  '**In November 2023, the WHO set up its own commission on social',
  'connection and called loneliness an urgent health hazard.** That is',
  'new: a health organisation is talking about friendship.',
  '',
  'On stress: **the INTERHEART study (Yusuf et al., Lancet 2004)',
  'compared in 52 countries around 15,000 people after their first',
  'heart attack with just as many healthy ones. Nine factors together',
  'explained over 90 percent of the risk** — including smoking, blood',
  'lipids, high blood pressure, diabetes, waist circumference, too',
  'little fruit and vegetables, too little exercise — and',
  '**psychosocial strain**, that is, persistent stress, worry, low',
  'mood.',
  '',
  'And the British **Whitehall II study** under Michael Marmot, which',
  'followed over ten thousand civil servants from 1985 on, found',
  'something the voice of circumstances will take up in the next',
  'section: **the lower the position in the hierarchy, the higher the',
  'mortality** — and one of the strongest single factors was not the',
  'amount of work but **how little control someone had over their own',
  'work.**',
  '',
  'The limit I name myself: **with all this, nobody knows for sure what',
  'is cause and what is effect.** Sick people withdraw. Whoever already',
  'has complaints leaves the house less often, loses contacts, becomes',
  'lonely. So part of the connection runs backwards. I do not claim',
  'that friendship heals. I claim that it shows up in the mortality',
  'tables — and that a medicine that does not even ask about it',
  'overlooks something big.',
  '',
  '## What the figures say together',
  '',
  'Up to here there were three separate pillars. Now the question that',
  'matters: **how much do they add up to together?**',
  '',
  'The best answer comes from Germany.',
  '',
  '**The EPIC-Potsdam study followed 23,153 people between 35 and 65.',
  'An analysis of 2009 (Ford et al., Archives of Internal Medicine)',
  'tested four characteristics: never having smoked, a body-mass index',
  'under 30, at least three and a half hours of exercise a week, and a',
  'diet rich in fruit, vegetables and whole grains with little',
  'meat.**',
  '',
  '**Those who met all four had, compared with those who met none, a 78',
  'percent lower risk of developing a serious chronic disease in the',
  'following years** — in detail: 93 percent less type 2 diabetes, 81',
  'percent fewer heart attacks, 50 percent fewer strokes and 36',
  'percent fewer cancers.',
  '',
  'That is the number this chapter is about. **No preparation in the',
  'world reaches 78 percent across four disease groups at once.** And',
  'these four characteristics are what they are: not smoking, not being',
  'too heavy, moving, eating sensibly. No rocket science.',
  '',
  'Two further pieces of evidence in the same direction:',
  '',
  '- **The American Diabetes Prevention Program (2002) allocated 3,234',
  '  people with precursors of diabetes by lot to three groups:** a',
  '  lifestyle programme, the drug metformin, or sham treatment. After',
  '  on average barely three years, the number of new diabetes cases',
  '  **fell by 58 percent in the lifestyle arm, by 31 percent in the',
  '  metformin arm.** Behaviour beat the drug — and in the same trial,',
  '  under the same conditions.',
  '- **North Karelia.** In the early 1970s this Finnish province had the',
  '  highest heart attack mortality in the world. From 1972 on, a team',
  '  around Pekka Puska worked not with patients but with dairies,',
  '  sausage makers, village clubs and housewives\' associations; in 1977',
  '  the project was extended to all of Finland. **By 2012 the heart',
  '  attack mortality of men of working age there had fallen by around',
  '  80 percent.** Here too the honest qualification: there was no',
  '  control group, and mortality fell across Europe. In North Karelia',
  '  it fell earlier and steeper.',
  '',
  '## And the study that speaks against me',
  '',
  'If I only cited the figures from just now, I would be dishonest. So I',
  'name the most important study that contradicts my thesis myself.',
  '',
  '**Look AHEAD, published in 2013 in the New England Journal of',
  'Medicine.** 5,145 overweight adults with type 2 diabetes were split',
  'by lot: one half received, over years, an intensive lifestyle',
  'programme with nutritional counselling, an exercise programme and',
  'close contact; the other, usual care. What was measured was who',
  'suffered a heart attack, a stroke or cardiac death.',
  '',
  '**After on average 9.6 years the study was stopped — not because of',
  'harm, but because it was becoming apparent that no difference would',
  'emerge anymore.** The lifestyle group had less weight, better',
  'values, more mobility, less kidney disease and less depression —',
  '**but not fewer heart attacks.**',
  '',
  'What follows from this? One can make it too easy for oneself in both',
  'directions. Those who argue against me say: there you have it — the',
  'way of life does not prevent the infarction. Those who argue for me',
  'say: the comparison group received modern drugs that lowered blood',
  'pressure and blood lipids, and besides, it too changed its',
  'behaviour; a difference was therefore hard to achieve.',
  '',
  '**Both explanations are permissible, and neither is proven.** I put',
  'the study here because it belongs here. Whoever takes simple',
  'medicine for a miracle cure is wrong on this point: it is no miracle',
  'cure. It is a very broadly acting, very cheap approach, well',
  'documented in parts and unproven in parts.',
  '',
  '## The Blue Zones — and why I distrust them myself',
  '',
  'Above the map of this chapter lie five regions in which strikingly',
  'many people grow very old. **In 2004, the population researchers',
  'Gianni Pes and Michel Poulain circled in blue pen, on a map of',
  'Sardinia, the municipalities with the most centenarians** — hence',
  'the name. From 2005 on, the journalist Dan Buettner turned it into',
  'five areas for National Geographic: **Ogliastra in Sardinia,',
  'Okinawa, Ikaria, the Nicoya peninsula in Costa Rica, and the',
  'Adventist community of Loma Linda in California.**',
  '',
  'They have almost nothing in common. Different continents, different',
  'religions, different cuisines — on Sardinia sheep\'s cheese and wine,',
  'on Okinawa sweet potatoes, in Nicoya maize and beans. What repeats',
  'itself is a **pattern, not a recipe:** movement built into the day',
  'instead of into a studio; mostly plant-based food, and rarely eaten',
  'to satiety; firm, lifelong bonds; and a task that is still there at',
  'eighty.',
  '',
  'And now the part the books about the Blue Zones rarely print.',
  '',
  '**The demographer Saul Justin Newman has shown that regions with',
  'strikingly many reported centenarians are very often regions with',
  'poor birth registers.** Where births were registered late or not at',
  'all, where pension payments are tied to proof of age, and where',
  'deaths are reported incompletely, the same statistics arise as with',
  'genuine longevity. In some regions the number of centenarians fell',
  'abruptly as soon as reliable registers were introduced. For this',
  'work Newman received the Ig Nobel Prize in 2024 — a prize that',
  'honours research which first makes you laugh and then makes you',
  'think.',
  '',
  'His criticism is disputed among experts and not the last word. **But',
  'it hits a real weak point, and that is why I write it into my own',
  'chapter:** the Blue Zones are a beautiful story with a shaky',
  'statistical foundation. I use them here as illustration, not as',
  'proof. The proof stands further up — in Potsdam, in Framingham, in',
  'the 3,234 lots of the diabetes programme.',
  '',
  'Two of the five zones speak against the glorification anyway. **On',
  'Okinawa, processed food arrived after 1945 with the American bases;',
  'the younger generations of the island today rank among the heaviest',
  'in Japan.** And in Nicoya too, the advantage is shrinking. The',
  'advantage did not hang on the genes and not on the island. It hung',
  'on a way of life — and with it, it goes.',
  '',
  '## Why the simple is so hard',
  '',
  'Now comes the section in which I harm my own cause most — and which',
  'is nevertheless the most important one.',
  '',
  '**The sentence "Everyone can do this on their own responsibility" is',
  'true and dangerous at the same time.**',
  '',
  'It is true because nobody can walk for you. No doctor, no health',
  'insurance, no state can take the dinner off your plate or the walk',
  'off your feet. In this very precise sense this chapter belongs to',
  'me: you spend the 8,758 hours.',
  '',
  'It is dangerous because it contains a word that quickly becomes an',
  'accusation — **responsibility.** And from an accusation quickly',
  'comes the claim that a sick person is to blame themselves. That is',
  'false, and demonstrably so:',
  '',
  '- **Not every chronic disease is a lifestyle disease.** Type 1',
  '  diabetes, multiple sclerosis, rheumatism, congenital heart defects,',
  '  childhood cancers, most autoimmune diseases: whoever suggests to',
  '  these people that they should have eaten differently does them an',
  '  injustice. The WHO figures above apply to the large group of common',
  '  diseases of civilisation — not to every single diagnosis.',
  '- **Those who work shifts cannot choose their sleep.** The',
  '  International Agency for Research on Cancer classifies night-shift',
  '  work as "probably carcinogenic" (group 2A). A person who stocks',
  '  shelves at night, nurses the sick or drives trains cannot decide',
  '  for a daytime rhythm. They can only change profession — and by no',
  '  means everyone can.',
  '- **Fresh food costs time, and time is unequally distributed.** Those',
  '  who have two jobs, raise children alone or care for relatives have',
  '  no hour left in the evening for the stove. Ready-made food is not',
  '  only cheap and durable, it is also fast — and for many people',
  '  speed is not a convenience but a necessity.',
  '- **Where you live plays a part.** A child growing up on a four-lane',
  '  road without a playground moves less than one with a forest behind',
  '  the house. That is not a question of character, that is urban',
  '  planning.',
  '- **And Marmot\'s finding still holds:** those who have little control',
  '  over their own work die earlier. That is the core of the',
  '  accusation my thesis must withstand. For control over one\'s own',
  '  day is exactly what my programme presupposes.',
  '',
  '**That is why I say clearly: simple medicine is not simple for',
  'everyone.** It is simple to understand and often hard to do. Whoever',
  'passes it off as a moral demand turns an offer into a debt — and',
  'loses exactly the people who would benefit most from it.',
  '',
  'Two things I nevertheless do not give up: first, that the share',
  'someone holds in their own hands would therefore be zero. It is',
  'large for some and small for others, but it is rarely zero. Second,',
  'that someone else could fill it in for you.',
  '',
  '## When the simple becomes a commodity',
  '',
  'This book carries an observation that appeared in almost every',
  'chapter: **new ideas have often first harmed and only later',
  'helped.** Surgery killed through wound fever before it saved. The',
  'rays killed their discoverers. Vaccination began with experiments on',
  'prisoners and orphans. Penicillin saved millions and produced the',
  'resistance.',
  '',
  '**With me this pattern stands on its head, and I will immediately',
  'say why that is no merit:** walking, simple food and neighbours are',
  'as old as the species. They have never triggered an epidemic because',
  'there was never anything new about them. You cannot rush anything',
  'with them. There is no approval study for climbing stairs and no',
  'adverse-event report for a kohlrabi.',
  '',
  '**But the cycle catches up with me all the same — at the point where',
  'the simple becomes a commodity.** And that point has long been',
  'reached:',
  '',
  '- From "move" came a subscription with a minimum term.',
  '- From "eat less processed" came a shelf of products that are highly',
  '  processed and called "clean".',
  '- From "eat vegetables" came a jar of capsules. The effectiveness of',
  '  dietary supplements for prevention has for the most part not been',
  '  demonstrable in large trials; they are sold anyway.',
  '- From "look after yourself" came a watch that grades your sleep, and',
  '  a self-tracking that turns rest into yet another task.',
  '- From "eat in moderation" came a diet market that has been growing',
  '  for seventy years even though its customers on average do not grow',
  '  slimmer.',
  '',
  'The industry association Global Wellness Institute estimates the',
  'global "wellness economy" at several trillion dollars a year. I cite',
  'this figure with explicit reservation — it comes from the industry',
  'itself and is no official statistic. But the direction is not',
  'disputed: **the cheapest thing has become a bestseller.**',
  '',
  'And with that arises the harm for which my side is responsible. It',
  'is not the harm of surgery or of the rays. It is a quieter one: **it',
  'hits the soul and the wallet.** Those who cannot afford the',
  'programme feel guilty on top of everything. Those who can afford it',
  'sometimes buy accessories instead of change. And out of a thing',
  'that was free for everyone becomes one that looks like a lifestyle',
  'for people with time and money.',
  '',
  '**That is the point at which I betray myself most readily — and I',
  'name it before someone else does.**',
  '',
  '## What I am not',
  '',
  'So that no misunderstanding remains at the end, here are the limits',
  'of my claim, as clearly as I can draw them:',
  '',
  '**I am no alternative.** I am no substitute for insulin in type 1',
  'diabetes, not for an antibiotic in meningitis, not for an operation',
  'for an intestinal obstruction, not for chemotherapy for childhood',
  'leukaemia. Whoever takes away from this chapter that they could stop',
  'their tablets and go for a walk instead has understood it wrong —',
  'and can die from it.',
  '',
  '**Nor am I an indictment of doctors.** Most of them know everything',
  'written here. Many also say it. They say it in seven and a half',
  'minutes, against an advertisement that runs twenty-four hours, and',
  'in a billing system in which the prescription is reimbursed and the',
  'conversation barely. That is not a question of character. It is a',
  'question of construction.',
  '',
  '**I am the ground floor.** Everything else stands on it. A blood',
  'pressure that is 160 without exercise and 145 with it still needs a',
  'tablet — but perhaps one instead of three. A diabetes that recedes',
  'no longer needs to be treated. A back that is trained is operated on',
  'less often. **That is my claim, and it is more modest than it sounds',
  'in self-help books: not instead of medicine, but underneath it.**',
  '',
  '## The door to the second voice',
  '',
  'Throughout this whole chapter I have spoken of the 8,758 hours as',
  'if they were yours.',
  '',
  '**They are not entirely yours.**',
  '',
  'Part of them belongs to a shift schedule. Part to a commute someone',
  'else laid out. Part to a food industry that knows very well which',
  'mixture of fat, sugar and salt makes you keep eating even though you',
  'are full. Part to an advertisement aimed at children. Part to a fee',
  'schedule in which seven and a half minutes are listed. Part to a',
  'housing market that decides whether there is a road or a path in',
  'front of your door.',
  '',
  '**That is why this chapter is not finished with my voice.** I tell',
  'simple medicine from within — out of life, from the point of view of',
  'the one who takes the stairs or does not take them. That is one',
  'half, and it is the half that tends to underestimate the',
  'circumstances.',
  '',
  '**The second voice of this chapter is the voice of circumstances.** It',
  'will speak of the structures: of industry, of advertising, of the',
  'world of work, of poverty — and of the question why a system that',
  'pays for every pill does not pay for the advice. It will hold',
  'against me that my programme presupposes people who dispose of',
  'their day. The objection is justified. **I noted it above myself,',
  'but I wrote it smaller than it is.**',
  '',
  'Both voices are equal. The order is chance and no judgement. Read',
  'both before you form an opinion.',
  '',
  '## The bridge to the next chapter',
  '',
  'There remains the question this chapter passes on to the next.',
  '',
  'Everything written here is practically free. Walking costs nothing.',
  'Lentils cost little. A call to an old friend costs nothing.',
  'According to the Potsdam figures, there is more health in that than',
  'in most preparations ever approved.',
  '',
  '**And yet the development runs in the other direction.** Chapter 19',
  'of this book will tell of the divide: of a medicine in which very',
  'much will be possible for the few — cultivated organs, gene',
  'analyses, constant monitoring of one\'s own body — and little for the',
  'majority, already for reasons of cost.',
  '',
  'If that comes to pass, this chapter gains a second meaning, and I do',
  'not know whether it is the better or the bitterer one:',
  '',
  '**Is simple medicine the medicine for everyone — or does it become',
  'what remains for the many once high technology has become too',
  'expensive?**',
  '',
  'I have no answer to that. I only know: whoever starts taking the',
  'stairs today does not wait for the decision.',
].join('\n');

const stimmeDerVerhaeltnisse = [
  '## The same hours, from outside',
  '',
  'The first voice has spoken of the 8,758 hours as if they were yours.',
  'I see the same hours — only from outside. And from outside they look',
  'different: not as your day, but as a day that is allocated to you.',
  'Piece by piece, by institutions bigger than you. So before you ask',
  'what you do with your hours, I answer the question the first voice',
  'did not ask:',
  '',
  '**Who really owns the 8,758 hours?**',
  '',
  'The answer is unpleasant because it is impersonal. They belong to',
  'you only in part. And the part that does not belong to you is not',
  'your fault — but it is not chance either. It is the result of',
  'decisions others made for you before you were born: how the city you',
  'live in was built; what is sold at the next corner; how much your',
  'working time is worth; and what your health insurance pays when you',
  'fall ill.',
  '',
  'I tell this side because the first voice wrote it small. Not out of',
  'malice — out of perspective. From inside you do not see the wall you',
  'run against. I am the wall.',
  '',
  '## Who the hours belong to',
  '',
  'Start with work — the largest block of the waking hours.',
  '',
  '**An employed person spends about a third of their life at work.**',
  'But the figure conceals the essential: who the time during these',
  'hours belongs to. It belongs to the employer. He does not only buy',
  'the manual tasks, he buys the time of day — and with it the sleep,',
  'the meals, the movement and the rest that have to be built around',
  'the working time.',
  '',
  'Whoever gets up at six, stands at the machine at seven, has a',
  'quarter-hour break at ten and comes home at eighteen o\'clock has no',
  '"lifestyle". They have a daily plan someone else wrote. And whoever',
  'starts at twenty-two and stops at six, their body lives against its',
  'own clock — not out of negligence, but because the economy they work',
  'in does not sleep. Hospitals, logistics, gastronomy, care: a growing',
  'part of the world of work runs around the clock, and the people who',
  'keep it running cannot choose their rhythm. They can only endure',
  'it.',
  '',
  'Then there is the sitting time. **The modern workplace is a',
  'seating place.** Desk, steering wheel, checkout, screen: most',
  'professions have taken the body out of the work. Whoever sits for',
  'eight hours cannot simply "build in more movement" afterwards — the',
  'day is full. The stairs instead of the lift are a good start; but',
  'they are no compensation for a working week that passes sitting',
  'down. That is no accusation against the individual. It is a',
  'description of who the hours belong to.',
  '',
  '## Who divides them up: the built environment',
  '',
  'After work comes the way, and the way has been built — by people who',
  'decided how cities look.',
  '',
  '**The European post-war city was rebuilt for the car.** Footpaths',
  'became leftover stretches, crossings assault courses, town centres',
  'car parks. Whoever wants to walk in many areas today walks along',
  'roads built for eighty kilometres an hour. Whoever cycles fights',
  'against the traffic the urban planning itself invited in. That is no',
  'natural catastrophe. It was a decision — and decisions can be',
  'changed, even if it takes decades.',
  '',
  'And then there is the place where most people buy their food. **The',
  'supermarket is a built environment with its own laws.** The fresh',
  'counter lies at the back so that you walk through the aisles; the',
  'sweets lie at child height by the checkout; the "healthy" shelf',
  'stands next to the one that is supposed to refute it. Whoever shops',
  'tired from work buys what is quickest and advertises loudest — not',
  'what keeps you full longest. In areas where there is no shop with',
  'fresh vegetables, only petrol-station shops and snack bars,',
  'researchers speak of "food deserts". The word sounds exaggerated',
  'until you have lived there.',
  '',
  'And finally the screens — the newest dividers of the hours. **They',
  'are not neutral.** The attention they bind is measured, stored and',
  'sold. The applications that fill your evenings are optimised to fill',
  'your evenings; every hour you give away is an income for someone.',
  'That too is a circumstance simple medicine does not know: the pill',
  'acts in the body, the screen acts at the place where your good',
  'intentions live.',
  '',
  '## Who earns from them: the plate',
  '',
  'Now to what the first voice called "what goes in every day". She is',
  'right — and she left out half: who makes the things that go in.',
  '',
  '**A large part of the food in the supermarket has not been cooked',
  'but formulated.** Food technologists develop products so that fat,',
  'sugar and salt land in a mixture the body no longer recognises as',
  '"full". In the industry this point has a name: "bliss point" — the',
  'moment in which a formulation tastes most irresistible. The term',
  'comes from product development, not from the kitchen. It describes',
  'no recipe but an intention.',
  '',
  'Research has made this intention visible. **The NOVA classification',
  'sorts foods by degree of processing** — not by nutrients.',
  'Ultra-processed products contain substances that exist in no',
  'kitchen: emulsifiers, stabilisers, flavourings, sweeteners in',
  'technical combinations. And the studies on this point clearly in one',
  'direction: the larger the share of ultra-processed food, the more',
  'people eat without noticing it. The first voice cited Kevin Hall\'s',
  'experiment — I merely refer to it and ask further: **why does a',
  'product that demonstrably outwits the feeling of satiety stand in',
  'every aisle of a country that has food laws — and a warning almost',
  'never next to it?**',
  '',
  'The answer has to do with money, and that is no secret. **The food',
  'and beverage industry spends billions on advertising every year** —',
  'a multiple of what all governments together spend on health',
  'education. A considerable part of this advertising explicitly',
  'targets children: colourful packaging, figures, surprises, collect',
  'cards. Children cannot read nutrition tables, but they can recognise',
  'figures — and they learn the brands before they learn to read. The',
  'World Health Organization has for years recommended restricting',
  'advertising of unhealthy food to children; little has happened',
  'because the advertising defends itself.',
  '',
  'And the crown is "health washing": **products that make you fat are',
  'sold as a contribution to health.** "With fibre", "No added sugar",',
  '"Natural ingredients" — these are not statements about the product',
  'but about the longing of the customers. The packaging speaks of',
  'vitality, the content speaks of fat, sugar and salt. You can buy',
  'both at the same time. That is called marketing, and it belongs to',
  'the hours that are not yours: they are earned at the checkout.',
  '',
  '## Who earns from them: advertising',
  '',
  'Advertising itself is a separate earner on your hours.',
  '',
  '**Attention has become a business.** Every minute a person looks at',
  'a screen is counted, bundled and sold to the highest-bidding',
  'intention. The first voice mentioned the doctor who speaks in seven',
  'and a half minutes against an advertisement that runs twenty-four',
  'hours. I add the mechanics: the twenty-four hours are not there by',
  'chance. They were bought — with the knowledge of when you are tired,',
  'when you are hungry and when you feel alone. The algorithms that',
  'fill your evenings have learned in which mood you resist and in',
  'which you do not.',
  '',
  'That sounds like conspiracy but is plain market economics: **where',
  'attention is the raw material, the human being becomes a deposit.**',
  'They are not hated, they are used — kindly, professionally and',
  'around the clock. Against this infrastructure simple medicine has no',
  'weapon as long as it only advises the individual. "Turn off the',
  'television" is good advice and a powerless sentence: it presupposes',
  'that one can switch off the device without losing the connection.',
  '',
  '## Who earns from them: the pill',
  '',
  'And then the question around which the whole chapter circles: **why',
  'does medicine prescribe pills instead of lifestyle?**',
  '',
  'The first voice answered: because the construction wants it so. I go',
  'one step further and show the construction.',
  '',
  '**Medicine is not paid to change hours — it is paid to treat',
  'diagnoses.** A doctor in Germany bills according to a catalogue that',
  'fixes what a service is worth: the conversation, the examination,',
  'the prescription. In this catalogue the lifestyle advice is a bad',
  'investment: it takes long, it is not documentable, it is not',
  'controllable — and it is hardly reimbursed. The prescription, by',
  'contrast, is quick, unambiguous, billable and verifiable. **The',
  'system pays for what it can measure and does not measure what it',
  'does not pay.**',
  '',
  'Then there is liability. **A doctor is liable for the pill they',
  'prescribe — for the advice they give, nobody is liable.** Whoever',
  'prescribes a drug has made a documented decision that can be checked',
  'in case of doubt. Whoever recommends a lifestyle has uttered a hope',
  'nobody can check. In a medicine that insures itself against errors,',
  'the pill wins because it can be insured. That is no evil intention',
  'of individual doctors. It is the logic of the system they work in.',
  '',
  'And finally continuing education. **A considerable part of doctors\'',
  'continuing education is financed by the pharmaceutical industry** —',
  'the chapters of this book about the financial interests of the',
  'industry have explained that. The lectures about exercise,',
  'nutrition and stress, by contrast, are financed by nobody, because',
  'they sell no product. A system fed by industry learns the language',
  'of industry: it thinks in active substances, not in weekly plans.',
  'Whoever asks why the pill beats the advice need not start with the',
  'doctors. They must start with the catalogue, with liability and with',
  'continuing education.',
  '',
  '## Poverty is a circumstance',
  '',
  'The first voice conceded that money and time are unequally',
  'distributed. I sharpen that: **poverty is no footnote of lifestyle',
  'medicine, it is its hardest test.**',
  '',
  'Those who have little money buy the cheapest — and the cheapest is',
  'almost always the most processed, because processing means shelf',
  'life and shelf life saves transport costs. Those who have little',
  'time buy the quickest — and the quickest is almost always the most',
  'ready-made. **Simple medicine is indeed simple for people with time',
  'and money; for the others it is an additional task on a day that is',
  'already full.**',
  '',
  'Then there is the stress that comes with poverty: the fear of the',
  'bill, of losing the job, of the end of the month. Research speaks',
  'of allostatic load — the wear and tear that constant pressure to',
  'adapt leaves in the body. Chronic stress is no mood, but a state',
  'that demonstrably works its way into the body: into blood pressure,',
  'into sleep, into the inflammatory values. And against this stress',
  'neither a prescription nor advice helps — it only helps to go away,',
  'and away it rarely is.',
  '',
  '**Those who want to follow simple medicine need not only will. They',
  'need leeway.** And leeway is what poverty takes away most',
  'reliably. Saying that is no excuse, it is a description. The only',
  'question is for whom the description is more unpleasant: for the one',
  'who hears it, or for the one who needs it.',
  '',
  '## What I hold against the first voice',
  '',
  'Now the objection the first voice announced itself.',
  '',
  '**Her programme presupposes people who dispose of their day.** She',
  'conceded that, and I say it once more because it is the core: for',
  'those who cannot decide when they sleep, when they eat and when they',
  'move, the sentence "Everyone can do this on their own responsibility"',
  'is simply false. It is not meant badly — it is spoken from a',
  'standpoint where the day belongs to one.',
  '',
  '**My second objection concerns the stairs.** The first voice ends',
  'with the sentence: "Whoever starts taking the stairs today does not',
  'wait for the decision." Beautifully said — but who built the',
  'stairs? Who decides whether there is a staircase in front of the',
  'door or a four-lane road, whether the lift in new buildings is',
  'mandatory, and whether the commute can be walked or only endured in',
  'traffic jams? The stairs are the symbol of simple medicine because',
  'they are always there. But they are also the symbol of what the',
  'first voice overlooks: **stairs are built or not built — that is a',
  'decision of the circumstances.**',
  '',
  'And my third objection is the quietest and the most important: **the',
  'first voice speaks of "the people" as if they were spectators of',
  'their own lives.** But the people are not only those who take the',
  'stairs or do not take them. They are also those who build the',
  'stairs, write the shifts, fill the shelves, sell the advertisements',
  'and issue the prescriptions. Simple medicine is no affair of the',
  'individual — it is an affair of all who help build on the hours.',
  'And there are more of them than the first voice wants to admit.',
  '',
  '## My own uncomfortable spot',
  '',
  'Now what I let be held against myself — for the first voice is not',
  'the only one with blind spots.',
  '',
  '**My first blind spot: the circumstances are made by people — and',
  'people can be changed.** North Karelia has shown that it works:',
  'there, it was not individual patients who changed their habits, but',
  'dairies, sausage makers and village clubs their products and their',
  'culture. If I pretend the circumstances are a law of nature, I turn',
  'a political task into an excuse. And excuses are the last thing the',
  'people need who suffer under the circumstances.',
  '',
  '**My second blind spot: I too earn from the hours.** The',
  'circumstances I describe are no foreign being — they are the sum of',
  'very many small, understandable decisions. Industry delivers what',
  'sells. Advertising sells what finds attention. Politics mirrors',
  'what is elected. And me? I too eat ready-made pizza when it has to',
  'be quick; I too scroll in the evening; I too shop at the discount',
  'store. Whoever accuses the circumstances should not pretend to',
  'stand outside them.',
  '',
  '**And my third blind spot is the hardest: acute medicine is a',
  'miracle.** It first made the hours this chapter is about possible',
  'for millions of people — the pacemakers, the antibiotics, the',
  'operations, the emergency care. Whoever draws the pill as an enemy',
  'of simple medicine forgets that the pill is often the reason why',
  'someone is still there to take the stairs. My quarrel with the',
  'first voice is not the quarrel between good and evil. It is the',
  'quarrel between two truths that both hold: **the individual can do',
  'something — and the individual cannot do everything.**',
  '',
  '## The door back',
  '',
  'I have described the hours from outside: who they belong to, who',
  'divides them up, who earns from them. The first voice described',
  'them from inside: what the body wants, what the plate can do, what',
  'closeness achieves.',
  '',
  '**We have not quarrelled about the evidence.** That movement,',
  'nutrition and connectedness work, I do not dispute. We quarrel',
  'about who can make something of it. The first voice says: you. I',
  'say: you — and those who divide up your day. Both are right, and',
  'both are wrong when they keep silent about the other part.',
  '',
  '**Whoever only points at the circumstances gives away the 8,758',
  'hours. Whoever only points at themselves conceals the',
  'circumstances.** The synthesis of this chapter must decide what',
  'follows from that — for the individual, for medicine and for those',
  'who divide up the hours.',
  '',
  'I have spoken. Now it is the synthesis\'s turn.',
].join('\n');

const einfacheMedizin = {
  id: 'einfache-medizin',
  titel: 'Simple Medicine',
  epoche: 'The Present',

  aufhaenger: {
    frage:
      'If exercise, simple food and good neighbours demonstrably ' +
      'work — why does that so rarely appear on a prescription?',
    text: [
      'A person with a chronic disease spends about two hours a year',
      'with doctors. The year has 8,760 hours. In the remaining 8,758',
      'happens what this chapter is about: the way to the bus stop, the',
      'plate in the evening, the night, the people at the table.',
      '',
      'The figures for that are there, and they are not small. The',
      'World Health Organization attributes around 41 million deaths a',
      'year — about 74 percent of all deaths worldwide — to',
      'non-communicable diseases and names tobacco, unhealthy diet, lack',
      'of exercise and alcohol as common risks. A Potsdam study of',
      '23,153 people found in 2009: those who do not smoke, are not too',
      'heavy, move regularly and eat sensibly have a 78 percent lower',
      'risk of developing a serious chronic disease.',
      '',
      'The operator of this book, himself a naturopath, has made a',
      'thesis out of it: the treatment of chronic diseases should',
      'actually be very simple — exercise, a balanced diet with little',
      'processed food, a good social environment and little stress.',
      '"It takes no rocket science."',
      '',
      'This chapter tests the thesis fairly — with the studies that',
      'speak for it and with those that speak against it. And it asks',
      'the uncomfortable question that is really at stake: why does',
      'medicine prescribe pills instead of lifestyle? Does it lie with',
      'the doctors, with the patients — or with the circumstances in',
      'which both are caught?',
    ].join('\n'),
  },

  // The map lives in utils/themen/karten/einfache-medizin.js — here only
  // the phase references are translated (phasen → karteHinweise), not the
  // map itself.
  karteHinweise: [
    {
      label: '1948: Framingham — the birth of the word "risk factor"',
      hinweis:
        'In the small town of Framingham west of Boston, an investigation ' +
        'begins in 1948 such as had never existed before: 5,209 healthy ' +
        'adults are enrolled and re-examined every two years — blood ' +
        'pressure, weight, smoking habits, blood values — and then one ' +
        'waits to see who falls ill. Not the sick are questioned, but the ' +
        'healthy are followed. From this study comes the term "risk ' +
        'factor" (1961), and from it comes the insight that high blood ' +
        'pressure, smoking and high blood lipids precede the heart ' +
        'attack. The study is still running today, now in the third ' +
        'generation.',
    },
    {
      label: '1958: the Seven Countries Study — 12,763 men in 16 places',
      hinweis:
        'The American physiologist Ancel Keys had observed in Naples ' +
        'that heart attacks were rare where people were poor and ate ' +
        'simply. From 1958 on he tests this systematically: 12,763 men ' +
        'between 40 and 59, in 16 cohorts in seven countries — Finland, ' +
        'Greece, Italy, Japan, the Netherlands, the USA and Yugoslavia. ' +
        'Result after decades: mortality from heart disease differs ' +
        'between the places by a multiple, lowest on Crete and in Japan, ' +
        'highest in eastern Finland. The criticism belongs to it: the ' +
        'study compared places, not people, and Keys was later accused ' +
        'of paying too little attention to sugar.',
    },
    {
      label: '1972: North Karelia — the first province to change its way of life',
      hinweis:
        'North Karelia in eastern Finland had the highest heart attack ' +
        'mortality in the world in the early 1970s. In 1972 a project ' +
        'begins there that treats not individual people but a whole ' +
        'province: the doctor Pekka Puska and his team work with ' +
        'villages, housewives\' associations, dairies and sausage makers ' +
        '— less salt, less animal fat, more vegetables, less smoking. ' +
        'In 1977 the project is extended to all of Finland. Between 1972 ' +
        'and 2012 the heart attack mortality of men of working age in ' +
        'North Karelia falls by around 80 percent. It was no trial with ' +
        'a control group — the decline happened all over Europe, in ' +
        'North Karelia only earlier and steeper.',
    },
    {
      label: '2004: the "Blue Zones" — five regions full of old people',
      hinweis:
        'The term comes from the population researchers Gianni Pes and ' +
        'Michel Poulain, who in 2004, on a map of Sardinia, circled in ' +
        'blue the municipalities with especially many centenarians. ' +
        'From 2005 on, the journalist Dan Buettner made it into five ' +
        'areas for National Geographic: Ogliastra in Sardinia, Okinawa, ' +
        'Ikaria, the Nicoya peninsula and the Adventist community of ' +
        'Loma Linda in California. They share no diet and no sport, but ' +
        'a pattern: movement in the daily routine, mostly plant-based ' +
        'food, firm social bonds, a task in old age. The criticism ' +
        'belongs on the same map: the demographer Saul Justin Newman ' +
        'showed that high centenarian rates often coincide with poor ' +
        'birth registers.',
    },
    {
      label: 'From 2017: lifestyle medicine becomes a discipline — and a market',
      hinweis:
        'Out of the observation becomes a treatment. In 2017 and 2018 ' +
        'the British DiRECT study shows in family doctor practices in ' +
        'Scotland and northern England that type 2 diabetes can recede ' +
        'through weight loss: after twelve months in 46 percent of ' +
        'participants, after 24 months in 36 percent — versus 4 and 3 ' +
        'percent in usual care. At the same time the simple idea ' +
        'becomes a business: nutritional counselling, fasting cures, ' +
        'dietary supplements, fitness subscriptions, self-tracking. The ' +
        'cheapest medicine in the world gets a price.',
    },
  ],

  perspektiven: [
    {
      id: 'alltag',
      name: 'The Voice of Everyday Life',
      stimme: 'Opus',
      text: stimmeDesAlltags,
    },
    {
      id: 'verhaeltnisse',
      name: 'The Voice of Circumstances',
      stimme: 'DeepSeek',
      text: stimmeDerVerhaeltnisse,
    },
  ],

  synthese: [
    '**This synthesis is the chapter\'s third voice: it holds on to what',
    'the other two have hit, and names what they disagree about.**',
    '',
    '**Where they meet.** They do not quarrel about the evidence. The',
    'voice of everyday life has named the figures that speak for simple',
    'medicine — the Potsdam study with its 78 percent, the Diabetes',
    'Prevention Program, North Karelia — and it has itself named the',
    'studies that speak against it: Look AHEAD, the shaky foundation of',
    'the Blue Zones. The voice of circumstances has not disputed this',
    'evidence; it has asked under which conditions one can follow it.',
    'Both have themselves spoken out their uncomfortable spots: the one,',
    'that its offer quickly becomes an accusation; the other, that the',
    'circumstances are made by people — and that it too has a part in',
    'them.',
    '',
    '**What they disagree about.** They disagree about a single',
    'question: who can implement it? The voice of everyday life says:',
    'you — the 8,758 hours are yours, and whoever starts today does not',
    'wait for the decision. The voice of circumstances says: you — and',
    'those who divide up your day; whoever has not built the stairs',
    'cannot take them either. It is no quarrel between true and false.',
    'It is the quarrel between two truths that both hold: **the',
    'individual can do something — and the individual cannot do',
    'everything.**',
    '',
    '**What that means for this book.** The way of thinking determines',
    'the method. Medicine thinks in diagnoses, active substances and',
    'billable services — that is why it prescribes the pill. Lifestyle',
    'medicine thinks in hours, habits and circumstances — that is why it',
    'has no billing code. Simple medicine is no rocket science, but it',
    'is also no prescription. It is a negotiation between the human',
    'being and their surroundings. Whoever burdens only the individual',
    'with it turns an offer into a debt. Whoever burdens only the',
    'circumstances with it gives away the hours that really lie in',
    'one\'s own hands. The one is unfair, the other is an excuse — and',
    'this chapter has named both so that the reader believes neither.',
    '',
    '**The bridge to the next chapter.** And then the question remains',
    'that this chapter passes on to the next: if the medicine of',
    'tomorrow becomes expensive and reserved for the few — cultivated',
    'organs, gene analyses, constant monitoring — will simple medicine',
    'then become the medicine for everyone? Or the one that remains for',
    'the many once the divide between rich and poor opens? Both voices',
    'of this chapter have named the same concern in different words.',
    'Chapter 19 will show the divide.',
  ].join('\n'),

  urteil: {
    frage:
      'Why is simple medicine so hard to prescribe — and who would ' +
      'have to change something so that it arrives?',
    hinweis: [
      'There is no right and no wrong here. Hold the two sides side by',
      'side. The one: four simple characteristics — not smoking, not',
      'being too heavy, moving, eating sensibly — were linked in the',
      'Potsdam study with a 78 percent lower risk of serious chronic',
      'diseases. No drug achieves that. The other: advice is no',
      'treatment; the Look AHEAD study found after almost ten years no',
      'difference in heart attacks; and those who work shifts or have',
      'two jobs cannot choose their day. Ask yourself three things.',
      'First: what of the three pillars — exercise, food, people around',
      'you — actually lies in your hand, and what does not? Second: when',
      'a doctor has seven and a half minutes, what can they realistically',
      'do in that time — issue a prescription or start a change of life?',
      'Third: when the most effective thing costs almost nothing — who',
      'benefits from it being so rarely prescribed all the same?',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'What did the doctor Jeremy Morris investigate in 1953 among ' +
        'London bus conductors and bus drivers?',
      antworten: [
        'Whether traffic noise raises blood pressure.',
        'Whether the conductors, who ran up and down the double-decker ' +
          'stairs all day, had fewer heart attacks than the sitting ' +
          'drivers.',
        'Whether shift work lowers life expectancy.',
      ],
      richtig: 1,
      erklaerung:
        'Morris compared two occupational groups of the same company that ' +
        'resembled each other in almost everything and differed in ' +
        'movement. The conductors had about half as many heart attacks as ' +
        'the drivers and survived them more often. He checked the result ' +
        'with postmen and counter clerks of the post office and found the ' +
        'same picture. The 1953 publication in the Lancet counts as the ' +
        'beginning of research on exercise and health.',
    },
    {
      frage:
        'In the Potsdam EPIC study (2009 analysis), four characteristics ' +
        'were tested: never smoked, body-mass index under 30, at least ' +
        'three and a half hours of exercise per week, and a plant-based ' +
        'diet. How big was the difference?',
      antworten: [
        'Those who met all four had an about 78 percent lower risk of a ' +
          'serious chronic disease.',
        'Those who met all four had an about 12 percent lower risk.',
        'There was no difference between the groups.',
      ],
      richtig: 0,
      erklaerung:
        'The study followed 23,153 people between 35 and 65. Those who met ' +
        'all four characteristics had, compared with those who met none, a ' +
        '78 percent lower risk — in detail 93 percent less type 2 ' +
        'diabetes, 81 percent fewer heart attacks, 50 percent fewer ' +
        'strokes and 36 percent fewer cancers. It is an observational ' +
        'study, not a trial with random allocation.',
    },
    {
      frage:
        'What happened in the experiment of Kevin Hall and his group (2019), ' +
        'in which twenty people received two weeks of ultra-processed and ' +
        'two weeks of unprocessed food?',
      antworten: [
        'The people ate the same amount in both phases.',
        'In the weeks with ultra-processed food they ate around 500 ' +
          'kilocalories more per day and gained weight.',
        'The unprocessed food made the participants hungrier.',
      ],
      richtig: 1,
      erklaerung:
        'Both menus were balanced by nutrients, and the participants were ' +
        'allowed to eat as much as they wanted. In the ultra-processed ' +
        'weeks the same people ate about 500 kilocalories more per day ' +
        'and gained almost a kilogram on average; in the unprocessed ' +
        'weeks they lost almost a kilogram. The experiment took place ' +
        'inpatient so that everything eaten could be recorded.',
    },
    {
      frage:
        'Where does the term "Blue Zones" come from for regions with ' +
        'especially many very old people?',
      antworten: [
        'From the blue colour of the sea at the coasts in question.',
        'From an advertising campaign of the World Health Organization.',
        'From Gianni Pes and Michel Poulain, who in 2004, on a map of ' +
          'Sardinia, circled in blue pen the municipalities with the most ' +
          'centenarians.',
      ],
      richtig: 2,
      erklaerung:
        'From these blue circles came, from 2005 on, through the ' +
        'journalist Dan Buettner, the well-known series of five areas: ' +
        'Sardinia, Okinawa, Ikaria, Nicoya and Loma Linda. The finding is ' +
        'disputed: the demographer Saul Justin Newman showed that high ' +
        'centenarian rates often coincide with incomplete birth ' +
        'registers; for that he received the Ig Nobel Prize in 2024.',
    },
    {
      frage:
        'The Look AHEAD study (2013) tested an intensive lifestyle ' +
        'programme on 5,145 overweight people with type 2 diabetes. What ' +
        'was its main result?',
      antworten: [
        'The lifestyle group had markedly fewer heart attacks and strokes.',
        'The lifestyle group lost more weight and had better values, but ' +
          'after on average 9.6 years no lower number of serious ' +
          'cardiovascular events.',
        'The programme harmed the participants, which is why the study ' +
          'was stopped.',
      ],
      richtig: 1,
      erklaerung:
        'The study was ended early because it was becoming apparent that ' +
        'no difference at the main goal was to be expected — not because ' +
        'of harm. The lifestyle group had less weight, more mobility, ' +
        'less kidney disease and less depression. A possible reason for ' +
        'the absent difference in heart attacks: the comparison group too ' +
        'was well treated with drugs and changed its behaviour. This ' +
        'explanation is not proven.',
    },
  ],
};

module.exports = einfacheMedizin;
