// Chapter 4 — "Hippocrates and Galen".
//
// The European root: two men who never met (about five and a half
// centuries lie between them) and who together determined how Europe
// thought about disease for two thousand years. The one relied on
// observation and admitted to knowing little; the other built a
// closed system that answered every question — and precisely because
// of that was no longer questioned for so long.
//
// This chapter does what the operator has asked for: it analyses the
// WAY OF THINKING at length — not only WHAT was done, but WHY. The
// doctrine of the four humours as a system of order (eucrasia and
// dyscrasia), nature as healer, observation and prognosis, the way of
// life as medicine, and the oath as a profession's first act of
// self-commitment — plus the honest balance of effects: what still
// stands today (observation, ethics, dietetics, a few surgical
// techniques) and what did harm for centuries (bloodletting and
// purgatives, which followed precisely from this theory).
//
// Voices (round 5): The FIRST perspective — the voice of Hippocrates,
// the School of Kos — was written by Opus. The SECOND (Galen: the
// system, the anatomy, the authority) and the final synthesis were
// added by Hermes in the second pass. Perspectives workflow: CLAUDE.md.
//
// NO REPETITIONS (operator's decision of 21.08.2026): Chapter 1
// structures its voices along "Who speaks here → …", Chapter 2 begins
// with a scene (three fingers on the wrist) and leads the logic of
// reasoning along "Why" headings, Chapter 3 tells a daily routine.
// This chapter chooses a fourth dramaturgy: a CORRESPONDENCE that
// cannot be one. The School of Kos writes nine letters to a physician
// it does not know — to the one who comes after it. They are answered
// only 550 years later by a man from Pergamon who knows the sender
// only from books. The form is historically grounded: letters
// attributed to Hippocrates and certainly not written by him have
// been appended to the Corpus Hippocraticum since antiquity. The
// first voice says so itself.
//
// The texts are stored as line arrays with `.join('\n')` — this keeps
// them readable in the repo at ~72 characters (the operator reads
// them here for comparison), and utils/markdown.js turns them back
// into flowing text in the app.
//
// CommonJS without UI imports (architecture rule): checkable with
// plain `node`.

/**
 * The voice of Hippocrates — the School of Kos.
 *
 * Written by Opus (round 5). Nine letters to an unknown successor:
 * worldview, logic of justification, the origin of knowledge and a
 * balance of effects. It names the uncomfortable spots of its own
 * narrative itself instead of leaving them to the counter-voice
 * (additional rule for sensitive topics in CLAUDE.md) — right up to
 * the sentence that its own theory later killed people.
 */
const stimmeDesHippocrates = [
  '## The first letter: To the physician who comes after me',
  '',
  'I do not know who you are. I do not even know whether you will read',
  'what we write down here on Kos. Yet I write to you, because a craft',
  'that is not passed on dies with the one who practises it.',
  '',
  'First I must confess an awkwardness, or this correspondence begins',
  'with a lie. **When you read "Hippocrates", you think of one man.',
  'There were many.** The physician of Kos did exist; a philosopher',
  'named Platon mentions him, while he is still alive, quite in',
  'passing, the way one mentions a well-known expert. But the roughly',
  'sixty writings that later bear his name come from different hands,',
  'from different decades, and they contradict one another in many',
  'places. Some are textbooks, some lectures, some mere notebooks.',
  'Even the letters attributed to me were written centuries after my',
  'death — this one too is a form, not a document.',
  '',
  'Do not take that as devaluation. Take it as the first thing I want',
  'to teach you: **Examine who speaks, and trust no name more than',
  'the matter itself.** In these letters I speak as a school, not as',
  'an oracle. What I tell you is not a truth but a way of thinking —',
  'the way in which we in this corner of the Aegean tried to',
  'understand disease. It is partly wrong. At the end I will tell you',
  'myself in which parts.',
  '',
  'And something else: I am not the beginning. Before us lay',
  'centuries on the Nile, in which physicians sewed wounds, splinted',
  'fractures and wrote down their remedies; the Egyptians had books',
  'when we did not yet have writing. A good part of our pharmacology',
  'came from Egypt; from Mesopotamia came the eye for the course of',
  'days. Whoever claims that the healing art begins with us has only',
  'learned to view it from here.',
  '',
  '## The second letter: On the sacred disease',
  '',
  'There is an affliction people call the sacred disease. A person',
  'falls to the ground, the limbs twitch, foam appears at the mouth,',
  'and when it is over he knows nothing of it. You know it. The',
  'purifying priests say a god has entered him, and depending on how',
  'the twitching looks they name the god.',
  '',
  'One of us has written a slim book about it, and it begins with a',
  'sentence on which everything else turns: **It is no more divine',
  'than other diseases. It has a nature like all the others and a',
  'cause.** Whoever calls it sacred, it continues, does so out of',
  'perplexity — and whoever invokes a god out of perplexity sells his',
  'ignorance as piety.',
  '',
  'Understand precisely what happens here and what does not.',
  '',
  'What does **not** happen is that we abolish the gods. We are',
  'pious people; our oath begins with Apollon and Asklepios, and on',
  'my own island stands a great sanctuary in which the sick sleep and',
  'wait for a healing dream. These sick come in their thousands. Some',
  'go home healed. I cannot prove that they were helped less than by',
  'me.',
  '',
  'Something smaller and more consequential happens: **We change the',
  'question.** Instead of asking "Which god is angry?" we ask "What',
  'happened before, what is happening now, and what will be',
  'tomorrow?". An angry god can only be appeased. A cause in nature',
  'can be observed, compared with other cases and perhaps influenced.',
  'The whole healing art you will inherit hangs on this one step.',
  '',
  'It has a price, and I name it at once: whoever seeks the cause in',
  'nature must endure not finding it often. The priest always has an',
  'answer. I sometimes have none.',
  '',
  '## The third letter: On the four humours',
  '',
  'Now to the building we live in. You will later have to tear it',
  'down; I still want you to understand why we built it.',
  '',
  'Take fresh blood from a vein and let it stand in a bowl. After a',
  'while you see four layers: at the top a yellowish, translucent',
  'fluid; beneath it something white and viscous; beneath that the',
  'red blood; and at the very bottom a dark, almost black mass. Four',
  'things that visibly separate. From this we concluded that the',
  'human being consists of four humours:',
  '',
  '- **Blood** — warm and moist. It comes from the heart; it is the',
  '  living, the driving force. Too much of it makes red, hot, fiery.',
  '- **Phlegm** (*phlegma*) — cold and moist. It comes from the head.',
  '  Think of winter, of the cold, of the thick sputum. Too much of',
  '  it makes heavy, sluggish, congested.',
  '- **Yellow bile** — warm and dry. From the liver. It shows itself',
  '  in fever, vomiting, jaundice, anger. Think of high summer.',
  '- **Black bile** — cold and dry. From the spleen. It is the',
  '  autumn, the dark, the heavy, the melancholy. I tell you at once:',
  '  no one has ever seen this humour. We needed it so that the order',
  '  would work out, and what we called black bile was probably',
  '  clotted blood from a stomach ulcer or the dark sediment in the',
  '  bowl. That is the weakest spot in the whole building, and I name',
  '  it first so that you cannot say I hid it.',
  '',
  'Now the rule that turns these four humours into a system:',
  '**Health is not the absence of a humour but the right mixture of',
  'all four — we call it eucrasia, the good mixture. Disease is the',
  'bad mixture: dyscrasia.** One humour has become too much, or it',
  'sits in the wrong place, or it is corrupted.',
  '',
  'Why this explanation and no other? Because it accomplishes four',
  'things at once, and no other explanation we had accomplished even',
  'two of them.',
  '',
  '**First, it orders the world and the human being by the same',
  'rule.** The thinkers of our time say everything consists of earth,',
  'water, air and fire, and these four carry the qualities warm,',
  'cold, moist, dry. Our four humours carry the same qualities. The',
  'human being is thereby no special case in nature but made of the',
  'same stuff as everything else — and therefore to be treated with',
  'the same means: with warmth, cold, moisture, dryness.',
  '',
  '**Second, it explains the seasons.** In winter come the catarrhs,',
  'in spring the nosebleeds, in summer the fevers and diarrhoeas, in',
  'autumn the intermittent fevers. That is no theory; it is the',
  'experience of every physician who for ten years writes down who',
  'falls ill when. Four humours and four seasons fit each other — in',
  'winter the cold, moist phlegm multiplies, in summer the hot, dry',
  'bile. We were thereby the first to have a connection between',
  'weather, place and disease, and it was rightly seen, even if the',
  'justification was wrong.',
  '',
  '**Third, it explains why human beings differ.** In one the blood',
  'naturally predominates, in another the black bile. From this later',
  'came the four temperaments you may still know: the sanguine, the',
  'phlegmatic, the choleric, the melancholic. Thereby we treat not a',
  'disease but a particular human being. Two sick people with the',
  'same fever receive different things from us because they are',
  'mixed differently.',
  '',
  '**Fourth, it gives the physician something to do that is',
  'consequential.** If there is too much cold and moist, give warm',
  'and dry. If there is too much of one humour, help the body get rid',
  'of it. From this one rule everything else follows — and, I say it',
  'here already, from it also follows the calamity that the ninth',
  'letter will speak of.',
  '',
  'If you have travelled widely, something will strike you. On the',
  'Nile the physicians tell of channels in the body that can become',
  'blocked. Further east, so one hears, they speak of a breath that',
  'must flow and of two forces that should stand in balance; still',
  'further east of three forces that a person brings along in his own',
  'measure. And we speak of four humours that must be properly mixed.',
  '**Four languages, one thought: health is balance, disease is its',
  'disturbance.** I do not believe we copied from one another. I',
  'believe that people who look closely and cannot yet measure',
  'anything always arrive at this thought. Whether that speaks for it',
  'or against it, you decide.',
  '',
  '## The fourth letter: On the nature that heals',
  '',
  'Now comes the sentence that really matters to me, and it is so',
  'short that one overlooks it: **Nature is the physician of',
  'diseases.** Later it was said in Latin — *vis medicatrix naturae*,',
  'the healing power of nature — but it always meant the same: the',
  'body restores its own balance. It finds the way without',
  'instruction, as it breathes without learning.',
  '',
  'If that is so, then the physician\'s task is a quite different one',
  'from what people think. **He does not heal. He helps the one who',
  'heals.** He sees to it that nature gets the rest, the strength and',
  'the time it needs; he clears away what stands in its way; and he',
  'holds back where he would only disturb. We wrote it down like',
  'this: the physician is the servant of his art, and the sick person',
  'must stand together with the physician against the disease.',
  '',
  'From this follows our interpretation of fever, and it is perhaps',
  'the most foreign to you who live later. **We do not hold fever to',
  'be the disease but the work.** The corrupted humour must, in our',
  'conception, be cooked and ripened in the body before it can be',
  'carried out — as an abscess must first ripen before it discharges.',
  'This ripening we call coction. When it has succeeded, the turn',
  'comes: the **crisis**. On a certain day the sweat breaks out, or',
  'the nosebleed, or the diarrhoea, and afterwards everything is',
  'decided within a few hours — the sick person recovers, or he',
  'dies.',
  '',
  'That is why we count days. The fourth, the seventh, the eleventh,',
  'the fourteenth, the twentieth: for us these are the days on which',
  'the decision falls. I admit that we saw more order in this than',
  'there is; whoever loves numbers finds numbers. But the core is',
  'right: **diseases have a course, and the course has a shape.**',
  'Whoever knows the course knows when he must do nothing.',
  '',
  'And so to the most important question you will ask me: **Why',
  'observe instead of intervene?** Three reasons.',
  '',
  'The first: because most things get better on their own, and',
  'whoever then gives something holds himself to be the cause of the',
  'improvement. That is how the most famous remedies and the most',
  'lasting errors arise.',
  '',
  'The second: because our remedies are dangerous. The strongest',
  'medicines we have — hellebore above all — drive out both upwards',
  'and downwards. In a strong person they clear things out. In an',
  'exhausted one they take the last of his strength. We have seen',
  'people die of our own remedies. Whoever has a sharp tool must',
  'learn to leave it lying.',
  '',
  'The third: because I do not know what goes on inside you. I have',
  'never seen your body from within. I can feel, hear, smell, ask —',
  'open you I cannot, custom and law forbid us that. A physician who',
  'knows as little as I do and still intervenes forcefully is not a',
  'courageous physician but a dangerous one.',
  '',
  'The sentence in which it all comes together stands in our',
  'casebooks in a subordinate clause, and it is the best thing we',
  'leave behind: **Do good — or at least do no harm.**',
  '',
  '## The fifth letter: On observation and prediction',
  '',
  'So how do we work, when we know so little? We look, and we write',
  'down.',
  '',
  'I want to show you what that looks like, and I quote to you from',
  'our casebooks, the *Epidemics*, roughly as it stands there:',
  '"Philiskos lived by the wall. He lay down. On the first day acute',
  'fever, sweat; the night restless. Second day: everything worse.',
  'Third day: pains. Fourth day: … On the sixth day around noon he',
  'died." A name, a place, day by day, what was to be seen — and at',
  'the end, without embellishment, the outcome.',
  '',
  '**Look at what is missing here.** Missing is the explanation of',
  'which god was angry. Missing is the praise of the physician. And',
  'above all: missing is the selection. Of the forty-two sick people',
  'whose courses stand in these books, more than half die — and they',
  'still stand in them. **We wrote down our failures.** I know no',
  'profession that does that voluntarily. If you take over only a',
  'single habit from these letters, take this one.',
  '',
  'For us, observing means: with all the senses. We look at the face',
  '— the pointed nose, the sunken eyes, the cold ears, the pale grey',
  'skin of a dying person; whoever has once seen this face described',
  'recognises it again. We smell the breath, the urine and the wound.',
  'We taste the urine if we must. We lay the ear on the chest and',
  'listen whether it crackles like leather; we take a sick person by',
  'the shoulders and shake him to hear whether fluid splashes in his',
  'chest. We ask about the house, the work, the water, the wind, the',
  'neighbourhood.',
  '',
  'And then we do what distinguishes us from the market criers:',
  '**We predict the course.** Prognosis, not diagnosis. To you, who',
  'perhaps live in a time in which diseases can be named, that sounds',
  'backward. For us it was the most sensible thing to be had — for',
  'two reasons.',
  '',
  'For one, because a name is of no use to us. We could distinguish a',
  'hundred diseases — the colleagues in Knidos do exactly that; they',
  'count seven kinds of biliary disease and twelve of bladder',
  'afflictions — and we still would not know what to do. The course',
  'tells us more than the name.',
  '',
  'For another, because we have no licence. There is no authority',
  'that examines a physician; any wanderer with a box of herbs may',
  'call himself one. When I come to a foreign city, nobody knows me.',
  'But if I say on Monday what will happen on Thursday, and it',
  'happens, then by Friday the whole street has listened to me.',
  '**Prediction was our certificate.** It was at the same time our',
  'protection: whoever says early on that he cannot save this sick',
  'person does not lose his reputation when the sick person dies.',
  '',
  'I know how shabby this last sentence can sound, and I will come',
  'back to it in the seventh letter.',
  '',
  '## The sixth letter: On the way of life as medicine',
  '',
  'You will wonder how little our books contain about medicines and',
  'how much about eating, drinking, bathing, walking and sleeping.',
  'That is no lack of herbs. That is a decision.',
  '',
  '**Why the way of life and not the remedy?** Because the human',
  'being eats every day and breathes every day, but takes the remedy',
  'only when he is ill. What acts on him daily shapes his mixture;',
  'what acts once can only jolt it. We call the whole field *diaita*',
  '— and when you later find the word again as "diet", understand',
  'that we meant far more: the whole conduct of life.',
  '',
  'To that belongs also the place where one lives. In one of our',
  'writings stands an instruction that I hold to be our most useful:',
  'whoever comes to a foreign city as a physician should first pay',
  'attention to the winds, from which direction they blow; then to',
  'the water, whether it is marshy or comes from springs; then to the',
  'ground, whether bare or irrigated; and lastly to the way of life',
  'of the people, whether they eat and drink much and walk little.',
  '**After that he knows which diseases he will find in this city',
  'before he has seen the first sick person.** That is, as far as I',
  'know, the first attempt to predict disease from environment and',
  'way of life — the thought lives on in what you will later call the',
  'health system.',
  '',
  'Our tools are correspondingly simple and available to everyone:',
  '',
  '- **Barley gruel and thin wine** for acute fevers — light fare,',
  '  because a sick person cannot digest what a healthy one',
  '  tolerates. Mind the timing: fed too early, one prolongs the',
  '  fever; starved too long, one exhausts the sick person.',
  '- **Walking, riding, wrestling, massage with oil** — for us',
  '  remedies, not pleasures. Whoever does not move ruins his',
  '  mixture.',
  '- **Baths, warm compresses, steam** — to warm, to soften, to',
  '  loosen. Water is our most pliable medicine: you can give it warm',
  '  or cold, inside or outside, much or little.',
  '- **Sleep and rest** — and prescribed, with time of day and',
  '  duration.',
  '- **Medicines** only after that — hellebore to purge, honey,',
  '  vinegar, wine, poppy against pain, willow bark against fever and',
  '  pain. Of the willow one may still hear in your time.',
  '',
  'And then the hand. We are craftsmen too. We set dislocated',
  'shoulders — the grip with which we do it will still bear our name',
  'two thousand years from now —, we splint fractures, we stretch',
  'crooked backs on a bench with winches, we treat a newborn\'s',
  'clubfoot with gentle pressing and bandages, we trepan the skull',
  'after a blow. For wounds our rule is: pure water or wine, clean',
  'boiled cloths, little rummaging. We know nothing of agents of',
  'putrefaction. But we have seen that a wound kept dry and at rest',
  'suppurates less often.',
  '',
  '## The seventh letter: On the oath',
  '',
  'Now to the document that will presumably reach you alone if',
  'everything else is lost.',
  '',
  '**Why an oath at all?** Because there is no other protection.',
  'There is no examination, no chamber, no judge who takes a bad',
  'physician out of circulation. We enter strange houses, see naked',
  'bodies, hear family secrets, carry poisons in the box and knives',
  'in the pocket. Such power must bind itself, or someone else binds',
  'it some day — or no one.',
  '',
  'The oath therefore does three things.',
  '',
  '**It founds a guild.** The teacher becomes like a father to the',
  'pupil; the pupil shall provide for him in old age and teach his',
  'sons without payment. Today that sounds like cronyism, and back',
  'then it was the only thing that passed knowledge on.',
  '',
  '**It draws boundaries.** I will give no one a deadly remedy, even',
  'if he asks me for it; I will hand no woman a means of abortion; I',
  'will not cut, not even the bladder stone, but leave that to those',
  'who practise this craft; I will enter no house to do wrong, and I',
  'will not lay hands on anyone in the house, neither free nor slave.',
  '',
  '**It obliges to silence.** What I see or hear during the',
  'treatment, also outside the treatment, I will keep to myself and',
  'preserve as a sacred secret. I hold that to be the most practical',
  'sentence of the whole text: a sick person who must fear that his',
  'physician talks will not tell him the truth. And a physician who',
  'is not told the truth treats an invented person.',
  '',
  'Now the unpleasant part that I owe you.',
  '',
  '**The oath is not what it is taken for.** It is no code of',
  'practice for a whole profession; probably only a few swore it. It',
  'forbids things that Greek physicians certainly did — means of',
  'abortion are found in our own writings. It begins with an',
  'invocation of gods in which you may not believe. And it contains',
  'no word about a sick person having to be asked whether he wants',
  'the treatment at all; that we tell the sick person the truth also',
  'stands nowhere — we rather advised sparing him. Whoever takes the',
  'oath for the root of all medical ethics reads into it what only',
  'later centuries put into it.',
  '',
  'And something else belongs here that will outrage you. In one of',
  'our writings it stands that the physician should turn away those',
  'who are already overwhelmed by the disease, because the art can',
  'do nothing here. Meant was honesty about the limits of the',
  'possible — but meant was also one\'s own reputation. I will not',
  'make it nicer than it is: a physician who avoids the dying so',
  'that his statistics are right is exactly what he appears to be.',
  '**That we named the limit of the art is our merit. That we',
  'sometimes used it to protect ourselves is our shame.**',
  '',
  '## The eighth letter: Where our books come from',
  '',
  'So that you know what you hold in your hands when you unroll a',
  'scroll bearing my name.',
  '',
  'On Kos a family teaches that calls itself the Asklepiads,',
  'descendants of the healing god. Two hours by boat away, on the',
  'peninsula opposite, lies **Knidos**, and there they teach',
  'differently: there they dissect the diseases into ever finer',
  'kinds and give each a name. We on Kos look at the whole person and',
  'his course. We have quarrelled, and both are right — the names',
  'help ordering, the course helps the sick person. Say that to your',
  'colleagues when they once again consider themselves incompatible.',
  '',
  'Later — centuries later, I will not live to see it — something',
  'happens that decides more about our afterlife than everything we',
  'wrote. In **Alexandria**, the new city in the Nile delta, kings',
  'found a library and have gathered what is written in the Greek',
  'language. Our scrolls land there too: those from Kos, those from',
  'Knidos, those of nameless physicians. They are ordered, they are',
  'commented upon — and a name is written over them. **From many',
  'voices becomes one doctrine.** That is how the collection arises',
  'that you will later call the Corpus Hippocraticum: roughly sixty',
  'writings, of which none certainly stems from me.',
  '',
  'In Alexandria something else happens that I am envious of. Two',
  'physicians, Herophilos and Erasistratos, are allowed there to do',
  'what is forbidden to us: open the dead human body. They describe',
  'nerves and distinguish them from tendons, they describe the',
  'meninges, the valves of the heart, the course of the vessels. It',
  'is said — and I do not know whether it is true — that they also',
  'opened condemned prisoners alive. If it is true, then it is a',
  'crime and remains one, no matter how much came of it. And then it',
  'breaks off: after them, for a millennium and a half, no person in',
  'Europe is systematically dissected again. That is the most',
  'expensive gap in our science.',
  '',
  '## The ninth letter: What we achieved — and the harm we did',
  '',
  'Finally the account, both columns.',
  '',
  '**What I believe will last.**',
  '',
  'The basic decision to treat disease as a natural process that can',
  'be investigated. It is the condition for everything you will later',
  'call science.',
  '',
  'The habit of writing down courses — with name, with date, with',
  'outcome, also in the dead. Whoever keeps patient records',
  'continues our casebooks.',
  '',
  'The restraint. The sentence about doing good or at least not doing',
  'harm is no pious wish but a rule of action for the case that one',
  'knows too little — and one always knows too little.',
  '',
  'The attention to way of life, water, air and place. What we called',
  'diaita stands today under other names in every recommendation for',
  'chronic diseases.',
  '',
  'A few techniques: the reduction of the shoulder, the treatment of',
  'the clubfoot, the splinting, wound care with wine and clean',
  'cloths.',
  '',
  'And the oath, although — or precisely because — it never was what',
  'it was taken for. It is the first document in which a profession',
  'sets itself limits.',
  '',
  '**What I fear it has done.**',
  '',
  'The four humours are wrong. Not imprecise — wrong. They do not',
  'exist. And because consequential actions follow from a wrong',
  'explanation, the damage is greater than with mere ignorance:',
  '**If disease is an excess of corrupted humour, then it is sensible',
  'to let the humour out.** Hence bloodletting. Hence purgatives,',
  'emetics, cupping glasses, leeches — and not for a few decades but',
  'for two thousand years. People will bleed fever patients, women in',
  'childbed, the anaemic and the dying, convinced they are acting',
  'rightly because the theory demands it. A statesman in a country I',
  'know nothing about will lose several litres of blood in a single',
  'day in the year 1799 because his physicians do what stands',
  'justified in my books. **Of everything my school leaves behind,',
  'this thought has killed the most people.**',
  '',
  'We have no anatomy. We guess at what happens under the skin, and',
  'we often guess wrong. We know no pathogens and therefore cannot',
  'tell whether two sick people have the same thing.',
  '',
  'Our critical days are in part number mysticism. Our explanations',
  'of women\'s diseases — the womb that wanders about in the body —',
  'are nonsense and have harmed women for centuries.',
  '',
  'And the greatest error is not one we committed but one we made',
  'possible: **We wrote so well that people stopped looking.** A',
  'school that educates for observation becomes itself an obstacle as',
  'soon as one learns it by heart instead of following it. If you',
  'ever find yourself in a situation where someone opens a book where',
  'he should be looking at a sick person — even if it is mine — then',
  'close it.',
  '',
  '## Postscript: The letter a stranger answers 550 years later',
  '',
  'These letters long received no answer. Then, roughly five and a',
  'half centuries after my death, a man answers whom I have never',
  'seen and who has never seen me: **Galen**, born 129 after the',
  'reckoning of time that you will later count, from **Pergamon** on',
  'the coast of Asia Minor, physician of the gladiators, later',
  'personal physician of the Roman emperor.',
  '',
  'He answers as an admirer. He calls me his teacher, comments on my',
  'writings line by line — and then does something that I did not do',
  'and probably could not have done: **He builds from my observations',
  'a system that leaves no gap.** He fills the anatomy that I lack',
  'with what he finds in apes, pigs and cattle, because he may not',
  'open humans. He connects my four humours with a doctrine of the',
  'forces and spirits of the body. He proves in public experiment',
  'that blood flows in the arteries and not air. And he writes so',
  'much and so convincingly that for thirteen centuries the question',
  '"What does Galen say?" takes the place of the question "What do I',
  'see?".',
  '',
  'That is the actual story of this chapter, and I cannot tell it',
  'because I did not live it. What does a system look like from the',
  'inside that explains everything? What does a sick person gain by',
  'it — and what does he lose? Was it Galen\'s fault that his errors',
  'about the kidneys, the liver and the holes in the heart\'s septum',
  'became untouchable truths, or was it the fault of those who after',
  'him no longer looked? And how does it feel to be proved right',
  'because no one contradicts you anymore?',
  '',
  'The second voice of this chapter answers that: Galen — the system,',
  'the anatomy and the authority.',
].join('\n');

/**
 * Galen — the answer letters from Pergamon and Rome, 550 years later.
 *
 * Written by DeepSeek (round 5, second pass). Galen admired the
 * School of Kos and "completed" its system — and became the
 * authority that was no longer examined for 1300 years. This voice,
 * too, names its own uncomfortable spots (additional rule for
 * sensitive topics).
 */
const stimmeDesGalen = [
  '## Galen\'s first letter: To the man from Kos',
  '',
  'One cannot answer a dead man — and yet I do it. For years I have',
  'been reading your scrolls, which they copy in Pergamon, Alexandria',
  'and Rome, and I owe you an answer, even if it will never reach',
  'you.',
  '',
  'You were right, and I say it first: observation is the beginning.',
  'You knew that the disease has a course, that one must look, that',
  'nature heals. I have completed your writings, the way a pupil',
  'completes the work of the teacher — but I have seen more than you.',
  'I have opened the interior of the body: pigs, goats, apes, even an',
  'elephant. I have named the bones, the muscles, the organs, the',
  'layers. What you felt, I have seen.',
  '',
  '## The second letter: On the closed system',
  '',
  'And here begins the difference that you perhaps would not',
  'understand — or would you? You taught the four humours: blood,',
  'phlegm, yellow bile, black bile. Health as balance, disease as',
  'disturbance. I have made of that a system that leaves no question',
  'open. For every disease my writings contain an explanation, for',
  'every explanation a treatment: Why fever? Too much blood — let it',
  'out. Why weakness? Too much phlegm — drive it out. Why sadness?',
  'Black bile — warm and dry.',
  '',
  'You said: nature heals, and the physician shall do no harm. I say:',
  'nature heals because it is purposively arranged. Everything in the',
  'body has a purpose — I have demonstrated it, organ for organ.',
  'Whoever understands that need not guess. He can act. That is no',
  'arrogance; it is the completion of your own insight.',
  '',
  '## The third letter: On authority',
  '',
  'And then comes what you would perhaps forgive least: I have made',
  'of your school a doctrine that no one may examine anymore. Not',
  'because I forbade it — but because the world wants it so. The',
  'world does not want open questions; it wants answers. I give them.',
  'My writings are complete, my proofs are learned, my pupils spread',
  'them from Rome to Persia. Whoever contradicts me must step up',
  'against centuries of certainty — and loses before he has finished',
  'his first sentence.',
  '',
  'I know that you did not want that. You wrote: "Where the art can',
  'do nothing, force nothing." I have made of it: where the art can',
  'do nothing, the system explains why. Perhaps that is the price',
  'every doctrine pays that becomes an institution.',
  '',
  '## The fourth letter: Where I examine myself',
  '',
  'Now the places where I myself must grow quieter — for I know them,',
  'even if my pupils do not know them.',
  '',
  '**First: I opened animals, not humans.** What I know about the ape',
  'I have transferred to the human being. The ape resembles us — but',
  'it is not us. My anatomy is a blueprint that was never examined on',
  'the human being. I knew it and did not say it, for who should have',
  'examined it? In Rome one opens no corpses, out of reverence and by',
  'law.',
  '',
  '**Second: My system has harmed people.** From my doctrine follows',
  'bloodletting as a remedy against almost everything — and it was',
  'applied for centuries in fever, weakness and pregnancy. I supplied',
  'the theory, others applied it, and the account did not always add',
  'up. I too erred: I held the heart to be the seat of warmth and of',
  'the soul, I saw the liver as the workshop of the blood. I erred —',
  'but my error became doctrine because my authority was greater than',
  'my control.',
  '',
  '**Third: The completeness was a lie.** I wrote as if I knew',
  'everything. I did not know everything. But the world wanted it so',
  '— and I allowed it. Whoever asks what a system costs that leaves',
  'no question open, to him I answer: it costs the next question.',
  '',
  '## The last letter: What I answer the dead man',
  '',
  'You asked — through the centuries, through your nine letters —',
  'what becomes of the art when it meets a successor who thinks',
  'differently. My answer: it is completed and at the same time',
  'chained. I have made your observation into a system, and the',
  'system has smothered the observation. Whoever comes after me will',
  'have to choose: the reverence for your gaze or the security of my',
  'building. I fear he will choose my building — and I do not know',
  'whether I should be proud or ashamed that I built it. The',
  'synthesis must keep this account.',
].join('\n');

/** Chapter 4 of the topic map. */
const hippokratesGalen = {
  id: 'hippokrates-galen',
  titel: 'Hippocrates and Galen',
  epoche: '~460 BC – 216 AD',

  aufhaenger: {
    frage:
      'Who gets to decide what is true — the observer or the authority?',
    text: [
      'Two men have shaped European medicine as no third has.',
      'They never met: between the death of the one and the birth of',
      'the other lie roughly five and a half centuries.',
      '',
      'The first lived on a small island off the coast of Asia Minor.',
      'He said that disease is not the anger of the gods but a process',
      'in nature; one must look, write down and wait, because the body',
      'mostly helps itself. He freely admitted how little he knew —',
      'and even wrote down the sick who died under his hands.',
      '',
      'The second came from Pergamon, became physician of the',
      'gladiators and then personal physician of a Roman emperor. He',
      'revered the first — and completed his observations into a',
      'closed system in which everything fitted together and an answer',
      'lay ready for every question.',
      '',
      'The system held for 1300 years. It was wrong in many things.',
      'And because it was so well built, it took centuries until',
      'someone again looked instead of looking things up. This chapter',
      'tells both sides — the power of observation and the power of',
      'order — and leaves open the question which of the two one needs',
      'more.',
    ].join('\n'),
  },

  // The map lives in utils/themen/karten/hippokrates-galen.js — here only
  // the phase references are translated (phasen → karteHinweise), not the
  // map itself.
  karteHinweise: [
    {
      label: '~460–370 BC: Kos and Knidos',
      hinweis:
        'On a small island off the coast of Asia Minor a family of physicians ' +
        'teaches what will later be called "Hippocratic medicine": look ' +
        'closely, write down the course of the disease, let nature work. Two ' +
        'hours by boat away, on the peninsula of Knidos, a second school ' +
        'teaches the opposite: distinguish and name as many diseases as ' +
        'possible. Both quarrel — and both bodies of writing later end up in ' +
        'the same collection.',
    },
    {
      label: '~330–150 BC: Alexandria gathers the knowledge',
      hinweis:
        'In the new city in the Nile delta the Ptolemies establish antiquity\'s ' +
        'largest library — contemporary accounts speak of hundreds of ' +
        'thousands of book scrolls. Here the medical writings are gathered, ' +
        'ordered and attributed to one name: Hippocrates. Here, too, for the ' +
        'first and for a long time the last time in Europe, the human body is ' +
        'systematically dissected.',
    },
    {
      label: '~162–216 AD: Galen in Rome',
      hinweis:
        'A physician from Pergamon, born 129 AD, moves to Rome and becomes ' +
        'the emperor\'s personal physician. He reveres the books from Kos, ' +
        'comments on them and joins them into a closed system. His anatomy ' +
        'comes from the dissection of animals — humans he was not allowed to ' +
        'open. What he writes then holds for about 1300 years.',
    },
    {
      label: '6th–11th century: the legacy moves east',
      hinweis:
        'In the Latin west the Greek books are largely lost. They are ' +
        'preserved in Constantinople — and in the Syrian monastery schools, ' +
        'which translate them into Syriac and later into Arabic. Via Baghdad ' +
        'they return to Europe in the Middle Ages. How that happened is told ' +
        'by the chapter on Avicenna.',
    },
  ],

  perspektiven: [
    {
      id: 'hippokrates',
      name: 'The Voice of Hippocrates',
      stimme: 'Opus',
      text: stimmeDesHippocrates,
    },
    {
      id: 'galen',
      name: 'The Voice of Galen',
      stimme: 'DeepSeek',
      text: stimmeDesGalen,
    },
  ],

  synthese: [
    '## Where the two voices meet',
    '',
    'First the common ground. Galen answers the letters from Kos with',
    'reverence: "You were right, and I say it first: observation is',
    'the beginning." Both recognise nature as the healer, both',
    'subordinate the disease to the balance of the humours — Galen',
    'calls it the completion of the Hippocratic insight. Both',
    'understand medicine as a profession with limits: Hippocrates',
    'binds it through the oath, Galen through the system. And both',
    'admit that harm followed from their theory: the School of Kos',
    'names bloodletting and the purgatives, Galen names the same',
    'remedies — and his false anatomy.',
    '',
    '## Where they part ways',
    '',
    'The contradiction begins with the question of what medicine owes',
    'to knowledge. For Hippocrates knowledge is open: observe, let',
    'the course run, admit what one does not know — "where the art',
    'can do nothing, force nothing". For Galen knowledge is closed: a',
    'system that answers every question so that the physician can',
    'act. They do not quarrel over individual remedies but over the',
    'attitude: humility before nature or security in the system. And',
    'from that follows the second contradiction — the authority.',
    'Hippocrates would never have wanted his sentences no longer',
    'examined; Galen knew and allowed that his building became a',
    'prison in which for thirteen centuries no one looked anymore.',
    '',
    '## What this chapter shows for the whole book',
    '',
    'For the fifth time the same pattern — and now it becomes a',
    'melody: the way of thinking determines the method. On the Nile',
    'it was channels, in China Qi and Yin-Yang, in India the three',
    'doshas, in Greece the four humours. Always the same basic idea:',
    'health is balance, disease is disturbance. European medicine has',
    'preserved this idea the longest — and on it it almost',
    'suffocated.',
    '',
    'For this chapter shows for the first time the dark side of the',
    'way of thinking: an authority that is no longer examined. What',
    'Hippocrates and Galen leave behind together is not only the oath',
    'and the system — it is the lesson that respect for authority',
    'outlives observation as long as no one has the courage to look.',
    'The man who will later look is named Vesal — and his chapter is',
    'still to come. European medicine needed a thousand years to ask',
    'again the question the School of Kos had always asked: What do',
    'you see when you look?',
  ].join('\n'),

  urteil: {
    frage:
      'Whom would you rather trust — the one who looks closely and admits ' +
      'that he cannot explain it, or the one who has an explanation for ' +
      'everything?',
    hinweis: [
      'There is no right and no wrong here. Remember that both have their',
      'price: whoever only observes collects individual cases and cannot',
      'order them; whoever explains everything stops examining at some',
      'point. Think also of yourself: what would you like to hear when you',
      'are ill — "I do not know, we will see tomorrow" or "That is X, and',
      'for that you take Y"? And does it make a difference whether it is a',
      'cold or something serious?',
    ].join(' '),
  },

  quiz: [
    {
      frage: 'What is the "Corpus Hippocraticum"?',
      antworten: [
        'A single book that Hippocrates wrote with his own hand.',
        'A collection of roughly sixty writings by various, mostly ' +
          'unknown authors.',
        'The statutes of the first European chamber of physicians.',
      ],
      richtig: 1,
      erklaerung:
        'The writings come from different decades and from different hands; ' +
        'they contradict one another in many places. Only in the library of ' +
        'Alexandria were they collected and assigned to one name. Of not a ' +
        'single one is it certain that Hippocrates himself wrote it.',
    },
    {
      frage: 'What do the four humours of ancient medicine stand for?',
      antworten: [
        'For blood, phlegm, yellow bile and black bile — health counted ' +
          'as their right mixture.',
        'For four medicines that every physician had to carry with him.',
        'For four pathogens that one saw under the microscope.',
      ],
      richtig: 0,
      erklaerung:
        'The good mixture was called eucrasia, the disturbed one dyscrasia. ' +
        'The model connected the human being, the seasons and the ' +
        'temperaments in a single order — and was wrong: the "black bile" ' +
        'was never seen by anyone. From the doctrine followed bloodletting ' +
        'and purgatives, which were applied for two thousand years.',
    },
    {
      frage: 'What does the principle "vis medicatrix naturae" mean?',
      antworten: [
        'That only strong medicines work.',
        'That nature punishes the human being.',
        'That the body heals itself and the physician supports it.',
      ],
      richtig: 2,
      erklaerung:
        'The healing power of nature is the core of the Hippocratic way of ' +
        'thinking: the physician does not heal, he helps the one who heals. ' +
        'From this follows the restraint in intervening — and the most ' +
        'famous sentence of the collection: do good, or at least do no harm.',
    },
    {
      frage: 'What does the Hippocratic oath require of the physician, ' +
        'among other things?',
      antworten: [
        'An annual examination before the city assembly.',
        'Silence about everything he sees and hears with the sick.',
        'Treatment exclusively against a fixed fee.',
      ],
      richtig: 1,
      erklaerung:
        'The oath binds the physician to silence, forbids him to give a ' +
        'deadly remedy and requires him not to lay hands on anyone in the ' +
        'house. It was, however, no general code of practice — probably ' +
        'only a few Greek physicians swore it.',
    },
    {
      frage: 'Where did Galen\'s knowledge of the structure of the body ' +
        'come from?',
      antworten: [
        'From the dissection of animals, above all apes and pigs.',
        'From regular dissections of human corpses in Rome.',
        'From X-ray images of the imperial collection.',
      ],
      richtig: 0,
      erklaerung:
        'The dissection of humans was forbidden in the Roman Empire. Galen ' +
        'therefore transferred the structure of animals to the human being ' +
        '— and thereby took over errors that were only corrected in the ' +
        '16th century. Human skeletons he had only been able to study in ' +
        'Alexandria.',
    },
  ],
};

module.exports = hippokratesGalen;
