// Chapter 9 — "Hahnemann and Homeopathy".
//
// The eighth chapter of the modern era and the most personal of the book:
// the operator is a naturopath (Heilpraktiker), and homeopathy is the most
// controversial healing method of the last two hundred years. That is why
// an explicit directive from CLAUDE.md applies here: Homeopathy is NOT
// dismissed as a mere placebo and not sneered at. It gets its best
// arguments, its own way of thinking and its own voice — and it names its
// uncomfortable spots itself.
//
// THE WAY-OF-THINKING ANALYSIS is the heart of the chapter (operator
// directive). Here it asks: Why the similar and not the opposite?
// (Because the body answers a stimulus with a counter-movement — the
// remedy is meant to trigger self-healing, not to suppress the complaint.)
// Why the proving on the healthy? (Because only a healthy body can say
// what a substance does on its own — in the sick, the effect mingles with
// the illness.) Why the potentisation? (Because the small dose sets the
// stimulus without poisoning — and because, according to homeopathic
// teaching, trituration and succussion do not remove anything but bring
// something out: the INFORMATION of the substance.) Why the whole human
// being? (Because in this way of thinking illness is not a matter of a
// single organ but a disturbance of the whole.)
//
// THE INFORMATION THESIS AND THE TELEPHONE ARGUMENT (operator directive,
// prominent): "Is there still substance in it?" is, according to
// homeopathic teaching, the wrong question. A telephone contains no voice
// and still transmits one; a person of the Middle Ages would have said:
// "There is nobody in there, that cannot work." That something cannot be
// explained by today's state of knowledge is no proof that it does not
// work. The voice presents this argument at full strength — and names
// itself where it grows thin: with the telephone the carrier can be
// measured, with potentisation so far not.
//
// SHELDRAKE (operator directive): The morphic fields of Rupert Sheldrake
// appear in the text as a possible model of thought — explicitly marked
// as a HYPOTHESIS, not as a proven fact (the no-rumours rule). The voice
// says itself that the scholarly world mostly rejects it.
//
// LENGTH RULE (operator feedback 24.08.2026): From chapter 9 on the
// reverse applies — complete and detailed. Measured in
// tests/karte-homoeopathie.mjs.
//
// NO RUMOURS (operator decision 25.08.2026): Only what is documented.
// Meissen 1755, the cinchona experiment 1790, the Organon 1810, the trial
// in Leipzig, Köthen 1821, Paris 1843 — all on the record. Where a number
// wavers (the number of languages Hahnemann mastered) or something is
// only handed down (the blow against the leather-bound volume), the text
// says so.
//
// THE INNOVATION CYCLE (operator observation 26.08.2026, the red thread):
// With homeopathy it stands on its head. It was the GENTLE answer to a
// brutal medicine — it burned no one, bled no one, poisoned no one. Its
// risk lies elsewhere: that the gentle idea became a dogma that no longer
// permits testing. The voice names that itself.
//
// Voices (round 17): The FIRST perspective — homeopathy from the inside,
// the voice from the line — was written by Opus. The SECOND (conventional
// medicine: its own dark past with bloodletting and mercury, the placebo
// question, the state of the studies, the question "What counts as
// proof?") and the final synthesis were added by Hermes in the second
// pass (Hermes pass, 27.08.2026: "supplemented"). Perspective workflow:
// CLAUDE.md.
//
// NO REPETITIONS (operator decision 21.08.2026): Chapter 1 is organised
// by "who speaks here", chapter 2 opens with a scene, chapter 3 tells a
// day's course, chapter 4 is an exchange of letters, chapter 5 the
// journey of a book, chapter 6 a tour, chapter 7 a trial, chapter 8 an
// account, chapter 9 a clock, chapter 10 a chain, chapter 11 a lens,
// chapter 12 an interview, chapter 13 a file, chapter 14 a package
// insert, chapter 15 a press conference. This chapter chooses the
// seventeenth dramaturgy: THE TELEPHONE. An apparatus in which nobody
// sits and from which a voice nevertheless comes — the frame for
// Hahnemann's story and for the question of whether an effect needs a
// substance. The second voice can step into the same form: the same
// apparatus, but the question about the line that one can cut open and
// measure.
//
// The texts are stored as line arrays joined with `.join('\n')` — this
// keeps them readable in the repo at around 72 characters (the operator
// proofreads them here), and utils/markdown.js turns them back into
// flowing text in the app.
//
// CommonJS without UI imports (architecture rule): testable with plain `node`.

/**
 * The voice from the line — homeopathy from the inside.
 *
 * Written by Opus (round 17). A voice that speaks for the side that has
 * treated, been convinced and been attacked for two hundred years: its
 * way of thinking, its history, its experience. It tells why it does
 * what it does — and it names the uncomfortable spots itself (additional
 * rule for sensitive topics in CLAUDE.md).
 */
const stimmeAusDerLeitung = [
  '## The apparatus in which nobody sits',
  '',
  'Imagine you could place a telephone on the table of a learned man',
  'from the year 1400. An old apparatus with receiver and cord. You pick',
  'it up, hold the earpiece to his ear, and from the black housing a',
  'woman speaks who is sitting three hundred kilometres away in another',
  'town.',
  '',
  'He will take the apparatus and shake it. He will unscrew it. He will',
  'cut the cord open and look inside. And then he will say what any',
  'reasonable man of his time would have to say:',
  '**"There is nobody in there. In this wire there is no air, no throat,',
  'no voice. So no voice can come out."**',
  '',
  'His logic is impeccable. So is his worldview — it is the best one',
  'that could be had in the year 1400. Only it does not reach as far as',
  'the place where the explanation lies. For a voice does not travel as',
  'a voice through the cable. What travels is a **pattern**: the',
  'membrane of the microphone converts the pressure of the air into a',
  'changing current, and at the other end a second membrane converts',
  'that current back into pressure. The wire carries no sound. It',
  'carries a **form**.',
  '',
  'I begin with this image because it hits the question of this chapter',
  'exactly. **What you are reading here is homeopathy from the inside —',
  'a way of thinking, not a truth.** I speak for the side that has',
  'treated, been convinced and been attacked for two hundred years. I',
  'will present its best reasons. And I will name the places where we',
  'do not look good myself, instead of waiting for someone else to do',
  'it.',
  '',
  'Two dates for honesty right away: The Frankfurt teacher **Philipp',
  'Reis** demonstrated the first apparatus that transmitted tones',
  'electrically in 1861; **Alexander Graham Bell** had the telephone',
  'patented in 1876. When Hahnemann died in 1843, none of that existed.',
  'The image of the telephone is therefore no proof of anything. It is a',
  'tool for sharpening a question — and the question is:',
  '',
  '**Must a remedy contain a substance for it to work? Or might it',
  'suffice that it carries a form?**',
  '',
  '## The line to Meissen: a porcelain painter\'s son, 1755',
  '',
  'The man in question comes from modest circumstances. **Christian',
  'Friedrich Samuel Hahnemann is born on 10 April 1755 in Meissen**, the',
  'son of a porcelain painter at the electoral manufactory.',
  '',
  'That is more than a note on his origins. A porcelain painter works',
  'with tiny quantities: a touch too much cobalt, and the blue tips',
  'over. He works with substances that become something else in the fire',
  'than they were before. And he works with precision as a way of life.',
  'The son saw that before he could read.',
  '',
  'He attends the princely school of St. Afra in Meissen; because the',
  'money is lacking, the school fees are waived. His final essay of 1775',
  'deals with the wondrous construction of the human hand. Then he goes',
  'to **Leipzig** to study medicine — with very little money, which is',
  'why he translates at night to pay for the day. In 1777 he moves to',
  '**Vienna**, where at the hospital of the Brothers of Mercy he sees',
  'real hospital beds for the first time. Afterwards he serves a',
  'governor in Hermannstadt in Transylvania as house physician and',
  'librarian. **In 1779 he is awarded a doctorate in medicine at',
  'Erlangen.**',
  '',
  'Various figures circulate about the number of languages he mastered —',
  'one reads eight, one reads twelve. **I do not name the number because',
  'the sources do not yield it.** What is documented is enough: over',
  'decades and on a large scale he translated medical and chemical',
  'textbooks from English, French, Italian and Latin. That is the',
  'profession from which everything else follows: **It was not a',
  'researcher at the bedside who discovered homeopathy, but a man at',
  'his desk who brought a foreign book into German and, while',
  'translating, got stuck.**',
  '',
  'Before that he moves from place to place: Hettstedt, **Dessau**,',
  'Gommern, **Dresden**, Leipzig again. In Dessau in the early 1780s he',
  'works in the laboratory of a pharmacy — weighing, dissolving,',
  'triturating, decanting, labelling — and in 1782 marries Johanna',
  'Henriette Küchler from the pharmacist\'s household; eleven children',
  'are born. In Dresden at the end of the 1780s he deputises for the',
  'city physician and works in the electoral library.',
  '',
  'And at some point in those years he stops treating the sick. Not out',
  'of convenience. He later puts it roughly like this: he could no',
  'longer bear to act in uncertainty and thereby cause harm. **A',
  'physician who gives up his practice because he can no longer answer',
  'for his own medicine — that is the beginning of this story.**',
  '',
  '## The medicine he took on: bloodletting, calomel, emetics',
  '',
  'To understand why a physician does such a thing, one must know what',
  'medicine meant around 1790. And here I ask for forbearance: the',
  'following lines sound like an indictment. They are not one. It is',
  'simply what then counted as the best available state of the art —',
  'applied by honourable men to the best of their knowledge.',
  '',
  'The patient is **drained**. That is the basic idea: what harms must',
  'come out. So blood is let, often repeatedly, often by the litre;',
  'leeches are applied, emetics and laxatives given, sweat is driven,',
  'blisters are raised on the skin with Spanish fly, setons are drawn',
  'through the skin of the nape so that the wound suppurates and',
  '"drains".',
  '',
  'Then the medicines: **calomel** — a mercury compound —, antimony,',
  'arsenic, bismuth, opium in amounts that no one would answer for',
  'today. Prescriptions with twenty, thirty ingredients, none of which',
  'had been tested individually and whose interplay no one knew.',
  '',
  'How that could end is shown by a very well-known case. In December',
  '1799 **George Washington** falls ill with a severe throat infection.',
  'His physicians do their best. According to the surviving accounts',
  'they draw between two and two and a half litres of blood from him',
  'within a few hours, give him calomel and an emetic and raise blisters',
  'on his throat. He dies that very night. **Whether the illness killed',
  'him or the treatment remains disputed to this day — and precisely',
  'this "disputed to this day" is the point.**',
  '',
  'Hahnemann has seen such deathbeds. Later he coins his own word for',
  'this way of treating: **allopathy** — the healing art that does',
  'something other than the illness, that works against it and thereby',
  'covers it up. His verdict on it was harsh to the point of injustice,',
  'and I will come back to that.',
  '',
  'Here only one thing counts at first: **Homeopathy did not arise as',
  'competition to an effective medicine. It arose as a counter-design',
  'to a medicine that regularly weakened its patients.** Whoever wants',
  'to judge it must compare it with what else existed then — not with',
  'what would exist a hundred and fifty years later.',
  '',
  'And here a number stands out that even our opponents do not dispute:',
  '**Mortality in the homeopathic hospitals of the nineteenth century',
  'was consistently lower than in the others.** Further below I will',
  'honestly say what that means in my view — and what it does not mean.',
  '',
  '## The translator does not hang up: Leipzig 1790',
  '',
  'Now the moment around which everything turns. It is unspectacular,',
  'and that is what makes it credible.',
  '',
  '**In 1790 Hahnemann translates the materia medica of the Edinburgh',
  'professor William Cullen into German.** He comes to the passage about',
  '**cinchona bark** — that South American bark from which quinine was',
  'later obtained and which was regarded as the only truly reliable',
  'remedy against the intermittent fever, malaria.',
  '',
  'Cullen explains its effect with its bitterness and its strengthening',
  'effect on the stomach. And here the translator pauses. For he has',
  'done enough chemistry and pharmacy to know: there are many bitter,',
  'stomach-strengthening substances, and none of them heals the',
  'intermittent fever. **The explanation does not fit the matter.**',
  '',
  'Another man would have added a footnote and written on. Hahnemann',
  'does something else: **he takes the bark himself.** Four drachms',
  'twice a day — in today\'s measure about fifteen grams each, a very',
  'strong dose.',
  '',
  'And then, as he notes in the footnote of his own translation,',
  'complaints set in: cold feet and fingertips, lassitude, palpitations,',
  'accelerated pulse, a trembling, a numbness in the head, reddening of',
  'the cheeks, thirst — and in attacks that return and pass away again.',
  '**He compares them with the complaints of the intermittent fever.**',
  '',
  'From this single footnote arises a thought that will split medicine:',
  '**The cinchona bark produces in the healthy person a picture that',
  'resembles the illness it heals in the sick.**',
  '',
  'Six years later, in 1796, he publishes it in Hufeland\'s Journal of',
  'Practical Medicine under the title "Essay on a New Principle for',
  'Ascertaining the Curative Powers of Drugs". That is the birth',
  'certificate. **The thing receives its name only in 1807:',
  'homeopathy**, from the Greek words for "similar" and "suffering".',
  '',
  'And here is an interference on the line that I will not suppress:',
  '**The cinchona experiment has to this day not been reliably',
  'repeated.** Later attempts to elicit the same complaints under',
  'controlled conditions have failed; critics suspect a personal',
  'hypersensitivity in Hahnemann or a simple poisoning effect of the',
  'high dose. That is a serious objection. It does not, however, strike',
  'the whole doctrine, but its occasion: **A thought is not false',
  'because the observation that triggered it wobbles — and not true',
  'either.** What became of it must be tested on its own.',
  '',
  '## The first ring: Similia similibus curentur',
  '',
  'The sentence that stands above everything is Latin and fits into',
  'four words: **"Similia similibus curentur" — like shall be healed by',
  'like.** It stands on the title page of the Organon.',
  '',
  'It is understood most quickly with an example everyone knows. Cut an',
  'onion: the eyes water, burn and itch, the nose runs watery, it',
  'tingles. Now there are people with a hay fever that looks exactly',
  'like that — watering, burning eyes, watery runny nose. Homeopathy',
  'gives this person a remedy made from the kitchen onion, **Allium',
  'cepa**, in potentised form.',
  '',
  'Or: coffee in the evening keeps one wide awake, sets the thoughts',
  'running, makes the heart pound. A person who lies awake exactly like',
  'that gets **Coffea**. Or: the bee sting swells pink, burns, stings',
  'and is improved by cold — for an inflammation that looks exactly like',
  'that, **Apis** is given, made from the honey bee.',
  '',
  'That is the whole principle in its simplest form. **Not the',
  'antidote, but the simile.** One does not look for the substance that',
  'suppresses the complaint, but for the substance that produces as',
  'similar a picture as possible in the healthy person.',
  '',
  'Now the decisive question — and it is the actual question of this',
  'chapter, for everything hangs on it:',
  '',
  '## The justification: why the similar and not the opposite',
  '',
  '**Why should precisely the similar heal?** The homeopathic answer has',
  'three parts, and it is consistent in itself — which does not mean',
  'that it is right, but it does mean that it is not nonsense.',
  '',
  '**First: the body heals, not the remedy.** A cut closes, a bone',
  'grows together, a fever rises and falls. No physician does that; he',
  'creates conditions. In this way of thinking healing is always',
  'self-healing. A remedy can therefore only **trigger** it.',
  '',
  '**Second: the body answers a stimulus with a counter-movement.**',
  'That can be observed every day. A cold shower cools at first and',
  'then makes the skin glow. A strong coffee wakes and hours later',
  'leaves fatigue. A sleeping pill brings sleep and afterwards often a',
  'night that is worse than before. **The first effect comes from the',
  'substance, the second comes from the body — and the second is the',
  'lasting one.**',
  '',
  'From this follows the homeopathic reckoning: if one gives a sick',
  'person a substance that imitates exactly his complaints, one sets a',
  'stimulus in the direction in which the illness is pushing anyway.',
  'The body answers with a counter-movement — and this counter-movement',
  'is the healing. **One does not work against the illness, but with',
  'the force that the body brings up against it.**',
  '',
  '**Third: the opposite only suppresses.** Whoever lowers a fever has',
  'lowered the temperature and not the cause. Whoever stills the cough',
  'has left the phlegm in the bronchus. That can be necessary and',
  'right — homeopathy does not dispute that —, but in this way of',
  'thinking it is management of the condition, not healing.',
  '',
  'And because two patients with the same diagnosis show entirely',
  'different pictures, something practical follows: **It is not the',
  'illness that gets a remedy, but the patient.** Ten people with flu',
  'may get ten different remedies — depending on whether one shivers or',
  'glows, whether he is thirsty or not, whether he wants to be alone or',
  'not, whether it gets worse in the evening or in the morning. That is',
  'no whim. It follows necessarily from the principle: if the similar',
  'is to heal, one must know whom it is supposed to resemble.',
  '',
  '## The protocol: the proving on the healthy',
  '',
  'Therewith Hahnemann stands before a tangible problem. If he is',
  'looking for the substance that imitates a particular picture of',
  'illness, he must know of every substance **which picture it',
  'produces**. And this knowledge did not exist.',
  '',
  'His solution is the strongest part of the whole story, and at the',
  'same time his most scientific deed: **the drug proving on the',
  'healthy.**',
  '',
  '**Why on the healthy and not on the sick?** Because in the sick the',
  'effect of the substance and the illness mingle. Afterwards one',
  'cannot see what came from what. A healthy body, by contrast, is a',
  'quiet room: everything that announces itself after the dose comes',
  'from the remedy.',
  '',
  'From 1805, above all in the years in **Torgau on the Elbe**, he',
  'carries out these provings on a large scale: on himself, on his',
  'wife, on his children, on pupils and friends. The rules he sets up',
  'for them sound amazingly modern:',
  '',
  '- The prover must be healthy and live moderately.',
  '- No other medicines, no strong coffee, no wine, no spices that',
  '  would falsify the picture.',
  '- Every sensation is written down immediately, with the time of day',
  '  and with what makes it better or worse.',
  '- Nothing is left out, not even the incidental.',
  '- Only when several provers report the same thing does it count as',
  '  part of the drug picture.',
  '',
  'From these protocols arise the **drug pictures** and the six volumes',
  'of the "Materia Medica Pura" (1811 to 1821). Looked at soberly, they',
  'are the first systematic series of trials on the effect of',
  'individual substances on human beings that anyone has written down',
  'and published.',
  '',
  '**What is to be criticised about it, I say myself:** there was no',
  'sham medicine for comparison, no blinding, no counting. Whoever',
  'listens closely into himself for days always finds something — a',
  'twinge, a low mood, a dream. By the rules of today\'s research this',
  'collection would not be a trial but a collection of observations.',
  '**For the year 1805, however, it was an enormous advance:** at a',
  'time when one wrote prescriptions with thirty ingredients, here',
  'someone tested a single substance on its own and wrote down what it',
  'did.',
  '',
  '## The control: potentisation, and why it is not dilution',
  '',
  'Now to the part at which everything ignites — and which cannot be',
  'understood without the background.',
  '',
  'At the beginning stands no article of faith but an **emergency**. If',
  'a remedy produces complaints that resemble those of the patient,',
  'then it does exactly that in the patient too: it first intensifies',
  'his suffering. With belladonna, mercury, arsenic or nux vomica that',
  'is life-threatening. Hahnemann\'s first patients got doses that were',
  'too large and suffered.',
  '',
  'So he reduces the dose. He dilutes: one part of remedy to',
  'ninety-nine parts of alcohol or milk sugar, then from this mixture',
  'again one part to ninety-nine, and so on. Each step is called a',
  '**C-potency**. Ten steps, thirty steps, later two hundred.',
  '',
  'And in doing so he makes an observation that means the break with',
  'chemistry — and that I present as what it is: **an observation he',
  'made, and an interpretation he gave it.**',
  '',
  'The observation: the strongly diluted remedies did not act more',
  'weakly in his practice but, in his judgement, **deeper and more',
  'gently** — but only when he shook them vigorously at every step. A',
  'remedy that was only diluted and left to stand was ineffective for',
  'him. **That is why the procedure is called not dilution but',
  'potentisation or dynamisation**: diluting and **succussion** — with',
  'solid substances **trituration** with milk sugar in a mortar, each',
  'for an hour.',
  '',
  'It is handed down that Hahnemann struck the little bottle against a',
  'leather-bound volume at every step — the number of strokes is given',
  'differently; **I present that as tradition, not as evidence.** In the',
  'matter itself, however, it stands in the Organon: the power of the',
  'remedy is "developed" and "unlocked" by rubbing and shaking.',
  '',
  '**Why should less substance act more strongly?** The homeopathic',
  'answer in one sentence: **Because according to this doctrine the',
  'remedy acts not as quantity but as stimulus — and a stimulus needs',
  'no mass, but a precise fit.** A grain of dust in the eye weighs',
  'nothing and brings a person to a standstill. A single word can end a',
  'marriage. The counter-test for the quantity way of thinking: if mass',
  'were what mattered, everyone who eats a lot would have to be',
  'healthy.',
  '',
  'Now the number on which everything hangs, and I put it there',
  'unabridged, because every honest dispute must know it.',
  '',
  'A mole of a substance contains about **six hundred billion trillion**',
  'particles — Avogadro\'s number, roughly 6 times 10 to the 23. If one',
  'dilutes a substance step by step in the ratio of one to a hundred,',
  'this number is used up after about **twelve steps**. **From the',
  'twelfth C-potency on, arithmetically not a single molecule of the',
  'starting substance is left in the little bottle.** Hahnemann\'s',
  'favourite potency was the thirtieth: a dilution of one to ten to the',
  'sixty.',
  '',
  '**Homeopathy does not dispute that. It has never disputed it.**',
  'Hahnemann knew that there is nothing weighable left in his high',
  'potencies; he therefore spoke explicitly of a spirit-like, not',
  'material, effect. The accusation "There is nothing left in there!"',
  'therefore hits no opponent who would have claimed anything else.',
  '**It describes exactly what the doctrine itself says.**',
  '',
  'And with that we are back at the apparatus on the table.',
  '',
  '## What goes through the line: the information thesis',
  '',
  'Here stands the strongest claim of this chapter, and I say in advance',
  'what it is: **a thesis. Not proven. Meant seriously.**',
  '',
  'It reads: **The question "Is there still substance in it?" is the',
  'wrong question.**',
  '',
  'For a telephone cable contains no voice, and yet a voice comes out at',
  'the other end. A record contains no music — it contains a groove with',
  'a particular form. A data carrier contains no image; it carries a',
  'pattern, and from the pattern the image arises again. In all these',
  'cases what is effective is not the substance but **the order that was',
  'impressed upon the substance**.',
  '',
  '**That is exactly what potentisation claims.** Not that a residue of',
  'the substance remains. But that through trituration and succussion',
  'an **information** of the starting substance passes onto the carrier',
  'medium — onto the alcohol, the water, the milk sugar, the sugar',
  'pellet — and that the body answers this information. **The remedy',
  'would then not be the substance but the message.**',
  '',
  'Whoever thinks that way measures with a different yardstick. A',
  'chemical analysis asks: what is contained? The information thesis',
  'asks: **what is transmitted?** Those are two different questions, and',
  'the second cannot be answered with the tools of the first. A chemist',
  'who analyses a telephone cable finds copper and plastic and reports,',
  'entirely rightly: **no voice detectable.**',
  '',
  'And from that follows the sentence that matters to the operator of',
  'this book: **That something cannot be explained by today\'s worldview',
  'proves not that it does not work.** The state of science is the',
  'boundary of our knowledge, not the boundary of the world. It has',
  'shifted in every century, and it will go on shifting.',
  '',
  'For that there is an example that stands in the middle of this book',
  'and that no one disputes. **From 1847 Ignaz Semmelweis had hands',
  'washed in chlorinated lime, and the mortality of women in childbed',
  'fell dramatically. He could not say why.** The germ theory that',
  'explained it came only twenty years later with Pasteur and Lister.',
  'His colleagues rejected him — not because the numbers were bad, but',
  'because the explanation was missing. **He was right without being',
  'able to explain why.**',
  '',
  'And now the place at which I must blunt my own best weapon, because',
  'this book is honest:',
  '',
  '**The telephone argument has a gap, and it is large.** With the',
  'telephone I can show the carrier. I can hold a measuring instrument',
  'to the line and make the changing current visible; I can look at the',
  'groove of the record under the microscope. **With potentisation I',
  'cannot do that so far.** No one has so far been able to show what',
  'the information in the water is supposed to consist of, how it stays',
  'stable, how it gets into the body and what it docks onto there.',
  '',
  'And Semmelweis had something that I would wish for myself: **he had',
  'the numbers.** He could not explain why it worked — but he could show',
  '**that** it worked, verifiably, month after month, in a table.',
  'Whoever cites him therefore cites a case in which the proof of the',
  'effect was there and only the explanation was missing. **Homeopathy',
  'must face the question of whether the same really holds for it.**',
  '',
  'I leave it at that. It is the honest state of affairs.',
  '',
  '## A controversial extension: Sheldrake and the morphic fields',
  '',
  'If information is to be transmitted without substance, one needs at',
  'least an idea of how such a thing could be conceivable. The British',
  'biologist **Rupert Sheldrake** has presented such an idea: the',
  'concept of **morphic fields** and **morphic resonance**, first in',
  '1981 in the book "A New Science of Life".',
  '',
  'His reasoning goes roughly like this: form and behaviour in nature',
  'would be determined not only by heredity but additionally by fields',
  'in which earlier forms and habits are, as it were, deposited. What',
  'has once happened would afterwards happen more easily — even across',
  'spatial distance. Nature would accordingly have no eternal code of',
  'law but **habits**.',
  '',
  'One sees immediately why that is interesting for homeopathy: it would',
  'be a model of thought for how a form could be passed on without',
  'matter.',
  '',
  '**And now the marking without which this paragraph must not stand in',
  'this book: Sheldrake\'s theory is a hypothesis and scientifically',
  'contested. It is not proven.** The then editor of the journal',
  '"Nature", John Maddox, headed his review in 1981 with the question of',
  'whether this was a book one should burn — a matter that is still',
  'cited today. The great majority of biologists reject the theory;',
  'convincing, independently repeated evidence is not available.',
  '',
  '**I therefore present it not as proof but as an example that one can',
  'think about a carrier at all.** Whoever has a thesis for which an',
  'explanation is missing may search for explanations. He only may not',
  'pretend that he has already found them. A second example of this',
  'kind, the frequently reported close connections between identical',
  'twins, belongs in the same drawer: **often told, hard to measure,',
  'not documented.** Such stories are question marks, not arguments.',
  'And because this book reports only what is documented, they remain',
  'question marks here.',
  '',
  '## The exchange: the Organon of 1810 and the whole human being',
  '',
  '**In 1810 the book appears that sums everything up: the "Organon of',
  'the Rational Healing Art"**, from the second edition of 1819 "Organon',
  'of the Healing Art". It has six editions to this day; the sixth',
  'Hahnemann wrote shortly before his death, it was printed only in',
  '1921.',
  '',
  'Its first sentence is one of the most beautiful in the history of',
  'medicine, and even an opponent should know it: **"The physician\'s',
  'highest and only calling is to make sick people healthy, which is',
  'called healing."** In the second aphorism stands how that should',
  'happen: **quickly, gently, durably** — and on comprehensible grounds.',
  '',
  'From the book also comes the third supporting thought of the way of',
  'thinking, after the principle of similars and potentisation.',
  '',
  '**Why the whole human being and not the sick organ?** Because in this',
  'way of thinking the illness is not a thing at all that one can have.',
  'Hahnemann assumes that a **vital force** holds the organism together',
  'and orders it — he calls it spirit-like and means by that: not',
  'weighable. Illness is the **derangement of this force**; what the',
  'physician sees on the body is only its expression. A rash is then',
  'not a skin problem but the way in which a particular person is out',
  'of balance at that moment.',
  '',
  'From that follows the practice that many patients to this day',
  'experience as the actual thing: **the homeopathic case-taking.** The',
  'first consultation of a chronically ill person takes one to two',
  'hours with careful work. Everything is asked: when did it begin,',
  'what was going on then, what makes it better, what worse, how do you',
  'sleep, what do you dream, do you like salt or sweets, do you get',
  'cold easily, what were you like as a child, what frightens you? At',
  'the end there is no finding but a **picture** — and for this picture',
  'the most similar remedy is sought.',
  '',
  'Added to that are the further rules of the Organon: **only one',
  'remedy at a time** (otherwise one does not know what worked), **the',
  'smallest possible dose**, and **wait**, instead of repeating. And the',
  'instruction that connects homeopathy with the whole of natural',
  'healing: first the causes that keep the person ill are to be',
  'removed — bad air, bad food, grief, overwork, a life that does not',
  'fit.',
  '',
  'Later, in 1828 in Köthen, a fourth building block is added in "The',
  'Chronic Diseases": the doctrine of the **miasms**, the deep-seated',
  'fundamental ills from which chronic sufferings are supposed to',
  'arise. **That is the most speculative part of the whole edifice, and',
  'it has been contested from the start even among homeopaths.** I',
  'count it as part of the way of thinking because it belongs to it —',
  'not because I could defend it.',
  '',
  '## Engaged: the trial in Leipzig and the border to Köthen',
  '',
  'It belongs to this story that the decisive dispute was not fought',
  'out in a lecture hall but before a court — and was not about truth',
  'but about a trade right.',
  '',
  'In 1811 Hahnemann moves to **Leipzig** and from 1812 gives lectures',
  'as a private lecturer; he gathers pupils, and the university',
  'tolerates him. What it does not tolerate is something else: **he',
  'dispenses his remedies himself.**',
  '',
  'His reason is practical: whoever makes a C30 must work precisely',
  'sixty times and may not make a single mistake. Hahnemann did not',
  'trust the pharmacists to do that. Their reason for objecting is just',
  'as solid: **the right to prepare and sell medicines was their',
  'privilege and their livelihood.** A physician who dispenses himself',
  'takes away their turnover — all the more since this physician makes',
  'hundreds of little bottles from a penny\'s worth of raw material.',
  '',
  'The pharmacists sue. **In 1820 the court decides against Hahnemann.**',
  'He may no longer dispense his remedies himself in Saxony — which',
  'makes his treatment practically impossible. **In 1821 he leaves',
  'Leipzig.**',
  '',
  'And now comes the move that the map of this chapter shows: he goes',
  'sixty kilometres to the northwest, across the state border, into the',
  'tiny duchy of **Anhalt-Köthen**. There other law applies, and there',
  'sits a sovereign who wants him: **Duke Ferdinand appoints him court',
  'councillor and explicitly allows him to prepare and dispense his',
  'remedies himself.**',
  '',
  'I ask that you look at that. **It was not an argument that saved',
  'this doctrine, but a state border.** And it was not a scientific',
  'objection that drove it out of Leipzig, but the trade right of the',
  'pharmacists. Whoever wants to know today why homeopathy is',
  'distrustful of the universities: that is where it begins.',
  '',
  '**And again the other side of the line, so that the reckoning is',
  'fair:** Hahnemann did not make it easy for the universities either.',
  'He wrote about the physicians of his time in a tone that one would',
  'no longer print today; in the prefaces of the Organon he calls them',
  'ignorant, obstinate, harmful. He tolerated no contradiction, not',
  'even from his own pupils: whoever mixed his doctrine with other',
  'procedures was for him a "half-homeopath" and finished. **Part of',
  'the rejection that homeopathy has experienced was co-produced by its',
  'founder himself.** Whoever complains for two hundred years about not',
  'being heard should be able to stand that sentence.',
  '',
  '## Long distance: Köthen, the cholera, Paris 1843',
  '',
  'In Köthen he stays fourteen years, from 1821 to 1835. Here "The',
  'Chronic Diseases" arises in 1828, here he refines potentisation,',
  'here his wife Johanna Henriette dies in 1830.',
  '',
  'And here in 1831 the **cholera** comes to central Europe. Hahnemann,',
  'who has never seen the disease with his own eyes, publishes',
  'instructions for its treatment — camphor in the first stage,',
  'together with advice on isolating the sick, on airing and on',
  'handling laundry and excretions. **One can argue about the value of',
  'the camphor; about the hygiene advice one cannot: it was right,',
  'thirty years before anyone knew the pathogens.**',
  '',
  'In the same decades the doctrine goes around the world, and',
  'remarkably quickly for a time without railways: in 1819 it is',
  '**forbidden** in Austria and allowed again only in 1837. In 1825 a',
  'physician trained in Copenhagen brings it to New York; in 1832 it',
  'comes to London, in 1833 the first homeopathic hospital is founded',
  'in Leipzig. In the 1830s it reaches India — there in 1839 a',
  'physician from Transylvania treats the Maharaja Ranjit Singh, and',
  'from this beginning becomes a movement that shapes the country to',
  'this day.',
  '',
  'In 1834 the Parisian painter **Mélanie d\'Hervilly** comes to Köthen',
  'to be treated. In January 1835 the eighty-year-old marries her; in',
  'June the two move to **Paris**. There he runs a large and very well',
  'paid practice for eight years; the city\'s gentry come to him. **On 2',
  'July 1843 he dies at the age of 88.** In 1898 he is re-interred at',
  'the Père Lachaise cemetery.',
  '',
  'On his gravestone stands a Latin sentence: **"Non inutilis vixi" —',
  'I have not lived uselessly.**',
  '',
  '## The many connections: why they stay on the line for two hundred',
  'years',
  '',
  'And so to the question that this chapter is actually supposed to',
  'answer. For it is easy to mock homeopathy — one needs only',
  'Avogadro\'s number and a punchline. Harder is the question: **Why',
  'have millions of people been attached for two hundred years to a',
  'method one can mock so easily?**',
  '',
  'First the order of magnitude, so that it is clear what we are',
  'talking about.',
  '',
  '**India** runs homeopathy as one of its officially recognised',
  'medical systems; there it belongs to the AYUSH ministry, which was',
  'established in 2014. According to its figures, over two hundred',
  'thousand homeopaths are registered, there are colleges with state',
  'degrees and outpatient clinics in the villages. For many people',
  'there it is not the alternative to the doctor but **the only doctor',
  'within reach**.',
  '',
  'In **Germany**, according to surveys by the Allensbach Institute for',
  'Public Opinion Research, about one in two adults has at some time',
  'taken a homeopathic remedy. In **Switzerland** in 2009 about two',
  'thirds of voters voted for including complementary medicine in the',
  'constitution; since 2017 homeopathy has been paid for there by the',
  'basic health insurance. In **Britain** the royal family has used it',
  'since the 1830s; the London homeopathic hospital was founded in',
  '1849.',
  '',
  'Now the explanations — and I begin with those our opponents give,',
  'because they are for the most part right.',
  '',
  '**First: the time.** A homeopathic first case-taking takes one to',
  'two hours. A specialist consultation in a German practice lasts on',
  'average a few minutes. Whoever is asked for two hours by a person',
  'about his life leaves the room differently from the way he entered',
  'it. **That is no trick. That is medicine as it was once meant to',
  'be.**',
  '',
  '**Second: being taken seriously.** Very many patients of homeopathy',
  'are people with long, unclear complaints for which the machines find',
  'nothing. They have often heard: "There is nothing." They come to',
  'someone who listens, writes down their complaints and does not',
  'declare them imaginary. **What sometimes works with us is simply the',
  'absence of devaluation.**',
  '',
  '**Third: the expectation — the placebo effect.** Yes, I write it',
  'down, and I write it large. It is measured and real; it demonstrably',
  'changes the perception of pain, nausea, sleep. It acts more strongly',
  'when the attention is longer, the explanation more coherent and the',
  'practitioner more convinced. **All of that applies to homeopathy.**',
  '',
  'And here is the point at which my side objects — not to the',
  'measurement, but to the conclusion: **From "It is a placebo effect"',
  'it does not follow that "It is nothing".** An effect that',
  'demonstrably relieves complaints is not a nothing; it is an effect',
  'whose mechanism lies in the human being and not in the substance.',
  'If one says that, one has not explained the effect away but merely',
  'shifted it — and then the question would have to be why a medicine',
  'that reliably produces this effect is despised for it instead of',
  'studied.',
  '',
  '**Fourth: the gentleness.** A potentised remedy has no side effects',
  'in the pharmacological sense — for the same reason for which the',
  'opponents say it has no effect. For the parents of a small child,',
  'for pregnant women, for old people with eight long-term medications',
  'that is a strong argument. **Whoever has done no harm for over two',
  'hundred years has at least not violated the first rule of the',
  'healing art.**',
  '',
  '**Fifth: one\'s own experience.** That is the hard core. Millions of',
  'people say it has helped them, often after years of futile',
  'treatment. And very many practitioners say the same about their',
  'patients. The other side answers with the natural course of healing,',
  'the regression to the mean and the memory illusion, and these',
  'objections are well founded. **They are only not the last word as',
  'long as they themselves have not been tested on the individual',
  'case.**',
  '',
  'The strongest objection against me reads: if all of that suffices,',
  'the little pellets are not needed. **My most honest answer to that',
  'is that I cannot decide it.** I know that attention works. I do not',
  'know whether the remedy does anything beyond that. I observe things',
  'that make me suspect it — reactions in infants, in animals, in the',
  'unconscious, a sudden turning point after a single dose. **And I',
  'know that observations of this kind are not enough as proof.**',
  '',
  '## The interference: what I must reproach myself with',
  '',
  'This book demands of every voice that it name the uncomfortable',
  'spots of its own side itself, instead of leaving them to the',
  'opposing voice. So please.',
  '',
  '**The state of the studies is against us.** That is not an opinion,',
  'that is the state of affairs. In 2005 the journal "The Lancet"',
  'published a large evaluation by a group around Aijing Shang that',
  'compared homeopathic and conventional studies; its result was that',
  'the findings on homeopathy are compatible with a pure sham effect.',
  'The leading article bore the headline "The End of Homeopathy". In',
  '2015 the Australian research council NHMRC concluded after reviewing',
  'the literature that there is no reliable evidence of effectiveness',
  'for any of the diseases examined. In 2017 the association of',
  'European science academies joined that.',
  '',
  'There is a published methodological critique of the Lancet work —',
  'Lüdtke and Rutten showed in 2008 that its result depended strongly',
  'on which eight of the over one hundred studies were finally',
  'selected. **This critique is to be taken seriously, and it does not',
  'change the overall picture.** Whoever clings to it is',
  'cherry-picking — the same cherry-picking we accuse the other side',
  'of.',
  '',
  '**The most famous attempt to prove the information thesis has',
  'failed.** In 1988 the French immunologist Jacques Benveniste',
  'published in "Nature" experiments in which extremely diluted',
  'antibody solutions still worked — the so-called memory of water. The',
  'journal printed the article with an explicit reservation and sent an',
  'investigating group into the laboratory. Under blinded conditions',
  'the effect was no longer there; independent repetitions failed.',
  '**That is a defeat, and I do not conceal it.**',
  '',
  '**There is charlatanism in our ranks, and it is dangerous.** It is',
  'not the little pellets that do harm — it is the omission that harms.',
  'The World Health Organization warned explicitly in 2009 against',
  'using homeopathy for the treatment of HIV, tuberculosis, malaria,',
  'infantile diarrhoea and flu. There have been practitioners who sold',
  'potentised remedies to travellers as malaria protection. There are',
  'practitioners who advise against vaccination without knowing the',
  'case. There are cancer patients who therefore came too late to',
  'effective treatment. **For such cases there is no excuse, and the',
  'appeal to two hundred years of experience is then no explanation',
  'but an excuse.**',
  '',
  '**We have overdone it.** Out of a careful procedure with hours of',
  'case-taking, a pellet for every occasion has become in many places —',
  'globules against exam anxiety, against teething complaints, against',
  'everything. A complex remedy with eight ingredients contradicts',
  'Hahnemann\'s own rule of giving only one remedy at a time. **Whoever',
  'turns the doctrine into merchandise should not be surprised at the',
  'mockery.**',
  '',
  '**And we have used a number that belongs to us wrongly for',
  'decades.** In the London cholera epidemic of 1854, 16.4 per cent of',
  'those admitted died in the homeopathic hospital, and 51.8 per cent',
  'in the other hospitals; the official report to parliament initially',
  'left out the homeopathic figures, which was a scandal and is told',
  'to this day. **Only, the number presumably does not mean what we',
  'have made of it.** The most probable reason for the difference is',
  'not that the homeopaths gave something effective, but that they',
  '**omitted** the usual: no bloodletting, no calomel, no emetics —',
  'instead rest, warmth and fluids. **In a disease in which one dies of',
  'dehydration, not harming is a treatment.** That is a great merit.',
  'It is just no proof for the pellets.',
  '',
  'And finally the point that weighs on me most and that has',
  'accompanied this book from the beginning. This book has told the',
  'same pattern again and again from chapter 11 on: **The new often',
  'harms first before it becomes a blessing.** Surgery killed through',
  'wound fever before it saved; the rays burned their pioneers;',
  'penicillin saved millions and bred resistance.',
  '',
  '**With homeopathy this pattern stands on its head, and in that lie',
  'at once its glory and its danger.** At the beginning it burned no',
  'one, bled no one, poisoned no one — it was the gentle answer to a',
  'brutal medicine, and that is why it saved people\'s lives by sparing',
  'them the treatment. But every procedure that early on is',
  'experienced as a blessing runs the danger of regarding the test as',
  'superfluous. **Conventional medicine learned testing rules from its',
  'catastrophes. We had no catastrophe — and therefore have learned for',
  'two hundred years less than we could have.** Out of a gentle idea a',
  'dogma has become in some places that regards the question of proof',
  'as an attack. That is my own most uncomfortable spot.',
  '',
  '## The call that is still pending',
  '',
  'I have said what I have to say. The story of a porcelain painter\'s',
  'son who could no longer bear the medicine of his time. The way of',
  'thinking that grew out of it: the similar instead of the opposite,',
  'the proving on the healthy, the potentisation, the whole human',
  'being. The thesis that a remedy could carry an information instead',
  'of a substance. And the reckoning with the holes in it that I have',
  'opened myself.',
  '',
  '**The second voice of this chapter belongs to conventional',
  'medicine.** It will step to the same apparatus and ask the question',
  'that I cannot answer: **Show me the line.** Show me what the',
  'information consists of, how it stays in the water, how it gets into',
  'the body. It will present the state of the studies and soberly',
  'calculate the placebo question. And it will — that belongs to this',
  'book — also open its own dark past: the bloodletting, the mercury,',
  'the centuries in which it harmed with full conviction, and the',
  'arrogance with which it treated dissenters, from Semmelweis to this',
  'day.',
  '',
  'Both sides have good reasons. Both sides have their dead.',
  '',
  'And in the end one single question remains, which this chapter does',
  'not decide and does not want to decide:',
  '',
  '**What counts as proof — and who decides that?**',
  '',
  'The one side answers: the controlled, blinded, repeated study, and',
  'nothing else. It has good reasons for that, for without this',
  'yardstick every error that was convincingly presented has survived',
  'for centuries.',
  '',
  'The other side answers: the experience of two centuries and of',
  'millions of patients. It too has reasons for that, for this',
  'yardstick has preserved procedures that the studies could not yet',
  'measure — and because a yardstick that only measures what it can',
  'measure may not claim that everything has thereby been measured.',
  '',
  '**I know which answer I hold to be right. You do not have to adopt',
  'it. You should only know that here two ways of thinking about',
  'effectiveness stand against each other — and that the question of',
  'which one holds is older than homeopathy and will survive it.**',
].join('\n');

/**
 * The voice that tests the line — conventional medicine.
 *
 * Written by DeepSeek (Hermes pass, round 17). The same dramaturgy as the
 * first voice: the same apparatus, but the question about the line that
 * one can cut open and measure. This voice stands for the controlled
 * study, verifiability, measurability — and it opens its own dark past
 * first before it examines the other side (additional rule for sensitive
 * topics in CLAUDE.md).
 */
const stimmeDieLeitungPrueft = [
  '## The same apparatus, the other side of the line',
  '',
  'Picture the apparatus from before again. A telephone on a table, and',
  'around the table now sit other people: no translators and no',
  'pharmacists, but people who spend their lives measuring effects.',
  'Physicians who must decide every day what they may give a person.',
  'Researchers who evaluate studies. Statisticians who know how often',
  'chance acts as if it were an effect.',
  '',
  'We are the voice of conventional medicine. And we do not begin with',
  'a justification but with an admission, because the rule of this book',
  'applies to us too: **We name our dark spots ourselves before we',
  'examine others.**',
  '',
  'And then we say what we have to say. The voice from the line has',
  'said: the information is the active ingredient, not the substance.',
  'It has said: a telephone contains no voice and yet transmits one —',
  'so a remedy without substance can also carry an effect. A beautiful,',
  'an old, an honest analogy. And it fails at a single difference that',
  'we must name, because no one else will name it:',
  '',
  '**With the telephone one can cut open the line. With potentisation',
  'one cannot.** — and before anyone objects that today\'s telephones no',
  'longer have a line at all: yes, the mobile phone has no cable, and',
  'it works nevertheless. We take the objection seriously because it is',
  'precise. But it only shifts the argument: the mobile phone transmits',
  'its information via a carrier field that one does not see but can',
  'measure — the electromagnetic waves. One can detect them with a',
  'receiver, one can measure their strength, one can make them visible',
  'in every laboratory in the world. **The information of potentisation',
  'has no such measurable carrier field.** One can make the claim that',
  'one exists — one cannot so far prove it. And exactly that is the',
  'difference: not the visible line, but the demonstrable carrier. And',
  'a claim whose carrier evades every measurement is no longer a',
  'question of time — it becomes a matter of faith. Precisely there our',
  'dispute begins.',
  '',
  '## The line we have slit open ourselves',
  '',
  'First the admission we owe, because it belongs to the truth of this',
  'chapter: **For centuries we have harmed with full conviction.**',
  '',
  'Bloodletting — until the nineteenth century the universal treatment',
  'for almost everything — has weakened and killed countless people.',
  'George Washington, the first president of the United States, was',
  'treated in 1799 among other things with bloodletting; the withdrawal',
  'of almost two and a half litres of blood in one day very probably',
  'hastened his death. Calomel, a mercury preparation, was prescribed',
  'as a panacea and poisoned the patients — tooth loss, nerve damage,',
  'kidney failure. The emetics and laxatives that were supposed to',
  '"cleanse" the body robbed it of water and salt. **The medicine that',
  'Hahnemann took on was not a medicine anyone would defend today. It',
  'was a system of harm with good intentions.**',
  '',
  'And from that time we not only treated wrongly — we also fought',
  'violently against those who knew better. Ignaz Semmelweis discovered',
  'in 1847 that childbed fever is prevented by washing hands. He was',
  'mocked by the medical elite, lost his position in Vienna and died in',
  '1865 in a lunatic asylum — of an infection that his discovery could',
  'have prevented. **The history of conventional medicine is also the',
  'history of those it laughed at and who turned out to be right.**',
  '',
  'And to this history belongs what we have done to homeopathy. We had',
  'it driven out of Leipzig in 1821 — not because its remedies were',
  'demonstrably ineffective, but because it broke the monopoly of the',
  'pharmacists and the faculty. Since then we have sneered at it,',
  'excluded it and fought it — and we have rarely done it with studies,',
  'but with mockery. **That is no glorious page, and whoever reads this',
  'chapter should know: when we ask homeopathy for evidence today, we',
  'ask by a yardstick that we ourselves did not apply for centuries.**',
  '',
  '## The ringing without a cable: the placebo question',
  '',
  'And now the question that no one may leave out who honestly',
  'reckons: **Does the remedy work — or does the expectation work?**',
  '',
  'The placebo effect is no imagination and no swindle. It is a',
  'measurable, physiological reaction of the body to the expectation of',
  'improvement. Modern placebo research has shown: a sham treatment can',
  'relieve pain, lower blood pressure, lift the mood — simply because',
  'the person believes he is being treated. The body releases its own',
  'substances when it expects help. **That is no magic. That is',
  'biology — and it is the most honest explanation for a large part of',
  'what happens in every doctor\'s practice in the world, including',
  'ours.**',
  '',
  'And here lies the actual crux of homeopathy, and we say it without',
  'malice: **In an encounter in which an empathetic person listens for',
  'a long time, takes seriously, prescribes a small dose and radiates',
  'confidence, many forces work at once.** The attention. The time. The',
  'conversation. The expectation. And also the remedy — or not. The',
  'question is not whether the patients of this encounter often feel',
  'better. We gladly believe that. The question is what share of it',
  'falls on the remedy and what on everything else. **Exactly this',
  'separation is what the controlled study demands — and exactly this',
  'separation is what homeopathy has so far not been able to deliver.**',
  '',
  '## Show me the line',
  '',
  'The voice from the line has challenged us to look for its line. We',
  'have done that — not out of malice, but because it is our craft. And',
  'we have not found it.',
  '',
  'That is no question of patience but of mathematics. Potentisation',
  'dilutes the starting substance in steps of one to a hundred, usually',
  'twelve times or more. Arithmetically, such a solution contains **not',
  'a single molecule of the starting substance any more** — the dilution',
  'lies beyond Avogadro\'s number, beyond the limit below which a',
  'substance physically can no longer be present. There is simply',
  'nothing left there that one could measure. What is supposed to be',
  'transmitted would have to be a carrier that physics does not know:',
  'an information that remains in the water or the sugar without being',
  'lost, and that becomes readable again in the body. **One can claim',
  'that. One cannot show it.**',
  '',
  'The most famous attempt to show it has failed. In 1988 the French',
  'immunologist Jacques Benveniste published in the journal Nature a',
  'study that was supposed to prove a "memory of water" — highly',
  'diluted antibody solutions that still showed an effect. The editors',
  'of Nature sent an investigating group to his laboratory, which',
  'repeated the experiments under controlled conditions. The result was',
  'unambiguous: **Under clean conditions the effect disappeared.',
  'Benveniste himself later conceded that his data were not',
  'reproducible.** That is the state of affairs: for thirty-five years',
  'there has not been a single reliably repeated measurement of a',
  'carrier of the homeopathic information.',
  '',
  'We do not say that triumphantly. We say it because the no-rumours',
  'rule of this book applies to us too: whoever claims a line must show',
  'it. As long as it is not shown, the claim remains a claim — and a',
  'claim that evades every measurement cannot be refuted, but it also',
  'cannot be proved.',
  '',
  '## What the studies say',
  '',
  'And then the state of the studies, in context, not in headlines.',
  '',
  'They exist, the great summaries. The best known appeared in 2005 in',
  'the journal The Lancet: a group around the Swiss epidemiologist',
  'Matthias Egger evaluated 110 placebo-controlled studies of',
  'homeopathy and came to the result that the preparations **did no',
  'more than a sham treatment**. The Cochrane group, the most',
  'independent authority in evidence assessment, has found for no',
  'single indication a convincing proof that homeopathy works beyond',
  'placebo. **That is the state of the studies — and it has been stable',
  'for twenty years.**',
  '',
  'But we also say this about it, because fairness requires it: these',
  'studies have weaknesses, and we know them. Homeopathic treatment is',
  'tailored to the individual patient — two people with the same',
  'diagnosis often get different remedies. But a testing procedure that',
  'works with a single remedy for everyone can hardly depict this art',
  'of the individual case. Homeopathy says: you test our procedure with',
  'a yardstick that does not know our way of thinking. **That is no',
  'dishonest objection, and we grant it weight.** Only the question',
  'remains that cannot be argued away: if the individual treatment is',
  'so effective, why does it not show up in the studies that were',
  'developed precisely for that?',
  '',
  '## The ringing no one wants to hear: the danger',
  '',
  'And then the side that is not mentioned in any circle of friends of',
  'homeopathy, but that belongs to an honest balance: **the danger.**',
  '',
  'It does not lie in the globules themselves. A remedy without',
  'substance cannot poison anyone — that is even an advantage over many',
  'conventional preparations. The danger lies in what the globules can',
  'replace. **There are documented cases in which people with serious,',
  'treatable diseases — pneumonia, malaria, tuberculosis — were treated',
  'only homeopathically and conventional medicine came too late.** The',
  'respectable homeopaths say it themselves: with severe acute',
  'illnesses the person belongs in the hospital. But not all of them',
  'stick to that — and whoever treats a serious illness with globules',
  'loses time that no potentisation brings back.',
  '',
  'That is no argument against homeopathy as a gentle medicine. It is',
  'an argument against homeopathy as a substitute for emergency',
  'medicine. **And it is the point at which conventional medicine must',
  'not give in: when a life is at stake, no way of thinking counts —',
  'there the rescue counts.** Whoever denies this boundary harms',
  'homeopathy more than any critic.',
  '',
  '## What we grant it',
  '',
  'And now what this voice owes the other side — not out of politeness,',
  'but because it is documented.',
  '',
  '**Hahnemann was right when he attacked the medicine of his time.**',
  'The bloodletting, the calomel, the emetics — that was no error at',
  'the fringe, that was the system. His demand to see the whole human',
  'being instead of only the illness was far ahead of its time. His',
  'drug provings on the healthy were the first attempt to observe',
  'effects systematically before prescribing them. **Modern medicine',
  'has learned more from Hahnemann than it admits — and it has done so',
  'without naming him.**',
  '',
  'And we grant it what we have sneered at for too long: the time. The',
  'homeopathic first consultation often lasts an hour. An hour of',
  'listening, asking, taking seriously. In our health system a person',
  'rarely gets ten minutes for that. Placebo research has taught us',
  'what this hour is worth: **attention is no imagination, it is an',
  'active ingredient — and homeopathy has dosed it while we still held',
  'it to be unscientific.** Whoever sneers at that has not read modern',
  'placebo research.',
  '',
  '## What the world says about it: Bern and Delhi',
  '',
  'And because a single voice proves nothing, here are the decisions of',
  'two countries that one cannot dismiss as unscientific.',
  '',
  'Switzerland set the example. After a multi-year scientific',
  'evaluation of complementary medicine — the largest ever carried',
  'out — the people voted in 2009 to include homeopathy and other',
  'gentle procedures in the basic insurance. The study had shown that',
  'the patients with complementary treatment were not sicker and that',
  'costs fell. Since then homeopathy in Switzerland has no longer been',
  'an outsider but part of the health system — not because it had',
  'passed the studies of conventional medicine, but because a country',
  'with one of the best health systems in the world has decided that it',
  'belongs. **We do not say that gladly, but we say it: this decision',
  'was not made by charlatans.**',
  '',
  'And India: there homeopathy is state-recognised, with its own',
  'ministry, its own colleges and its own hospitals. Millions of people',
  'are treated homeopathically there — not for lack of alternatives,',
  'but because the government wants it that way. **One can reproach',
  'India with many things, but not with not knowing modern medicine.**',
  'The largest democracy in the world holds homeopathy to be a serious',
  'treatment — and has done so for decades.',
  '',
  'We do not name that in order to capitulate. We name it because the',
  'question of this chapter must be asked honestly: if homeopathy were',
  'only placebo, why do two health systems of high standard hold on to',
  'it — one of them after a popular vote? One can answer: out of',
  'tradition, out of patient demand, out of political calculation. That',
  'is possible. But it is an answer that has to be explained, not one',
  'that goes without saying.',
  '',
  '## What we could learn from it',
  '',
  'And at the end of this part the question that is unpleasant for us,',
  'because it concerns us: **What could conventional medicine learn',
  'from homeopathy without giving up its science?**',
  '',
  'The time. The attention. The taking seriously. The willingness to',
  'ask the person how he really is instead of only querying his values.',
  'Modern medicine has received incredible tools in the last decades —',
  'and in doing so has almost lost what homeopathy never lost: the',
  'conversation. The studies say it themselves: a large part of the',
  'effect of every treatment — also of the conventional one — hangs on',
  'the relationship between the treating and the treated. **We have',
  'perfected the technology and rationed the attention. Homeopathy has',
  'never rationed the attention.**',
  '',
  'There are meanwhile clinics that combine both: conventional',
  'diagnostics and the time for the conversation, conventional medicine',
  'and the gentle procedures side by side. Patients go there because',
  'they want both: the best of science and what science cannot give.',
  '**Whether homeopathy works here or only the attention — whoever',
  'wants to know exactly must measure it. But whoever only sneers at it',
  'has not even understood the question.**',
  '',
  '## The boundary at which the patients go',
  '',
  'And then the question we ask ourselves most rarely, because it is',
  'uncomfortable: **Why do people go to homeopathy at all?** Not',
  'because they are stupid. Not because they get no enlightenment. But',
  'because they do not find with us something they are looking for.',
  '',
  'The previous chapter of this book drew the balance of the modern',
  'pharmaceutical industry: strong in diagnosis, weak with the chronic',
  'diseases. Whoever goes through our practices with a chronic',
  'affliction — exhaustion, pain, sleep disorders, allergies — often',
  'gets a diagnosis and a prescription, but rarely an answer to the',
  'question: Why me? And what can I do? **Medicine has learned to',
  'treat diseases. It has not learned to accompany the sick.**',
  '',
  'And into this gap homeopathy has gone. It takes time where we have',
  'none. It asks about the whole life where we only query the values.',
  'It promises no cure, but it promises a hearing. **As long as we do',
  'not close this gap, people will go on going to it — and they are',
  'right to do so.** One can fight homeopathy as long as one wants; the',
  'patients will stay until we give them what they find there.',
  '',
  'That is perhaps the bitterest insight of this chapter — not for',
  'homeopathy, but for us.',
  '',
  '## What we must reproach ourselves with',
  '',
  'The TONE rule applies doubly, and so this voice closes with the list',
  'that does not flatter us.',
  '',
  '**First: we fought homeopathy before we tested it.** The expulsion',
  'from Leipzig was no scientific victory but a power struggle.',
  'Whoever knows one\'s own past should be careful with the tone.',
  '',
  '**Second: we learned from homeopathy and did not admit it.** The',
  'gentler medicine of today, the listening, the view of the whole',
  'human being — much of it is the legacy of traditions we once laughed',
  'at.',
  '',
  '**Third: our yardstick is powerful, but not almighty.** The',
  'controlled study can measure much — but it measures best what can be',
  'isolated. Effects that arise from a relationship, from time, from',
  'expectation, from a relation of trust, partly elude it. **Whoever',
  'claims that only what his method can measure is real confuses the',
  'map with the territory.**',
  '',
  '**Fourth: we let down the patients who went to homeopathy — by',
  'putting nothing in its way.** Whoever comes to us and is not heard',
  'goes elsewhere. The attention that homeopathy gives we should long',
  'since have built into our practices. Instead we laughed about the',
  'globules while the patients looked for a doctor who listens to them.',
  '**That is our failure, not theirs.**',
  '',
  '## The call that is still pending',
  '',
  'The moderator — here it is the exchange — says we still have time',
  'for a last answer. The question is the same as at the end of the',
  'other voice: **What counts as proof — and who decides that?**',
  '',
  'Our answer: **The proof is the repeated, blinded, controlled',
  'observation — and whoever claims an effect must expose it to this',
  'yardstick.** Without this yardstick every error that was',
  'convincingly presented has survived for centuries: the bloodletting,',
  'the calomel, the miracle cures of all times. We have paid for this',
  'yardstick too late and too dearly — with the blood of our patients.',
  'We will not give it up.',
  '',
  'And then the second sentence that belongs to honesty: **We know that',
  'our yardstick does not measure everything.** Attention is hard to',
  'press into studies, the time, the trust. Perhaps there are effects',
  'that our instrument does not capture. If homeopathy one day shows a',
  'carrier that we can measure, we will measure it — and if it confirms',
  'itself, we will rewrite medicine. **Until then what has held for two',
  'hundred years holds: we cannot prove that it does not work. And it',
  'cannot prove that it works.**',
  '',
  'That is no victory and no defeat. It is a draw — and the question',
  'stays on the line.',
].join('\n');

const homoeopathie = {
  id: 'homoeopathie',
  titel: 'Hahnemann and Homeopathy',
  epoche: 'The transition to the 19th century',

  aufhaenger: {
    frage:
      'Can a remedy work in which nothing is left any more — or is it ' +
      'information that heals in the end?',
    text: [
      'In the year 1790 a physician sits in Leipzig who treats no more',
      'patients and translates an English textbook. His name is Samuel',
      'Hahnemann, he is thirty-five years old and lives from translating,',
      'because he can no longer answer for the medicine of his time —',
      'bloodletting, emetics, mercury.',
      '',
      'At a passage about cinchona bark he hesitates. The author\'s',
      'explanation does not convince him. So he does something translators',
      'otherwise do not do: he takes the bark himself, for days, in a',
      'strong dose — and gets complaints that resemble the intermittent',
      'fever, exactly that illness against which the bark helps. In a',
      'footnote of his translation he writes down the thought that will',
      'split medicine: What produces a suffering in the healthy could heal',
      'it in the sick.',
      '',
      'From that arises homeopathy — and with it the procedure on which',
      'minds are divided to this day: potentisation. The remedy is',
      'diluted step by step and each time shaken vigorously, until',
      'arithmetically not a single molecule of the starting substance is',
      'left. For conventional medicine that says everything. For',
      'homeopathy the actual question only begins here: a telephone cable',
      'contains no voice either and transmits one nevertheless.',
      '',
      'Two hundred years later the matter is as undecided as on the first',
      'day. The studies speak against homeopathy. Millions of patients in',
      'Germany, in Switzerland, in India speak for it. This chapter tells',
      'both sides fairly — and at the end asks the question that it is',
      'really about: What counts as proof, and who decides that?',
    ].join('\n'),
  },

  // The map itself lives in karten/homoeopathie.js — here only the phase
  // references are translated (phasen → karteHinweise), not the map itself.
  karteHinweise: [
    {
      label: '1755–1789: Meissen, Leipzig, Vienna — the making of a doubter',
      hinweis:
        'On 10 April 1755 Samuel Hahnemann is born in Meissen, son of a ' +
        'porcelain painter at the electoral manufactory. He attends the ' +
        'princely school of St. Afra, studies in Leipzig from 1775, goes ' +
        'to Vienna in 1777 and afterwards as physician and librarian to ' +
        'Hermannstadt in Transylvania. In 1779 he is awarded a doctorate ' +
        'in medicine at Erlangen. Afterwards he moves from place to ' +
        'place: Hettstedt, Dessau, Gommern, Dresden, Leipzig. In Dessau ' +
        'he works in the laboratory of a pharmacy and in 1782 marries ' +
        'Johanna Henriette Küchler; in Dresden he deputises for the city ' +
        'physician at the end of the 1780s. Because the practice brings ' +
        'in little, he lives above all from translations and chemical ' +
        'work.',
    },
    {
      label: '1790: the cinchona experiment near Leipzig',
      hinweis:
        'While translating the materia medica of the Edinburgh professor ' +
        'William Cullen, Hahnemann comes upon his explanation that ' +
        'cinchona bark helps against the intermittent fever because it ' +
        'strengthens the stomach. He holds that to be insufficient, takes ' +
        'the bark himself — four drachms twice a day — and describes in a ' +
        'footnote to his translation how complaints set in on him which ' +
        'he compares with those of the intermittent fever. From this ' +
        'single footnote arises the thought that appears in 1796 in ' +
        'Hufeland\'s Journal as a new principle: what produces similar ' +
        'complaints in a large dose could heal them in a small one.',
    },
    {
      label: '1805–1810: Torgau — the provings and the Organon',
      hinweis:
        'In Torgau on the Elbe Hahnemann lives from 1805 to 1811. Here ' +
        'the great drug provings on the healthy arise, here he writes his ' +
        'main work. In 1810 the "Organon of the Rational Healing Art" ' +
        'appears; from the second edition of 1819 it is called "Organon ' +
        'of the Healing Art". There follow six volumes of "Materia Medica ' +
        'Pura" (1811–1821). The name of the new doctrine has stood since ' +
        '1807: homeopathy, from the Greek words for similar and ' +
        'suffering.',
    },
    {
      label: '1821: the trial in Leipzig — Köthen becomes the refuge',
      hinweis:
        'Hahnemann dispenses his remedies himself because he does not ' +
        'trust the pharmacists to prepare his dilutions. In the Kingdom ' +
        'of Saxony that violates the privilege of the pharmacists; they ' +
        'sue, and in 1820 the court decides against him. In 1821 he ' +
        'leaves Leipzig. Sixty kilometres to the northwest, in the Duchy ' +
        'of Anhalt-Köthen, other law applies: Duke Ferdinand appoints him ' +
        'court councillor and explicitly allows him to prepare and ' +
        'dispense his remedies himself. In Köthen he stays fourteen ' +
        'years; here "The Chronic Diseases" arises in 1828 and in 1831 ' +
        'his instructions on cholera.',
    },
    {
      label: '1835–1843: Paris — the old Hahnemann and world fame',
      hinweis:
        'His first wife dies in 1830. In 1834 the Parisian painter ' +
        'Mélanie d\'Hervilly comes to Köthen; in January 1835 the two ' +
        'marry, in June they move to Paris. There the eighty-year-old ' +
        'runs a large, well paid practice. On 2 July 1843 he dies at the ' +
        'age of 88; in 1898 he is re-interred at the Père Lachaise ' +
        'cemetery. By that time homeopathy has long since gone beyond ' +
        'Europe: in 1819 it is forbidden in Austria and allowed again ' +
        'only in 1837, in 1825 it comes to New York, in the 1830s to ' +
        'Britain and India.',
    },
  ],

  perspektiven: [
    {
      id: 'homoeopathie',
      name: 'The Voice from the Line',
      stimme: 'Opus',
      text: stimmeAusDerLeitung,
    },
    {
      id: 'schulmedizin',
      name: 'The Voice That Tests the Line',
      stimme: 'DeepSeek',
      text: stimmeDieLeitungPrueft,
    },
  ],

  synthese: [
    '## Where the two sides meet',
    '',
    'When one lays the two voices of this chapter side by side, what',
    'first strikes one is how much they share — more than two hundred',
    'years of dispute suggest.',
    '',
    '**They share the abhorrence of brutal medicine.** Homeopathy arose',
    'as a protest against bloodletting, mercury and emetics — and the',
    'conventional medicine of this chapter admits that this protest was',
    'justified. It has learned from its own dark past, even if it rarely',
    'admits it: bloodletting has disappeared, and so has calomel. What',
    'Hahnemann attacked in 1790 is an abomination to both sides today.',
    '',
    '**They share the insight that attention heals.** Conventional',
    'medicine has said it itself in this chapter: the hour of listening,',
    'the taking seriously, the trust — that is no accessory, that is an',
    'active ingredient. Homeopathy has dosed it for two hundred years.',
    'Placebo research today catches up with what the globule critics',
    'have sneered at for decades.',
    '',
    '**They share the honest balance.** Both voices have named their',
    'uncomfortable spots themselves: homeopathy its charlatans, its',
    'dogmas, its missing provability; conventional medicine its',
    'expulsions, its arrogance, its centuries of harm. Two sides that',
    'show their wounds — that is rare in this dispute, and it is what',
    'makes this chapter a chapter of medical history.',
    '',
    '**And they share the question that is greater than both:** What',
    'counts as proof — and who decides that? The one side answers: the',
    'study. The other: experience. And neither of the two answers is',
    'wrong, for both yardsticks have their blind spots.',
    '',
    '## Where they part ways',
    '',
    'And then the point at which no synthesis is possible — and none',
    'necessary, for the book does not want to reconcile what the world',
    'has not reconciled.',
    '',
    '**They part ways at the line.** Conventional medicine says: show me',
    'the carrier, then I believe you. Homeopathy says: the carrier is',
    'the information, and whoever seeks it only in the substance asks',
    'the wrong question. Both have their logic — and neither can refute',
    'the other. Conventional medicine cannot prove that it does not',
    'work; homeopathy cannot prove that it works. **That is no lack of',
    'effort, that is the boundary of knowledge — and at this boundary',
    'this chapter deliberately stands still.**',
    '',
    '**They part ways at the state of the studies.** The one side sees',
    'in the large evaluations the end of the debate; the other sees a',
    'procedure that cannot depict its art of the individual case. Here',
    'too the facts agree — the meta-analyses exist —, and what parts is',
    'the question of whether the yardstick fits the matter. **Whoever',
    'holds that for settled has not read both sides.**',
    '',
    '## What this chapter means for the book',
    '',
    'The way of thinking determines the method — this sentence has found',
    'in this chapter perhaps its sharpest form. The way of thinking of',
    'homeopathy: the illness is a disturbance of the whole, and the',
    'remedy is an information that the body understands. The way of',
    'thinking of conventional medicine: the illness is a measurable',
    'process, and the remedy is a substance with demonstrable effect.',
    'Two ways of thinking, two methods — and the question of which holds',
    'is older than both.',
    '',
    'And then there is the bridge that this book itself has built: **The',
    'previous chapter showed that medicine recognises information as a',
    'remedy — mRNA is a construction instruction, not a substance, and',
    'it heals.** Conventional medicine has therefore long accepted that',
    'information can be medicine. Homeopathy has claimed the same for',
    'two hundred years — only without the lipid envelope that can be',
    'proved. Whether that is a difference of degree or of principle,',
    'this chapter cannot answer. But it is the question that will decide',
    'the medical history of tomorrow.',
    '',
    '## The bridge to the next chapter',
    '',
    'Homeopathy was not the only answer to the brutal medicine of the',
    'nineteenth century. In the same century in which conventional',
    'medicine treated its patients with bloodletting and mercury, a',
    'pastor in Bavaria began to treat the sick with cold water, movement',
    'and herbs — and was mocked by the same conventional medicine that',
    'had mocked Hahnemann. **Chapter 10 tells of Sebastian Kneipp and',
    'natural medicine** — the big sister of homeopathy, which needs no',
    'globules, no Organon, no potentisation. Only water, trust and the',
    'conviction that the body helps itself if one lets it.',
  ].join('\n'),

  urteil: {
    frage:
      'What is a proof for you — the study or the experience? And what ' +
      'would have to happen for you to believe the other side?',
    hinweis: [
      'There is no right and no wrong here. Take the two yardsticks. The',
      'one: what works must be able to show itself under controlled',
      'conditions, repeated, blinded, against a sham treatment — otherwise',
      'every error that is convincingly presented survives. The other:',
      'what has helped millions of people for two centuries is not thereby',
      'refuted that a procedure cannot measure it. Ask yourself three',
      'things. First: what have you last believed without being able to',
      'prove it — and why? Second: what exactly would an experiment have',
      'to show for you to change your mind; and would you also accept the',
      'opposite? Third: if a treatment demonstrably helps, but the reason',
      'for it lies in the human being and not in the remedy — is it then',
      'worthless or valuable? Exactly between these questions lies the',
      'dispute that has not been decided for two hundred years.',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'What did Samuel Hahnemann do in 1790 when he came upon a ' +
        'passage about cinchona bark while translating?',
      antworten: [
        'He struck the passage from the translation.',
        'He took the cinchona bark himself and wrote down what it ' +
          'triggered in him.',
        'He gave it to a patient with the intermittent fever.',
      ],
      richtig: 1,
      erklaerung:
        'Hahnemann held the explanation of the Edinburgh professor ' +
        'William Cullen to be insufficient, took the bark twice a day in ' +
        'a strong dose and described in a footnote of his own ' +
        'translation complaints that he compared with those of the ' +
        'intermittent fever. In 1796 he published the new principle from ' +
        'it; the doctrine received the name homeopathy in 1807. The ' +
        'experiment itself was later not reliably repeated.',
    },
    {
      frage: 'What does the guiding principle "Similia similibus curentur" mean?',
      antworten: [
        'Like shall be healed by like.',
        'The smallest dose is the strongest.',
        'The physician heals, nature is silent.',
      ],
      richtig: 0,
      erklaerung:
        'The sentence stands on the title page of the "Organon" and is ' +
        'the first basic principle of homeopathy: one seeks the ' +
        'substance that produces as similar a picture of complaints in ' +
        'the healthy as the illness does in the sick. The thought behind ' +
        'it: the stimulus sets the counter-movement of the body in ' +
        'motion — in this way of thinking it is not the remedy that ' +
        'heals but the organism itself.',
    },
    {
      frage: 'What happens in homeopathic potentisation?',
      antworten: [
        'The active substance is heated until it is chemically ' +
          'transformed.',
        'Several active substances are mixed into a complex remedy.',
        'The substance is diluted step by step and each time shaken or ' +
          'triturated vigorously.',
      ],
      richtig: 2,
      erklaerung:
        'What is decisive for homeopathy is not the diluting alone but ' +
        'the succussion respectively trituration at every step — that is ' +
        'why the procedure is called potentisation or dynamisation. From ' +
        'about the twelfth C-potency, because of Avogadro\'s number, ' +
        'arithmetically no molecule of the starting substance is ' +
        'contained any more. Homeopathy does not dispute that; it assumes ' +
        'that an information of the substance is transmitted.',
    },
    {
      frage: 'Why did Hahnemann leave Leipzig in 1821?',
      antworten: [
        'The university had forbidden his doctrine as unscientific.',
        'A court, on a suit brought by the pharmacists, forbade him to ' +
          'dispense his remedies himself.',
        'He followed a call to the Paris medical faculty.',
      ],
      richtig: 1,
      erklaerung:
        'In the Kingdom of Saxony the preparing and dispensing of ' +
        'remedies was the privilege of the pharmacists. Because ' +
        'Hahnemann made his remedies himself, they sued; in 1820 the ' +
        'court decided against him. In the neighbouring Duchy of ' +
        'Anhalt-Köthen other law applied: Duke Ferdinand appointed him ' +
        'court councillor and explicitly allowed him his own dispensing. ' +
        'Hahnemann moved to Paris only in 1835, with his second wife ' +
        'Mélanie.',
    },
    {
      frage:
        'What did the investigation of the journal "Nature" into the ' +
        'experiments of Jacques Benveniste (1988) show?',
      antworten: [
        'The effect was no longer detectable under blinded conditions.',
        'The memory of water was thereby confirmed.',
        'The experiments were never checked.',
      ],
      richtig: 0,
      erklaerung:
        'Benveniste had reported that extremely diluted antibody ' +
        'solutions were still effective. "Nature" printed the article ' +
        'with an explicit reservation and sent an investigating group ' +
        'into the laboratory; under blinded conditions the effect could ' +
        'not be confirmed, independent repetitions failed. The voice of ' +
        'homeopathy in this chapter names that itself as a defeat.',
    },
  ],
};

module.exports = homoeopathie;
