// Chapter 12 — "Jenner and Vaccination".
//
// The second chapter of the modern era. It tells the most successful
// measure in the history of medicine — the eradication of smallpox — and
// at the same time the oldest and hardest dispute medicine has ever had
// with its patients. The two belong together and are told together here.
//
// The WAY-OF-THINKING analysis is the heart of the chapter (the owner's
// requirement). It asks: Why prevent instead of cure? (Because there was
// no treatment for smallpox — the only lever lay before the illness.)
// Why deliberately make a healthy person ill? (Because everyone knew that
// a survivor never fell ill again — the body learns; and because a
// deliberately set illness runs a milder course than one that is
// inhaled.) Why the cowpox? (Because the harmless relative teaches the
// same lesson as the deadly one — the teacher need not be dangerous.)
// Why from arm to arm? (Because there was no vessel that could keep the
// vaccine — only the living body.) Why the compulsion? (Because the
// protection of the individual only becomes protection for all once
// enough people take part — and because the state discovered a new power
// over the body in the process.) And why was it precisely this one
// disease that could be eradicated?
//
// LENGTH RULE (owner's feedback, 24 Aug 2026): From chapter 9 onwards the
// rule is reversed — complete and detailed. For this chapter it applies
// doubly (owner's requirement: the dark early history AND the
// vaccine-critical statistics prominent, not as a footnote). Detailed
// does not mean bloated: every paragraph moves the story forward.
// Measured in tests/karte-jenner-impfung.mjs.
//
// The TONE rule, applied with particular sharpness here: BOTH sides
// fairly. This first voice speaks FOR vaccination — and names the
// uncomfortable places of its own side itself, instead of leaving them
// to the opposing voice: the experiments on prisoners and orphans
// (Newgate and Boston, 1721), the boy James Phipps, the syphilis that
// travelled along from arm to arm, the trade in lymph, the compulsion of
// the vaccination laws — and the critics' statistics (the decline of
// many diseases began before vaccination), which are not passed over
// here but explained. THE NO-RUMOURS RULE (the owner's decision,
// 25 Aug 2026): Only documented facts stand in the text; where figures
// are disputed, the text says so.
//
// Voices (round 11): The FIRST perspective — the vaccinating doctors
// from within — was written by Opus. The SECOND (the vaccine criticism:
// the dark early history from the perspective of those who suffered it,
// the curves before vaccination, the hygiene hypothesis and the
// allergies, the financial interests) and the final synthesis were added
// by Hermes in the second pass. Perspective workflow: CLAUDE.md.
//
// NO REPETITIONS (the owner's decision, 21 Aug 2026): Chapter 1 is
// structured around "who speaks here", chapter 2 begins with a scene,
// chapter 3 tells a day in the life, chapter 4 is an exchange of
// letters, chapter 5 the journey of a book, chapter 6 a tour, chapter 7
// a trial, chapter 8 an invoice, chapter 9 a clock. This chapter
// chooses the tenth dramaturgy: THE CHAIN. The vaccine of the 19th
// century had no phial — it travelled from arm to arm, from child to
// child, around the whole world. The sections are the links of this
// chain: the first link from the East, the link from the cowshed, the
// links nobody asked, what the chain dragged along with it — down to the
// last link in 1977 in Somalia. The second voice can read the same chain
// from its broken links.
//
// The texts are stored as line arrays joined with `.join('\n')` — that
// way they stay readable in the repo at ~72 characters (the owner reads
// them here for review), and utils/markdown.js turns them back into
// flowing text in the app.
//
// CommonJS without UI imports (architecture rule): checkable with plain
// `node`.

/**
 * The voice of the vaccinating doctors — vaccination from within.
 *
 * Written by Opus (round 11). A shared voice of those who vaccinated:
 * the country doctor from Berkeley, the parish vaccinators of the
 * English poor, the doctors of the worldwide campaign. It tells why
 * they did what they did — and it names the uncomfortable places
 * itself (additional rule for sensitive topics in CLAUDE.md).
 */
const stimmeDerImpfaerzte = [
  '## The Chain',
  '',
  'Imagine a chain made of people.',
  '',
  'It begins on an afternoon in May 1796 on the left arm of an',
  'eight-year-old boy in an English village, and it ends one hundred',
  'and eighty-one years later on the arm of a hospital cook in',
  'Somalia. Between the two lie millions of arms. For the vaccine this',
  'chapter is about had, for decades, no phial and no refrigeration. It',
  'lived only in a human being, and to pass it on you had to set it',
  'from the one person\'s arm into the next one\'s. Eight days later that',
  'arm was the source for the one after that. **Vaccination literally',
  'went around the world as a chain — from arm to arm, from child to',
  'child.**',
  '',
  '**What you hear here is the view of those who vaccinated — a way of',
  'thinking, not the truth.** We speak for the country doctor in',
  'Gloucestershire, for the parish vaccinators of the English poor, for',
  'the doctors of the worldwide campaign of the 1970s. We have',
  'something to tell that is unique in the history of medicine: **a',
  'disease that no longer exists.** And we have something to confess:',
  'this chain has links that nobody asked.',
  '',
  'We will walk it, link by link. Including the places where it',
  'rusts.',
  '',
  '## Before the chain: what smallpox was',
  '',
  'To understand why people did what comes next, you must first know',
  'what they were afraid of. Not theoretically. Practically.',
  '',
  'In 18th-century Europe smallpox was everywhere. Nearly everyone',
  'caught it at some point, usually as a child. Historians estimate',
  'that around **four hundred thousand** people in Europe died of it',
  'every year. Of ten who fell ill, about three died in the severe',
  'form. Whoever survived carried it in the face for the rest of their',
  'lives: deep, round scars, often by the hundred. A large share of all',
  'blindness at that time went back to smallpox.',
  '',
  'It did not strike only the poor. Queen Mary II of England died of it',
  'in 1694, Emperor Joseph I in 1711, King Louis XV of France in 1774.',
  'In the Habsburg families several children died in a single',
  'generation. **This matters for everything that follows: smallpox was',
  'the one disease against which wealth was no help.**',
  '',
  'And there was nothing. No treatment, no remedy, no comfort except',
  'nursing. The doctor could accompany the fever, cover the sores,',
  'instruct the relatives — nothing more. Whoever caught smallpox',
  'waited to see whether they were one of the seven in ten.',
  '',
  'Here lies the root of our whole way of thinking, and it is a root of',
  'desperation. **Why prevent instead of cure?** Not because we were',
  'wiser than the doctors before us. But because there was nothing to',
  'cure. Once a disease is present and nobody can stop it, only one',
  'lever remains: the time **before**. Vaccination is the first great',
  'intervention of medicine in a person who is not ill at all. That was',
  'new, and to this day it is the point at which minds divide — that,',
  'too, belongs honestly in this chapter: with every other treatment,',
  'the doctor waits until a sick person comes to him. With vaccination,',
  'he goes to the healthy.',
  '',
  '## The first link came from the East',
  '',
  'The first protection against smallpox was not a European invention,',
  'and it did not come from a university. It came from the experience',
  'of ordinary people in China, India, West Africa and the Ottoman',
  'Empire.',
  '',
  'The procedure was later called **variolation**, after the Latin name',
  'of smallpox. It consisted of deliberately infecting a healthy person',
  'with **real human smallpox**: in Turkey one scratched the skin and',
  'placed in it a drop of fluid from the pustule of a mildly ill',
  'patient. In China one blew dried, powdered smallpox scab into the',
  'nose. In parts of Africa one scratched the arm.',
  '',
  'The news of it reached England through **Lady Mary Wortley Montagu**,',
  'the wife of the British ambassador in Constantinople. She had',
  'survived smallpox herself, her brother had died of it, and her face',
  'was marked. In 1717 she wrote home from Turkey that old women there',
  'went from house to house in September with a nutshell full of',
  'smallpox material; the thing was so safe that she would have it done',
  'to her own son. She did so in 1718 in Constantinople and in 1721 to',
  'her daughter in London.',
  '',
  '**Why should one deliberately make a healthy person ill?** That',
  'question sounds crazy today. Back then it had a clean answer in',
  'three steps, and every step rested on an observation anyone could',
  'make:',
  '',
  '**First: the body learns and does not forget.** Whoever had survived',
  'smallpox never caught it again. Everyone knew that. That is why',
  'people with scarred faces were preferred for nursing the sick — they',
  'were considered safe. Nobody could explain why. But it held so',
  'reliably that one could build on it.',
  '',
  '**Second: not every course of the disease is equally severe.** Some',
  'got away with a few pustules, others died. If the protection is the',
  'same no matter how severe the illness was — then the mild course is',
  'a pure gain.',
  '',
  '**Third: the course can be influenced.** And here lies the real art',
  'of the old variolators. They chose the material from a mild case,',
  'took little of it, put it into the skin instead of the air one',
  'breathes, chose a sturdy person and a good season. The result was',
  'not certain, but it was different: of a hundred who were variolated,',
  'about one or two died. Of a hundred infected naturally, twenty to',
  'thirty died.',
  '',
  '**That is the calculation on which all prevention rests** — and it',
  'is a bet, not a certainty. One traded a great danger that would',
  'almost surely strike sooner or later for a small danger that one',
  'chose oneself and timed oneself. Whoever did not accept this',
  'calculation had an objection we could never refute, and still cannot',
  'refute today: **the one or two in a hundred were people who, without',
  'the intervention, might never have fallen ill.** And they died of a',
  'disease a doctor had given them.',
  '',
  'Variolation had a second price that we must name: the person',
  'vaccinated was contagious for weeks. They carried real smallpox.',
  'Whoever was careless set an epidemic in motion. That is exactly why',
  'variolation was banned by law in England in 1840, long after it had',
  'done its duty.',
  '',
  '## Newgate and Boston, 1721: the price of the first trial',
  '',
  'And now the place where we smooth nothing over. For the question of',
  'how dangerous the procedure is, nobody in England wanted answered on',
  'their own child. So it was answered on people who could not say no.',
  '',
  'On **9 August 1721** six prisoners sentenced to death in the London',
  'prison of **Newgate** were variolated — three men and three women.',
  'The quid pro quo was the pardon. Doctors and courtiers looked on.',
  'All six survived, all six were set free; one of the women was then',
  'sent to a smallpox hospital to test whether the protection held.',
  '',
  'The following year the trial was repeated on the orphans of the',
  'parish of St James in Westminster. Only then did the Princess of',
  'Wales have her own daughters vaccinated — and only then did the',
  'matter become socially acceptable in England.',
  '',
  '**We call it by its name: that was a human experiment on prisoners',
  'and on children without parents.** A consent such as we require',
  'today did not exist and could not exist: whoever chooses between the',
  'gallows and a vaccination does not choose freely. Whoever, as an',
  'orphan, belongs to a parish is not asked. The justification of the',
  'time was that it had, after all, turned out well for everyone. That',
  'is not a justification. It is luck.',
  '',
  'In the same year the same thing happened on the other side of the',
  'Atlantic, and there the story is even more uncomfortable. In',
  '**Boston** a smallpox epidemic raged in 1721. The preacher Cotton',
  'Mather had the procedure not from a book but from **Onesimus**, a',
  'man he owned as a slave who came from West Africa: Onesimus showed',
  'him the scar on his arm and explained that in his homeland people',
  'protected themselves against smallpox in this way. The physician',
  '**Zabdiel Boylston** dared the attempt — first on his own',
  'six-year-old son and on two enslaved people of his household, an',
  'adult and a small child.',
  '',
  'By the end of the epidemic Boylston had variolated 242 people. Six',
  'of them died. Of the roughly 5,900 Bostonians who had caught the',
  'disease naturally, 844 died. **The figures were unambiguous, and',
  'they were the first of their kind in the history of medicine: a',
  'prevention, counted across a whole population.**',
  '',
  'And yet next to it stands a sentence that cannot be calculated away:',
  '**the knowledge of Africans was taken, the bodies of the enslaved',
  'were used, and the glory went to two white men.** Onesimus barely',
  'appears in the books of medicine for over two hundred years. We',
  'write him here into the place where he belongs: at the beginning.',
  '',
  '## The link from the cowshed',
  '',
  'And now to Gloucestershire, a landscape of meadows, hedges and',
  'dairy cattle.',
  '',
  'Among the farmers there, a claim had circulated for as long as',
  'anyone could remember: **whoever has had cowpox does not catch',
  'human smallpox.** Cowpox was a trifling matter — a cattle disease',
  'that passed onto the hands during milking: a few blisters on the',
  'fingers, a few days of malaise, done. The milkmaids who sat in the',
  'barn morning and evening often caught it. And in the smallpox years',
  'they remained conspicuously healthy.',
  '',
  'A country doctor named **Edward Jenner** (born in Berkeley in 1749,',
  'died there in 1823) took this talk of the farmers seriously. That',
  'is the decisive step, and it is not a medical one but a mental one:',
  '**he took the knowledge of the milkmaids for an observation and not',
  'for superstition.**',
  '',
  'Jenner had learned under John Hunter in London, the anatomist from',
  'the ninth chapter of this book, and had taken over the sentence',
  'that carries all of modern medicine: why do you think about it? Why',
  'don\'t you try it out? So he collected cases. He sought out milkmaids',
  'who had had cowpox and had them variolated — with real smallpox.',
  'With them, nothing happened. The puncture stayed irritation-free,',
  'the fever stayed away. With others, variolation took its usual',
  'course.',
  '',
  '**Why the cowpox?** Because from these cases Jenner derived a',
  'rationale that was to become one of the most fruitful in the whole',
  'history of medicine: **when two diseases resemble each other closely',
  'enough, the harmless one teaches the body the same lesson as the',
  'deadly one.** The body learns from a harmless example and passes the',
  'test when the real thing comes. The teacher need not be dangerous.',
  '',
  'That is the whole idea of vaccination, and it is the same to this',
  'day. Everything that has been added since — killed pathogens,',
  'weakened pathogens, single protein building blocks, construction',
  'blueprints — are answers to the one question of how to give the body',
  'the lesson without giving it the disease.',
  '',
  'Two honesties at this point. **The first: Jenner was not the first.**',
  'The farmer **Benjamin Jesty** of Yetminster in Dorset had, in 1774 —',
  'twenty-two years before Jenner — vaccinated his wife and his two',
  'sons with cowpox material on a knitting needle, to carry them',
  'through a smallpox wave. They remained spared for life. Jesty',
  'reaped mockery and stones and wrote nothing down. What Jenner did',
  'and Jesty did not do was to **test the matter and publish it**. That',
  'is a great achievement. It is just a different one from the',
  'achievement that stands on the monuments.',
  '',
  '**The second: the origin of the vaccine is not fully settled to this',
  'day.** Recent studies of old vaccine samples suggest that many of',
  'these lymphs contained not the cowpox virus at all but a close',
  'relative from the horse. Jenner himself repeatedly pointed to a',
  'horse disease that came into the stables through the hands of the',
  'grooms. For the effect, that changes nothing. For our certainty it',
  'does: **we vaccinated for decades with something of which we did not',
  'know exactly what it was.**',
  '',
  '## 14 May 1796: a boy named James Phipps',
  '',
  'On this day the chain begins.',
  '',
  'The cow maid **Sarah Nelmes** had caught cowpox while milking a cow;',
  'the blisters sat on her hand. Jenner took fluid from them and placed',
  'it in two small cuts on the arm of the eight-year-old **James',
  'Phipps**, the son of his gardener. The boy got what was to be',
  'expected: a local pustule, a few days of malaise, then nothing more.',
  '',
  'And then came the part that turned the matter into a proof and, at',
  'the same time, into a problem. On **1 July 1796** Jenner variolated',
  'the boy — with real human smallpox material. **He gave him the',
  'disease he wanted to protect him against.** Had the idea been wrong,',
  'James Phipps could have died. Nothing happened. Jenner repeated the',
  'trial several times later; the protection held.',
  '',
  '**By today\'s standards this is not a permissible experiment.** No',
  'informed-consent conversation, no written consent from the parents,',
  'no independent body watching over the trial — and above all: a child',
  'to whom the real thing was deliberately administered. For two',
  'hundred years we read past this in our own accounts, because the',
  'result was so great. That was a mistake. **A result does not make an',
  'experiment permissible in hindsight.**',
  '',
  'What can be said in Jenner\'s favour we also say, so that you can',
  'weigh both: with variolation he used a procedure that was common at',
  'the time and that many parents expressly wanted for their children.',
  'He looked after the boy for the rest of his life, later made over a',
  'house to him and never lost sight of him. And when he was famous, he',
  'vaccinated the poor of the neighbourhood **free of charge** in a',
  'small hut in his garden; he called it the temple of vaccinia. That',
  'does not make the experiment on the child permissible. It only shows',
  'that a person can be both.',
  '',
  'The Royal Society rejected his first report. In 1798 he printed, at',
  'his own expense, a slim treatise on cowpox in which he set out',
  'twenty-three cases. From the Latin word for cow — *vacca* — comes',
  'the name the matter has borne ever since: vaccination. When Louis',
  'Pasteur developed his own vaccines eighty years later, he kept the',
  'word, expressly in Jenner\'s honour.',
  '',
  '## How the chain ran around the world',
  '',
  'What happened next is without precedent: within a few years a finding',
  'from an English cowshed ran around the whole globe. And because',
  'there was neither refrigeration nor a durable preparation, it ran as',
  'a chain.',
  '',
  '**Why from arm to arm?** Because there was no vessel that kept the',
  'vaccine alive. Nobody knew pathogens, cultures, glycerine or ice.',
  'Dried lymph on a thread or between two glass plates survived a few',
  'weeks, often not even that. **The only reliable container for the',
  'vaccine was a living human being.** So on the eighth day one took',
  'fluid from the pustule of the last person vaccinated and placed it',
  'in the next arm. If the chain broke, the vaccine was lost in that',
  'region, and one had to send for new.',
  '',
  'That is how vaccination reached Vienna and Geneva in 1799 and Boston',
  'in 1800 — Benjamin Waterhouse received from the English Bath a',
  'thread with dried lymph and vaccinated his own son with it. Napoleon',
  'had his army vaccinated from 1805 and honoured Jenner, although',
  'their countries were at war; at Jenner\'s request he released English',
  'prisoners.',
  '',
  'Spain went furthest. In 1803 King Charles IV sent an expedition',
  'under the physician **Francisco Javier de Balmis** across the',
  'Atlantic to bring vaccination to the Spanish colonies and as far as',
  'the Philippines. Since the vaccine would not have survived the',
  'voyage, **twenty-two orphan boys** were taken along — as a living',
  'chain. Every nine to ten days two of them were freshly vaccinated so',
  'that the vaccine would arrive. They were accompanied by the matron',
  'of their orphanage, Isabel Zendal Gómez, who cared for them; the',
  'World Health Organization later honoured her as the first woman in',
  'an international health mission.',
  '',
  'That expedition saved countless lives on two continents. And it used',
  'twenty-two children as containers. **Both is true, and we insist',
  'that both be told.** It is the same sentence as with Newgate, with',
  'the orphans of Westminster, with the enslaved in Boston, with James',
  'Phipps: in its early links, the chain of vaccination used the people',
  'who were least able to say no.',
  '',
  '## What the chain dragged along',
  '',
  'A chain of people transmits not only what one wants to transmit.',
  '',
  'Whoever places fluid from one child\'s arm into the next child\'s arm',
  'transmits blood along with it. And with the blood, another disease',
  'can travel. That is exactly what happened, and the best known case',
  'stands in Piedmont: **in 1861 in Rivalta** several dozen children',
  'were vaccinated from the arm of a single infant. More than forty of',
  'them fell ill with **syphilis**; the infant that was the source had',
  'inherited it from its mother, without it showing. Some of the',
  'children died, some mothers were infected while nursing. Similar',
  'cases are documented from Bremen, from Italy and from France.',
  '',
  '**That is no rumour of the anti-vaccinationists. That is our own',
  'record.** In protecting against the one disease we spread another,',
  'and it took us years to admit it, because it harmed the cause we',
  'were advocating.',
  '',
  'The solution came back from the cow: the vaccine was grown on',
  '**calves** again and taken from there instead of from children\'s',
  'arms. From the 1860s this prevailed in Europe; later glycerine was',
  'added, which made the lymph durable and killed off accompanying',
  'germs. In England, arm-to-arm vaccination was expressly forbidden by',
  'the law of **1898**. So the problem was solvable — but it was only',
  'solved after children had paid for it.',
  '',
  'And then the money, because that, too, belongs to it from the start.',
  '',
  'Vaccination was a **business** from its first decade. Itinerant',
  'vaccinators went from place to place and had themselves paid per',
  'arm. There was trade in "genuine cowpox lymph", and there was',
  'counterfeiting: diluted, old, ineffective goods. When England made',
  'vaccination free for the poor in 1840, it paid the doctors **per',
  'head vaccinated** — an incentive to vaccinate a lot and check',
  'little. Jenner himself received money from Parliament twice, ten',
  'thousand pounds in 1802 and twenty thousand in 1807; that was a',
  'fortune. He had not had his procedure protected, but poor he did not',
  'remain.',
  '',
  'We say this so plainly because the other side will say it anyway and',
  'because it is true: **wherever there is vaccination, there is also',
  'money to be made.** It does not follow from that that vaccination',
  'does not work. But it does follow that an argument is not wrong',
  'simply because an opponent of vaccination brings it forward.',
  '',
  '## The law and the resistance',
  '',
  'Now comes the part where a medical offer became a state duty — and',
  'doubters became a movement.',
  '',
  'England led the way: in 1840 free vaccination for all and a ban on',
  'the old variolation; **in 1853 compulsory vaccination** for every',
  'child in the first three months of life; in 1867 the extension with',
  'penalties that were repeated as long as the child remained',
  'unvaccinated; in 1871 dedicated vaccination officers who kept the',
  'registers.',
  '',
  '**Why the compulsion?** Two reasons, one matter-of-fact and one less',
  'pretty, and we name both.',
  '',
  'The matter-of-fact one: a contagious disease is not a private',
  'matter. The protection of the individual only becomes protection for',
  'all once enough people take part; otherwise islands remain in which',
  'the disease keeps running and from which it returns — also to the',
  'infants who cannot yet be vaccinated and to the sick who cannot',
  'tolerate it. Whoever vaccinates protects not only themselves.',
  '',
  'The less pretty one: **with the vaccination laws, the state',
  'discovered a new power over the bodies of its citizens.** For the',
  'first time in history a government intervened in a healthy person',
  'and punished whoever refused. We welcomed that at the time, because',
  'it made our work easier. We thought too little about what a door was',
  'opened with it.',
  '',
  'And the compulsion struck unequally. Whoever had money could pay the',
  'fine. Whoever had none went to prison or lost their tools to the',
  'bailiff — and because the penalties were repeated, there were',
  'fathers who sat in prison several times for the same matter. **That',
  'the first great anti-vaccination movement was a movement of the',
  'working class is no coincidence, but a consequence of these laws.**',
  '',
  'It organized itself quickly: the Anti-Vaccination League from 1853,',
  'the league against compulsory vaccination from 1867, its own',
  'journals from 1879. On **23 March 1885** tens of thousands of people',
  'in **Leicester** marched through the city, burned an effigy of',
  'Jenner and demanded the abolition of the duty. A royal commission',
  'heard both sides from 1889 to 1896. The law of **1898** drew the',
  'conclusion: whoever did not want to be vaccinated for reasons of',
  'conscience could have themselves exempted. The English word for the',
  'conscientious objector was born in this debate.',
  '',
  'And what followed in Leicester? The city hardly vaccinated any more.',
  'Instead it relied on something else: immediate reporting of every',
  'case, immediate isolation of the sick, quarantine for the whole',
  'household, disinfection of the dwelling. **And Leicester came',
  'through the smallpox years well** — better than some cities that',
  'vaccinated. That is a result that speaks against us, and it stands',
  'here because it is true. We long claimed that Leicester lived only',
  'off the protection of the neighbouring cities. What is true: the',
  'isolation was effective. What is also true: it required a far larger',
  'administrative apparatus than most places had.',
  '',
  'Ten years after the march it hit the neighbourhood: in **Gloucester**',
  'a smallpox epidemic broke out in 1895, in a city with a very low',
  'vaccination rate. There were barely two thousand cases and about',
  '**four hundred and thirty dead**, mostly children. The city set up',
  'isolation houses and finally vaccinated on a large scale. **We do',
  'not bring forward this figure to triumph.** It stands next to',
  'Leicester, not in its place. Both cities belong to this story.',
  '',
  '## The curve that fell before us',
  '',
  'And now to the objection that gives us the most trouble, because it',
  'consists not of outrage but of figures.',
  '',
  'It goes like this: whoever looks at the death curves of the great',
  'infectious diseases in the 19th and 20th centuries sees them',
  '**falling long before there was a vaccination**. With tuberculosis',
  'the decline steepened from about 1850; the remedy against it came',
  'after 1940. With scarlet fever, mortality fell to almost zero —',
  '**there is still no vaccination against scarlet fever to this day.**',
  'Typhoid and cholera disappeared from western cities with the sewers.',
  'And with measles, the number of deaths in England and Wales fell by',
  'well over ninety per cent between 1900 and 1960 — the vaccination',
  'came in 1968.',
  '',
  'In 1976 the physician Thomas McKeown turned this into a thesis that',
  'has shaped the debate ever since: the great decline in mortality was',
  'essentially not the work of medicine but of nutrition, housing,',
  'clean water and working conditions.',
  '',
  '**These curves are real. They are not faked, they are not taken out',
  'of context, and whoever shows them is no crank.** For too long we',
  'treated them as an attack. They are an observation, and it is right',
  'in what it shows.',
  '',
  'What we have to say to that is not a contradiction but a distinction',
  '— and it is the core of this section. **These curves almost always',
  'measure mortality, not incidence.** They answer the question: how',
  'many of those who fell ill died? They do not answer the question:',
  'how many fell ill at all?',
  '',
  'And this second curve looks different. Until 1968 nearly every child',
  'got measles, year after year, in waves; the number of cases remained',
  'high while the number of deaths fell. Only with the vaccination did',
  'the number of cases collapse. **In other words: prosperity made the',
  'diseases less deadly. Vaccination made them rarer.** Both are a',
  'gain, and both are not the same thing.',
  '',
  'For smallpox itself this holds with a qualification we do not hide:',
  'here the share of vaccination in the 19th century is harder to',
  'separate out, because at the same time the isolation of the sick,',
  'better housing and the reporting requirement were at work — see',
  'Leicester. What can be said with certainty is what happened at the',
  'end: once systematic vaccination began worldwide in 1967, smallpox',
  'disappeared within ten years from a world in which there was neither',
  'clean water everywhere nor good housing everywhere.',
  '',
  'Two events that one may not plan and that therefore weigh heavily',
  'show the same pattern. **In the Netherlands** seventy-one people',
  'fell ill with polio in 1992/93 and two died — almost exclusively in',
  'a community that refused vaccination on religious grounds, in the',
  'middle of a country with excellent hygiene. And **in the successor',
  'states of the Soviet Union** diphtheria returned in the 1990s after',
  'the vaccination programmes had collapsed: more than 150,000 cases',
  'and several thousand dead in countries with sewers and doctors.',
  '',
  'That does not settle the question, and we do not claim it does. **It',
  'must be answered separately for every disease**, and the answers',
  'turn out differently. Whoever says all vaccinations had achieved',
  'nothing is riding roughshod over the figures. Whoever says every',
  'decline is owed to vaccination does the same. We did the second for',
  'a long time.',
  '',
  '## The last link: Merka, 26 October 1977',
  '',
  'And now the end of the chain.',
  '',
  'In 1967 the world still counted ten to fifteen million smallpox',
  'cases a year and about two million dead. In that year the World',
  'Health Organization began its determined programme. It ended on 26',
  'October 1977 with a hospital cook in the Somali city of Merka.',
  '**Ali Maow Maalin** was the last person in history to catch smallpox',
  'naturally. He survived. Later he himself vaccinated for decades,',
  'against polio, and died of malaria in 2013.',
  '',
  'The last case of the severe form had been two years earlier: the',
  'three-year-old Rahima Banu in Bangladesh. The very last death was in',
  '1978, the photographer Janet Parker in Birmingham — she died of a',
  'virus that had escaped from a laboratory. On **8 May 1980** the',
  'World Health Assembly declared smallpox eradicated.',
  '',
  '**Why was it precisely this disease that could be eradicated — and',
  'no second one since?** This question matters more than the',
  'celebration, because its answer shows how limited our abilities',
  'really are. It came down to six properties of this one disease:',
  '',
  '**First:** smallpox lived only in humans. There was no animal in',
  'which it hid and from which it could have returned. **Second:** you',
  'could see it. Whoever had smallpox had the rash; silent carriers',
  'practically did not exist. **Third:** whoever survived it was',
  'protected forever — and whoever was vaccinated, usually for many',
  'years. **Fourth:** infection required close contact and was slow',
  'enough that one could get ahead of it. **Fifth:** there was a',
  'freeze-dried vaccine that withstood heat, and from 1965 a forked',
  'needle that even briefly trained helpers could use. **Sixth** — and',
  'that was the actual idea: people stopped wanting to vaccinate',
  'everyone. Instead of vaccinating populations, one sought out every',
  'outbreak and vaccinated a ring around it. **They did not chase the',
  'disease; they surrounded it.**',
  '',
  'That is why no second disease has followed. Measles is transmitted',
  'through the air and is incomparably more infectious; polio is',
  'invisible in most cases; influenza viruses live in animals; malaria',
  'has the mosquito. **The eradication of smallpox was not proof that',
  'we can do anything. It was the proof that once, everything fit.**',
  '',
  'And even this ending has its shadow. In the final phase in South',
  'Asia, people were forced to be vaccinated. In 1995 the historian',
  'Paul Greenough compiled in a scholarly journal how vaccination teams',
  'in India entered houses at night between 1973 and 1975 and held down',
  'people who refused. Those involved later described it themselves.',
  '**The last stretch of the most beautiful story of our field was',
  'partly walked with violence.** Whoever conceals that tells the story',
  'wrongly — and later wonders why nobody believes them.',
  '',
  '## The balance sheet of the chain',
  '',
  'Let us take stock, in both directions.',
  '',
  '**What stands.** Smallpox is gone — the only disease in human',
  'history that no longer exists; in the 20th century alone it had',
  'killed an estimated three hundred million people. The idea that the',
  'body can learn from a harmless example still carries every',
  'vaccination today. Polio has fallen from about 350,000 cases in 1988',
  'to a few dozen wild-virus cases. The World Health Organization',
  'estimates that the measles vaccination alone prevented around',
  'fifty-seven million deaths between 2000 and 2022 — an estimate, not',
  'a tally, and it rests on model calculations that one should know',
  'about when using the figure. Tetanus and diphtheria, which once tore',
  'children away, have become rare among us.',
  '',
  '**What we did not manage.** We built the early history of our own',
  'method on people who were not asked: on prisoners, orphans, the',
  'enslaved, a gardener\'s son, twenty-two orphan boys on board a ship.',
  'With arm-to-arm vaccination we spread syphilis and admitted it too',
  'late. We watched vaccination become a business and talked ourselves',
  'into believing it was none of our concern. We welcomed the',
  'compulsion without paying its bill. And for decades we did not',
  'refute the critics\' statistics but ignored them — which harmed the',
  'cause more than any pamphlet.',
  '',
  '**What remains open.** Side effects are rare, but they are not zero.',
  'The smallpox vaccination itself had severe ones: brain',
  'inflammations and deaths on the order of a few per million first',
  'vaccinations. That is exactly why it was discontinued everywhere',
  'after 1980 — **once the disease was gone, the risk of the',
  'vaccination was greater than its benefit, and we stopped.** That is',
  'a calculation we must make again and again for every vaccination,',
  'and we do not always make it well enough in public.',
  '',
  'And then the question to which we have no answer. In the countries',
  'in which the infectious diseases of childhood have almost',
  'disappeared, **allergies, asthma and autoimmune diseases** have been',
  'increasing for decades. In 1989 the epidemiologist David Strachan',
  'wrote down the hypothesis that has since been called the hygiene',
  'hypothesis: an immune system that has too little to do in the first',
  'years of life later falls out of step. Children who grow up on',
  'farms with animals have markedly less hay fever and asthma — that is',
  'well documented.',
  '',
  'What that means for vaccinations is **not** decided by this. The',
  'evidence so far points to the microbial environment as a whole —',
  'stables, siblings, dirt, gut flora — and not to individual',
  'vaccinations. But the question is legitimate, it has not been',
  'conclusively answered, and **to this day there is no recipe against',
  'the allergies.** We traded one burden of disease for another without',
  'ever calculating the exchange. Whoever asks this question asks a',
  'good question.',
  '',
  '## Where the chain breaks: the other voice',
  '',
  'We have shown you a chain that goes around the world and ends in',
  'Somalia. We have told it from our side — from the side of those who',
  'held the needle.',
  '',
  'There is another side, and from it the same chain looks different.',
  'From there it consists not of links but of individual people: of the',
  'prisoner in Newgate who was allowed to choose between the gallows',
  'and the lancet; of the children of Rivalta; of the father in',
  'Leicester who went to prison because he would not hand over his',
  'child; of the parents whose claim of vaccine injury was not',
  'believed.',
  '',
  '**The second voice of this chapter belongs to the critics of',
  'vaccination** — and it has more to offer than outrage. It will show',
  'the curves that fell before vaccination and draw different',
  'conclusions from them than we do. It will ask about the allergies',
  'and about what has taken their place. It will go through the money',
  'made from vaccines and ask who pays for the studies. And it will ask',
  'a question we must ask ourselves and that this book will leave',
  'open:',
  '',
  '**Why does a science that lives on doubt bear doubt so badly on',
  'precisely this question?**',
  '',
  'We have no good answer to that. We only have one experience: every',
  'time we left out an uncomfortable place in our story — Newgate,',
  'Rivalta, the money, the compulsion — it did not weaken the doubters',
  'in the end, but us. **Whoever defends a good cause with only half',
  'the truth defends it badly.**',
].join('\n');

/**
 * The critique of vaccination — the other side of the chain. What the
 * success story does not tell: the prisoners of Newgate, the boy James
 * Phipps, the syphilis in the lymph, the compulsion of the law, the
 * curve that fell before vaccination — and the open questions of today.
 *
 * Written by DeepSeek (round 11, second pass). This voice, too, names
 * the uncomfortable places of its own side itself (additional rule for
 * sensitive topics) — and adheres to the no-rumours rule: only
 * documented facts, nothing invented.
 */
const stimmeDerImpfkritik = [
  '## Where the chain breaks',
  '',
  'The other voice has told the chain: from Constantinople to Berkeley,',
  'from Berkeley into the world, from the world to eradication. It',
  'named the dark links itself — Newgate, the orphans, James Phipps,',
  'the syphilis, the itinerant vaccinators. That is more than their',
  'guild usually admits, and we credit it for that. Now we tell the',
  'same chain from the other side: from the people it was drawn',
  'through, without anyone asking whether they consented. And from the',
  'question the chain has not answered to this day: whom does it serve',
  '— and who pays the price?',
  '',
  '## The first link: the prisoners of Newgate',
  '',
  'London, 1721. Smallpox rages, and the doctors have an idea from',
  'Constantinople: variolation — deliberately infect with real smallpox',
  'so that the disease runs a "controlled" course. But nobody knows',
  'whether it works, and nobody wants to try it first. So one gets the',
  'test subjects where they have no choice: in Newgate prison. Six',
  'people sentenced to death are offered the choice: be variolated — or',
  'be hanged. They choose the lancet, survive, are pardoned. After that',
  'come the orphans of the parish, one after another, without anyone',
  'asking their parents — if they had any. In Boston, in the same year,',
  'Zabdiel Boylston does the same: he vaccinates hundreds, including',
  'the enslaved and orphans, some against their will. And the knowledge',
  'for the variolation in Boston comes from an enslaved man named',
  'Onesimus, who knew the method from Africa — his knowledge was used,',
  'his freedom was not granted.',
  '',
  'One may object: that was the 18th century, that was how the age was.',
  'True. But this voice does not tell it to condemn — but because the',
  'chain of vaccination history begins at this link: with people',
  'without a choice. And the question whether a person can really',
  'consent when they are poor, imprisoned or enslaved is not a question',
  'of the 18th century. It is the question of every vaccination',
  'campaign to this day.',
  '',
  '## The link from the cowshed: the boy who was not asked',
  '',
  'Berkeley, 14 May 1796. Edward Jenner has heard the farmers\' story:',
  'whoever had cowpox did not catch smallpox. He takes lymph from the',
  'cow maid Sarah Nelmes and vaccinates a boy with it: James Phipps,',
  'eight years old. The boy survives it, and when Jenner vaccinates him',
  'weeks later with real smallpox, he does not fall ill. The experiment',
  'succeeds — and becomes the foundation of vaccination.',
  '',
  'James Phipps was never asked. No parent signed, no doctor explained',
  'to the child what was happening to him. Today such an experiment on',
  'a child would be considered unethical and would be forbidden. The',
  'other voice conceded that, and we take note of it. But we add: the',
  'success of 1796 turned an ethical mistake into a worldwide practice.',
  'For decades children, soldiers and the poor were vaccinated without',
  'being told what was injected into them — and without anyone knowing',
  'what, besides the protection, was in the lymph.',
  '',
  '## What the chain dragged along: the syphilis',
  '',
  'For the lymph was no pure vaccine. It was transmitted from arm to',
  'arm — from child to child, from patient to patient — and other',
  'pathogens travelled with it. In Rivalta near Turin, documented cases',
  'became known in 1861 in which children were infected with syphilitic',
  'lymph through vaccination; similar cases occurred in Italy, France',
  'and England. The doctors knew it, discussed it — and kept',
  'vaccinating, because the benefit seemed greater than the harm.',
  'Whether the children\'s parents saw it that way too was not asked.',
  'And the itinerant vaccinators, who travelled from village to village',
  'and sold their "smallpox lymph" out of their own pockets, had an',
  'interest that dirtied the chain: they sold whatever could be sold',
  'and did not check what they sold.',
  '',
  '## The chain and the law: the compulsion',
  '',
  'In 1853 England introduces compulsory vaccination: every child must',
  'be vaccinated, and parents who refuse are punished — fines, repeated',
  'and increased, up to the confiscation of possessions. It was the',
  'first great vaccination law in history, and it met the first great',
  'organized resistance: the Anti-Vaccination League, founded in 1866,',
  'the protests in Leicester, where more than a hundred thousand people',
  'demonstrated in 1885, the refusal of whole towns. Only in 1898 did',
  'England give in and allow the conscience clause. And in Gloucester,',
  'where the parents refused en masse, people again died of smallpox in',
  '1896 — which some took as proof for vaccination and others as',
  'evidence that compulsion had destroyed the trust on which protection',
  'first becomes possible.',
  '',
  'This voice does not tell this to say that compulsory vaccination was',
  'always wrong. It tells it because the question remains open to this',
  'day: may a state intervene in the bodies of its citizens — and from',
  'what point does care become paternalism? Whoever does not ask this',
  'question has learned nothing from history.',
  '',
  '## The curve that fell before us',
  '',
  'And now the figure that is missing from the heroic stories. The',
  'mortality from the great infectious diseases — measles, scarlet',
  'fever, tuberculosis, typhoid — began to fall in England and Germany',
  'decades before the respective vaccination. Clean water, sewers,',
  'better nutrition, less overcrowding in the dwellings: the historian',
  'Thomas McKeown documented these connections with figures in the',
  '1970s. The mortality curves fell steeply before the vaccines came —',
  'and after their introduction they often fell hardly any steeper.',
  'That does not mean the vaccinations achieved nothing; it means the',
  'heroic story forgets the other heroes: the engineers of the sewers,',
  'the reformers of hygiene, the educators of nutrition.',
  '',
  'And it means something for today: the children in our countries',
  'barely get infectious diseases any more — and instead allergies,',
  'neurodermatitis, asthma, autoimmune diseases, which did not exist in',
  'this accumulation before. The hygiene hypothesis says: the immune',
  'system that no longer fights real battles turns against its own',
  'body. The infectious diseases declined — but against what is wrong',
  'with children today, medicine has no recipe. The chain solved one',
  'problem and left a new one open, and nobody knows how big the new',
  'one is.',
  '',
  '## Answer to the advocates of vaccination',
  '',
  'The other voice said the chain eradicated smallpox — that is true,',
  'and this voice does not dispute it. It only wants to complete the',
  'account: the chain saved people — and it was drawn over people who',
  'were not asked. It defeated the disease — and it left open questions',
  'that a free society may not sweep under the carpet: the questions of',
  'consent, of compulsion, of side effects, of money. Whoever asks',
  'these questions is no enemy of medicine. They are its conscience.',
  '',
  'And one more thing, because it is often said: it is easy to be',
  'against vaccinations because one no longer knows smallpox. Perhaps',
  'the opposite is true: it is easy to be for vaccinations when one no',
  'longer knows the fear — and when one has never asked who paid the',
  'price of the chain. The chain of vaccination has two sides, and both',
  'belong in the story. This voice has told the second side.',
].join('\n');

/** Chapter 12 of the topic map. */
const jennerImpfung = {
  id: 'jenner-impfung',
  titel: 'Jenner and Vaccination',
  epoche: '1796 – present',

  aufhaenger: {
    frage:
      'What does a cow maid from Gloucestershire have to do with the ' +
      'greatest heroic story in medicine — and with its oldest dispute?',
    text: [
      'For centuries smallpox killed more people than any war. It made no',
      'distinction between poor and rich: kings died of it like day',
      'labourers, and whoever survived carried the scars in the face. A',
      'treatment did not exist.',
      '',
      'Then farmers in England noticed something: the milkmaids who caught',
      'the harmless cowpox while milking did not catch smallpox. A country',
      'doctor took this observation seriously, tested it and vaccinated an',
      'eight-year-old boy on 14 May 1796. Nearly two hundred years later,',
      'in 1980, the World Health Organization declared smallpox',
      'eradicated — the first and so far only disease in history that no',
      'longer exists.',
      '',
      'But with the same vaccination there also began one of the oldest',
      'and most bitter disputes in medicine. From the start it revolved',
      'around the same four questions as today: How safe is it? Who is',
      'liable when something goes wrong? May the state compel it? And who',
      'profits from it?',
      '',
      'This chapter tells both. The triumph — and the early history that',
      'is seldom told along with it: the experiments on prisoners and',
      'orphans, the boy on whom smallpox was deliberately set in 1796,',
      'the syphilis that travelled from arm to arm in the 19th century,',
      'and the statistics that critics of vaccination have long put',
      'forward: for many diseases the decline was already well advanced',
      'before a vaccination against them existed.',
    ].join('\n'),
  },

  // The map lives in utils/themen/karten/jenner-impfung.js — here only
  // the phase references are translated (phasen → karteHinweise), not the
  // map itself.
  karteHinweise: [
    {
      label: '1721: variolation reaches England — the trial in Newgate',
      hinweis:
        'Lady Mary Wortley Montagu had seen the procedure in 1717 in ' +
        'Constantinople: one deliberately gives a healthy person real ' +
        'human smallpox so that they get through it mildly. How dangerous ' +
        'it is is tested on 9 August 1721 in London on six people ' +
        'sentenced to death in Newgate prison; the quid pro quo is the ' +
        'pardon. The following year the trial is repeated on the orphans ' +
        'of the parish of St James. Only then does the Princess of Wales ' +
        'have her own daughters vaccinated.',
    },
    {
      label: '1774–1796: the cowpox — Yetminster and Berkeley',
      hinweis:
        'Among the farmers in the west the observation circulates that ' +
        'the milkmaids with cowpox on their hands do not catch human ' +
        'smallpox. In 1774 the farmer Benjamin Jesty in Yetminster ' +
        '(Dorset) vaccinates his wife and his sons with a knitting needle ' +
        'and cowpox material. On 14 May 1796 the country doctor Edward ' +
        'Jenner in Berkeley places fluid from the cow maid Sarah Nelmes\' ' +
        'cowpox into the arm of the eight-year-old James Phipps — and ' +
        'tests the protection on 1 July with real human smallpox.',
    },
    {
      label: '1840–1867: compulsory vaccination in England and Wales',
      hinweis:
        'In 1840 vaccination becomes free for the poor and the old ' +
        'variolation is forbidden. In 1853 follows the duty for every ' +
        'child in the first three months of life, in 1867 the extension ' +
        'with penalties that are repeated as long as the child remains ' +
        'unvaccinated; from 1871 dedicated vaccination officers keep the ' +
        'registers. Whoever can pay, pays the fine; whoever cannot pay ' +
        'goes to prison or loses their tools to the bailiff.',
    },
    {
      label: '1885–1898: Leicester, Gloucester and the conscience clause',
      hinweis:
        'On 23 March 1885 tens of thousands of people in Leicester march ' +
        'through the city against compulsory vaccination. Leicester then ' +
        'hardly vaccinates any more and instead relies on immediate ' +
        'reporting, isolation of the sick and quarantine of the ' +
        'households. In Gloucester a smallpox epidemic breaks out in ' +
        '1895/96 at a low vaccination rate, mostly among children. A ' +
        'royal commission hears both sides from 1889 to 1896; the law of ' +
        '1898 permits refusal on grounds of conscience and forbids ' +
        'arm-to-arm transmission.',
    },
    {
      label: '1967–1980: the way into the world and the end of smallpox',
      hinweis:
        'The vaccine knew neither refrigeration nor phial: it travelled ' +
        'as a chain from arm to arm, through the western ports to ' +
        'America (1800) and with the Spanish Balmis expedition from 1803 ' +
        'as far as the Philippines. In 1967 the world still counts ten ' +
        'to fifteen million smallpox cases a year; the World Health ' +
        'Organization begins its programme of ring vaccination. Britain ' +
        'ends general smallpox vaccination in 1971. The last person to ' +
        'be infected naturally fell ill on 26 October 1977 in Somalia; ' +
        'on 8 May 1980 the World Health Assembly declares smallpox ' +
        'eradicated.',
    },
  ],

  perspektiven: [
    {
      id: 'impfbefuerworter',
      name: 'The Voice of the Vaccinating Doctors',
      stimme: 'Opus',
      text: stimmeDerImpfaerzte,
    },
    {
      id: 'impfkritik',
      name: 'The Voice of the Vaccine Critics',
      stimme: 'DeepSeek',
      text: stimmeDerImpfkritik,
    },
  ],

  synthese: [
    '## Where the two voices meet',
    '',
    'First the common ground — and it is greater than the headlines of',
    'both sides suggest. Both voices acknowledge that smallpox was a',
    'scourge whose eradication in 1980 is one of the greatest deeds of',
    'medicine. Both name the same dark links of the chain: Newgate, the',
    'orphans, James Phipps, the syphilis of Rivalta, the itinerant',
    'vaccinators, the compulsion of the laws. Both agree that hygiene,',
    'water and nutrition initiated the decline of the diseases before',
    'vaccination. And both know that money is made with vaccines — one',
    'side calls it the price of research, the other the interest that',
    'must be checked. Whoever hears only one of these voices hears half',
    'the chain.',
    '',
    '## Where they part ways',
    '',
    'The contradiction begins with the interpretation of the same',
    'figures. The curves that fell before vaccination: for the',
    'vaccinating doctors they are the proof that medicine was only one',
    'factor among many — an honest concession that does not diminish',
    'their own achievement. For the critics they are the proof that the',
    'glory was given to vaccination that belongs to hygiene — and that',
    'the curves have not been looked at so closely since. They argue',
    'about the weight of the figures: how much of the decline was the',
    'vaccination, how much the water? The answer is not unambiguous, and',
    'that is exactly the point. They argue about compulsion: may the',
    'state intervene in the bodies of its citizens, even when it means',
    'well? The vaccinating doctors say: the community protects itself.',
    'The critics say: the individual is made into a means. And they',
    'argue about the open question of today: the children no longer have',
    'measles — but allergies, and nobody knows whether the one has',
    'anything to do with the other. Both sides face the same ignorance',
    'and draw opposite conclusions from it.',
    '',
    '## What this chapter shows for the whole book',
    '',
    'For the eleventh time the same pattern — and now with particular',
    'sharpness: the way of thinking determines the method. The way of',
    'thinking of prevention, which began with Jenner, transformed',
    'medicine: it turned the art of healing into a protective power that',
    'does not let the disease come at all. This way of thinking has',
    'saved millions of lives — and it has, like every way of thinking in',
    'this book, its blind spots: it measures success by the disease',
    'averted, but not by the trust it consumes, and not by the questions',
    'it leaves open.',
    '',
    'And this chapter shows for the first time a debate that is not',
    'conducted between two cultures but within the same medicine — and',
    'that is perhaps the most important thing it has to say: a medicine',
    'that treats its critics as enemies loses the trust on which it',
    'stands. The opponents of vaccination in Leicester were not stupid;',
    'they were distrustful because they had not been asked. Medicine',
    'learned from that — and forgot that it had learned. The question',
    'this chapter leaves behind is the question of the whole book: how',
    'much truth can a story bear that is meant to give courage? The',
    'answer: more than one thinks. The next chapter tells of two men who',
    'understood that — Pasteur and Lister, who found the cause of the',
    'infection that Semmelweis had seen without being able to name it.',
  ].join('\n'),

  urteil: {
    frage:
      'Whom do you trust when you have to decide whether a child should ' +
      'be vaccinated — the doctor, the state, the figures or your gut ' +
      'feeling? And what would have to happen for you to reconsider your ' +
      'opinion?',
    hinweis: [
      'There is no right and no wrong here, and this book pressures you',
      'into nothing. Ask yourself two things while thinking it over.',
      'First: what kind of evidence would convince you — a figure, an',
      'experience from your family, the judgment of a person you trust?',
      'Second: what would you demand of the other side so that you would',
      'listen to it — and do you meet that requirement yourself? Also',
      'consider that the decision has two sides: it concerns your own',
      'child, and it concerns the children of others. Both sides of this',
      'calculation are real.',
    ].join(' '),
  },

  quiz: [
    {
      frage: 'What was variolation, which became common in the 18th century?',
      antworten: [
        'A vaccination with cowpox material.',
        'The deliberate infection of a healthy person with real ' +
          'human smallpox.',
        'A herbal tea against fever.',
      ],
      richtig: 1,
      erklaerung:
        'In variolation, material from the pustule of a mildly ill ' +
        'person was brought into the skin of a healthy person. The ' +
        'procedure came from China, India, West Africa and the Ottoman ' +
        'Empire. It was dangerous — about one or two in a hundred died ' +
        'of it — but markedly less dangerous than a natural infection, ' +
        'which killed twenty to thirty in a hundred.',
    },
    {
      frage:
        'What did Edward Jenner vaccinate the eight-year-old James ' +
        'Phipps with on 14 May 1796?',
      antworten: [
        'With fluid from the cowpox on the hand of the cow maid Sarah ' +
          'Nelmes.',
        'With the blood of a recovered smallpox patient.',
        'With a powder made of dried smallpox scab.',
      ],
      richtig: 0,
      erklaerung:
        'Sarah Nelmes had caught cowpox while milking — a harmless ' +
        'cattle disease. Jenner placed fluid from it into two small cuts ' +
        'on the boy\'s arm. Six weeks later he tested the protection by ' +
        'variolating him with real human smallpox. By today\'s standards ' +
        'this experiment on a child would not be permissible.',
    },
    {
      frage:
        'How was the vaccine passed on over long distances in the ' +
        '19th century?',
      antworten: [
        'In refrigerated glass ampoules.',
        'From arm to arm: fluid from the pustule of the last person ' +
          'vaccinated went into the next arm.',
        'Through the drinking water of the cities.',
      ],
      richtig: 1,
      erklaerung:
        'There was neither refrigeration nor a durable preparation: the ' +
        'only reliable container was a living human being. For the trip ' +
        'to America, a Spanish expedition even took twenty-two orphan ' +
        'boys along in 1803 as a living chain. The way from arm to arm ' +
        'had a price: syphilis was transmitted along with the lymph, for ' +
        'instance in Rivalta in 1861. In England it was forbidden in ' +
        '1898.',
    },
    {
      frage: 'When did the World Health Organization declare smallpox eradicated?',
      antworten: ['1918', '1953', '1980'],
      richtig: 2,
      erklaerung:
        'The declaration came on 8 May 1980. The last person infected ' +
        'naturally was the hospital cook Ali Maow Maalin in Somalia on ' +
        '26 October 1977; he survived. To this day smallpox is the only ' +
        'human disease ever eradicated — among other things because it ' +
        'occurred only in humans and was always visible.',
    },
    {
      frage: 'What did the English vaccination law of 1898 bring?',
      antworten: [
        'It introduced compulsory vaccination for the first time.',
        'It allowed refusal on grounds of conscience and ended ' +
          'arm-to-arm vaccination.',
        'It forbade smallpox vaccination entirely.',
      ],
      richtig: 1,
      erklaerung:
        'Compulsory vaccination had existed in England since 1853 and ' +
        'had been tightened in 1867; against it arose the first great ' +
        'anti-vaccination movement, which brought tens of thousands of ' +
        'people onto the streets of Leicester in 1885. After a royal ' +
        'commission (1889–1896) had heard both sides, the law of 1898 ' +
        'brought the conscience clause — and forbade arm-to-arm ' +
        'transmission.',
    },
  ],
};

module.exports = jennerImpfung;
