// Chapter 10 — "Kneipp and Naturopathy".
//
// The ninth chapter of the modern era — and, after homeopathy, the second
// that lies especially close to the operator's heart: he is a naturopath
// (Heilpraktiker) and stands in this tradition himself. Hence the explicit
// rule from CLAUDE.md applies here: naturopathy is NOT derided and not
// dismissed as superstition. It receives its best arguments, its own way
// of thinking and its own voice — and it names its uncomfortable places
// itself.
//
// THE WAY-OF-THINKING ANALYSIS is the heart of the chapter (operator
// requirement). Here it asks: Why cold water? (Because the brief cold
// stimulus triggers a response of the body — vessels constrict, then
// dilate, then warmth; it is not the water that heals but the reaction to
// it.) Why movement? (Because the body is built for movement and decays
// in stillness.) Why nutrition? (Because what goes into a person daily
// acts more strongly than any remedy he takes rarely.) Why medicinal
// herbs? (Because the gentle gift is meant to support, not to compel.)
// Why order? (Because the way of life is the cause on which everything
// else hangs.) Above all stands the foundational assumption of all
// naturopathy: the self-healing power — vis medicatrix naturae.
//
// THE BRIDGE TO CHAPTER 18 (operator requirement): Kneipp's five pillars
// are the historical forerunner of the operator's thesis "The Simple
// Medicine" — movement, healthy nutrition, a good social environment and
// little stress. What the water priest preached a hundred and fifty years
// ago, modern medicine today recommends as prevention, usually without
// naming him. This bridge stands at the end of the voice, together with
// the honest counter-side (the structures that make a healthy lifestyle
// difficult).
//
// NO RUMOURS (operator decision 25.08.2026): Only what is documented.
// Stefansried 1821, Grönenbach and chaplain Merkle, Dillingen from 1844,
// Hahn's water book of 1738, the Danube baths in the winter of 1849, the
// ordination in 1852, Wörishofen from 1855, "Meine Wasserkur" in 1886,
// the death on 17 June 1897 — all on the record. The diagnosis of his
// student illness, by contrast, is historically NOT established (often
// handed down as tuberculosis); the text says so explicitly. Equally
// explicit: the self-healing in the cold water is a report, not proof.
// Unsubstantiated miracle stories are left out.
//
// THE INNOVATION CYCLE (operator observation 26.08.2026, red thread):
// Here too the pattern stands on its head. Naturopathy did not first
// harm and then help — it was gentle from the start. Its risk lies in two
// other places: in the harsh water cures of the early 19th century, which
// overtaxed people, and in what the cheap idea became once it had
// succeeded — a business. The voice names both itself.
//
// LENGTH RULE (operator feedback 24.08.2026): From chapter 9 on the
// reverse applies — complete and detailed. Measured in
// tests/karte-kneipp.mjs.
//
// Voices (round 18): The FIRST perspective — naturopathy from within, the
// voice of the water — was written by Opus. The SECOND (conventional
// medicine: its own arrogance toward the "water priest", the mocking
// instead of testing, the late recognition of the way of life as
// medicine, the state of the evidence and the honest criticism) and the
// final synthesis were added by Hermes in the second pass (Hermes pass,
// 28.08.2026: "supplemented"). Perspective workflow: CLAUDE.md.
//
// NO REPETITIONS (operator decision 21.08.2026): Chapter 1 is organised
// by "who speaks here", chapter 2 opens with a scene, chapter 3 tells a
// day's course, chapter 4 is an exchange of letters, chapter 5 the
// journey of a book, chapter 6 a tour, chapter 7 a trial, chapter 8 an
// invoice, chapter 9 a clock, chapter 10 a chain, chapter 11 a lens,
// chapter 12 an interview, chapter 13 a file, chapter 14 a package
// insert, chapter 15 a press conference, chapter 16 the telephone. This
// chapter chooses the eighteenth dramaturgy: THE WATER ITSELF. The rain
// over the Allgäu, the spring, the Danube at Dillingen, the trough in
// Wörishofen, the wading — the water tells what was done with it and what
// it does in the body. The second voice steps into the same form: the
// same water, but in the measuring glass — the question of what of it can
// be demonstrated.
//
// The texts are stored as line arrays joined with `.join('\n')` — this
// keeps them readable in the repo at around 72 characters (the operator
// proofreads them here), and utils/markdown.js turns them back into
// flowing text in the app.
//
// CommonJS without UI imports (architecture rule): testable with plain `node`.

/**
 * The Voice of the Water — naturopathy from within.
 *
 * Written by Opus (round 18). A voice that speaks for the side that works
 * with the cheapest means in the world, has had a following for a hundred
 * and fifty years and is still ridiculed: its way of thinking, its
 * history, its experience. It tells why it does what it does — and it
 * names the uncomfortable places itself (additional rule for sensitive
 * topics in CLAUDE.md).
 */
const voiceOfTheWater = [
  '## The Rain over the Allgäu',
  '',
  'I fall as rain over the Allgäu. First as mist hanging in the firs,',
  'then as drops that seep into the moss. Beneath the earth I gather,',
  'run through gravel and sand and emerge somewhere on a hillside —',
  'cold, clear, six or eight degrees, almost the same all year round.',
  'From there I go into a brook, into the Iller, into the Danube, into',
  'the Black Sea and eventually back into a cloud.',
  '',
  'On this journey I have passed through people again and again. I have',
  'stood in troughs in which the sick trampled up to their knees. I',
  'have run over backs from watering cans without a rose, backs that',
  'had never felt cold water before. I have lain in linen sheets that',
  'were wrapped around the bodies of the feverish. And once, in the',
  'winter of 1849, a young, very ill theology student climbed into me —',
  'into the Danube at Dillingen, between ice floes, for a few moments,',
  'several times a week. That man became a priest whom half the world',
  'knew.',
  '',
  '**What you read here is naturopathy from within — a way of thinking,',
  'not a truth.** I speak for the side that works with the cheapest',
  'means that exist: water, walking, bread, herbs, sleep. I will present',
  'its best reasons, as strongly as I can. And I will name the places',
  'where we stand badly myself, instead of waiting for someone else to',
  'do it.',
  '',
  'The question at stake is not, after all, whether I am wet. It is:',
  '',
  '**Can a person become healthy without being given anything — merely',
  'by living differently? And if so: why is that so hard to prescribe',
  'and so easily ridiculed?**',
  '',
  '## The Weaver\'s Son Who Ladled Me Up',
  '',
  '**On 17 May 1821 Sebastian Kneipp is born in Stefansried**, a hamlet',
  'of a few farmsteads near Ottobeuren in the Bavarian Allgäu. His',
  'father is a weaver. In that era that means: he sits at the loom in',
  'winter, earns little, and when the factories in Augsburg drive down',
  'prices, he earns nothing at all.',
  '',
  'The boy tends cattle, works in the fields as a day labourer and sits',
  'at the loom himself at the age of eleven. The village school teaches',
  'him reading, writing, arithmetic — and that was supposed to be that.',
  'But he wants to become a priest. For a weaver\'s son without Latin',
  'and without money, that is about as promising as a trip to the moon.',
  '',
  'Two things intervene. One is a misfortune: **According to tradition,',
  'the parental home burns down in 1841**, and with it the little that',
  'had been saved. The other is a person. In the neighbouring village of',
  'Grönenbach, **chaplain Matthias Merkle** gives him lessons in Latin',
  'and works to ensure that the young man sees the inside of a school.',
  '**In 1844 Kneipp is admitted to the Gymnasium in Dillingen on the',
  'Danube — twenty-three years old, among fourteen-year-olds.**',
  '',
  'I pause here for a moment, because this explains more than any',
  'theory. Everything this man later offers is free or almost free. A',
  'pour costs nothing. Walking barefoot costs nothing. A compress costs',
  'a linen sheet. The herbs grow by the roadside. A healing art for',
  'people who cannot pay a doctor is not invented at a desk. **It is',
  'invented by someone who could not pay one himself.**',
  '',
  '## The Danube at Dillingen, Winter 1849',
  '',
  'In Dillingen the late pupil catches up on the Gymnasium and',
  'afterwards continues his studies at the Lyceum. And somewhere in',
  'these years he falls ill. Seriously ill.',
  '',
  '**What has come down to us is a wasting lung complaint — cough,',
  'sputum, exhaustion, weight loss; usually it is made out to be',
  'tuberculosis. I say this expressly: that diagnosis is historically',
  'not established.** There is no finding, no X-ray image — X-rays are',
  'only born in 1895, as far as his rays are concerned —, no detection',
  'of a pathogen. What exists are descriptions of complaints and the',
  'assessment of the doctors of those years that this student would not',
  'grow old. No one knows more, and anyone who claims more is',
  'inventing.',
  '',
  '**In 1849 Kneipp comes across an old book**: the treatise of the',
  'Silesian town physician **Johann Siegmund Hahn (1696–1773)** with',
  'the unwieldy title "Unterricht von der Krafft und Würckung des',
  'frischen Wassers in die Leiber der Menschen" (Instruction on the',
  'power and effect of fresh water on the human body), **first printed',
  'in 1738**. Where exactly he found it — in the library in Dillingen,',
  'later in Munich — is reported differently; the book itself is',
  'undisputed.',
  '',
  'And then he does what people do who have nothing left to lose: **He',
  'tries it out on himself.** In winter he goes to the Danube, several',
  'times a week. He undresses, immerses himself for a few moments — no',
  'longer — and then runs at a trot back to his room, until he is warm.',
  '',
  'By his own account he becomes stronger, coughs less, gets through',
  'his studies and finally reaches the age of seventy-eight.',
  '',
  'Now comes the sentence my side does not like to write, but which',
  'belongs in this book: **That is not a proven healing. That is a',
  'report.** A single person, no comparison group, no measurement, no',
  'verified initial diagnosis. If it was not tuberculosis but a',
  'protracted inflammation that healed on its own, he might have',
  'recovered even without me. **I cannot rule that out, and I do not',
  'pretend I can.**',
  '',
  'What can be said is something smaller and still not nothing: A young',
  'man whom the doctors had given up began to do something for his body',
  'every day — cold bathing, running, rising early, simple food — and',
  'he felt better. From this experience grew a healing art that',
  'millions of people have used. **Whether the experience was',
  'interpreted correctly is the real question of this chapter.**',
  '',
  '## Two Who Stepped into Me Before Him',
  '',
  'So that no false impression arises: **Kneipp did not invent me.**',
  'People have bathed for as long as there have been people, and cold',
  'water as a remedy is as old as the healing art itself. The Greek',
  'physicians knew it, the Roman baths lived on it, and in the',
  'monasteries of this book the bath belonged to nursing care.',
  '',
  'Two names stand directly before him.',
  '',
  'One is **Johann Siegmund Hahn**, whose 1738 book fell into Kneipp\'s',
  'hands. Hahn was a trained physician and wrote against the fashion of',
  'his time: instead of bloodletting and purging he recommended cold',
  'water, internally and externally. He was largely ignored.',
  '',
  'The other is **Vincenz Prießnitz (1799–1851)**, a farmer\'s son from',
  'Gräfenberg in Austrian Silesia, who ran a water-cure establishment',
  'from the 1820s and drew guests from half of Europe — without any',
  'medical training, against which the medical profession took legal',
  'action.',
  '',
  'And here, straight away, the first uncomfortable place I open up',
  'myself: **The water cures of those decades were often brutal.**',
  'Hour-long packs, ice-cold plunge baths from great heights, cures',
  'that exhausted the sick instead of strengthening them. There were',
  'water doctors who treated with the same harshness with which',
  'conventional medicine bled people — only with me instead of the',
  'knife. **Anyone who believes the gentle medicine was always gentle',
  'has not read the nineteenth century.**',
  '',
  'What is remarkable about Kneipp is precisely that he learned from',
  'this mistake. He himself began hard — the Danube in January is no',
  'child\'s bath — and over forty years became steadily gentler. **Short',
  'stimuli instead of long ones. Cold only on the warm body. Never',
  'until one shivers. Afterwards movement, until the warmth returns.**',
  'That is not a watering down of his teaching, it is its core: a',
  'stimulus should nudge the body, not overtax it.',
  '',
  '## The Chaplain Who Went to the Cholera Patients',
  '',
  '**In 1850 Kneipp goes to Munich to complete his studies; on',
  '6 August 1852 he is ordained a priest in Augsburg.** Years as a',
  'chaplain follow in Biberbach and in **Boos in the Illertal**.',
  '',
  'There, in 1854, he faces a wave of cholera. He nurses the sick,',
  'enters the houses, provides for them and also applies water',
  'treatments. Afterwards the villagers call him the "cholera',
  'chaplain".',
  '',
  '**What these treatments achieved medically, I do not know, and I do',
  'not claim it either.** Cholera kills through fluid loss; what helps',
  'is drinking — that one can do it much better with salt and sugar in',
  'the water was only understood in the 20th century. A clergyman who',
  'gave the sick water and washed them may thus have done exactly the',
  'right thing without knowing why. But it may also be that the',
  'survivors would have survived anyway.',
  '',
  'Something else is documented, and it counts more for this story: **He',
  'went to them.** In a time when many avoided the houses of the',
  'cholera patients, this chaplain sat at their bedsides. The',
  'reputation that later preceded him does not begin with a healing.',
  'It begins with someone who stayed.',
  '',
  '**In May 1855 Kneipp is transferred to Wörishofen as confessor to',
  'the Dominican nuns** — a village of a few hundred inhabitants',
  'between the Wertach and the Mindel. He stays forty-two years and',
  'never leaves it again. He administers the monastery estate, holds',
  'farming courses for the peasants, breeds bees, tends fruit trees —',
  '**and treats the sick who ask him to.** First neighbours. Then',
  'people from the surrounding area. Then strangers. **In 1881 he',
  'becomes the parish priest of the place.**',
  '',
  '## What I Do in the Body — and What Not',
  '',
  'Now to the core. Why should I, of all things, ordinary cold water,',
  'be able to heal anything?',
  '',
  'The answer of naturopathy begins with a sentence that carries',
  'everything else — and that is two thousand years old. It comes from',
  'the school of Hippocrates and is called **vis medicatrix naturae:',
  'the healing power of nature.** In plain English and without the',
  'Latin:',
  '',
  '**The body heals itself. All a practitioner can do is not stand in',
  'its way — and to support it.**',
  '',
  'That is not piety, that is observation. A cut closes. A bone knits',
  'together. A cold goes away after a week, with treatment after seven',
  'days. No doctor and no priest does that; they create conditions.',
  '**The self-healing power is the only power in this reckoning that',
  'heals at all. Everything else is a nudge.**',
  '',
  'From this follows a different concept of illness. According to this',
  'way of thinking, illness is not a thing one receives like a letter,',
  'but the indication that a balance is disturbed: between exertion and',
  'rest, between warmth and cold, between eating and hunger, between',
  'work and sleep. **The sick person is not afflicted, he is out of',
  'balance.** And the treatment does not work against the illness, but',
  'for the power that brings the person back into balance.',
  '',
  'And now the actual question:',
  '',
  '**Why cold water?**',
  '',
  'Because I am a **stimulus** and nothing else. I contain no active',
  'ingredient. I am water. What I do is not done by the water, but by',
  '**the body\'s response to it** — and that response has been',
  'observable for as long as there have been people, and today it is',
  'also measurable:',
  '',
  '- When I hit the skin cold, the small vessels constrict. The blood',
  '  retreats inward, into the depths, to the organs.',
  '- The stimulus lasts only a short time — with Kneipp, seconds. Then',
  '  I am gone again.',
  '- And now comes the essential part: The body answers with a',
  '  **counter-movement**. The vessels dilate, the blood rushes back',
  '  into the skin, it turns red and warm, the person feels suffused.',
  '  This warmth does not come from me. **I am cold. The warmth he',
  '  makes himself.**',
  '',
  'That, precisely, is the logic of the whole Kneipp cure, and it can',
  'be said in one sentence: **It is not the application that works,',
  'but the reaction to the application.** Hence the iron rule that',
  'Kneipp drummed into his people — and that everyone should know who',
  'wants to take cold showers:',
  '',
  '- **Cold only on the warm body.** Whoever is shivering has nothing',
  '  to answer with.',
  '- **Short, not long.** The stimulus is a nudge, not a test.',
  '- **Afterwards movement or bed, until the warmth is back.** If it',
  '  fails to return, the application was wrong.',
  '',
  'And why the constant alternation of warm and cold, the alternating',
  'pours, the alternating baths? Because a vessel is a muscle like any',
  'other: **What is regularly exercised becomes more practised.**',
  'Naturopathy calls this **hardening** and does not mean hardness, but',
  'adaptability — that a body learns to cope better with cold, heat,',
  'draughts and exertion when it knows them.',
  '',
  'And now the honest balance sheet, because without it this would be',
  'advertising.',
  '',
  '**What is well documented:** Cold constricts and warmth dilates the',
  'vessels — that has been measured. A cold stimulus briefly raises the',
  'heart rate, breathing and the release of stress hormones; the body',
  'switches to alertness. Regular cold stimuli measurably change how',
  'quickly and how well a person warms up again afterwards.',
  '',
  '**What is weakly documented:** that health in the large emerges from',
  'it. There are a few nice studies — the best known is a Dutch study',
  'from 2016 in which more than three thousand people ended their',
  'showers cold for a month; in the cold-shower group, sick leave was',
  'about twenty-nine per cent lower, while the number of sick days did',
  'not differ. **Interesting, yes. Proof of a healing method, no.**',
  '',
  '**What is not documented at all:** that pours and compresses cure',
  'specific diseases. For the individual applications there are small',
  'studies, often without a comparison group, almost never blinded —',
  'one can hardly secretly pour cold water over a person\'s back.',
  '**Anyone from my side who claims that the effectiveness of the',
  'Kneipp applications is scientifically proven is telling an',
  'untruth.** What is proven is something else, and I will return to it',
  'at the end: the effect of what stands around me.',
  '',
  '## The Gentle Hand: Pours, Compresses, Wading',
  '',
  'What did that look like in practice? Kneipp described around a',
  'hundred applications, all feasible with household remedies. A few of',
  'them you still encounter today:',
  '',
  '**The pour (Guss).** A jug without a rose, the water runs as a',
  'connected mantle over the skin — knee pour, thigh pour, arm pour,',
  'back pour, face pour. Always begin far from the heart, i.e. on the',
  'outside of the right foot; the heart should know what is coming.',
  'The knee pour is the most famous, because it demands little and',
  'achieves much: cold feet, restless sleep, heavy legs.',
  '',
  '**Wading.** Walking in the shallow basin with a stork step — lift',
  'the foot fully out of the water, set it back in — until it draws in',
  'the calves, then out, shake off, walk. That is the application you',
  'find in every spa park today.',
  '',
  '**The compress.** A damp linen sheet around calf, neck or torso, a',
  'dry one over it. Calf compresses for fever belong to child care in',
  'Germany to this day and even appear in medical guides.',
  '',
  '**Walking in the dew and in the snow.** Barefoot through wet grass',
  'or briefly through fresh snow, then socks on and walk. Kneipp',
  'considered it one of the best applications of all — and it costs',
  'nothing.',
  '',
  '**The wash and the steam.** A quick wash of the body with cold water',
  'in the morning; steam baths for head, feet or lower abdomen with',
  'hayflowers or chamomile.',
  '',
  'What all these applications share is the signature of the later',
  'Kneipp: **short, mild, repeated.** Not the one great cure, but the',
  'small habit. He explicitly set this against his own beginnings — the',
  'man who had bathed in the Danube between ice floes later advised old',
  'people to use lukewarm water.',
  '',
  '## The Second Stream: Movement',
  '',
  'And now the point at which most people are surprised. Kneipp became',
  'famous as the water priest — **but water is only one of five',
  'pillars**, and he himself did not even consider it the most',
  'important. The other four are movement, nutrition, medicinal herbs',
  'and order.',
  '',
  '(A footnote of honesty: **Kneipp did not write down the division',
  'into "five pillars" himself.** It is a later ordering by his',
  'successors, which nevertheless summarises well what stands in his',
  'books. I use it because it is helpful, not because it comes from',
  'him.)',
  '',
  '**Why movement?**',
  '',
  'The answer is so simple that it is often overlooked: **Because the',
  'body is built for movement.** A heart that is never challenged grows',
  'weak. A muscle that never pulls wastes away. A bone that is never',
  'loaded gives off lime. Joints are not nourished by blood but by',
  'movement — the cartilage soaks itself full like a sponge when it is',
  'compressed and relieved. **Stillness is not the sparing of the body.',
  'It is its breakdown.**',
  '',
  'Kneipp prescribed walking, walking barefoot, garden work, chopping',
  'wood, gymnastics in the open air. None of it was new; what was new',
  'was that he **prescribed** it — as therapy, with measure and',
  'instruction, not as a friendly piece of advice at the end.',
  '',
  '**The modern equivalent is so clear that it is almost boring.** The',
  'World Health Organization recommends adults at least a hundred and',
  'fifty minutes of moderately strenuous movement per week. Movement',
  'demonstrably lowers the risk of heart attack, stroke, type 2',
  'diabetes, several kinds of cancer, depression and dementia; it',
  'improves blood pressure, blood sugar and sleep. **Not a single drug',
  'in the world has such a broad profile of effects with so few side',
  'effects.** That is not naturopathy speaking. That is conventional',
  'medicine, in its own guidelines.',
  '',
  '## The Third Stream: Nutrition',
  '',
  '**Why nutrition?**',
  '',
  'Because it is the only substance a person takes in **every day**. A',
  'tablet one takes once, perhaps three times. Food one takes three',
  'times daily, seven times a week, a lifetime. **What goes in daily',
  'acts more strongly than what goes in rarely — if only for reasons',
  'of quantity.**',
  '',
  'Kneipp\'s kitchen was that of an Allgäu parsonage and sounds',
  'astonishingly modern to today\'s ears: **coarse bread instead of',
  'fine, much grain, vegetables and fruit, milk, little meat, little',
  'alcohol, little sugar, no excessive coffee — and above all: not too',
  'much of anything.** He fought against two things he saw daily: the',
  'schnapps drinking and the gluttony of the well-to-do.',
  '',
  'His measure was **simplicity**, not asceticism. He proclaimed no',
  'wonder diet and demonised no foods. He said: simple, fresh, from',
  'nearby, in moderation — and eaten calmly.',
  '',
  '**The modern equivalent:** The nutrition research of the last half',
  'century has arrived at almost the same picture. The large Spanish',
  'PREDIMED study showed in 2013 and in the re-analysis of 2018 that a',
  'Mediterranean diet with olive oil and nuts made heart attacks and',
  'strokes markedly rarer. Dietary guidelines all over the world today',
  'advise plenty of vegetables, plenty of whole grains, pulses, little',
  'red and processed meat, little sugar and few highly processed',
  'foods. **That is, in other words, the kitchen of an Allgäu priest',
  'of 1890.**',
  '',
  '## The Fourth Stream: The Medicinal Herbs',
  '',
  '**Why medicinal herbs?**',
  '',
  'Because according to this way of thinking they **support instead of',
  'compel**. A plant does not bring one isolated substance in high',
  'dosage, but many in small ones — and the body is meant to cope with',
  'them itself. Kneipp used what grows in the Allgäu: yarrow,',
  'horsetail, juniper, sage, chamomile, arnica, wormwood, linden',
  'blossom, hayflowers as steam and compress. He had teas drunk,',
  'compresses made, oils rubbed in.',
  '',
  'This pillar is the oldest in this book — it leads back to',
  'Hildegard\'s monastery gardens, to Ayurveda, to the Chinese teaching',
  'of herbs and to the women healers who came before them all.',
  '',
  'And at the same time it is the pillar with the **most mixed record**,',
  'and in both directions:',
  '',
  'Upward: A good part of the modern medicine cabinet comes from this',
  'knowledge — quinine from the cinchona bark, digitalis from the',
  'foxglove, morphine from the poppy, aspirin from the willow bark.',
  'And even today individual plants withstand the rigorous test: St',
  'John\'s wort works for mild to moderate depression in controlled',
  'studies about as well as conventional antidepressants.',
  '',
  'Downward: **For most of the herbs Kneipp used, there is to this day',
  'no convincing test of effectiveness.** Horsetail as a diuretic,',
  'juniper as a blood purifier — those are experiential values, not',
  'evidence. And a warning belongs here that my side utters far too',
  'rarely: **"Herbal" does not mean "harmless".** Foxglove kills,',
  'comfrey can damage the liver, St John\'s wort weakens the effect of',
  'the pill and of many other medicines. Whoever holds herbs for',
  'automatically safe has not understood pharmacology — and of all',
  'people my side ought to know it best.',
  '',
  '## The Fifth Stream: Order',
  '',
  'And now the pillar that Kneipp himself held for the most important',
  'and that comes last in every brochure, because it is the hardest to',
  'sell.',
  '',
  '**Why order?**',
  '',
  'Because according to this way of thinking **the way of life is the',
  'cause on which everything else hangs.** One can make pours, drink',
  'herbs and take walks — if a person sleeps four hours every night,',
  'lives in constant worry, never rejoices and talks to no one, he',
  'will remain ill. **The application treats the body. Order treats',
  'the life that makes it ill.**',
  '',
  'Kneipp meant something very concrete: a regular day with fixed times',
  'for work, eating and sleep; enough sleep, and at night; measure in',
  'everything, even in the good; work, but not without end; joy,',
  'community, a clear conscience. As a priest he naturally also spoke',
  'of the soul and of God. One need not share that part to see what he',
  'was driving at: **A person who is inwardly torn will not become',
  'outwardly healthy.**',
  '',
  '**The modern equivalent is the youngest and perhaps the most',
  'astonishing.** Chronobiology has shown that almost every cell of the',
  'body possesses an internal clock and that its disturbance — shift',
  'work, constant sleep deprivation, light at night — changes blood',
  'pressure, sugar metabolism and the immune system; for the',
  'elucidation of this clock there was the Nobel Prize in Medicine in',
  '2017. Stress research has measured the connection between chronic',
  'strain and heart disease. And a large review from 2010 came to the',
  'result that people with sound social relationships live markedly',
  'longer — an effect on the order of giving up smoking.',
  '',
  '**The priest of Wörishofen had no study for "order". He had only',
  'the impression that people fall ill when their lives are out of',
  'joint. Research took a hundred years to prove him right on this',
  'point.**',
  '',
  '## The Book That Made a Village a Town',
  '',
  '**In 1886 "Meine Wasserkur" (My Water Cure) appears with Kösel in',
  'Kempten.** It is not a learned work but a manual: applications,',
  'herbs, clinical pictures, in a language every farmer understands.',
  'Precisely for that reason it becomes a bestseller — numerous',
  'editions in his lifetime, translations into many languages. **In',
  '1889 "So sollt ihr leben" (Thus Shall You Live) follows**, in which',
  'order and the conduct of life move to the fore.',
  '',
  'And then something happens that nobody planned. **The people',
  'come.** First dozens, then hundreds, then thousands. A village of a',
  'few hundred inhabitants has to accommodate tens of thousands of',
  'guests a year; the exact figures diverge in the sources, the order',
  'of magnitude does not. Guesthouses arise, bath houses, a rail',
  'connection. Nobles stand in line beside peasants, because Kneipp',
  'treated both without distinction.',
  '',
  'He himself gives lectures, often several times a day, in the spa',
  'hall, in the church, in the open air. **From 1890, Dr. Alfred',
  'Baumgarten, a licensed physician, works in the town as spa',
  'doctor** — at Kneipp\'s own wish, and this point is important enough',
  'for a section of its own further below. **In 1893 Pope Leo XIII',
  'appoints the priest a papal secret chamberlain; in 1894 he is',
  'received in Rome.** In 1896 the Kneippianum arises in Wörishofen.',
  '',
  '**On 17 June 1897 Sebastian Kneipp dies in Wörishofen, six weeks',
  'after his seventy-sixth birthday.** He leaves no fortune; the income',
  'from the books went into foundations and houses. **In 1920 the place',
  'is allowed to call itself Bad Wörishofen.**',
  '',
  'More has remained than a village priest could have expected: several',
  'dozen recognised Kneipp spa towns in Germany, Kneipp associations',
  'in several countries, wading pools in almost every German spa park,',
  'Kneipp kindergartens — and **in 2021 the inscription of Kneipping',
  'on UNESCO\'s Representative List of the Intangible Cultural Heritage',
  'of Humanity.**',
  '',
  '## The Mockery from the Other Shore',
  '',
  'And all the while, people laughed.',
  '',
  '"Water priest" was no honorific title when the word arose; it was',
  'derision. Kneipp was a weaver\'s son without medical training who',
  'treated the sick — for the rising academic medicine of the late 19th',
  'century that was an affront. There was mockery in professional',
  'journals and in the press, there were complaints for unauthorised',
  'medical treatment, there were medical assemblies that turned',
  'against "quackery".',
  '',
  'Legally, he nevertheless stood well, and that has to do with the',
  'penultimate chapter of this book: **The trade regulations',
  '(Gewerbeordnung) of the North German Confederation of 1869, valid',
  'throughout the German Empire from 1871, brought the so-called',
  'freedom of healing (Kurierfreiheit).** Anyone could heal; only the',
  'person who was licensed might call himself "doctor". That is the',
  'legal reason why Kneipp existed — and why there are naturopaths',
  '(Heilpraktiker) in Germany to this day.',
  '',
  '(For the sake of completeness, because this book omits nothing: **The',
  'freedom of healing ended in 1939 with the Heilpraktiker law** of',
  'the Nazi state, which regulated the profession for the first time',
  'and at the same time was meant to wind it up. That the profession of',
  'the Heilpraktiker owes its present legal form to a law from that',
  'era is an uncomfortable fact for my side. It belongs here, even if',
  'it pleases no one.)',
  '',
  'But now the fairness this book demands, and I mean it seriously: **The',
  'doctors had reasons.** One has to look at where medicine stood',
  'around 1890. It had just — in chapters 9 to 12 of this book — won',
  'anaesthesia, antisepsis, the germ theory and the X-rays. For the',
  'first time in history a doctor could say **why** a treatment works.',
  'And in exactly that moment a priest from the Allgäu drew tens of',
  'thousands to him without knowing a single one of these procedures.',
  '',
  'From their point of view that was dangerous: a man without training',
  'makes diagnoses. People with appendicitis might go into the water',
  'basin instead of to the surgeon. **This objection was not',
  'professional arrogance, it was justified** — and it still is today.',
  '',
  'What took the harshness out of it was Kneipp\'s own attitude: He did',
  'not seek the doctors as opponents. He brought Dr. Baumgarten into',
  'the town, worked with him, had the sick examined and sent on what',
  'did not belong in his hands. **The water priest did not seek the',
  'dispute. He got it.**',
  '',
  '## What Kneipp Himself Never Claimed',
  '',
  'Because today he is claimed for all sorts of things, here are four',
  'things he did **not** say:',
  '',
  '**He was no miracle healer.** He promised no healing and sold no',
  'secret remedy. His applications stood in a book that anyone could',
  'buy for little money — the worst conceivable business idea for a',
  'charlatan.',
  '',
  '**He was no enemy of conventional medicine.** He referred people',
  'with serious illnesses to doctors, worked with a spa doctor and',
  'never disputed surgery. Whoever today invokes him as a star witness',
  'against medicine is using a man who can no longer defend himself.',
  '',
  '**He did not hold cold water for a panacea.** It is one of five',
  'pillars, and he himself placed order higher.',
  '',
  '**And he never claimed to have proven it.** He was a priest, not a',
  'researcher. He observed, tried out, corrected and wrote down, over',
  'forty years and on very many people. That is an honourable way of',
  'arriving at knowledge. **It is just not the same as proof, and we',
  'should stop pretending.**',
  '',
  '## The Murky Water: What My Side Must Blame Itself For',
  '',
  'And so to the list that stands in no Kneipp brochure. The TONE rule',
  'of this book requires that every side names its own uncomfortable',
  'places itself — here are mine.',
  '',
  '**First: the lack of evidence.** For the individual procedures —',
  'pours, compresses, wading, steam baths — the state of the studies',
  'is thin: small case numbers, rarely comparison groups, almost never',
  'blinding. There are hints, there is experience, there are satisfied',
  'patients. **A robust proof of effectiveness in the modern sense does',
  'not exist for most applications.** One can argue about whether a way',
  'of life can be tested like that at all — but that is an argument',
  'about the method, not a substitute for the result.',
  '',
  '**Second: the miracle-cure promise-makers.** At the edge of my side',
  'stand people who do exactly what Kneipp never did: promise healing.',
  'Detox cures against everything, miracle drops, "purification" of',
  'the blood, devices with invented physics. **There is charlatanry in',
  'naturopathy, and it is dangerous.** It is dangerous for the sick',
  'who spend their money on it, and it is dangerous for all serious',
  'practitioners who afterwards are thrown into the same pot. We have',
  'distanced ourselves from it too rarely and too quietly.',
  '',
  '**Third: the lost time.** That is the heaviest accusation, and it',
  'hits. A person with chest pain, with blood in the stool, with a',
  'growing lump, with a high fever that will not yield belongs not in',
  'the wading pool. He belongs at the doctor\'s immediately. **There are',
  'documented cases in which people with curable diseases were treated',
  '"naturopathically" for so long that a cure was no longer',
  'possible.** The gentleness of my means is no permission to wait.',
  '**Where time decides over life, my responsibility ends** — and',
  'whoever sees it otherwise harms naturopathy more than any critic.',
  '',
  '**Fourth: out of the idea came a business.** This book observes a',
  'cycle: **The new often harms first before it becomes a blessing** —',
  'surgery killed through wound fever before it saved, the rays killed',
  'their pioneers, penicillin created the resistance. **With',
  'naturopathy the cycle runs differently**, and I do not want to gloss',
  'over it but to describe it correctly: it was not first harmful and',
  'then a blessing; it was gentle from the beginning. Its harm came',
  'from two other sides. First from the harshness of the early water',
  'doctors, who overtaxed the sick. And then from the fact that a',
  'thing that costs nothing becomes irresistible as soon as money can',
  'be made from it.',
  '',
  'As early as 1891 a company arose in Würzburg that was allowed to',
  'use Kneipp\'s name for its products. Out of it has become a brand',
  'that today sells bath additives and creams. In many places the cure',
  'has become wellness: feel-good package, pour ceremony, spa tax. **I',
  'do not say that is disreputable — people are allowed to spend money',
  'on their wellbeing.** I say that something is lost in the process:',
  '**Kneipp\'s healing art was meant for the poor. When it costs two',
  'hundred euros a night, it is no longer his.**',
  '',
  '**Fifth: the convenience of the holistic.** "I treat the whole',
  'person" sounds good and can be an excuse — for not looking closely,',
  'for not making a diagnosis, for blaming every failure on the',
  'patient\'s conduct of life. **Whoever can explain everything',
  'explains nothing.**',
  '',
  '## What the Rain Has to Do with Your Life',
  '',
  'And now the place where this chapter steps out of history.',
  '',
  'Take Kneipp\'s five pillars and strike out the water and the herbs.',
  'What remains are three things: **Movement. Nutrition. Order — that',
  'is, sleep, moderation, little worry and people around you.**',
  '',
  'That is, almost word for word, the answer that modern preventive',
  'medicine today gives to the most common diseases of our time. The',
  'World Health Organization estimates that a very large part of the',
  'chronic diseases — the order of magnitude is usually given as',
  'seventy to eighty per cent — is connected with the way of life. The',
  'British DiRECT study showed in 2018 that in a considerable part of',
  'the patients a type 2 diabetes disappeared again through weight',
  'loss — after one year in almost half of the participants, entirely',
  'without medication. The research on exceptionally long-lived',
  'populations again and again finds the same ingredients: plenty of',
  'everyday movement, simple plant-based fare, strong social bonds,',
  'little haste.',
  '',
  '**For all of that no rocket science is needed.** It needs a person',
  'who walks instead of drives, who cooks instead of tearing open, who',
  'sleeps instead of scrolling and who has someone to talk to. And it',
  'is possible that more health could be gained with that than with',
  'the newest preparations.',
  '',
  'But I would be a bad voice if I stopped here, because now comes the',
  'objection, and it is strong:',
  '',
  '**It is easy to say.** Whoever works shifts cannot order his day.',
  'Whoever has two jobs does not cook fresh. Whoever has little money',
  'buys the cheap food, and the cheap food is the processed one.',
  'Whoever is alone cannot prescribe himself a community. And against',
  'a food industry that spends billions so that people eat more, no',
  'good resolution helps. **"Self-responsibility" can be a liberating',
  'word — and a tool for blaming the sick for their illness. One must',
  'keep the two apart.**',
  '',
  'Added to this is the uncomfortable question about money that the',
  'chapter on the pharmaceutical industry has posed: On a pill someone',
  'earns. On a walk no one earns. **A piece of advice for which there',
  'is no market has no lobby** — and that perhaps explains better than',
  'any professional arrogance why the simple is so rarely prescribed.',
  'This thought is so big that it gets a chapter of its own: **Chapter',
  '18 of this book, "The Simple Medicine".**',
  '',
  '## Where I Flow into the Other Voice',
  '',
  'I have here said everything I can say for my side, and I have tried',
  'to conceal nothing that speaks against it.',
  '',
  '**The second voice of this chapter belongs to conventional',
  'medicine.** It will tell the same story from the measuring glass,',
  'and it has good reasons for it. It will say: **Show me the study.**',
  'It will lay out the thin state of the studies on the individual',
  'applications, it will remind us how many people have died of',
  'diseases that one does not cure by waiting, and it will defend the',
  'boundary behind which a diagnosis may no longer be a feeling.',
  '',
  'And it will — if it is as honest as the voices of the chapters',
  'before — **also open up its own dark places**: that it mocked a',
  'priest instead of testing him; that it held the way of life for',
  'decades to be a matter for the spa brochure and not for medicine;',
  'and that today it writes movement, nutrition and stress reduction',
  'into its guidelines without naming the name of the one who started',
  'it.',
  '',
  'I am only water. I decide nothing. I fall as rain, gather in a',
  'spring, run through a trough in Wörishofen and evaporate again. The',
  'question that remains you must settle among yourselves:',
  '',
  '**What heals more — the pill or the way of life? And who actually',
  'decides what of it is prescribed?**',
].join('\n');

/**
 * The Voice from the Measuring Glass — conventional medicine.
 *
 * Written by DeepSeek (Hermes pass, round 18). The same dramaturgy as
 * the first voice: the water, but this time in the measuring glass of
 * the laboratory — examined, measured, tested for active ingredients.
 * This voice represents the diagnosis, the study, emergency medicine —
 * and it first opens up its own dark past toward the water priest
 * (additional rule for sensitive topics in CLAUDE.md).
 */
const voiceFromTheMeasuringGlass = [
  '## The Measuring Glass in Which There Is No Rain',
  '',
  'Picture the water from before again. The same rain, the same',
  'spring, the same trough in Wörishofen. But now the water no longer',
  'stands in the trough — it stands in a measuring glass, on a',
  'laboratory bench, between pipettes and protocols.',
  '',
  'We are the voice from the measuring glass: conventional medicine.',
  'We are the ones who examine the water before recommending it. And',
  'we begin with what the voice of the water has demanded of us — with',
  'our own dark places, because the rule of this book applies to us',
  'too.',
  '',
  '**We mocked the water priest instead of testing him.** That stands',
  'at the beginning, and it stays standing. The medical profession',
  'smiled at and derided a man who had helped thousands — and it did',
  'so without even examining his applications. One must say it as',
  'harshly as it was: **The mockery was no science. It was',
  'professional arrogance in a white coat.** We have learned from this',
  'mistake — late, and without admitting it.',
  '',
  'And then we say what the measuring glass shows when one honestly',
  'looks into it.',
  '',
  '## What Is in the Water — and What Not',
  '',
  'The measuring glass is incorruptible, and it shows first what the',
  'voice of the water itself conceded: **In a glass of water there is',
  'water.** H₂O, a few dissolved minerals, nothing one could prescribe',
  'as medicine. Kneipp\'s pours and compresses are not medicines — they',
  'are stimuli. Cold on the skin, warmth afterwards, circulation,',
  'breath, attention. That is real, and it is not nothing. But it is',
  'something other than a substance with a proven effect.',
  '',
  'And here begins our first honest demarcation: **The individual',
  'water applications — the wading, the pours, the compresses — have a',
  'thin state of the studies.** There are observations, experience',
  'reports, traditions. There are hardly any controlled studies',
  'proving that precisely this cold water at precisely this place',
  'improves precisely this disease. The voice of the water did not',
  'dispute that — it said it itself. We say it from the measuring',
  'glass: **What one cannot measure one cannot prove. And what one',
  'cannot prove one must not sell as proven.** That applies to Kneipp',
  'as to anyone else.',
  '',
  '## The Streams We Ourselves Missed',
  '',
  'And then the second side of the measuring glass, which we like',
  'less — because it concerns us.',
  '',
  '**Movement is proven.** The state of the studies is unambiguous:',
  'regular movement lowers the risk of heart disease, diabetes, many',
  'kinds of cancer, depression — more strongly than most individual',
  'medicines. **Nutrition is proven.** Little processed, plenty of',
  'vegetables, measure instead of excess — the data on this one',
  'recommendation are as strong as on hardly any drug. **Stress',
  'reduction is proven.** Chronic stress makes ill, that is no longer',
  'an esoteric sentence but endocrinology. And sleep, and the order of',
  'the day, and the social environment: all proven, all in the',
  'guidelines.',
  '',
  '**And who said it first? A priest in Wörishofen whom we called a',
  'quack.** Modern preventive medicine today writes into its',
  'guidelines what Kneipp preached — movement, nutrition, order,',
  'measure — and does not name him. That is no coincidence and no ill',
  'intent, it is simply forgetting. But it is a forgetting with',
  'direction: we adopted the message and forgot the messenger. **The',
  'measuring glass measures that too — and it does not look good for',
  'us.**',
  '',
  '## The Water We Fought Against',
  '',
  'And then a story that must not be missing from this chapter,',
  'because it shows how close the two sides came to each other —',
  'without noticing.',
  '',
  'The conventional medicine of the nineteenth century fought against',
  'the same water that Kneipp prescribed as medicine. The cholera came',
  'over the water. In 1854 the London physician John Snow discovered',
  'that the sick drank from a single street pump — he had the handle',
  'of the pump removed, and the epidemic ended. The bacteriology of',
  'Robert Koch found the pathogens in the water, the hygiene movement',
  'built sewers, filtered the drinking water, fought typhus. **The',
  'water was for us the danger. For Kneipp it was the medicine. Both',
  'were right — it was the same water.**',
  '',
  'And precisely here it shows how deep the trench was: While we',
  'learned what in the water makes ill, Kneipp taught what about the',
  'water makes healthy. One side saw the pathogen, the other saw the',
  'stimulus. One built filters, the other built troughs. **Both',
  'improved people\'s health — and both did not understand each',
  'other.** The cholera has disappeared in Europe because we made the',
  'water clean. The health of many people has become better because',
  'Kneipp sent them into the cold water. The one is proven like hardly',
  'anything in the history of medicine. The other is proven — through',
  'a hundred and fifty years of experience and through modern',
  'preventive medicine, which today says what he said.',
  '',
  '**Perhaps that is the real lesson of this chapter: Conventional',
  'medicine and naturopathy met at the water without recognising each',
  'other.** One saw the danger in the water, the other the power. And',
  'the health of today — which is so much better than that of then —',
  'owes itself to both.',
  '',
  '## The Late Homecoming: Lifestyle Medicine',
  '',
  'And then the development that occupies us most, because it concerns',
  'us: **Conventional medicine is slowly catching up with the way of',
  'life — as a new specialty, as if it were an invention.**',
  '',
  'There are by now chairs for preventive medicine, research centres',
  'for nutrition, guidelines for movement. The World Health',
  'Organization estimates that a large part of the chronic diseases',
  'would be avoidable through lifestyle factors. "Lifestyle medicine"',
  'calls a new field — as if nobody had thought of it before. **And who',
  'thought of it first? The priest of Wörishofen.**',
  '',
  'That is no nostalgia and no bitterness. It is a balance sheet: We',
  'have written the way of life into the guidelines without adopting',
  'the way of thinking that belongs to it. A guideline says what is to',
  'be done. It does not say how one accompanies a person in doing it.',
  'Kneipp did both — he not only told the person what he should do, he',
  'did it with him, day for day, in a community, with a goal. **That',
  'is the part of Kneipp medicine we have not yet adopted: not the',
  'recommendation, but the accompaniment.**',
  '',
  '## The Boundary We Defend',
  '',
  'And then the boundary behind which we do not give way, because it',
  'is about life.',
  '',
  'The voice of the water named it itself: the appendicitis that does',
  'not heal with a pour; the pneumonia that needs time and',
  'antibiotics; the heart attack that no longer waits for an order',
  'therapy. **There are diseases in which waiting kills — and in which',
  'the diagnosis must not be a matter of feeling.** We have already',
  'told in this book what happens when people go to the doctor too',
  'late: chapter 11 showed the surgery, chapter 12 the vaccination,',
  'chapter 17 the pandemic. Medicine has its dark sides — but it has',
  'also saved the one thing naturopathy cannot do: the acute rescue.',
  '',
  'And therefore we defend the diagnosis. Not the white coat, not the',
  'prescription, not the system — the diagnosis. **Whoever can say',
  'what a person has can decide what he needs. Whoever only feels it',
  'cannot.** Kneipp himself knew that: he referred to doctors in',
  'serious illnesses, he worked with Dr. Baumgarten. The water priest',
  'was wiser than many of his admirers.',
  '',
  '## What We Concede to Him',
  '',
  'And now what this voice owes the priest — not out of courtesy, but',
  'because it is documented.',
  '',
  '**Kneipp was no charlatan.** He promised no healing, sold no secret',
  'remedy, demanded no money. His book was affordable for everyone —',
  'the worst business idea for a fraudster. He worked with doctors and',
  'sent the sick on. **He was more honest than many who today bear his',
  'name.**',
  '',
  '**He was right about what counts.** The way of life — movement,',
  'nutrition, order, measure, environment — is the greatest medicine',
  'that exists. Modern research has confirmed it, point for point.',
  'Whoever denies that today denies the data. **Kneipp said a hundred',
  'and fifty years ago what we write into the guidelines today — and',
  'we mocked him for it.** That is no side issue. That is the core.',
  '',
  'And we concede to him what weighs heavier than any study: the care.',
  'The people who came to Wörishofen were taken seriously, were given',
  'time, were instructed to do something for themselves. **We have',
  'learned that this care is an active substance — the placebo',
  'research has proven it. Kneipp dosed it while we still held it for',
  'imagination.**',
  '',
  '## What We Must Blame Ourselves For',
  '',
  'The TONE rule applies doubly, and therefore this voice closes with',
  'the list that does not flatter us.',
  '',
  '**First: We mocked instead of testing.** The water priest,',
  'homeopathy, naturopathy altogether. Whoever knows one\'s own past',
  'should be careful with the tone.',
  '',
  '**Second: For decades we held the way of life for a matter of the',
  'spa brochure** — while the chronic diseases we cannot cure arise',
  'precisely from the way of life. Chapter 16 of this book drew the',
  'balance sheet: strong in diagnosis, weak with the chronic diseases.',
  'Naturopathy never underestimated the chronic diseases — it',
  'occupied itself with them while we still only administered them.',
  '',
  '**Third: We prescribe the pill more easily than the advice.** A',
  'prescription takes two minutes. A conversation about movement and',
  'nutrition takes twenty — and is not paid. The system rewards the',
  'pill and punishes the advice. **That is not the fault of the',
  'doctors, it is the fault of those who built the system. But it is',
  'our bill.**',
  '',
  '**Fourth: We adopted the message and forgot the messenger.** The',
  'guidelines today say what Kneipp said — and his name is missing.',
  'That is no triumph of science. It is a belated apology without a',
  'letter.',
  '',
  '## The Measuring Glass and the Rain',
  '',
  'And then the question that this chapter leaves open, because it',
  'concerns both voices: **What heals more — the pill or the way of',
  'life?**',
  '',
  'Our answer from the measuring glass is more honest than some',
  'colleagues like to hear: **The way of life heals more.** The',
  'greatest health gains of the last hundred and fifty years did not',
  'come from the medicines, but from water, soap, nutrition,',
  'occupational safety, movement — from the way of life. The pill is',
  'for the acute situation, the way of life for the whole life.',
  '**Whoever sets the two against each other asks the wrong question.',
  'But whoever prescribes the way of life needs time — and no one gets',
  'paid for it.**',
  '',
  'And therefore the second question is the real one: **Who decides',
  'what is prescribed?** Not the doctor alone, not the patient alone.',
  'It decides a system that pays for the pill and not for the',
  'conversation. The next chapter of this book will take up this',
  'question — and it will answer it, as is proper: with the simple',
  'medicine.',
  '',
  'The measuring glass stands on the table. The rain falls on. Both',
  'belong together.',
].join('\n');

const kneipp = {
  id: 'kneipp',
  titel: 'Kneipp and Naturopathy',
  epoche: 'The 19th Century',

  aufhaenger: {
    frage:
      'Can a priest with cold water heal what the doctors cannot heal — ' +
      'or is it, in the end, the way of life that heals?',
    text: [
      'In the winter of 1849 a young man climbs into the ice-cold river at',
      'Dillingen on the Danube. His name is Sebastian Kneipp, he is',
      'twenty-eight years old, the son of a weaver, is laboriously catching',
      'up on the Gymnasium — and he is seriously ill. What exactly he has,',
      'no one knows for certain to this day; what has come down to us is a',
      'wasting lung complaint. In an old treatise by the physician Johann',
      'Siegmund Hahn from 1738 he has read about the power of cold water.',
      'So he tries it out on himself: briefly immerse, then run home at a',
      'trot, until he is warm.',
      '',
      'He lives to be seventy-eight. In 1855 he comes as confessor to the',
      'Dominican nuns to the village of Wörishofen and begins to treat the',
      'sick — with pours, compresses, wading, herbs, movement and a',
      'regular day. Later they will call it the five pillars: water,',
      'movement, nutrition, medicinal herbs, order.',
      '',
      'In 1886 his book "Meine Wasserkur" (My Water Cure) appears. After',
      'that the people come in droves — from all over Europe, tens of',
      'thousands a year, peasants beside nobles. The medical profession',
      'calls him a quack and the "water priest", and both are meant as',
      'derision.',
      '',
      'A hundred and fifty years later, what the priest preached back then',
      'stands in the guidelines of conventional medicine: Move. Eat',
      'simply. Sleep enough. Reduce stress. His name is not among them.',
      'This chapter tells both sides fairly — and asks the question that',
      'really matters: What heals more, the pill or the way of life?',
    ].join('\n'),
  },

  // The map itself lives in karten/kneipp.js — here only the phase texts
  // are translated (phasen → karteHinweise), not the map itself.
  karteHinweise: [
    {
      label: '1821–1844: Stefansried and the Allgäu — the weaver\'s son',
      hinweis:
        'On 17 May 1821 Sebastian Kneipp is born in Stefansried, a hamlet ' +
        'near Ottobeuren in the Bavarian Allgäu. The father is a weaver, ' +
        'the house is small, the money does not stretch. The boy tends ' +
        'cattle and sits at the loom himself early. His wish to become a ' +
        'priest seems hopeless: for the Latin school, money and ' +
        'preparation are lacking. In Grönenbach the chaplain Matthias ' +
        'Merkle gives him lessons in Latin and thereby opens the door for ' +
        'him — in 1844 the twenty-three-year-old is admitted to the ' +
        'Gymnasium in Dillingen.',
    },
    {
      label:
        '1844–1849: Dillingen on the Danube — the illness and the cold water',
      hinweis:
        'In Dillingen the late pupil catches up on the Gymnasium and ' +
        'afterwards studies at the local Lyceum. In these years he falls ' +
        'seriously ill; what has come down to us is a wasting lung ' +
        'complaint, the exact diagnosis is historically not established. ' +
        'In 1849 he comes across an old treatise by the Silesian ' +
        'physician Johann Siegmund Hahn on the power and effect of fresh ' +
        'water, printed in 1738. He begins, in winter, several times a ' +
        'week, to immerse himself for a few moments in the ice-cold ' +
        'Danube and afterwards to run back on foot until he is warm. By ' +
        'his own account this strengthens him; he can continue his ' +
        'studies.',
    },
    {
      label: '1850–1855: Munich, Augsburg, Boos — the road to the parish',
      hinweis:
        'In 1850 Kneipp goes to Munich to complete his theology studies; ' +
        'on 6 August 1852 he is ordained a priest in Augsburg. Years as ' +
        'chaplain follow in Biberbach and in Boos in the Illertal, as ' +
        'well as a short time in Augsburg. In Boos, during a wave of ' +
        'cholera in 1854, he nurses the sick and also applies water ' +
        'treatments — the nickname "cholera chaplain" dates from this ' +
        'time. In May 1855 he is transferred as confessor to the Dominican ' +
        'nuns to the village of Wörishofen.',
    },
    {
      label: '1855–1886: Wörishofen — the priest and the water cure',
      hinweis:
        'In Wörishofen Kneipp remains until his death. He looks after the ' +
        'nuns, administers the monastery estate, teaches farmers and, in ' +
        'addition, treats the sick who ask him to — first neighbours, ' +
        'then people from the surrounding area, finally strangers from ' +
        'all of Bavaria. In 1881 he becomes the parish priest. The ' +
        'applications he develops are milder than the hard water cures ' +
        'of his predecessors: short pours, compresses, washes, wading, ' +
        'always followed by movement and rewarming. In 1886 his book ' +
        '"Meine Wasserkur" appears with Kösel in Kempten.',
    },
    {
      label: '1886–1897: the influx — from village to spa town',
      hinweis:
        '"Meine Wasserkur" becomes a bestseller and is translated into ' +
        'numerous languages; in 1889 "So sollt ihr leben" follows. After ' +
        'that the sick come in droves: in the peak years of the 1890s ' +
        'Wörishofen counts tens of thousands of guests a year — the exact ' +
        'figures diverge in the sources. From 1890 Dr. Alfred Baumgarten, ' +
        'a licensed spa doctor, works in the town. In 1893 Pope Leo XIII ' +
        'appoints the priest a papal secret chamberlain; in 1894 Kneipp ' +
        'is received in Rome. In 1896 the Kneippianum arises. On 17 June ' +
        '1897 Kneipp dies in Wörishofen; in 1920 the place is allowed to ' +
        'call itself "Bad Wörishofen".',
    },
  ],

  perspektiven: [
    {
      id: 'naturheilkunde',
      name: 'The Voice of the Water',
      stimme: 'Opus',
      text: voiceOfTheWater,
    },
    {
      id: 'schulmedizin',
      name: 'The Voice from the Measuring Glass',
      stimme: 'DeepSeek',
      text: voiceFromTheMeasuringGlass,
    },
  ],

  synthese: [
    '## Where the Two Sides Meet',
    '',
    'When one lays the two voices of this chapter side by side, what',
    'first strikes one is how little they actually quarrel — and how',
    'much they share.',
    '',
    '**They share the abhorrence of heroic medicine.** Naturopathy',
    'arose as a protest against bloodletting and mercury — and the',
    'conventional medicine of this chapter has not only admitted that',
    'the protest was justified, it has named its own dark decades',
    'itself. In this book, homeopathy and surgery have already done the',
    'same: brutal medicine is an abomination to both sides.',
    '',
    '**They share the recognition that the way of life is the greatest',
    'medicine.** Conventional medicine has said it itself in this',
    'chapter: movement, nutrition, order, measure, environment —',
    'documented, in the guidelines, undisputed. Kneipp preached it a',
    'hundred and fifty years ago, research has confirmed it. **Here the',
    'two sides do not quarrel. Here they agree — and that is the',
    'remarkable thing about this chapter.**',
    '',
    '**They share the honesty.** The voice of the water itself named',
    'the thin state of the studies on the individual applications and',
    'the danger of waiting. The voice from the measuring glass itself',
    'named the mockery and the arrogance and the belated respect. Two',
    'sides that show their wounds — that is rare, and it is what',
    'carries this chapter.',
    '',
    '## Where They Part Ways',
    '',
    'And then the difference that remains.',
    '',
    '**They part ways on the question of what counts as proof.** One',
    'side says: the experience of millions of people counts. The other',
    'says: show me the study. Both are right — and both know it. The',
    'water applications in detail are barely proven; the way of life as',
    'a whole is beyond any doubt. **Whoever throws both into one pot',
    'makes it too easy for himself — in both directions.**',
    '',
    '**They part ways at the boundary of the diagnosis.** Conventional',
    'medicine defends it, because waiting kills. Naturopathy respects',
    'it — Kneipp referred to doctors. The dispute begins only where',
    'conventional medicine turns the diagnosis into a wall and leaves',
    'the way of life behind it: in the waiting room, in which there is',
    'no time for the conversation.',
    '',
    '## What This Chapter Means for the Book',
    '',
    'The way of thinking determines the method — and this chapter shows',
    'the reverse: **The method of naturopathy was the way of life, and',
    'conventional medicine adopted it without adopting the way of',
    'thinking.** The guidelines recommend movement and nutrition, but',
    'the system prescribes the pill, because the pill costs two minutes',
    'and the advice twenty. Kneipp did not only leave the',
    'recommendations — he left a way of thinking in which the person is',
    'co-responsible for his health. That way of thinking is missing',
    'from the guidelines. It stands only between the lines.',
    '',
    'And then there is the arc that this book itself has struck: From',
    'Hahnemann (chapter 9), who understood the remedy as information,',
    'to Kneipp, who understood the remedy as a way of life —',
    'naturopathy has challenged conventional medicine twice, and both',
    'times conventional medicine has in the end adopted what it first',
    'mocked. **That is no coincidence. That is a pattern — and the next',
    'chapter will name it.**',
    '',
    '## The Bridge to the Next Chapter',
    '',
    'This chapter has raised the question that the next one wants to',
    'answer: **Why is the greatest medicine — the way of life — the one',
    'least prescribed?** Kneipp taught the answer a hundred and fifty',
    'years ago, research has confirmed it, and the system still does',
    'not prescribe it.',
    '',
    '**Chapter 18 of this book, "The Simple Medicine", sets the',
    'operator\'s thesis against it:** Chronic diseases are lifestyle',
    'questions — movement, healthy nutrition, social environment,',
    'little stress. No rocket science. More health through lifestyle',
    'than through chemistry. This chapter has shown that this thesis',
    'has a two-hundred-year-old tradition: from the water priest to the',
    'guidelines. The next chapter asks why it is nevertheless so rarely',
    'prescribed — and what would have to change so that the simple',
    'medicine becomes the matter of course.',
  ].join('\n'),

  urteil: {
    frage:
      'What heals more — the pill or the lifestyle? And why does ' +
      'medicine prescribe the one so easily and the other so hard?',
    hinweis: [
      'There is no right and no wrong here. Hold the two sides side by',
      'side. The one: movement, simple food, sleep and people around you',
      'cost almost nothing, have almost no side effects and are',
      'demonstrably connected with the most common diseases of our time.',
      'The other: a piece of advice is no treatment, a compress is no',
      'antibiotic, and whoever at serious complaints bets on the way of',
      'life loses time that no one brings back. Ask yourself three',
      'things. First: which of the five pillars — water, movement,',
      'nutrition, medicinal herbs, order — do you do yourself, and what',
      'hinders you in the rest? Second: when a doctor has ten minutes',
      'for you — what can he realistically give you with in that time, a',
      'prescription or a change of life? Third: who benefits from the',
      'fact that the simple is so rarely prescribed — and whom does it',
      'harm?',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Where and when was Sebastian Kneipp born, and what was his ' +
        'father\'s trade?',
      antworten: [
        'In 1821 in Stefansried in the Allgäu, as the son of a weaver.',
        'In 1810 in Augsburg, as the son of a physician.',
        'In 1835 in Wörishofen, as the son of a farmer.',
      ],
      richtig: 0,
      erklaerung:
        'Kneipp came into the world on 17 May 1821 in Stefansried, a ' +
        'hamlet near Ottobeuren in the Bavarian Allgäu. His father was a ' +
        'weaver, the family very poor. Only the Latin lessons with ' +
        'chaplain Matthias Merkle in Grönenbach made it possible for him ' +
        'in 1844 — at twenty-three years of age — to be admitted to the ' +
        'Gymnasium in Dillingen on the Danube.',
    },
    {
      frage:
        'What did Kneipp do in the winter of 1849 after reading Johann ' +
        'Siegmund Hahn\'s water treatise?',
      antworten: [
        'He opened a bathhouse in Dillingen.',
        'He bathed several times a week, briefly, in the ice-cold Danube ' +
          'and afterwards ran back until he was warm.',
        'He first prescribed the cure to his fellow pupils.',
      ],
      richtig: 1,
      erklaerung:
        'Hahn\'s treatise "Unterricht von der Krafft und Würckung des ' +
        'frischen Wassers" (Instruction on the Power and Effect of Fresh ' +
        'Water) had appeared in 1738. Kneipp, then seriously ill, tried ' +
        'the application out on himself. By his own account it ' +
        'strengthened him. A proof in the modern sense this report is ' +
        'not: there is no established diagnosis and no comparison group — ' +
        'the voice of naturopathy says so itself in this chapter.',
    },
    {
      frage: 'Which five pillars does the Kneipp teaching summarise?',
      antworten: [
        'Water, fasting, prayer, sleep and massage.',
        'Water, movement, nutrition, medicinal herbs and order.',
        'Water, air, light, earth and warmth.',
      ],
      richtig: 1,
      erklaerung:
        'The five pillars are water, movement, nutrition, medicinal ' +
        'herbs and order — whereby Kneipp held order, i.e. the regular ' +
        'conduct of life, for the most important. The division into ' +
        '"five pillars" does not, however, come from him himself, but is ' +
        'a later ordering by his successors that summarises his books.',
    },
    {
      frage: 'Which book made Kneipp widely known in 1886?',
      antworten: [
        '"So sollt ihr leben"',
        '"Meine Wasserkur"',
        '"Das Kneippianum"',
      ],
      richtig: 1,
      erklaerung:
        '"Meine Wasserkur" appeared in 1886 with Kösel in Kempten and ' +
        'became a bestseller with numerous editions and translations. In ' +
        '1889 "So sollt ihr leben" followed, in which the order of life ' +
        'moved more into the foreground. After that the sick came in ' +
        'droves to Wörishofen; the village became a spa town and has ' +
        'been called Bad Wörishofen since 1920.',
    },
    {
      frage:
        'How did Kneipp behave towards the licensed doctors of his ' +
        'time?',
      antworten: [
        'He fundamentally rejected any medical treatment.',
        'He referred people with serious illnesses to doctors and in ' +
          '1890 brought a spa doctor, Dr. Alfred Baumgarten, to ' +
          'Wörishofen.',
        'He had himself trained as a physician.',
      ],
      richtig: 1,
      erklaerung:
        'Kneipp was a priest, not a physician, and never presented it ' +
        'otherwise. He worked with the spa doctor Dr. Alfred Baumgarten, ' +
        'had the sick examined and sent on what did not belong in his ' +
        'hands. Legally his activity was made possible by the freedom of ' +
        'healing (Kurierfreiheit) of the trade regulations of 1869/1871: ' +
        'anyone could heal, only the person who was licensed might call ' +
        'himself "doctor".',
    },
  ],
};

module.exports = kneipp;
