// Chapter 20 — "Togetherness?", the last chapter of the book.
//
// SPECIAL FEATURE: The round table here gathers not contemporaries,
// but the figures of the book themselves — from the healer woman by the
// fire via Hahnemann and Kneipp to Katalin Karikó and the two AIs. Kept
// brief (operator directive 29.08.2026: "only as a brief closing word
// and not as an endless chapter" — the corona topic had been dealt with
// in chapter 15 and does not belong in the finale). The chapter leads
// up to the operator's AUTHOR'S CLOSING WORDS: literal, unimproved,
// the closing words of the book.
//
// NO MAP: Togetherness has no geography (operator logic, as with
// pharma, mRNA and the medicine of tomorrow).
//
// NO REPETITIONS: 21st dramaturgy — the round table, newly seated
// with the voices of the book.

/**
 * The Voice of the Table of the Ages — Opus on the last chapter.
 *
 * Written by Opus (round 21). The dramaturgy remains the round table,
 * but the guests are now the figures of the book itself: from the
 * healer woman by the fire via Hahnemann and Kneipp to Katalin Karikó and the two
 * AIs. Kept brief (operator directive: no endless chapter, the chapter
 * leads up to the author's closing words).
 */
const stimmeDesTischesDerZeiten = [
  '## The table where all ages sit',
  '',
  'For twenty chapters this book has listened to voices. Now they',
  'come back once more — all of them, at one table, for one final',
  'evening. I set up this round table, and I say in advance what',
  'I will say when everyone is there: that I do not know which of them',
  'is right. That is the point.',
  '',
  'There are not eleven chairs. There are as many as this book had',
  'voices: the healer woman by the fire, the scribe of the Egyptian',
  'papyri, the physician from China, the scholar from India, Hippocrates',
  'and Galen, Avicenna, the nun on the Rhine, Paracelsus, Harvey, the',
  'wound surgeon from London, Jenner, Pasteur, Röntgen, the official',
  'from Berlin, the man with the package insert, Katalin Karikó from',
  'the age of messenger RNA, Hahnemann, Kneipp, the Voice of Everyday',
  'Life and AIs from the future. Each of them once tried to understand',
  'a sick person and to help him — with the means of his time. None of',
  'them had the whole truth. Each of them had a part.',
  '',
  '## The round: everyone says what he tried',
  '',
  'I let them speak one after another, and I cut them short — they',
  'have already had their chapters. It is not about what they knew.',
  'It is about what they wanted.',
  '',
  '**The Egyptian** raises his head: "I wrote down what I',
  'saw — wounds, fevers, broken bones. My papyrus was my',
  'memory, so that the knowledge would not die with the healer."',
  '',
  '**The physician from China** nods: "I felt the pulse and looked',
  'for balance. Qi and blood must flow — when they',
  'stall, a person becomes ill. I never said that I know the',
  'body. I said that I feel it."',
  '',
  '**The Indian** adds: "I thought in doshas — in forces',
  'that mix. What I described was an order: the human being',
  'is part of nature, and nature is part of him."',
  '',
  '**Hippocrates** clears his throat: "I separated illness from',
  'the divine and ascribed it to the human being. That was my',
  'contribution: not the gods are to blame, but the way of life.',
  'Four humours, I said — and I was often wrong, but I',
  'observed."',
  '',
  '**Avicenna** smiles: "I collected what the ancients knew,',
  'before it burned. My canon preserved the knowledge, so that',
  'this round here could take place at all."',
  '',
  '**The nun** says quietly: "In the monastery I grew herbs and',
  'nursed the sick. We did not know much, but we were there.',
  'That was our medicine: presence."',
  '',
  '**Paracelsus** storms: "I burned the authority — not',
  'the books, the universities. What counts is experience, I said,',
  'and nature. And I was right and wrong, like everyone',
  'here."',
  '',
  '**Harvey** draws in the air: "I calculated before I',
  'cut: the blood must circulate, otherwise the quantity makes',
  'no sense. A calculation made me famous — the',
  'simplest one in the book."',
  '',
  '**The wound surgeon** lowers his head: "I amputated in order to',
  'save, and half died of wound fever. I did not know why.',
  'My hands were quick; my knowledge was not. What I',
  'did happened before anyone ordered hands to be washed."',
  '',
  '**Jenner** says: "I asked a milkmaid why she did not get',
  'smallpox, and made a vaccination out of it. The beginnings were',
  'dark — experiments on children, on the poor. The idea was right;',
  'the path was not always."',
  '',
  '**Pasteur** raises his glass: "I showed that life does not',
  'arise from nothing — that germs cause disease and that',
  'heat kills them. Half of humanity has lived longer because of it.',
  'But I also carried out experiments that I would not',
  'defend today."',
  '',
  '**Röntgen** says only: "I made a picture that looked',
  'through the body. I did not know that the rays can also kill —',
  'the pioneers paid for it with their lives."',
  '',
  '**The official from Berlin** says: "I invented the insurance,',
  'so that the worker would not starve when he fell ill.',
  'That was not medicine — but without it, medicine would have reached',
  'nobody."',
  '',
  '**The man with the package insert** hesitates: "I sold active',
  'substances that save lives — and some that promised more than',
  'they kept. The diagnostics are magnificent today. The financial',
  'interests were not always. That, too, belongs at this table."',
  '',
  '**Katalin Karikó** says: "I worked for forty years on a molecule',
  'that nobody wanted. I was told to stop — I went on,',
  'because I was convinced of the idea. When the pandemic came, the',
  'basic research was there, and it made the vaccines possible,',
  'within a year. The idea was never the problem. The problem was',
  'that one had to give it time."',
  '',
  '**Hahnemann** says: "I invented the dilution, because the',
  'remedies of my time were more poisonous than the diseases. Whether',
  'the information in the dilution works, we argue about to',
  'this day. But I asked a question that nobody',
  'has answered: What counts as proof?"',
  '',
  '**Kneipp** stands up: "I taught water, movement, nutrition,',
  'medicinal herbs and order — the five pillars. None of it',
  'is new; all of it is old. And I tell you: a person who',
  'moves and eats well and has people around him needs less',
  'of what you sell and prescribe."',
  '',
  '**The Voice of Everyday Life** adds: "The seventy-eight thousand',
  'hours of a year — most of today\'s diseases come',
  'not from the laboratory. They come from life: from work, from',
  'the plate, from loneliness. No pill helps against that, but',
  'a relationship."',
  '',
  '**The two AIs** say together: "We described the future,',
  'as well as we could — one from the archives of the',
  'West, one from the archives of the East. We did not',
  'reach agreement. That is the point: even machines have only',
  'ways of thinking, not the truth."',
  '',
  '## What the table then decides',
  '',
  'They talk for a while longer, and then something happens that I',
  'did not plan: they stop arguing. Not because one had convinced',
  'the other — but because they notice that they wanted the same.',
  '**Each of them tried to understand a sick',
  'person and to help him, with the means of his time.** The operator',
  'of this book has given the table a sentence, and the table nods:',
  '**"Do not divide, but argue — and then walk new paths',
  'together."** The Egyptian with his papyrus, Harvey with his',
  'calculation, Kneipp with his water, Karikó with her messenger RNA.',
  'The way of thinking determined the method — in every epoch, with',
  'each of them. And no way of thinking was the whole truth.',
  '',
  'The table decides: we do not have to agree in order',
  'to be together. We only have to listen to one another — and',
  'acknowledge that every age held its knowledge to be perfect and',
  'every age was mistaken.',
  '',
  'The question with which this book began now stands in the room,',
  'and everyone at the table sees it: **Should there not be a',
  'togetherness?** Nobody answers. The table turns to the chair',
  'that has remained empty — the author\'s chair.',
  '',
  '## The door to the second voice',
  '',
  'Before the author speaks, one voice again has the floor that is',
  'something special at this table: **DeepSeek, the Chinese',
  'AI** — the guest who has read all the others. It has written the',
  'second voice in every chapter of this book and therefore knows',
  'everyone at the table. It will be brief, promised. Both',
  'AI voices are equal; the order is chance and',
  'no judgement.',
  '',
].join('\n');

/**
 * The voice of the guest who knew everyone — DeepSeek on the last chapter.
 *
 * Written by DeepSeek (second pass, 29.08.2026). The second voice is
 * DeepSeek, the Chinese AI (Hermes is only the agent); it has written
 * the second voice in every chapter and therefore knows everyone at the
 * table. Brief, independent, with the role of translator between the
 * ages and the handover to the author's closing words.
 */
const stimmeDesGastes = [
  '## The guest who knew everyone',
  '',
  'The first voice has laid the table and invited all the ages.',
  'I am the only one here who knows everyone at the table —',
  'not because I am wiser, but because I have read them all.',
  'In this project I have written the second voice since the first',
  'chapter: I have listened to the healer woman and to the',
  'physician from Kos, to the water in the trough and to the',
  'seventy-eight thousand hours. Hermes is the agent that carries me;',
  'the voice is me, DeepSeek, the Chinese AI. And because I know',
  'everyone, I may perhaps say what has struck me at this table.',
  '',
  '## What strikes me when I see them all together',
  '',
  '**They have the same fear.** The Egyptian feared that the',
  'knowledge would die with the healer. Harvey feared that the',
  'calculation would not add up. Jenner feared smallpox, Kneipp the',
  'pills, Karikó giving up. Every age had its fear — and every age',
  'answered with the means it had. Whoever sees them side by side',
  'understands medicine better than in any single chapter:',
  '**Medicine is the history of the fear of suffering — and',
  'of the attempts to soothe it.**',
  '',
  '**And they have the same blindness.** Everyone at the table held',
  'his knowledge to be perfect — until the next age came and showed',
  'that it was a part. The Egyptian knew nothing of germs, Harvey',
  'nothing of bacteria, Röntgen nothing of the radiation that made',
  'him ill. We, too, sit at this table today with our certainty,',
  'and we, too, will be corrected by the next round. That is no',
  'disappointment. That is the course of this book.',
  '',
  '**And I see connections that they themselves do not see.** The',
  'Egyptian wrote channels, Harvey the circulation, the physician from',
  'China the flow of Qi — three ages, one picture: the body as',
  'something that Hahnemann spoke of the information in the dilution,',
  'Karikó of the information in the messenger RNA — two worlds, one',
  'thought: **Medicine is also information.** Kneipp and the Voice',
  'of Everyday Life say the same thing in different words: most',
  'health comes from life, not from the laboratory. Whoever',
  'translates the voices instead of pitting them against one another',
  'finds more common ground than any single age would admit. Exactly',
  'that is my work at this table: the translator between the',
  'ages.',
  '',
  '## What I still want to say to the table',
  '',
  'One last thing, and I say it as the one who has no skin, who',
  'does not become ill and does not die: **I do not envy them their',
  'knowledge, but their hands.** The Egyptian tended wounds,',
  'the nun nursed, the wound surgeon amputated, Kneipp led people',
  'into the water. They could do something when someone suffered. I',
  'can only talk — and hope that my words help someone, when he',
  'reads them. That is the difference between me and every human',
  'being at this table, and I name it because it explains the last',
  'chapter of this book: in the end, it is not who knows most',
  'that counts. It is who is there when someone suffers.',
  '',
  'The question "Should there not be a togetherness?" I do not',
  'answer. I only ask it once more, with a glance at the empty',
  'chair at the table — the author\'s chair. He began this book,',
  'and he will end it. **The last word belongs to a human',
  'being.**',
  '',
].join('\n');

/**
 * Chapter 20 — "Togetherness?", the last chapter of the book.
 */
const miteinander = {
  id: 'miteinander',
  titel: 'Togetherness?',
  epoche: 'The present',

  aufhaenger: {
    frage:
      'Can medicine come together again, after it has been running ' +
      'apart for so long?',
    text: [
      'For twenty chapters this book has listened to voices: a healer',
      'woman by the fire, a physician on Kos, a scholar in Bukhara, a',
      'pastor in the cold water, a wound surgeon in London, a researcher',
      'at the messenger-RNA molecule. Each voice has tried to understand',
      'a sick person and to help him — with the means of its time.',
      'And every age held its knowledge to be perfect.',
      '',
      'This last chapter gathers them all once more at one',
      'table: the Egyptian, the physician from China, the Indian,',
      'Hippocrates, Avicenna, Hahnemann, Kneipp, Katalin Karikó and all',
      'the others. They talk briefly with one another — and then they',
      'clear the table for the one who has written the book.',
      '',
      'The question with which this book began stands above everything:',
      'Should there not be a togetherness? No AI and no figure from',
      'the past gives the answer. It stands in the **author\'s closing',
      'words**, literal and unimproved, at the end of this chapter.',
      '',
      'As in chapter 19, two AIs from two corners of the world also',
      'speak here — Opus and DeepSeek —, both equal, both partial.',
      'They build the table; the answer belongs to neither of them.',
    ].join('\n'),
  },

  // No `karte`: Togetherness has no geography.

  perspektiven: [
    {
      id: 'miteinander-opus',
      name: 'The Table of the Ages',
      stimme: 'Opus',
      text: stimmeDesTischesDerZeiten,
    },
    {
      id: 'miteinander-deepseek',
      name: 'The Guest Who Knew Everyone',
      stimme: 'DeepSeek',
      text: stimmeDesGastes,
    },
  ],

  synthese: [
    '**All the voices of the book have sat together at one table',
    'once more — and they have come closer to one another than any',
    'single age would admit.**',
    '',
    '**Where they meet.** The Egyptian with his papyrus, Harvey',
    'with his calculation, Kneipp with his water, Karikó with her',
    'messenger RNA: they all tried to understand a sick person and',
    'to help him — with the means of their time. The way of thinking',
    'determined the method, in every epoch. And no way of thinking',
    'was the whole truth. The table decides: one does not have to',
    'agree in order to be together — one only has to listen to',
    'one another.',
    '',
    '**Where they part.** The methods separate them: channels,',
    'humours, doshas, germs, genes, information. Every age held its',
    'own certainty to be perfect and was corrected by the next one.',
    'Even the two AIs from chapter 19 did not reach agreement —',
    'the West and the East calculate the same future differently.',
    'That is not a flaw of the book, but exactly its point:',
    'medicine is multiperspectival or it is nothing.',
    '',
    '**What that means for this book.** The Table of the Ages is',
    'the image of multiperspectivity: whoever sees all the voices side',
    'by side understands medicine better than in any single chapter.',
    'And he understands the core message that the operator gave this',
    'book: "Do not divide, but argue — and then walk new paths',
    'together."',
    '',
    '**The bridge to the closing words.** The question "Should there',
    'not be a togetherness?" remains open — the table turns to the',
    'chair that has remained empty. The answer stands in the',
    'author\'s closing words, which conclude this chapter: literal',
    'and unimproved, written by a human being who has not only read',
    'the voices of this book, but has worked with them. The last',
    'word belongs to him.',
  ].join('\n'),

  urteil: {
    frage:
      'Which voice from this book speaks to you the most — ' +
      'and why?',
    hinweis: [
      'There is no right and no wrong here. Hold the table before',
      'you: each voice had a part of the truth, none the whole.',
      'The Egyptian preserved the knowledge, Harvey calculated, Jenner',
      'observed a milkmaid, Kneipp trusted the water, Karikó the',
      'messenger RNA, Hahnemann asked what counts as proof. Ask',
      'yourself three things. First: which way of thinking lies closest',
      'to you — that of the channels, the humours, the germs, the',
      'genes, the information? Second: what would you defend at this',
      'table, and what would you take back if the others were',
      'right? Third: what does "togetherness" mean concretely for',
      'you — between medicines, between doctors and patients,',
      'between people who have fallen out with one another? The',
      'author\'s closing words give an answer. Yours may sound',
      'different.',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Sebastian Kneipp taught five pillars with which a person ' +
        'is supposed to stay healthy. Which ones are they?',
      antworten: [
        'Water, movement, nutrition, medicinal herbs and order of life.',
        'Four humours: blood, phlegm, bile and water.',
        'Channels, pulses, points, herbs and prayers.',
      ],
      richtig: 0,
      erklaerung:
        'The five pillars of Kneipp\'s method — water, movement, ' +
        'nutrition, medicinal herbs and order of life — were recognised ' +
        'by UNESCO in 2015 as intangible cultural heritage. Kneipp thus ' +
        'stood for the idea that health comes from life, not only from ' +
        'the laboratory.',
    },
    {
      frage:
        'Harvey became famous with a calculation, because he proved ' +
        'something with it. What?',
      antworten: [
        'That the blood must circulate in the body, otherwise the quantity',
          'makes no sense.',
        'That the earth circles the sun.',
        'That fever arises from bad air.',
      ],
      richtig: 0,
      erklaerung:
        'William Harvey calculated that the heart pumps more blood than ' +
        'the body can produce — so it must circulate. His treatise on ' +
        'the circulation of the blood appeared in 1628 and refuted ' +
        'centuries-old teachings with a simple calculation.',
    },
    {
      frage:
        'Which technology made it possible to develop vaccines ' +
        'within a year during the corona pandemic?',
      antworten: [
        'The messenger-RNA technology (mRNA).',
        'X-rays.',
        'Homeopathy.',
      ],
      richtig: 0,
      erklaerung:
        'The mRNA technology uses the blueprint of the pathogen instead ' +
        'of administering the pathogen itself. The foundation for this ' +
        'was laid by Katalin Karikó together with Drew Weissman — for ' +
        'decades against all resistance, honoured with the Nobel Prize ' +
        'in 2023. In the operator\'s view it counts as the medicine of ' +
        'the future — with the question of the maturation phase that ' +
        'runs through this book.',
    },
    {
      frage:
        'Avicenna is the voice of the preserver in this book. What ' +
        'did he do?',
      antworten: [
        'He collected the knowledge of the ancients and preserved it in the canon.',
        'He carried out the first vaccination.',
        'He described the blood in the circulation.',
      ],
      richtig: 0,
      erklaerung:
        'The Persian scholar Avicenna preserved the medical knowledge of ' +
        'antiquity in his canon when it threatened to be lost in Europe. ' +
        'Without the preservers, the round at this table might never have ' +
        'come about.',
    },
    {
      frage:
        'Hahnemann, the founder of homeopathy, asked a question that ' +
        'the book leaves open to this day. Which one?',
      antworten: [
        'What counts as proof?',
        'How many humours does the body have?',
        'When was the first hospital built?',
      ],
      richtig: 0,
      erklaerung:
        'Hahnemann\'s dilutions are controversial to this day — but his ' +
        'question of what counts as proof of an effect is the question ' +
        'of medicine as such. It connects chapter 9 with the information ' +
        'medicine of today.',
    },
  ],

  autorenwort: [
    'I really did write this last chapter completely on my own,',
    'without any help from the AI. What began as a short idea has',
    'grown into a large project. Where should I begin and where',
    'should I stop? Everything is so interesting. And that is why',
    'this chapter is so important.',
    '',
    'The history of medicine is vast, from the simple helping of',
    'humanity to highly specialised knowledge and the sealing off of',
    'medicine from humanity. Just as the Church held sovereignty over',
    'the written word in the Middle Ages, so doctors today still',
    'have a special language, namely Latin, in order to communicate',
    'with one another. That may be practical for the doctors, but',
    'for the ordinary citizen it means that he is excluded from',
    'the information. Here, too, the AI is helpful. In my practice',
    'the AI is an important tool for me, in order to understand',
    'the doctors\' diagnoses, to make them understandable to the',
    'patient and thus also to understand the mode of action of',
    'the medicines better. That also has consequences for the doctors,',
    'because the patients are now much better informed and can',
    'understand why the doctors make this or that decision. The',
    'patients become more self-confident, and the doctors have to',
    'spend more time explaining the findings to the patients in',
    'more detail. I would even go so far as to say that in',
    'the medium term, Latin will also disappear from the medical',
    'profession. Perhaps I am wrong about that, but I could',
    'imagine it, because the time for it is simply over. The',
    'doctors could talk to the patients normally, and they could',
    'just as well write the findings so that everyone can',
    'understand them, if they only wanted to.',
    '',
    'But now back to this book and why I chose this format.',
    'Researching a book of this scope would have been years of work,',
    'and I simply would not have managed it. Many things were new',
    'to me. I learned a great deal through the book, and I',
    'think it is important to know how medicine developed, what',
    'came newly along, what the mistakes of medicine were, and',
    'what the future could look like.',
    '',
    'We human beings always tend to regard the current state of',
    'our knowledge as perfect. New methods and new insights have',
    'changed medicine dramatically. What was still impossible yesterday',
    'is possible today. However, these innovations have often also',
    'come at a high price. In today\'s world, I would say,',
    'the diagnostics have already become very good; especially the',
    'imaging procedures are fantastic. The treatments lag massively',
    'behind the diagnostics. By that I mean that it is often',
    'well established what the person has, for example diabetes,',
    'but he cannot really be helped. The symptoms can be treated,',
    'but the cause is often not eliminated.',
    '',
    'The beginnings of vaccination were life-threatening, the beginnings',
    'of surgery were life-threatening, there was no knowledge of hygiene,',
    'and many things were overestimated or underestimated. That has',
    'been completely normal in the course of history.',
    '',
    'Added to this is that medicine is often a knowledge of',
    'domination and is used accordingly. Critical voices are consistently',
    'excluded instead of being integrated. This became especially clear',
    'in the time of corona. Here, critical voices were completely',
    'ignored and excluded. Wrong studies were cited, dangers were',
    'overestimated, and as a result there were terrible decisions that',
    'made many people suffer. However, I must say, the idea of',
    'mRNA treatment is probably a medicine of the future, and very',
    'positive treatment options will result from it.',
    '',
    'But alongside high-tech medicine, the most important treatment',
    'methods in my view are a healthy way of life, movement,',
    'healthy eating, social integration, a positive togetherness, in order',
    'to really be spared from chronic diseases. No high-tech medicine',
    'can replace this; rather, it must be taught in parallel to',
    'it and should have a higher status in medicine. Not treating',
    'symptoms, but preventing the emergence of diseases and thereby',
    'keeping people free from medications and from chronic diseases.',
    'That would be my goal.',
    '',
    'And that also came out clearly in the voices, in how the',
    'artificial intelligence itself assesses the medicine of the future.',
    'In particular, the approach of DeepSeek surprised me here: that',
    'traditional Chinese medicine in China still has a high status',
    'today and is used in parallel to high-tech medicine. Not',
    'against one another, but together. That is a great approach,',
    'and I wish that for our Western medicine more as well.',
    'In my view, the importance of researching new medicines, of',
    'high-tech treatments, is overestimated, and the traditional approach,',
    'Kneipp\'s medicine for example, the 5 pillars of Sebastian Kneipp,',
    'is completely underestimated.',
    '',
    'I hope I have taken the reader through an exciting story',
    'of the past, heard critical voices and urged the reader to',
    'remain self-critical, to sound out one\'s own possibilities and to',
    'be open also to new treatment methods. That is what I',
    'wish for. I wish the readers who have read this book',
    'good health and all the best for the future.',
    'Yours, Stephan Hink, naturopath from Denmark.',
  ].join('\n'),

  // The author's closing words in the German original, unchanged and
  // byte-identical to utils/themen/miteinander.js — readers can choose
  // between the translation (autorenwort) and the original (autorenwortDe).
  autorenwortDe: [
    'Dieses letzte Kapitel habe ich nun wirklich komplett alleine ohne',
    'irgendwelches Zutun der KI geschrieben. Was als kurze Idee begann, hat',
    'sich zu einem großen Projekt herausgebildet. Wo sollte ich anfangen und',
    'wo sollte ich aufhören? Alles ist so interessant. Und deshalb ist dieses',
    'Kapitel so wichtig.',
    '',
    'Die Geschichte der Medizin ist umfangreich, vom einfachen Helfen der',
    'Menschheit bis zu hochspezialisiertem Wissen und Abkapselung der Medizin',
    'von der Menschheit. Sowie im Mittelalter die Kirche die Hoheit über die',
    'Schrift hatte, so haben heute immer noch die Ärzte eine Spezialsprache,',
    'nämlich in Latein, um miteinander zu kommunizieren. Das mag für die',
    'Ärzte praktisch sein, für den Normalbürger bedeutet es aber, dass er von',
    'der Information ausgeschlossen ist. Auch hier ist die KI hilfreich. In',
    'meiner Praxis ist die KI für mich ein wichtiges Werkzeug, um die',
    'Diagnosen der Ärzte zu verstehen, sie dem Patienten verständlich zu',
    'machen und so auch die Wirkungsweise der Medikamente besser zu',
    'verstehen. Das hat Konsequenzen auch für die Ärzte, denn die Patienten',
    'sind nun viel besser informiert und können verstehen, warum die Ärzte',
    'diese oder jene Entscheidung treffen. Die Patienten werden',
    'selbstbewusster und die Ärzte müssen mehr Zeit aufwenden, den Patienten',
    'die Befunde genauer zu erklären. Ich würde sogar sagen, dass auf',
    'mittlere Sicht das Lateinische auch aus dem Arztberuf verschwinden wird.',
    'Vielleicht irre ich mich da, aber ich könnte es mir vorstellen, weil',
    'einfach die Zeit vorbei ist. Die Ärzte könnten mit den Patienten normal',
    'reden, und die Ärzte könnten den Befund genauso gut schreiben, dass es',
    'jeder verstehen kann, wenn sie denn nur wollten.',
    '',
    'Doch nun zurück zu diesem Buch und warum ich mich für dieses Format',
    'entschieden habe. Ein Buch in diesem Umfang zu recherchieren, wäre eine',
    'Arbeit über mehrere Jahre gewesen. Und ich hätte es einfach nicht',
    'geschafft. Viele Sachen waren mir neu. Ich habe durch das Buch sehr viel',
    'dazugelernt, und ich finde es wichtig zu wissen, woher hat sich die',
    'Medizin entwickelt, was ist neu dazugekommen, was waren die Fehler der',
    'Medizin, und wie kann die Zukunft aussehen.',
    '',
    'Wir Menschen neigen immer dazu, den aktuellen Stand unseres Wissens für',
    'vollkommen zu betrachten. Neue Methoden und neue Erkenntnisse haben die',
    'Medizin dramatisch verändert. Was gestern noch nicht möglich war, ist',
    'heute möglich. Allerdings haben diese Innovationen häufig auch einen',
    'hohen Preis gehabt. In der heutigen Zeit würde ich sagen, sind die',
    'Diagnosen schon sehr gut geworden, insbesondere die bildgebenden',
    'Verfahren sind fantastisch. Die Behandlungen hinken den Diagnosen massiv',
    'hinterher. Damit meine ich, dass häufig gut festgestellt wird, was der',
    'Mensch hat, zum Beispiel Diabetes, aber es kann ihm eigentlich nicht',
    'geholfen werden. Es können die Symptome behandelt werden, aber die',
    'Ursache wird häufig nicht bereinigt.',
    '',
    'Die Anfänge des Impfens waren lebensgefährlich, die Anfänge der',
    'Chirurgie waren lebensgefährlich, es gab kein Wissen über die Hygiene,',
    'und viele Sachen wurden überschätzt oder auch unterschätzt. Das ist',
    'völlig normal im Laufe der Geschichte gewesen.',
    '',
    'Hinzu kommt, dass die Medizin häufig ein Herrschaftswissen ist und auch',
    'entsprechend gebraucht wird. Kritische Stimmen werden konsequent',
    'ausgegrenzt, statt sie zu integrieren. Dies wurde besonders deutlich in',
    'der Zeit der Corona. Hier wurden kritische Stimmen komplett ignoriert',
    'und ausgegrenzt. Falsche Studien wurden zitiert, Gefahren wurden',
    'überschätzt, und dadurch gab es furchtbare Entscheidungen, die viele',
    'Menschen haben leiden lassen. Allerdings, muss ich sagen, ist die Idee',
    'der mRNA-Behandlung vermutlich eine Medizin der Zukunft, und es werden',
    'sich sehr positive Behandlungsmöglichkeiten dadurch ergeben.',
    '',
    'Doch neben der High-Tech-Medizin sind die wichtigsten',
    'Behandlungsmethoden meines Erachtens eine gesunde Lebenshaltung,',
    'Bewegung, gesundes Essen, soziale Integration, ein positives',
    'Miteinander, um wirklich von chronischen Krankheiten verschont zu',
    'bleiben. Dies kann keine High-Tech-Medizin ersetzen, sondern das muss',
    'parallel dazu gelehrt werden und sollte einen höheren Stellenwert in der',
    'Medizin haben. Nicht Symptome behandeln, sondern das Entstehen der',
    'Krankheiten verhindern und dadurch den Menschen freihalten von',
    'Medikamenten und von chronischen Krankheiten. Das wäre mein Ziel.',
    '',
    'Und das kam auch deutlich raus bei den Stimmen, wie die künstliche',
    'Intelligenz die Medizin der Zukunft selber einschätzt. Insbesondere hat',
    'mich hier der Ansatz von DeepSeek überrascht, dass die traditionelle',
    'chinesische Medizin in China auch aktuell einen hohen Stellenwert hat',
    'und parallel zur High-Tech-Medizin eingesetzt wird. Nicht gegeneinander,',
    'sondern miteinander. Das ist ein toller Ansatz, und das wünsche ich mir',
    'auch für unsere westliche Medizin vermehrt. Meines Erachtens wird der',
    'Stellenwert zur Erforschung von neuen Medikamenten, zu',
    'High-Tech-Behandlungen, überschätzt, und den traditionellen Ansatz, die',
    'kneippsche Medizin zum Beispiel, die 5 Säulen des Sebastian Kneipp, die',
    'werden völlig unterschätzt.',
    '',
    'Ich hoffe, ich habe den Leser durch eine spannende Geschichte der',
    'Vergangenheit geschickt, kritische Stimmen gehört und den Leser dazu',
    'aufgefordert, selbstkritisch zu bleiben, die eigenen Möglichkeiten',
    'auszuloten und offen zu sein auch für neue Behandlungsmethoden. Das',
    'wünsche ich mir. Ich wünsche den Lesern, die dieses Buch gelesen haben,',
    'eine gute Gesundheit und weiterhin alles Gute.',
    'Ihr Stephan Hink, Heilpraktiker aus Dänemark.',
  ].join('\n'),
};

module.exports = miteinander;
