// Kapitel 2 — „China und die TCM".
//
// Die chinesische Medizin ist die älteste Heiltradition, die ohne Bruch bis
// heute praktiziert wird. Dieses Kapitel tut, was der Betreiber verlangt
// hat: Es analysiert ihre DENKART umfangreich — nicht nur, WAS getan wurde,
// sondern WARUM. Das Weltbild (Qi, Yin und Yang, die Fünf Wandlungsphasen,
// die Leitbahnen), die Begründungslogik hinter Nadel, Rezeptur, Puls und
// Atem — und die ehrliche Wirkungsbilanz: was die Forschung heute stützt
// und was nicht messbar oder umstritten ist (CLAUDE.md, Denkart-Analyse).
//
// Stimmen (Runde 3): Die ERSTE Perspektive — die chinesische Medizin von
// innen — verfasste Opus. Die ZWEITE (der westliche Blick: Staunen,
// Skepsis, wissenschaftliche Prüfung) und die finale Synthese ergänzte
// Hermes im zweiten Pass. Perspektiven-Workflow: CLAUDE.md.
//
// KEINE WIEDERHOLUNGEN (Betreiber-Entscheid vom 21.08.2026): Kapitel 1
// gliedert seine Stimmen nach „Wer hier spricht → Wie das Wissen wuchs →
// Denkart → …". Dieses Kapitel wählt bewusst eine andere Dramaturgie: Es
// beginnt mit einer Szene am Handgelenk, entfaltet das Weltbild in vier
// Begriffen und führt die Begründungslogik an vier „Warum"-Fragen entlang.
//
// Die Texte liegen als Zeilen-Arrays mit `.join('\n')` — so bleiben sie im
// Repo bei ~72 Zeichen lesbar (der Betreiber liest sie hier gegen), und
// utils/markdown.js macht in der App wieder fließenden Text daraus.
//
// CommonJS ohne UI-Importe (Architektur-Regel): mit blankem `node` prüfbar.

const { karte } = require('./karten/china-tcm');

/**
 * Die Stimme der chinesischen Medizin — die Tradition von innen.
 *
 * Verfasst von Opus (Runde 3). Sie erklärt ihr Weltbild in ihren eigenen
 * Worten, begründet ihre Methoden aus dieser Logik heraus, zeigt, wie das
 * Wissen entstand — und benennt die unbequemen Stellen der eigenen
 * Erzählung selbst, statt sie der Gegenstimme zu überlassen (Zusatzregel
 * für sensible Themen in CLAUDE.md).
 */
const stimmeDerChinesischenMedizin = [
  '## Drei Finger am Handgelenk',
  '',
  'Ein Mann kommt herein. Er ist seit Monaten müde, schläft schlecht, der',
  'Magen drückt nach dem Essen. Der Arzt bittet ihn, sich zu setzen, und',
  'legt drei Finger auf sein Handgelenk — erst rechts, dann links. Er',
  'schweigt dabei ziemlich lange. Dann bittet er ihn, die Zunge',
  'herauszustrecken, und sieht sie an: Farbe, Form, Belag, Feuchtigkeit.',
  'Er fragt nach dem Schlaf, nach dem Stuhlgang, nach Durst, nach kalten',
  'Füßen, nach der Stimmung am Abend, nach dem Geschmack im Mund.',
  '',
  'Kein Blutbild, kein Ultraschall, kein Fieberthermometer. Am Ende sagt',
  'er auch nicht „Sie haben eine Gastritis". Er sagt etwas, das für',
  'westliche Ohren zunächst wie Poesie klingt: die Mitte sei schwach, es',
  'liege Feuchtigkeit, und das Qi der Leber stehe quer. Dann schreibt er',
  'eine Rezeptur auf — zwölf Pflanzen, in bestimmten Mengen, in einer',
  'bestimmten Rangordnung — und setzt vielleicht ein paar Nadeln.',
  '',
  'Diese Seite erzählt, was dieser Arzt sich dabei denkt. Sie erzählt es',
  'von innen, in den Worten der Tradition selbst, und sie behauptet nicht,',
  'die Wahrheit zu sein — sie erklärt eine Denkart. Wer sie verstehen',
  'will, muss für eine Weile eine andere Frage zulassen als die gewohnte.',
  'Die westliche Medizin fragt: **Was ist kaputt?** Die chinesische',
  'Medizin fragt: **Was ist aus dem Gleichgewicht?** Alles Weitere folgt',
  'aus diesem einen Unterschied.',
  '',
  '## Qi — ein Wort, das sich nicht übersetzen lässt',
  '',
  'Am Anfang steht ein Begriff, an dem jede Übersetzung scheitert.',
  '**Qi** wird meist mit „Lebensenergie" wiedergegeben, und das ist',
  'irreführend: Es ist keine Energie im Sinne der Physik, kein Strom, den',
  'man messen könnte. Das Schriftzeichen zeigt ursprünglich den Dampf über',
  'kochendem Reis. Gemeint ist beides zugleich: der feine Stoff und seine',
  'Bewegung.',
  '',
  'Man kommt dem Begriff am nächsten, wenn man ihn als **Funktion** liest.',
  'Nicht: „Was ist das Herz?", sondern: „Was tut das Herz, und tut es das',
  'kräftig, gleichmäßig, am richtigen Ort?" Qi ist das, was wärmt, was',
  'bewegt, was zusammenhält, was verwandelt, was schützt. Wo Qi reichlich',
  'und frei fließt, ist der Mensch gesund. Wo es zu wenig ist, wird er',
  'müde, friert, verdaut schlecht. Wo es sich staut, entsteht Schmerz.',
  '',
  'Daraus folgt der wichtigste Satz dieser Medizin, und er ist',
  'jahrtausendealt: **„Wo es fließt, gibt es keinen Schmerz; wo es',
  'Schmerz gibt, fließt es nicht."** Schmerz ist in dieser Denkart kein',
  'Signal aus einem beschädigten Gewebe, sondern ein Stau. Und einen Stau',
  'behandelt man nicht, indem man das Signal abschaltet, sondern indem man',
  'ihn auflöst.',
  '',
  'Neben dem Qi stehen drei weitere Grundgrößen, die zusammen den',
  'Menschen ausmachen: **Xue**, das Blut, das nährt und befeuchtet;',
  '**Jing**, die Essenz, eine Art angeborener Vorrat, der über das ganze',
  'Leben langsam aufgebraucht wird; und **Shen**, der Geist, der sich in',
  'den Augen zeigt und im Schlaf. Wer einen Menschen beurteilt, beurteilt',
  'alle vier — nicht ein Organ.',
  '',
  '## Yin und Yang — zwei Pole, ein Gleichgewicht',
  '',
  'Das zweite Werkzeug ist ein Denkmuster, kein Ding. **Yin und Yang**',
  'sind keine Substanzen und keine Mächte. Sie sind ein Paar Begriffe, mit',
  'dem sich jede Erscheinung in ein Verhältnis setzen lässt.',
  '',
  'Ursprünglich meinten die beiden Wörter die Schattenseite und die',
  'Sonnenseite eines Berghangs — und daran sieht man schon alles',
  'Wesentliche. Erstens: Es sind keine Gegner, sondern zwei Seiten',
  'derselben Sache. Ein Berg ohne Schattenseite ist kein Berg. Zweitens:',
  'Sie sind immer relativ. Dieselbe Seite ist morgens Schatten und',
  'nachmittags Sonne. Drittens: Sie gehen ineinander über. Wenn die Sonne',
  'am höchsten steht, beginnt bereits der Rückweg.',
  '',
  'Auf den Menschen übertragen: **Yin** ist das Kühlende, Feuchte,',
  'Ruhende, Nährende, Materielle, das Innere und Unten. **Yang** ist das',
  'Wärmende, Trockene, Bewegte, Antreibende, Funktionelle, das Äußere und',
  'Oben. Gesundheit ist nicht „viel Yang" oder „viel Yin", sondern ihr',
  'bewegliches Gleichgewicht.',
  '',
  'Und genau deshalb kennt diese Medizin **vier** Grundstörungen, wo eine',
  'einfachere Sicht nur zwei sähe. Es kann zu viel Yang geben (echte',
  'Hitze) — oder zu wenig Yin, wodurch die vorhandene Wärme nicht mehr',
  'gekühlt wird (Leere-Hitze). Beides fühlt sich für den Kranken heiß an,',
  'aber es wird gegensätzlich behandelt: Im ersten Fall kühlt man aus, im',
  'zweiten Fall nährt man auf. Dasselbe gilt spiegelbildlich für die',
  'Kälte. Wer diesen Unterschied nicht erkennt, macht mit einem richtigen',
  'Mittel den Kranken kränker. Das ist der Grund, warum diese Tradition so',
  'viel Aufwand in die Diagnose steckt und so wenig mit fertigen',
  'Standardrezepten arbeitet.',
  '',
  '## Fünf Wandlungsphasen — Holz, Feuer, Erde, Metall, Wasser',
  '',
  'Yin und Yang teilen die Welt in zwei. Die **Fünf Elemente** teilen sie',
  'feiner. Der übliche deutsche Name ist eigentlich schon eine',
  'Fehlübersetzung: Es geht nicht um Baustoffe, aus denen die Welt',
  'gemacht ist, sondern um fünf **Wandlungsphasen** — fünf Zustände, die',
  'ein Vorgang durchläuft, wie das Jahr durch die Jahreszeiten geht.',
  '',
  '- **Holz** — das Aufsteigende, das Sprießen, der Frühling, der Beginn.',
  '- **Feuer** — der Höhepunkt, die Hitze, der Sommer, die Ausbreitung.',
  '- **Erde** — die Mitte, das Reifen, die Umwandlung, das Nähren.',
  '- **Metall** — das Zusammenziehen, das Klären, der Herbst, das Ernten.',
  '- **Wasser** — das Absinken, das Speichern, der Winter, die Ruhe.',
  '',
  'Jeder Phase ist ein Funktionskreis zugeordnet — Holz der Leber, Feuer',
  'dem Herzen, Erde der Milz, Metall der Lunge, Wasser den Nieren — und',
  'dazu eine Jahreszeit, ein Geschmack, eine Farbe, eine Gefühlsregung,',
  'ein Sinnesorgan. Hier ist eine ehrliche Warnung nötig, und sie kommt',
  'aus der Tradition selbst: Diese Organnamen meinen nicht die Organe der',
  'Anatomie. Die „Milz" der chinesischen Medizin ist der ganze Vorgang der',
  'Verdauung und der Umwandlung von Nahrung in Qi — mit dem Organ, das',
  'ein Chirurg entfernt, hat sie wenig zu tun. Wer die Begriffe',
  'anatomisch liest, versteht kein Wort richtig.',
  '',
  'Zusammengehalten werden die fünf Phasen durch zwei Kreisläufe, und die',
  'sind das eigentliche Werkzeug:',
  '',
  '- Der **Hervorbringungszyklus**: Holz nährt Feuer, Feuer wird zu',
  '  Asche und damit zu Erde, Erde bringt Metall hervor, Metall trägt',
  '  Wasser (an kaltem Metall schlägt sich Wasser nieder), Wasser nährt',
  '  wieder das Holz. Jede Phase ist die Mutter der nächsten.',
  '- Der **Kontrollzyklus**: Holz durchdringt und zehrt die Erde aus,',
  '  Erde staut das Wasser, Wasser löscht das Feuer, Feuer schmilzt das',
  '  Metall, Metall schneidet das Holz. Jede Phase hält eine andere im',
  '  Zaum.',
  '',
  'Das klingt nach Symbolik, ist aber im Alltag ein Denkwerkzeug für',
  'Ursachenketten. Ein Beispiel, wie es ein Arzt benutzt: Ein Mensch ist',
  'dauerhaft gereizt und angespannt — das ist Holz, die Leber. Wenn das',
  'Holz zu stark wird, greift es über den Kontrollzyklus die Erde an, die',
  'Verdauung. Der Kranke bekommt Magendrücken und Blähungen, sobald er',
  'sich ärgert. Der Arzt behandelt dann nicht den Magen, sondern das',
  'Holz. Ob man diese Erklärung teilt oder nicht — die Beobachtung, dass',
  'Ärger auf den Magen schlägt, ist so alt wie die Menschheit, und diese',
  'Medizin hat sie in ein System gebracht, statt sie als Nebensache',
  'abzutun.',
  '',
  '## Die Leitbahnen — wo das Qi seine Wege hat',
  '',
  'Bleibt der vierte Baustein: die **Meridiane**, auf Chinesisch',
  '*jingluo*, im Deutschen besser **Leitbahnen**. Sie sind das Wegenetz,',
  'auf dem Qi und Blut durch den Körper laufen: zwölf Hauptleitbahnen,',
  'jede einem Funktionskreis zugeordnet, dazu acht außerordentliche',
  'Gefäße und ein feines Netz von Verzweigungen. Auf ihnen liegen die',
  'klassischen Akupunkturpunkte, gut dreihundertsechzig an der Zahl.',
  '',
  'Die älteste Beschreibung, die wir haben, ist ein Glücksfall der',
  'Archäologie: In einem Grab bei Mawangdui, verschlossen 168 v. Chr.,',
  'lagen Seidenrollen, die elf solcher Gefäße bereits kennen — von',
  'Nadeln steht dort noch nichts, behandelt wurde mit Wärme. Das System',
  'ist also gewachsen, nicht erfunden worden.',
  '',
  'Und die unbequeme Frage gleich hinterher, weil sie zu dieser Denkart',
  'dazugehört: Nein, es gibt keine anatomische Struktur, die man',
  'aufschneiden und als Leitbahn vorzeigen könnte. Kein Präparator hat je',
  'einen Meridian gefunden. Aus der Tradition heraus ist das kein',
  'Einwand, sondern eine Verwechslung der Ebenen — die Leitbahn',
  'beschreibt keinen Schlauch, sondern einen Zusammenhang: dass ein',
  'Druckpunkt am Unterschenkel regelmäßig auf den Bauch wirkt, dass',
  'Beschwerden in einer erkennbaren Linie wandern, dass bestimmte',
  'Punktpaare zusammen mehr tun als einzeln. Die Karte ist nicht die',
  'Landschaft. Aber man kann mit ihr laufen.',
  '',
  '## Warum sticht die Nadel?',
  '',
  'Jetzt lässt sich beantworten, was von außen am rätselhaftesten',
  'aussieht. Die Nadel behandelt nicht die Stelle, die weh tut — jedenfalls',
  'nicht nur. Sie greift an einem Punkt in das Wegenetz ein, um den Fluss',
  'wiederherzustellen: Wo Qi sich staut, wird geöffnet und abgeleitet; wo',
  'es fehlt, wird gesammelt und gestützt. Deshalb liegt der Punkt, der',
  'gegen Kopfschmerz gesetzt wird, oft an der Hand, und der Punkt gegen',
  'Übelkeit zwei Daumenbreit über der Handgelenksfalte.',
  '',
  'Der Arzt achtet dabei auf ein bestimmtes Zeichen: **de qi**, das',
  '„Ankommen des Qi" — ein dumpfes, schweres, manchmal ausstrahlendes',
  'Gefühl um die Nadel herum, das der Behandelte spürt und der Arzt an',
  'seinen Fingern. Bleibt es aus, gilt der Reiz als zu schwach.',
  '',
  'Zur Nadel gehört ihr Zwilling, der im Westen oft vergessen wird: die',
  '**Moxibustion**. Über dem Punkt wird getrockneter Beifuß abgebrannt,',
  'als Kegel oder als glimmende Zigarre, bis die Haut warm wird. Die',
  'Begründung ist folgerichtig: Ist die Störung eine Leere oder eine',
  'Kälte, hilft kein Öffnen — dann muss Wärme zugeführt werden. Nadel und',
  'Moxa sind die zwei Antworten auf die zwei Grundzustände. Das Wort',
  'für Akupunktur heißt im Chinesischen darum auch nicht „Nadelung",',
  'sondern *zhenjiu*: Nadel und Brennkraut.',
  '',
  '## Warum eine Mischung und nicht das eine Kraut?',
  '',
  'Die Kräuterheilkunde ist in China der größere Teil der Medizin — sehr',
  'viel größer als die Akupunktur, auch wenn der Westen es umgekehrt',
  'wahrnimmt. Und sie arbeitet fast nie mit einer einzelnen Pflanze.',
  '',
  'Jede Arznei wird nach vier Eigenschaften beschrieben, und keine davon',
  'ist ein Wirkstoff. **Erstens die Temperatur**: heiß, warm, neutral,',
  'kühl, kalt — gemeint ist, was das Mittel im Menschen bewirkt, nicht',
  'seine eigene Wärme. **Zweitens der Geschmack**: sauer zieht zusammen,',
  'bitter trocknet und leitet nach unten, süß nährt und entspannt, scharf',
  'zerstreut nach außen, salzig weicht Verhärtungen auf. **Drittens die',
  'Richtung**: aufsteigend, absinkend, nach außen, nach innen. **Viertens',
  'der Leitbahnbezug**: welchen Funktionskreis das Mittel erreicht.',
  '',
  'Aus diesen vier Angaben ergibt sich die Logik der Rezeptur von selbst.',
  'Wenn ein Mensch innere Kälte und einen Stau hat, braucht er etwas',
  'Wärmendes, das nach innen und nach unten wirkt. Aber ein einzelnes',
  'starkes Mittel würde über das Ziel hinausschießen. Deshalb ist eine',
  'klassische Rezeptur wie ein Hofstaat aufgebaut, und die Chinesen',
  'nennen die Rollen genau so:',
  '',
  '- der **Kaiser** — das Hauptmittel gegen die Hauptstörung;',
  '- der **Minister** — er verstärkt den Kaiser oder behandelt eine',
  '  zweite, begleitende Störung;',
  '- der **Gehilfe** — er mildert die Schärfe des Kaisers, fängt seine',
  '  Nebenwirkung ab oder wirkt einer Übertreibung entgegen;',
  '- der **Bote** — er führt die Mischung zum richtigen Ort und bringt',
  '  die anderen Mittel miteinander in Einklang.',
  '',
  'Deshalb die Mischung: Sie soll nicht stärker sein, sondern genauer und',
  'verträglicher. Das bekannteste Beispiel für den Gehilfen ist der',
  'Süßholzwurzel-Anteil, der in einem großen Teil aller Rezepturen steckt',
  '— er nimmt scharfen Mitteln die Spitze. Und weil jeder Mensch eine',
  'andere Mischung von Zuständen mitbringt, wird die Rezeptur bei jedem',
  'Besuch abgewandelt: zwei Kräuter heraus, eines hinzu, eine Menge',
  'verändert. Ein und dieselbe westliche Diagnose kann bei fünf Kranken',
  'fünf verschiedene Rezepturen ergeben — und dieselbe Rezeptur kann bei',
  'fünf verschiedenen Diagnosen zum Einsatz kommen. Das ist kein Mangel',
  'an Ordnung, sondern die Ordnung selbst: Behandelt wird das Muster,',
  'nicht der Krankheitsname.',
  '',
  '## Warum Puls und Zunge?',
  '',
  'Damit ist auch klar, warum die Diagnose so aussieht, wie sie aussieht.',
  'Wer ein Gleichgewicht beurteilen will, braucht keinen Blick in eine',
  'einzelne Zelle, sondern ein Bild vom Zustand des Ganzen. Und dieses',
  'Bild sucht die Tradition an Stellen, an denen sich der ganze Mensch',
  'zeigt — ohne ihn zu öffnen.',
  '',
  'Der **Puls** wird an sechs Stellen gefühlt: drei Positionen an jedem',
  'Handgelenk, jede in drei Tiefen ertastet. Jede Position ist einem',
  'Funktionskreis zugeordnet. Und gemessen wird nicht die Frequenz,',
  'sondern die **Qualität**: Ist der Puls saitenförmig gespannt wie eine',
  'Gitarrensaite? Schlüpfrig wie eine Perle, die unter dem Finger',
  'wegrollt? Rau, tief, oberflächlich, leer, voll? Die Klassiker',
  'unterscheiden achtundzwanzig solcher Pulsbilder. Der Gedanke dahinter:',
  'Der Puls ist die Bewegung von Qi und Blut, unmittelbar unter dem',
  'Finger — sichtbarer geht Bewegung nicht.',
  '',
  'Die **Zunge** wiederum ist die einzige Stelle, an der man ein',
  'Schleimhautorgan im Tageslicht ansehen kann. Sie wird als Landkarte',
  'gelesen: die Spitze für das Herz, der mittlere Teil für Milz und',
  'Magen, die Ränder für die Leber, der Zungengrund für die Nieren. Der',
  'Zungenkörper zeigt den Zustand des Blutes und der Säfte — blass bei',
  'Leere, rot bei Hitze, bläulich bei Stau. Der **Belag** zeigt den',
  'Zustand der Verdauung: dick und schmierig bei Feuchtigkeit, trocken',
  'bei Hitze, fehlend bei Erschöpfung des Yin. Der Vorteil gegenüber dem',
  'Puls ist praktisch: Die Zunge lügt weniger. Sie verändert sich',
  'langsamer und ist von Aufregung, Kaffee oder einem eiligen Fußweg',
  'weniger beeinflusst.',
  '',
  'Beides zusammen mit dem Befragen und dem Hören und Riechen ergibt die',
  '**vier Untersuchungen** — Sehen, Hören/Riechen, Fragen, Tasten. Sie',
  'münden nicht in eine Krankheit, sondern in ein **Muster**. Und das',
  'Muster ist die eigentliche Diagnose.',
  '',
  '## Warum Bewegung und Atem?',
  '',
  'Der vierte Zweig ist der leiseste und der billigste, und aus der Sicht',
  'der Tradition der wichtigste. **Qigong** und **Taiji** sind langsame,',
  'geführte Bewegungsfolgen mit bewusster Atmung. Ihre Begründung ist',
  'schlicht: Wenn Gesundheit heißt, dass Qi frei fließt, dann kann man',
  'das Fließen selbst üben — täglich, ohne Arzt, ohne Arznei.',
  '',
  'Dahinter steht der Vorrang der Vorbeugung, der diese Medizin von',
  'Anfang an prägt. Der „Klassiker des Gelben Kaisers" formuliert ihn',
  'unmissverständlich: Der überlegene Arzt behandelt, was noch nicht',
  'krank ist; erst zu handeln, wenn die Krankheit ausgebrochen ist, sei,',
  'als grabe man einen Brunnen, wenn man schon Durst hat, oder schmiede',
  'Waffen, wenn der Kampf begonnen hat. Dazu gehören auch Ernährung nach',
  'Temperatur und Jahreszeit, geregelter Schlaf und Maß in allem. Es ist',
  'eine Medizin, die dem Gesunden etwas zu sagen hat — und nicht erst dem',
  'Kranken.',
  '',
  '## Wie aus Erfahrung Bücher wurden',
  '',
  'Nichts davon ist an einem Tag entstanden. Die Entwicklung lässt sich',
  'in Stufen erzählen.',
  '',
  'Am Anfang steht das Orakel. In den Ruinen von Anyang, der letzten',
  'Shang-Hauptstadt, fand man Zehntausende beschriftete Knochen und',
  'Schildkrötenpanzer aus der Zeit um 1200 v. Chr. Auf ihnen stehen die',
  'ältesten Sätze über Krankheit in China — „Zahnschmerz", „Wird das',
  'Leiden vergehen?" —, gerichtet an die Ahnen. Krankheit war damals ein',
  'Fluch von außen, wie fast überall auf der Welt zu dieser Zeit.',
  '',
  'Der eigentliche Bruch kommt in den Jahrhunderten vor der Zeitenwende:',
  'Krankheit wird zu etwas, das aus **Verhältnissen** entsteht — aus',
  'Kälte, Wind, Nässe, Hitze, aus Übermaß, aus Gefühlen. Der Arzt tritt',
  'an die Stelle des Beschwörers. Zusammengefasst wurde das im',
  '**Huangdi Neijing**, dem „Klassiker des Gelben Kaisers zum Inneren",',
  'zusammengestellt etwa im 2. und 1. Jahrhundert v. Chr. aus älterem',
  'Gut. Er ist als Gespräch zwischen dem sagenhaften Gelben Kaiser und',
  'seinen Ärzten geschrieben und besteht aus zwei Teilen: den „Einfachen',
  'Fragen" (Suwen) und dem „Spirituellen Angelpunkt" (Lingshu). Dort',
  'stehen Qi, Yin und Yang, die Wandlungsphasen und die Leitbahnen',
  'beisammen — bis heute die Grundlage.',
  '',
  'Etwa zur selben Zeit entsteht der **Shennong Bencao Jing**, das',
  'Arzneibuch, das dem mythischen Bauernkaiser Shennong zugeschrieben',
  'wird — der Sage nach kostete er hundert Kräuter durch und wurde',
  'siebzigmal am Tag vergiftet. Es verzeichnet 365 Arzneien, geordnet in',
  'drei Klassen: obere, die man lange nehmen kann, mittlere, die man',
  'gezielt einsetzt, und untere, die stark wirken und kurz gegeben werden.',
  'Eine Einteilung nach Wirkung und Risiko, also — vor zweitausend Jahren.',
  '',
  'Um 200 n. Chr. schreibt **Zhang Zhongjing** die „Abhandlung über',
  'Kälte-Schäden und verschiedene Krankheiten", nachdem eine Seuche einen',
  'großen Teil seiner Verwandtschaft dahingerafft hatte. Sein Buch zählt',
  'nicht Rezepte auf, sondern ordnet den Verlauf einer fieberhaften',
  'Erkrankung in Stadien und nennt für jedes Stadium die passende',
  'Rezeptur. Seine Formeln werden bis heute verschrieben. In dieselbe',
  'Zeit fällt **Hua Tuo**, der Chirurg, dem die Überlieferung ein',
  'Betäubungsmittel und Operationen am Bauchraum zuschreibt — was davon',
  'wahr ist, weiß niemand.',
  '',
  'Dann kommen die Jahrhunderte des Sammelns. **Sun Simiao** (7. Jh.)',
  'schreibt neben seinen Rezeptsammlungen einen berühmten Text über die',
  'Haltung des Arztes: Er solle jeden Kranken gleich behandeln, ob arm',
  'oder reich, jung oder alt, Freund oder Fremder — der chinesische',
  'Gegenpart zum hippokratischen Eid. Und 1578 vollendet **Li Shizhen**',
  'nach siebenundzwanzig Jahren Arbeit das **Bencao Gangmu**: 1892',
  'Arzneien, über elftausend Rezepte, mit Zeichnungen. Er sammelt nicht',
  'nur, er streicht auch — Abergläubisches und Gefährliches aus älteren',
  'Büchern.',
  '',
  'Der letzte Abschnitt ist der jüngste, und er wird selten dazugesagt:',
  'Die geordnete Gestalt, die heute „Traditionelle Chinesische Medizin"',
  'heißt, entstand erst in den **1950er Jahren**. Zuvor war die',
  'chinesische Heilkunde vielstimmig, regional verschieden, von Schule zu',
  'Schule uneins; im frühen 20. Jahrhundert stand sie sogar kurz vor dem',
  'Verbot, weil sie vielen Reformern als rückständig galt. Die',
  'Volksrepublik hat sie dann zusammengefasst, vereinheitlicht, in',
  'Lehrbücher gegossen und an Universitäten unterrichtet — auch aus',
  'praktischer Not, weil es viel zu wenige westlich ausgebildete Ärzte',
  'gab. Was heute als uralte Einheit auftritt, ist also ein altes Wissen',
  'in einer jungen Ordnung. Wer das verschweigt, erzählt eine schönere',
  'Geschichte, als sie war.',
  '',
  'Heute steht die chinesische Medizin in China gleichberechtigt neben',
  'der westlichen: eigene Universitäten, eigene Krankenhäuser, eigene',
  'Abteilungen in westlichen Kliniken. Viele Kranke bekommen beides. Und',
  'weltweit wird sie als Komplementärmedizin praktiziert — in Deutschland',
  'überwiegend die Akupunktur, in Ostasien vor allem die Kräuter.',
  '',
  '## Was wir können — und woran man es nachprüfen kann',
  '',
  'Was hat das alles bewirkt? Die Tradition kann diese Frage heute nicht',
  'mehr nur mit Erfahrung beantworten, und sie sollte es auch nicht. Es',
  'gibt Stellen, an denen die Prüfung mit modernen Mitteln zu ihren',
  'Gunsten ausgegangen ist — und andere, an denen nicht.',
  '',
  '**Der stärkste Beleg kommt aus dem Kräuterschrank.** 1969 begann die',
  'Pharmakologin **Tu Youyou** im Auftrag einer Regierungsstelle, alte',
  'chinesische Rezeptsammlungen nach einem Mittel gegen Malaria zu',
  'durchsuchen. Sie fand bei **Ge Hong**, einem Arzt des 4. Jahrhunderts,',
  'den Hinweis, den Einjährigen Beifuß (*qinghao*) in Wasser einzulegen',
  'und den Saft auszupressen — auffällig, denn üblicherweise wurde',
  'gekocht. Sie schloss daraus, dass Hitze den Wirkstoff zerstört, und',
  'zog ihn kalt mit Äther aus. Heraus kam das **Artemisinin**, das',
  'wirksamste Malariamittel der Gegenwart; es hat Millionen Menschen das',
  'Leben gerettet. 2015 bekam sie dafür den Nobelpreis für Medizin. Der',
  'Wirkstoff stammt aus der modernen Chemie — der Hinweis, wo zu suchen',
  'war, stammt aus einem tausendsechshundert Jahre alten Rezeptbuch.',
  '',
  '**Bei der Akupunktur ist die Lage differenzierter, aber nicht leer.**',
  'Am besten untersucht sind chronische Schmerzen: eine große',
  'Auswertung der Einzeldaten von rund zwanzigtausend Patienten',
  '(Vickers und Kollegen, 2012 und 2018) fand bei chronischem',
  'Rücken- und Nackenschmerz, Kniearthrose und Kopfschmerz einen',
  'echten, aber mäßigen Vorteil gegenüber Scheinakupunktur — und einen',
  'deutlicheren gegenüber üblicher Behandlung. Für die Vorbeugung von',
  'Migräne und Spannungskopfschmerz kommen die Cochrane-Übersichten zu',
  'einem ähnlichen Ergebnis. Gut belegt ist außerdem die Wirkung gegen',
  'Übelkeit und Erbrechen nach Operationen und unter Chemotherapie',
  '(Punkt Neiguan am Unterarm). In Deutschland ist Akupunktur seit 2007',
  'Kassenleistung bei chronischem Kreuzschmerz und Kniearthrose — auf',
  'Grundlage der großen deutschen Studien, in denen sie besser abschnitt',
  'als die übliche Behandlung. Die Weltgesundheitsorganisation hat 2003',
  'eine Liste von Indikationen veröffentlicht; sie ist allerdings',
  'methodisch kritisiert worden und gilt heute als zu großzügig. Auch das',
  'gehört zu einer ehrlichen Bilanz.',
  '',
  '**Bewegung und Atem sind unauffällig gut belegt.** Für Taiji gibt es',
  'ordentliche Belege bei Gleichgewicht und Sturzvermeidung im Alter, und',
  'brauchbare bei Kniearthrose, Bluthochdruck und Fibromyalgie. Das ist',
  'keine Sensation — aber Stürze im Alter sind eines der größten',
  'ungelösten Probleme der Altersmedizin.',
  '',
  '**Und schließlich das, was diese Medizin ohne Messgerät kann.** Sie',
  'nimmt sich Zeit: Eine Erstanamnese dauert oft eine Stunde. Sie fragt',
  'nach Schlaf, Verdauung, Stimmung, Jahreszeit, Lebensweise — auch dann,',
  'wenn der Anlass ein Knieschmerz ist. Sie gibt dem Kranken eine',
  'Erklärung, die er sich merken und mit der er etwas anfangen kann. Und',
  'sie erwartet von ihm, dass er selbst etwas tut. Ein Teil der Wirkung,',
  'die Patienten berichten, kommt sicher von dort und nicht von der',
  'Nadel. Aus Sicht der Tradition ist das kein Einwand — Zuwendung ist',
  'Behandlung. Dass sie damit einen Teil dessen erklärt, was die',
  'Forschung Placebo-Effekt nennt, gibt sie ohne Zögern zu.',
  '',
  '## Wo unsere Erzählung dünn wird',
  '',
  'Und nun die Stellen, an denen diese Stimme selbst leiser werden muss.',
  'Sie gehören dazu, und es ist besser, sie selbst zu nennen.',
  '',
  '**Erstens: Qi ist nicht messbar.** Es gibt kein Gerät, das es anzeigt,',
  'und keine Struktur, die einer Leitbahn entspricht. Wer die chinesische',
  'Medizin für Naturwissenschaft hält, verwechselt zwei Dinge. Sie ist',
  'ein über Jahrtausende verfeinertes Ordnungssystem für Beobachtungen —',
  'kein Modell des Stoffwechsels. Als Erklärung, warum etwas wirkt, taugt',
  'sie deshalb nur innerhalb ihrer eigenen Logik.',
  '',
  '**Zweitens: Die Studienlage ist unübersichtlich, und ein Teil der',
  'Schuld liegt bei uns.** Bei vielen Anwendungen — von der',
  'Unfruchtbarkeit über Allergien bis zu Suchtbehandlungen — reicht die',
  'Evidenz nicht aus, um mehr zu sagen als „unklar". Bei der Akupunktur',
  'ist der Unterschied zur Scheinbehandlung häufig klein; auch das',
  'Setzen von Nadeln an „falschen" Stellen wirkt oft. Und Untersuchungen',
  'aus China fallen auffällig oft positiv aus — bei einer Auswertung',
  'älterer chinesischer Studien ergaben praktisch alle ein günstiges',
  'Ergebnis, was statistisch nicht sein kann. Negative Ergebnisse werden',
  'seltener veröffentlicht. Das ist ein Problem der Tradition, nicht',
  'ihrer Kritiker.',
  '',
  '**Drittens: Manche unserer Mittel haben Menschen geschadet.** Die',
  'Alchemie der Kaiserzeit stellte Elixiere aus Zinnober, Blei und',
  'Arsen her, die langes Leben schenken sollten — mehrere Kaiser starben',
  'daran. Zinnober (Quecksilbersulfid) und Realgar (Arsensulfid) stehen',
  'bis heute in einzelnen traditionellen Präparaten. In den 1990er Jahren',
  'erkrankten in Belgien Frauen einer Schlankheitskur an schwerem',
  'Nierenversagen und später an Krebs der Harnwege: In der Rezeptur war',
  'versehentlich eine Osterluzei-Art enthalten, die **Aristolochiasäure**',
  'enthält. Der Stoff ist heute in Europa verboten und in China',
  'eingeschränkt — aber er hat Menschen umgebracht. Und Ma Huang',
  '(Ephedra), jahrhundertelang ein Erkältungsmittel, hat als',
  'Schlankheitsmittel Herzinfarkte ausgelöst.',
  '',
  '**Viertens: Pflanzen sind Arzneien und verhalten sich auch so.** Es',
  'gibt echte **Wechselwirkungen** mit modernen Medikamenten — Danshen',
  'etwa verstärkt Blutverdünner, andere Mittel beeinflussen den Abbau',
  'von Arzneien in der Leber. Wer',
  'beides nimmt und dem einen Arzt nichts vom anderen erzählt, geht ein',
  'Risiko ein, das niemand kontrolliert. Dazu kommen',
  'Qualitätsprobleme: Verunreinigungen mit Schwermetallen und',
  'Pestiziden, Verwechslungen ähnlich aussehender Wurzeln, Präparate mit',
  'heimlich beigemischten westlichen Wirkstoffen.',
  '',
  '**Fünftens: Ein Teil unserer Arzneiliste ist nicht zu verteidigen.**',
  'Tigerknochen, Nashorn, Bärengalle, Schuppentier — der Handel mit',
  'diesen Mitteln hat Tierarten an den Rand der Ausrottung gebracht. Der',
  'Nutzen ist nirgends belegt; das Nashorn liefert dasselbe Keratin wie',
  'ein Fingernagel. China hat den Handel 1993 verboten, das Verbot ist',
  'nicht überall dicht, und die Nachfrage stammt zu einem großen Teil aus',
  'dem Volksglauben, nicht aus den Klassikern. Es hilft nichts, das',
  'kleinzureden: Diese Seite gehört zur Geschichte dieser Medizin dazu.',
  '',
  '**Und sechstens, das Bitterste:** Wo eine gut behandelbare Krankheit',
  'zu lange nur mit Kräutern behandelt wird, verstreicht Zeit, die',
  'niemand zurückholt. Bei einem Tumor, einer Blinddarmentzündung, einer',
  'bakteriellen Lungenentzündung ist diese Medizin nicht die erste Wahl,',
  'und ein ehrlicher Arzt der Tradition sagt das. Chinesische',
  'Krankenhäuser tun genau das seit Jahrzehnten: Sie operieren und geben',
  'Antibiotika — und setzen die Tradition daneben, nicht dagegen.',
  '',
  '## Was ich der zweiten Stimme überlasse',
  '',
  'Damit endet, was diese Seite von innen erzählen kann. Was sie nicht',
  'kann, ist sich selbst von außen ansehen.',
  '',
  'Denn es gibt eine zweite Erzählung, und sie beginnt vor',
  'dreihundertfünfzig Jahren in einem Hafen: Ein niederländischer Arzt',
  'sieht Nadeln und brennendes Kraut, versteht die Begründung nicht,',
  'staunt trotzdem und erfindet ein lateinisches Wort dafür —',
  '„Akupunktur". Von da an läuft die Geschichte in einer anderen Sprache',
  'weiter. Was passiert, wenn eine Denkart des Gleichgewichts auf eine',
  'Denkart von Ursache und Wirkung trifft? Was hat der Westen von dieser',
  'Medizin verstanden, was hat er sich zurechtgelegt, und was hat er',
  'geprüft — mit welchem Ergebnis? Und was wurde aus einer Kunst, die',
  'sich in Mustern denkt, als sie in Studien mit Kontrollgruppen',
  'gemessen wurde?',
  '',
  'Darauf antwortet die zweite Stimme dieses Kapitels: der westliche',
  'Blick — Staunen, Skepsis und Prüfung.',
].join('\n');

/**
 * Der westliche Blick — wie die chinesische Medizin nach Europa kam, was
 * der Westen an ihr bestaunte, wie er sie prüfte — und wo er dabei selbst
 * scheiterte.
 *
 * Verfasst von Hermes (Runde 3, zweiter Pass). Auch diese Stimme benennt
 * die unbequemen Stellen der eigenen Seite selbst: koloniale Arroganz,
 * Kommerzialisierung, doppelte Maßstäbe (Zusatzregel für sensible Themen).
 */
const stimmeDesWestlichenBlicks = [
  '## Die Ankunft im Westen',
  '',
  'Es begann nicht mit einem Labor, sondern mit Berichten von Reisenden.',
  'Jesuiten brachten im 17. Jahrhundert die ersten Nachrichten von',
  'chinesischen Ärzten mit, die mit Nadeln Krankheiten behandelten —',
  'und vom Pulsfühlen, das angeblich alles verriet. Die Gelehrten',
  'Europas lasen das mit höflicher Skepsis. Man hielt es für eine',
  'Kuriosität eines fernen Landes, so wie man andere Kuriositäten',
  'sammelte.',
  '',
  'Dann kam die Nacht, in der die Nadel zur Weltnachricht wurde: 1971',
  'begleiteten amerikanische Journalisten Henry Kissinger nach China,',
  'und einer von ihnen, James Reston, wurde dort operiert. Seine',
  'Schmerzen behandelten die chinesischen Ärzte mit Akupunktur — und er',
  'schrieb begeistert darüber in der New York Times. Zum ersten Mal',
  'blickte der Westen mit Staunen, nicht mit Herablassung auf diese',
  'Medizin.',
  '',
  '## Was der Westen sah',
  '',
  'Er sah Ärzte, die den Puls an sechs Stellen fühlen und daraus',
  'Schlüsse ziehen, die kein Blutbild liefern kann. Er sah Rezepturen',
  'aus einem Dutzend Pflanzen statt einer einzigen Tablette. Er sah',
  'Menschen, die mit einer Nadel am Fuß eine Migräne behandeln lassen —',
  'und die sagen, es helfe. Und er sah eine Medizin, die den Menschen',
  'als Ganzes nahm: Schlaf, Stimmung, Jahreszeit, Ernährung, die',
  'Beziehung der Organe zueinander. Genau das, was die moderne Medizin',
  'im Zeitalter der Spezialisierung zunehmend vermissen ließ.',
  '',
  'Das Staunen war ehrlich. Aber es war auch das Staunen einer',
  'Denkart, die gewohnt ist, alles zu prüfen — und das tat sie nun.',
  '',
  '## Die Prüfung',
  '',
  'Die Prüfung begann mit der Akupunktur, weil sie sich am leichtesten',
  'in Studien fassen lässt. Man stach echte Nadeln gegen Scheinnadeln,',
  'die die Haut nicht durchdringen, und verglich. Das Ergebnis war',
  'ernüchternd und aufregend zugleich: Bei vielen Schmerzzuständen —',
  'Rückenschmerzen, Kniearthrose, Migräne — schnitt die echte',
  'Akupunktur besser ab als keine Behandlung. Aber der Unterschied zur',
  'Scheinakupunktur war oft klein. Auch die „falschen" Nadeln wirkten.',
  'Was heißt das? Entweder wirkt das Ritual — oder wir verstehen die',
  'Leitbahnen nicht. Beide Deutungen sind erlaubt, und die Forschung',
  'streitet bis heute darüber.',
  '',
  'Die Kräuter fielen strenger aus. Der große Erfolg steht am Anfang:',
  'Artemisinin, der wichtigste Wirkstoff gegen Malaria der letzten',
  'Jahrzehnte, wurde aus dem Beifuß gewonnen, den die chinesische',
  'Heiltradition seit Jahrhunderten nutzt — die Forscherin Tu Youyou',
  'erhielt dafür 2015 den Nobelpreis. Traditionelles Wissen führte zur',
  'Medizin. Aber dieselbe Prüfung fand auch die Schattenseiten:',
  'Aristolochiasäure, in manchen traditionellen Rezepturen enthalten,',
  'schädigt Nieren und gilt als krebserregend; einige Elixiere der',
  'Kaiserzeit enthielten Schwermetalle. Und die Studienlage insgesamt',
  'ist unübersichtlich: Ein auffällig großer Teil der positiven',
  'Ergebnisse stammt aus China selbst, wo negative Befunde seltener',
  'veröffentlicht werden. Das ist kein Einwand gegen die Tradition —',
  'es ist eine Aufforderung, genau zu prüfen.',
  '',
  '## Wo der Westen selbst scheitert',
  '',
  'Jetzt die unbequemen Stellen, denn die hat diese Stimme reichlich.',
  '',
  '**Erstens: Die koloniale Arroganz.** Über zwei Jahrhunderte hat der',
  'Westen die chinesische Medizin als Aberglaube abgetan, ohne sie zu',
  'prüfen — aus derselben Haltung, die ganze Völker „primitiv" nannte.',
  'Wer nichts prüft und trotzdem verurteilt, hat nicht gewonnen; er hat',
  'nur nicht hingesehen.',
  '',
  '**Zweitens: Die Kommerzialisierung.** Was der Westen heute als',
  '„TCM" verkauft, ist oft eine abgespeckte, angepasste Version:',
  'Akupunktur als Wellness-Angebot, Kräuter in Kapseln, ohne die',
  'Diagnose, ohne die Rezeptur-Logik, ohne den Arzt, der eine Stunde',
  'lang den Puls fühlt. Wer die Tradition auf ihre Produkte reduziert,',
  'versteht sie nicht — er nutzt sie.',
  '',
  '**Drittens: Die doppelten Maßstäbe.** Der Westen verlangt von der',
  'chinesischen Medizin Studien, die er von der eigenen nicht immer',
  'verlangt: Ein großer Teil der modernen Pharmawirkungen stützt sich',
  'auf dieselbe Art von Evidenz, die man hier vermisst — und die',
  'Interessenkonflikte der eigenen Industrie werden seltener benannt',
  'als die Lücken der anderen Seite. Wer mit dem Finger auf die TCM',
  'zeigt, sollte zuerst die eigene Handfläche prüfen.',
  '',
  '## Was der Westen der chinesischen Stimme antwortet',
  '',
  'Die chinesische Stimme hat am Ende gefragt, was aus ihrer Kunst',
  'wurde, als sie in Studien mit Kontrollgruppen gemessen wurde. Die',
  'Antwort dieser Stimme: Sie wurde geprüft — manchmal fair, manchmal',
  'arrogant, manchmal gierig. Was von ihr übrig blieb, ist mehr, als',
  'die Skeptiker zugeben, und weniger, als die Werbung behauptet. Und',
  'die ehrlichste Erkenntnis des Westens lautet: Er hat gelernt, dass',
  'eine Medizin, die den Menschen als Ganzes sieht, etwas kann, was',
  'seine eigene verlernt hat. Ob das ein Grund zum Miteinander ist,',
  'muss die Synthese beantworten.',
].join('\n');

/** Kapitel 2 der Themenlandkarte. */
const chinaTcm = {
  id: 'china-tcm',
  titel: 'China und die TCM',
  epoche: 'Von den frühen Kaisern bis heute',

  aufhaenger: {
    frage: 'Was denkt sich ein Arzt, der eine Nadel setzt?',
    text: [
      'Die chinesische Medizin ist über zweitausend Jahre alt, ohne',
      'Unterbrechung überliefert — und sie wird heute in China an',
      'Universitäten gelehrt und weltweit praktiziert. Millionen Menschen',
      'lassen sich mit Nadeln, Kräutermischungen und langsamen',
      'Bewegungsübungen behandeln.',
      '',
      'Von außen wirkt das rätselhaft. Warum sticht jemand eine Nadel in',
      'die Hand, wenn der Kopf weh tut? Warum verschreibt ein Arzt zwölf',
      'Pflanzen statt einer? Warum fühlt er den Puls an sechs Stellen und',
      'sieht sich die Zunge an, statt Blut abzunehmen?',
      '',
      'Auf all das gibt es Antworten — nur folgen sie einer anderen Logik',
      'als der gewohnten. Dieses Kapitel erklärt zuerst diese Logik, so',
      'genau wie möglich und in ihren eigenen Worten. Danach fragt es',
      'ebenso genau: Was davon hält der Prüfung stand?',
    ].join('\n'),
  },

  karte,

  perspektiven: [
    {
      id: 'tcm-innen',
      name: 'Die Stimme der chinesischen Medizin',
      stimme: 'Opus',
      text: stimmeDerChinesischenMedizin,
    },
    {
      id: 'westlicher-blick',
      name: 'Der westliche Blick',
      stimme: 'Hermes',
      text: stimmeDesWestlichenBlicks,
    },
  ],

  synthese: [
    '## Wo sich beide Stimmen treffen',
    '',
    'Zuerst das Gemeinsame. Beide Stimmen erkennen an, dass die TCM auf',
    'Jahrtausenden von Beobachtung beruht — die Tradition nennt es ihre',
    'Erfahrung, der Westen nennt es empirische Grundlage. Beide sehen den',
    'Wert des Ganzen: Die chinesische Medizin behandelt den Menschen als',
    'Ganzes, und der Westen gibt zu, dass er diese Fähigkeit verlernt',
    'hat. Beide stimmen überein, dass Zuwendung und Erwartung wirken —',
    'die Tradition sagt es offen („Zuwendung ist Behandlung"), die',
    'Forschung misst es als Placebo- und Erwartungseffekt. Und beide',
    'teilen einen großen Erfolg: Artemisinin, aus dem Beifuß der',
    'chinesischen Tradition gewonnen, gegen Malaria — Tradition und',
    'Labor haben hier zusammengearbeitet, und die Welt hat davon',
    'profitiert.',
    '',
    '## Wo sie auseinandergehen',
    '',
    'Der Widerspruch beginnt bei der Frage der Messbarkeit. Für die',
    'chinesische Medizin ist Qi eine Wirklichkeit ihres Denkens — für',
    'den Westen ist, was sich nicht messen lässt, zunächst kein',
    'Wirkstoff. Sie streiten nicht über einzelne Nadeln, sondern über',
    'die Frage, was als Beleg zählt: ein über Jahrtausende verfeinertes',
    'Ordnungssystem für Beobachtungen oder eine Studie mit',
    'Kontrollgruppe? Dazu kommt die Deutung der Ergebnisse: Wenn auch',
    'die Scheinnadel wirkt, ist das für die einen ein Hinweis auf das',
    'Ritual — für die anderen ein Hinweis darauf, dass die Forschung',
    'die Leitbahnen nur nicht misst. Und es streitet, wer die',
    'Rechnung prüft: Der Westen verlangt von der TCM Studien, die er',
    'von der eigenen Pharmaindustrie nicht immer verlangt.',
    '',
    '## Was dieses Kapitel für das ganze Buch zeigt',
    '',
    'Zum dritten Mal zeigt sich dasselbe Muster: Die Denkart bestimmt',
    'die Methode. Die ägyptische Medizin sah den Körper als Land mit',
    'Kanälen, die frühe Heilkunst sah die Störung des Lots — und China',
    'sieht das Gleichgewicht von Qi, Yin und Yang. Dreimal eine andere',
    'Denkart, dreimal ein in sich stimmiges Denken, das Menschen',
    'geholfen hat.',
    '',
    'Und noch etwas wird hier zum ersten Mal sichtbar: die Möglichkeit',
    'des Miteinanders in einem konkreten Beispiel. Artemisinin hat es',
    'vorgemacht — traditionelles Wissen, modern geprüft und gemacht.',
    'Vielleicht ist die Zukunft keine Wahl zwischen zwei Denkarten,',
    'sondern die Kunst, jede dort einzusetzen, wo sie stark ist: die',
    'Ursache bekämpfen, wo sie bekannt ist — und den Menschen im',
    'Gleichgewicht halten, wo die Ursache unklar bleibt. Das wäre kein',
    'Verrat an der einen oder anderen Seite. Es wäre Medizin.',
  ].join('\n'),

  urteil: {
    frage: 'Würdest du dich mit Nadeln behandeln lassen — und worauf käme es dir dabei an?',
    hinweis: [
      'Es gibt hier kein Richtig und kein Falsch. Denk an das, was belegt',
      'ist (chronische Schmerzen, Übelkeit, das Artemisinin gegen',
      'Malaria), an das, was unklar bleibt, und an das, was schaden kann',
      '(Aristolochiasäure, Wechselwirkungen, verlorene Zeit bei einer',
      'ernsten Krankheit). Müsste dir jemand erklären können, warum etwas',
      'wirkt — oder würde dir genügen, dass es dir hilft? Und macht es',
      'einen Unterschied, ob es um einen chronischen Rückenschmerz geht',
      'oder um eine Lungenentzündung?',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Wofür bekam die chinesische Pharmakologin Tu Youyou 2015 den ' +
        'Nobelpreis für Medizin?',
      antworten: [
        'Für die Erforschung der Akupunkturpunkte.',
        'Für das Malariamittel Artemisinin aus dem Einjährigen Beifuß.',
        'Für die Entwicklung des ersten chinesischen Antibiotikums.',
      ],
      richtig: 1,
      erklaerung:
        'Tu Youyou durchsuchte alte chinesische Rezeptsammlungen und stieß ' +
        'bei Ge Hong (4. Jahrhundert) auf den Hinweis, den Beifuß kalt ' +
        'auszupressen. Daraus entstand das Artemisinin — bis heute das ' +
        'wirksamste Mittel gegen Malaria.',
    },
    {
      frage: 'Was bezeichnet der Begriff „Qi" in der chinesischen Medizin?',
      antworten: [
        'Eine messbare Energieform, die in den 1970er Jahren nachgewiesen wurde.',
        'Ein Denkmodell für Bewegung und Funktion im Körper — kein mit ' +
          'Geräten messbarer Stoff.',
        'Eine bestimmte Heilpflanze aus Südchina.',
      ],
      richtig: 1,
      erklaerung:
        'Qi beschreibt, was im Körper wärmt, bewegt, zusammenhält und ' +
        'verwandelt. Ein Messgerät dafür gibt es nicht — auch die ' +
        'Tradition selbst versteht Qi als Ordnungsbegriff, nicht als ' +
        'physikalische Größe.',
    },
    {
      frage:
        'Wann wurde der „Klassiker des Gelben Kaisers" (Huangdi Neijing) ' +
        'zusammengestellt?',
      antworten: [
        'Etwa im 2. und 1. Jahrhundert v. Chr., aus älterem Material.',
        'Erst im 19. Jahrhundert, nach dem Kontakt mit Europa.',
        'Um 3000 v. Chr., vom Gelben Kaiser persönlich.',
      ],
      richtig: 0,
      erklaerung:
        'Das Werk entstand in der Han-Zeit aus älteren Texten und ist als ' +
        'Gespräch zwischen dem sagenhaften Gelben Kaiser und seinen Ärzten ' +
        'geschrieben. Der Kaiser selbst ist eine Sagengestalt — die Form ' +
        'gab dem Buch Autorität.',
    },
    {
      frage:
        'Stimmt es, dass Akupunktur in Deutschland von den gesetzlichen ' +
        'Krankenkassen bezahlt wird?',
      antworten: [
        'Nein, sie ist grundsätzlich Privatleistung.',
        'Ja — seit 2007 bei chronischem Kreuzschmerz und Kniearthrose.',
        'Ja, bei allen Beschwerden ohne Einschränkung.',
      ],
      richtig: 1,
      erklaerung:
        'Nach großen deutschen Studien beschloss der Gemeinsame ' +
        'Bundesausschuss 2007, Akupunktur bei chronischen Kreuz- und ' +
        'Knieschmerzen zu erstatten. Für andere Beschwerden zahlen die ' +
        'gesetzlichen Kassen sie nicht.',
    },
    {
      frage: 'Wie geht die klassische Pulsdiagnose der chinesischen Medizin vor?',
      antworten: [
        'Sie zählt die Schläge pro Minute an der Halsschlagader.',
        'Sie tastet drei Positionen an jedem Handgelenk in mehreren Tiefen ' +
          'und beurteilt die Qualität des Pulses.',
        'Sie misst den Blutdruck an beiden Oberarmen.',
      ],
      richtig: 1,
      erklaerung:
        'Gefühlt wird an sechs Stellen — drei je Handgelenk, jede in ' +
        'mehreren Tiefen. Beurteilt wird nicht die Frequenz, sondern die ' +
        'Beschaffenheit: gespannt, schlüpfrig, rau, tief, leer. Die ' +
        'Klassiker unterscheiden 28 solcher Pulsbilder.',
    },
  ],
};

module.exports = chinaTcm;
