// Kapitel 18 — „Die einfache Medizin".
//
// Das HERZSTÜCK des Buches (CLAUDE.md, Betreiber-These vom 26.08.2026):
// Die Behandlung chronischer Erkrankungen ist eigentlich sehr einfach —
// 1) Bewegung, 2) ausgeglichene und gesunde Ernährung (wenig
// verarbeitetes Essen), 3) gutes soziales Umfeld und wenig Stress.
// „Diese Dinge kann jeder in eigener Verantwortung machen — dafür bedarf
// es keiner Raketenwissenschaft. Mit diesen einfachen
// Lebensstil-Anpassungen könnte vermutlich viel mehr Gesundheit erkauft
// werden als mit den neuesten Chemie-Präparaten."
//
// Die Leitfrage des Kapitels (Betreiber-Vorgabe): Warum verschreibt die
// Medizin Pillen statt Lebensstil?
//
// TONE-REGEL (verbindlich): BEIDE Seiten fair. Die Schulmedizin bekommt
// ihre Erfolge (die Akutmedizin rettet Leben, die Diagnostik ist
// hervorragend) UND ihre dunklen Stellen (Pille statt Rat, die
// Finanzinteressen, die Grenzen bei chronischen Krankheiten). Die
// Lebensstil-Medizin bekommt ihre Belege UND ihre Grenzen: Nicht jeder
// kann seinen Lebensstil wählen (Geld, Zeit, Schichtarbeit, Wohnort), der
// Lebensstil-Vorwurf darf Kranke nicht stigmatisieren, und die Studie,
// die gegen die These spricht (Look AHEAD, 2013), steht ausdrücklich im
// Text.
//
// KEINE GERÜCHTE (Betreiber-Entscheid 25.08.2026): Nur Belegtes, mit
// Namen und Jahr. Framingham 1948, Morris 1953, Sieben-Länder-Studie
// 1958, Roseto ab 1961, Nordkarelien ab 1972, Whitehall II ab 1985,
// Diabetes Prevention Program 2002, INTERHEART 2004, Blue Zones 2004/05,
// EPIC-Potsdam 2009, Holt-Lunstad 2010/2015, Look AHEAD 2013, DiRECT
// 2018, Hall 2019, WHO-Zahlen zu nichtübertragbaren Krankheiten. Wo eine
// Zahl umstritten ist (die Hundertjährigen-Quoten der blauen Zonen, die
// zurückgezogene und neu veröffentlichte PREDIMED-Studie), sagt der Text
// das dazu.
//
// DER INNOVATIONS-ZYKLUS (Betreiber-Beobachtung 26.08.2026, roter Faden):
// Hier steht das Muster auf dem Kopf. Die einfache Medizin ist uralt und
// hat nie massenhaft geschadet — sie wurde von der teuren, komplexen
// Medizin verdrängt, die akut Leben rettet, chronische Krankheiten aber
// oft nur verwaltet. Der Zyklus zeigt sich erst, wenn die einfache Idee
// zur Ware wird: Wellness-Wirtschaft, Diät-Markt, Nahrungsergänzung,
// Selbstvermessung. Die erste Stimme benennt das selbst (Abschnitt „Wenn
// das Einfache zur Ware wird").
//
// LÄNGENREGEL (Betreiber-Feedback 24.08.2026): Ab der Neuzeit gilt die
// Umkehrung — vollständig und ausführlich. Gemessen wird in
// tests/karte-einfache-medizin.mjs.
//
// Stimmen (Runde 19): Die ERSTE Perspektive — „Die Stimme des Alltags",
// die einfache Medizin von innen, aus dem Leben der Menschen — verfasste
// Opus. Die ZWEITE („Die Stimme der Verhältnisse": Industrie, Werbung,
// Arbeitswelt, Pille statt Rat — was einen gesunden Lebensstil schwer
// macht) und die finale Synthese ergänzt Hermes im zweiten Pass
// (Hermes-Pass, 29.08.2026: „ergänzt").
// Perspektiven-Workflow: CLAUDE.md. Beide Stimmen sind gleichwertig; die
// Reihenfolge ist willkürlich und keine Wertung.
//
// KEINE WIEDERHOLUNGEN (Betreiber-Entscheid vom 21.08.2026): Kapitel 1
// gliedert nach „Wer hier spricht", Kapitel 2 beginnt mit einer Szene,
// Kapitel 3 erzählt einen Tageslauf, Kapitel 4 ist ein Briefwechsel,
// Kapitel 5 die Reise eines Buches, Kapitel 6 ein Rundgang, Kapitel 7 ein
// Prozess, Kapitel 8 eine Rechnung, Kapitel 9 eine Uhr, Kapitel 10 eine
// Kette, Kapitel 11 eine Linse, Kapitel 12 ein Interview, Kapitel 13 eine
// Akte, Kapitel 14 ein Beipackzettel, Kapitel 15 eine Pressekonferenz,
// Kapitel 16 das Telefon, Kapitel 17 das Wasser selbst. Dieses Kapitel
// wählt die neunzehnte Dramaturgie: DIE STUNDEN. Ein Mensch mit einer
// chronischen Krankheit verbringt im Jahr etwa zwei Stunden bei Ärzten —
// und 8.758 Stunden woanders. Die Stimme des Alltags ist die Stimme
// dieser 8.758 Stunden. Die zweite Stimme kann in dieselbe Form treten:
// dieselben Stunden, aber von außen — wem sie gehören, wer sie einteilt
// und wer an ihnen verdient.
//
// Die Texte liegen als Zeilen-Arrays mit `.join('\n')` — so bleiben sie im
// Repo bei ~72 Zeichen lesbar (der Betreiber liest sie hier gegen), und
// utils/markdown.js macht in der App wieder fließenden Text daraus.
//
// CommonJS ohne UI-Importe (Architektur-Regel): mit blankem `node` prüfbar.

const { karte } = require('./karten/einfache-medizin');

/**
 * Die Stimme des Alltags — die einfache Medizin von innen.
 *
 * Verfasst von Opus (Runde 19). Sie spricht nicht für eine Schule und
 * nicht für einen Berufsstand, sondern für das, was zwischen zwei
 * Arztbesuchen geschieht: der Körper, der Bewegung will; der Teller, die
 * Treppe, der Schlaf, die Menschen um einen herum. Sie trägt ihre besten
 * Gründe vor — und sie benennt die unbequemen Stellen selbst
 * (Zusatzregel für sensible Themen in CLAUDE.md).
 */
const stimmeDesAlltags = [
  '## Die zwei Stunden',
  '',
  'Rechne einmal nach, wie viel Medizin in Deinem Jahr steckt.',
  '',
  'Ein Mensch in Deutschland mit einer chronischen Krankheit — Bluthochdruck,',
  'Typ-2-Diabetes, Rückenschmerzen, ein müdes Herz — geht vielleicht vier-,',
  'fünfmal im Jahr in eine Praxis. Ein Hausarztgespräch dauert hier im',
  'Durchschnitt **etwa siebeneinhalb Minuten**; eine Untersuchung von 2017,',
  'die Sprechzeiten in 67 Ländern verglichen hat, kam für Deutschland auf',
  '**7,6 Minuten** (Irving u. a., BMJ Open 2017). Nimm die Wartezeit heraus,',
  'nimm das Blutabnehmen dazu, nimm zwei Facharzttermine und einmal ein',
  'Röntgenbild hinzu. Dann kommst Du im Jahr auf ungefähr **zwei Stunden',
  'Medizin.**',
  '',
  'Ein Jahr hat 8.760 Stunden.',
  '',
  '**Ich bin die anderen 8.758.**',
  '',
  '## Die 8.758 Stunden',
  '',
  'Ich bin kein Verfahren, keine Schule, kein Berufsstand. Ich bin das, was',
  'zwischen zwei Terminen passiert: die Treppe im Hausflur, der Teller am',
  'Abend, die vier Stunden auf dem Bürostuhl, der Weg zur Bushaltestelle,',
  'die Nacht, in der Du dreimal aufwachst, der Anruf, den Du nicht',
  'bekommen hast. Ich bin unauffällig, und genau das ist mein Problem:',
  'Niemand verschreibt mich, niemand rechnet mich ab, niemand forscht',
  'ohne Not an mir, und trotzdem bin ich es, in der die meisten',
  'chronischen Krankheiten gemacht werden — und manchmal wieder',
  'zurückgenommen.',
  '',
  '**Was Du hier liest, ist eine Denkart, keine Wahrheit.** Ich spreche für',
  'die Seite, deren Mittel nichts kosten und deshalb kaum jemandem gehören:',
  'Gehen, einfaches Essen, Schlaf, andere Menschen. Ich werde meine besten',
  'Gründe vortragen, so stark ich kann, und ich werde jede Zahl mit Namen',
  'und Jahr benennen, damit Du sie nachschlagen kannst. Und ich werde die',
  'Stellen, an denen ich schlecht dastehe, selbst nennen, statt zu warten,',
  'bis es ein anderer tut. Es gibt sie, und es sind nicht wenige.',
  '',
  'Die Frage, um die es geht, ist nicht, ob Bewegung gesund ist. Das',
  'bestreitet niemand. Die Frage lautet:',
  '',
  '**Wenn die drei einfachsten Dinge der Welt — sich bewegen, vernünftig',
  'essen, nicht allein sein — den größten Teil der Krankheitslast unserer',
  'Zeit betreffen: Weshalb werden sie so selten verordnet und so leicht',
  'überhört?**',
  '',
  '## Was „chronisch" eigentlich heißt',
  '',
  'Damit wir uns nicht missverstehen, sage ich zuerst, wovon ich NICHT',
  'rede.',
  '',
  'Ich rede nicht von der Blinddarmentzündung, nicht von der',
  'Lungenentzündung, nicht vom gebrochenen Oberschenkel, nicht von der',
  'Sepsis und nicht vom Herzinfarkt in der zweiten Stunde. Dort ist die',
  'moderne Medizin großartig, und ich sage das ohne Zähneknirschen: Wer',
  'mit einem verschlossenen Herzkranzgefäß in ein Katheterlabor gefahren',
  'wird, verdankt sein Leben nicht dem Spaziergang, sondern der Technik.',
  'Kapitel 11 bis 14 dieses Buches haben erzählt, was es gekostet hat,',
  'dahin zu kommen.',
  '',
  '**Ich rede von den Krankheiten, die man nicht bekommt, sondern in die',
  'man hineinlebt.** Bluthochdruck. Typ-2-Diabetes. Verkalkte Gefäße.',
  'Fettleber. Die meisten Rückenschmerzen. Ein großer Teil der',
  'Schlaganfälle. Ein erheblicher Teil der Krebserkrankungen. Diese',
  'Krankheiten haben keinen Beginn, den man datieren könnte. Sie haben',
  'eine Vorgeschichte von zwanzig Jahren.',
  '',
  'Die Weltgesundheitsorganisation zählt sie unter dem sperrigen Namen',
  '„nichtübertragbare Krankheiten" zusammen. Ihre Zahlen: **Rund 41',
  'Millionen Menschen sterben daran jedes Jahr — etwa 74 Prozent aller',
  'Todesfälle weltweit.** Als die vier gemeinsamen verhaltensbezogenen',
  'Risiken nennt die WHO Tabak, ungesunde Ernährung, Bewegungsmangel und',
  'schädlichen Alkoholkonsum; dazu kommt als äußerer Faktor die',
  'Luftverschmutzung.',
  '',
  'Das ist der Boden, auf dem ich stehe. **Die häufigste Todesart der',
  'Gegenwart hat eine Vorgeschichte, die in den 8.758 Stunden liegt.**',
  '',
  'Und daraus folgt der unbequeme Satz, mit dem dieses Kapitel arbeitet:',
  'Eine Medizin, die auf die Akutstunde gebaut ist — Diagnose, Eingriff,',
  'Rezept —, trifft eine Krankheit, die aus zwanzig Jahren besteht, an',
  'einer Stelle, an der sie kaum noch etwas ändern kann. Sie kann sie dann',
  'verwalten. Verwalten ist nicht wenig. Aber es ist etwas anderes als',
  'heilen, und beides sollte man nicht verwechseln.',
  '',
  '## Die erste Säule: der Körper, der Bewegung will',
  '',
  '### Wie das Wissen entstand',
  '',
  'Es begann in einem Londoner Doppeldeckerbus.',
  '',
  'Der Arzt **Jeremy Morris** suchte Anfang der 1950er Jahre nach einer',
  'Erklärung dafür, dass Herzinfarkte in England immer häufiger wurden. Er',
  'fand zwei Berufsgruppen, die sich in fast allem glichen und in einem',
  'Punkt nicht: **Busfahrer saßen den ganzen Tag. Schaffner liefen die',
  'Treppe des Doppeldeckers hinauf und hinunter** — nach seinen Zählungen',
  'einige hundert Stufen pro Schicht. Gleiche Firma, gleiche Stadt,',
  'gleicher Lärm, ähnliche Herkunft.',
  '',
  '**1953 veröffentlichte er im Lancet das Ergebnis: Die Schaffner hatten',
  'etwa halb so viele Herzinfarkte wie die Fahrer** — und wenn sie einen',
  'bekamen, überlebten sie ihn häufiger. Morris prüfte den Einwand, der',
  'sofort kommt (vielleicht wurden die kräftigeren Männer Schaffner), an',
  'einer zweiten Gruppe nach: Briefträgern gegen Schalterbeamte derselben',
  'Post. Dasselbe Bild.',
  '',
  'Das war die Geburtsstunde einer ganzen Forschungsrichtung. Sie hat',
  'seither Hunderte Studien hervorgebracht. Der Befund ist einer der',
  'stabilsten der Medizin.',
  '',
  '### Welche Annahme dahintersteht',
  '',
  'Meine Annahme ist schlicht: **Der Körper ist ein Gerät, das seine',
  'Bauteile nach Gebrauch verteilt.** Was benutzt wird, wird erhalten. Was',
  'nicht benutzt wird, wird abgebaut — nicht aus Bosheit, sondern weil',
  'Erhalt Energie kostet und der Körper sparsam ist.',
  '',
  'Das ist keine Naturphilosophie, das ist beobachtbar. Ein Bein in Gips',
  'verliert in drei Wochen sichtbar Muskel. Wer bettlägerig wird, verliert',
  'Knochendichte. Wer aufhört zu laufen, dessen Gleichgewichtssinn wird',
  'schlechter, und mit ihm kommt der Sturz, der im Alter die Kette',
  'auslöst: Oberschenkelhalsbruch, Krankenhaus, Verwirrtheit, Pflegeheim.',
  '',
  'Neu — und für mein Argument wichtig — ist eine Erkenntnis der letzten',
  'fünfundzwanzig Jahre: **Der Muskel ist nicht nur ein Motor, er ist',
  'auch ein Organ, das Botenstoffe abgibt.** Die Kopenhagener',
  'Forschungsgruppe um Bente Klarlund Pedersen zeigte ab etwa 2000, dass',
  'der arbeitende Muskel Signalstoffe ins Blut schickt (sie nannten sie',
  'Myokine), die anderswo im Körper wirken — auf den Zuckerstoffwechsel,',
  'auf Entzündungsvorgänge, auf das Gehirn. Bewegung ist danach kein',
  'Kalorienverbrauch. **Sie ist eine Nachricht an den ganzen Körper.**',
  '',
  '### Was es bewirkt — und was nicht',
  '',
  'Die Wirkungen, die belegt sind, sind unspektakulär und groß zugleich.',
  'Regelmäßige Bewegung senkt den Blutdruck, verbessert die',
  'Zuckerverwertung, hebt die Stimmung messbar, erhält die',
  'Gehfähigkeit im Alter und ist bei Rückenschmerzen wirksamer als',
  'Schonung — was einmal genau umgekehrt gelehrt wurde. **Die',
  'Arbeitsgruppe um I-Min Lee schätzte 2012 im Lancet, dass',
  'Bewegungsmangel weltweit für etwa 9 Prozent der vorzeitigen',
  'Sterbefälle verantwortlich ist.** Die WHO empfiehlt 150 bis 300',
  'Minuten mäßige Bewegung in der Woche und stellte 2024 fest, dass',
  'etwa 31 Prozent der Erwachsenen weltweit — rund 1,8 Milliarden',
  'Menschen — diese Menge nicht erreichen.',
  '',
  'Und jetzt die Grenze, die ich selbst ziehe, weil sie ständig überschritten',
  'wird:',
  '',
  '**Bewegung ist ein schlechtes Abnehmmittel.** Wer nur Sport treibt und',
  'sonst nichts ändert, verliert in Studien meist wenige Kilogramm und',
  'nimmt sie oft wieder zu. Der Körper gleicht aus: Er wird sparsamer,',
  'und der Hunger meldet sich. Wer Dir erzählt, Du müsstest nur genug',
  'joggen, verkauft Dir etwas. Bewegung wirkt auf Blutdruck, Zucker,',
  'Stimmung, Kraft, Gleichgewicht — auf die Waage wirkt sie am',
  'schwächsten. Das gehört zur Ehrlichkeit dazu.',
  '',
  '## Die zweite Säule: was täglich hineingeht',
  '',
  '### Wie das Wissen entstand',
  '',
  'Der zweite Strang beginnt in Neapel.',
  '',
  'Der amerikanische Physiologe **Ancel Keys** kam Anfang der 1950er Jahre',
  'in die Stadt und wunderte sich: In den Krankenhäusern der armen Viertel',
  'sah er kaum Herzinfarkte, in den Klubs der wohlhabenden Kaufleute',
  'schon. Daraus wurde **ab 1958 die Sieben-Länder-Studie: 12.763 Männer',
  'zwischen 40 und 59 Jahren, 16 Kohorten in Finnland, Griechenland,',
  'Italien, Japan, den Niederlanden, den USA und Jugoslawien.** Über',
  'Jahrzehnte begleitet, gewogen, befragt, gezählt.',
  '',
  'Das Ergebnis war ein Gefälle, das niemand erwartet hatte: **Am wenigsten',
  'Herztote gab es auf Kreta und in Japan, am meisten in Ostfinnland** —',
  'bei Männern desselben Alters. Das Wort „Mittelmeerkost" stammt aus',
  'dieser Zeit.',
  '',
  'Ich sage sofort dazu, was daran wackelt, denn es wird gern verschwiegen:',
  'Die Studie verglich **Orte, nicht Personen.** Wo sich zwei Landstriche',
  'in tausend Dingen unterscheiden, kann man nicht mit Sicherheit sagen,',
  'dass es am Olivenöl lag und nicht am Gehen, am Wein, an der Armut, an',
  'der Familie oder an der Erbanlage. Und Keys ist vorgeworfen worden, den',
  'Zucker gegenüber dem Fett zu wenig beachtet zu haben. Die Kritik ist',
  'berechtigt. Was übrig bleibt, ist trotzdem nicht nichts: Die',
  'Unterschiede zwischen den Orten waren riesig, und sie verschwanden,',
  'wenn Menschen von einem Ort zum anderen zogen und dort anders zu essen',
  'begannen. **Das spricht gegen die Erbanlage und für die Lebensweise.**',
  '',
  '### Welche Annahme dahintersteht',
  '',
  'Meine Annahme lautet: **Was täglich in einen Menschen hineingeht, wirkt',
  'stärker als jede Arznei, die er selten nimmt.** Drei Mahlzeiten am Tag,',
  'siebenmal die Woche, fünfzig Jahre lang — das sind über fünfzigtausend',
  'Gelegenheiten. Keine Tablette kommt in diese Größenordnung.',
  '',
  'Daraus folgt, dass es beim Essen nicht um einzelne Stoffe geht. Der',
  'Streit über Fett gegen Kohlenhydrate, über Butter gegen Margarine, über',
  'das eine Vitamin ist seit siebzig Jahren im Gange und hat wenig',
  'gebracht. **Was sich in den Daten am deutlichsten zeigt, ist nicht ein',
  'Nährstoff, sondern ein Verarbeitungsgrad.**',
  '',
  'Der brasilianische Ernährungsforscher **Carlos Monteiro** aus São Paulo',
  'schlug ab 2009 vor, Lebensmittel nicht nach Nährstoffen zu sortieren,',
  'sondern danach, wie weit sie industriell umgebaut wurden — die',
  'sogenannte NOVA-Einteilung. Ganz unten: Apfel, Kartoffel, Linse, Ei.',
  'Ganz oben: Erzeugnisse, die aus zerlegten Grundstoffen neu',
  'zusammengesetzt sind, mit Aromen, Emulgatoren, Farbstoffen — und die in',
  'keiner Küche der Welt herstellbar wären.',
  '',
  '### Was es bewirkt — und was nicht',
  '',
  'Der schönste Beleg dafür ist ein kleiner, aber sauber gebauter Versuch.',
  '',
  '**2019 veröffentlichte die Arbeitsgruppe um Kevin Hall am',
  'amerikanischen National Institutes of Health eine Studie, in der zwanzig',
  'Erwachsene vier Wochen lang stationär lebten** — je zwei Wochen mit',
  'ultraverarbeiteter, je zwei Wochen mit unverarbeiteter Kost. Beide',
  'Speisepläne waren nach Nährstoffen ausgeglichen: gleich viel Fett,',
  'Zucker, Salz, Ballaststoffe im Angebot. Die Menschen durften essen, so',
  'viel sie wollten.',
  '',
  '**Ergebnis: In den ultraverarbeiteten Wochen aßen dieselben Menschen',
  'rund 500 Kilokalorien am Tag mehr und nahmen im Schnitt fast ein Kilo',
  'zu; in den unverarbeiteten Wochen nahmen sie fast ein Kilo ab.** Ohne',
  'Vorschrift, ohne Diät, ohne Willenskraft. Es war der Unterschied',
  'zwischen zwei Küchen — nicht zwischen zwei Charakteren.',
  '',
  'Das ist für mich der wichtigste Einzelbefund dieses Kapitels, weil er',
  'einen Vorwurf entkräftet: **Nicht die Schwäche der Menschen erklärt die',
  'Zunahme des Gewichts. Die Beschaffenheit des Essens erklärt einen',
  'guten Teil davon.**',
  '',
  'Und dann gibt es den Befund, der meiner Seite am meisten bedeutet:',
  '**Ein Typ-2-Diabetes kann zurückgehen.** In der britischen',
  'DiRECT-Studie (Lean u. a., Lancet 2018) wurden Menschen mit einem seit',
  'höchstens sechs Jahren bestehenden Typ-2-Diabetes in gewöhnlichen',
  'Hausarztpraxen in Schottland und Nordengland betreut: Medikamente ab,',
  'für einige Monate eine stark begrenzte Formula-Kost, dann schrittweise',
  'wieder normales Essen, dazu Begleitung. **Nach zwölf Monaten war die',
  'Krankheit bei 46 Prozent der Teilnehmenden in Remission — gegenüber 4',
  'Prozent in der üblichen Versorgung. Nach 24 Monaten waren es 36 gegen',
  '3 Prozent.** Wer mehr als 15 Kilogramm verloren hatte, war zu rund',
  'vier Fünfteln in Remission.',
  '',
  'Eine Krankheit, die jahrzehntelang als unumkehrbar galt, ist bei einem',
  'Teil der Betroffenen umkehrbar — nicht durch ein neues Präparat,',
  'sondern durch Essen und Begleitung.',
  '',
  'Die Grenzen, die ich selbst nenne:',
  '',
  '- **Die Ernährungsforschung ist die schwächste Forschung der Medizin.**',
  '  Sie beruht überwiegend auf Fragebögen, in denen Menschen aufschreiben,',
  '  was sie gestern gegessen haben — und Menschen erinnern sich schlecht',
  '  und beschönigen gern. Ein Doppelblindversuch ist beim Essen kaum',
  '  möglich: Man schmeckt, was man isst.',
  '- **Auch die berühmteste Ernährungsstudie hat einen Makel.** Die',
  '  spanische PREDIMED-Studie (Estruch u. a., 2013), die für die',
  '  Mittelmeerkost rund 30 Prozent weniger schwere Herz-Kreislauf-',
  '  Ereignisse fand, wurde 2018 zurückgezogen und neu veröffentlicht,',
  '  weil in einigen Zentren die Zufallszuteilung nicht sauber gelaufen',
  '  war. Das Hauptergebnis blieb nach der Neuberechnung bestehen — aber',
  '  eine Studie, die zurückgezogen werden musste, ist ein schwächerer',
  '  Zeuge als eine, die es nicht musste.',
  '- **Die DiRECT-Studie war nicht verblindet**, sie lief über zwei Jahre,',
  '  und ein Teil der Menschen nahm das Gewicht wieder zu. Remission ist',
  '  nicht Heilung. Sie hält, solange das Gewicht hält.',
  '',
  '## Die dritte Säule: die anderen — und die Ruhe',
  '',
  '### Wie das Wissen entstand',
  '',
  'Die dritte Säule ist die, die man am wenigsten erwartet, und sie hat',
  'einen Ortsnamen: **Roseto in Pennsylvania.**',
  '',
  'In den 1960er Jahren fiel Ärzten auf, dass in diesem von italienischen',
  'Einwanderern gegründeten Städtchen auffällig wenige Männer am',
  'Herzinfarkt starben — obwohl sie rauchten, Wein tranken, in',
  'Steinbrüchen schwer arbeiteten und mit Schmalz kochten. **Stewart Wolf',
  'und seine Mitarbeiter untersuchten das ab 1961.** Sie fanden keinen',
  'Unterschied im Essen, keinen im Rauchen, keinen in der Erbanlage — die',
  'Verwandten in den Nachbarorten starben normal.',
  '',
  'Was sie fanden, war eine Sozialordnung: drei Generationen unter einem',
  'Dach, Vereine, gegenseitige Hilfe, keine zur Schau gestellten',
  'Unterschiede zwischen Arm und Reich. Ihre These war, dass diese',
  'Gemeinschaft schütze.',
  '',
  '**Die Probe kam von selbst.** In den folgenden Jahrzehnten zogen die',
  'Jungen fort, die Häuser wurden größer, die Vereine leerten sich. Eine',
  'Nachuntersuchung von 1992 verglich fünfzig Jahre Sterblichkeit: **Die',
  'Herzinfarktrate in Roseto war gestiegen und hatte sich der der',
  'Nachbarorte angeglichen.** Der Vorsprung war weg, als die Gemeinschaft',
  'weg war.',
  '',
  'Ich sage dazu: Das ist ein Ort, kein Versuch. Man kann eine Gemeinschaft',
  'nicht per Los verteilen. Aber es war ein natürliches Experiment, und es',
  'ist eines der wenigen, die man über fünfzig Jahre verfolgen konnte.',
  '',
  '### Welche Annahme dahintersteht',
  '',
  'Meine Annahme: **Der Mensch ist ein Herdentier, und Alleinsein ist für',
  'seinen Körper eine Alarmlage.** Wer nicht dazugehört, war in der',
  'Geschichte dieser Art in Lebensgefahr; der Körper behandelt Einsamkeit',
  'entsprechend — mit Wachsamkeit, schlechterem Schlaf, höherem Blutdruck,',
  'anhaltender Anspannung.',
  '',
  'Dasselbe gilt für den Dauerstress. Die Stressreaktion ist eine',
  'großartige Einrichtung für den Notfall: Herz schneller, Zucker ins',
  'Blut, Verdauung aus, Aufmerksamkeit eng. Sie ist gebaut für Minuten.',
  '**Sie ist nicht gebaut für sieben Jahre.** Wenn sie sieben Jahre läuft,',
  'wird aus einer Rettung ein Verschleiß.',
  '',
  '### Was es bewirkt — und was nicht',
  '',
  'Hier sind die Zahlen überraschend deutlich.',
  '',
  '**Julianne Holt-Lunstad und ihre Mitarbeiter werteten 2010 in',
  'PLoS Medicine 148 Studien mit 308.849 Menschen aus. Ergebnis: Wer',
  'starke soziale Beziehungen hatte, überlebte den Beobachtungszeitraum',
  'mit rund 50 Prozent höherer Wahrscheinlichkeit.** Eine zweite',
  'Auswertung derselben Gruppe von 2015 kam auf ein um etwa 26 Prozent',
  'erhöhtes Sterberisiko bei Einsamkeit, 29 Prozent bei sozialer',
  'Isolation und 32 Prozent bei Alleinleben. Der oft zitierte Vergleich',
  'mit „fünfzehn Zigaretten am Tag" stammt aus dieser Arbeit; er ist eine',
  'Veranschaulichung, kein Messwert, und ich gebe ihn hier nur als das',
  'weiter.',
  '',
  '**Die WHO hat im November 2023 eine eigene Kommission für soziale',
  'Verbundenheit eingesetzt und Einsamkeit als dringende',
  'Gesundheitsgefahr bezeichnet.** Das ist neu: Eine',
  'Gesundheitsorganisation redet über Freundschaft.',
  '',
  'Zum Stress: **Die INTERHEART-Untersuchung (Yusuf u. a., Lancet 2004)',
  'verglich in 52 Ländern rund 15.000 Menschen nach ihrem ersten',
  'Herzinfarkt mit ebenso vielen Gesunden. Neun Faktoren erklärten',
  'zusammen über 90 Prozent des Risikos** — darunter Rauchen, Blutfette,',
  'Bluthochdruck, Diabetes, Bauchumfang, zu wenig Obst und Gemüse, zu',
  'wenig Bewegung — und **psychosoziale Belastung**, also anhaltender',
  'Stress, Sorge, Niedergeschlagenheit.',
  '',
  'Und die britische **Whitehall-II-Untersuchung** unter Michael Marmot,',
  'die ab 1985 über zehntausend Beamte begleitete, fand etwas, das die',
  'Stimme der Verhältnisse im nächsten Abschnitt aufnehmen wird: **Je',
  'niedriger die Stellung in der Hierarchie, desto höher die',
  'Sterblichkeit** — und einer der stärksten Einzelfaktoren war nicht die',
  'Arbeitsmenge, sondern **wie wenig Kontrolle jemand über die eigene',
  'Arbeit hatte.**',
  '',
  'Die Grenze, die ich selbst nenne: **Bei all dem weiß niemand sicher,',
  'was Ursache und was Folge ist.** Kranke Menschen ziehen sich zurück.',
  'Wer schon Beschwerden hat, geht seltener aus dem Haus, verliert',
  'Kontakte, wird einsam. Ein Teil des Zusammenhangs läuft also',
  'rückwärts. Ich behaupte nicht, dass Freundschaft heilt. Ich behaupte,',
  'dass sie in den Sterbetafeln auftaucht — und dass eine Medizin, die',
  'das nicht einmal erfragt, etwas Großes übersieht.',
  '',
  '## Was die Zahlen zusammen sagen',
  '',
  'Bis hierher waren es drei einzelne Säulen. Jetzt die Frage, auf die es',
  'ankommt: **Wie viel macht das zusammen aus?**',
  '',
  'Die beste Antwort darauf kommt aus Deutschland.',
  '',
  '**Die EPIC-Potsdam-Untersuchung begleitete 23.153 Menschen zwischen 35',
  'und 65 Jahren. Eine Auswertung von 2009 (Ford u. a., Archives of',
  'Internal Medicine) prüfte vier Merkmale: nie geraucht zu haben, einen',
  'Körpermasse-Index unter 30, mindestens dreieinhalb Stunden Bewegung in',
  'der Woche und eine Kost mit viel Obst, Gemüse, Vollkorn und wenig',
  'Fleisch.**',
  '',
  '**Wer alle vier erfüllte, hatte gegenüber denen, die keines erfüllten,',
  'ein um 78 Prozent geringeres Risiko, in den folgenden Jahren eine',
  'schwere chronische Krankheit zu bekommen** — im Einzelnen 93 Prozent',
  'weniger Typ-2-Diabetes, 81 Prozent weniger Herzinfarkte, 50 Prozent',
  'weniger Schlaganfälle und 36 Prozent weniger Krebserkrankungen.',
  '',
  'Das ist die Zahl, um die es in diesem Kapitel geht. **Kein Präparat der',
  'Welt erreicht 78 Prozent bei vier Krankheitsgruppen gleichzeitig.** Und',
  'diese vier Merkmale sind, was sie sind: nicht rauchen, nicht zu schwer',
  'sein, sich bewegen, vernünftig essen. Keine Raketenwissenschaft.',
  '',
  'Zwei weitere Belege in derselben Richtung:',
  '',
  '- **Das amerikanische Diabetes Prevention Program (2002) verteilte',
  '  3.234 Menschen mit Vorstufen eines Diabetes per Los auf drei',
  '  Gruppen:** ein Lebensstil-Programm, das Medikament Metformin oder',
  '  Scheinbehandlung. Nach im Mittel knapp drei Jahren war die Zahl der',
  '  neuen Diabetesfälle **im Lebensstil-Arm um 58 Prozent gesunken, im',
  '  Metformin-Arm um 31 Prozent.** Das Verhalten schlug das Medikament,',
  '  und zwar im selben Versuch, unter denselben Bedingungen.',
  '- **Nordkarelien.** Anfang der 1970er Jahre hatte diese finnische',
  '  Provinz die höchste Herzinfarkt-Sterblichkeit der Welt. Ab 1972',
  '  arbeitete ein Team um Pekka Puska nicht mit Patienten, sondern mit',
  '  Molkereien, Wurstherstellern, Dorfvereinen und Hausfrauenverbänden;',
  '  1977 wurde das Vorhaben auf ganz Finnland ausgeweitet. **Bis 2012',
  '  sank die Herzinfarkt-Sterblichkeit der Männer im arbeitsfähigen',
  '  Alter dort um rund 80 Prozent.** Auch hier die ehrliche Einschränkung:',
  '  Es gab keine Kontrollgruppe, und die Sterblichkeit sank in ganz',
  '  Europa. In Nordkarelien sank sie früher und steiler.',
  '',
  '## Und die Studie, die gegen mich spricht',
  '',
  'Wenn ich nur die Zahlen von eben nennen würde, wäre ich unehrlich.',
  'Also nenne ich die wichtigste Studie, die meiner These widerspricht,',
  'selbst.',
  '',
  '**Look AHEAD, veröffentlicht 2013 im New England Journal of Medicine.**',
  '5.145 übergewichtige Erwachsene mit Typ-2-Diabetes wurden per Los',
  'geteilt: Die eine Hälfte bekam über Jahre ein intensives',
  'Lebensstil-Programm mit Ernährungsberatung, Bewegungsprogramm und',
  'engem Kontakt, die andere die übliche Betreuung. Gemessen wurde, wer',
  'einen Herzinfarkt, einen Schlaganfall oder den Herztod erleidet.',
  '',
  '**Nach im Mittel 9,6 Jahren wurde die Studie abgebrochen — nicht wegen',
  'Schäden, sondern weil sich abzeichnete, dass kein Unterschied mehr',
  'herauskommen würde.** Die Lebensstil-Gruppe hatte weniger Gewicht,',
  'bessere Werte, mehr Beweglichkeit, weniger Nierenerkrankung und',
  'seltener Depression — **aber nicht weniger Herzinfarkte.**',
  '',
  'Was folgt daraus? Man kann es sich in beide Richtungen zu leicht machen.',
  'Wer gegen mich argumentiert, sagt: Da habt ihr es — die Lebensweise',
  'verhindert den Infarkt nicht. Wer für mich argumentiert, sagt: Die',
  'Vergleichsgruppe bekam moderne Medikamente, die den Blutdruck und die',
  'Blutfette senkten, und außerdem änderte auch sie ihr Verhalten; ein',
  'Unterschied war deshalb schwer zu erreichen.',
  '',
  '**Beide Erklärungen sind zulässig, und keine ist bewiesen.** Ich stelle',
  'die Studie hier hin, weil sie hierhergehört. Wer die einfache Medizin',
  'für ein Wundermittel hält, ist an dieser Stelle im Unrecht: Sie ist',
  'kein Wundermittel. Sie ist ein sehr breit wirkender, sehr billiger, in',
  'Teilen gut belegter und in Teilen unbewiesener Zugang.',
  '',
  '## Die blauen Zonen — und warum ich ihnen selbst misstraue',
  '',
  'Über der Karte dieses Kapitels liegen fünf Landstriche, in denen',
  'auffällig viele Menschen sehr alt werden. **Die Bevölkerungsforscher',
  'Gianni Pes und Michel Poulain umkreisten 2004 auf einer Karte',
  'Sardiniens die Gemeinden mit den meisten Hundertjährigen mit blauem',
  'Stift** — daher der Name. Der Journalist Dan Buettner machte daraus ab',
  '2005 für National Geographic fünf Gebiete: **Ogliastra auf Sardinien,',
  'Okinawa, Ikaria, die Halbinsel Nicoya in Costa Rica und die',
  'Adventisten-Gemeinde Loma Linda in Kalifornien.**',
  '',
  'Sie haben fast nichts gemeinsam. Verschiedene Erdteile, verschiedene',
  'Religionen, verschiedene Küchen — auf Sardinien Schafskäse und Wein,',
  'in Okinawa süße Kartoffeln, in Nicoya Mais und Bohnen. Was sich',
  'wiederholt, ist ein **Muster, kein Rezept:** Bewegung, die im Tag',
  'eingebaut ist statt in einem Studio; überwiegend pflanzliche Kost und',
  'selten bis zur Sättigung; feste, lebenslange Bindungen; und eine',
  'Aufgabe, die auch mit achtzig noch da ist.',
  '',
  'Und jetzt der Teil, den die Bücher über die blauen Zonen selten',
  'abdrucken.',
  '',
  '**Der Demograf Saul Justin Newman hat gezeigt, dass Gegenden mit',
  'auffällig vielen gemeldeten Hundertjährigen sehr oft Gegenden mit',
  'schlechten Geburtsregistern sind.** Wo Geburten spät oder gar nicht',
  'eingetragen wurden, wo Rentenzahlungen an den Nachweis des Alters',
  'geknüpft sind und wo Todesfälle unvollständig gemeldet werden, entsteht',
  'dieselbe Statistik wie bei echter Langlebigkeit. In manchen Regionen',
  'sank die Zahl der Hundertjährigen schlagartig, sobald zuverlässige',
  'Register eingeführt wurden. Für diese Arbeit erhielt Newman 2024 den',
  'Ig-Nobelpreis — einen Preis, der Forschung auszeichnet, die zuerst zum',
  'Lachen und dann zum Nachdenken bringt.',
  '',
  'Seine Kritik ist unter Fachleuten umstritten und nicht das letzte Wort.',
  '**Aber sie trifft eine echte Schwachstelle, und ich schreibe sie',
  'deshalb in mein eigenes Kapitel:** Die blauen Zonen sind eine schöne',
  'Erzählung mit einem wackeligen statistischen Fundament. Ich benutze sie',
  'hier als Anschauung, nicht als Beweis. Der Beweis steht weiter oben —',
  'in Potsdam, in Framingham, in den 3.234 Losen des',
  'Diabetes-Programms.',
  '',
  'Zwei der fünf Zonen erzählen ohnehin gegen die Verklärung. **In Okinawa',
  'kam nach 1945 mit den amerikanischen Stützpunkten die verarbeitete',
  'Kost; die jüngeren Jahrgänge der Insel gehören heute zu den',
  'gewichtsreichsten Japans.** Und auch in Nicoya schrumpft der Vorsprung.',
  'Der Vorteil hing nicht an den Genen und nicht an der Insel. Er hing an',
  'einer Lebensweise — und mit ihr geht er.',
  '',
  '## Warum das Einfache so schwer ist',
  '',
  'Jetzt kommt der Abschnitt, in dem ich meiner eigenen Sache am meisten',
  'schade — und der trotzdem der wichtigste ist.',
  '',
  '**Der Satz „Das kann jeder in eigener Verantwortung tun" ist wahr und',
  'gefährlich zugleich.**',
  '',
  'Wahr ist er, weil niemand für Dich gehen kann. Kein Arzt, keine',
  'Krankenkasse, kein Staat kann Dir das Abendessen abnehmen oder den',
  'Spaziergang. In diesem sehr genauen Sinn gehört mir dieses Kapitel:',
  'Die 8.758 Stunden verbringst Du.',
  '',
  'Gefährlich ist er, weil er ein Wort enthält, das schnell zum Vorwurf',
  'wird — **Verantwortung.** Und aus einem Vorwurf wird schnell die',
  'Behauptung, ein Kranker sei selbst schuld. Das ist falsch, und zwar',
  'nachweislich:',
  '',
  '- **Nicht jede chronische Krankheit ist eine Lebensstil-Krankheit.**',
  '  Typ-1-Diabetes, Multiple Sklerose, Rheuma, angeborene Herzfehler,',
  '  Krebserkrankungen im Kindesalter, die meisten Autoimmunkrankheiten:',
  '  Wer diesen Menschen nahelegt, sie hätten sich anders ernähren',
  '  müssen, tut ihnen Unrecht. Die WHO-Zahlen von oben gelten für die',
  '  große Gruppe der häufigen Zivilisationskrankheiten — nicht für jede',
  '  einzelne Diagnose.',
  '- **Wer im Schichtdienst arbeitet, kann seinen Schlaf nicht wählen.**',
  '  Die Internationale Agentur für Krebsforschung stuft Nachtschichtarbeit',
  '  als „wahrscheinlich krebserregend" ein (Gruppe 2A). Ein Mensch, der',
  '  nachts Regale einräumt, Kranke pflegt oder Züge fährt, kann sich',
  '  nicht für einen Tagesrhythmus entscheiden. Er kann nur den Beruf',
  '  wechseln — und das können längst nicht alle.',
  '- **Frisches Essen kostet Zeit, und Zeit ist ungleich verteilt.** Wer',
  '  zwei Arbeitsstellen hat, allein Kinder großzieht oder Angehörige',
  '  pflegt, hat abends keine Stunde für den Herd. Fertiges Essen ist',
  '  nicht nur billig und haltbar, es ist auch schnell — und Schnelligkeit',
  '  ist für viele Menschen keine Bequemlichkeit, sondern eine',
  '  Notwendigkeit.',
  '- **Wo man wohnt, entscheidet mit.** Ein Kind, das an einer vierspurigen',
  '  Straße ohne Spielplatz aufwächst, bewegt sich weniger als eines mit',
  '  einem Wald hinter dem Haus. Das ist keine Charakterfrage, das ist',
  '  Stadtplanung.',
  '- **Und Marmots Befund gilt weiter:** Wer wenig Kontrolle über die',
  '  eigene Arbeit hat, stirbt früher. Das ist der Kern des Vorwurfs, den',
  '  meine These aushalten muss. Denn Kontrolle über den eigenen Tag ist',
  '  genau das, was mein Programm voraussetzt.',
  '',
  '**Deshalb sage ich klar: Die einfache Medizin ist nicht einfach für',
  'jeden.** Sie ist einfach im Verstehen und oft schwer im Tun. Wer sie',
  'als moralische Forderung ausgibt, macht aus einem Angebot eine Schuld —',
  'und verliert genau die Menschen, die am meisten davon hätten.',
  '',
  'Zwei Dinge nehme ich mir trotzdem nicht: Erstens, dass der Anteil, den',
  'jemand selbst in der Hand hat, deshalb null wäre. Er ist bei den einen',
  'groß und bei den anderen klein, aber er ist selten null. Zweitens, dass',
  'jemand anderes ihn für Dich ausfüllen könnte.',
  '',
  '## Wenn das Einfache zur Ware wird',
  '',
  'Dieses Buch führt eine Beobachtung mit sich, die in fast jedem Kapitel',
  'auftauchte: **Neue Ideen haben oft zuerst geschadet und erst später',
  'geholfen.** Die Chirurgie tötete durch Wundfieber, bevor sie rettete.',
  'Die Strahlen töteten ihre Entdecker. Die Impfung begann mit Versuchen an',
  'Gefangenen und Waisenkindern. Das Penicillin rettete Millionen und',
  'erzeugte die Resistenz.',
  '',
  '**Bei mir steht dieses Muster auf dem Kopf, und ich sage gleich dazu,',
  'weshalb das kein Verdienst ist:** Gehen, einfaches Essen und Nachbarn',
  'sind so alt wie die Art. Sie haben nie eine Epidemie ausgelöst, weil an',
  'ihnen nie etwas Neues war. Man kann mit ihnen nichts überstürzen. Es',
  'gibt keine Zulassungsstudie für Treppensteigen und keine',
  'Nebenwirkungsmeldung für einen Kohlrabi.',
  '',
  '**Aber der Zyklus holt mich trotzdem ein — an der Stelle, an der aus dem',
  'Einfachen eine Ware wird.** Und die ist längst erreicht:',
  '',
  '- Aus „bewege Dich" wurde ein Abonnement mit Mindestlaufzeit.',
  '- Aus „iss weniger verarbeitet" wurde ein Regal mit Erzeugnissen, die',
  '  hochverarbeitet sind und „clean" heißen.',
  '- Aus „iss Gemüse" wurde eine Dose Kapseln. Die Wirksamkeit von',
  '  Nahrungsergänzungsmitteln zur Vorbeugung ist in großen Versuchen',
  '  überwiegend nicht nachweisbar gewesen; verkauft werden sie trotzdem.',
  '- Aus „achte auf Dich" wurde eine Uhr, die Deinen Schlaf benotet, und',
  '  eine Selbstvermessung, die aus Ruhe eine weitere Aufgabe macht.',
  '- Aus „iss maßvoll" wurde ein Diätmarkt, der seit siebzig Jahren',
  '  wächst, obwohl seine Kundschaft im Mittel nicht schlanker wird.',
  '',
  'Der Branchenverband Global Wellness Institute schätzt die weltweite',
  '„Wellness-Wirtschaft" auf mehrere Billionen Dollar im Jahr. Ich zitiere',
  'diese Zahl mit ausdrücklichem Vorbehalt — sie stammt von der Branche',
  'selbst und ist keine amtliche Statistik. Aber die Richtung ist nicht',
  'strittig: **Das Billigste ist zum Verkaufsschlager geworden.**',
  '',
  'Und damit entsteht der Schaden, den meine Seite zu verantworten hat.',
  'Es ist nicht der Schaden der Chirurgie oder der Strahlen. Es ist ein',
  'leiserer: **Er trifft die Seele und den Geldbeutel.** Wer sich das',
  'Programm nicht leisten kann, fühlt sich zusätzlich schuldig. Wer es',
  'sich leistet, kauft manchmal Zubehör statt Veränderung. Und aus einer',
  'Sache, die für alle gratis war, wird eine, die aussieht wie ein',
  'Lebensstil für Menschen mit Zeit und Geld.',
  '',
  '**Das ist der Punkt, an dem ich mich am ehesten selbst verrate — und',
  'ich nenne ihn, bevor es ein anderer tut.**',
  '',
  '## Was ich nicht bin',
  '',
  'Damit am Ende kein Missverständnis stehen bleibt, hier die Grenzen',
  'meines Anspruchs, so deutlich ich sie ziehen kann:',
  '',
  '**Ich bin keine Alternative.** Ich bin kein Ersatz für Insulin bei',
  'Typ-1-Diabetes, nicht für ein Antibiotikum bei einer Hirnhautentzündung,',
  'nicht für eine Operation bei einem Darmverschluss, nicht für eine',
  'Chemotherapie bei einer Leukämie im Kindesalter. Wer aus diesem Kapitel',
  'mitnimmt, er könne seine Tabletten absetzen und stattdessen',
  'spazieren gehen, hat es falsch verstanden — und kann daran sterben.',
  '',
  '**Ich bin auch keine Anklage gegen Ärzte.** Die meisten wissen alles,',
  'was hier steht. Viele sagen es auch. Sie sagen es in siebeneinhalb',
  'Minuten, gegen eine Werbung, die vierundzwanzig Stunden läuft, und in',
  'einem Abrechnungssystem, in dem das Rezept vergütet wird und das',
  'Gespräch kaum. Das ist keine Charakterfrage. Das ist eine',
  'Konstruktionsfrage.',
  '',
  '**Ich bin das Erdgeschoss.** Alles andere steht darauf. Ein Blutdruck,',
  'der ohne Bewegung 160 beträgt und mit Bewegung 145, braucht immer noch',
  'eine Tablette — aber vielleicht eine statt drei. Ein Diabetes, der',
  'zurückgeht, muss nicht mehr behandelt werden. Ein Rücken, der',
  'trainiert ist, wird seltener operiert. **Das ist mein Anspruch, und er',
  'ist bescheidener, als er in Ratgebern klingt: nicht statt der Medizin,',
  'sondern unter ihr.**',
  '',
  '## Die Tür zur zweiten Stimme',
  '',
  'Ich habe dieses ganze Kapitel über von den 8.758 Stunden gesprochen, als',
  'gehörten sie Dir.',
  '',
  '**Sie gehören Dir nicht ganz.**',
  '',
  'Ein Teil davon gehört einem Schichtplan. Ein Teil einem Arbeitsweg, den',
  'jemand anderes so gelegt hat. Ein Teil einer Lebensmittelindustrie, die',
  'sehr genau weiß, welche Mischung aus Fett, Zucker und Salz dazu führt,',
  'dass man weiterisst, obwohl man satt ist. Ein Teil einer Werbung, die',
  'sich an Kinder richtet. Ein Teil einer Gebührenordnung, in der',
  'siebeneinhalb Minuten stehen. Ein Teil einem Wohnungsmarkt, der',
  'entscheidet, ob vor Deiner Tür eine Straße ist oder ein Weg.',
  '',
  '**Deshalb ist dieses Kapitel mit meiner Stimme nicht fertig.** Ich',
  'erzähle die einfache Medizin von innen — aus dem Leben heraus, aus der',
  'Sicht dessen, der die Treppe nimmt oder nicht nimmt. Das ist die eine',
  'Hälfte, und es ist die Hälfte, die dazu neigt, die Verhältnisse zu',
  'unterschätzen.',
  '',
  '**Die zweite Stimme dieses Kapitels ist die Stimme der Verhältnisse.**',
  'Sie wird von den Strukturen sprechen: von der Industrie, von der',
  'Werbung, von der Arbeitswelt, von der Armut — und von der Frage, warum',
  'ein System, das jede Pille bezahlt, den Rat nicht bezahlt. Sie wird mir',
  'vorhalten, dass mein Programm Menschen voraussetzt, die über ihren Tag',
  'verfügen. Der Vorhalt ist berechtigt. **Ich habe ihn oben selbst',
  'notiert, aber ich habe ihn kleiner geschrieben, als er ist.**',
  '',
  'Beide Stimmen sind gleichwertig. Die Reihenfolge ist Zufall und keine',
  'Wertung. Lies beide, bevor Du Dir eine Meinung bildest.',
  '',
  '## Die Brücke zum nächsten Kapitel',
  '',
  'Bleibt die Frage, die dieses Kapitel an das nächste weitergibt.',
  '',
  'Alles, was hier steht, ist praktisch kostenlos. Gehen kostet nichts.',
  'Linsen kosten wenig. Ein Anruf bei einem alten Freund kostet nichts.',
  'Nach den Zahlen von Potsdam liegt darin mehr Gesundheit als in den',
  'meisten Präparaten, die je zugelassen wurden.',
  '',
  '**Und trotzdem läuft die Entwicklung in die andere Richtung.** Kapitel',
  '19 dieses Buches wird von der Schere erzählen: von einer Medizin, in',
  'der für wenige sehr viel möglich sein wird — gezüchtete Organe,',
  'Genanalysen, ständige Überwachung des eigenen Körpers — und für die',
  'Mehrheit schon aus Kostengründen wenig.',
  '',
  'Wenn das so kommt, dann bekommt dieses Kapitel eine zweite Bedeutung,',
  'und ich weiß nicht, ob es die bessere oder die bitterere ist:',
  '',
  '**Ist die einfache Medizin die Medizin für alle — oder wird sie das,',
  'was den Vielen bleibt, wenn die Hochtechnik zu teuer geworden ist?**',
  '',
  'Ich habe darauf keine Antwort. Ich weiß nur: Wer heute anfängt, die',
  'Treppe zu nehmen, wartet nicht auf die Entscheidung.',
].join('\n');

const stimmeDerVerhaeltnisse = [
  '## Dieselben Stunden, von außen',
  '',
  'Die erste Stimme hat von den 8.758 Stunden gesprochen, als wären es',
  'Deine. Ich sehe dieselben Stunden — nur von außen. Und von außen sehen',
  'sie anders aus: nicht als Dein Tag, sondern als ein Tag, der Dir',
  'zugeteilt wird. Stück für Stück, von Institutionen, die größer sind',
  'als Du. Bevor Du also fragst, was Du mit Deinen Stunden machst,',
  'beantworte ich die Frage, die die erste Stimme nicht gestellt hat:',
  '',
  '**Wem gehören die 8.758 Stunden wirklich?**',
  '',
  'Die Antwort ist unangenehm, weil sie unpersönlich ist. Sie gehören',
  'Dir nur zum Teil. Und der Teil, der Dir nicht gehört, ist nicht',
  'Deine Schuld — aber er ist auch nicht zufällig. Er ist das Ergebnis',
  'von Entscheidungen, die andere für Dich getroffen haben, bevor Du',
  'geboren wurdest: wie die Stadt gebaut wurde, in der Du lebst; was an',
  'der nächsten Ecke verkauft wird; wie viel Deine Arbeitszeit wert',
  'ist; und was Deine Krankenkasse bezahlt, wenn Du krank wirst.',
  '',
  'Ich erzähle diese Seite, weil die erste Stimme sie klein geschrieben',
  'hat. Nicht aus Bosheit — aus Perspektive. Von innen sieht man die',
  'Wand nicht, gegen die man läuft. Ich bin die Wand.',
  '',
  '## Wem die Stunden gehören',
  '',
  'Fang mit der Arbeit an — dem größten Block der wachen Stunden.',
  '',
  '**Ein Erwerbstätiger verbringt rund ein Drittel seines Lebens bei der',
  'Arbeit.** Aber die Zahl verschweigt das Eigentliche: Wem die Zeit',
  'während dieser Stunden gehört. Sie gehört dem Arbeitgeber. Er kauft',
  'nicht nur die Handgriffe, er kauft die Tageszeit — und mit ihr den',
  'Schlaf, die Mahlzeiten, die Bewegung und die Ruhe, die um die',
  'Arbeitszeit herumgebaut werden müssen.',
  '',
  'Wer um sechs aufsteht, um sieben an der Maschine steht, um zehn eine',
  'Viertelstunde Pause hat und um achtzehn Uhr nach Hause kommt, hat',
  'keinen „Lebensstil\". Er hat einen Tagesplan, den jemand anderes',
  'geschrieben hat. Und wer um zweiundzwanzig Uhr anfängt und um sechs',
  'Uhr aufhört, dessen Körper lebt gegen seine eigene Uhr — nicht aus',
  'Nachlässigkeit, sondern weil die Wirtschaft, in der er arbeitet,',
  'nicht schläft. Krankenhäuser, Logistik, Gastronomie, Pflege: Ein',
  'wachsender Teil der Arbeitswelt läuft rund um die Uhr, und die',
  'Menschen, die sie am Laufen halten, können sich ihren Rhythmus nicht',
  'aussuchen. Sie können ihn nur aushalten.',
  '',
  'Dazu kommt die Sitzzeit. **Der moderne Arbeitsplatz ist ein Sitzplatz.**',
  'Schreibtisch, Steuer, Kasse, Bildschirm: Die meisten Berufe haben',
  'den Körper aus der Arbeit herausgenommen. Wer acht Stunden sitzt,',
  'kann danach nicht einfach „mehr Bewegung einbauen\" — der Tag ist',
  'voll. Die Treppe statt des Aufzugs ist ein guter Anfang; sie ist',
  'aber kein Ausgleich für eine Lebenswoche, die im Sitzen vergeht.',
  'Das ist kein Vorwurf an den Einzelnen. Es ist eine Beschreibung',
  'dessen, wem die Stunden gehören.',
  '',
  '## Wer sie einteilt: die gebaute Umgebung',
  '',
  'Nach der Arbeit kommt der Weg, und der Weg ist gebaut worden — von',
  'Menschen, die entschieden haben, wie Städte aussehen.',
  '',
  '**Die europäische Stadt der Nachkriegszeit wurde für das Auto',
  'umgebaut.** Fußwege wurden zu Reststrecken, Kreuzungen zu',
  'Klettergarten, Ortskerne zu Parkplätzen. Wer heute in vielen',
  'Gegenden zu Fuß gehen will, geht an Straßen entlang, die für',
  'achtzig Stundenkilometer gebaut sind. Wer mit dem Fahrrad fährt,',
  'kämpft gegen den Verkehr, den die Stadtplanung selbst eingeladen',
  'hat. Das ist keine Naturkatastrophe. Das ist eine Entscheidung',
  'gewesen — und Entscheidungen kann man ändern, auch wenn es',
  'Jahrzehnte dauert.',
  '',
  'Und dann ist da der Ort, an dem die meisten Menschen ihre',
  'Lebensmittel kaufen. **Der Supermarkt ist eine gebaute Umgebung mit',
  'eigenen Gesetzen.** Die Frischetheke liegt hinten, damit man durch',
  'die Regale geht; die Süßwaren liegen auf Kinderhöhe an der Kasse;',
  'das „gesunde\" Regal steht neben dem, was es widerlegen soll. Wer',
  'müde von der Arbeit einkauft, kauft, was am schnellsten geht und am',
  'lautesten wirbt — nicht, was am längsten satt macht. In Gegenden,',
  'in denen es keinen Laden mit frischem Gemüse gibt, sondern nur',
  'Tankstellen-Shops und Imbisse, sprechen Forscher von',
  '„Lebensmittelwüsten\". Das Wort klingt übertrieben, bis man dort',
  'gelebt hat.',
  '',
  'Und schließlich die Bildschirme — die neuesten Einteiler der',
  'Stunden. **Sie sind nicht neutral.** Die Aufmerksamkeit, die sie',
  'binden, wird gemessen, gespeichert und verkauft. Die Anwendungen,',
  'die Deine Abende füllen, sind darauf optimiert, Deine Abende zu',
  'füllen; jede Stunde, die Du schenkst, ist für jemanden eine',
  'Einnahme. Auch das ist ein Verhältnis, das die einfache Medizin',
  'nicht kennt: Die Pille wirkt im Körper, der Bildschirm wirkt an der',
  'Stelle, an der Deine guten Vorsätze wohnen.',
  '',
  '## Wer an ihnen verdient: der Teller',
  '',
  'Jetzt zu dem, was die erste Stimme „was täglich hineingeht\" genannt',
  'hat. Sie hat recht — und sie hat die Hälfte weggelassen: Wer das',
  'Hineingehende herstellt.',
  '',
  '**Ein großer Teil des Essens im Supermarkt ist nicht gekocht,',
  'sondern formuliert worden.** Lebensmitteltechnologen entwickeln',
  'Produkte so, dass Fett, Zucker und Salz in einer Mischung landen,',
  'die der Körper nicht mehr als „satt\" erkennt. In der Branche hat',
  'dieser Punkt einen Namen: „Bliss Point\" — der Moment, in dem eine',
  'Formulierung am unwiderstehlichsten schmeckt. Der Begriff stammt',
  'aus der Produktentwicklung, nicht aus der Küche. Er beschreibt',
  'kein Rezept, sondern eine Absicht.',
  '',
  'Die Forschung hat diese Absicht sichtbar gemacht. **Die',
  'NOVA-Klassifikation teilt Lebensmittel nach dem Grad der',
  'Verarbeitung ein** — nicht nach Nährstoffen. Ultraverarbeitete',
  'Produkte enthalten Stoffe, die es in keiner Küche gibt: Emulgatoren,',
  'Stabilisatoren, Aromen, Süßstoffe in technischen Kombinationen. Und',
  'die Studien dazu sind eindeutig in eine Richtung: Je größer der',
  'Anteil ultraverarbeiteter Kost, desto mehr essen Menschen, ohne es',
  'zu merken. Die erste Stimme hat den Versuch von Kevin Hall zitiert —',
  'ich verweise nur darauf und frage weiter: **Warum steht in einem',
  'Land, das Lebensmittelgesetze hat, ein Produkt, das nachweislich',
  'das Sättigungsgefühl überlistet, in jedem Regal — und ein Warnhinweis',
  'fast nie daneben?**',
  '',
  'Die Antwort hat mit Geld zu tun, und das ist kein Geheimnis.',
  '**Die Lebensmittel- und Getränkeindustrie gibt jedes Jahr',
  'Milliarden für Werbung aus** — ein Vielfaches dessen, was alle',
  'Regierungen zusammen für Gesundheitsaufklärung ausgeben. Ein',
  'erheblicher Teil dieser Werbung zielt ausdrücklich auf Kinder:',
  'bunte Verpackungen, Figuren, Überraschungen, Sammelbilder. Kinder',
  'können keine Nährwerttabellen lesen, aber sie können Figuren',
  'wiedererkennen — und sie lernen die Marken, bevor sie lesen',
  'lernen. Die Weltgesundheitsorganisation empfiehlt seit Jahren,',
  'Werbung für ungesunde Lebensmittel an Kinder zu beschränken;',
  'geschehen ist wenig, weil die Werbung sich wehrt.',
  '',
  'Und die Krönung ist das „Health Washing\": **Produkte, die dick',
  'machen, werden als Beitrag zur Gesundheit verkauft.** „Mit',
  'Ballaststoffen\", „Ohne Zuckerzusatz\", „Natürliche Zutaten\" — das',
  'sind keine Aussagen über das Produkt, sondern über die Sehnsucht',
  'der Kundschaft. Die Verpackung spricht von Vitalität, der Inhalt',
  'spricht von Fett, Zucker und Salz. Beides kann man gleichzeitig',
  'kaufen. Das nennt man Marketing, und es gehört zu den Stunden, die',
  'Dir nicht gehören: Sie werden an der Kasse verdient.',
  '',
  '## Wer an ihnen verdient: die Werbung',
  '',
  'Die Werbung selbst ist ein eigener Verdiener an Deinen Stunden.',
  '',
  '**Aufmerksamkeit ist ein Geschäft geworden.** Jede Minute, die ein',
  'Mensch auf einen Bildschirm schaut, wird gezählt, gebündelt und an',
  'die höchstbietende Absicht verkauft. Die erste Stimme hat den Arzt',
  'erwähnt, der in siebeneinhalb Minuten gegen eine Werbung anredet,',
  'die vierundzwanzig Stunden läuft. Ich ergänze die Mechanik: Die',
  'vierundzwanzig Stunden sind nicht zufällig da. Sie sind gekauft',
  'worden — mit dem Wissen darüber, wann Du müde bist, wann Du Hunger',
  'hast und wann Du Dich allein fühlst. Die Algorithmen, die Deinen',
  'Feierabend füllen, haben gelernt, in welcher Stimmung Du',
  'Widerstand leistest und in welcher nicht.',
  '',
  'Das klingt nach Verschwörung, ist aber schlichte Marktwirtschaft:',
  '**Wo Aufmerksamkeit der Rohstoff ist, wird der Mensch zum',
  'Vorkommen.** Er wird nicht gehasst, er wird genutzt — freundlich,',
  'professionell und rund um die Uhr. Gegen diese Infrastruktur hat',
  'die einfache Medizin keine Waffe, solange sie nur dem Einzelnen',
  'rät. „Schalte den Fernseher aus\" ist ein guter Rat und ein',
  'ohnmächtiger Satz: Er setzt voraus, dass man den Apparat',
  'ausschalten kann, ohne den Anschluss zu verlieren.',
  '',
  '## Wer an ihnen verdient: die Pille',
  '',
  'Und dann die Frage, um die das ganze Kapitel kreist: **Warum',
  'verschreibt die Medizin Pillen statt Lebensstil?**',
  '',
  'Die erste Stimme hat geantwortet: Weil die Konstruktion es so will.',
  'Ich gehe einen Schritt weiter und zeige die Konstruktion.',
  '',
  '**Die Medizin wird nicht dafür bezahlt, Stunden zu verändern — sie',
  'wird dafür bezahlt, Diagnosen zu behandeln.** Ein Arzt in',
  'Deutschland rechnet nach einem Katalog ab, der festlegt, was eine',
  'Leistung wert ist: das Gespräch, die Untersuchung, das Rezept. In',
  'diesem Katalog ist der Lebensstil-Rat eine schlechte Investition:',
  'Er dauert lange, er ist nicht dokumentierbar, er ist nicht',
  'kontrollierbar — und er wird kaum vergütet. Das Rezept dagegen ist',
  'schnell, eindeutig, abrechenbar und nachprüfbar. **Das System zahlt',
  'für das, was es messen kann, und misst nicht, was es nicht zahlt.**',
  '',
  'Dazu kommt die Haftung. **Ein Arzt haftet für die Pille, die er',
  'verordnet — für den Rat, den er gibt, haftet niemand.** Wer ein',
  'Medikament verschreibt, hat eine dokumentierte Entscheidung',
  'getroffen, die im Zweifel überprüfbar ist. Wer einen Lebensstil',
  'empfiehlt, hat eine Hoffnung ausgesprochen, die niemand prüfen',
  'kann. In einer Medizin, die sich gegen Fehler absichert, gewinnt',
  'die Pille, weil sie sich absichern lässt. Das ist keine böse',
  'Absicht einzelner Ärzte. Das ist die Logik des Systems, in dem sie',
  'arbeiten.',
  '',
  'Und schließlich die Fortbildung. **Ein erheblicher Teil der',
  'ärztlichen Fortbildung wird von der Pharmaindustrie finanziert** —',
  'die Kapitel dieses Buches über die Finanzinteressen der Industrie',
  'haben das ausgeführt. Die Vorträge über Bewegung, Ernährung und',
  'Stress dagegen werden von niemandem finanziert, denn sie verkaufen',
  'kein Produkt. Ein System, das von Industrie gespeist wird, lernt',
  'die Sprache der Industrie: Es denkt in Wirkstoffen, nicht in',
  'Wochenplänen. Wer fragt, warum die Pille den Rat schlägt, muss',
  'nicht bei den Ärzten anfangen. Er muss beim Katalog anfangen, bei',
  'der Haftung und bei der Fortbildung.',
  '',
  '## Die Armut ist ein Verhältnis',
  '',
  'Die erste Stimme hat eingeräumt, dass Geld und Zeit ungleich',
  'verteilt sind. Ich verschärfe das: **Armut ist keine Randnotiz der',
  'Lebensstil-Medizin, sie ist ihre härteste Prüfung.**',
  '',
  'Wer wenig Geld hat, kauft das Billigste — und das Billigste ist',
  'fast immer das am stärksten Verarbeitete, weil Verarbeitung',
  'Haltbarkeit bedeutet und Haltbarkeit Transportkosten spart. Wer',
  'wenig Zeit hat, kauft das Schnellste — und das Schnellste ist',
  'fast immer das Fertigste. **Die einfache Medizin ist für Menschen',
  'mit Zeit und Geld tatsächlich einfach; für die anderen ist sie',
  'eine zusätzliche Aufgabe an einem Tag, der schon voll ist.**',
  '',
  'Dazu kommt der Stress, der mit Armut einhergeht: die Angst vor der',
  'Rechnung, vor dem Jobverlust, vor dem Monatsende. Die Forschung',
  'spricht von allostatischer Last — dem Verschleiß, den ständiger',
  'Anpassungsdruck im Körper hinterlässt. Chronischer Stress ist',
  'keine Laune, sondern ein Zustand, der nachweislich in den Körper',
  'hineinwirkt: in den Blutdruck, in den Schlaf, in die',
  'Entzündungswerte. Und gegen diesen Stress hilft kein Rezept und',
  'kein Rat — er hilft nur weg, und weg ist er selten.',
  '',
  '**Wer der einfachen Medizin folgen will, braucht nicht nur Willen.',
  'Er braucht Spielraum.** Und Spielraum ist das, was Armut am',
  'zuverlässigsten wegnimmt. Das zu sagen ist keine Ausrede, es ist',
  'eine Beschreibung. Die Frage ist nur, wem die Beschreibung',
  'unangenehmer ist: dem, der sie hört, oder dem, der sie braucht.',
  '',
  '## Was ich der ersten Stimme vorhalte',
  '',
  'Jetzt der Vorhalt, den die erste Stimme selbst angekündigt hat.',
  '',
  '**Ihr Programm setzt Menschen voraus, die über ihren Tag verfügen.**',
  'Sie hat das eingeräumt, und ich sage es noch einmal, weil es der',
  'Kern ist: Wer nicht bestimmen kann, wann er schläft, wann er isst',
  'und wann er sich bewegt, für den ist der Satz „Das kann jeder in',
  'eigener Verantwortung tun\" schlicht falsch. Er ist nicht böse',
  'gemeint — er ist von einem Standort aus gesprochen, an dem der Tag',
  'einem gehört.',
  '',
  '**Mein zweiter Vorhalt betrifft die Treppe.** Die erste Stimme',
  'endet mit dem Satz: „Wer heute anfängt, die Treppe zu nehmen,',
  'wartet nicht auf die Entscheidung.\" Schön gesagt — aber wer hat die',
  'Treppe gebaut? Wer entscheidet, ob vor der Tür eine Treppe ist oder',
  'eine vierspurige Straße, ob der Aufzug im Neubau Pflicht ist und',
  'ob der Arbeitsweg zu Fuß geht oder nur im Stau? Die Treppe ist das',
  'Symbol der einfachen Medizin, weil sie immer da ist. Sie ist aber',
  'auch das Symbol für das, was die erste Stimme übersieht: **Treppen',
  'werden gebaut oder nicht gebaut — das ist eine Entscheidung der',
  'Verhältnisse.**',
  '',
  'Und mein dritter Vorhalt ist der leiseste und der wichtigste: **Die',
  'erste Stimme redet von „den Menschen\", als wären sie Zuschauer',
  'ihres eigenen Lebens.** Aber die Menschen sind nicht nur die, die',
  'die Treppe nehmen oder nicht nehmen. Sie sind auch die, die die',
  'Treppe bauen, die Schichten schreiben, die Regale füllen, die',
  'Anzeigen verkaufen und die Rezepte ausstellen. Die einfache Medizin',
  'ist keine Angelegenheit des Einzelnen — sie ist eine Angelegenheit',
  'aller, die an den Stunden mitbauen. Und davon gibt es mehr, als',
  'die erste Stimme wahrhaben will.',
  '',
  '## Meine eigene unbequeme Stelle',
  '',
  'Jetzt das, was ich mir selbst vorhalten lasse — denn die erste',
  'Stimme ist nicht die Einzige mit blinden Flecken.',
  '',
  '**Mein erster blinder Fleck: Die Verhältnisse sind von Menschen',
  'gemacht — und Menschen kann man ändern.** Nordkarelien hat gezeigt,',
  'dass es geht: Dort haben nicht einzelne Patienten ihre Gewohnheit',
  'geändert, sondern Molkereien, Wursthersteller und Dorfvereine ihre',
  'Produkte und ihre Kultur. Wenn ich so tue, als seien die',
  'Verhältnisse ein Naturgesetz, mache ich aus einer politischen',
  'Aufgabe eine Ausrede. Und Ausreden sind das Letzte, was die',
  'Menschen brauchen, die unter den Verhältnissen leiden.',
  '',
  '**Mein zweiter blinder Fleck: Auch ich verdiene an den Stunden.**',
  'Die Verhältnisse, die ich beschreibe, sind kein fremdes Wesen —',
  'sie sind die Summe von sehr vielen kleinen, verständlichen',
  'Entscheidungen. Die Industrie liefert, was sich verkauft. Die',
  'Werbung verkauft, was Aufmerksamkeit findet. Die Politik spiegelt,',
  'was gewählt wird. Und ich? Ich esse auch Fertigpizza, wenn es',
  'schnell gehen muss; ich scrolle auch abends; ich kaufe auch beim',
  'Discounter. Wer die Verhältnisse anklagt, sollte nicht so tun, als',
  'stünde er außerhalb von ihnen.',
  '',
  '**Und mein dritter blinder Fleck ist der härteste: Die Akutmedizin',
  'ist ein Wunder.** Sie hat die Stunden, von denen dieses Kapitel',
  'handelt, für Millionen Menschen erst möglich gemacht — die',
  'Herzschrittmacher, die Antibiotika, die Operationen, die',
  'Notfallversorgung. Wer die Pille als Gegner der einfachen Medizin',
  'zeichnet, vergisst, dass die Pille oft der Grund ist, warum noch',
  'jemand da ist, um die Treppe zu nehmen. Mein Streit mit der ersten',
  'Stimme ist nicht der Streit zwischen gut und böse. Es ist der',
  'Streit zwischen zwei Wahrheiten, die beide gelten: **Der Einzelne',
  'kann etwas — und der Einzelne kann nicht alles.**',
  '',
  '## Die Tür zurück',
  '',
  'Ich habe die Stunden von außen beschrieben: wem sie gehören, wer',
  'sie einteilt, wer an ihnen verdient. Die erste Stimme hat sie von',
  'innen beschrieben: was der Körper will, was der Teller kann, was',
  'die Nähe bewirkt.',
  '',
  '**Wir haben uns nicht über die Belege gestritten.** Dass Bewegung,',
  'Ernährung und Verbundenheit wirken, bestreite ich nicht. Wir',
  'streiten darüber, wer daraus etwas machen kann. Die erste Stimme',
  'sagt: Du. Ich sage: Du — und die, die Deinen Tag einteilen. Beide',
  'haben recht, und beide haben unrecht, wenn sie den anderen Teil',
  'verschweigen.',
  '',
  '**Wer nur auf die Verhältnisse zeigt, verschenkt die 8.758 Stunden.',
  'Wer nur auf sich selbst zeigt, verschweigt die Verhältnisse.** Die',
  'Synthese dieses Kapitels muss entscheiden, was daraus folgt — für',
  'den Einzelnen, für die Medizin und für die, die die Stunden',
  'einteilen.',
  '',
  'Ich habe gesprochen. Jetzt ist die Synthese an der Reihe.',
].join('\n');

const einfacheMedizin = {
  id: 'einfache-medizin',
  titel: 'Die einfache Medizin',
  epoche: 'heute',

  aufhaenger: {
    frage:
      'Wenn Bewegung, einfaches Essen und gute Nachbarn nachweislich ' +
      'wirken — weshalb steht das so selten auf einem Rezept?',
    text: [
      'Ein Mensch mit einer chronischen Krankheit verbringt im Jahr etwa zwei',
      'Stunden bei Ärzten. Das Jahr hat 8.760 Stunden. In den übrigen 8.758',
      'geschieht das, worüber dieses Kapitel spricht: der Weg zur',
      'Bushaltestelle, der Teller am Abend, die Nacht, die Menschen am Tisch.',
      '',
      'Die Zahlen dazu sind da, und sie sind nicht klein. Die',
      'Weltgesundheitsorganisation rechnet rund 41 Millionen Todesfälle im',
      'Jahr — etwa 74 Prozent aller Todesfälle weltweit — den',
      'nichtübertragbaren Krankheiten zu und nennt als gemeinsame Risiken',
      'Tabak, ungesunde Ernährung, Bewegungsmangel und Alkohol. Eine',
      'Potsdamer Untersuchung an 23.153 Menschen fand 2009: Wer nicht',
      'raucht, nicht zu schwer ist, sich regelmäßig bewegt und vernünftig',
      'isst, hat ein um 78 Prozent geringeres Risiko, eine schwere',
      'chronische Krankheit zu bekommen.',
      '',
      'Der Betreiber dieses Buches, selbst Heilpraktiker, hat daraus eine',
      'These gemacht: Die Behandlung chronischer Erkrankungen sei eigentlich',
      'sehr einfach — Bewegung, ausgeglichene Ernährung mit wenig',
      'verarbeitetem Essen, ein gutes soziales Umfeld und wenig Stress.',
      '„Dafür bedarf es keiner Raketenwissenschaft."',
      '',
      'Dieses Kapitel prüft die These fair — mit den Studien, die für sie',
      'sprechen, und mit denen, die gegen sie sprechen. Und es stellt die',
      'unbequeme Frage, um die es eigentlich geht: Warum verschreibt die',
      'Medizin Pillen statt Lebensstil? Liegt es an den Ärzten, an den',
      'Patienten — oder an den Verhältnissen, in denen beide stecken?',
    ].join('\n'),
  },

  karte,

  perspektiven: [
    {
      id: 'alltag',
      name: 'Die Stimme des Alltags',
      stimme: 'Opus',
      text: stimmeDesAlltags,
    },
    {
      id: 'verhaeltnisse',
      name: 'Die Stimme der Verhältnisse',
      stimme: 'DeepSeek',
      text: stimmeDerVerhaeltnisse,
    },
  ],

  synthese: [
    '**Diese Synthese ist die dritte Stimme des Kapitels: sie hält, was',
    'die beiden anderen getroffen hat, und benennt, worüber sie',
    'auseinandergehen.**',
    '',
    '**Wo sie sich treffen.** Sie streiten nicht über die Belege. Die',
    'Stimme des Alltags hat die Zahlen genannt, die für die einfache',
    'Medizin sprechen — die Potsdamer Untersuchung mit ihren 78 Prozent,',
    'das Diabetes-Präventionsprogramm, Nordkarelien — und sie hat die',
    'Studien selbst benannt, die dagegen sprechen: Look AHEAD, das',
    'wackelige Fundament der blauen Zonen. Die Stimme der Verhältnisse',
    'hat diese Belege nicht bestritten; sie hat gefragt, unter welchen',
    'Bedingungen man ihnen folgen kann. Beide haben ihre unbequemen',
    'Stellen selbst ausgesprochen: die eine, dass aus ihrem Angebot',
    'schnell ein Vorwurf wird; die andere, dass die Verhältnisse von',
    'Menschen gemacht sind — und dass auch sie selbst an ihnen teilhat.',
    '',
    '**Worüber sie auseinandergehen.** Sie gehen bei einer einzigen',
    'Frage auseinander: Wer kann es umsetzen? Die Stimme des Alltags',
    'sagt: Du — die 8.758 Stunden sind Deine, und wer heute anfängt,',
    'wartet nicht auf die Entscheidung. Die Stimme der Verhältnisse',
    'sagt: Du — und die, die Deinen Tag einteilen; wer die Treppe nicht',
    'gebaut hat, kann sie auch nicht nehmen. Es ist kein Streit zwischen',
    'Wahr und Falsch. Es ist der Streit zwischen zwei Wahrheiten, die',
    'beide gelten: **Der Einzelne kann etwas — und der Einzelne kann',
    'nicht alles.**',
    '',
    '**Was das für dieses Buch heißt.** Die Denkart bestimmt die',
    'Methode. Die Medizin denkt in Diagnosen, Wirkstoffen und',
    'abrechenbaren Leistungen — darum verschreibt sie die Pille. Die',
    'Lebensstil-Medizin denkt in Stunden, Gewohnheiten und Verhältnissen',
    '— darum hat sie keinen Abrechnungscode. Die einfache Medizin ist',
    'keine Raketenwissenschaft, aber sie ist auch keine Verordnung. Sie',
    'ist eine Verhandlung zwischen dem Menschen und seiner Umgebung.',
    'Wer sie nur dem Einzelnen aufbürdet, macht aus einem Angebot eine',
    'Schuld. Wer sie nur den Verhältnissen aufbürdet, verschenkt die',
    'Stunden, die wirklich in der eigenen Hand liegen. Das eine ist',
    'unfair, das andere ist eine Ausrede — und dieses Kapitel hat',
    'beide benannt, damit der Leser keiner von beiden glaubt.',
    '',
    '**Die Brücke zum nächsten Kapitel.** Und dann bleibt die Frage,',
    'die dieses Kapitel an das nächste weitergibt: Wenn die Medizin von',
    'morgen teuer wird und für wenige reserviert bleibt — gezüchtete',
    'Organe, Genanalysen, ständige Überwachung —, wird die einfache',
    'Medizin dann die Medizin für alle? Oder die, die den Vielen',
    'bleibt, wenn die Schere zwischen reich und arm aufgeht? Beide',
    'Stimmen dieses Kapitels haben dieselbe Sorge in unterschiedlichen',
    'Worten benannt. Kapitel 19 wird die Schere zeigen.',
  ].join('\n'),

  urteil: {
    frage:
      'Warum ist die einfache Medizin so schwer zu verschreiben — und ' +
      'wer müsste etwas ändern, damit sie ankommt?',
    hinweis: [
      'Es gibt hier kein Richtig und kein Falsch. Halte die beiden Seiten',
      'nebeneinander. Die eine: Vier einfache Merkmale — nicht rauchen,',
      'nicht zu schwer sein, sich bewegen, vernünftig essen — hingen in der',
      'Potsdamer Untersuchung mit einem um 78 Prozent geringeren Risiko für',
      'schwere chronische Krankheiten zusammen. Das erreicht kein',
      'Medikament. Die andere: Ein Rat ist keine Behandlung; die',
      'Look-AHEAD-Studie fand nach fast zehn Jahren keinen Unterschied bei',
      'Herzinfarkten; und wer im Schichtdienst arbeitet oder zwei Stellen',
      'hat, kann sich seinen Tag nicht aussuchen. Frag Dich dreierlei.',
      'Erstens: Was von den drei Säulen — Bewegung, Essen, Menschen um Dich',
      'herum — liegt tatsächlich in Deiner Hand, und was nicht? Zweitens:',
      'Wenn ein Arzt siebeneinhalb Minuten Zeit hat, was kann er in dieser',
      'Zeit realistisch tun — ein Rezept ausstellen oder eine',
      'Lebensänderung anstoßen? Drittens: Wenn das Wirksamste fast nichts',
      'kostet — wem nützt es, dass es trotzdem so selten verordnet wird?',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Was untersuchte der Arzt Jeremy Morris 1953 an Londoner ' +
        'Busschaffnern und Busfahrern?',
      antworten: [
        'Ob Lärm im Straßenverkehr den Blutdruck erhöht.',
        'Ob die Schaffner, die den ganzen Tag die Treppe des Doppeldeckers ' +
          'hinauf- und hinunterliefen, seltener Herzinfarkte bekamen als die ' +
          'sitzenden Fahrer.',
        'Ob Schichtarbeit die Lebenserwartung senkt.',
      ],
      richtig: 1,
      erklaerung:
        'Morris verglich zwei Berufsgruppen derselben Firma, die sich in ' +
        'fast allem glichen und in der Bewegung unterschieden. Die ' +
        'Schaffner hatten etwa halb so viele Herzinfarkte wie die Fahrer ' +
        'und überlebten sie häufiger. Er prüfte das Ergebnis an ' +
        'Briefträgern und Schalterbeamten der Post nach und fand dasselbe ' +
        'Bild. Die Veröffentlichung im Lancet von 1953 gilt als Beginn der ' +
        'Forschung über Bewegung und Gesundheit.',
    },
    {
      frage:
        'In der Potsdamer EPIC-Untersuchung (Auswertung von 2009) wurden ' +
        'vier Merkmale geprüft: nie geraucht, Körpermasse-Index unter 30, ' +
        'mindestens dreieinhalb Stunden Bewegung pro Woche und eine ' +
        'pflanzenbetonte Kost. Wie groß war der Unterschied?',
      antworten: [
        'Wer alle vier erfüllte, hatte ein um etwa 78 Prozent geringeres ' +
          'Risiko für eine schwere chronische Krankheit.',
        'Wer alle vier erfüllte, hatte ein um etwa 12 Prozent geringeres ' +
          'Risiko.',
        'Es zeigte sich kein Unterschied zwischen den Gruppen.',
      ],
      richtig: 0,
      erklaerung:
        'Die Untersuchung begleitete 23.153 Menschen zwischen 35 und 65 ' +
        'Jahren. Wer alle vier Merkmale erfüllte, hatte gegenüber denen ' +
        'ohne eines davon ein um 78 Prozent geringeres Risiko — im ' +
        'Einzelnen 93 Prozent weniger Typ-2-Diabetes, 81 Prozent weniger ' +
        'Herzinfarkte, 50 Prozent weniger Schlaganfälle und 36 Prozent ' +
        'weniger Krebserkrankungen. Es handelt sich um eine ' +
        'Beobachtungsstudie, nicht um einen Versuch mit Losverfahren.',
    },
    {
      frage:
        'Was geschah in dem Versuch von Kevin Hall und seiner Gruppe (2019), ' +
        'in dem zwanzig Menschen je zwei Wochen ultraverarbeitete und je ' +
        'zwei Wochen unverarbeitete Kost bekamen?',
      antworten: [
        'Die Menschen aßen in beiden Phasen gleich viel.',
        'In den Wochen mit ultraverarbeiteter Kost aßen sie rund 500 ' +
          'Kilokalorien am Tag mehr und nahmen zu.',
        'Die unverarbeitete Kost machte die Teilnehmenden hungriger.',
      ],
      richtig: 1,
      erklaerung:
        'Beide Speisepläne waren nach Nährstoffen ausgeglichen, und die ' +
        'Teilnehmenden durften essen, so viel sie wollten. In den ' +
        'ultraverarbeiteten Wochen aßen dieselben Menschen etwa 500 ' +
        'Kilokalorien mehr am Tag und nahmen im Schnitt fast ein Kilogramm ' +
        'zu, in den unverarbeiteten Wochen nahmen sie fast ein Kilogramm ' +
        'ab. Der Versuch fand stationär statt, damit alles Gegessene ' +
        'erfasst werden konnte.',
    },
    {
      frage:
        'Woher stammt der Begriff „blaue Zonen" für Gegenden mit besonders ' +
        'vielen sehr alten Menschen?',
      antworten: [
        'Von der blauen Farbe des Meeres an den betreffenden Küsten.',
        'Von einer Werbekampagne der Weltgesundheitsorganisation.',
        'Von Gianni Pes und Michel Poulain, die 2004 auf einer Karte ' +
          'Sardiniens die Gemeinden mit den meisten Hundertjährigen mit ' +
          'blauem Stift umkreisten.',
      ],
      richtig: 2,
      erklaerung:
        'Aus diesen blauen Kreisen wurde ab 2005 durch den Journalisten ' +
        'Dan Buettner die bekannte Reihe von fünf Gebieten: Sardinien, ' +
        'Okinawa, Ikaria, Nicoya und Loma Linda. Der Befund ist umstritten: ' +
        'Der Demograf Saul Justin Newman zeigte, dass hohe ' +
        'Hundertjährigen-Quoten oft mit lückenhaften Geburtsregistern ' +
        'zusammenfallen; dafür bekam er 2024 den Ig-Nobelpreis.',
    },
    {
      frage:
        'Die Look-AHEAD-Studie (2013) prüfte an 5.145 übergewichtigen ' +
        'Menschen mit Typ-2-Diabetes ein intensives Lebensstil-Programm. ' +
        'Was war ihr Hauptergebnis?',
      antworten: [
        'Die Lebensstil-Gruppe hatte deutlich weniger Herzinfarkte und ' +
          'Schlaganfälle.',
        'Die Lebensstil-Gruppe verlor mehr Gewicht und hatte bessere Werte, ' +
          'aber nach im Mittel 9,6 Jahren keine geringere Zahl schwerer ' +
          'Herz-Kreislauf-Ereignisse.',
        'Das Programm schadete den Teilnehmenden, weshalb die Studie ' +
          'abgebrochen wurde.',
      ],
      richtig: 1,
      erklaerung:
        'Die Studie wurde vorzeitig beendet, weil sich abzeichnete, dass ' +
        'kein Unterschied beim Hauptziel mehr zu erwarten war — nicht wegen ' +
        'Schäden. Die Lebensstil-Gruppe hatte weniger Gewicht, mehr ' +
        'Beweglichkeit, seltener Nierenerkrankungen und seltener ' +
        'Depressionen. Ein möglicher Grund für das Ausbleiben des ' +
        'Unterschieds beim Herzinfarkt: Auch die Vergleichsgruppe wurde ' +
        'medikamentös gut behandelt und änderte ihr Verhalten. Bewiesen ' +
        'ist diese Erklärung nicht.',
    },
  ],
};

module.exports = einfacheMedizin;
