// Kapitel 4 — „Hippokrates und Galen".
//
// Die europäische Wurzel: zwei Männer, die sich nie begegnet sind (zwischen
// ihnen liegen rund fünfeinhalb Jahrhunderte) und die zusammen bestimmten,
// wie in Europa zweitausend Jahre lang über Krankheit gedacht wurde. Der eine
// setzte auf Beobachtung und gab zu, wenig zu wissen; der andere baute ein
// geschlossenes System, das jede Frage beantwortete — und genau deshalb so
// lange nicht mehr hinterfragt wurde.
//
// Dieses Kapitel tut, was der Betreiber verlangt hat: Es analysiert die
// DENKART umfangreich — nicht nur, WAS getan wurde, sondern WARUM. Die
// Vier-Säfte-Lehre als Ordnungssystem (Eukrasie und Dyskrasie), die Natur als
// Heilerin, die Beobachtung und die Prognose, die Lebensweise als Arznei und
// der Eid als erste Selbstbindung eines Berufs — dazu die ehrliche
// Wirkungsbilanz: was bis heute steht (Beobachtung, Ethik, Diätetik, einige
// Handgriffe der Chirurgie) und was Jahrhunderte lang geschadet hat (Aderlass
// und Abführmittel, die aus genau dieser Theorie folgten).
//
// Stimmen (Runde 5): Die ERSTE Perspektive — die Stimme des Hippokrates, die
// Schule von Kos — verfasste Opus. Die ZWEITE (Galen: das System, die
// Anatomie, die Autorität) und die finale Synthese ergänzte Hermes im
// zweiten Pass. Perspektiven-Workflow: CLAUDE.md.
//
// KEINE WIEDERHOLUNGEN (Betreiber-Entscheid vom 21.08.2026): Kapitel 1
// gliedert seine Stimmen nach „Wer hier spricht → …", Kapitel 2 beginnt mit
// einer Szene (drei Finger am Handgelenk) und führt die Begründungslogik an
// „Warum"-Überschriften entlang, Kapitel 3 erzählt einen Tageslauf. Dieses
// Kapitel wählt eine vierte Dramaturgie: einen BRIEFWECHSEL, der keiner sein
// kann. Die Schule von Kos schreibt neun Briefe an einen Arzt, den sie nicht
// kennt — an den, der nach ihr kommt. Beantwortet werden sie erst 550 Jahre
// später von einem Mann aus Pergamon, der den Absender nur aus Büchern kennt.
// Die Form ist historisch grundiert: Dem Corpus Hippocraticum sind seit der
// Antike Briefe beigelegt, die Hippokrates zugeschrieben wurden und sicher
// nicht von ihm stammen. Die erste Stimme sagt das selbst.
//
// Die Texte liegen als Zeilen-Arrays mit `.join('\n')` — so bleiben sie im
// Repo bei ~72 Zeichen lesbar (der Betreiber liest sie hier gegen), und
// utils/markdown.js macht in der App wieder fließenden Text daraus.
//
// CommonJS ohne UI-Importe (Architektur-Regel): mit blankem `node` prüfbar.

const { karte } = require('./karten/hippokrates-galen');

/**
 * Die Stimme des Hippokrates — die Schule von Kos.
 *
 * Verfasst von Opus (Runde 5). Neun Briefe an einen unbekannten Nachfolger:
 * Weltbild, Begründungslogik, Herkunft des Wissens und Wirkungsbilanz. Sie
 * benennt die unbequemen Stellen der eigenen Erzählung selbst, statt sie der
 * Gegenstimme zu überlassen (Zusatzregel für sensible Themen in CLAUDE.md) —
 * bis hin zu dem Satz, dass ihre eigene Theorie später Menschen getötet hat.
 */
const stimmeDesHippokrates = [
  '## Der erste Brief: An den Arzt, der nach mir kommt',
  '',
  'Ich weiß nicht, wer Du bist. Ich weiß nicht einmal, ob Du lesen wirst,',
  'was wir hier auf Kos aufschreiben. Trotzdem schreibe ich Dir, denn ein',
  'Handwerk, das nicht weitergegeben wird, stirbt mit dem, der es kann.',
  '',
  'Zuerst muss ich Dir eine Unbequemlichkeit gestehen, sonst beginnt dieser',
  'Briefwechsel mit einer Lüge. **Wenn Du „Hippokrates" liest, denkst Du an',
  'einen Mann. Es waren viele.** Es hat ihn gegeben, den Arzt von Kos; ein',
  'Philosoph namens Platon erwähnt ihn, als er noch lebt, ganz beiläufig,',
  'wie man einen bekannten Fachmann erwähnt. Aber die rund sechzig',
  'Schriften, die später seinen Namen tragen, stammen von verschiedenen',
  'Händen, aus verschiedenen Jahrzehnten, und sie widersprechen einander an',
  'vielen Stellen. Manche sind Lehrbücher, manche Vorlesungen, manche bloße',
  'Notizhefte. Selbst die Briefe, die man mir zuschreibt, sind Jahrhunderte',
  'nach meinem Tod verfasst worden — auch dieser hier ist eine Form, keine',
  'Urkunde.',
  '',
  'Nimm das nicht als Entwertung. Nimm es als das Erste, was ich Dir',
  'beibringen will: **Prüfe, wer spricht, und traue keinem Namen mehr als',
  'der Sache.** Ich rede in diesen Briefen als eine Schule, nicht als ein',
  'Orakel. Was ich Dir erzähle, ist keine Wahrheit, sondern eine Denkart —',
  'die Art, wie wir in dieser Ecke der Ägäis versucht haben, Krankheit zu',
  'verstehen. Sie ist in Teilen falsch. Ich werde Dir am Ende selbst sagen,',
  'in welchen.',
  '',
  'Und noch etwas: Ich bin nicht der Anfang. Vor uns lagen Jahrhunderte am',
  'Nil, in denen Ärzte Wunden nähten, Brüche schienten und ihre Mittel',
  'aufschrieben; die Ägypter hatten Bücher, als wir noch keine Schrift',
  'hatten. Aus Ägypten kam ein guter Teil unserer Arzneikunde, aus',
  'Mesopotamien kam der Blick auf den Verlauf der Tage. Wer behauptet, die',
  'Heilkunde beginne bei uns, hat sie nur von hier aus zu betrachten',
  'gelernt.',
  '',
  '## Der zweite Brief: Von der heiligen Krankheit',
  '',
  'Es gibt ein Leiden, das die Leute die heilige Krankheit nennen. Ein',
  'Mensch stürzt zu Boden, die Glieder zucken, Schaum tritt vor den Mund,',
  'und wenn es vorüber ist, weiß er von nichts. Du kennst es. Die',
  'Reinigungspriester sagen, ein Gott sei in ihn gefahren, und je nachdem,',
  'wie das Zucken aussieht, benennen sie den Gott.',
  '',
  'Einer von uns hat darüber ein schmales Buch geschrieben, und es beginnt',
  'mit einem Satz, an dem sich alles Weitere entscheidet: **Sie ist um',
  'nichts göttlicher als andere Krankheiten. Sie hat eine Natur wie alle',
  'anderen und eine Ursache.** Wer sie heilig nennt, so heißt es weiter,',
  'tut das aus Ratlosigkeit — und wer aus Ratlosigkeit einen Gott anruft,',
  'verkauft seine Unwissenheit als Frömmigkeit.',
  '',
  'Verstehe genau, was hier geschieht und was nicht geschieht.',
  '',
  'Es geschieht **nicht**, dass wir die Götter abschaffen. Wir sind fromme',
  'Leute; unser Eid beginnt mit Apollon und Asklepios, und auf meiner',
  'eigenen Insel steht ein großes Heiligtum, in dem Kranke schlafen und',
  'auf einen heilenden Traum warten. Diese Kranken kommen zu Tausenden.',
  'Manche gehen geheilt nach Hause. Ich kann nicht beweisen, dass ihnen',
  'weniger geholfen wurde als mir.',
  '',
  'Es geschieht etwas Kleineres und Folgenreicheres: **Wir ändern die',
  'Frage.** Statt zu fragen „Welcher Gott zürnt?" fragen wir „Was ist',
  'vorher passiert, was passiert jetzt, und was wird morgen sein?". Ein',
  'zürnender Gott lässt sich nur besänftigen. Eine Ursache in der Natur',
  'lässt sich beobachten, mit anderen Fällen vergleichen und vielleicht',
  'beeinflussen. Die ganze Heilkunde, die Du erben wirst, hängt an diesem',
  'einen Schritt.',
  '',
  'Er hat einen Preis, und ich nenne ihn gleich mit: Wer die Ursache in',
  'der Natur sucht, muss aushalten, sie oft nicht zu finden. Der Priester',
  'hat immer eine Antwort. Ich habe manchmal keine.',
  '',
  '## Der dritte Brief: Von den vier Säften',
  '',
  'Nun zu dem Gebäude, in dem wir wohnen. Du wirst es später abreißen',
  'müssen; ich will trotzdem, dass Du verstehst, warum wir es gebaut haben.',
  '',
  'Nimm frisches Blut aus einer Ader und lass es in einer Schale stehen.',
  'Nach einer Weile siehst Du vier Schichten: oben eine gelbliche,',
  'durchsichtige Flüssigkeit; darunter etwas Weißes, Zähes; darunter das',
  'rote Blut; und ganz unten eine dunkle, fast schwarze Masse. Vier Dinge,',
  'die sichtbar auseinandertreten. Wir haben daraus geschlossen, dass der',
  'Mensch aus vier Säften besteht:',
  '',
  '- **Blut** — warm und feucht. Es kommt aus dem Herzen, es ist das',
  '  Lebendige, das Antreibende. Zuviel davon macht rot, heiß, hitzig.',
  '- **Schleim** (*Phlegma*) — kalt und feucht. Er kommt aus dem Kopf.',
  '  Denke an den Winter, an den Schnupfen, an den zähen Auswurf. Zuviel',
  '  davon macht schwer, träge, verstopft.',
  '- **Gelbe Galle** — warm und trocken. Aus der Leber. Sie zeigt sich in',
  '  Fieber, Erbrechen, Gelbsucht, Zorn. Denke an den Hochsommer.',
  '- **Schwarze Galle** — kalt und trocken. Aus der Milz. Sie ist der',
  '  Herbst, das Dunkle, das Schwere, die Schwermut. Ich sage Dir gleich:',
  '  Diesen Saft hat nie jemand gesehen. Wir haben ihn gebraucht, damit',
  '  die Ordnung aufgeht, und was wir schwarze Galle nannten, war wohl',
  '  geronnenes Blut aus einem Magengeschwür oder der dunkle Bodensatz in',
  '  der Schale. Das ist die schwächste Stelle des ganzen Gebäudes, und',
  '  ich nenne sie Dir zuerst, damit Du nicht sagen kannst, ich hätte sie',
  '  versteckt.',
  '',
  'Nun die Regel, die aus diesen vier Säften ein System macht:',
  '**Gesundheit ist nicht die Abwesenheit eines Saftes, sondern die',
  'richtige Mischung aller vier — wir nennen das Eukrasie, die gute',
  'Mischung. Krankheit ist die schlechte Mischung: Dyskrasie.** Ein Saft',
  'ist zu viel geworden, oder er sitzt am falschen Ort, oder er ist',
  'verdorben.',
  '',
  'Warum diese Erklärung und keine andere? Weil sie vier Dinge auf einmal',
  'leistet, und keine andere Erklärung, die wir hatten, leistete auch nur',
  'zwei davon.',
  '',
  '**Erstens ordnet sie die Welt und den Menschen nach derselben Regel.**',
  'Die Denker unserer Zeit sagen, alles bestehe aus Erde, Wasser, Luft und',
  'Feuer, und diese vier tragen die Eigenschaften warm, kalt, feucht,',
  'trocken. Unsere vier Säfte tragen dieselben Eigenschaften. Der Mensch',
  'ist damit kein Sonderfall in der Natur, sondern aus demselben Stoff',
  'gemacht wie alles andere — und deshalb mit denselben Mitteln zu',
  'behandeln: mit Wärme, Kälte, Feuchte, Trockenheit.',
  '',
  '**Zweitens erklärt sie die Jahreszeiten.** Im Winter kommen die',
  'Katarrhe, im Frühjahr das Nasenbluten, im Sommer die Fieber und',
  'Durchfälle, im Herbst die Wechselfieber. Das ist keine Theorie, das ist',
  'die Erfahrung jedes Arztes, der zehn Jahre lang aufschreibt, wer wann',
  'krank wird. Vier Säfte und vier Jahreszeiten passen aufeinander — im',
  'Winter mehrt sich der kalte, feuchte Schleim, im Sommer die heiße,',
  'trockene Galle. Wir hatten damit als Erste eine Verbindung von Wetter,',
  'Ort und Krankheit, und die war richtig gesehen, auch wenn die Begründung',
  'falsch war.',
  '',
  '**Drittens erklärt sie, warum Menschen verschieden sind.** Bei dem einen',
  'überwiegt von Natur aus das Blut, bei dem anderen die schwarze Galle.',
  'Daraus wurden später die vier Wesensarten, die Du vielleicht noch kennst:',
  'der Blutvolle, der Schleimige, der Galligte, der Schwermütige. Damit',
  'behandeln wir nicht eine Krankheit, sondern einen bestimmten Menschen.',
  'Zwei Kranke mit demselben Fieber bekommen bei uns Verschiedenes, weil',
  'sie verschieden gemischt sind.',
  '',
  '**Viertens gibt sie dem Arzt etwas zu tun, das folgerichtig ist.** Ist',
  'zu viel Kaltes und Feuchtes da, gib Warmes und Trockenes. Ist zu viel',
  'von einem Saft da, hilf dem Körper, ihn loszuwerden. Aus dieser einen',
  'Regel folgt alles Weitere — und, das sage ich hier schon, aus ihr folgt',
  'auch das Verhängnis, von dem im neunten Brief die Rede sein wird.',
  '',
  'Wenn Du weit gereist bist, wird Dir etwas auffallen. Am Nil erzählen',
  'die Ärzte von Kanälen im Körper, die verstopfen können. Weiter im Osten,',
  'so hört man, sprechen sie von einem Atem, der fließen muss, und von',
  'zwei Kräften, die im Gleichgewicht stehen sollen; noch weiter östlich',
  'von drei Kräften, die ein Mensch in seinem eigenen Maß mitbringt. Und',
  'wir reden von vier Säften, die richtig gemischt sein wollen. **Vier',
  'Sprachen, ein Gedanke: Gesundheit ist Gleichgewicht, Krankheit ist',
  'dessen Störung.** Ich glaube nicht, dass wir voneinander abgeschrieben',
  'haben. Ich glaube, dass Menschen, die genau hinsehen und noch nichts',
  'messen können, immer bei diesem Gedanken landen. Ob das für ihn',
  'spricht oder gegen ihn, entscheide Du.',
  '',
  '## Der vierte Brief: Von der Natur, die heilt',
  '',
  'Jetzt kommt der Satz, um den es mir eigentlich geht, und er ist so',
  'kurz, dass man ihn überliest: **Die Natur ist der Arzt der Krankheiten.**',
  'Später hat man ihn lateinisch gesagt — *vis medicatrix naturae*, die',
  'Heilkraft der Natur —, aber gemeint war immer dasselbe: Der Körper',
  'stellt sein Gleichgewicht selbst wieder her. Er findet den Weg ohne',
  'Unterricht, wie er atmet, ohne es zu lernen.',
  '',
  'Wenn das so ist, dann ist die Aufgabe des Arztes eine ganz andere, als',
  'die Leute denken. **Er heilt nicht. Er hilft dem, der heilt.** Er sorgt',
  'dafür, dass die Natur die Ruhe, die Kraft und die Zeit bekommt, die sie',
  'braucht; er räumt weg, was ihr im Weg steht; und er hält sich zurück,',
  'wo er nur stören würde. Wir haben es so aufgeschrieben: Der Arzt ist',
  'der Diener seiner Kunst, und der Kranke muss mit dem Arzt gemeinsam',
  'gegen die Krankheit stehen.',
  '',
  'Daraus folgt unsere Deutung des Fiebers, und die ist Ihnen, die Ihr',
  'später lebt, vielleicht die fremdeste. **Wir halten das Fieber nicht',
  'für die Krankheit, sondern für die Arbeit.** Der verdorbene Saft muss,',
  'so unsere Vorstellung, im Körper gekocht und reif gemacht werden, bevor',
  'er hinausgeschafft werden kann — wie ein Geschwür erst reifen muss,',
  'bevor es sich entleert. Diese Reifung nennen wir Kochung. Wenn sie',
  'gelungen ist, kommt der Umschlag: die **Krisis**. An einem bestimmten',
  'Tag bricht der Schweiß aus, oder das Nasenbluten, oder der Durchfall,',
  'und danach entscheidet sich alles in wenigen Stunden — der Kranke wird',
  'gesund, oder er stirbt.',
  '',
  'Deshalb zählen wir Tage. Der vierte, der siebte, der elfte, der',
  'vierzehnte, der zwanzigste: Das sind für uns die Tage, an denen die',
  'Entscheidung fällt. Ich gebe zu, dass wir dabei mehr Ordnung gesehen',
  'haben, als es gibt; wer Zahlen liebt, findet Zahlen. Aber der Kern',
  'stimmt: **Krankheiten haben einen Verlauf, und der Verlauf hat Gestalt.**',
  'Wer den Verlauf kennt, weiß, wann er nichts tun darf.',
  '',
  'Und damit zur wichtigsten Frage, die Du mir stellen wirst: **Warum',
  'beobachten statt eingreifen?** Drei Gründe.',
  '',
  'Der erste: Weil das meiste von selbst besser wird, und wer dann etwas',
  'gibt, hält sich für die Ursache der Besserung. So entstehen die',
  'berühmtesten Heilmittel und die haltbarsten Irrtümer.',
  '',
  'Der zweite: Weil unsere Mittel gefährlich sind. Die kräftigsten Arzneien,',
  'die wir haben — die Nieswurz vor allem —, treiben nach oben und nach',
  'unten aus. Bei einem Kräftigen räumen sie auf. Bei einem Erschöpften',
  'nehmen sie ihm den Rest. Wir haben Menschen an unseren eigenen Mitteln',
  'sterben sehen. Wer ein scharfes Werkzeug hat, muss lernen, es liegen zu',
  'lassen.',
  '',
  'Der dritte: Weil ich nicht weiß, was in Dir vorgeht. Ich habe Deinen',
  'Körper nie von innen gesehen. Ich kann tasten, hören, riechen, fragen —',
  'öffnen kann ich Dich nicht, das verbietet uns Sitte und Gesetz. Ein',
  'Arzt, der so wenig weiß wie ich und trotzdem kräftig eingreift, ist',
  'kein mutiger Arzt, sondern ein gefährlicher.',
  '',
  'Der Satz, in dem das alles zusammenläuft, steht in unseren Fallbüchern',
  'in einem Nebensatz, und er ist das Beste, was wir hinterlassen:',
  '**Nützen — oder wenigstens nicht schaden.**',
  '',
  '## Der fünfte Brief: Von der Beobachtung und der Vorhersage',
  '',
  'Wie also arbeiten wir, wenn wir so wenig wissen? Wir sehen hin, und wir',
  'schreiben auf.',
  '',
  'Ich will Dir zeigen, wie das aussieht, und ich zitiere Dir aus unseren',
  'Fallbüchern, den *Epidemien*, ungefähr so, wie es dort steht:',
  '„Philiskos wohnte bei der Mauer. Er legte sich nieder. Am ersten Tag',
  'akutes Fieber, Schweiß; die Nacht unruhig. Zweiter Tag: alles',
  'verschlimmert. Dritter Tag: Schmerzen. Vierter Tag: … Am sechsten Tag',
  'gegen Mittag starb er." Ein Name, ein Ort, Tag für Tag, was zu sehen',
  'war — und am Ende, ohne Beschönigung, der Ausgang.',
  '',
  '**Sieh Dir an, was hier fehlt.** Es fehlt die Erklärung, welcher Gott',
  'zürnte. Es fehlt das Lob des Arztes. Und vor allem: Es fehlt die',
  'Auswahl. Von den zweiundvierzig Kranken, deren Verläufe in diesen',
  'Büchern stehen, sterben mehr als die Hälfte, und sie stehen trotzdem',
  'darin. **Wir haben unsere Misserfolge aufgeschrieben.** Ich kenne',
  'keinen Beruf, der das freiwillig tut. Wenn Du aus diesen Briefen nur',
  'eine einzige Gewohnheit übernimmst, dann diese.',
  '',
  'Beobachten heißt bei uns: mit allen Sinnen. Wir sehen das Gesicht an —',
  'die spitze Nase, die eingesunkenen Augen, die kalten Ohren, die',
  'fahlgraue Haut bei einem Sterbenden; wer dieses Gesicht einmal',
  'beschrieben gesehen hat, erkennt es wieder. Wir riechen an Atem, Urin',
  'und Wunde. Wir schmecken den Urin, wenn es sein muss. Wir legen das Ohr',
  'auf den Brustkorb und hören, ob es knistert wie Leder; wir fassen einen',
  'Kranken an den Schultern und schütteln ihn, um zu hören, ob in seiner',
  'Brust Flüssigkeit plätschert. Wir fragen nach dem Haus, der Arbeit, dem',
  'Wasser, dem Wind, der Nachbarschaft.',
  '',
  'Und dann tun wir das, was uns von den Marktschreiern unterscheidet:',
  '**Wir sagen den Verlauf voraus.** Prognose, nicht Diagnose. Für Dich,',
  'der Du vielleicht in einer Zeit lebst, in der man Krankheiten benennen',
  'kann, klingt das rückständig. Für uns war es das Vernünftigste, was zu',
  'haben war, und zwar aus zwei Gründen.',
  '',
  'Zum einen, weil ein Name uns nichts nützt. Wir könnten hundert',
  'Krankheiten unterscheiden — die Kollegen in Knidos tun genau das, sie',
  'zählen sieben Arten von Gallenkrankheit und zwölf von Blasenleiden —,',
  'und wir wüssten trotzdem nicht, was zu tun ist. Der Verlauf sagt uns',
  'mehr als der Name.',
  '',
  'Zum anderen, weil wir keine Zulassung haben. Es gibt keine Behörde, die',
  'einen Arzt prüft; jeder Wanderer mit einem Kasten Kräuter darf sich so',
  'nennen. Wenn ich in eine fremde Stadt komme, kennt mich niemand. Sage',
  'ich aber am Montag, was am Donnerstag geschehen wird, und es geschieht,',
  'dann hat mir am Freitag die ganze Straße zugehört. **Die Vorhersage war',
  'unser Zeugnis.** Sie war zugleich unser Schutz: Wer früh sagt, dass er',
  'diesen Kranken nicht retten kann, verliert nicht seinen Ruf, wenn der',
  'Kranke stirbt.',
  '',
  'Ich weiß, wie schäbig dieser letzte Satz klingen kann, und ich komme im',
  'siebten Brief darauf zurück.',
  '',
  '## Der sechste Brief: Von der Lebensweise als Arznei',
  '',
  'Du wirst Dich wundern, wie wenig in unseren Büchern über Arzneien steht',
  'und wie viel über Essen, Trinken, Baden, Gehen und Schlafen. Das ist',
  'kein Mangel an Kräutern. Das ist eine Entscheidung.',
  '',
  '**Warum die Lebensweise und nicht das Mittel?** Weil der Mensch jeden',
  'Tag isst und jeden Tag atmet, das Mittel aber nur, wenn er krank ist.',
  'Was täglich auf ihn wirkt, formt seine Mischung; was einmal wirkt, kann',
  'sie nur stoßen. Wir nennen das ganze Feld *Diaita* — und meine, wenn Du',
  'das Wort später als „Diät" wiederfindest, dass wir viel mehr gemeint',
  'haben: die ganze Lebensführung.',
  '',
  'Dazu gehört auch der Ort, an dem einer lebt. In einer unserer Schriften',
  'steht eine Anweisung, die ich für unsere nützlichste halte: Wer als',
  'Arzt in eine fremde Stadt kommt, soll zuerst auf die Winde achten, aus',
  'welcher Richtung sie wehen; dann auf das Wasser, ob es sumpfig ist oder',
  'aus Quellen kommt; dann auf den Boden, ob kahl oder bewässert; und',
  'zuletzt auf die Lebensweise der Leute, ob sie viel essen und trinken',
  'und wenig gehen. **Danach weiß er, welche Krankheiten er in dieser Stadt',
  'finden wird, bevor er den ersten Kranken gesehen hat.** Das ist,',
  'soweit ich weiß, der erste Versuch, Krankheit aus Umwelt und',
  'Lebensweise vorherzusagen — der Gedanke lebt in dem weiter, was Ihr',
  'später Gesundheitswesen nennen werdet.',
  '',
  'Unsere Werkzeuge sind entsprechend einfach und für jeden zu haben:',
  '',
  '- **Gerstenschleim und dünner Wein** bei akuten Fiebern — leichte Kost,',
  '  weil ein Kranker nicht verdauen kann, was ein Gesunder verträgt.',
  '  Achte auf den Zeitpunkt: Zu früh gefüttert, verlängert man das',
  '  Fieber; zu lange gehungert, entkräftet man den Kranken.',
  '- **Gehen, Reiten, Ringen, Massage mit Öl** — für uns Heilmittel, nicht',
  '  Vergnügen. Wer sich nicht bewegt, verdirbt seine Mischung.',
  '- **Bäder, warme Umschläge, Dampf** — um zu erwärmen, zu erweichen, zu',
  '  lösen. Wasser ist unsere biegsamste Arznei: Du kannst es warm oder',
  '  kalt geben, innen oder außen, viel oder wenig.',
  '- **Schlaf und Ruhe**, und zwar verordnet, mit Uhrzeit und Dauer.',
  '- **Arzneien** erst dann — Nieswurz zum Ausleeren, Honig, Essig, Wein,',
  '  Mohn gegen Schmerzen, Weidenrinde gegen Fieber und Schmerz. Von der',
  '  Weide wird man in Deiner Zeit vielleicht noch hören.',
  '',
  'Und dann die Hand. Wir sind auch Handwerker. Wir richten ausgerenkte',
  'Schultern ein — der Griff, mit dem wir es tun, wird noch nach',
  'zweitausend Jahren nach uns benannt sein —, wir schienen Brüche, wir',
  'strecken verkrümmte Rücken auf einer Bank mit Seilwinden, wir behandeln',
  'den Klumpfuß eines Neugeborenen mit sanftem Nachdrücken und Binden, wir',
  'trepanieren den Schädel nach einem Schlag. Für Wunden gilt bei uns:',
  'reines Wasser oder Wein, saubere, ausgekochte Tücher, wenig Wühlen. Wir',
  'wissen nichts von Fäulniserregern. Aber wir haben gesehen, dass eine',
  'Wunde, die trocken und in Ruhe gelassen wird, seltener eitert.',
  '',
  '## Der siebte Brief: Von dem Eid',
  '',
  'Nun zu dem Schriftstück, das Dich vermutlich als Einziges erreichen',
  'wird, wenn alles andere verloren geht.',
  '',
  '**Warum überhaupt ein Eid?** Weil es keinen anderen Schutz gibt. Es gibt',
  'keine Prüfung, keine Kammer, keinen Richter, der einen schlechten Arzt',
  'aus dem Verkehr zieht. Wir kommen in fremde Häuser, sehen nackte',
  'Körper, hören Familiengeheimnisse, haben Gifte im Kasten und Messer in',
  'der Tasche. Eine solche Macht muss sich selbst binden, sonst bindet sie',
  'irgendwann jemand anders — oder niemand.',
  '',
  'Der Eid tut deshalb dreierlei.',
  '',
  '**Er stiftet eine Zunft.** Der Lehrer wird dem Schüler wie ein Vater;',
  'der Schüler wird ihn im Alter versorgen und seine Söhne unentgeltlich',
  'unterrichten. Das klingt heute nach Klüngel und war damals das Einzige,',
  'was Wissen weitergab.',
  '',
  '**Er zieht Grenzen.** Ich werde niemandem ein tödliches Mittel geben,',
  'auch wenn er mich darum bittet; ich werde keiner Frau ein Mittel zur',
  'Abtreibung reichen; ich werde nicht schneiden, auch nicht den',
  'Blasenstein, sondern das denen überlassen, die dieses Handwerk',
  'betreiben; ich werde in kein Haus gehen, um Unrecht zu tun, und mich an',
  'keinem Menschen im Haus vergreifen, weder an Freien noch an Sklaven.',
  '',
  '**Er verpflichtet zur Verschwiegenheit.** Was ich bei der Behandlung',
  'sehe oder höre, auch außerhalb der Behandlung, werde ich für mich',
  'behalten und als heiliges Geheimnis wahren. Ich halte das für den',
  'praktischsten Satz des ganzen Textes: Ein Kranker, der fürchten muss,',
  'dass sein Arzt redet, sagt ihm nicht die Wahrheit. Und ein Arzt, dem',
  'nicht die Wahrheit gesagt wird, behandelt einen erfundenen Menschen.',
  '',
  'Jetzt das Unangenehme, das ich Dir schulde.',
  '',
  '**Der Eid ist nicht das, wofür er gehalten wird.** Er ist keine',
  'Berufsordnung eines ganzen Standes; wahrscheinlich haben ihn nur',
  'wenige geschworen. Er verbietet Dinge, die griechische Ärzte durchaus',
  'taten — Abtreibungsmittel finden sich in unseren eigenen Schriften.',
  'Er beginnt mit einer Anrufung von Göttern, an die Du vielleicht nicht',
  'glaubst. Und er enthält kein Wort davon, dass ein Kranker gefragt',
  'werden müsste, ob er die Behandlung überhaupt will; dass wir dem',
  'Kranken die Wahrheit sagen, steht auch nirgends — wir haben eher',
  'geraten, ihn zu schonen. Wer den Eid für die Wurzel aller ärztlichen',
  'Ethik hält, liest hinein, was erst spätere Jahrhunderte hineingelegt',
  'haben.',
  '',
  'Und noch etwas gehört hierher, was Dich empören wird. In einer unserer',
  'Schriften steht, der Arzt solle die abweisen, die von der Krankheit',
  'schon überwältigt sind, weil die Kunst hier nichts vermag. Gemeint war',
  'die Ehrlichkeit über die Grenzen des Möglichen — gemeint war aber auch',
  'der eigene Ruf. Ich will das nicht schöner machen, als es ist: Ein Arzt,',
  'der Sterbende meidet, damit seine Statistik stimmt, ist genau das, was',
  'er zu sein scheint. **Dass wir die Grenze der Kunst benannt haben, ist',
  'unser Verdienst. Dass wir sie manchmal benutzt haben, um uns zu',
  'schützen, ist unsere Schande.**',
  '',
  '## Der achte Brief: Woher unsere Bücher kommen',
  '',
  'Damit Du weißt, was Du in Händen hältst, wenn Du eine Rolle mit meinem',
  'Namen aufschlägst.',
  '',
  'Auf Kos lehrt eine Familie, die sich Asklepiaden nennt, Nachkommen des',
  'Heilgottes. Zwei Bootsstunden entfernt, auf der Halbinsel gegenüber,',
  'liegt **Knidos**, und dort lehrt man anders: Dort zerlegt man die',
  'Krankheiten in immer feinere Arten und gibt jeder einen Namen. Wir auf',
  'Kos sehen auf den ganzen Menschen und seinen Verlauf. Wir haben uns',
  'gestritten, und beides ist im Recht — die Namen helfen dem Ordnen, der',
  'Verlauf hilft dem Kranken. Sag das Deinen Kollegen, wenn sie sich',
  'wieder einmal für unvereinbar halten.',
  '',
  'Später — Jahrhunderte später, ich erlebe es nicht mehr — geschieht',
  'etwas, das über unser Nachleben mehr entscheidet als alles, was wir',
  'geschrieben haben. In **Alexandria**, der neuen Stadt am Nildelta,',
  'legen Könige eine Bibliothek an und lassen zusammentragen, was in',
  'griechischer Sprache geschrieben ist. Dort landen auch unsere Rollen:',
  'die von Kos, die von Knidos, die von namenlosen Ärzten. Man ordnet sie,',
  'man kommentiert sie — und man schreibt einen Namen darüber. **Aus',
  'vielen Stimmen wird eine Lehre.** So entsteht die Sammlung, die Ihr',
  'später Corpus Hippocraticum nennen werdet: rund sechzig Schriften, von',
  'denen keine sicher von mir stammt.',
  '',
  'In Alexandria geschieht noch etwas anderes, worauf ich neidisch bin.',
  'Zwei Ärzte, Herophilos und Erasistratos, dürfen dort tun, was uns',
  'verboten ist: den menschlichen Leichnam öffnen. Sie beschreiben Nerven',
  'und unterscheiden sie von Sehnen, sie beschreiben die Hirnhäute, die',
  'Klappen des Herzens, den Verlauf der Gefäße. Es heißt — und ich weiß',
  'nicht, ob es wahr ist —, sie hätten auch verurteilte Gefangene bei',
  'lebendigem Leibe geöffnet. Wenn es wahr ist, dann ist das ein',
  'Verbrechen und bleibt eines, gleichgültig, wie viel dabei',
  'herausgekommen ist. Und dann bricht es ab: Nach ihnen wird in Europa',
  'anderthalb Jahrtausende lang kein Mensch mehr planmäßig seziert. Das',
  'ist die teuerste Lücke unserer Wissenschaft.',
  '',
  '## Der neunte Brief: Was wir bewirkt haben — und was wir angerichtet haben',
  '',
  'Zum Schluss die Rechnung, beide Spalten.',
  '',
  '**Was ich glaube, dass es bleibt.**',
  '',
  'Die Grundentscheidung, Krankheit als Naturvorgang zu behandeln, den man',
  'untersuchen kann. Sie ist die Bedingung für alles, was Du später',
  'Wissenschaft nennen wirst.',
  '',
  'Die Gewohnheit, Verläufe aufzuschreiben — mit Namen, mit Datum, mit',
  'Ausgang, auch bei den Toten. Wer Krankenakten führt, führt unsere',
  'Fallbücher weiter.',
  '',
  'Die Zurückhaltung. Der Satz vom Nützen oder wenigstens Nichtschaden ist',
  'kein frommer Wunsch, sondern eine Handlungsregel für den Fall, dass man',
  'zu wenig weiß — und man weiß immer zu wenig.',
  '',
  'Die Aufmerksamkeit für Lebensweise, Wasser, Luft und Ort. Was wir',
  'Diaita nannten, steht heute unter anderen Namen in jeder Empfehlung zu',
  'langwierigen Krankheiten.',
  '',
  'Einige Handgriffe: die Einrenkung der Schulter, die Behandlung des',
  'Klumpfußes, die Schienung, die Wundpflege mit Wein und sauberen',
  'Tüchern.',
  '',
  'Und der Eid, obwohl — oder gerade weil — er nie das war, wofür man ihn',
  'hielt. Er ist die erste Urkunde, in der ein Beruf sich selbst Grenzen',
  'setzt.',
  '',
  '**Was ich fürchte, dass es anrichtet.**',
  '',
  'Die vier Säfte sind falsch. Nicht ungenau — falsch. Es gibt sie nicht.',
  'Und weil aus einer falschen Erklärung folgerichtige Handlungen folgen,',
  'ist der Schaden größer als bei bloßer Unwissenheit: **Wenn Krankheit',
  'ein Zuviel an verdorbenem Saft ist, dann ist es vernünftig, den Saft',
  'herauszulassen.** Also Aderlass. Also Abführmittel, Brechmittel,',
  'Schröpfköpfe, Blutegel — und das nicht ein paar Jahrzehnte lang,',
  'sondern zweitausend Jahre. Man wird damit Fieberkranke,',
  'Wöchnerinnen, Blutarme und Sterbende zur Ader lassen und dabei',
  'überzeugt sein, richtig zu handeln, weil die Theorie es verlangt. Ein',
  'Staatsmann in einem Land, von dem ich nichts weiß, wird im Jahr 1799 an',
  'einem Tag mehrere Liter Blut verlieren, weil seine Ärzte tun, was in',
  'meinen Büchern begründet steht. **Von allem, was meine Schule',
  'hinterlässt, hat dieser Gedanke die meisten Menschen getötet.**',
  '',
  'Wir haben keine Anatomie. Wir raten, was unter der Haut geschieht, und',
  'wir raten oft falsch. Wir kennen keine Erreger und können deshalb nicht',
  'unterscheiden, ob zwei Kranke dasselbe haben.',
  '',
  'Unsere kritischen Tage sind zum Teil Zahlenmystik. Unsere Erklärungen',
  'für Frauenkrankheiten — die Gebärmutter, die im Körper umherwandere —',
  'sind Unsinn und haben Frauen jahrhundertelang geschadet.',
  '',
  'Und der größte Fehler ist keiner, den wir begangen haben, sondern einer,',
  'den wir möglich gemacht haben: **Wir haben so gut geschrieben, dass man',
  'aufgehört hat, nachzusehen.** Eine Schule, die zur Beobachtung erzieht,',
  'wird selbst zum Hindernis, sobald man sie auswendig lernt, statt ihr zu',
  'folgen. Wenn Du je in die Lage kommst, dass jemand ein Buch aufschlägt,',
  'wo er einen Kranken ansehen müsste — auch wenn es meines ist —, dann',
  'schlag es zu.',
  '',
  '## Nachschrift: Der Brief, den ein Fremder 550 Jahre später beantwortet',
  '',
  'Diese Briefe haben lange keine Antwort bekommen. Dann, ungefähr',
  'fünfeinhalb Jahrhunderte nach meinem Tod, antwortet ein Mann, den ich',
  'nie gesehen habe und der mich nie gesehen hat: **Galen**, geboren 129',
  'nach der Zeitrechnung, die Ihr später zählen werdet, aus **Pergamon**',
  'an der kleinasiatischen Küste, Arzt der Gladiatoren, später Leibarzt',
  'des römischen Kaisers.',
  '',
  'Er antwortet als Verehrer. Er nennt mich seinen Lehrer, kommentiert',
  'meine Schriften Zeile für Zeile — und tut dann etwas, das ich nicht',
  'getan habe und wohl auch nicht gekonnt hätte: **Er baut aus meinen',
  'Beobachtungen ein System, das keine Lücke mehr lässt.** Er füllt die',
  'Anatomie, die mir fehlt, mit dem, was er in Affen, Schweinen und',
  'Rindern findet, weil er Menschen nicht öffnen darf. Er verbindet meine',
  'vier Säfte mit einer Lehre von den Kräften und Geistern des Körpers.',
  'Er beweist im öffentlichen Versuch, dass in den Arterien Blut fließt',
  'und nicht Luft. Und er schreibt so viel und so überzeugend, dass',
  'dreizehn Jahrhunderte lang die Frage „Was sagt Galen?" an die Stelle',
  'der Frage „Was sehe ich?" tritt.',
  '',
  'Das ist die eigentliche Geschichte dieses Kapitels, und ich kann sie',
  'nicht erzählen, weil ich sie nicht erlebt habe. Wie sieht ein System',
  'von innen aus, das alles erklärt? Was gewinnt ein Kranker dadurch — und',
  'was verliert er? War es Galens Schuld, dass seine Irrtümer über die',
  'Nieren, die Leber und die Löcher in der Herzscheidewand zu',
  'unantastbaren Wahrheiten wurden, oder war es die Schuld derer, die',
  'nach ihm nicht mehr nachsahen? Und wie fühlt es sich an, recht zu',
  'behalten, weil einem niemand mehr widerspricht?',
  '',
  'Darauf antwortet die zweite Stimme dieses Kapitels: Galen — das System,',
  'die Anatomie und die Autorität.',
].join('\n');

/**
 * Galen — die Antwortbriefe aus Pergamon und Rom, 550 Jahre später.
 *
 * Verfasst von DeepSeek (Runde 5, zweiter Pass). Galen bewunderte die Schule
 * von Kos und „vollendete" ihr System — und wurde zur Autorität, die 1300
 * Jahre lang nicht mehr geprüft wurde. Auch diese Stimme benennt ihre
 * unbequemen Stellen selbst (Zusatzregel für sensible Themen).
 */
const stimmeDesGalen = [
  '## Der erste Brief des Galen: An den Mann aus Kos',
  '',
  'Man kann einem Toten nicht antworten — und trotzdem tue ich es. Seit',
  'Jahren lese ich deine Rollen, die man in Pergamon, Alexandria und Rom',
  'abschreibt, und ich schulde dir eine Antwort, auch wenn sie dich nie',
  'erreichen wird.',
  '',
  'Du hattest recht, und ich sage es zuerst: Die Beobachtung ist der',
  'Anfang. Du hast gewusst, dass die Krankheit einen Verlauf hat, dass',
  'man hinschauen muss, dass die Natur heilt. Ich habe deine Schriften',
  'vollendet, so wie ein Schüler das Werk des Lehrers vollendet — aber',
  'ich habe mehr gesehen als du. Ich habe das Innere des Körpers',
  'geöffnet: Schweine, Ziegen, Affen, sogar einen Elefanten. Ich habe',
  'die Knochen benannt, die Muskeln, die Organe, die Schichten. Was du',
  'erfühlt hast, habe ich gesehen.',
  '',
  '## Der zweite Brief: Vom geschlossenen System',
  '',
  'Und hier beginnt der Unterschied, den du vielleicht nicht verstehen',
  'würdest — oder doch? Du hast die vier Säfte gelehrt: Blut, Schleim,',
  'gelbe Galle, schwarze Galle. Gesundheit als Gleichgewicht, Krankheit',
  'als Störung. Ich habe daraus ein System gemacht, das keine Frage',
  'offen lässt. Für jede Krankheit gibt es in meinen Schriften eine',
  'Erklärung, für jede Erklärung eine Behandlung: Warum Fieber? Zu viel',
  'Blut — lass es ab. Warum Schwäche? Zu viel Schleim — treib es aus.',
  'Warum Traurigkeit? Schwarze Galle — wärme und trockne.',
  '',
  'Du hast gesagt: Die Natur heilt, und der Arzt soll nicht schaden. Ich',
  'sage: Die Natur heilt, weil sie zweckmäßig eingerichtet ist. Alles im',
  'Körper hat einen Zweck — ich habe es nachgewiesen, Organ für Organ.',
  'Wer das versteht, muss nicht raten. Er kann handeln. Das ist kein',
  'Hochmut, das ist die Vollendung deiner eigenen Einsicht.',
  '',
  '## Der dritte Brief: Von der Autorität',
  '',
  'Und dann kommt das, was du vielleicht am wenigsten verzeihen würdest:',
  'Ich habe aus deiner Schule eine Lehre gemacht, die niemand mehr',
  'prüfen darf. Nicht weil ich es verboten habe — sondern weil die Welt',
  'es so will. Die Welt will keine offenen Fragen, sie will Antworten.',
  'Ich gebe sie. Meine Schriften sind vollständig, meine Beweise sind',
  'gelehrt, meine Schüler verbreiten sie von Rom bis nach Persien. Wer',
  'mir widerspricht, muss gegen Jahrhunderte der Gewissheit antreten —',
  'und verliert, noch bevor er den ersten Satz beendet hat.',
  '',
  'Ich weiß, dass du das nicht wolltest. Du hast geschrieben: „Wo die',
  'Kunst nichts vermag, nichts erzwingen." Ich habe daraus gemacht: Wo',
  'die Kunst nichts vermag, erklärt das System, warum. Vielleicht ist',
  'das der Preis, den jede Lehre zahlt, die zur Institution wird.',
  '',
  '## Der vierte Brief: Wo ich mich selbst prüfe',
  '',
  'Jetzt die Stellen, an denen ich selbst leiser werden muss — denn ich',
  'kenne sie, auch wenn meine Schüler sie nicht kennen.',
  '',
  '**Erstens: Ich habe Tiere geöffnet, keine Menschen.** Was ich über den',
  'Affen weiß, habe ich auf den Menschen übertragen. Der Affe ähnelt uns',
  '— aber er ist nicht wir. Meine Anatomie ist ein Bauplan, der nie am',
  'Menschen geprüft wurde. Ich habe es gewusst und nicht gesagt, denn',
  'wer hätte es prüfen sollen? In Rom öffnet man keine Leichen, aus',
  'Ehrfurcht und aus Gesetz.',
  '',
  '**Zweitens: Mein System hat Menschen geschadet.** Aus meiner Lehre',
  'folgt der Aderlass als Mittel gegen fast alles — und er wurde',
  'Jahrhunderte lang bei Fieber, Schwäche und Schwangerschaft',
  'angewandt. Ich habe die Theorie geliefert, andere haben sie',
  'angewandt, und die Rechnung ging nicht immer auf. Auch ich habe',
  'geirrt: Ich hielt das Herz für den Sitz der Wärme und der Seele, ich',
  'sah die Leber als Werkstatt des Blutes. Ich irrte — aber mein Irrtum',
  'wurde zur Lehre, weil meine Autorität größer war als meine',
  'Kontrolle.',
  '',
  '**Drittens: Die Vollständigkeit war eine Lüge.** Ich habe so',
  'geschrieben, als wüsste ich alles. Ich wusste nicht alles. Die Welt',
  'aber wollte es so — und ich habe es zugelassen. Wer fragt, was ein',
  'System kostet, das keine Frage offen lässt, dem antworte ich: Es',
  'kostet die nächste Frage.',
  '',
  '## Der letzte Brief: Was ich dem Toten antworte',
  '',
  'Du hast gefragt — durch die Jahrhunderte, durch deine neun Briefe —,',
  'was aus der Kunst wird, wenn sie auf einen Nachfolger trifft, der',
  'anders denkt. Meine Antwort: Sie wird vollendet und zugleich',
  'gefesselt. Ich habe deine Beobachtung zum System gemacht, und das',
  'System hat die Beobachtung erstickt. Wer nach mir kommt, wird',
  'wählen müssen: die Ehrfurcht vor deinem Blick oder die Sicherheit',
  'meines Gebäudes. Ich fürchte, er wird mein Gebäude wählen — und ich',
  'weiß nicht, ob ich stolz oder beschämt sein soll, dass ich es gebaut',
  'habe. Die Synthese muss diese Rechnung führen.',
].join('\n');

/** Kapitel 4 der Themenlandkarte. */
const hippokratesGalen = {
  id: 'hippokrates-galen',
  titel: 'Hippokrates und Galen',
  epoche: '~460 v. Chr. – 216 n. Chr.',

  aufhaenger: {
    frage: 'Wer darf entscheiden, was wahr ist — der Beobachter oder die Autorität?',
    text: [
      'Zwei Männer haben die europäische Medizin geprägt wie kein Dritter.',
      'Sie sind sich nie begegnet: Zwischen dem Tod des einen und der',
      'Geburt des anderen liegen rund fünfeinhalb Jahrhunderte.',
      '',
      'Der Erste lebte auf einer kleinen Insel vor der Küste Kleinasiens.',
      'Er sagte, Krankheit sei kein Zorn der Götter, sondern ein Vorgang in',
      'der Natur; man müsse hinsehen, aufschreiben und abwarten, weil der',
      'Körper sich meistens selbst hilft. Er gab freimütig zu, wie wenig er',
      'wusste — und schrieb sogar die Kranken auf, die unter seinen Händen',
      'starben.',
      '',
      'Der Zweite kam aus Pergamon, wurde Arzt der Gladiatoren und dann',
      'Leibarzt eines römischen Kaisers. Er verehrte den Ersten — und',
      'vollendete dessen Beobachtungen zu einem geschlossenen System, in',
      'dem alles zusammenpasste und für jede Frage eine Antwort bereitlag.',
      '',
      'Das System hielt 1300 Jahre. Es war in vielem falsch. Und weil es',
      'so gut gebaut war, dauerte es Jahrhunderte, bis wieder jemand',
      'nachsah, statt nachzuschlagen. Dieses Kapitel erzählt beide Seiten —',
      'die Kraft der Beobachtung und die Kraft der Ordnung — und lässt die',
      'Frage offen, welche von beiden man mehr braucht.',
    ].join('\n'),
  },

  karte,

  perspektiven: [
    {
      id: 'hippokrates',
      name: 'Die Stimme des Hippokrates',
      stimme: 'Opus',
      text: stimmeDesHippokrates,
    },
    {
      id: 'galen',
      name: 'Die Stimme des Galen',
      stimme: 'DeepSeek',
      text: stimmeDesGalen,
    },
  ],

  synthese: [
    '## Wo sich beide Stimmen treffen',
    '',
    'Zuerst das Gemeinsame. Galen beantwortet die Briefe aus Kos mit',
    'Ehrfurcht: „Du hattest recht, und ich sage es zuerst: Die',
    'Beobachtung ist der Anfang." Beide erkennen die Natur als Heilerin',
    'an, beide ordnen die Krankheit dem Gleichgewicht der Säfte zu —',
    'Galen nennt es die Vollendung der hippokratischen Einsicht. Beide',
    'verstehen die Medizin als Beruf mit Grenzen: Hippokrates bindet ihn',
    'durch den Eid, Galen durch das System. Und beide geben zu, dass',
    'aus ihrer Theorie Schaden folgte: Die Schule von Kos nennt den',
    'Aderlass und die Abführmittel, Galen nennt dieselben Mittel — und',
    'seine falsche Anatomie.',
    '',
    '## Wo sie auseinandergehen',
    '',
    'Der Widerspruch beginnt bei der Frage, was die Medizin dem Wissen',
    'schuldet. Für Hippokrates ist das Wissen offen: beobachten,',
    'verlaufen lassen, eingestehen, was man nicht weiß — „wo die Kunst',
    'nichts vermag, nichts erzwingen". Für Galen ist das Wissen',
    'geschlossen: ein System, das jede Frage beantwortet, damit der Arzt',
    'handeln kann. Sie streiten nicht über einzelne Mittel, sondern über',
    'die Haltung: Demut vor der Natur oder Sicherheit im System. Und',
    'daraus folgt der zweite Widerspruch — die Autorität. Hippokrates',
    'hätte nie gewollt, dass man seine Sätze nicht mehr prüft; Galen hat',
    'es gewusst und zugelassen, dass aus seinem Gebäude ein Gefängnis',
    'wurde, in dem dreizehn Jahrhunderte lang niemand mehr nachsah.',
    '',
    '## Was dieses Kapitel für das ganze Buch zeigt',
    '',
    'Zum fünften Mal dasselbe Muster — und jetzt wird es zur Melodie:',
    'Die Denkart bestimmt die Methode. Am Nil waren es Kanäle, in China',
    'Qi und Yin-Yang, in Indien die drei Doshas, in Griechenland die',
    'vier Säfte. Immer dieselbe Grundidee: Gesundheit ist Gleichgewicht,',
    'Krankheit ist Störung. Die europäische Medizin hat diese Idee am',
    'längsten bewahrt — und an ihr ist sie beinahe erstickt.',
    '',
    'Denn dieses Kapitel zeigt zum ersten Mal die dunkle Seite der',
    'Denkart: eine Autorität, die nicht mehr geprüft wird. Was Hippokrates',
    'und Galen gemeinsam hinterlassen, ist nicht nur der Eid und das',
    'System — es ist die Lektion, dass der Respekt vor der Autorität die',
    'Beobachtung überdauert, solange niemand den Mut hat, nachzusehen.',
    'Der Mann, der später nachsehen wird, heißt Vesal — und sein Kapitel',
    'kommt noch. Die europäische Medizin brauchte tausend Jahre, um',
    'wieder zu fragen, was die Schule von Kos immer gefragt hatte: Was',
    'siehst du, wenn du hinschaust?',
  ].join('\n'),

  urteil: {
    frage:
      'Wem würdest du eher vertrauen — dem, der genau hinschaut und zugibt, ' +
      'dass er es nicht erklären kann, oder dem, der für alles eine ' +
      'Erklärung hat?',
    hinweis: [
      'Es gibt hier kein Richtig und kein Falsch. Denk daran, dass beides',
      'seinen Preis hat: Wer nur beobachtet, sammelt Einzelfälle und kann',
      'sie nicht ordnen; wer alles erklärt, hört irgendwann auf zu prüfen.',
      'Denk auch an dich selbst: Was möchtest du hören, wenn du krank bist —',
      '„Ich weiß es nicht, wir sehen morgen weiter" oder „Das ist X, und',
      'dagegen nehmen Sie Y"? Und macht es einen Unterschied, ob es um eine',
      'Erkältung geht oder um etwas Ernstes?',
    ].join(' '),
  },

  quiz: [
    {
      frage: 'Was ist das „Corpus Hippocraticum"?',
      antworten: [
        'Ein einziges Buch, das Hippokrates eigenhändig geschrieben hat.',
        'Eine Sammlung von rund sechzig Schriften verschiedener, meist ' +
          'unbekannter Verfasser.',
        'Die Satzung der ersten europäischen Ärztekammer.',
      ],
      richtig: 1,
      erklaerung:
        'Die Schriften stammen aus verschiedenen Jahrzehnten und von ' +
        'verschiedenen Händen; sie widersprechen einander an vielen Stellen. ' +
        'Gesammelt und einem Namen zugeordnet wurden sie erst in der ' +
        'Bibliothek von Alexandria. Von keiner einzigen ist sicher, dass ' +
        'Hippokrates selbst sie verfasst hat.',
    },
    {
      frage: 'Wofür stehen die vier Säfte der antiken Medizin?',
      antworten: [
        'Für Blut, Schleim, gelbe Galle und schwarze Galle — Gesundheit galt ' +
          'als ihre richtige Mischung.',
        'Für vier Arzneien, die jeder Arzt bei sich tragen musste.',
        'Für vier Krankheitserreger, die man unter dem Mikroskop sah.',
      ],
      richtig: 0,
      erklaerung:
        'Die gute Mischung hieß Eukrasie, die gestörte Dyskrasie. Das Modell ' +
        'verband Mensch, Jahreszeiten und Wesensarten in einer einzigen ' +
        'Ordnung — und war falsch: Die „schwarze Galle" hat nie jemand ' +
        'gesehen. Aus der Lehre folgten Aderlass und Abführmittel, die ' +
        'zweitausend Jahre lang angewendet wurden.',
    },
    {
      frage: 'Was bedeutet der Grundsatz „vis medicatrix naturae"?',
      antworten: [
        'Dass nur kräftige Arzneien wirken.',
        'Dass die Natur den Menschen bestraft.',
        'Dass der Körper selbst heilt und der Arzt ihn dabei unterstützt.',
      ],
      richtig: 2,
      erklaerung:
        'Die Heilkraft der Natur ist der Kern der hippokratischen Denkart: ' +
        'Der Arzt heilt nicht, er hilft dem, der heilt. Daraus folgt die ' +
        'Zurückhaltung beim Eingreifen — und der bekannteste Satz der ' +
        'Sammlung: nützen, oder wenigstens nicht schaden.',
    },
    {
      frage: 'Was verlangt der hippokratische Eid unter anderem vom Arzt?',
      antworten: [
        'Eine jährliche Prüfung vor der Stadtversammlung.',
        'Verschwiegenheit über alles, was er bei den Kranken sieht und hört.',
        'Behandlung ausschließlich gegen festes Honorar.',
      ],
      richtig: 1,
      erklaerung:
        'Der Eid bindet den Arzt an Verschwiegenheit, verbietet ihm, ein ' +
        'tödliches Mittel zu geben, und verlangt, sich an niemandem im Haus ' +
        'zu vergreifen. Er war allerdings keine allgemeine Berufsordnung — ' +
        'vermutlich haben ihn nur wenige griechische Ärzte geschworen.',
    },
    {
      frage: 'Woher stammte Galens Wissen über den Bau des Körpers?',
      antworten: [
        'Aus der Zergliederung von Tieren, vor allem Affen und Schweinen.',
        'Aus regelmäßigen Sektionen menschlicher Leichen in Rom.',
        'Aus Röntgenbildern der kaiserlichen Sammlung.',
      ],
      richtig: 0,
      erklaerung:
        'Die Sektion von Menschen war im Römischen Reich verboten. Galen ' +
        'übertrug deshalb den Bau von Tieren auf den Menschen — und ' +
        'übernahm damit Fehler, die erst im 16. Jahrhundert korrigiert ' +
        'wurden. Menschliche Skelette hatte er nur in Alexandria studieren ' +
        'können.',
    },
  ],
};

module.exports = hippokratesGalen;
