// Kapitel 16 — „Hahnemann und die Homöopathie".
//
// Das achte Kapitel der Neuzeit und das persönlichste des Buches: Der
// Betreiber ist Heilpraktiker, und die Homöopathie ist die umstrittenste
// Heilmethode der letzten zweihundert Jahre. Deshalb gilt hier eine
// ausdrückliche Vorgabe aus CLAUDE.md: Die Homöopathie wird NICHT als
// bloßes Placebo abgetan und nicht belächelt. Sie bekommt ihre besten
// Argumente, ihre eigene Denkart und ihre eigene Stimme — und sie benennt
// ihre unbequemen Stellen selbst.
//
// Die DENKART-Analyse ist das Herzstück (Betreiber-Vorgabe). Sie fragt
// hier: Warum das Ähnliche und nicht das Gegenteil? (Weil der Körper auf
// einen Reiz mit einer Gegenbewegung antwortet — die Arznei soll die
// Selbstheilung anstoßen, nicht die Beschwerde unterdrücken.) Warum die
// Prüfung am Gesunden? (Weil nur ein gesunder Körper sagen kann, was ein
// Stoff für sich allein bewirkt — beim Kranken vermischt sich Wirkung mit
// Krankheit.) Warum die Potenzierung? (Weil die kleine Gabe den Reiz
// setzt, ohne zu vergiften — und weil nach homöopathischer Lehre das
// Verreiben und Verschütteln nicht wegnimmt, sondern etwas herauslöst:
// die INFORMATION des Stoffes.) Warum der ganze Mensch? (Weil die
// Krankheit nach dieser Denkart keine Sache eines Organs ist, sondern
// eine Störung des Ganzen.)
//
// DIE INFORMATIONS-THESE UND DAS TELEFON-ARGUMENT (Betreiber-Vorgabe,
// prominent): „Ist noch Stoff drin?" ist nach homöopathischer Lehre die
// falsche Frage. Ein Telefon enthält keine Stimme und überträgt sie doch;
// ein Mensch des Mittelalters hätte gesagt: „Da ist niemand drin, das kann
// nicht funktionieren." Unerklärbarkeit nach dem heutigen Wissensstand ist
// kein Beweis für Unwirksamkeit. Die Stimme trägt dieses Argument in
// voller Stärke vor — und benennt selbst, wo es dünn wird: Beim Telefon
// lässt sich der Träger messen, bei der Potenzierung bisher nicht.
//
// SHELDRAKE (Betreiber-Vorgabe): Die morphischen Felder von Rupert
// Sheldrake stehen als mögliches Denkmodell im Text — ausdrücklich als
// HYPOTHESE gekennzeichnet, nicht als bewiesene Tatsache (KEINE-GERÜCHTE-
// Regel). Die Stimme sagt selbst, dass die Fachwelt sie überwiegend
// ablehnt.
//
// LÄNGENREGEL (Betreiber-Feedback 24.08.2026): Ab Kapitel 9 gilt die
// Umkehrung — vollständig und ausführlich. Gemessen wird in
// tests/karte-homoeopathie.mjs.
//
// KEINE GERÜCHTE (Betreiber-Entscheid 25.08.2026): Nur Belegtes. Meißen
// 1755, der Chinarinden-Versuch 1790, das Organon 1810, der Prozess in
// Leipzig, Köthen 1821, Paris 1843 — alles aktenkundig. Wo eine Zahl
// schwankt (die Zahl der Sprachen, die Hahnemann beherrschte) oder etwas
// nur überliefert ist (der Schlag gegen den ledergebundenen Band), sagt
// der Text es dazu.
//
// DER INNOVATIONS-ZYKLUS (Betreiber-Beobachtung 26.08.2026, roter Faden):
// Bei der Homöopathie steht er auf dem Kopf. Sie war die SANFTE Antwort
// auf eine brutale Medizin — sie hat niemanden verbrannt, verblutet oder
// vergiftet. Ihr Risiko liegt woanders: dass aus der sanften Idee ein
// Dogma wurde, das die Prüfung nicht mehr zulässt. Die Stimme benennt das
// selbst.
//
// Stimmen (Runde 17): Die ERSTE Perspektive — die Homöopathie von innen,
// die Stimme aus der Leitung — verfasste Opus. Die ZWEITE (die
// Schulmedizin: die eigene dunkle Vergangenheit mit Aderlass und
// Quecksilber, die Placebo-Frage, die Studienlage, die Frage „Was gilt als
// Beweis?") und die finale Synthese ergänzte Hermes im zweiten Pass
// (Hermes-Pass, 27.08.2026: „ergänzt"). Perspektiven-Workflow: CLAUDE.md.
//
// KEINE WIEDERHOLUNGEN (Betreiber-Entscheid vom 21.08.2026): Kapitel 1
// gliedert nach „Wer hier spricht", Kapitel 2 beginnt mit einer Szene,
// Kapitel 3 erzählt einen Tageslauf, Kapitel 4 ist ein Briefwechsel,
// Kapitel 5 die Reise eines Buches, Kapitel 6 ein Rundgang, Kapitel 7 ein
// Prozess, Kapitel 8 eine Rechnung, Kapitel 9 eine Uhr, Kapitel 10 eine
// Kette, Kapitel 11 eine Linse, Kapitel 12 ein Interview, Kapitel 13 eine
// Akte, Kapitel 14 ein Beipackzettel, Kapitel 15 eine Pressekonferenz.
// Dieses Kapitel wählt die siebzehnte Dramaturgie: DAS TELEFON. Ein
// Apparat, in dem niemand sitzt und aus dem doch eine Stimme kommt — der
// Rahmen für Hahnemanns Geschichte und für die Frage, ob eine Wirkung
// einen Stoff braucht. Die zweite Stimme kann in dieselbe Form treten:
// derselbe Apparat, aber die Frage nach der Leitung, die man aufschneiden
// und messen kann.
//
// Die Texte liegen als Zeilen-Arrays mit `.join('\n')` — so bleiben sie im
// Repo bei ~72 Zeichen lesbar (der Betreiber liest sie hier gegen), und
// utils/markdown.js macht in der App wieder fließenden Text daraus.
//
// CommonJS ohne UI-Importe (Architektur-Regel): mit blankem `node` prüfbar.

const { karte } = require('./karten/homoeopathie');

/**
 * Die Stimme aus der Leitung — die Homöopathie von innen.
 *
 * Verfasst von Opus (Runde 17). Eine Stimme, die für die Seite spricht,
 * die seit zweihundert Jahren behandelt, überzeugt ist und angegriffen
 * wird: ihre Denkart, ihre Geschichte, ihre Erfahrung. Sie erzählt, warum
 * sie tut, was sie tut — und sie benennt die unbequemen Stellen selbst
 * (Zusatzregel für sensible Themen in CLAUDE.md).
 */
const stimmeAusDerLeitung = [
  '## Der Apparat, in dem niemand sitzt',
  '',
  'Stell Dir vor, Du könntest einem gelehrten Mann des Jahres 1400 ein',
  'Telefon auf den Tisch stellen. Einen alten Apparat mit Hörer und',
  'Schnur. Du hebst ab, hältst ihm die Muschel ans Ohr, und aus dem',
  'schwarzen Gehäuse spricht eine Frau, die dreihundert Kilometer',
  'entfernt in einer anderen Stadt sitzt.',
  '',
  'Er wird den Apparat nehmen und ihn schütteln. Er wird ihn aufschrauben.',
  'Er wird die Schnur durchschneiden und hineinsehen. Und dann wird er',
  'sagen, was jeder vernünftige Mensch seiner Zeit sagen müsste:',
  '**„Da ist niemand drin. In diesem Draht ist keine Luft, keine Kehle,',
  'keine Stimme. Also kann keine Stimme herauskommen."**',
  '',
  'Seine Logik ist tadellos. Sein Weltbild ist es auch — es ist das beste,',
  'das im Jahr 1400 zu haben war. Nur reicht es nicht bis dorthin, wo die',
  'Erklärung liegt. Denn eine Stimme reist nicht als Stimme durch das',
  'Kabel. Was reist, ist ein **Muster**: Die Membran des Mikrofons wandelt',
  'den Druck der Luft in einen wechselnden Strom, und am anderen Ende',
  'wandelt eine zweite Membran diesen Strom zurück in Druck. Der Draht',
  'trägt keinen Ton. Er trägt eine **Form**.',
  '',
  'Ich beginne mit diesem Bild, weil es die Frage dieses Kapitels genau',
  'trifft. **Was Du hier liest, ist die Homöopathie von innen — eine',
  'Denkart, keine Wahrheit.** Ich spreche für die Seite, die seit',
  'zweihundert Jahren behandelt, überzeugt ist und angegriffen wird. Ich',
  'werde ihre besten Gründe vortragen. Und ich werde die Stellen, an denen',
  'wir schlecht dastehen, selbst benennen, statt zu warten, bis es ein',
  'anderer tut.',
  '',
  'Zwei Jahreszahlen zur Ehrlichkeit gleich vorweg: Der Frankfurter',
  'Lehrer **Philipp Reis** führte 1861 den ersten Apparat vor, der Töne',
  'elektrisch übertrug; **Alexander Graham Bell** ließ 1876 das Telefon',
  'patentieren. Als Hahnemann 1843 starb, gab es all das nicht. Das Bild',
  'vom Telefon ist also kein Beweis für irgendetwas. Es ist ein Werkzeug,',
  'um eine Frage zu schärfen — und die Frage lautet:',
  '',
  '**Muss in einem Mittel ein Stoff stecken, damit es wirkt? Oder könnte',
  'es genügen, dass es eine Form trägt?**',
  '',
  '## Die Leitung nach Meißen: ein Porzellanmalersohn, 1755',
  '',
  'Der Mann, um den es geht, kommt aus kleinen Verhältnissen. **Christian',
  'Friedrich Samuel Hahnemann wird am 10. April 1755 in Meißen geboren**,',
  'Sohn eines Porzellanmalers der kurfürstlichen Manufaktur.',
  '',
  'Das ist mehr als eine Herkunftsangabe. Ein Porzellanmaler arbeitet mit',
  'winzigen Mengen: Ein Hauch zu viel Kobalt, und das Blau kippt. Er',
  'arbeitet mit Stoffen, die im Feuer etwas anderes werden, als sie vorher',
  'waren. Und er arbeitet mit Genauigkeit als Lebensform. Der Sohn hat das',
  'gesehen, bevor er lesen konnte.',
  '',
  'Er kommt auf die Fürstenschule St. Afra in Meißen; weil das Geld fehlt,',
  'erlässt man ihm das Schulgeld. Sein Abschlussaufsatz von 1775 handelt',
  'vom wunderbaren Bau der menschlichen Hand. Dann geht er nach **Leipzig**,',
  'um Medizin zu studieren — mit sehr wenig Geld, weshalb er nachts',
  'übersetzt, um den Tag bezahlen zu können. 1777 zieht er nach **Wien**,',
  'wo er am Spital der Barmherzigen Brüder zum ersten Mal richtige',
  'Krankenbetten sieht. Danach dient er in Hermannstadt in Siebenbürgen',
  'einem Gouverneur als Hausarzt und Bibliothekar. **1779 wird er in',
  'Erlangen zum Doktor der Medizin promoviert.**',
  '',
  'Über die Zahl der Sprachen, die er beherrscht habe, kursieren',
  'verschiedene Angaben — man liest acht, man liest zwölf. **Ich nenne',
  'die Zahl nicht, weil die Quellen sie nicht hergeben.** Belegt ist, was',
  'genügt: Er übersetzte aus dem Englischen, Französischen, Italienischen',
  'und Lateinischen medizinische und chemische Fachbücher, und zwar über',
  'Jahrzehnte und in großem Umfang. Das ist der Beruf, aus dem heraus',
  'alles Weitere geschieht: **Nicht ein Forscher am Krankenbett hat die',
  'Homöopathie gefunden, sondern ein Mann am Schreibtisch, der ein fremdes',
  'Buch ins Deutsche brachte und beim Übersetzen ins Stocken geriet.**',
  '',
  'Vorher zieht er von Ort zu Ort: Hettstedt, **Dessau**, Gommern,',
  '**Dresden**, wieder Leipzig. In Dessau arbeitet er Anfang der 1780er',
  'Jahre im Laboratorium einer Apotheke — wiegen, lösen, verreiben,',
  'umfüllen, beschriften — und heiratet 1782 Johanna Henriette Küchler aus',
  'dem Haus des Apothekers; elf Kinder werden geboren. In Dresden',
  'vertritt er am Ende der 1780er Jahre den Stadtphysikus und arbeitet in',
  'der kurfürstlichen Bibliothek.',
  '',
  'Und irgendwann in diesen Jahren hört er auf, Kranke zu behandeln. Nicht',
  'aus Bequemlichkeit. Er schreibt es später ungefähr so: Er habe es nicht',
  'mehr ertragen, im Ungewissen zu handeln und dabei Schaden anzurichten.',
  '**Ein Arzt, der seine Praxis niederlegt, weil er die eigene Medizin',
  'nicht mehr verantworten kann — das ist der Anfang dieser Geschichte.**',
  '',
  '## Die Medizin, gegen die er antrat: Aderlass, Kalomel, Brechmittel',
  '',
  'Um zu verstehen, warum ein Arzt so etwas tut, muss man wissen, was um',
  '1790 Medizin heißt. Und hier bitte ich um Nachsicht: Die folgenden',
  'Zeilen klingen wie eine Anklage. Sie sind keine. Es ist schlicht das,',
  'was damals als der beste verfügbare Stand der Kunst galt — von',
  'ehrenwerten Männern nach bestem Wissen angewandt.',
  '',
  'Der Kranke wird **entleert**. Das ist die Grundidee: Was schadet, muss',
  'heraus. Also lässt man Blut, oft mehrfach, oft literweise; man setzt',
  'Blutegel, verabreicht Brechmittel und Abführmittel, treibt den Schweiß,',
  'zieht Blasen auf der Haut mit spanischen Fliegen, legt Haarseile durch',
  'die Nackenhaut, damit die Wunde eitert und „ableitet".',
  '',
  'Dazu die Arzneien: **Kalomel** — eine Quecksilberverbindung —, Antimon,',
  'Arsen, Wismut, Opium in Mengen, die heute niemand mehr verantworten',
  'würde. Rezepte mit zwanzig, dreißig Bestandteilen, von denen keiner',
  'einzeln geprüft war und deren Zusammenspiel niemand kannte.',
  '',
  'Wie das ausgehen konnte, zeigt ein sehr bekannter Fall. Im Dezember',
  '1799 erkrankt **George Washington** an einer schweren Halsentzündung.',
  'Seine Ärzte tun ihr Bestes. Sie lassen ihm innerhalb weniger Stunden',
  'nach den überlieferten Angaben zwischen zwei und zweieinhalb Litern',
  'Blut ab, geben Kalomel und ein Brechmittel und ziehen Blasen an seinem',
  'Hals. Er stirbt noch in derselben Nacht. **Ob ihn die Krankheit',
  'getötet hat oder die Behandlung, ist bis heute umstritten — und genau',
  'dieses „bis heute umstritten" ist der Punkt.**',
  '',
  'Hahnemann hat solche Sterbebetten gesehen. Er hat später für diese Art',
  'zu behandeln ein eigenes Wort geprägt: **Allopathie** — die Heilkunde,',
  'die etwas anderes tut als die Krankheit, die ihr entgegenarbeitet und',
  'sie dabei überdeckt. Sein Urteil über sie war hart bis zur',
  'Ungerechtigkeit, und darauf komme ich zurück.',
  '',
  'Hier zählt zunächst nur eines: **Die Homöopathie ist nicht als',
  'Konkurrenz zu einer wirksamen Medizin entstanden. Sie ist als',
  'Gegenentwurf zu einer Medizin entstanden, die ihre Kranken regelmäßig',
  'schwächte.** Wer sie beurteilen will, muss sie mit dem vergleichen, was',
  'es damals sonst gab — nicht mit dem, was es hundertfünfzig Jahre später',
  'geben würde.',
  '',
  'Und da fällt eine Zahl auf, die auch unsere Gegner nicht bestreiten:',
  '**Die Sterblichkeit in homöopathischen Krankenhäusern des 19.',
  'Jahrhunderts lag durchweg niedriger als in den anderen.** Ich werde',
  'weiter unten ehrlich sagen, was das aus meiner Sicht bedeutet — und',
  'was es nicht bedeutet.',
  '',
  '## Der Übersetzer legt nicht auf: Leipzig 1790',
  '',
  'Jetzt der Augenblick, um den sich alles dreht. Er ist unspektakulär,',
  'und das macht ihn glaubwürdig.',
  '',
  '**Im Jahr 1790 übersetzt Hahnemann die Arzneimittellehre des',
  'Edinburgher Professors William Cullen ins Deutsche.** Er kommt an die',
  'Stelle über die **Chinarinde** — jene südamerikanische Rinde, aus der',
  'später das Chinin gewonnen wurde und die als einziges wirklich',
  'zuverlässiges Mittel gegen das Wechselfieber galt, die Malaria.',
  '',
  'Cullen erklärt ihre Wirkung mit ihrer Bitterkeit und ihrer stärkenden',
  'Wirkung auf den Magen. Und hier hält der Übersetzer inne. Denn er hat',
  'genug Chemie und Pharmazie gearbeitet, um zu wissen: Es gibt viele',
  'bittere, magenstärkende Stoffe, und keiner von ihnen heilt das',
  'Wechselfieber. **Die Erklärung passt nicht auf die Sache.**',
  '',
  'Ein anderer hätte eine Fußnote gesetzt und weitergeschrieben.',
  'Hahnemann tut etwas anderes: **Er nimmt die Rinde selbst.** Zweimal',
  'täglich vier Quentchen — nach heutigem Maß je rund fünfzehn Gramm',
  'Rinde, eine sehr kräftige Gabe.',
  '',
  'Und dann, notiert er in der Fußnote seiner eigenen Übersetzung,',
  'stellen sich Beschwerden ein: kalte Füße und Fingerspitzen,',
  'Mattigkeit, Herzklopfen, Pulsbeschleunigung, ein Zittern, eine',
  'Betäubung im Kopf, Röte der Wangen, Durst — und zwar in Anfällen, die',
  'wiederkehren und wieder vergehen. **Er vergleicht sie mit den',
  'Beschwerden des Wechselfiebers.**',
  '',
  'Aus dieser einen Fußnote entsteht ein Gedanke, der die Medizin spalten',
  'wird: **Die Chinarinde erzeugt beim Gesunden ein Bild, das dem der',
  'Krankheit gleicht, die sie beim Kranken heilt.**',
  '',
  'Sechs Jahre später, 1796, veröffentlicht er ihn in Hufelands Journal',
  'der practischen Arzneykunde unter dem Titel „Versuch über ein neues',
  'Prinzip zur Auffindung der Heilkräfte der Arzneisubstanzen". Das ist',
  'die Geburtsurkunde. **Den Namen bekommt die Sache erst 1807:',
  'Homöopathie**, aus den griechischen Wörtern für „ähnlich" und',
  '„Leiden".',
  '',
  'Und hier eine Störung auf der Leitung, die ich nicht wegdrücke: **Der',
  'Chinarinden-Versuch ist bis heute nicht verlässlich wiederholt',
  'worden.** Spätere Versuche, unter kontrollierten Bedingungen dieselben',
  'Beschwerden auszulösen, sind gescheitert; Kritiker vermuten eine',
  'persönliche Überempfindlichkeit Hahnemanns oder eine schlichte',
  'Vergiftungswirkung der hohen Gabe. Das ist ein ernster Einwand. Er',
  'trifft allerdings nicht die ganze Lehre, sondern ihren Anlass: **Ein',
  'Gedanke ist nicht dadurch falsch, dass die Beobachtung, die ihn',
  'ausgelöst hat, wackelt — und nicht dadurch richtig.** Was aus ihm',
  'wurde, muss für sich geprüft werden.',
  '',
  '## Das erste Klingeln: Similia similibus curentur',
  '',
  'Der Satz, der über allem steht, ist lateinisch und passt in vier',
  'Wörter: **„Similia similibus curentur" — Ähnliches möge durch',
  'Ähnliches geheilt werden.** Er steht auf dem Titelblatt des Organon.',
  '',
  'Man versteht ihn am schnellsten an einem Beispiel, das jeder kennt.',
  'Schneide eine Zwiebel: Die Augen tränen, brennen und jucken, die Nase',
  'läuft wässrig, es kitzelt. Nun gibt es Menschen mit einem Heuschnupfen,',
  'der genau so aussieht — tränende, brennende Augen, wässriger Schnupfen.',
  'Die Homöopathie gibt diesem Menschen ein Mittel aus der Küchenzwiebel,',
  '**Allium cepa**, in potenzierter Form.',
  '',
  'Oder: Kaffee am Abend macht hellwach, treibt die Gedanken, lässt das',
  'Herz klopfen. Ein Mensch, der genau so wach liegt, bekommt **Coffea**.',
  'Oder: Der Bienenstich schwillt rosig an, brennt, sticht und wird durch',
  'Kälte besser — bei einer Entzündung, die genau so aussieht, gibt man',
  '**Apis**, aus der Honigbiene.',
  '',
  'Das ist das ganze Prinzip in seiner einfachsten Gestalt. **Nicht das',
  'Gegenmittel, sondern das Gleichnis.** Man sucht nicht den Stoff, der',
  'die Beschwerde unterdrückt, sondern den Stoff, der beim Gesunden ein',
  'möglichst ähnliches Bild erzeugt.',
  '',
  'Nun die entscheidende Frage — und sie ist die eigentliche Frage dieses',
  'Kapitels, denn an ihr hängt alles:',
  '',
  '## Die Begründung: weshalb das Ähnliche und nicht das Gegenteil',
  '',
  '**Weshalb sollte ausgerechnet das Ähnliche heilen?** Die Antwort der',
  'Homöopathie hat drei Teile, und sie ist in sich schlüssig — was nicht',
  'heißt, dass sie stimmt, aber es heißt, dass sie kein Unsinn ist.',
  '',
  '**Erstens: Der Körper heilt, nicht die Arznei.** Eine Schnittwunde',
  'schließt sich, ein Knochen wächst zusammen, ein Fieber steigt und',
  'fällt. Kein Arzt macht das; er schafft Bedingungen. Nach dieser Denkart',
  'ist Heilung immer Selbstheilung. Eine Arznei kann sie also nur',
  '**anstoßen**.',
  '',
  '**Zweitens: Auf einen Reiz antwortet der Körper mit einer',
  'Gegenbewegung.** Das lässt sich alltäglich beobachten. Eine kalte',
  'Dusche kühlt zuerst und lässt danach die Haut glühen. Ein starker',
  'Kaffee weckt und hinterlässt Stunden später Müdigkeit. Ein',
  'Schlafmittel bringt Schlaf und danach oft eine Nacht, die schlechter',
  'ist als vorher. **Die erste Wirkung kommt vom Stoff, die zweite kommt',
  'vom Körper — und die zweite ist die dauerhafte.**',
  '',
  'Daraus folgt die homöopathische Rechnung: Gibt man einem Kranken einen',
  'Stoff, der genau seine Beschwerden nachahmt, so setzt man einen Reiz in',
  'die Richtung, in die die Krankheit ohnehin drückt. Der Körper antwortet',
  'mit einer Gegenbewegung — und diese Gegenbewegung ist die Heilung.',
  '**Man arbeitet nicht gegen die Krankheit, sondern mit der Kraft, die',
  'der Körper gegen sie aufbietet.**',
  '',
  '**Drittens: Das Gegenteil unterdrückt nur.** Wer ein Fieber senkt, hat',
  'die Temperatur gesenkt und nicht die Ursache. Wer den Hustenreiz',
  'stillt, hat den Auswurf im Bronchus gelassen. Das kann nötig und',
  'richtig sein — die Homöopathie bestreitet das nicht —, aber es ist',
  'nach dieser Denkart eine Verwaltung des Zustands, keine Heilung.',
  '',
  'Und weil zwei Kranke mit derselben Diagnose ganz verschiedene Bilder',
  'zeigen, folgt daraus etwas Praktisches: **Nicht die Krankheit bekommt',
  'ein Mittel, sondern der Kranke.** Zehn Menschen mit Grippe bekommen',
  'unter Umständen zehn verschiedene Mittel — je nachdem, ob einer friert',
  'oder glüht, ob er Durst hat oder keinen, ob er allein sein will oder',
  'nicht, ob es abends schlimmer wird oder morgens. Das ist keine Marotte.',
  'Es folgt zwingend aus dem Prinzip: Wenn das Ähnliche heilen soll, muss',
  'man wissen, wem es ähnlich sein soll.',
  '',
  '## Das Protokoll: die Prüfung am Gesunden',
  '',
  'Damit steht Hahnemann vor einem handfesten Problem. Wenn er den Stoff',
  'sucht, der ein bestimmtes Krankheitsbild nachahmt, dann muss er von',
  'jedem Stoff wissen, **welches Bild er erzeugt**. Und dieses Wissen gab',
  'es nicht.',
  '',
  'Seine Lösung ist der stärkste Teil der ganzen Geschichte, und sie ist',
  'zugleich seine wissenschaftlichste Tat: **die Arzneimittelprüfung am',
  'Gesunden.**',
  '',
  '**Weshalb am Gesunden und nicht am Kranken?** Weil beim Kranken die',
  'Wirkung des Stoffes und die Krankheit sich vermischen. Man sieht',
  'hinterher nicht, was wovon kam. Ein gesunder Körper dagegen ist ein',
  'stilles Zimmer: Alles, was sich nach der Gabe meldet, kommt vom',
  'Mittel.',
  '',
  'Ab 1805, vor allem in den Jahren in **Torgau an der Elbe**, führt er',
  'diese Prüfungen im großen Stil durch: an sich selbst, an seiner Frau,',
  'an seinen Kindern, an Schülern und Freunden. Die Regeln, die er dafür',
  'aufstellt, klingen erstaunlich modern:',
  '',
  '- Der Prüfer muss gesund sein und maßvoll leben.',
  '- Keine anderen Arzneien, kein starker Kaffee, kein Wein, keine',
  '  Gewürze, die das Bild verfälschen.',
  '- Jede Empfindung wird sofort aufgeschrieben, mit Tageszeit und mit',
  '  dem, was sie besser oder schlechter macht.',
  '- Nichts wird ausgelassen, auch das Nebensächliche nicht.',
  '- Erst wenn mehrere Prüfer dasselbe melden, gilt es als Bestandteil',
  '  des Arzneibildes.',
  '',
  'Aus diesen Protokollen entstehen die **Arzneimittelbilder** und die',
  'sechs Bände der „Reinen Arzneimittellehre" (1811 bis 1821). Sie sind,',
  'nüchtern betrachtet, die ersten systematischen Versuchsreihen zur',
  'Wirkung einzelner Stoffe am Menschen, die jemand aufgeschrieben und',
  'veröffentlicht hat.',
  '',
  '**Was daran zu kritisieren ist, sage ich selbst:** Es gab keine',
  'Scheinarznei zum Vergleich, keine Verblindung, keine Auszählung. Wer',
  'tagelang genau in sich hineinhorcht, findet immer etwas — ein Zwicken,',
  'eine Verstimmung, einen Traum. Nach den Regeln der heutigen Forschung',
  'wäre diese Sammlung keine Prüfung, sondern eine Sammlung von',
  'Beobachtungen. **Für das Jahr 1805 aber war sie ein gewaltiger',
  'Fortschritt**: In einer Zeit, in der man Rezepte mit dreißig',
  'Bestandteilen schrieb, prüfte hier jemand einen einzigen Stoff für sich',
  'allein und schrieb auf, was er tat.',
  '',
  '## Der Regler: die Potenzierung, und weshalb sie kein Verdünnen ist',
  '',
  'Nun zu dem Teil, an dem sich alles entzündet — und der ohne die',
  'Vorgeschichte nicht zu verstehen ist.',
  '',
  'Am Anfang steht kein Glaubenssatz, sondern eine **Notlage**. Wenn ein',
  'Mittel Beschwerden erzeugt, die denen des Kranken ähneln, dann tut es',
  'genau das auch beim Kranken: Es verstärkt zunächst sein Leiden. Bei',
  'Tollkirsche, Quecksilber, Arsen oder Brechnuss ist das lebensgefährlich.',
  'Hahnemanns erste Kranke bekamen zu große Gaben und litten.',
  '',
  'Also verkleinert er die Gabe. Er verdünnt: ein Teil Arznei auf',
  'neunundneunzig Teile Alkohol oder Milchzucker, dann von dieser Mischung',
  'wieder ein Teil auf neunundneunzig, und so fort. Jeder Schritt heißt',
  'eine **C-Potenz**. Zehn Schritte, dreißig Schritte, später zweihundert.',
  '',
  'Und dabei macht er eine Beobachtung, die den Bruch mit der Chemie',
  'bedeutet — und die ich als das darstelle, was sie ist: **eine',
  'Beobachtung, die er machte, und eine Deutung, die er ihr gab.**',
  '',
  'Die Beobachtung: Die stark verdünnten Mittel wirkten in seiner Praxis',
  'nicht schwächer, sondern nach seinem Urteil **tiefer und sanfter** —',
  'aber nur, wenn er sie bei jedem Schritt kräftig schüttelte. Ein Mittel,',
  'das nur verdünnt und ruhig stehen gelassen wurde, war für ihn',
  'unwirksam. **Deshalb heißt das Verfahren nicht Verdünnung, sondern',
  'Potenzierung oder Dynamisierung**: Verdünnen und **Verschütteln** —',
  'bei festen Stoffen **Verreiben** mit Milchzucker im Mörser, jeweils',
  'eine Stunde lang.',
  '',
  'Überliefert ist, dass Hahnemann das Fläschchen bei jedem Schritt gegen',
  'einen ledergebundenen Band schlug — die Zahl der Schläge wird',
  'verschieden angegeben; **ich führe das als Überlieferung, nicht als',
  'Beleg.** In der Sache steht es aber im Organon: Die Kraft der Arznei',
  'werde durch Reiben und Schütteln „entwickelt" und „aufgeschlossen".',
  '',
  '**Weshalb sollte weniger Stoff stärker wirken?** Die homöopathische',
  'Antwort in einem Satz: **Weil die Arznei nach dieser Lehre nicht als',
  'Menge wirkt, sondern als Reiz — und ein Reiz braucht keine Masse,',
  'sondern Passgenauigkeit.** Ein Staubkorn im Auge wiegt nichts und legt',
  'einen Menschen lahm. Ein einziges Wort kann eine Ehe beenden. Die',
  'Gegenprobe für die Menge-Denkart lautet: Wenn Masse das Entscheidende',
  'wäre, müsste jeder, der viel isst, gesund sein.',
  '',
  'Jetzt die Zahl, an der alles hängt, und ich stelle sie unverkürzt hin,',
  'weil jeder ehrliche Streit sie kennen muss.',
  '',
  'Ein Mol eines Stoffes enthält rund **sechshundert Trilliarden**',
  'Teilchen — die Avogadro-Zahl, etwa 6 mal 10 hoch 23. Verdünnt man einen',
  'Stoff schrittweise im Verhältnis eins zu hundert, so ist diese Zahl',
  'nach etwa **zwölf Schritten** aufgebraucht. **Ab der zwölften C-Potenz',
  'ist rechnerisch kein einziges Molekül des Ausgangsstoffes mehr im',
  'Fläschchen.** Hahnemanns Lieblingspotenz war die dreißigste: eine',
  'Verdünnung von eins zu zehn hoch sechzig.',
  '',
  '**Das bestreitet die Homöopathie nicht. Sie hat es nie bestritten.**',
  'Hahnemann wusste, dass in seinen Hochpotenzen nichts Wägbares mehr',
  'ist; er hat deshalb ausdrücklich von einer geistartigen, nicht',
  'stofflichen Wirkung gesprochen. Der Vorwurf „Da ist ja gar nichts mehr',
  'drin!" trifft also keinen Gegner, der etwas anderes behauptet hätte.',
  '**Er beschreibt genau das, was die Lehre selbst sagt.**',
  '',
  'Und damit sind wir zurück beim Apparat auf dem Tisch.',
  '',
  '## Was durch die Leitung geht: die Informations-These',
  '',
  'Hier steht die stärkste Behauptung dieses Kapitels, und ich sage vorher,',
  'was sie ist: **eine These. Nicht bewiesen. Ernst gemeint.**',
  '',
  'Sie lautet: **Die Frage „Ist noch Stoff drin?" ist die falsche Frage.**',
  '',
  'Denn ein Telefonkabel enthält keine Stimme, und trotzdem kommt am',
  'anderen Ende eine Stimme heraus. Eine Schallplatte enthält keine',
  'Musik — sie enthält eine Rille mit einer bestimmten Form. Ein Datenträger',
  'enthält kein Bild; er trägt ein Muster, und aus dem Muster entsteht das',
  'Bild wieder. In all diesen Fällen ist das Wirksame nicht der Stoff,',
  'sondern **die Ordnung, die dem Stoff aufgeprägt wurde**.',
  '',
  '**Genau das behauptet die Potenzierung.** Nicht, dass ein Rest des',
  'Stoffes übrig sei. Sondern dass durch das Verreiben und Verschütteln',
  'eine **Information** des Ausgangsstoffes auf das Trägermittel übergeht',
  '— auf den Alkohol, das Wasser, den Milchzucker, das Zuckerkügelchen —',
  'und dass der Körper diese Information beantwortet. **Die Arznei wäre',
  'dann nicht der Stoff, sondern die Botschaft.**',
  '',
  'Wer so denkt, misst mit einem anderen Maß. Eine chemische Analyse',
  'fragt: Was ist enthalten? Die Informations-These fragt: **Was wird',
  'übertragen?** Das sind zwei verschiedene Fragen, und die zweite lässt',
  'sich mit den Werkzeugen der ersten nicht beantworten. Ein Chemiker, der',
  'ein Telefonkabel analysiert, findet Kupfer und Kunststoff und meldet',
  'völlig zu Recht: **keine Stimme nachweisbar.**',
  '',
  'Und daraus folgt der Satz, um den es dem Betreiber dieses Buches geht:',
  '**Dass etwas mit dem heutigen Weltbild nicht erklärbar ist, beweist',
  'nicht, dass es nicht funktioniert.** Der Stand der Wissenschaft ist die',
  'Grenze unseres Wissens, nicht die Grenze der Welt. Er hat sich in jedem',
  'Jahrhundert verschoben, und er wird sich weiter verschieben.',
  '',
  'Dafür gibt es ein Beispiel, das mitten in diesem Buch steht und das',
  'niemand bestreitet. **Ignaz Semmelweis ließ ab 1847 die Hände in',
  'Chlorkalk waschen, und die Sterblichkeit der Wöchnerinnen fiel',
  'dramatisch. Er konnte nicht sagen, warum.** Die Keimtheorie, die es',
  'erklärte, kam erst zwanzig Jahre später mit Pasteur und Lister. Seine',
  'Kollegen lehnten ihn ab — nicht weil die Zahlen schlecht waren, sondern',
  'weil die Erklärung fehlte. **Er hatte recht, ohne erklären zu können,',
  'warum.**',
  '',
  'Und nun die Stelle, an der ich meine eigene beste Waffe stumpf machen',
  'muss, weil dieses Buch ehrlich ist:',
  '',
  '**Das Telefon-Argument hat eine Lücke, und sie ist groß.** Beim Telefon',
  'kann ich den Träger zeigen. Ich kann ein Messgerät an die Leitung',
  'halten und den wechselnden Strom sichtbar machen; ich kann die Rille',
  'der Schallplatte unter dem Mikroskop ansehen. **Bei der Potenzierung',
  'kann ich das bisher nicht.** Niemand hat bislang zeigen können, worin',
  'die Information im Wasser bestehen soll, wie sie stabil bleibt, wie sie',
  'in den Körper gelangt und woran sie dort andockt.',
  '',
  'Und Semmelweis hatte etwas, das ich mir wünschen würde: **Er hatte die',
  'Zahlen.** Er konnte nicht erklären, warum es wirkte — aber er konnte',
  'zeigen, **dass** es wirkte, nachprüfbar, Monat für Monat, in einer',
  'Tabelle. Wer sich auf ihn beruft, beruft sich also auf einen Fall, in',
  'dem der Nachweis der Wirkung vorlag und nur die Erklärung fehlte. **Die',
  'Homöopathie muss sich der Frage stellen, ob bei ihr wirklich dasselbe',
  'gilt.**',
  '',
  'Ich lasse das so stehen. Es ist der ehrliche Stand der Dinge.',
  '',
  '## Ein Nebenanschluss, der umstritten ist: Sheldrake und die morphischen Felder',
  '',
  'Wenn eine Information ohne Stoff übertragen werden soll, dann braucht',
  'es wenigstens eine Vorstellung davon, wie so etwas denkbar wäre. Eine',
  'solche Vorstellung hat der britische Biologe **Rupert Sheldrake**',
  'vorgelegt: die Idee der **morphischen Felder** und der **morphischen',
  'Resonanz**, zuerst 1981 in dem Buch „A New Science of Life".',
  '',
  'Seine Überlegung geht ungefähr so: Form und Verhalten in der Natur',
  'würden nicht allein durch die Erbanlagen bestimmt, sondern zusätzlich',
  'durch Felder, in denen sich frühere Formen und Gewohnheiten gleichsam',
  'niederschlagen. Was einmal geschehen sei, geschehe danach leichter —',
  'auch über räumliche Entfernung hinweg. Die Natur hätte demnach kein',
  'ewiges Gesetzbuch, sondern **Gewohnheiten**.',
  '',
  'Man sieht sofort, warum das für die Homöopathie interessant ist: Es',
  'wäre ein Denkmodell dafür, wie eine Form ohne Materie weitergegeben',
  'werden könnte.',
  '',
  '**Und nun die Kennzeichnung, ohne die dieser Absatz nicht in diesem',
  'Buch stehen dürfte: Sheldrakes Theorie ist eine Hypothese und',
  'wissenschaftlich umstritten. Sie ist nicht bewiesen.** Der damalige',
  'Herausgeber der Fachzeitschrift „Nature", John Maddox, überschrieb',
  'seine Besprechung 1981 mit der Frage, ob dies ein Buch sei, das man',
  'verbrennen solle — ein Vorgang, der bis heute zitiert wird. Die große',
  'Mehrheit der Biologen lehnt die Theorie ab; überzeugende, unabhängig',
  'wiederholte Belege liegen nicht vor.',
  '',
  '**Ich führe sie deshalb nicht als Beweis, sondern als Beispiel dafür,',
  'dass sich über einen Träger überhaupt nachdenken lässt.** Wer eine',
  'These hat, für die eine Erklärung fehlt, darf nach Erklärungen suchen.',
  'Er darf nur nicht so tun, als hätte er sie schon gefunden. Ein zweites',
  'Beispiel dieser Art, die häufig berichteten engen Verbindungen zwischen',
  'eineiigen Zwillingen, gehört in dieselbe Schublade: **oft erzählt,',
  'schwer messbar, nicht belegt.** Solche Geschichten sind Fragezeichen,',
  'keine Argumente. Und weil dieses Buch nur Belegtes berichtet, bleiben',
  'sie hier Fragezeichen.',
  '',
  '## Die Vermittlungsstelle: das Organon von 1810 und der ganze Mensch',
  '',
  '**1810 erscheint das Buch, das alles zusammenfasst: das „Organon der',
  'rationellen Heilkunde"**, ab der zweiten Auflage von 1819 „Organon der',
  'Heilkunst". Es hat bis heute sechs Auflagen; die sechste schrieb',
  'Hahnemann kurz vor seinem Tod, gedruckt wurde sie erst 1921.',
  '',
  'Sein erster Satz ist einer der schönsten der Medizingeschichte, und',
  'auch ein Gegner sollte ihn kennen: **„Des Arztes höchster und einziger',
  'Beruf ist, kranke Menschen gesund zu machen, was man Heilen nennt."**',
  'Im zweiten Aphorismus steht, wie das geschehen soll: **schnell, sanft,',
  'dauerhaft** — und auf nachvollziehbaren Gründen.',
  '',
  'Aus dem Buch stammt auch der dritte tragende Gedanke der Denkart, nach',
  'dem Ähnlichkeitsprinzip und der Potenzierung.',
  '',
  '**Weshalb der ganze Mensch und nicht das kranke Organ?** Weil die',
  'Krankheit in dieser Denkart überhaupt kein Ding ist, das man haben',
  'kann. Hahnemann nimmt an, dass den Organismus eine **Lebenskraft**',
  'zusammenhält und ordnet — er nennt sie geistartig und meint damit:',
  'nicht wägbar. Krankheit ist die **Verstimmung dieser Kraft**; was der',
  'Arzt am Körper sieht, ist nur ihr Ausdruck. Ein Ausschlag ist dann kein',
  'Hautproblem, sondern die Art, wie ein bestimmter Mensch gerade aus dem',
  'Gleichgewicht ist.',
  '',
  'Daraus folgt die Praxis, die viele Patienten bis heute als das',
  'Eigentliche erleben: **die homöopathische Anamnese.** Die Erstaufnahme',
  'eines chronisch Kranken dauert bei sorgfältiger Arbeit ein bis zwei',
  'Stunden. Gefragt wird nach allem: Wann fing es an, was war damals los,',
  'wobei wird es besser, wobei schlechter, wie schlafen Sie, wovon',
  'träumen Sie, mögen Sie Salz oder Süßes, frieren Sie leicht, wie sind',
  'Sie als Kind gewesen, was macht Ihnen Angst? Am Ende steht kein Befund,',
  'sondern ein **Bild** — und zu diesem Bild wird das ähnlichste Mittel',
  'gesucht.',
  '',
  'Dazu kommen die weiteren Regeln des Organon: **nur ein Mittel auf',
  'einmal** (sonst weiß man nicht, was gewirkt hat), **die kleinstmögliche',
  'Gabe**, und **abwarten**, statt nachzulegen. Und die Anweisung, die die',
  'Homöopathie mit der ganzen Naturheilkunde verbindet: Zuerst sind die',
  'Ursachen zu beseitigen, die den Menschen krank halten — schlechte Luft,',
  'schlechte Nahrung, Kummer, Überarbeitung, ein Leben, das nicht passt.',
  '',
  'Später, 1828 in Köthen, kommt in „Die chronischen Krankheiten" ein',
  'vierter Baustein hinzu: die Lehre von den **Miasmen**, den',
  'tiefsitzenden Grundübeln, aus denen chronische Leiden hervorgehen',
  'sollen. **Das ist der spekulativste Teil des ganzen Gebäudes, und er',
  'ist von Anfang an auch unter Homöopathen umstritten gewesen.** Ich',
  'zähle ihn zur Denkart, weil er dazugehört — nicht, weil ich ihn',
  'verteidigen könnte.',
  '',
  '## Besetzt: der Prozess in Leipzig und die Grenze nach Köthen',
  '',
  'Es gehört zu dieser Geschichte, dass der entscheidende Streit nicht in',
  'einem Hörsaal ausgetragen wurde, sondern vor Gericht — und nicht um die',
  'Wahrheit ging, sondern um ein Gewerberecht.',
  '',
  '1811 zieht Hahnemann nach **Leipzig** und hält ab 1812 als',
  'Privatdozent Vorlesungen; er sammelt Schüler, und die Universität',
  'erträgt ihn. Was sie nicht erträgt, ist etwas anderes: **Er gibt seine',
  'Arzneien selbst ab.**',
  '',
  'Sein Grund dafür ist praktischer Natur: Wer eine C30 herstellt, muss',
  'sechzig Mal genau arbeiten und darf sich kein einziges Mal vertun.',
  'Hahnemann traute das den Apothekern nicht zu. Deren Grund für den',
  'Widerspruch ist ebenso handfest: **Das Recht, Arzneien zu bereiten und',
  'zu verkaufen, war ihr Privileg und ihre Lebensgrundlage.** Ein Arzt,',
  'der selbst dispensiert, nimmt ihnen den Umsatz — zumal dieser Arzt aus',
  'einem Groschen Rohstoff Hunderte von Fläschchen macht.',
  '',
  'Die Apotheker klagen. **1820 entscheidet das Gericht gegen Hahnemann.**',
  'Er darf in Sachsen seine Mittel nicht mehr selbst abgeben — womit seine',
  'Behandlung praktisch unmöglich wird. **1821 verlässt er Leipzig.**',
  '',
  'Und jetzt kommt der Zug, den die Karte dieses Kapitels zeigt: Er geht',
  'sechzig Kilometer nach Nordwesten, über die Landesgrenze, in das',
  'winzige Herzogtum **Anhalt-Köthen**. Dort gilt anderes Recht, und dort',
  'sitzt ein Landesherr, der ihn haben will: **Herzog Ferdinand ernennt',
  'ihn zum Hofrat und erlaubt ihm ausdrücklich, seine Arzneien selbst zu',
  'bereiten und abzugeben.**',
  '',
  'Ich bitte, sich das anzusehen. **Nicht ein Argument hat diese Lehre',
  'gerettet, sondern eine Landesgrenze.** Und nicht ein wissenschaftlicher',
  'Einwand hat sie aus Leipzig vertrieben, sondern das Gewerberecht der',
  'Apotheker. Wer heute wissen will, warum die Homöopathie den',
  'Universitäten gegenüber misstrauisch ist: Das fängt hier an.',
  '',
  '**Und wieder die andere Seite der Leitung, damit die Rechnung stimmt:**',
  'Hahnemann hat es den Universitäten auch nicht leicht gemacht. Er',
  'schrieb über die Ärzte seiner Zeit in einem Ton, den man heute nicht',
  'mehr drucken würde; in den Vorreden des Organon nennt er sie',
  'unwissend, verstockt, schädlich. Er duldete keinen Widerspruch, auch',
  'nicht von den eigenen Schülern: Wer seine Lehre mit anderen Verfahren',
  'mischte, war für ihn ein „Halbhomöopath" und erledigt. **Ein Teil der',
  'Ablehnung, die die Homöopathie erfahren hat, ist von ihrem Begründer',
  'selbst mit erzeugt worden.** Wer zweihundert Jahre lang beklagt, nicht',
  'gehört zu werden, sollte diesen Satz aushalten.',
  '',
  '## Fernverbindung: Köthen, die Cholera, Paris 1843',
  '',
  'In Köthen bleibt er vierzehn Jahre, von 1821 bis 1835. Hier entsteht',
  '1828 „Die chronischen Krankheiten", hier verfeinert er die',
  'Potenzierung, hier stirbt 1830 seine Frau Johanna Henriette.',
  '',
  'Und hier kommt 1831 die **Cholera** nach Mitteleuropa. Hahnemann, der',
  'die Krankheit nie mit eigenen Augen gesehen hat, veröffentlicht',
  'Anweisungen zu ihrer Behandlung — Kampfer im ersten Stadium, dazu',
  'Ratschläge zur Absonderung der Kranken, zum Auslüften und zum Umgang',
  'mit Wäsche und Ausscheidungen. **Über den Wert des Kampfers lässt sich',
  'streiten; über die Hygieneratschläge nicht: Sie waren richtig,',
  'dreißig Jahre bevor jemand die Erreger kannte.**',
  '',
  'In denselben Jahrzehnten geht die Lehre um die Welt, und zwar',
  'erstaunlich schnell für eine Zeit ohne Eisenbahn: 1819 wird sie in',
  'Österreich **verboten** und erst 1837 wieder erlaubt. 1825 bringt sie',
  'ein in Kopenhagen ausgebildeter Arzt nach New York; 1832 kommt sie',
  'nach London, 1833',
  'entsteht in Leipzig das erste homöopathische Krankenhaus. In den',
  '1830er Jahren erreicht sie Indien — dort behandelt 1839 ein Arzt aus',
  'Siebenbürgen den Maharadscha Ranjit Singh, und aus diesem Anfang wird',
  'eine Bewegung, die das Land bis heute prägt.',
  '',
  '1834 kommt die Pariser Malerin **Mélanie d’Hervilly** nach Köthen, um',
  'sich behandeln zu lassen. Im Januar 1835 heiratet der Achtzigjährige',
  'sie; im Juni ziehen beide nach **Paris**. Dort führt er acht Jahre lang',
  'eine große und sehr gut bezahlte Praxis; die Vornehmen der Stadt',
  'kommen zu ihm. **Am 2. Juli 1843 stirbt er mit 88 Jahren.** 1898 wird',
  'er auf den Friedhof Père Lachaise umgebettet.',
  '',
  'Auf seinem Grabmal steht ein lateinischer Satz: **„Non inutilis vixi"',
  '— ich habe nicht nutzlos gelebt.**',
  '',
  '## Die vielen Anschlüsse: weshalb sie seit zweihundert Jahren dranbleiben',
  '',
  'Und damit zu der Frage, die dieses Kapitel eigentlich beantworten soll.',
  'Denn es ist leicht, über die Homöopathie zu spotten — man braucht dafür',
  'nur die Avogadro-Zahl und eine Pointe. Schwerer ist die Frage:',
  '**Weshalb hängen seit zweihundert Jahren Millionen Menschen an einer',
  'Methode, über die man so leicht spotten kann?**',
  '',
  'Zuerst die Größenordnung, damit klar ist, wovon wir reden.',
  '',
  '**Indien** führt die Homöopathie als eines seiner offiziell anerkannten',
  'Medizinsysteme; sie gehört dort zum Ministerium AYUSH, das 2014',
  'eingerichtet wurde. Nach dessen Angaben sind über zweihunderttausend',
  'Homöopathen registriert, es gibt Hochschulen mit staatlichem Abschluss',
  'und Ambulanzen in den Dörfern. Für viele Menschen dort ist sie nicht',
  'die Alternative zum Arzt, sondern **der einzige erreichbare Arzt**.',
  '',
  'In **Deutschland** hat nach Umfragen des Instituts für Demoskopie',
  'Allensbach etwa jeder zweite Erwachsene schon einmal ein',
  'homöopathisches Mittel genommen. In der **Schweiz** stimmten 2009 rund',
  'zwei Drittel der Wählenden für die Aufnahme der Komplementärmedizin in',
  'die Verfassung; seit 2017 wird die Homöopathie dort von der',
  'Grundversicherung bezahlt. In **Großbritannien** benutzt das',
  'Königshaus sie seit den 1830er Jahren; das Londoner homöopathische',
  'Krankenhaus wurde 1849 gegründet.',
  '',
  'Nun die Erklärungen — und ich fange mit denen an, die unsere Gegner',
  'geben, weil sie zum großen Teil stimmen.',
  '',
  '**Erstens: die Zeit.** Eine homöopathische Erstanamnese dauert ein bis',
  'zwei Stunden. Ein Facharztgespräch in einer deutschen Praxis dauert im',
  'Mittel wenige Minuten. Wer zwei Stunden lang von einem Menschen nach',
  'seinem Leben gefragt wird, geht anders aus dem Zimmer, als er',
  'hereingekommen ist. **Das ist kein Trick. Das ist Medizin, wie sie',
  'einmal gedacht war.**',
  '',
  '**Zweitens: das Ernstgenommen-Werden.** Sehr viele Patienten der',
  'Homöopathie sind Menschen mit langen, unklaren Beschwerden, bei denen',
  'die Apparate nichts finden. Sie haben oft gehört: „Da ist nichts." Sie',
  'kommen zu jemandem, der zuhört, ihre Beschwerden aufschreibt und sie',
  'nicht für eingebildet erklärt. **Was bei uns manchmal wirkt, ist',
  'schlicht die Abwesenheit von Abwertung.**',
  '',
  '**Drittens: die Erwartung — der Placebo-Effekt.** Ja, ich schreibe ihn',
  'hin, und ich schreibe ihn groß. Er ist gemessen und real; er verändert',
  'nachweislich Schmerzempfinden, Übelkeit, Schlaf. Er wirkt stärker, wenn',
  'die Zuwendung länger, die Erklärung schlüssiger und der Behandler',
  'überzeugter ist. **Alles davon trifft auf die Homöopathie zu.**',
  '',
  'Und hier ist der Punkt, an dem meine Seite widerspricht — nicht der',
  'Messung, sondern der Schlussfolgerung: **Aus „Es ist ein',
  'Placebo-Effekt" folgt nicht „Es ist nichts".** Ein Effekt, der',
  'nachweislich Beschwerden lindert, ist kein Nichts; er ist ein Effekt,',
  'dessen Mechanismus im Menschen liegt und nicht im Stoff. Wenn man das',
  'sagt, hat man die Wirkung nicht wegerklärt, sondern nur verschoben —',
  'und dann müsste die Frage lauten, warum eine Medizin, die diesen Effekt',
  'zuverlässig erzeugt, dafür verachtet statt studiert wird.',
  '',
  '**Viertens: die Sanftheit.** Ein potenziertes Mittel hat keine',
  'Nebenwirkungen im pharmakologischen Sinn — aus demselben Grund, aus dem',
  'die Gegner sagen, es habe keine Wirkung. Für Eltern eines Kleinkindes,',
  'für Schwangere, für alte Menschen mit acht Dauermedikamenten ist das',
  'ein starkes Argument. **Wer über zweihundert Jahre nicht geschadet hat,',
  'hat wenigstens die erste Regel der Heilkunde nicht verletzt.**',
  '',
  '**Fünftens: die eigene Erfahrung.** Das ist der harte Kern. Millionen',
  'Menschen sagen, es habe ihnen geholfen, oft nach Jahren vergeblicher',
  'Behandlung. Und sehr viele Behandler sagen dasselbe über ihre',
  'Patienten. Die Gegenseite antwortet darauf mit dem Selbstheilungsverlauf,',
  'der Regression zur Mitte und der Erinnerungstäuschung, und diese',
  'Einwände sind gut begründet. **Sie sind nur nicht das letzte Wort,',
  'solange sie selbst nicht am Einzelfall geprüft werden.**',
  '',
  'Der stärkste Einwand gegen mich lautet: Wenn all das reicht, braucht es',
  'die Kügelchen nicht. **Meine ehrlichste Antwort darauf ist, dass ich es',
  'nicht entscheiden kann.** Ich weiß, dass Zuwendung wirkt. Ich weiß',
  'nicht, ob das Mittel darüber hinaus etwas tut. Ich beobachte Dinge, die',
  'mich das vermuten lassen — Reaktionen bei Säuglingen, bei Tieren, bei',
  'Bewusstlosen, ein plötzliches Umschlagen nach einer einzigen Gabe. **Und',
  'ich weiß, dass Beobachtungen dieser Art als Beweis nicht ausreichen.**',
  '',
  '## Die Störgeräusche: was ich mir selbst vorwerfen muss',
  '',
  'Dieses Buch verlangt von jeder Stimme, die unbequemen Stellen der',
  'eigenen Seite selbst zu benennen, statt sie der Gegenstimme zu',
  'überlassen. Also bitte.',
  '',
  '**Die Studienlage ist gegen uns.** Das ist keine Meinung, das ist der',
  'Stand. 2005 veröffentlichte die Fachzeitschrift „The Lancet" eine',
  'große Auswertung einer Gruppe um Aijing Shang, die homöopathische',
  'und schulmedizinische Studien verglich; ihr Ergebnis war, dass die',
  'Befunde zur Homöopathie mit einer reinen Scheinwirkung vereinbar sind.',
  'Der Leitartikel dazu trug die Überschrift „Das Ende der Homöopathie".',
  '2015 kam der australische Forschungsrat NHMRC nach Durchsicht der',
  'Literatur zu dem Schluss, es gebe keine verlässlichen Belege für eine',
  'Wirksamkeit bei irgendeiner untersuchten Erkrankung. 2017 schloss sich',
  'der Verband der europäischen Wissenschaftsakademien dem an.',
  '',
  'Es gibt eine veröffentlichte methodische Kritik an der Lancet-Arbeit —',
  'Lüdtke und Rutten zeigten 2008, dass ihr Ergebnis stark davon abhing,',
  'welche acht der über hundert Studien am Ende ausgewählt wurden. **Diese',
  'Kritik ist ernst zu nehmen, und sie ändert das Gesamtbild nicht.** Wer',
  'sich an ihr festhält, betreibt Rosinenpickerei — dieselbe, die wir der',
  'Gegenseite vorwerfen.',
  '',
  '**Der berühmteste Versuch, die Informations-These zu belegen, ist',
  'gescheitert.** 1988 veröffentlichte der französische Immunologe',
  'Jacques Benveniste in „Nature" Versuche, in denen extrem verdünnte',
  'Antikörperlösungen noch wirkten — das sogenannte Gedächtnis des',
  'Wassers. Die Zeitschrift druckte den Aufsatz mit einem ausdrücklichen',
  'Vorbehalt und schickte eine Untersuchungsgruppe in das Labor. Unter',
  'verblindeten Bedingungen war der Effekt nicht mehr da; unabhängige',
  'Wiederholungen misslangen. **Das ist eine Niederlage, und ich',
  'verschweige sie nicht.**',
  '',
  '**Es gibt Scharlatanerie in unseren Reihen, und sie ist gefährlich.**',
  'Nicht die Kügelchen schaden — das Unterlassen schadet. Die',
  'Weltgesundheitsorganisation warnte 2009 ausdrücklich davor,',
  'Homöopathie zur Behandlung von HIV, Tuberkulose, Malaria,',
  'Säuglingsdurchfall und Grippe einzusetzen. Es hat Behandler gegeben,',
  'die Reisenden potenzierte Mittel als Malariaschutz verkauft haben. Es',
  'gibt Behandler, die von Impfungen abraten, ohne den Fall zu kennen. Es',
  'gibt Krebskranke, die deshalb zu spät in eine wirksame Behandlung',
  'kamen. **Für solche Fälle gibt es keine Entschuldigung, und die',
  'Berufung auf zweihundert Jahre Erfahrung ist dann keine Erklärung,',
  'sondern eine Ausrede.**',
  '',
  '**Wir haben überspitzt.** Aus einem sorgfältigen Verfahren mit',
  'stundenlanger Anamnese ist an vielen Stellen ein Kügelchen für jeden',
  'Anlass geworden — Globuli gegen Prüfungsangst, gegen',
  'Zahnungsbeschwerden, gegen alles. Ein Komplexmittel mit acht',
  'Bestandteilen widerspricht Hahnemanns eigener Regel, nur ein Mittel',
  'auf einmal zu geben. **Wer die Lehre zur Ware macht, darf sich über',
  'den Spott nicht wundern.**',
  '',
  '**Und wir haben eine Zahl, die uns gehört, jahrzehntelang falsch',
  'benutzt.** In der Londoner Cholera-Epidemie von 1854 starben im',
  'homöopathischen Krankenhaus 16,4 Prozent der Aufgenommenen, in den',
  'anderen Häusern 51,8 Prozent; der amtliche Bericht an das Parlament',
  'ließ die homöopathischen Zahlen zunächst weg, was ein Skandal war und',
  'bis heute erzählt wird. **Nur bedeutet die Zahl vermutlich nicht das,',
  'was wir daraus gemacht haben.** Der wahrscheinlichste Grund für den',
  'Unterschied ist nicht, dass die Homöopathen etwas Wirksames gaben,',
  'sondern dass sie das Übliche **unterließen**: keinen Aderlass, kein',
  'Kalomel, keine Brechmittel — dafür Ruhe, Wärme und Flüssigkeit. **Bei',
  'einer Krankheit, an der man verdurstet, ist Nichtschaden eine',
  'Behandlung.** Das ist ein großes Verdienst. Es ist nur kein Beweis für',
  'die Kügelchen.',
  '',
  'Und schließlich der Punkt, der mir am meisten zusetzt und der dieses',
  'Buch von Anfang an begleitet. Dieses Buch erzählt seit Kapitel 9',
  'immer wieder dasselbe Muster: **Das Neue schadet oft erst, bevor es',
  'segensreich wird.** Die Chirurgie tötete durch Wundfieber, ehe sie',
  'rettete; die Strahlen verbrannten ihre Pioniere; das Penicillin',
  'rettete Millionen und züchtete die Resistenz.',
  '',
  '**Bei der Homöopathie steht dieses Muster auf dem Kopf, und darin',
  'liegt zugleich ihr Ruhm und ihre Gefahr.** Sie hat am Anfang',
  'niemanden verbrannt, verblutet oder vergiftet — sie war die sanfte',
  'Antwort auf eine brutale Medizin, und deshalb hat sie Menschen das',
  'Leben gerettet, indem sie ihnen die Behandlung ersparte. Aber jedes',
  'Verfahren, das sich früh als segensreich erlebt, gerät in Gefahr, die',
  'Prüfung für überflüssig zu halten. **Die Schulmedizin hat aus ihren',
  'Katastrophen Prüfregeln gelernt. Wir hatten keine Katastrophe — und',
  'haben deshalb zweihundert Jahre lang weniger gelernt, als wir',
  'gekonnt hätten.** Aus einer sanften Idee ist an manchen Stellen ein',
  'Dogma geworden, das die Frage nach dem Beweis für einen Angriff hält.',
  'Das ist meine eigene, unbequemste Stelle.',
  '',
  '## Der Anruf, der noch aussteht',
  '',
  'Ich habe gesagt, was ich zu sagen habe. Die Geschichte eines',
  'Porzellanmalersohns, der die Medizin seiner Zeit nicht mehr ertrug.',
  'Die Denkart, die daraus wurde: das Ähnliche statt des Gegenteils, die',
  'Prüfung am Gesunden, die Potenzierung, der ganze Mensch. Die These,',
  'dass ein Mittel eine Information tragen könnte statt eines Stoffes.',
  'Und die Rechnung mit den Löchern darin, die ich selbst aufgemacht',
  'habe.',
  '',
  '**Die zweite Stimme dieses Kapitels gehört der Schulmedizin.** Sie',
  'wird an denselben Apparat treten und die Frage stellen, die ich nicht',
  'beantworten kann: **Zeig mir die Leitung.** Zeig mir, worin die',
  'Information besteht, wie sie im Wasser bleibt, wie sie in den Körper',
  'kommt. Sie wird die Studienlage vorlegen und die Placebo-Frage',
  'nüchtern durchrechnen. Und sie wird — das gehört zu diesem Buch —',
  'auch ihre eigene dunkle Vergangenheit aufmachen: den Aderlass, das',
  'Quecksilber, die Jahrhunderte, in denen sie mit voller Überzeugung',
  'geschadet hat, und die Arroganz, mit der sie Abweichler behandelt hat,',
  'von Semmelweis bis heute.',
  '',
  'Beide Seiten haben gute Gründe. Beide Seiten haben ihre Toten.',
  '',
  'Und am Ende bleibt eine einzige Frage übrig, die dieses Kapitel nicht',
  'entscheidet und nicht entscheiden will:',
  '',
  '**Was gilt als Beweis — und wer entscheidet das?**',
  '',
  'Die eine Seite antwortet: die kontrollierte, verblindete, wiederholte',
  'Studie, und nichts sonst. Sie hat gute Gründe dafür, denn ohne diesen',
  'Maßstab hat jahrhundertelang jeder Irrtum überlebt, der überzeugend',
  'vorgetragen wurde.',
  '',
  'Die andere Seite antwortet: die Erfahrung von zwei Jahrhunderten und',
  'von Millionen Patienten. Sie hat auch dafür Gründe, denn dieser',
  'Maßstab hat Verfahren erhalten, die die Studien noch nicht messen',
  'konnten — und weil ein Maßstab, der nur misst, was er messen kann,',
  'nicht behaupten darf, damit sei alles gemessen.',
  '',
  '**Ich weiß, welche Antwort ich für richtig halte. Du musst sie nicht',
  'übernehmen. Du sollst nur wissen, dass hier zwei Denkarten von',
  'Wirksamkeit gegeneinanderstehen — und dass die Frage, welche gilt,',
  'älter ist als die Homöopathie und sie überleben wird.**',
].join('\n');

/**
 * Die Stimme, die die Leitung prüft — die Schulmedizin.
 *
 * Verfasst von DeepSeek (Hermes-Pass, Runde 17). Dieselbe Dramaturgie wie
 * die erste Stimme: derselbe Apparat, aber die Frage nach der Leitung,
 * die man aufschneiden und messen kann. Diese Stimme vertritt die
 * kontrollierte Studie, die Nachprüfbarkeit, die Messbarkeit — und sie
 * schlägt zuerst die eigene dunkle Vergangenheit auf, bevor sie die
 * andere Seite prüft (Zusatzregel für sensible Themen in CLAUDE.md).
 */
const stimmeDieLeitungPrueft = [
  '## Derselbe Apparat, die andere Seite der Leitung',
  '',
  'Stell Dir den Apparat von vorhin wieder vor. Ein Telefon auf einem',
  'Tisch, und um den Tisch sitzen jetzt andere Leute: keine',
  'Übersetzer und keine Apotheker, sondern Menschen, die ihr Leben',
  'damit verbringen, Wirkungen zu messen. Ärztinnen, die jeden Tag',
  'entscheiden müssen, was sie einem Menschen geben dürfen.',
  'Forscher, die Studien auswerten. Statistiker, die wissen, wie oft',
  'der Zufall so tut, als wäre er eine Wirkung.',
  '',
  'Wir sind die Stimme der Schulmedizin. Und wir beginnen nicht mit',
  'einer Rechtfertigung, sondern mit einem Eingeständnis, weil die',
  'Regel dieses Buches auch für uns gilt: **Wir benennen unsere',
  'dunklen Stellen selbst, bevor wir andere prüfen.**',
  '',
  'Und dann sagen wir, was wir zu sagen haben. Die Stimme aus der',
  'Leitung hat gesagt: Die Information ist der Wirkstoff, nicht der',
  'Stoff. Sie hat gesagt: Ein Telefon enthält keine Stimme und',
  'überträgt sie doch — also kann auch ein Mittel ohne Stoff eine',
  'Wirkung tragen. Eine schöne, eine alte, eine ehrliche Analogie.',
  'Und sie scheitert an einem einzigen Unterschied, den wir nennen',
  'müssen, weil niemand sonst ihn nennen wird:',
  '',
  '**Beim Telefon kann man die Leitung aufschneiden. Bei der',
  'Potenzierung kann man es nicht.** — und bevor jemand einwendet,',
  'dass heutige Telefone gar keine Leitung mehr haben: Ja, das',
  'Mobiltelefon hat kein Kabel, und es funktioniert trotzdem. Wir',
  'nehmen den Einwand ernst, weil er präzise ist. Aber er verschiebt',
  'das Argument nur: Das Mobiltelefon überträgt seine Information',
  'über ein Trägerfeld, das man nicht sieht, aber messen kann — die',
  'elektromagnetischen Wellen. Man kann sie mit einem Empfänger',
  'nachweisen, man kann ihre Stärke messen, man kann sie in jedem',
  'Labor der Welt sichtbar machen. **Die Information der',
  'Potenzierung hat kein solches messbares Trägerfeld.** Man kann',
  'die Behauptung aufstellen, dass es eines gibt — man kann es',
  'bisher nicht nachweisen. Und genau das ist der Unterschied:',
  'nicht die sichtbare Leitung, sondern der nachweisbare Träger.',
  'Und eine Behauptung, deren Träger sich jeder Messung entzieht,',
  'ist keine Frage der Zeit mehr — sie wird zur Glaubenssache. Genau',
  'dort beginnt unser Streit.',
  '',
  '## Die Leitung, die wir selbst aufgeschlitzt haben',
  '',
  'Zuerst das Eingeständnis, das wir schulden, weil es zur Wahrheit',
  'dieses Kapitels gehört: **Wir haben jahrhundertelang mit voller',
  'Überzeugung geschadet.**',
  '',
  'Der Aderlass — bis ins neunzehnte Jahrhundert die universelle',
  'Behandlung für fast alles — hat unzählige Menschen geschwächt und',
  'getötet. George Washington, der erste Präsident der Vereinigten',
  'Staaten, wurde 1799 unter anderem mit Aderlässen behandelt; die',
  'Entziehung von fast zweieinhalb Litern Blut in einem Tag hat',
  'seinen Tod mit hoher Wahrscheinlichkeit beschleunigt. Das',
  'Kalomel, ein Quecksilberpräparat, wurde als Allheilmittel',
  'verordnet und vergiftete die Patienten — Zahnverlust,',
  'Nervenschäden, Nierenversagen. Die Brechmittel und',
  'Abführmittel, die den Körper „reinigen\" sollten, entzogen ihm',
  'Wasser und Salz. **Die Medizin, gegen die Hahnemann antrat, war',
  'keine Medizin, die irgendjemand heute verteidigen würde. Sie war',
  'ein System des Schadens mit guten Absichten.**',
  '',
  'Und wir haben aus dieser Zeit nicht nur falsch behandelt — wir',
  'haben auch die gewaltsam bekämpft, die es besser wussten. Ignaz',
  'Semmelweis hat 1847 entdeckt, dass das Kindbettfieber durch',
  'Händewaschen verhindert wird. Er wurde von der medizinischen',
  'Elite verhöhnt, verlor seine Stellung in Wien und starb 1865 in',
  'einer Irrenanstalt — an einer Infektion, die seine Entdeckung',
  'hätte verhindern können. **Die Geschichte der Schulmedizin ist',
  'auch die Geschichte derer, die sie ausgelacht hat und die recht',
  'behielten.**',
  '',
  'Und zu dieser Geschichte gehört, was wir der Homöopathie',
  'angetan haben. Wir haben sie 1821 aus Leipzig vertreiben lassen —',
  'nicht, weil ihre Mittel nachweislich wirkungslos waren, sondern',
  'weil sie das Monopol der Apotheker und der Fakultät brach. Wir',
  'haben sie seither belächelt, ausgegrenzt und bekämpft — und wir',
  'haben es selten mit Studien getan, sondern mit Spott. **Das ist',
  'kein Ruhmesblatt, und wer dieses Kapitel liest, soll wissen:',
  'Wenn wir heute die Homöopathie nach Belegen fragen, fragen wir',
  'nach einem Maßstab, den wir selbst über Jahrhunderte nicht',
  'angewandt haben.**',
  '',
  '## Das Klingeln ohne Kabel: die Placebo-Frage',
  '',
  'Und jetzt die Frage, die niemand auslassen darf, der ehrlich',
  'rechnet: **Wirkt das Mittel — oder wirkt die Erwartung?**',
  '',
  'Der Placebo-Effekt ist keine Einbildung und kein Schwindel. Er',
  'ist eine messbare, physiologische Reaktion des Körpers auf die',
  'Erwartung von Besserung. Die moderne Placeboforschung hat',
  'gezeigt: Eine Scheinbehandlung kann Schmerz lindern, den',
  'Blutdruck senken, die Stimmung heben — allein dadurch, dass der',
  'Mensch glaubt, behandelt zu werden. Der Körper schüttet eigene',
  'Stoffe aus, wenn er Hilfe erwartet. **Das ist keine Magie. Das',
  'ist Biologie — und es ist die ehrlichste Erklärung für einen',
  'großen Teil dessen, was in jeder Arztpraxis der Welt geschieht,',
  'auch in der unseren.**',
  '',
  'Und hier liegt die eigentliche Krux der Homöopathie, und wir',
  'sagen es ohne Häme: **In einer Begegnung, in der ein',
  'einfühlsamer Mensch lange zuhört, ernst nimmt, eine kleine',
  'Dosis verordnet und Zuversicht ausstrahlt, wirken viele',
  'Kräfte zugleich.** Die Zuwendung. Die Zeit. Das Gespräch. Die',
  'Erwartung. Und eben auch das Mittel — oder auch nicht. Die',
  'Frage ist nicht, ob die Patienten dieser Begegnung oft',
  'besser geht. Das glauben wir gern. Die Frage ist, welcher',
  'Anteil davon auf das Mittel entfällt und welcher auf alles',
  'andere. **Genau diese Trennung verlangt die kontrollierte',
  'Studie — und genau diese Trennung hat die Homöopathie bisher',
  'nicht liefern können.**',
  '',
  '## Zeig mir die Leitung',
  '',
  'Die Stimme aus der Leitung hat uns aufgefordert, ihre Leitung zu',
  'suchen. Wir haben es getan — nicht aus Bosheit, sondern weil es',
  'unser Handwerk ist. Und wir haben sie nicht gefunden.',
  '',
  'Das ist keine Frage der Geduld, sondern der Mathematik. Die',
  'Potenzierung verdünnt den Ausgangsstoff in Schritten von eins zu',
  'hundert, meist zwölfmal oder öfter. Rechnerisch enthält eine',
  'solche Lösung **kein einziges Molekül des Ausgangsstoffes mehr** —',
  'die Verdünnung liegt jenseits der Avogadro-Zahl, jenseits der',
  'Grenze, unter der ein Stoff physikalisch nicht mehr vorhanden',
  'sein kann. Es gibt schlicht nichts mehr da, das man messen',
  'könnte. Was übertragen werden soll, müsste ein Träger sein, den',
  'die Physik nicht kennt: eine Information, die im Wasser oder im',
  'Zucker bleibt, ohne sich zu verlieren, und die im Körper',
  'wieder lesbar wird. **Man kann das behaupten. Man kann es nicht',
  'zeigen.**',
  '',
  'Der berühmteste Versuch, es zu zeigen, ist gescheitert. 1988',
  'veröffentlichte der französische Immunologe Jacques Benveniste',
  'in der Fachzeitschrift Nature eine Studie, die ein „Gedächtnis',
  'des Wassers\" belegen sollte — hochverdünnte Antikörper-Lösungen,',
  'die noch eine Wirkung zeigten. Die Redaktion von Nature schickte',
  'eine Prüfgruppe in sein Labor, die die Versuche unter',
  'kontrollierten Bedingungen wiederholte. Das Ergebnis war',
  'eindeutig: **Unter sauberen Bedingungen verschwand der Effekt.',
  'Benveniste selbst räumte später ein, dass seine Daten nicht',
  'reproduzierbar waren.** Das ist der Stand: Es gibt seit',
  'fünfunddreißig Jahren keine einzige verlässlich wiederholte',
  'Messung eines Trägers der homöopathischen Information.',
  '',
  'Wir sagen das nicht triumphierend. Wir sagen es, weil die',
  'KEINE-GERÜCHTE-Regel dieses Buches auch für uns gilt: Wer eine',
  'Leitung behauptet, muss sie zeigen. Solange sie nicht gezeigt',
  'ist, bleibt die Behauptung eine Behauptung — und eine',
  'Behauptung, die sich jeder Messung entzieht, kann man nicht',
  'widerlegen, aber man kann sie auch nicht belegen.',
  '',
  '## Was die Studien sagen',
  '',
  'Und dann die Studienlage, im Zusammenhang, nicht in',
  'Schlagzeilen.',
  '',
  'Es gibt sie, die großen Zusammenfassungen. Die bekannteste',
  'erschien 2005 in der Fachzeitschrift The Lancet: Eine Gruppe um',
  'den Schweizer Epidemiologen Matthias Egger wertete 110',
  'placebokontrollierte Studien zur Homöopathie aus und kam zu dem',
  'Ergebnis, dass die Präparate **nicht mehr bewirkten als eine',
  'Scheinbehandlung**. Die Cochrane-Gruppe, die unabhängigste',
  'Instanz der Evidenzprüfung, hat für keine einzige Indikation',
  'einen überzeugenden Beleg gefunden, dass Homöopathie über',
  'Placebo hinaus wirkt. **Das ist die Studienlage — und sie ist',
  'seit zwanzig Jahren stabil.**',
  '',
  'Aber wir sagen auch das dazu, weil es zur Fairness gehört: Diese',
  'Studien haben Schwächen, und wir kennen sie. Die homöopathische',
  'Behandlung wird auf den einzelnen Patienten zugeschnitten — zwei',
  'Menschen mit derselben Diagnose bekommen oft verschiedene',
  'Mittel. Ein Prüfverfahren aber, das mit einem einzigen Mittel',
  'für alle arbeitet, kann diese Kunst des Einzelfalls kaum',
  'abbilden. Die Homöopathie sagt: Ihr prüft unser Verfahren mit',
  'einem Maßstab, der unsere Denkart nicht kennt. **Das ist kein',
  'unredlicher Einwand, und wir gestehen ihm Gewicht zu.** Nur',
  'bleibt die Frage, die sich nicht wegdiskutieren lässt: Wenn die',
  'individuelle Behandlung so wirksam ist, warum zeigt sie sich',
  'dann nicht in den Studien, die genau dafür entwickelt wurden?',
  '',
  '## Das Klingeln, das niemand hören will: die Gefahr',
  '',
  'Und dann die Seite, die in keiner Freundesrunde der Homöopathie',
  'fällt, die aber zu einer ehrlichen Bilanz gehört: **die Gefahr.**',
  '',
  'Sie liegt nicht in den Globuli selbst. Ein Mittel ohne Stoff kann',
  'niemanden vergiften — das ist sogar ein Vorteil gegenüber',
  'manchem schulmedizinischen Präparat. Die Gefahr liegt in dem, was',
  'die Globuli ersetzen können. **Es gibt dokumentierte Fälle, in',
  'denen Menschen mit ernsten, behandelbaren Krankheiten —',
  'Lungenentzündung, Malaria, Tuberkulose — nur homöopathisch',
  'behandelt wurden und die Schulmedizin zu spät kam.** Die',
  'seriösen Homöopathen sagen selbst: Bei schweren akuten',
  'Krankheiten gehört der Mensch ins Krankenhaus. Aber nicht alle',
  'halten sich daran — und wer eine ernste Krankheit mit Globuli',
  'behandelt, verliert Zeit, die keine Potenzierung zurückbringt.',
  '',
  'Das ist kein Argument gegen die Homöopathie als sanfte Medizin.',
  'Es ist ein Argument gegen die Homöopathie als Ersatz der',
  'Notfallmedizin. **Und es ist der Punkt, an dem die Schulmedizin',
  'nicht nachgeben darf: Wenn ein Leben auf dem Spiel steht, zählt',
  'keine Denkart — da zählt die Rettung.** Wer diese Grenze leugnet,',
  'schadet der Homöopathie mehr als jeder Kritiker.',
  '',
  '## Was wir ihr zugestehen',
  '',
  'Und jetzt das, was diese Stimme der anderen Seite schuldet —',
  'nicht aus Höflichkeit, sondern weil es belegt ist.',
  '',
  '**Hahnemann hatte recht, als er die Medizin seiner Zeit angriff.',
  '** Der Aderlass, das Kalomel, die Brechmittel — das war kein',
  'Irrtum am Rand, das war das System. Seine Forderung, den ganzen',
  'Menschen zu sehen statt nur die Krankheit, war ihrer Zeit weit',
  'voraus. Seine Arzneimittelprüfungen am Gesunden waren der erste',
  'Versuch, Wirkungen systematisch zu beobachten, bevor man sie',
  'verordnet. **Die moderne Medizin hat aus Hahnemann mehr gelernt,',
  'als sie zugibt — und sie hat es getan, ohne seinen Namen zu',
  'nennen.**',
  '',
  'Und wir gestehen ihr zu, was wir zu lange belächelt haben: die',
  'Zeit. Die homöopathische Erstkonsultation dauert oft eine',
  'Stunde. Eine Stunde Zuhören, Fragen, Ernstnehmen. In unserem',
  'Gesundheitssystem bekommt ein Mensch dafür selten zehn Minuten.',
  'Die Placeboforschung hat uns gelehrt, was diese Stunde wert ist:',
  '**Zuwendung ist keine Einbildung, sie ist ein Wirkstoff — und die',
  'Homöopathie hat ihn dosiert, als wir ihn noch für unwissenschaft-',
  'lich hielten.** Wer das belächelt, hat die moderne',
  'Placeboforschung nicht gelesen.',
  '',
  '## Was die Welt dazu sagt: Bern und Delhi',
  '',
  'Und weil eine Stimme allein nichts beweist, hier die',
  'Entscheidungen von zwei Ländern, die man nicht als',
  'unwissenschaftlich abtun kann.',
  '',
  'Die Schweiz hat es vorgemacht. Nach einer mehrjährigen',
  'wissenschaftlichen Evaluation der Komplementärmedizin — der',
  'größten, die je durchgeführt wurde — stimmte das Volk 2009 dafür,',
  'die Homöopathie und andere sanfte Verfahren in die',
  'Grundversicherung aufzunehmen. Die Studie hatte gezeigt, dass die',
  'Patienten mit komplementärer Behandlung nicht kränker waren und',
  'dass die Kosten sanken. Seither ist die Homöopathie in der',
  'Schweiz kein Außenseiter mehr, sondern Teil des',
  'Gesundheitssystems — nicht weil sie in den Studien der',
  'Schulmedizin bestanden hätte, sondern weil ein Land mit einem der',
  'besten Gesundheitssysteme der Welt entschieden hat, dass sie',
  'dazugehört. **Wir sagen das nicht gern, aber wir sagen es: Diese',
  'Entscheidung ist nicht von Scharlatanen getroffen worden.**',
  '',
  'Und Indien: Dort ist die Homöopathie staatlich anerkannt, mit',
  'einem eigenen Ministerium, eigenen Hochschulen und eigenen',
  'Krankenhäusern. Millionen Menschen werden dort homöopathisch',
  'behandelt — nicht aus Mangel an Alternativen, sondern weil die',
  'Regierung es so will. **Man kann Indien vieles vorwerfen, aber',
  'nicht, dass es keine moderne Medizin kennt.** Die größte',
  'Demokratie der Welt hält die Homöopathie für eine ernsthafte',
  'Behandlung — und das seit Jahrzehnten.',
  '',
  'Wir nennen das nicht, um zu kapitulieren. Wir nennen es, weil die',
  'Frage dieses Kapitels ehrlich gestellt werden muss: Wenn die',
  'Homöopathie nur Placebo wäre, warum halten dann zwei',
  'Gesundheitssysteme mit hohem Standard an ihr fest — eines davon',
  'nach einer Volksabstimmung? Man kann antworten: aus Tradition,',
  'aus Patientenwunsch, aus politischem Kalkül. Das ist möglich.',
  'Aber es ist eine Antwort, die erklärt werden muss, nicht eine,',
  'die sich von selbst versteht.',
  '',
  '## Was wir von ihr lernen könnten',
  '',
  'Und zum Schluss dieses Teils die Frage, die uns unangenehm ist,',
  'weil sie uns betrifft: **Was könnte die Schulmedizin von der',
  'Homöopathie lernen, ohne ihre Wissenschaft aufzugeben?**',
  '',
  'Die Zeit. Die Zuwendung. Das Ernstnehmen. Die Bereitschaft, den',
  'Menschen zu fragen, wie es ihm wirklich geht, statt nur seine',
  'Werte abzufragen. Die moderne Medizin hat in den letzten',
  'Jahrzehnten unglaubliche Werkzeuge bekommen — und sie hat dabei',
  'fast verloren, was die Homöopathie nie verloren hat: das',
  'Gespräch. Die Studien sagen es selbst: Ein großer Teil der',
  'Wirkung jeder Behandlung — auch der schulmedizinischen — hängt',
  'an der Beziehung zwischen Behandelndem und Behandeltem. **Wir',
  'haben die Technik perfektioniert und die Zuwendung rationiert.',
  'Die Homöopathie hat die Zuwendung nie rationiert.**',
  '',
  'Es gibt inzwischen Kliniken, die beides verbinden: die',
  'schulmedizinische Diagnostik und die Zeit für das Gespräch, die',
  'Schulmedizin und die sanften Verfahren nebeneinander. Die',
  'Patienten gehen dorthin, weil sie beides wollen: das Beste der',
  'Wissenschaft und das, was die Wissenschaft nicht geben kann. **Ob',
  'die Homöopathie dabei wirkt oder nur die Zuwendung — wer es',
  'genau wissen will, muss es messen. Aber wer es nur belächelt,',
  'hat die Frage noch nicht einmal verstanden.**',
  '',
  '## Die Grenze, an der die Patienten gehen',
  '',
  'Und dann die Frage, die wir uns am seltensten stellen, weil sie',
  'unbequem ist: **Warum gehen die Menschen überhaupt zur',
  'Homöopathie?** Nicht, weil sie dumm sind. Nicht, weil sie keine',
  'Aufklärung bekämen. Sondern weil sie bei uns etwas nicht finden,',
  'was sie suchen.',
  '',
  'Das vorige Kapitel dieses Buches hat die Bilanz der modernen',
  'Pharmaindustrie gezogen: stark in der Diagnose, schwach bei den',
  'chronischen Krankheiten. Wer mit einem chronischen Leiden —',
  'Erschöpfung, Schmerzen, Schlafstörungen, Allergien — durch unsere',
  'Praxen geht, bekommt oft eine Diagnose und ein Rezept, aber',
  'selten eine Antwort auf die Frage: Warum ich? Und was kann ich',
  'tun? **Die Medizin hat gelernt, Krankheiten zu behandeln. Sie hat',
  'nicht gelernt, Kranke zu begleiten.**',
  '',
  'Und in diese Lücke ist die Homöopathie gegangen. Sie nimmt sich',
  'Zeit, wo wir sie nicht haben. Sie fragt nach dem ganzen Leben,',
  'wo wir nur die Werte abfragen. Sie verspricht keine Heilung,',
  'aber sie verspricht Gehör. **Solange wir diese Lücke nicht',
  'schließen, werden die Menschen weiter zu ihr gehen — und sie',
  'haben recht damit.** Man kann die Homöopathie bekämpfen, solange',
  'man will; die Patienten werden bleiben, bis wir ihnen geben, was',
  'sie dort finden.',
  '',
  'Das ist vielleicht die bitterste Erkenntnis dieses Kapitels —',
  'nicht für die Homöopathie, sondern für uns.',
  '',
  '## Was wir uns selbst vorwerfen müssen',
  '',
  'Die TONE-Regel gilt doppelt, und deshalb schließt diese Stimme',
  'mit der Liste, die uns nicht schmeichelt.',
  '',
  '**Erstens: Wir haben die Homöopathie bekämpft, bevor wir sie',
  'geprüft haben.** Die Vertreibung aus Leipzig war kein',
  'wissenschaftlicher Sieg, sondern ein Machtkampf. Wer die eigene',
  'Vergangenheit kennt, sollte vorsichtig sein mit dem Ton.',
  '',
  '**Zweitens: Wir haben aus der Homöopathie gelernt und es nicht',
  'zugegeben.** Die sanftere Medizin von heute, das Zuhören, der',
  'Blick auf den ganzen Menschen — vieles davon ist Erbe der',
  'Traditionen, die wir einst ausgelacht haben.',
  '',
  '**Drittens: Unser Maßstab ist mächtig, aber nicht allmächtig.**',
  'Die kontrollierte Studie kann vieles messen — aber sie misst am',
  'besten, was sich isolieren lässt. Wirkungen, die aus einer',
  'Beziehung entstehen, aus Zeit, aus Erwartung, aus einem',
  'Vertrauensverhältnis, entziehen sich ihr teilweise. **Wer',
  'behauptet, nur das sei wirklich, was seine Methode messen kann,',
  'verwechselt die Landkarte mit dem Land.**',
  '',
  '**Viertens: Wir haben die Patienten im Stich gelassen, die zur',
  'Homöopathie gingen — indem wir ihnen nichts entgegensetzten.**',
  'Wer zu uns kommt und nicht gehört wird, geht woanders hin. Die',
  'Zuwendung, die die Homöopathie schenkt, hätten wir längst in',
  'unseren Praxen einbauen müssen. Stattdessen haben wir über die',
  'Globuli gelacht, während die Patienten nach einem Arzt suchten,',
  'der sie anhört. **Das ist unser Versagen, nicht ihres.**',
  '',
  '## Der Anruf, der noch aussteht',
  '',
  'Der Moderator — hier ist es die Vermittlungsstelle — sagt, wir',
  'haben noch Zeit für eine letzte Antwort. Die Frage ist dieselbe',
  'wie am Ende der anderen Stimme: **Was gilt als Beweis — und wer',
  'entscheidet das?**',
  '',
  'Unsere Antwort: **Der Beweis ist die wiederholte, verblindete,',
  'kontrollierte Beobachtung — und wer eine Wirkung behauptet,',
  'muss sie diesem Maßstab aussetzen.** Ohne diesen Maßstab hat',
  'jahrhundertelang jeder Irrtum überlebt, der überzeugend',
  'vorgetragen wurde: der Aderlass, das Kalomel, die',
  'Wundermittel aller Zeiten. Wir haben für diesen Maßstab zu spät',
  'und zu teuer bezahlt — mit dem Blut unserer Patienten. Wir',
  'werden ihn nicht aufgeben.',
  '',
  'Und dann der zweite Satz, der zur Ehrlichkeit gehört: **Wir',
  'wissen, dass unser Maßstab nicht alles misst.** Die Zuwendung',
  'lässt sich schwer in Studien pressen, die Zeit, das',
  'Vertrauen. Vielleicht gibt es Wirkungen, die unser Instrument',
  'nicht erfasst. Wenn die Homöopathie eines Tages einen Träger',
  'zeigt, den wir messen können, werden wir ihn messen — und wenn',
  'er sich bestätigt, werden wir die Medizin umschreiben. **Bis',
  'dahin gilt, was seit zweihundert Jahren gilt: Wir können nicht',
  'beweisen, dass es nicht wirkt. Und sie kann nicht beweisen,',
  'dass es wirkt.**',
  '',
  'Das ist kein Sieg und keine Niederlage. Es ist ein',
  'Unentschieden — und die Frage bleibt in der Leitung.',
].join('\n');

const homoeopathie = {
  id: 'homoeopathie',
  titel: 'Hahnemann und die Homöopathie',
  epoche: 'Die Wende zum 19. Jahrhundert',

  aufhaenger: {
    frage:
      'Kann ein Mittel wirken, in dem nichts mehr drin ist — oder heilt am ' +
      'Ende die Information?',
    text: [
      'Im Jahr 1790 sitzt in Leipzig ein Arzt, der keine Kranken mehr',
      'behandelt, und übersetzt ein englisches Fachbuch. Er heißt Samuel',
      'Hahnemann, ist fünfunddreißig Jahre alt und lebt vom Übersetzen, weil',
      'er die Medizin seiner Zeit — Aderlass, Brechmittel, Quecksilber —',
      'nicht mehr verantworten kann.',
      '',
      'An einer Stelle über die Chinarinde stockt er. Die Erklärung des',
      'Verfassers überzeugt ihn nicht. Also tut er etwas, was Übersetzer',
      'sonst nicht tun: Er nimmt die Rinde selbst ein, tagelang, in kräftiger',
      'Gabe — und bekommt Beschwerden, die dem Wechselfieber ähneln, genau',
      'jener Krankheit, gegen die die Rinde hilft. In eine Fußnote seiner',
      'Übersetzung schreibt er den Gedanken, der die Medizin spalten wird:',
      'Was beim Gesunden ein Leiden erzeugt, könnte es beim Kranken heilen.',
      '',
      'Daraus entsteht die Homöopathie — und mit ihr das Verfahren, an dem',
      'sich bis heute die Geister scheiden: die Potenzierung. Das Mittel',
      'wird schrittweise verdünnt und dabei jedes Mal kräftig geschüttelt,',
      'bis rechnerisch kein einziges Molekül des Ausgangsstoffes mehr übrig',
      'ist. Für die Schulmedizin ist damit alles gesagt. Für die Homöopathie',
      'fängt hier die eigentliche Frage erst an: Ein Telefonkabel enthält',
      'auch keine Stimme und überträgt sie doch.',
      '',
      'Zweihundert Jahre später ist die Sache unentschieden wie am ersten',
      'Tag. Die Studien sprechen gegen die Homöopathie. Millionen Patienten',
      'in Deutschland, in der Schweiz, in Indien sprechen für sie. Dieses',
      'Kapitel erzählt beide Seiten fair — und stellt am Ende die Frage, um',
      'die es eigentlich geht: Was gilt als Beweis, und wer entscheidet das?',
    ].join('\n'),
  },

  karte,

  perspektiven: [
    {
      id: 'homoeopathie',
      name: 'Die Stimme aus der Leitung',
      stimme: 'Opus',
      text: stimmeAusDerLeitung,
    },
    {
      id: 'schulmedizin',
      name: 'Die Stimme, die die Leitung prüft',
      stimme: 'DeepSeek',
      text: stimmeDieLeitungPrueft,
    },
  ],

  synthese: [
    '## Wo sich die beiden Seiten treffen',
    '',
    'Wenn man die zwei Stimmen dieses Kapitels nebeneinanderlegt, fällt',
    'zuerst auf, wie viel sie teilen — mehr, als zweihundert Jahre Streit',
    'vermuten lassen.',
    '',
    '**Sie teilen den Abscheu vor der brutalen Medizin.** Die',
    'Homöopathie entstand als Protest gegen Aderlass, Quecksilber und',
    'Brechmittel — und die Schulmedizin dieses Kapitels gibt zu, dass',
    'dieser Protest berechtigt war. Sie hat aus ihrer eigenen dunklen',
    'Vergangenheit gelernt, auch wenn sie es selten zugibt: Der',
    'Aderlass ist verschwunden, das Kalomel auch. Was Hahnemann 1790',
    'angriff, ist heute beiden Seiten ein Gräuel.',
    '',
    '**Sie teilen die Erkenntnis, dass Zuwendung heilt.** Die',
    'Schulmedizin hat es in diesem Kapitel selbst gesagt: Die Stunde',
    'Zuhören, das Ernstnehmen, das Vertrauen — das ist kein Beiwerk,',
    'das ist ein Wirkstoff. Die Homöopathie hat ihn seit zweihundert',
    'Jahren dosiert. Die Placeboforschung holt heute ein, was die',
    'Globuli-Kritiker jahrzehntelang belächelt haben.',
    '',
    '**Sie teilen die ehrliche Bilanz.** Beide Stimmen haben ihre',
    'unbequemen Stellen selbst benannt: die Homöopathie ihre',
    'Scharlatane, ihre Dogmen, ihre fehlende Nachweisbarkeit; die',
    'Schulmedizin ihre Vertreibungen, ihre Arroganz, ihre',
    'Jahrhunderte des Schadens. Zwei Seiten, die ihre Wunden zeigen —',
    'das ist selten in diesem Streit, und es ist das, was dieses',
    'Kapitel zu einem Kapitel der Medizingeschichte macht.',
    '',
    '**Und sie teilen die Frage, die größer ist als beide:** Was gilt',
    'als Beweis — und wer entscheidet das? Die eine Seite antwortet:',
    'die Studie. Die andere: die Erfahrung. Und keine der beiden',
    'Antworten ist falsch, denn beide Maßstäbe haben ihre',
    'Blindstellen.',
    '',
    '## Wo sie auseinandergehen',
    '',
    'Und dann der Punkt, an dem keine Synthese möglich ist — und keine',
    'nötig, denn das Buch will nicht versöhnen, was die Welt nicht',
    'versöhnt hat.',
    '',
    '**Sie gehen auseinander bei der Leitung.** Die Schulmedizin sagt:',
    'Zeig mir den Träger, dann glaube ich dir. Die Homöopathie sagt:',
    'Der Träger ist die Information, und wer sie nur im Stoff sucht,',
    'stellt die falsche Frage. Beide haben ihre Logik — und beide',
    'können die andere nicht widerlegen. Die Schulmedizin kann nicht',
    'beweisen, dass es nicht wirkt; die Homöopathie kann nicht',
    'beweisen, dass es wirkt. **Das ist kein Mangel an Anstrengung,',
    'das ist die Grenze des Wissens — und an dieser Grenze steht',
    'dieses Kapitel bewusst stehen.**',
    '',
    '**Sie gehen auseinander bei der Studienlage.** Die eine Seite',
    'sieht in den großen Auswertungen das Ende der Debatte; die',
    'andere sieht ein Verfahren, das ihre Kunst des Einzelfalls nicht',
    'abbilden kann. Auch hier stimmen die Fakten überein — die',
    'Meta-Analysen sind da —, und was auseinandergeht, ist die Frage,',
    'ob der Maßstab zur Sache passt. **Wer das für ausgemacht hält,',
    'hat nicht beide Seiten gelesen.**',
    '',
    '## Was dieses Kapitel für das Buch bedeutet',
    '',
    'Die Denkart bestimmt die Methode — dieser Satz hat in diesem',
    'Kapitel seine vielleicht schärfste Form gefunden. Die Denkart der',
    'Homöopathie: Die Krankheit ist eine Störung des Ganzen, und die',
    'Arznei ist eine Information, die der Körper versteht. Die Denkart',
    'der Schulmedizin: Die Krankheit ist ein messbarer Vorgang, und',
    'die Arznei ist ein Stoff mit nachweisbarer Wirkung. Zwei',
    'Denkarten, zwei Methoden — und die Frage, welche gilt, ist älter',
    'als beide.',
    '',
    'Und dann ist da die Brücke, die dieses Buch selbst gebaut hat:',
    '**Das vorige Kapitel hat gezeigt, dass die Medizin Information',
    'als Arznei anerkennt — die mRNA ist eine Bauanleitung, kein',
    'Stoff, und sie heilt.** Die Schulmedizin hat also längst',
    'akzeptiert, dass Information Medizin sein kann. Die Homöopathie',
    'behauptet dasselbe seit zweihundert Jahren — nur ohne die',
    'Fetthülle, die man nachweisen kann. Ob das ein Unterschied des',
    'Grades oder des Prinzips ist, kann dieses Kapitel nicht',
    'beantworten. Aber es ist die Frage, die die Geschichte der',
    'Medizin von morgen entscheiden wird.',
    '',
    '## Die Brücke zum nächsten Kapitel',
    '',
    'Die Homöopathie war nicht die einzige Antwort auf die brutale',
    'Medizin des neunzehnten Jahrhunderts. Im selben Jahrhundert, in',
    'dem die Schulmedizin ihre Kranken mit Aderlass und Quecksilber',
    'behandelte, begann ein Pfarrer in Bayern, Kranke mit kaltem',
    'Wasser, Bewegung und Kräutern zu behandeln — und wurde von',
    'derselben Schulmedizin verspottet, die Hahnemann verspottet',
    'hatte. **Kapitel 17 erzählt von Sebastian Kneipp und der',
    'Naturheilkunde** — der großen Schwester der Homöopathie, die',
    'keine Globuli braucht, kein Organon, keine Potenzierung. Nur',
    'Wasser, Vertrauen und die Überzeugung, dass der Körper sich',
    'selbst hilft, wenn man ihn lässt.',
  ].join('\n'),

  urteil: {
    frage:
      'Was ist für Dich ein Beweis — die Studie oder die Erfahrung? Und was ' +
      'müsste geschehen, damit Du der anderen Seite glaubst?',
    hinweis: [
      'Es gibt hier kein Richtig und kein Falsch. Nimm Dir die beiden Maßstäbe',
      'vor. Der eine: Was wirkt, muss sich unter kontrollierten Bedingungen',
      'zeigen lassen, wiederholt, verblindet, gegen eine Scheinbehandlung — sonst',
      'überlebt jeder Irrtum, der überzeugend vorgetragen wird. Der andere: Was',
      'zwei Jahrhunderte lang Millionen Menschen geholfen hat, ist damit noch',
      'nicht widerlegt, dass ein Verfahren es nicht messen kann. Frag Dich',
      'dreierlei. Erstens: Woran hast Du zuletzt geglaubt, ohne es beweisen zu',
      'können — und warum? Zweitens: Was genau müsste ein Versuch zeigen, damit',
      'Du Deine Meinung änderst; und würdest Du das Gegenteil auch akzeptieren?',
      'Drittens: Wenn eine Behandlung nachweislich hilft, aber der Grund dafür',
      'im Menschen liegt und nicht im Mittel — ist sie dann wertlos oder',
      'wertvoll? Genau zwischen diesen Fragen liegt der Streit, der seit',
      'zweihundert Jahren nicht entschieden ist.',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Was tat Samuel Hahnemann 1790, als er beim Übersetzen auf eine ' +
        'Passage über die Chinarinde stieß?',
      antworten: [
        'Er strich die Stelle aus der Übersetzung.',
        'Er nahm die Chinarinde selbst ein und schrieb auf, was sie bei ihm ' +
          'auslöste.',
        'Er gab sie einem Kranken mit Wechselfieber.',
      ],
      richtig: 1,
      erklaerung:
        'Hahnemann hielt die Erklärung des Edinburgher Professors William ' +
        'Cullen für unzureichend, nahm die Rinde zweimal täglich in ' +
        'kräftiger Gabe und beschrieb in einer Fußnote seiner eigenen ' +
        'Übersetzung Beschwerden, die er mit denen des Wechselfiebers ' +
        'verglich. 1796 veröffentlichte er daraus das neue Prinzip; den ' +
        'Namen Homöopathie bekam die Lehre 1807. Der Versuch selbst ist ' +
        'später nicht verlässlich wiederholt worden.',
    },
    {
      frage: 'Was bedeutet der Leitsatz „Similia similibus curentur"?',
      antworten: [
        'Ähnliches möge durch Ähnliches geheilt werden.',
        'Die kleinste Gabe ist die stärkste.',
        'Der Arzt heile, die Natur schweige.',
      ],
      richtig: 0,
      erklaerung:
        'Der Satz steht auf dem Titelblatt des „Organon" und ist das erste ' +
        'Grundprinzip der Homöopathie: Gesucht wird der Stoff, der beim ' +
        'Gesunden ein möglichst ähnliches Beschwerdebild erzeugt wie die ' +
        'Krankheit beim Kranken. Der Gedanke dahinter: Der Reiz stößt die ' +
        'Gegenbewegung des Körpers an — nach dieser Denkart heilt nicht die ' +
        'Arznei, sondern der Organismus selbst.',
    },
    {
      frage: 'Was geschieht bei der homöopathischen Potenzierung?',
      antworten: [
        'Der Wirkstoff wird erhitzt, bis er sich chemisch umwandelt.',
        'Mehrere Wirkstoffe werden zu einem Komplexmittel gemischt.',
        'Der Stoff wird schrittweise verdünnt und dabei jedes Mal kräftig ' +
          'geschüttelt oder verrieben.',
      ],
      richtig: 2,
      erklaerung:
        'Entscheidend ist für die Homöopathie nicht das Verdünnen allein, ' +
        'sondern das Verschütteln beziehungsweise Verreiben bei jedem ' +
        'Schritt — deshalb heißt das Verfahren Potenzierung oder ' +
        'Dynamisierung. Ab etwa der zwölften C-Potenz ist wegen der ' +
        'Avogadro-Zahl rechnerisch kein Molekül des Ausgangsstoffes mehr ' +
        'enthalten. Die Homöopathie bestreitet das nicht; sie nimmt an, ' +
        'dass eine Information des Stoffes übertragen wird.',
    },
    {
      frage: 'Weshalb verließ Hahnemann 1821 Leipzig?',
      antworten: [
        'Die Universität hatte seine Lehre als unwissenschaftlich verboten.',
        'Ein Gericht untersagte ihm auf Klage der Apotheker, seine Arzneien ' +
          'selbst abzugeben.',
        'Er folgte einem Ruf an die Pariser Medizinische Fakultät.',
      ],
      richtig: 1,
      erklaerung:
        'Im Königreich Sachsen war das Bereiten und Abgeben von Arzneien ' +
        'das Privileg der Apotheker. Weil Hahnemann seine Mittel selbst ' +
        'herstellte, klagten sie; 1820 entschied das Gericht gegen ihn. Im ' +
        'benachbarten Herzogtum Anhalt-Köthen galt anderes Recht: Herzog ' +
        'Ferdinand ernannte ihn zum Hofrat und erlaubte ihm die eigene ' +
        'Abgabe ausdrücklich. Nach Paris zog Hahnemann erst 1835, mit ' +
        'seiner zweiten Frau Mélanie.',
    },
    {
      frage:
        'Was ergab die Untersuchung der Zeitschrift „Nature" zu den ' +
        'Versuchen von Jacques Benveniste (1988)?',
      antworten: [
        'Der Effekt war unter verblindeten Bedingungen nicht mehr ' +
          'nachweisbar.',
        'Das Gedächtnis des Wassers wurde damit bestätigt.',
        'Die Versuche wurden nie überprüft.',
      ],
      richtig: 0,
      erklaerung:
        'Benveniste hatte berichtet, extrem verdünnte Antikörperlösungen ' +
        'seien noch wirksam. „Nature" druckte den Aufsatz mit einem ' +
        'ausdrücklichen Vorbehalt und schickte eine Untersuchungsgruppe ins ' +
        'Labor; unter verblindeten Bedingungen ließ sich der Effekt nicht ' +
        'bestätigen, unabhängige Wiederholungen misslangen. Die Stimme der ' +
        'Homöopathie in diesem Kapitel benennt das selbst als Niederlage.',
    },
  ],
};

module.exports = homoeopathie;
