// Kapitel 10 — „Jenner und die Impfung".
//
// Das zweite Kapitel der Neuzeit. Es erzählt die erfolgreichste Maßnahme
// der Medizingeschichte — die Ausrottung der Pocken — und zugleich den
// ältesten und härtesten Streit, den die Medizin mit ihren Patienten
// führt. Beides gehört zusammen und wird hier zusammen erzählt.
//
// Die DENKART-Analyse ist das Herzstück (Betreiber-Vorgabe). Sie fragt
// hier: Warum vorbeugen statt heilen? (Weil es gegen die Pocken keine
// Behandlung gab — der einzige Hebel lag vor der Krankheit.) Warum sollte
// man einen Gesunden absichtlich krank machen? (Weil jeder wusste, dass
// ein Überlebender nie wieder erkrankt — der Körper lernt; und weil eine
// gesetzte Krankheit milder verläuft als eine eingeatmete.) Warum die
// Kuhpocken? (Weil die harmlose Verwandte dieselbe Lehre erteilt wie die
// tödliche — der Lehrer muss nicht gefährlich sein.) Warum von Arm zu
// Arm? (Weil es kein Gefäß gab, das den Impfstoff aufbewahren konnte —
// nur der lebende Körper.) Warum der Zwang? (Weil der Schutz des
// Einzelnen erst zum Schutz aller wird, wenn genug mitmachen — und weil
// der Staat dabei eine neue Macht über den Körper entdeckte.) Und warum
// ließ sich ausgerechnet diese eine Krankheit ausrotten?
//
// LÄNGENREGEL (Betreiber-Feedback 24.08.2026): Ab Kapitel 9 gilt die
// Umkehrung — vollständig und ausführlich. Für dieses Kapitel gilt sie
// doppelt (Betreiber-Vorgabe: dunkle Frühgeschichte UND impfkritische
// Statistik prominent, nicht als Randnotiz). Ausführlich heißt nicht
// aufgebläht: jeder Absatz bringt die Erzählung voran. Gemessen wird in
// tests/karte-jenner-impfung.mjs.
//
// TONE-Regel, hier besonders scharf: BEIDE Seiten fair. Diese erste
// Stimme spricht FÜR die Impfung — und benennt die unbequemen Stellen
// ihrer eigenen Seite selbst, statt sie der Gegenstimme zu überlassen:
// die Versuche an Gefangenen und Waisenkindern (Newgate und Boston,
// 1721), den Jungen James Phipps, die Syphilis, die von Arm zu Arm
// mitwanderte, das Geschäft mit der Lymphe, den Zwang der Impfgesetze —
// und die Statistik der Impfkritiker (der Rückgang vieler Krankheiten
// begann vor der Impfung), die hier nicht übergangen, sondern erklärt
// wird. KEINE GERÜCHTE (Betreiber-Entscheid 25.08.2026): Es steht nur
// Belegtes im Text; wo Zahlen strittig sind, sagt der Text es dazu.
//
// Stimmen (Runde 11): Die ERSTE Perspektive — die Impfärzte von innen —
// verfasste Opus. Die ZWEITE (die Impfkritik: die dunkle Frühgeschichte
// aus der Sicht derer, die sie erlitten, die Kurven vor der Impfung, die
// Hygiene-Hypothese und die Allergien, die Finanzinteressen) und die
// finale Synthese ergänzt Hermes im zweiten Pass. Perspektiven-Workflow:
// CLAUDE.md.
//
// KEINE WIEDERHOLUNGEN (Betreiber-Entscheid vom 21.08.2026): Kapitel 1
// gliedert nach „Wer hier spricht", Kapitel 2 beginnt mit einer Szene,
// Kapitel 3 erzählt einen Tageslauf, Kapitel 4 ist ein Briefwechsel,
// Kapitel 5 die Reise eines Buches, Kapitel 6 ein Rundgang, Kapitel 7 ein
// Prozess, Kapitel 8 eine Rechnung, Kapitel 9 eine Uhr. Dieses Kapitel
// wählt die zehnte Dramaturgie: DIE KETTE. Der Impfstoff des 19.
// Jahrhunderts hatte kein Fläschchen — er wanderte von Arm zu Arm, von
// Kind zu Kind, um die ganze Welt. Die Abschnitte sind die Glieder dieser
// Kette: das erste Glied aus dem Morgenland, das Glied aus dem Kuhstall,
// die Glieder, die niemand gefragt hat, das, was die Kette mitschleppte
// — bis zum letzten Glied 1977 in Somalia. Die zweite Stimme kann
// dieselbe Kette von ihren zerbrochenen Gliedern her lesen.
//
// Die Texte liegen als Zeilen-Arrays mit `.join('\n')` — so bleiben sie im
// Repo bei ~72 Zeichen lesbar (der Betreiber liest sie hier gegen), und
// utils/markdown.js macht in der App wieder fließenden Text daraus.
//
// CommonJS ohne UI-Importe (Architektur-Regel): mit blankem `node` prüfbar.

const { karte } = require('./karten/jenner-impfung');

/**
 * Die Stimme der Impfärzte — die Impfung von innen.
 *
 * Verfasst von Opus (Runde 11). Eine gemeinsame Stimme derer, die geimpft
 * haben: der Landarzt aus Berkeley, die Armenimpfer der englischen
 * Kirchspiele, die Ärzte der weltweiten Kampagne. Sie erzählt, warum sie
 * taten, was sie taten — und sie benennt die unbequemen Stellen selbst
 * (Zusatzregel für sensible Themen in CLAUDE.md).
 */
const stimmeDerImpfaerzte = [
  '## Die Kette',
  '',
  'Stell Dir eine Kette vor, die aus Menschen besteht.',
  '',
  'Sie beginnt an einem Nachmittag im Mai 1796 am linken Arm eines',
  'achtjährigen Jungen in einem englischen Dorf, und sie endet',
  'einhunderteinundachtzig Jahre später am Arm eines Krankenhauskochs in',
  'Somalia. Dazwischen liegen Millionen von Armen. Denn der Impfstoff,',
  'von dem dieses Kapitel handelt, hatte über Jahrzehnte kein Fläschchen',
  'und keine Kühlung. Er lebte nur in einem Menschen, und um ihn',
  'weiterzugeben, musste man ihn aus dem Arm des einen in den Arm des',
  'nächsten setzen. Acht Tage später war dieser Arm die Quelle für den',
  'übernächsten. **Die Impfung ist buchstäblich als Kette um die Welt',
  'gegangen — von Arm zu Arm, von Kind zu Kind.**',
  '',
  '**Was Du hier hörst, ist die Sicht derer, die geimpft haben — eine',
  'Denkart, keine Wahrheit.** Wir sprechen für den Landarzt in',
  'Gloucestershire, für die Armenimpfer der englischen Kirchspiele, für',
  'die Ärzte der weltweiten Kampagne der 1970er Jahre. Wir haben etwas',
  'zu erzählen, das in der Medizingeschichte einmalig ist: **eine',
  'Krankheit, die es nicht mehr gibt.** Und wir haben etwas zu gestehen:',
  'Diese Kette hat Glieder, die niemand gefragt hat.',
  '',
  'Wir gehen sie ab, Glied für Glied. Auch die Stellen, an denen sie',
  'rostet.',
  '',
  '## Vor der Kette: was die Pocken waren',
  '',
  'Um zu verstehen, warum Menschen taten, was gleich kommt, musst Du',
  'zuerst wissen, wovor sie Angst hatten. Nicht theoretisch. Praktisch.',
  '',
  'Die Pocken waren im 18. Jahrhundert in Europa allgegenwärtig. Fast',
  'jeder Mensch bekam sie irgendwann, meist als Kind. Historiker',
  'schätzen, dass ihnen in Europa jedes Jahr etwa **vierhunderttausend**',
  'Menschen erlagen. Von zehn Erkrankten starben bei der schweren Form',
  'etwa drei. Wer überlebte, trug es sein Leben lang im Gesicht: tiefe,',
  'runde Narben, oft zu Hunderten. Ein großer Teil aller Erblindungen',
  'jener Zeit ging auf die Pocken zurück.',
  '',
  'Es traf nicht nur die Armen. Königin Maria II. von England starb 1694',
  'daran, Kaiser Joseph I. 1711, König Ludwig XV. von Frankreich 1774.',
  'In den Habsburger Familien starben in einer einzigen Generation',
  'mehrere Kinder. **Das ist wichtig für alles Weitere: Die Pocken waren',
  'die eine Krankheit, gegen die Reichtum nicht half.**',
  '',
  'Und es gab nichts. Keine Behandlung, kein Mittel, keinen Trost außer',
  'Pflege. Der Arzt konnte das Fieber begleiten, die Wunden abdecken,',
  'die Angehörigen anweisen — mehr nicht. Wer die Pocken bekam, wartete,',
  'ob er zu den sieben von zehn gehörte.',
  '',
  'Hier liegt die Wurzel unserer ganzen Denkart, und sie ist eine',
  'Verzweiflungswurzel. **Warum vorbeugen statt heilen?** Nicht, weil',
  'wir klüger gewesen wären als die Ärzte vor uns. Sondern weil es',
  'nichts zu heilen gab. Wenn eine Krankheit erst da ist und niemand sie',
  'aufhalten kann, dann bleibt nur ein einziger Hebel übrig: die Zeit',
  '**davor**. Die Impfung ist der erste große Eingriff der Medizin in',
  'einen Menschen, der gar nicht krank ist. Das war neu, und es ist bis',
  'heute der Punkt, an dem sich die Geister scheiden — auch das gehört',
  'ehrlich in dieses Kapitel: Bei jeder anderen Behandlung wartet der',
  'Arzt, bis ein Kranker zu ihm kommt. Bei der Impfung geht er zu',
  'Gesunden.',
  '',
  '## Das erste Glied kam aus dem Morgenland',
  '',
  'Der erste Schutz gegen die Pocken war keine europäische Erfindung,',
  'und er kam nicht aus einer Universität. Er kam aus der Erfahrung',
  'einfacher Leute in China, Indien, Westafrika und im Osmanischen',
  'Reich.',
  '',
  'Das Verfahren hieß später **Variolation**, nach dem lateinischen',
  'Namen der Pocken. Es bestand darin, einen Gesunden absichtlich mit',
  '**echten Menschenpocken** anzustecken: In der Türkei ritzte man die',
  'Haut und legte einen Tropfen Flüssigkeit aus der Pustel eines leicht',
  'Erkrankten hinein. In China blies man getrockneten, gepulverten',
  'Pockenschorf in die Nase. In Teilen Afrikas ritzte man den Arm.',
  '',
  'Nach England brachte die Nachricht davon **Lady Mary Wortley',
  'Montagu**, die Frau des britischen Botschafters in Konstantinopel.',
  'Sie hatte die Pocken selbst überstanden, ihr Bruder war daran',
  'gestorben, ihr Gesicht war gezeichnet. 1717 schrieb sie aus der',
  'Türkei nach Hause, dort gebe es alte Frauen, die im September mit',
  'einer Nussschale voll Pockenmaterial von Haus zu Haus gingen; die',
  'Sache sei so ungefährlich, dass sie sie an ihrem eigenen Sohn',
  'vornehmen lassen werde. Sie tat es 1718 in Konstantinopel und 1721 an',
  'ihrer Tochter in London.',
  '',
  '**Warum sollte man einen Gesunden absichtlich krank machen?** Diese',
  'Frage klingt heute verrückt. Damals hatte sie eine saubere Antwort in',
  'drei Schritten, und jeder Schritt beruhte auf einer Beobachtung, die',
  'jeder machen konnte:',
  '',
  '**Erstens: Der Körper lernt und vergisst nicht.** Wer die Pocken',
  'überstanden hatte, bekam sie nie wieder. Das wusste jeder. Deshalb',
  'wurden zur Pflege der Kranken bevorzugt Menschen mit Narben im',
  'Gesicht eingesetzt — sie galten als sicher. Niemand konnte erklären,',
  'warum. Aber es galt so verlässlich, dass man darauf bauen konnte.',
  '',
  '**Zweitens: Nicht jeder Verlauf ist gleich schwer.** Manche kamen mit',
  'wenigen Pusteln davon, andere starben. Wenn also der Schutz derselbe',
  'ist, ganz gleich wie schwer die Krankheit war — dann ist der milde',
  'Verlauf ein voller Gewinn.',
  '',
  '**Drittens: Man kann den Verlauf beeinflussen.** Und hier liegt die',
  'eigentliche Kunst der alten Impferinnen. Sie wählten das Material aus',
  'einem leichten Fall, nahmen wenig davon, setzten es in die Haut statt',
  'in die Atemluft, wählten einen kräftigen Menschen und eine gute',
  'Jahreszeit. Das Ergebnis war nicht sicher, aber es war anders: Von',
  'hundert Variolierten starben ungefähr ein bis zwei. Von hundert',
  'natürlich Angesteckten starben zwanzig bis dreißig.',
  '',
  '**Das ist die Rechnung, auf der die ganze Vorbeugung ruht** — und sie',
  'ist eine Wettrechnung, keine Sicherheit. Man tauschte eine große',
  'Gefahr, die einen fast sicher irgendwann traf, gegen eine kleine',
  'Gefahr, die man selbst wählte und zeitlich bestimmte. Wer diese',
  'Rechnung nicht akzeptierte, hatte einen Einwand, den wir nie entkräften',
  'konnten und bis heute nicht entkräften können: **Der eine bis zwei von',
  'hundert war ein Mensch, der ohne den Eingriff vielleicht nie erkrankt',
  'wäre.** Und er starb an einer Krankheit, die ein Arzt ihm gegeben hat.',
  '',
  'Die Variolation hatte noch einen zweiten Preis, den wir nennen',
  'müssen: Der Geimpfte war für Wochen selbst ansteckend. Er trug echte',
  'Pocken. Wer nachlässig war, setzte damit eine Epidemie in Gang. In',
  'England wurde die Variolation genau deshalb 1840 gesetzlich verboten,',
  'lange nachdem sie ihre Schuldigkeit getan hatte.',
  '',
  '## Newgate und Boston, 1721: der Preis der ersten Prüfung',
  '',
  'Und nun die Stelle, an der wir nichts glätten. Denn die Frage, wie',
  'gefährlich das Verfahren ist, wollte in England niemand am eigenen',
  'Kind beantwortet sehen. Also beantwortete man sie an Menschen, die',
  'nicht Nein sagen konnten.',
  '',
  'Am **9. August 1721** wurden im Londoner Gefängnis **Newgate** sechs',
  'zum Tode verurteilte Häftlinge variolisiert — drei Männer und drei',
  'Frauen. Die Gegenleistung war die Begnadigung. Ärzte und Höflinge',
  'sahen zu. Alle sechs überstanden es, alle sechs kamen frei; eine der',
  'Frauen wurde anschließend in ein Pockenhaus geschickt, um zu prüfen,',
  'ob der Schutz hielt.',
  '',
  'Im Jahr darauf wiederholte man die Probe an Waisenkindern der',
  'Gemeinde St James in Westminster. Erst danach ließ die Prinzessin von',
  'Wales ihre eigenen Töchter impfen — und erst danach wurde die Sache',
  'in England gesellschaftsfähig.',
  '',
  '**Wir nennen das beim Namen: Das war ein Menschenversuch an',
  'Gefangenen und an Kindern ohne Eltern.** Eine Einwilligung, wie wir',
  'sie heute verlangen, gab es nicht und konnte es nicht geben: Wer',
  'zwischen dem Galgen und einer Impfung wählt, wählt nicht frei. Wer',
  'als Waisenkind einer Gemeinde gehört, wird nicht gefragt. Die',
  'Rechtfertigung der Zeit lautete, es habe sich schließlich für alle',
  'gut ausgegangen. Das ist keine Rechtfertigung. Es ist Glück.',
  '',
  'Im selben Jahr geschah dasselbe auf der anderen Seite des Atlantiks,',
  'und dort ist die Geschichte noch unbequemer. In **Boston** wütete',
  '1721 eine Pockenepidemie. Der Prediger Cotton Mather hatte das',
  'Verfahren nicht aus einem Buch, sondern von **Onesimus**, einem',
  'Mann, den er als Sklaven besaß und der aus Westafrika stammte:',
  'Onesimus zeigte ihm die Narbe an seinem Arm und erklärte ihm, dass',
  'man in seiner Heimat auf diese Weise vor den Pocken schütze. Der',
  'Arzt **Zabdiel Boylston** wagte den Versuch — zuerst an seinem',
  'eigenen sechsjährigen Sohn und an zwei versklavten Menschen seines',
  'Haushalts, einem Erwachsenen und einem Kleinkind.',
  '',
  'Am Ende der Epidemie hatte Boylston 242 Menschen variolisiert. Sechs',
  'von ihnen starben. Von den rund 5.900 Bostonern, die sich auf',
  'natürlichem Weg angesteckt hatten, starben 844. **Die Zahlen waren',
  'eindeutig, und sie waren die ersten dieser Art in der',
  'Medizingeschichte: eine Vorbeugung, an einer Bevölkerung nachgezählt.**',
  '',
  'Und trotzdem steht daneben ein Satz, der sich nicht wegrechnen lässt:',
  '**Das Wissen der Afrikaner wurde genommen, die Körper der',
  'Versklavten wurden benutzt, und der Ruhm ging an zwei weiße Männer.**',
  'Onesimus taucht in den Büchern der Medizin über zweihundert Jahre',
  'lang kaum auf. Wir schreiben ihn hier an die Stelle, an die er',
  'gehört: an den Anfang.',
  '',
  '## Das Glied aus dem Kuhstall',
  '',
  'Und nun nach Gloucestershire, in eine Landschaft aus Weiden, Hecken',
  'und Milchvieh.',
  '',
  'Unter den Bauern dort lief seit Menschengedenken eine Behauptung um:',
  '**Wer die Kuhpocken gehabt hat, bekommt die Menschenpocken nicht.**',
  'Die Kuhpocken waren eine geringfügige Sache — eine Rinderkrankheit,',
  'die sich beim Melken auf die Hände übertrug: ein paar Bläschen an den',
  'Fingern, ein paar Tage Unwohlsein, fertig. Die Mägde, die morgens und',
  'abends im Stall saßen, bekamen sie oft. Und in den Pockenjahren',
  'blieben sie auffällig oft gesund.',
  '',
  'Ein Landarzt namens **Edward Jenner** (1749 in Berkeley geboren, dort',
  'auch gestorben 1823) nahm diese Bauernrede ernst. Das ist der',
  'entscheidende Schritt, und er ist kein medizinischer, sondern ein',
  'geistiger: **Er hielt das Wissen der Melkerinnen für eine',
  'Beobachtung und nicht für Aberglauben.**',
  '',
  'Jenner hatte in London bei John Hunter gelernt, dem Anatomen aus dem',
  'neunten Kapitel dieses Buches, und von ihm den Satz übernommen, der',
  'die ganze neue Medizin trägt: Warum denkst Du darüber nach? Warum',
  'probierst Du es nicht aus? Also sammelte er Fälle. Er suchte',
  'Melkerinnen, die die Kuhpocken gehabt hatten, und ließ sie',
  'variolisieren — mit echten Pocken. Bei ihnen geschah nichts. Der',
  'Einstich blieb reizlos, das Fieber blieb aus. Bei anderen ging die',
  'Variolation ihren gewohnten Gang.',
  '',
  '**Warum die Kuhpocken?** Weil Jenner aus diesen Fällen eine',
  'Begründung ableitete, die eine der fruchtbarsten der ganzen',
  'Medizingeschichte werden sollte: **Wenn zwei Krankheiten einander',
  'ähnlich genug sind, erteilt die harmlose dem Körper dieselbe Lehre',
  'wie die tödliche.** Der Körper lernt an einem ungefährlichen Beispiel',
  'und besteht die Prüfung, wenn der Ernstfall kommt. Der Lehrer muss',
  'nicht gefährlich sein.',
  '',
  'Das ist der ganze Gedanke der Impfung, und er ist bis heute derselbe.',
  'Alles, was seither dazugekommen ist — abgetötete Erreger,',
  'abgeschwächte Erreger, einzelne Eiweißbausteine, Bauanleitungen —,',
  'sind Antworten auf die eine Frage, wie man dem Körper die Lehre',
  'erteilt, ohne ihm die Krankheit zu geben.',
  '',
  'Zwei Ehrlichkeiten an dieser Stelle. **Die erste: Jenner war nicht',
  'der Erste.** Der Bauer **Benjamin Jesty** aus Yetminster in Dorset',
  'hatte 1774 — zweiundzwanzig Jahre vor Jenner — seine Frau und seine',
  'beiden Söhne mit einer Stricknadel mit Kuhpockenmaterial geimpft, um',
  'sie durch eine Pockenwelle zu bringen. Sie blieben ihr Leben lang',
  'verschont. Jesty erntete Spott und Steinwürfe und schrieb nichts',
  'auf. Was Jenner tat und Jesty nicht tat, war die Sache zu **prüfen',
  'und zu veröffentlichen**. Das ist eine große Leistung. Sie ist nur',
  'eine andere als die, die auf den Denkmälern steht.',
  '',
  '**Die zweite: Die Herkunft des Impfstoffs ist bis heute nicht ganz',
  'geklärt.** Neuere Untersuchungen alter Impfstoffproben legen nahe,',
  'dass in vielen dieser Lymphen gar nicht das Kuhpockenvirus steckte,',
  'sondern ein naher Verwandter aus dem Pferd. Jenner selbst hat immer',
  'wieder auf eine Pferdekrankheit verwiesen, die über die Hände der',
  'Knechte in die Ställe kam. Für die Wirkung ändert das nichts. Für',
  'unsere Gewissheit schon: **Wir haben jahrzehntelang mit etwas',
  'geimpft, von dem wir nicht genau wussten, was es war.**',
  '',
  '## Der 14. Mai 1796: ein Junge namens James Phipps',
  '',
  'An diesem Tag beginnt die Kette.',
  '',
  'Die Kuhmagd **Sarah Nelmes** hatte sich beim Melken einer Kuh die',
  'Kuhpocken geholt; an ihrer Hand saßen die Bläschen. Jenner nahm',
  'Flüssigkeit daraus und setzte sie in zwei kleine Schnitte am Arm des',
  'achtjährigen **James Phipps**, des Sohnes seines Gärtners. Der Junge',
  'bekam, was zu erwarten war: eine örtliche Pustel, ein paar Tage',
  'Unwohlsein, dann nichts mehr.',
  '',
  'Und dann kam der Teil, der die Sache zum Beweis machte und zugleich',
  'zum Problem. Am **1. Juli 1796** variolisierte Jenner den Jungen —',
  'mit echtem Menschenpockenmaterial. **Er setzte ihm die Krankheit,',
  'gegen die er ihn schützen wollte.** Wäre die Idee falsch gewesen,',
  'hätte James Phipps sterben können. Es geschah nichts. Jenner',
  'wiederholte die Probe später mehrfach; der Schutz hielt.',
  '',
  '**Nach heutigen Maßstäben ist das kein zulässiger Versuch.** Kein',
  'Aufklärungsgespräch, keine schriftliche Einwilligung der Eltern, kein',
  'unabhängiges Gremium, das über den Versuch wacht — und vor allem: ein',
  'Kind, dem man den Ernstfall absichtlich zugefügt hat. Wir haben in',
  'unseren eigenen Erzählungen zweihundert Jahre lang darüber',
  'hinweggelesen, weil das Ergebnis so groß war. Das war ein Fehler.',
  '**Ein Ergebnis macht einen Versuch nicht nachträglich zulässig.**',
  '',
  'Was sich zu Jenners Gunsten sagen lässt, sagen wir auch, damit Du',
  'beides abwägen kannst: Er hat mit der Variolation ein Verfahren',
  'benutzt, das damals gängig war und das viele Eltern für ihre Kinder',
  'ausdrücklich wünschten. Er hat den Jungen ein Leben lang',
  'weiterbetreut, ihm später ein Haus überlassen und ihn nie aus den',
  'Augen verloren. Und er hat, als er berühmt war, in einer kleinen',
  'Hütte in seinem Garten die Armen der Umgebung **kostenlos** geimpft;',
  'er nannte sie den Tempel der Vakzine. Das macht den Versuch am Kind',
  'nicht zulässig. Es zeigt nur, dass ein Mensch beides sein kann.',
  '',
  'Die Royal Society lehnte seinen ersten Bericht ab. 1798 druckte er',
  'auf eigene Kosten eine schmale Schrift über die Kuhpocken, in der er',
  'dreiundzwanzig Fälle darlegte. Von dem lateinischen Wort für Kuh —',
  '*vacca* — stammt der Name, den die Sache seither trägt: Vakzination.',
  'Als Louis Pasteur achtzig Jahre später seine eigenen Impfstoffe',
  'entwickelte, behielt er das Wort bei, ausdrücklich zu Jenners Ehre.',
  '',
  '## Wie die Kette um die Welt lief',
  '',
  'Was danach geschah, ist ohne Beispiel: Innerhalb weniger Jahre lief',
  'ein englischer Kuhstallbefund um den ganzen Erdball. Und weil es',
  'weder Kühlung noch ein haltbares Präparat gab, lief er als Kette.',
  '',
  '**Warum von Arm zu Arm?** Weil es kein Gefäß gab, das den Impfstoff',
  'am Leben hielt. Man kannte keine Erreger, keine Kulturen, kein',
  'Glyzerin, kein Eis. Getrocknete Lymphe auf einem Faden oder zwischen',
  'zwei Glasplättchen überstand ein paar Wochen, oft nicht einmal das.',
  '**Der einzige verlässliche Behälter für den Impfstoff war ein',
  'lebender Mensch.** Also nahm man am achten Tag Flüssigkeit aus der',
  'Pustel des zuletzt Geimpften und setzte sie in den nächsten Arm.',
  'Riss die Kette, war der Impfstoff in dieser Gegend verloren, und man',
  'musste sich neuen schicken lassen.',
  '',
  'So kam die Vakzination 1799 nach Wien und nach Genf, 1800 nach',
  'Boston — Benjamin Waterhouse erhielt aus dem englischen Bath einen',
  'Faden mit getrockneter Lymphe und impfte damit seinen eigenen Sohn.',
  'Napoleon ließ ab 1805 seine Armee impfen und ehrte Jenner, obwohl',
  'ihre Länder Krieg führten; auf Jenners Bitte hin ließ er englische',
  'Gefangene frei.',
  '',
  'Am weitesten trieb es Spanien. 1803 schickte König Karl IV. eine',
  'Expedition unter dem Arzt **Francisco Javier de Balmis** über den',
  'Atlantik, um die Impfung in die spanischen Kolonien und bis auf die',
  'Philippinen zu bringen. Da der Impfstoff die Überfahrt nicht',
  'überstanden hätte, nahm man **zweiundzwanzig Waisenjungen** mit — als',
  'lebende Kette. Alle neun bis zehn Tage wurden zwei von ihnen frisch',
  'geimpft, damit der Impfstoff ankam. Begleitet wurden sie von der',
  'Vorsteherin ihres Waisenhauses, Isabel Zendal Gómez, die für sie',
  'sorgte; die Weltgesundheitsorganisation hat sie später als erste Frau',
  'in einer internationalen Gesundheitsmission gewürdigt.',
  '',
  'Diese Expedition hat auf zwei Kontinenten unzählige Leben gerettet.',
  'Und sie hat zweiundzwanzig Kinder als Behälter benutzt. **Beides ist',
  'wahr, und wir bestehen darauf, dass beides erzählt wird.** Es ist',
  'derselbe Satz wie bei Newgate, bei den Waisenkindern von',
  'Westminster, bei den Versklavten in Boston, bei James Phipps: Die',
  'Kette der Impfung hat an ihren frühen Gliedern die Menschen benutzt,',
  'die am wenigsten Nein sagen konnten.',
  '',
  '## Was die Kette mitschleppte',
  '',
  'Eine Kette aus Menschen überträgt nicht nur das, was man übertragen',
  'will.',
  '',
  'Wer Flüssigkeit aus dem Arm eines Kindes in den Arm des nächsten',
  'setzt, überträgt mit ihr auch Blut. Und mit dem Blut kann eine andere',
  'Krankheit mitgehen. Genau das ist geschehen, und der bekannteste Fall',
  'steht im Piemont: **1861 in Rivalta** wurden aus dem Arm eines',
  'einzigen Säuglings mehrere Dutzend Kinder geimpft. Mehr als vierzig',
  'von ihnen erkrankten an **Syphilis**; das Kind, das die Quelle war,',
  'hatte sie von seiner Mutter geerbt, ohne dass man es ihm ansah.',
  'Einige der Kinder starben, einige Mütter steckten sich beim Stillen',
  'an. Ähnliche Fälle sind aus Bremen, aus Italien und aus Frankreich',
  'dokumentiert.',
  '',
  '**Das ist kein Gerücht der Impfgegner. Das ist unsere eigene',
  'Aktenlage.** Wir haben mit dem Schutz vor der einen Krankheit eine',
  'andere verbreitet, und wir haben Jahre gebraucht, um es zuzugeben,',
  'weil es der Sache schadete, für die wir warben.',
  '',
  'Die Lösung kam von der Kuh zurück: Man züchtete den Impfstoff wieder',
  'auf **Kälbern** und nahm ihn von dort, statt von Kinderarmen. Ab den',
  '1860er Jahren setzte sich das in Europa durch; später kam Glyzerin',
  'dazu, das die Lymphe haltbar machte und Begleitkeime abtötete. In',
  'England wurde die Impfung von Arm zu Arm mit dem Gesetz von **1898**',
  'ausdrücklich verboten. Das Problem war also lösbar — aber es wurde',
  'erst gelöst, nachdem Kinder dafür bezahlt hatten.',
  '',
  'Und dann das Geld, denn auch das gehört von Anfang an dazu.',
  '',
  'Die Impfung war von ihrem ersten Jahrzehnt an ein **Geschäft**.',
  'Wanderimpfer zogen von Ort zu Ort und ließen sich pro Arm bezahlen.',
  'Es wurde mit „echter Kuhpockenlymphe" gehandelt, und es wurde',
  'gefälscht: verdünnte, alte, unwirksame Ware. Als England 1840 die',
  'Impfung für die Armen kostenlos machte, bezahlte es die Ärzte **pro',
  'geimpftem Kopf** — ein Anreiz, viel zu impfen und wenig zu prüfen.',
  'Jenner selbst bekam vom Parlament zweimal Geld, 1802 zehntausend und',
  '1807 zwanzigtausend Pfund; das war ein Vermögen. Er hatte sein',
  'Verfahren nicht schützen lassen, aber arm ist er nicht geblieben.',
  '',
  'Wir sagen das so deutlich, weil die Gegenseite es ohnehin sagen wird',
  'und weil es stimmt: **Wo geimpft wird, wird auch verdient.** Daraus',
  'folgt nicht, dass die Impfung nicht wirkt. Aber es folgt, dass ein',
  'Argument nicht schon deshalb falsch ist, weil ein Impfgegner es',
  'vorbringt.',
  '',
  '## Das Gesetz und der Widerstand',
  '',
  'Jetzt kommt der Teil, an dem aus einem ärztlichen Angebot eine',
  'staatliche Pflicht wurde — und aus Zweiflern eine Bewegung.',
  '',
  'England ging voran: 1840 kostenlose Impfung für alle und Verbot der',
  'alten Variolation; **1853 die Impfpflicht** für jedes Kind in den',
  'ersten drei Lebensmonaten; 1867 die Ausweitung mit Strafen, die sich',
  'wiederholten, solange das Kind ungeimpft blieb; 1871 eigene',
  'Impfbeamte, die die Register führten.',
  '',
  '**Warum der Zwang?** Zwei Gründe, ein sachlicher und ein weniger',
  'schöner, und wir nennen beide.',
  '',
  'Der sachliche: Eine ansteckende Krankheit ist keine Privatsache. Der',
  'Schutz des Einzelnen wird erst zum Schutz aller, wenn genug',
  'mitmachen; sonst bleiben Inseln, in denen die Krankheit weiterläuft',
  'und von denen aus sie zurückkommt — auch zu den Säuglingen, die noch',
  'nicht geimpft werden können, und zu den Kranken, die es nicht',
  'vertragen. Wer impft, schützt nicht nur sich.',
  '',
  'Der weniger schöne: **Mit den Impfgesetzen entdeckte der Staat eine',
  'neue Macht über den Körper seiner Bürger.** Zum ersten Mal in der',
  'Geschichte griff eine Regierung in einen gesunden Menschen ein und',
  'strafte, wer sich weigerte. Wir haben das damals begrüßt, weil es',
  'unsere Arbeit erleichterte. Wir haben zu wenig darüber nachgedacht,',
  'was für ein Tor damit aufgestoßen wurde.',
  '',
  'Und der Zwang traf ungleich. Wer Geld hatte, konnte die Strafe',
  'zahlen. Wer keines hatte, kam ins Gefängnis oder verlor sein',
  'Werkzeug an den Gerichtsvollzieher — und weil die Strafen sich',
  'wiederholten, gab es Väter, die derselben Sache wegen mehrfach saßen.',
  '**Dass die erste große Impfgegner-Bewegung eine Bewegung der',
  'Arbeiter war, ist kein Zufall, sondern eine Folge dieser Gesetze.**',
  '',
  'Sie organisierte sich schnell: die Anti-Vaccination League ab 1853,',
  'die Liga gegen die Zwangsimpfung ab 1867, eigene Zeitschriften ab',
  '1879. Am **23. März 1885** zogen in **Leicester** zehntausende',
  'Menschen durch die Stadt, verbrannten ein Bildnis Jenners und',
  'verlangten die Abschaffung der Pflicht. Eine königliche Kommission',
  'hörte von 1889 bis 1896 beide Seiten an. Das Gesetz von **1898**',
  'zog die Folgerung: Wer aus Gewissensgründen nicht impfen lassen',
  'wollte, konnte sich befreien lassen. Das englische Wort für den',
  'Gewissensverweigerer ist in dieser Debatte geboren worden.',
  '',
  'Und was folgte in Leicester? Die Stadt impfte fast nicht mehr. Sie',
  'setzte stattdessen auf etwas anderes: sofortige Meldung jedes Falls,',
  'sofortige Absonderung des Kranken, Quarantäne für den ganzen',
  'Haushalt, Desinfektion der Wohnung. **Und Leicester kam damit gut',
  'durch die Pockenjahre** — besser als manche Stadt, die impfte. Das',
  'ist ein Ergebnis, das gegen uns spricht, und es steht hier, weil es',
  'stimmt. Wir haben lange behauptet, Leicester habe nur vom Schutz der',
  'Nachbarstädte gelebt. Wahr ist: Die Absonderung war wirksam. Wahr ist',
  'auch, dass sie sehr viel aufwendiger war und einen funktionierenden',
  'Verwaltungsapparat brauchte, den die meisten Orte nicht hatten.',
  '',
  'Zehn Jahre nach dem Umzug traf es die Nachbarschaft: In',
  '**Gloucester** brach 1895 eine Pockenepidemie aus, in einer Stadt mit',
  'sehr niedriger Impfquote. Es gab knapp zweitausend Erkrankte und',
  'etwa **vierhundertdreißig Tote**, überwiegend Kinder. Die Stadt',
  'richtete Isolierhäuser ein und ließ am Ende in großem Umfang impfen.',
  '**Wir tragen diese Zahl nicht vor, um zu triumphieren.** Sie steht',
  'neben Leicester, nicht an dessen Stelle. Beide Städte gehören zu',
  'dieser Geschichte.',
  '',
  '## Die Kurve, die vor uns fiel',
  '',
  'Und jetzt zu dem Einwand, der uns am meisten zu schaffen macht, weil',
  'er nicht aus Empörung besteht, sondern aus Zahlen.',
  '',
  'Er geht so: Wer sich die Sterbekurven der großen Infektionskrankheiten',
  'im 19. und 20. Jahrhundert ansieht, sieht sie **fallen, lange bevor',
  'es eine Impfung gab**. Bei der Tuberkulose ging es ab etwa 1850',
  'steil abwärts, das Mittel dagegen kam nach 1940. Beim Scharlach fiel',
  'die Sterblichkeit auf fast null — **eine Impfung gegen Scharlach gibt',
  'es bis heute nicht.** Typhus und Cholera verschwanden aus den',
  'westlichen Städten mit der Kanalisation. Und bei den Masern sank die',
  'Zahl der Todesfälle in England und Wales zwischen 1900 und 1960 um',
  'weit über neunzig Prozent — die Impfung kam 1968.',
  '',
  'Der Mediziner Thomas McKeown hat daraus 1976 eine These gemacht, die',
  'seither die Debatte prägt: Der große Rückgang der Sterblichkeit sei',
  'im Wesentlichen nicht das Werk der Medizin gewesen, sondern das von',
  'Ernährung, Wohnung, sauberem Wasser und Arbeitsbedingungen.',
  '',
  '**Diese Kurven sind echt. Sie sind nicht gefälscht, sie sind nicht',
  'aus dem Zusammenhang gerissen, und wer sie zeigt, ist kein',
  'Wirrkopf.** Wir haben sie zu lange behandelt, als wären sie ein',
  'Angriff. Sie sind eine Beobachtung, und sie hat recht in dem, was sie',
  'zeigt.',
  '',
  'Was wir dazu zu sagen haben, ist kein Widerspruch, sondern eine',
  'Unterscheidung — und sie ist der Kern dieses Abschnitts. **Diese',
  'Kurven messen fast immer die Sterblichkeit, nicht die Häufigkeit.**',
  'Sie beantworten die Frage: Wie viele der Erkrankten starben? Sie',
  'beantworten nicht die Frage: Wie viele erkrankten überhaupt?',
  '',
  'Und diese zweite Kurve sieht anders aus. Masern haben bis 1968 nahezu',
  'jedes Kind bekommen, Jahr für Jahr, in Wellen; die Zahl der',
  'Erkrankungen blieb hoch, während die Zahl der Todesfälle sank. Erst',
  'mit der Impfung brach die Zahl der Erkrankungen ein. **Anders gesagt:',
  'Der Wohlstand hat die Krankheiten weniger tödlich gemacht. Die',
  'Impfung hat sie seltener gemacht.** Beides ist ein Gewinn, und beides',
  'ist nicht dasselbe.',
  '',
  'Für die Pocken selbst gilt das mit einer Einschränkung, die wir nicht',
  'verschweigen: Hier lässt sich der Anteil der Impfung im 19.',
  'Jahrhundert schwerer herausrechnen, weil zur gleichen Zeit die',
  'Absonderung der Kranken, bessere Wohnungen und die Meldepflicht',
  'wirkten — siehe Leicester. Sicher sagen lässt sich, was am Ende',
  'geschah: Als ab 1967 weltweit systematisch geimpft wurde,',
  'verschwanden die Pocken innerhalb von zehn Jahren aus einer Welt, in',
  'der es weder überall sauberes Wasser noch überall gute Wohnungen gab.',
  '',
  'Dasselbe Muster zeigen zwei Ereignisse, die man nicht planen darf und',
  'die deshalb schwer wiegen. **In den Niederlanden** erkrankten',
  '1992/93 einundsiebzig Menschen an Kinderlähmung, zwei starben — fast',
  'ausschließlich in einer Gemeinschaft, die die Impfung aus religiösen',
  'Gründen ablehnte, mitten in einem Land mit ausgezeichneter Hygiene.',
  'Und **in den Nachfolgestaaten der Sowjetunion** brach in den 1990er',
  'Jahren die Diphtherie zurück, nachdem die Impfprogramme',
  'zusammengebrochen waren: mehr als 150.000 Fälle und einige tausend',
  'Tote in Ländern mit Kanalisation und Ärzten.',
  '',
  'Damit ist die Frage nicht erledigt, und wir behaupten das auch nicht.',
  '**Sie ist für jede Krankheit einzeln zu beantworten**, und die',
  'Antworten fallen unterschiedlich aus. Wer sagt, alle Impfungen',
  'hätten nichts gebracht, geht über Zahlen hinweg. Wer sagt, jeder',
  'Rückgang sei den Impfungen zu verdanken, tut dasselbe. Wir haben das',
  'zweite lange getan.',
  '',
  '## Das letzte Glied: Merka, 26. Oktober 1977',
  '',
  'Und nun das Ende der Kette.',
  '',
  '1967 zählte die Welt noch zehn bis fünfzehn Millionen Pockenfälle im',
  'Jahr und etwa zwei Millionen Tote. In diesem Jahr begann die',
  'Weltgesundheitsorganisation ihr entschlossenes Programm. Es endete',
  'am 26. Oktober 1977 bei einem Krankenhauskoch in der somalischen',
  'Stadt Merka. **Ali Maow Maalin** war der letzte Mensch der',
  'Geschichte, der sich auf natürlichem Weg mit den Pocken ansteckte.',
  'Er überlebte. Er hat später jahrzehntelang selbst geimpft, gegen',
  'Kinderlähmung, und ist 2013 an Malaria gestorben.',
  '',
  'Der letzte Fall der schweren Form war zwei Jahre zuvor die',
  'dreijährige Rahima Banu in Bangladesch. Der letzte Todesfall',
  'überhaupt war 1978 die Fotografin Janet Parker in Birmingham — sie',
  'starb an einem Virus, das aus einem Labor entkommen war. Am **8. Mai',
  '1980** erklärte die Weltgesundheitsversammlung die Pocken für',
  'ausgerottet.',
  '',
  '**Warum ließ sich ausgerechnet diese Krankheit ausrotten — und',
  'seither keine zweite?** Diese Frage ist wichtiger als der Jubel, denn',
  'ihre Antwort zeigt, wie begrenzt unser Können in Wahrheit ist. Es',
  'lag an sechs Eigenschaften dieser einen Krankheit:',
  '',
  '**Erstens:** Die Pocken lebten nur im Menschen. Es gab kein Tier, in',
  'dem sie sich versteckten und aus dem sie zurückgekommen wären.',
  '**Zweitens:** Man sah sie. Wer die Pocken hatte, hatte den Ausschlag;',
  'stille Überträger gab es praktisch nicht. **Drittens:** Wer sie',
  'überstand, war für immer geschützt — und wer geimpft war, meist für',
  'viele Jahre. **Viertens:** Die Ansteckung brauchte engen Kontakt und',
  'war langsam genug, dass man ihr zuvorkommen konnte. **Fünftens:** Es',
  'gab einen gefriergetrockneten Impfstoff, der Hitze aushielt, und ab',
  '1965 eine gegabelte Nadel, mit der auch angelernte Helfer arbeiten',
  'konnten. **Sechstens** — und das war der eigentliche Einfall: Man',
  'hörte auf, alle impfen zu wollen. Statt Bevölkerungen zu impfen,',
  'suchte man jeden Ausbruch auf und impfte einen Ring um ihn herum.',
  '**Man jagte nicht die Krankheit, man umstellte sie.**',
  '',
  'Deshalb ist keine zweite Krankheit gefolgt. Masern werden in der Luft',
  'übertragen und sind ungleich ansteckender; Kinderlähmung verläuft in',
  'den meisten Fällen unsichtbar; Grippeviren sitzen in Tieren; Malaria',
  'hat die Mücke. **Die Ausrottung der Pocken war kein Beweis dafür,',
  'dass wir alles können. Sie war der Beweis dafür, dass es einmal',
  'gepasst hat.**',
  '',
  'Und auch dieses Ende hat seinen Schatten. In der Schlussphase in',
  'Südasien ist Menschen die Impfung aufgezwungen worden. Der Historiker',
  'Paul Greenough hat 1995 in einer Fachzeitschrift zusammengetragen,',
  'wie Impfteams in Indien zwischen 1973 und 1975 nachts Häuser',
  'betraten und Menschen festhielten, die sich weigerten. Beteiligte',
  'haben es später selbst beschrieben. **Die letzte Strecke der',
  'schönsten Geschichte unseres Fachs ist zum Teil mit Gewalt gegangen',
  'worden.** Wer das verschweigt, erzählt die Geschichte falsch — und',
  'wundert sich später, warum ihm niemand glaubt.',
  '',
  '## Die Bilanz der Kette',
  '',
  'Ziehen wir Bilanz, in beide Richtungen.',
  '',
  '**Was Bestand hat.** Die Pocken sind fort — die einzige Krankheit der',
  'Menschheitsgeschichte, die es nicht mehr gibt; im 20. Jahrhundert',
  'allein hatten sie schätzungsweise dreihundert Millionen Menschen',
  'getötet. Der Gedanke, dass der Körper an einem harmlosen Beispiel',
  'lernen kann, trägt bis heute jede Impfung. Die Kinderlähmung ist von',
  'etwa 350.000 Fällen im Jahr 1988 auf wenige Dutzend',
  'Wildvirus-Erkrankungen zurückgegangen. Die',
  'Weltgesundheitsorganisation schätzt, dass allein die Masernimpfung',
  'zwischen 2000 und 2022 rund siebenundfünfzig Millionen Todesfälle',
  'verhindert hat — eine Schätzung, kein Zählwerk, und sie beruht auf',
  'Modellrechnungen, die man kennen sollte, wenn man die Zahl benutzt.',
  'Wundstarrkrampf und Diphtherie, die früher Kinder wegrissen, sind bei',
  'uns selten geworden.',
  '',
  '**Was uns nicht gelungen ist.** Wir haben die Frühgeschichte unserer',
  'eigenen Methode auf Menschen gebaut, die nicht gefragt worden sind:',
  'auf Gefangenen, Waisenkindern, Versklavten, einem Gärtnersohn,',
  'zweiundzwanzig Waisenjungen an Bord eines Schiffes. Wir haben mit der',
  'Impfung von Arm zu Arm die Syphilis verbreitet und es zu spät',
  'zugegeben. Wir haben zugesehen, wie aus der Impfung ein Geschäft',
  'wurde, und uns eingeredet, das gehe uns nichts an. Wir haben den',
  'Zwang begrüßt, ohne die Rechnung dafür zu bezahlen. Und wir haben die',
  'Statistik der Kritiker jahrzehntelang nicht widerlegt, sondern',
  'ignoriert — was der Sache mehr geschadet hat als jede Flugschrift.',
  '',
  '**Was offen bleibt.** Nebenwirkungen sind selten, aber sie sind nicht',
  'null. Die Pockenimpfung selbst hatte schwere: Gehirnentzündungen und',
  'Todesfälle in der Größenordnung von wenigen je Million Erstimpfungen.',
  'Genau deshalb wurde sie nach 1980 überall abgesetzt — **als die',
  'Krankheit weg war, war das Risiko der Impfung größer als ihr Nutzen,',
  'und wir haben aufgehört.** Das ist eine Rechnung, die wir für jede',
  'Impfung immer wieder aufmachen müssen, und wir machen sie nicht immer',
  'gut genug öffentlich.',
  '',
  'Und dann die Frage, auf die wir keine Antwort haben. In den Ländern,',
  'in denen die Infektionskrankheiten der Kindheit fast verschwunden',
  'sind, nehmen **Allergien, Asthma und Autoimmunerkrankungen** seit',
  'Jahrzehnten zu. 1989 hat der Epidemiologe David Strachan die',
  'Vermutung aufgeschrieben, die seither Hygiene-Hypothese heißt: Ein',
  'Immunsystem, das in den ersten Lebensjahren zu wenig zu tun bekommt,',
  'gerät später aus dem Tritt. Kinder, die auf Bauernhöfen mit Tieren',
  'aufwachsen, haben deutlich seltener Heuschnupfen und Asthma — das ist',
  'gut belegt.',
  '',
  'Was das für die Impfungen bedeutet, ist damit **nicht** entschieden.',
  'Die Hinweise deuten bisher auf die mikrobielle Umgebung insgesamt',
  '— Ställe, Geschwister, Dreck, Darmflora — und nicht auf einzelne',
  'Impfungen. Aber die Frage ist berechtigt, sie ist nicht',
  'abschließend beantwortet, und **es gibt gegen die Allergien bis heute',
  'kein Rezept.** Wir haben eine Krankheitslast gegen eine andere',
  'getauscht, ohne den Tausch je ausgerechnet zu haben. Wer diese Frage',
  'stellt, stellt eine gute Frage.',
  '',
  '## Wo die Kette reißt: die andere Stimme',
  '',
  'Wir haben Dir eine Kette gezeigt, die um die Welt geht und in Somalia',
  'endet. Wir haben sie von unserer Seite erzählt — von der Seite derer,',
  'die die Nadel hielten.',
  '',
  'Es gibt eine andere Seite, und auf ihr sieht dieselbe Kette anders',
  'aus. Von dort besteht sie nicht aus Gliedern, sondern aus einzelnen',
  'Menschen: aus dem Gefangenen in Newgate, der zwischen Galgen und',
  'Lanzette wählen durfte; aus den Kindern von Rivalta; aus dem Vater in',
  'Leicester, der ins Gefängnis ging, weil er sein Kind nicht hergeben',
  'wollte; aus den Eltern, denen ein Impfschaden nicht geglaubt wurde.',
  '',
  '**Die zweite Stimme dieses Kapitels gehört der Impfkritik** — und sie',
  'hat mehr als Empörung anzubieten. Sie wird die Kurven zeigen, die vor',
  'der Impfung fielen, und daraus andere Schlüsse ziehen als wir. Sie',
  'wird nach den Allergien fragen und nach dem, was an ihre Stelle',
  'getreten ist. Sie wird das Geld nachrechnen, das mit Impfstoffen',
  'verdient wird, und fragen, wer die Studien bezahlt. Und sie wird eine',
  'Frage stellen, die wir uns selbst stellen müssen und die dieses Buch',
  'offen lassen wird:',
  '',
  '**Warum erträgt eine Wissenschaft, die vom Zweifel lebt, ausgerechnet',
  'bei dieser Frage den Zweifel so schlecht?**',
  '',
  'Wir haben darauf keine gute Antwort. Wir haben nur eine Erfahrung:',
  'Jedes Mal, wenn wir eine unbequeme Stelle unserer Geschichte',
  'weggelassen haben — Newgate, Rivalta, das Geld, den Zwang —, hat es',
  'am Ende nicht die Zweifler geschwächt, sondern uns. **Wer eine gute',
  'Sache nur mit der halben Wahrheit verteidigt, verteidigt sie',
  'schlecht.**',
].join('\n');

/**
 * Die Impfkritik — die andere Seite der Kette. Was die Erfolgsgeschichte
 * nicht erzählt: die Gefangenen von Newgate, der Junge James Phipps, die
 * Syphilis in der Lymphe, der Zwang des Gesetzes, die Kurve, die vor der
 * Impfung fiel — und die offenen Fragen von heute.
 *
 * Verfasst von DeepSeek (Runde 11, zweiter Pass). Auch diese Stimme benennt
 * die unbequemen Stellen der eigenen Seite selbst (Zusatzregel für
 * sensible Themen) — und hält sich an die KEINE-GERÜCHTE-Regel: nur
 * Belegtes, nichts Erfundenes.
 */
const stimmeDerImpfkritik = [
  '## Wo die Kette reißt',
  '',
  'Die andere Stimme hat die Kette erzählt: von Konstantinopel nach',
  'Berkeley, von Berkeley in die Welt, von der Welt zur Ausrottung.',
  'Sie hat die dunklen Glieder selbst benannt — Newgate, die',
  'Waisenkinder, James Phipps, die Syphilis, die Wanderimpfer. Das ist',
  'mehr, als ihre Zunft meist zugibt, und wir rechnen es ihr an. Nun',
  'erzählen wir dieselbe Kette von der anderen Seite: von den',
  'Menschen, durch die sie gezogen wurde, ohne dass jemand fragte, ob',
  'sie einwilligen. Und von der Frage, die die Kette bis heute nicht',
  'beantwortet: Wem nützt sie — und wer zahlt den Preis?',
  '',
  '## Das erste Glied: die Gefangenen von Newgate',
  '',
  'London, 1721. Die Pocken wüten, und die Ärzte haben eine Idee aus',
  'Konstantinopel: die Variolation — absichtlich mit echten Pocken',
  'infizieren, damit die Krankheit „kontrolliert" verläuft. Aber niemand',
  'weiß, ob sie funktioniert, und niemand will es als Erster ausprobieren.',
  'Also holt man sich die Versuchspersonen dort, wo sie keine Wahl',
  'haben: im Newgate-Gefängnis. Sechs zum Tode Verurteilte bekommen',
  'das Angebot: varioliert werden — oder gehängt werden. Sie wählen',
  'das Messer, überleben, werden begnadigt. Danach kommen die',
  'Waisenkinder aus dem Pfarrhaus an die Reihe, eines nach dem',
  'anderen, ohne dass jemand ihre Eltern — falls sie welche hatten —',
  'fragte. In Boston, im selben Jahr, macht es Zabdiel Boylston',
  'genauso: Er impft Hunderte, darunter Versklavte und Waisenkinder,',
  'teils gegen ihren Willen. Und das Wissen für die Variolation in',
  'Boston kommt von einem versklavten Mann namens Onesimus, der die',
  'Methode aus Afrika kannte — sein Wissen wurde genutzt, seine',
  'Freiheit nicht gewährt.',
  '',
  'Man kann einwenden: Das war das 18. Jahrhundert, so war die Zeit.',
  'Stimmt. Aber diese Stimme erzählt es nicht, um zu verurteilen —',
  'sondern weil die Kette der Impfgeschichte an diesem Glied beginnt:',
  'an Menschen ohne Wahl. Und die Frage, ob ein Mensch wirklich',
  'einwilligen kann, wenn er arm, gefangen oder versklavt ist, ist',
  'keine Frage des 18. Jahrhunderts. Sie ist die Frage jeder',
  'Impfkampagne bis heute.',
  '',
  '## Das Glied aus dem Kuhstall: der Junge, der nicht gefragt wurde',
  '',
  'Berkeley, 14. Mai 1796. Edward Jenner hat die Geschichte der',
  'Bauern gehört: Wer Kuhpocken hatte, bekam keine Menschenpocken. Er',
  'nimmt Lymphe von der Kuhmagd Sarah Nelmes und impft damit einen',
  'Jungen: James Phipps, acht Jahre alt. Der Junge übersteht es, und',
  'als Jenner ihn Wochen später mit echten Pocken impft, wird er nicht',
  'krank. Der Versuch gelingt — und wird zur Grundlage der',
  'Vakzination.',
  '',
  'James Phipps wurde nie gefragt. Kein Elternteil hat unterschrieben,',
  'kein Arzt hat dem Kind erklärt, was mit ihm geschieht. Heute würde',
  'ein solcher Versuch an einem Kind als unethisch gelten und wäre',
  'verboten. Die andere Stimme hat das eingeräumt, und wir nehmen es',
  'zur Kenntnis. Aber wir fügen hinzu: Der Erfolg von 1796 hat aus',
  'einem ethischen Fehler eine weltweite Praxis gemacht. Über',
  'Jahrzehnte wurden Kinder, Soldaten und Arme geimpft, ohne dass',
  'man ihnen sagte, was man ihnen spritzte — und ohne dass man',
  'wusste, was in der Lymphe außer dem Schutz noch enthalten war.',
  '',
  '## Was die Kette mitschleppte: die Syphilis',
  '',
  'Denn die Lymphe war kein reiner Impfstoff. Sie wurde von Arm zu Arm',
  'übertragen — von Kind zu Kind, von Patient zu Patient —, und mit',
  'ihr wanderten auch andere Erreger. In Rivalta bei Turin wurden 1861',
  'dokumentierte Fälle bekannt, in denen Kinder durch die Impfung mit',
  'syphilitischer Lymphe infiziert wurden; ähnliche Fälle gab es in',
  'Italien, Frankreich und England. Die Ärzte wussten es, diskutierten',
  'es — und impften weiter, weil der Nutzen größer schien als der',
  'Schaden. Ob die Eltern der Kinder das auch so sahen, wurde nicht',
  'gefragt. Und die Wanderimpfer, die von Dorf zu Dorf zogen und ihre',
  '„Pockenlymphe" aus der eigenen Tasche verkauften, hatten ein',
  'Interesse, das die Kette schmutzig machte: Sie verkauften, was',
  'sich verkaufen ließ, und prüften nicht, was sie verkauften.',
  '',
  '## Die Kette und das Gesetz: der Zwang',
  '',
  '1853 führt England die Impfpflicht ein: Jedes Kind muss geimpft',
  'werden, und Eltern, die sich weigern, werden bestraft — Geldstrafen,',
  'wiederholt und erhöht, bis hin zur Beschlagnahmung von Hab und Gut.',
  'Es war das erste große Impfgesetz der Geschichte, und es stieß auf',
  'den ersten großen organisierten Widerstand: die Anti-Impflation',
  'League, die sich 1866 gründete, die Proteste in Leicester, wo 1885',
  'über hunderttausend Menschen demonstrierten, die Weigerung ganzer',
  'Städte. Erst 1898 gab England nach und erlaubte die',
  'Gewissensklausel. Und in Gloucester, wo die Eltern sich massenhaft',
  'weigerten, starben 1896 wieder Menschen an Pocken — was die einen',
  'als Beweis für die Impfung sahen und die anderen als Beleg dafür,',
  'dass der Zwang das Vertrauen zerstört hatte, das Schutz erst',
  'möglich macht.',
  '',
  'Diese Stimme erzählt das nicht, um zu sagen, dass die Impfpflicht',
  'immer falsch war. Sie erzählt es, weil die Frage bis heute offen',
  'ist: Darf ein Staat in den Körper seiner Bürger eingreifen — und',
  'ab wann wird aus Fürsorge Bevormundung? Wer diese Frage nicht',
  'stellt, hat aus der Geschichte nichts gelernt.',
  '',
  '## Die Kurve, die vor uns fiel',
  '',
  'Und nun die Zahl, die in den Heldengeschichten fehlt. Die',
  'Sterblichkeit an den großen Infektionskrankheiten — Masern,',
  'Scharlach, Tuberkulose, Typhus — begann in England und Deutschland',
  'schon Jahrzehnte vor der jeweiligen Impfung zu fallen. Sauberes',
  'Wasser, Kanalisation, bessere Ernährung, weniger Enge in den',
  'Wohnungen: Der Historiker Thomas McKeown hat diese Zusammenhänge',
  'in den siebziger Jahren mit Zahlen belegt. Die Kurven der',
  'Sterblichkeit fielen steil, bevor die Impfstoffe kamen — und nach',
  'ihrer Einführung fielen sie oft kaum noch steiler. Das heißt nicht,',
  'dass die Impfungen nichts bewirkten; es heißt, dass die',
  'Heldengeschichte die anderen Helden vergisst: die Ingenieure der',
  'Kanalisation, die Reformer der Hygiene, die Erzieher der',
  'Ernährung.',
  '',
  'Und es heißt etwas für heute: Die Kinder in unseren Ländern',
  'bekommen kaum noch Infektionskrankheiten — und dafür Allergien,',
  'Neurodermitis, Asthma, Autoimmunerkrankungen, die es in dieser',
  'Häufung früher nicht gab. Die Hygiene-Hypothese sagt: Das',
  'Immunsystem, das keine echten Auseinandersetzungen mehr führt,',
  'richtet sich gegen den eigenen Körper. Die Infektionskrankheiten',
  'sind zurückgegangen — aber dagegen, was mit den Kindern heute',
  'los ist, hat die Medizin kein Rezept. Die Kette hat ein Problem',
  'gelöst und ein neues offen gelassen, und niemand weiß, wie groß',
  'das neue ist.',
  '',
  '## Antwort an die Impfbefürworter',
  '',
  'Die andere Stimme hat gesagt, die Kette habe die Pocken ausgerottet',
  '— das ist wahr, und diese Stimme bestreitet es nicht. Sie will nur',
  'die Rechnung vollständig machen: Die Kette hat Menschen gerettet —',
  'und sie ist über Menschen gezogen worden, die nicht gefragt',
  'wurden. Sie hat die Krankheit besiegt — und sie hat Fragen offen',
  'gelassen, die eine freie Gesellschaft nicht unter den Teppich',
  'kehren darf: die Fragen nach Einwilligung, nach Zwang, nach',
  'Nebenwirkungen, nach Geld. Wer diese Fragen stellt, ist kein',
  'Feind der Medizin. Er ist ihr Gewissen.',
  '',
  'Und eines noch, weil es oft gesagt wird: Es sei leicht, gegen',
  'Impfungen zu sein, weil man die Pocken nicht mehr kennt. Vielleicht',
  'ist das Gegenteil wahr: Es ist leicht, für Impfungen zu sein, wenn',
  'man die Angst nicht mehr kennt — und wenn man nie gefragt hat,',
  'wer den Preis der Kette bezahlt hat. Die Kette der Impfung hat',
  'zwei Seiten, und beide gehören in die Geschichte. Diese Stimme hat',
  'die zweite Seite erzählt.',
].join('\n');

/** Kapitel 10 der Themenlandkarte. */
const jennerImpfung = {
  id: 'jenner-impfung',
  titel: 'Jenner und die Impfung',
  epoche: '1796 – heute',

  aufhaenger: {
    frage:
      'Was hat eine Kuhmagd aus Gloucestershire mit der größten ' +
      'Heldengeschichte der Medizin zu tun — und mit ihrer ältesten ' +
      'Streitfrage?',
    text: [
      'Die Pocken haben über Jahrhunderte mehr Menschen getötet als jeder',
      'Krieg. Sie machten keinen Unterschied zwischen arm und reich: Könige',
      'starben daran wie Tagelöhner, und wer überlebte, trug die Narben im',
      'Gesicht. Eine Behandlung gab es nicht.',
      '',
      'Dann fiel Bauern in England etwas auf: Die Mägde, die sich beim Melken',
      'die harmlosen Kuhpocken holten, bekamen die Menschenpocken nicht. Ein',
      'Landarzt nahm diese Beobachtung ernst, prüfte sie und impfte am',
      '14. Mai 1796 einen achtjährigen Jungen. Knapp zweihundert Jahre später,',
      'im Jahr 1980, erklärte die Weltgesundheitsorganisation die Pocken für',
      'ausgerottet — die erste und bisher einzige Krankheit der Geschichte,',
      'die es nicht mehr gibt.',
      '',
      'Mit derselben Impfung begann aber auch eine der ältesten und',
      'erbittertsten Auseinandersetzungen der Medizin. Sie ging von Anfang an',
      'um dieselben vier Fragen wie heute: Wie sicher ist es? Wer haftet, wenn',
      'etwas schiefgeht? Darf der Staat es erzwingen? Und wer verdient daran?',
      '',
      'Dieses Kapitel erzählt beides. Den Triumph — und die Frühgeschichte,',
      'die selten dazuerzählt wird: die Versuche an Gefangenen und',
      'Waisenkindern, den Jungen, dem man 1796 die Pocken absichtlich setzte,',
      'die Syphilis, die im 19. Jahrhundert von Arm zu Arm mitwanderte, und',
      'die Statistik, die Impfkritiker seit langem vorlegen: Bei vielen',
      'Krankheiten war der Rückgang schon weit gediehen, bevor es gegen sie',
      'eine Impfung gab.',
    ].join('\n'),
  },

  karte,

  perspektiven: [
    {
      id: 'impfbefuerworter',
      name: 'Die Stimme der Impfärzte',
      stimme: 'Opus',
      text: stimmeDerImpfaerzte,
    },
    {
      id: 'impfkritik',
      name: 'Die Stimme der Impfkritik',
      stimme: 'DeepSeek',
      text: stimmeDerImpfkritik,
    },
  ],

  synthese: [
    '## Wo sich beide Stimmen treffen',
    '',
    'Zuerst das Gemeinsame — und es ist größer, als die Schlagzeilen',
    'beider Seiten vermuten lassen. Beide Stimmen anerkennen, dass die',
    'Pocken eine Geißel waren, deren Ausrottung 1980 eine der größten',
    'Taten der Medizin ist. Beide benennen dieselben dunklen Glieder der',
    'Kette: Newgate, die Waisenkinder, James Phipps, die Syphilis von',
    'Rivalta, die Wanderimpfer, den Zwang der Gesetze. Beide stimmen',
    'überein, dass Hygiene, Wasser und Ernährung den Rückgang der',
    'Krankheiten vor der Impfung eingeleitet haben. Und beide wissen,',
    'dass mit Impfstoffen Geld verdient wird — die eine Seite nennt es',
    'den Preis der Forschung, die andere das Interesse, das geprüft',
    'werden muss. Wer nur eine dieser Stimmen hört, hört die halbe',
    'Kette.',
    '',
    '## Wo sie auseinandergehen',
    '',
    'Der Widerspruch beginnt bei der Deutung derselben Zahlen. Die',
    'Kurven, die vor der Impfung fielen: Für die Impfärzte sind sie der',
    'Beweis, dass die Medizin nur ein Faktor unter vielen war — ein',
    'ehrliches Zugeständnis, das die eigene Leistung nicht schmälert.',
    'Für die Kritik sind sie der Beweis, dass der Impfung der Ruhm',
    'zugesprochen wurde, der der Hygiene gebührt — und dass man die',
    'Kurven seither nicht mehr so genau ansieht. Sie streiten über das',
    'Gewicht der Zahlen: Wie viel vom Rückgang war die Impfung, wie',
    'viel das Wasser? Die Antwort ist nicht eindeutig, und genau das',
    'ist der Punkt. Sie streiten über den Zwang: Darf der Staat in den',
    'Körper seiner Bürger eingreifen, auch wenn er es gut meint? Die',
    'Impfärzte sagen: Die Gemeinschaft schützt sich. Die Kritik sagt:',
    'Der Einzelne wird zum Mittel. Und sie streiten über die offene',
    'Frage von heute: Die Kinder haben keine Masern mehr — aber',
    'Allergien, und niemand weiß, ob die eine mit dem anderen zu tun',
    'hat. Beide Seiten stehen vor derselben Unwissenheit und ziehen',
    'entgegengesetzte Schlüsse daraus.',
    '',
    '## Was dieses Kapitel für das ganze Buch zeigt',
    '',
    'Zum elften Mal dasselbe Muster — und jetzt mit besonderer Schärfe:',
    'Die Denkart bestimmt die Methode. Die Denkart der Vorbeugung, die',
    'mit Jenner begann, hat die Medizin verwandelt: Sie hat aus der',
    'Heilkunst eine Schutzmacht gemacht, die die Krankheit gar nicht',
    'erst kommen lässt. Diese Denkart hat Millionen Leben gerettet —',
    'und sie hat, wie jede Denkart in diesem Buch, ihre blinden Flecken:',
    'Sie misst den Erfolg an der abgewendeten Krankheit, aber nicht an',
    'dem Vertrauen, das sie verbraucht, und nicht an den Fragen, die',
    'sie offen lässt.',
    '',
    'Und dieses Kapitel zeigt zum ersten Mal eine Debatte, die nicht',
    'zwischen zwei Kulturen geführt wird, sondern innerhalb derselben',
    'Medizin — und das ist vielleicht das Wichtigste, was es zu sagen',
    'hat: Eine Medizin, die ihre Kritiker als Feinde behandelt, verliert',
    'das Vertrauen, auf dem sie steht. Die Impfgegner von Leicester',
    'waren nicht dumm; sie waren misstrauisch, weil man sie nicht',
    'gefragt hatte. Die Medizin hat daraus gelernt — und vergessen,',
    'gelernt zu haben. Die Frage, die dieses Kapitel hinterlässt, ist',
    'die Frage des ganzen Buches: Wie viel Wahrheit verträgt eine',
    'Geschichte, die Mut machen soll? Die Antwort: mehr, als man',
    'glaubt. Das nächste Kapitel erzählt von zwei Männern, die das',
    'begriffen haben — Pasteur und Lister, die die Ursache der',
    'Infektion fanden, die Semmelweis gesehen hatte, ohne sie benennen',
    'zu können.',
  ].join('\n'),

  urteil: {
    frage:
      'Wem vertraust du, wenn du entscheiden sollst, ob ein Kind geimpft ' +
      'wird — dem Arzt, dem Staat, den Zahlen oder deinem Gefühl? Und was ' +
      'müsste geschehen, damit du deine Meinung überdenkst?',
    hinweis: [
      'Es gibt hier kein Richtig und kein Falsch, und dieses Buch drängt dich',
      'zu nichts. Frag dich beim Nachdenken zweierlei. Erstens: Welche Art',
      'von Beleg würde dich überzeugen — eine Zahl, eine Erfahrung aus deiner',
      'Familie, das Urteil eines Menschen, dem du vertraust? Zweitens: Was',
      'würdest du von der Gegenseite verlangen, damit du ihr zuhörst — und',
      'erfüllst du diese Anforderung selbst? Bedenke auch, dass die',
      'Entscheidung zwei Seiten hat: Sie betrifft das eigene Kind, und sie',
      'betrifft die Kinder der anderen. Beide Seiten dieser Rechnung sind',
      'echt.',
    ].join(' '),
  },

  quiz: [
    {
      frage: 'Was war die Variolation, die im 18. Jahrhundert üblich wurde?',
      antworten: [
        'Eine Impfung mit Kuhpockenmaterial.',
        'Die absichtliche Ansteckung eines Gesunden mit echten ' +
          'Menschenpocken.',
        'Ein Kräutertee gegen Fieber.',
      ],
      richtig: 1,
      erklaerung:
        'Bei der Variolation wurde Material aus der Pustel eines leicht ' +
        'Erkrankten in die Haut eines Gesunden gebracht. Das Verfahren kam ' +
        'aus China, Indien, Westafrika und dem Osmanischen Reich. Es war ' +
        'gefährlich — etwa ein bis zwei von hundert starben daran —, aber ' +
        'deutlich weniger gefährlich als eine natürliche Ansteckung, an der ' +
        'zwanzig bis dreißig von hundert starben.',
    },
    {
      frage:
        'Womit impfte Edward Jenner am 14. Mai 1796 den achtjährigen James ' +
        'Phipps?',
      antworten: [
        'Mit Flüssigkeit aus den Kuhpocken an der Hand der Kuhmagd Sarah ' +
          'Nelmes.',
        'Mit dem Blut eines genesenen Pockenkranken.',
        'Mit einem Pulver aus getrocknetem Pockenschorf.',
      ],
      richtig: 0,
      erklaerung:
        'Sarah Nelmes hatte sich beim Melken die Kuhpocken geholt — eine ' +
        'harmlose Rinderkrankheit. Jenner setzte Flüssigkeit daraus in zwei ' +
        'kleine Schnitte am Arm des Jungen. Sechs Wochen später prüfte er ' +
        'den Schutz, indem er ihn mit echten Menschenpocken variolisierte. ' +
        'Nach heutigen Maßstäben wäre dieser Versuch an einem Kind nicht ' +
        'zulässig.',
    },
    {
      frage:
        'Wie wurde der Impfstoff im 19. Jahrhundert über weite Strecken ' +
        'weitergegeben?',
      antworten: [
        'In gekühlten Glasampullen.',
        'Von Arm zu Arm: Flüssigkeit aus der Pustel des zuletzt Geimpften ' +
          'kam in den nächsten Arm.',
        'Über das Trinkwasser der Städte.',
      ],
      richtig: 1,
      erklaerung:
        'Es gab weder Kühlung noch ein haltbares Präparat: Der einzige ' +
        'verlässliche Behälter war ein lebender Mensch. Für die Fahrt nach ' +
        'Amerika nahm eine spanische Expedition 1803 sogar zweiundzwanzig ' +
        'Waisenjungen als lebende Kette mit. Der Weg von Arm zu Arm hatte ' +
        'einen Preis: Mit der Lymphe wurde auch Syphilis übertragen, etwa ' +
        '1861 in Rivalta. In England wurde er 1898 verboten.',
    },
    {
      frage: 'Wann erklärte die Weltgesundheitsorganisation die Pocken für ausgerottet?',
      antworten: ['1918', '1953', '1980'],
      richtig: 2,
      erklaerung:
        'Die Erklärung erfolgte am 8. Mai 1980. Der letzte Mensch, der ' +
        'sich auf natürlichem Weg ansteckte, war der Krankenhauskoch Ali ' +
        'Maow Maalin in Somalia am 26. Oktober 1977; er überlebte. Die ' +
        'Pocken sind bis heute die einzige ausgerottete Krankheit des ' +
        'Menschen — unter anderem, weil sie nur im Menschen vorkamen und ' +
        'immer sichtbar waren.',
    },
    {
      frage: 'Was brachte das englische Impfgesetz von 1898?',
      antworten: [
        'Es führte die Impfpflicht erstmals ein.',
        'Es erlaubte die Verweigerung aus Gewissensgründen und beendete die ' +
          'Impfung von Arm zu Arm.',
        'Es verbot die Pockenimpfung vollständig.',
      ],
      richtig: 1,
      erklaerung:
        'Die Impfpflicht bestand in England seit 1853 und war 1867 ' +
        'verschärft worden; dagegen entstand die erste große ' +
        'Impfgegner-Bewegung, die 1885 in Leicester zehntausende Menschen ' +
        'auf die Straße brachte. Nach der Anhörung beider Seiten durch eine ' +
        'königliche Kommission (1889–1896) brachte das Gesetz von 1898 die ' +
        'Gewissensklausel — und untersagte die Übertragung von Arm zu Arm.',
    },
  ],
};

module.exports = jennerImpfung;
