// Kapitel 17 — „Kneipp und die Naturheilkunde".
//
// Das neunte Kapitel der Neuzeit — und nach der Homöopathie das zweite,
// das dem Betreiber besonders am Herzen liegt: Er ist Heilpraktiker und
// steht selbst in dieser Tradition. Deshalb gilt hier die ausdrückliche
// Vorgabe aus CLAUDE.md: Die Naturheilkunde wird NICHT belächelt und
// nicht als Aberglaube abgetan. Sie bekommt ihre besten Argumente, ihre
// eigene Denkart und ihre eigene Stimme — und sie benennt ihre
// unbequemen Stellen selbst.
//
// Die DENKART-Analyse ist das Herzstück (Betreiber-Vorgabe). Sie fragt
// hier: Weshalb kaltes Wasser? (Weil der kurze Kältereiz eine Antwort des
// Körpers auslöst — Gefäßenge, dann Gefäßweite, dann Wärme; nicht das
// Wasser heilt, sondern die Reaktion darauf.) Weshalb Bewegung? (Weil
// der Körper für Bewegung gebaut ist und im Stillstand verfällt.)
// Weshalb Ernährung? (Weil das, was täglich in den Menschen hineingeht,
// stärker wirkt als jede Arznei, die er selten nimmt.) Weshalb
// Heilpflanzen? (Weil die milde Gabe stützen soll, statt zu erzwingen.)
// Weshalb Ordnung? (Weil die Lebensweise die Ursache ist, an der alles
// andere hängt.) Über allem steht die Grundannahme der ganzen
// Naturheilkunde: die Selbstheilungskraft — vis medicatrix naturae.
//
// DIE BRÜCKE ZU KAPITEL 18 (Betreiber-Vorgabe): Kneipps fünf Säulen sind
// der historische Vorläufer der Betreiber-These „Die einfache Medizin" —
// Bewegung, gesunde Ernährung, gutes soziales Umfeld und wenig Stress.
// Was der Wasserpfarrer vor hundertfünfzig Jahren predigte, empfiehlt die
// moderne Medizin heute als Prävention, meist ohne seinen Namen zu
// nennen. Diese Brücke steht am Ende der Stimme, mitsamt der ehrlichen
// Gegenseite (die Strukturen, die einen gesunden Lebensstil erschweren).
//
// KEINE GERÜCHTE (Betreiber-Entscheid 25.08.2026): Nur Belegtes.
// Stefansried 1821, Grönenbach und Kaplan Merkle, Dillingen ab 1844,
// Hahns Wasserbuch von 1738, die Donaubäder im Winter 1849, die
// Priesterweihe 1852, Wörishofen ab 1855, „Meine Wasserkur" 1886, der
// Tod am 17. Juni 1897 — alles aktenkundig. Die Diagnose seiner
// Studentenkrankheit dagegen ist historisch NICHT gesichert (oft als
// Tuberkulose überliefert); der Text sagt das ausdrücklich dazu. Ebenso
// ausdrücklich: Die Selbstheilung im kalten Wasser ist ein Bericht, kein
// Nachweis. Unbelegte Wundergeschichten bleiben außen vor.
//
// DER INNOVATIONS-ZYKLUS (Betreiber-Beobachtung 26.08.2026, roter Faden):
// Auch hier steht das Muster quer. Die Naturheilkunde hat nicht erst
// geschadet und dann geholfen — sie war von Anfang an sanft. Ihr Risiko
// liegt an zwei anderen Stellen: bei den harten Wasserkuren des frühen
// 19. Jahrhunderts, die Menschen überforderten, und in dem, was aus der
// billigen Idee wurde, sobald sie Erfolg hatte — ein Geschäft. Die
// Stimme benennt beides selbst.
//
// LÄNGENREGEL (Betreiber-Feedback 24.08.2026): Ab Kapitel 9 gilt die
// Umkehrung — vollständig und ausführlich. Gemessen wird in
// tests/karte-kneipp.mjs.
//
// Stimmen (Runde 18): Die ERSTE Perspektive — die Naturheilkunde von
// innen, die Stimme des Wassers — verfasste Opus. Die ZWEITE (die
// Schulmedizin: die eigene Arroganz gegenüber dem „Wasserpfarrer", das
// Verspotten statt Prüfen, die späte Anerkennung der Lebensweise als
// Medizin, die Studienlage und die ehrliche Kritik) und die finale
// Synthese ergänzte Hermes im zweiten Pass (Hermes-Pass, 28.08.2026:
// „ergänzt"). Perspektiven-Workflow: CLAUDE.md.
//
// KEINE WIEDERHOLUNGEN (Betreiber-Entscheid vom 21.08.2026): Kapitel 1
// gliedert nach „Wer hier spricht", Kapitel 2 beginnt mit einer Szene,
// Kapitel 3 erzählt einen Tageslauf, Kapitel 4 ist ein Briefwechsel,
// Kapitel 5 die Reise eines Buches, Kapitel 6 ein Rundgang, Kapitel 7 ein
// Prozess, Kapitel 8 eine Rechnung, Kapitel 9 eine Uhr, Kapitel 10 eine
// Kette, Kapitel 11 eine Linse, Kapitel 12 ein Interview, Kapitel 13 eine
// Akte, Kapitel 14 ein Beipackzettel, Kapitel 15 eine Pressekonferenz,
// Kapitel 16 das Telefon. Dieses Kapitel wählt die achtzehnte
// Dramaturgie: DAS WASSER SELBST. Der Regen über dem Allgäu, die Quelle,
// die Donau bei Dillingen, der Trog in Wörishofen, das Wassertreten —
// das Wasser erzählt, was mit ihm gemacht wurde und was es im Körper
// anrichtet. Die zweite Stimme kann in dieselbe Form treten: dasselbe
// Wasser, aber im Messglas — die Frage, was sich davon nachweisen lässt.
//
// Die Texte liegen als Zeilen-Arrays mit `.join('\n')` — so bleiben sie im
// Repo bei ~72 Zeichen lesbar (der Betreiber liest sie hier gegen), und
// utils/markdown.js macht in der App wieder fließenden Text daraus.
//
// CommonJS ohne UI-Importe (Architektur-Regel): mit blankem `node` prüfbar.

const { karte } = require('./karten/kneipp');

/**
 * Die Stimme des Wassers — die Naturheilkunde von innen.
 *
 * Verfasst von Opus (Runde 18). Eine Stimme, die für die Seite spricht,
 * die mit den billigsten Mitteln der Welt arbeitet, seit hundertfünfzig
 * Jahren Zulauf hat und trotzdem belächelt wird: ihre Denkart, ihre
 * Geschichte, ihre Erfahrung. Sie erzählt, weshalb sie tut, was sie tut —
 * und sie benennt die unbequemen Stellen selbst (Zusatzregel für sensible
 * Themen in CLAUDE.md).
 */
const stimmeDesWassers = [
  '## Der Regen über dem Allgäu',
  '',
  'Ich falle als Regen über dem Allgäu. Erst als Nebel, der an den',
  'Fichten hängt, dann als Tropfen, die im Moos versickern. Unter der',
  'Erde sammle ich mich, laufe durch Kies und Sand und komme irgendwo',
  'an einem Hang wieder heraus — kalt, klar, sechs oder acht Grad, das',
  'ganze Jahr hindurch fast gleich. Von dort geht es in einen Bach, in',
  'die Iller, in die Donau, ins Schwarze Meer und irgendwann wieder in',
  'eine Wolke.',
  '',
  'Auf diesem Weg bin ich immer wieder durch Menschen hindurchgegangen.',
  'Ich habe in Trögen gestanden, in denen Kranke bis an die Knie',
  'stapften. Ich bin aus Gießkannen ohne Brause über Rücken gelaufen,',
  'die vorher noch nie kaltes Wasser gespürt hatten. Ich habe in',
  'Leintüchern gelegen, die man Fiebernden um den Leib gewickelt hat.',
  'Und einmal, im Winter 1849, ist ein junger, sehr kranker',
  'Theologiestudent in mich hineingestiegen — in die Donau bei',
  'Dillingen, zwischen Eisschollen, für ein paar Augenblicke, mehrmals',
  'in der Woche. Aus diesem Mann wurde ein Pfarrer, den die halbe Welt',
  'kannte.',
  '',
  '**Was Du hier liest, ist die Naturheilkunde von innen — eine Denkart,',
  'keine Wahrheit.** Ich spreche für die Seite, die mit den billigsten',
  'Mitteln arbeitet, die es gibt: Wasser, Gehen, Brot, Kräuter, Schlaf.',
  'Ich werde ihre besten Gründe vortragen, so stark ich kann. Und ich',
  'werde die Stellen, an denen wir schlecht dastehen, selbst benennen,',
  'statt zu warten, bis es ein anderer tut.',
  '',
  'Die Frage, um die es geht, ist nämlich nicht, ob ich nass bin. Sie',
  'lautet:',
  '',
  '**Kann ein Mensch gesund werden, ohne dass ihm etwas gegeben wird —',
  'nur dadurch, dass er anders lebt? Und wenn ja: Weshalb wird das so',
  'schwer verschrieben und so leicht belächelt?**',
  '',
  '## Der Weberssohn, der mich schöpfte',
  '',
  '**Am 17. Mai 1821 wird in Stefansried Sebastian Kneipp geboren**,',
  'einem Weiler von wenigen Höfen bei Ottobeuren im bayerischen Allgäu.',
  'Sein Vater ist Weber. Das heißt in dieser Zeit: Er sitzt im Winter am',
  'Webstuhl, verdient wenig, und wenn die Fabriken in Augsburg die',
  'Preise drücken, verdient er gar nichts.',
  '',
  'Der Junge hütet Vieh, geht als Taglöhner aufs Feld und sitzt mit elf',
  'Jahren selbst am Webstuhl. Die Dorfschule bringt ihm Lesen,',
  'Schreiben, Rechnen bei, und damit sollte es das gewesen sein. Er',
  'will aber Priester werden. Für einen Weberssohn ohne Latein und ohne',
  'Geld ist das ungefähr so aussichtsreich wie eine Reise zum Mond.',
  '',
  'Es kommen zwei Dinge dazwischen. Das eine ist ein Unglück: **Nach der',
  'Überlieferung brennt 1841 das Elternhaus ab**, und mit ihm das',
  'wenige Ersparte. Das andere ist ein Mensch. Im Nachbarort Grönenbach',
  'gibt ihm **Kaplan Matthias Merkle** Unterricht im Lateinischen und',
  'setzt sich dafür ein, dass der junge Mann eine Schule von innen',
  'sieht. **1844 wird Kneipp in das Gymnasium in Dillingen an der Donau',
  'aufgenommen — dreiundzwanzig Jahre alt, unter Vierzehnjährigen.**',
  '',
  'Ich halte an dieser Stelle kurz an, weil sie mehr erklärt als jede',
  'Theorie. Alles, was dieser Mann später anbietet, ist kostenlos oder',
  'fast kostenlos. Ein Guss kostet nichts. Barfußgehen kostet nichts.',
  'Ein Wickel kostet ein Leintuch. Die Kräuter wachsen am Wegrand. Eine',
  'Heilkunde für Leute, die keinen Arzt bezahlen können, wird nicht am',
  'Schreibtisch erfunden. **Sie wird von jemandem erfunden, der selbst',
  'keinen bezahlen konnte.**',
  '',
  '## Die Donau bei Dillingen, Winter 1849',
  '',
  'In Dillingen holt der späte Schüler das Gymnasium nach und studiert',
  'danach am Lyzeum weiter. Und irgendwann in diesen Jahren wird er',
  'krank. Richtig krank.',
  '',
  '**Überliefert ist ein zehrendes Lungenleiden — Husten, Auswurf,',
  'Erschöpfung, Gewichtsverlust; meist wird daraus Tuberkulose gemacht.',
  'Ich sage ausdrücklich dazu: Diese Diagnose ist historisch nicht',
  'gesichert.** Es gibt keinen Befund, kein Röntgenbild — Röntgen wird',
  'erst 1895 geboren, was seine Strahlen angeht —, keinen',
  'Erregernachweis. Was es gibt, sind Beschreibungen von Beschwerden und',
  'die Einschätzung der Ärzte jener Jahre, dieser Student werde nicht',
  'alt. Mehr weiß niemand, und wer mehr behauptet, erfindet.',
  '',
  '**1849 stößt Kneipp auf ein altes Buch**: die Schrift des',
  'schlesischen Stadtarztes **Johann Siegmund Hahn (1696–1773)** mit dem',
  'sperrigen Titel „Unterricht von der Krafft und Würckung des frischen',
  'Wassers in die Leiber der Menschen", **zuerst 1738 gedruckt**. Wo',
  'genau er sie gefunden hat — in der Bibliothek in Dillingen, später in',
  'München —, wird verschieden berichtet; das Buch selbst ist',
  'unstrittig.',
  '',
  'Und dann tut er das, was Menschen tun, denen nichts mehr zu verlieren',
  'bleibt: **Er probiert es an sich aus.** Im Winter geht er zur Donau,',
  'mehrmals in der Woche. Er zieht sich aus, taucht für ein paar',
  'Augenblicke unter — nicht länger — und läuft dann im Laufschritt',
  'zurück in seine Stube, bis ihm heiß wird.',
  '',
  'Nach seiner eigenen Darstellung wird er dadurch kräftiger, hustet',
  'weniger, hält das Studium durch und wird schließlich achtundsiebzig',
  'Jahre alt.',
  '',
  'Jetzt kommt der Satz, den meine Seite nicht gern schreibt, der aber',
  'in dieses Buch gehört: **Das ist keine belegte Heilung. Das ist ein',
  'Bericht.** Ein einzelner Mensch, keine Vergleichsgruppe, keine',
  'Messung, keine gesicherte Ausgangsdiagnose. Wenn es keine Tuberkulose',
  'war, sondern eine langwierige, aber ausheilende Entzündung, wäre er',
  'vielleicht auch ohne mich wieder gesund geworden. **Ich kann das',
  'nicht ausschließen, und ich tue nicht so, als könnte ich es.**',
  '',
  'Was sich sagen lässt, ist etwas Kleineres und trotzdem nicht nichts:',
  'Ein junger Mann, den die Ärzte aufgegeben hatten, begann, täglich',
  'etwas für seinen Körper zu tun — kalt baden, laufen, früh aufstehen,',
  'einfach essen —, und es ging ihm besser. Aus dieser Erfahrung ist',
  'eine Heilkunde geworden, die Millionen Menschen benutzt haben. **Ob',
  'die Erfahrung richtig gedeutet wurde, ist die eigentliche Frage',
  'dieses Kapitels.**',
  '',
  '## Zwei, die vor ihm in mich stiegen',
  '',
  'Damit kein falscher Eindruck entsteht: **Kneipp hat mich nicht',
  'erfunden.** Menschen baden seit es Menschen gibt, und das kalte',
  'Wasser als Heilmittel ist so alt wie die Heilkunde selbst. Die',
  'griechischen Ärzte kannten es, die römischen Bäder lebten davon, und',
  'in den Klöstern dieses Buches gehörte das Bad zur Krankenpflege.',
  '',
  'Zwei Namen stehen unmittelbar vor ihm.',
  '',
  'Der eine ist **Johann Siegmund Hahn**, dessen Buch von 1738 Kneipp in',
  'die Hand fiel. Hahn war ein studierter Arzt und schrieb gegen die',
  'Mode seiner Zeit an: Statt Aderlass und Abführen empfahl er kaltes',
  'Wasser, innerlich und äußerlich. Er wurde weitgehend übergangen.',
  '',
  'Der andere ist **Vincenz Prießnitz (1799–1851)**, ein Bauernsohn aus',
  'Gräfenberg in Österreichisch-Schlesien, der ab den 1820er Jahren eine',
  'Wasserheilanstalt betrieb und aus halb Europa Gäste anzog — ohne',
  'jede ärztliche Ausbildung, wogegen die Ärzteschaft prozessierte.',
  '',
  'Und hier gleich die erste unbequeme Stelle, die ich selbst aufmache:',
  '**Die Wasserkuren dieser Jahrzehnte waren oft brutal.** Stundenlange',
  'Packungen, eiskalte Sturzbäder aus großer Höhe, Kuren, die die',
  'Kranken erschöpften statt sie zu kräftigen. Es gab Wasserdoktoren,',
  'die mit derselben Härte behandelten, mit der die Schulmedizin',
  'aderließ — nur eben mit mir statt mit dem Messer. **Wer glaubt, die',
  'sanfte Medizin sei immer sanft gewesen, hat das 19. Jahrhundert nicht',
  'gelesen.**',
  '',
  'Das Bemerkenswerte an Kneipp ist gerade, dass er aus diesem Fehler',
  'gelernt hat. Er begann selbst hart — die Donau im Januar ist kein',
  'Kinderbad — und wurde über vierzig Jahre hinweg immer milder. **Kurze',
  'Reize statt langer. Kalt nur auf den warmen Körper. Nie bis zum',
  'Frieren. Danach Bewegung, bis die Wärme zurück ist.** Das ist keine',
  'Verwässerung seiner Lehre, das ist ihr Kern: Ein Reiz soll den Körper',
  'anstoßen, nicht überfordern.',
  '',
  '## Der Kaplan, der zu den Cholerakranken ging',
  '',
  '**1850 geht Kneipp zum Abschluss des Studiums nach München, am',
  '6. August 1852 wird er in Augsburg zum Priester geweiht.** Es folgen',
  'Kaplansjahre in Biberbach und in **Boos im Illertal**.',
  '',
  'Dort steht er 1854 vor einer Cholerawelle. Er pflegt die Kranken,',
  'geht in die Häuser, versorgt sie und wendet auch Wasseranwendungen',
  'an. Im Dorf nennen sie ihn danach den „Cholera-Kaplan".',
  '',
  '**Was diese Anwendungen medizinisch bewirkt haben, weiß ich nicht,',
  'und ich behaupte es auch nicht.** Cholera tötet durch',
  'Flüssigkeitsverlust; was hilft, ist Trinken — dass man das mit Salz',
  'und Zucker im Wasser noch viel besser kann, wurde erst im 20.',
  'Jahrhundert verstanden. Ein Geistlicher, der den Kranken Wasser gab',
  'und sie wusch, tat also womöglich genau das Richtige, ohne den Grund',
  'zu kennen. Es kann aber auch sein, dass die Überlebenden ohnehin',
  'überlebt hätten.',
  '',
  'Belegt ist etwas anderes, und es zählt für diese Geschichte mehr:',
  '**Er ging zu ihnen hin.** In einer Zeit, in der viele die Häuser der',
  'Cholerakranken mieden, saß dieser Kaplan an ihren Betten. Der Ruf,',
  'der ihm später vorauseilte, beginnt nicht mit einer Heilung. Er',
  'beginnt damit, dass jemand blieb.',
  '',
  '**Im Mai 1855 wird Kneipp als Beichtvater der Dominikanerinnen nach',
  'Wörishofen versetzt** — ein Dorf mit wenigen hundert Einwohnern',
  'zwischen Wertach und Mindel. Er bleibt zweiundvierzig Jahre und',
  'verlässt es nicht mehr. Er verwaltet das Klostergut, hält',
  'Landwirtschaftskurse für die Bauern, züchtet Bienen, kümmert sich um',
  'Obstbäume — **und behandelt Kranke, die ihn darum bitten.** Zuerst',
  'Nachbarn. Dann Leute aus der Umgebung. Dann Fremde. **1881 wird er',
  'Pfarrer des Ortes.**',
  '',
  '## Was ich im Körper anrichte — und was nicht',
  '',
  'Jetzt zum Kern. Weshalb sollte ausgerechnet ich, gewöhnliches kaltes',
  'Wasser, irgendetwas heilen können?',
  '',
  'Die Antwort der Naturheilkunde beginnt mit einem Satz, der alles',
  'andere trägt — und der zweitausend Jahre alt ist. Er stammt aus der',
  'Schule des Hippokrates und heißt **vis medicatrix naturae: die',
  'heilende Kraft der Natur.** Auf Deutsch und ohne Latein:',
  '',
  '**Der Körper heilt sich selbst. Alles, was ein Behandler tun kann,',
  'ist, ihm dabei nicht im Weg zu stehen — und ihn zu stützen.**',
  '',
  'Das ist keine Frömmigkeit, das ist Beobachtung. Eine Schnittwunde',
  'schließt sich. Ein Knochen wächst zusammen. Ein Schnupfen geht nach',
  'einer Woche, mit Behandlung nach sieben Tagen. Kein Arzt und kein',
  'Pfarrer macht das; sie schaffen Bedingungen. **Die',
  'Selbstheilungskraft ist die einzige Kraft, die in dieser Rechnung',
  'überhaupt heilt. Alles andere sind Anstöße.**',
  '',
  'Daraus folgt ein anderer Krankheitsbegriff. Nach dieser Denkart ist',
  'Krankheit kein Ding, das man bekommt wie einen Brief, sondern die',
  'Anzeige, dass ein Gleichgewicht gestört ist: zwischen Anstrengung und',
  'Ruhe, zwischen Wärme und Kälte, zwischen Essen und Hunger, zwischen',
  'Arbeit und Schlaf. **Der kranke Mensch ist nicht befallen, er ist aus',
  'dem Lot.** Und die Behandlung arbeitet nicht gegen die Krankheit,',
  'sondern für die Kraft, die den Menschen wieder ins Lot bringt.',
  '',
  'Und nun die eigentliche Frage:',
  '',
  '**Weshalb kaltes Wasser?**',
  '',
  'Weil ich ein **Reiz** bin und sonst nichts. Ich enthalte keinen',
  'Wirkstoff. Ich bin Wasser. Was ich tue, tut nicht das Wasser, sondern',
  '**die Antwort des Körpers darauf** — und diese Antwort ist',
  'beobachtbar, seit es Menschen gibt, und heute auch messbar:',
  '',
  '- Treffe ich kalt auf die Haut, ziehen sich die kleinen Gefäße',
  '  zusammen. Das Blut weicht nach innen aus, in die Tiefe, zu den',
  '  Organen.',
  '- Der Reiz dauert kurz — bei Kneipp Sekunden. Dann bin ich wieder',
  '  weg.',
  '- Und jetzt kommt das Eigentliche: Der Körper antwortet mit einer',
  '  **Gegenbewegung**. Die Gefäße weiten sich, das Blut schießt zurück',
  '  in die Haut, sie wird rot und warm, der Mensch fühlt sich',
  '  durchströmt. Diese Wärme kommt nicht von mir. **Ich bin kalt. Die',
  '  Wärme macht er selbst.**',
  '',
  'Genau das ist die Begründungslogik der ganzen Kneipp-Kur, und man',
  'kann sie in einem Satz sagen: **Nicht die Anwendung wirkt, sondern',
  'die Reaktion auf die Anwendung.** Deshalb die eiserne Regel, die',
  'Kneipp seinen Leuten einbläute — und die jeder kennen sollte, der',
  'kalt duschen will:',
  '',
  '- **Kalt nur auf den warmen Körper.** Wer friert, hat nichts zu',
  '  antworten.',
  '- **Kurz, nicht lang.** Der Reiz ist ein Anstoß, keine Prüfung.',
  '- **Danach Bewegung oder Bett, bis die Wärme wieder da ist.** Bleibt',
  '  sie aus, war die Anwendung falsch.',
  '',
  'Und weshalb der ständige Wechsel von Warm und Kalt, die Wechselgüsse,',
  'die Wechselbäder? Weil ein Gefäß ein Muskel ist wie jeder andere:',
  '**Was regelmäßig geübt wird, wird geübter.** Die Naturheilkunde nennt',
  'das **Abhärtung** und meint damit nicht Härte, sondern',
  'Anpassungsfähigkeit — dass ein Körper mit Kälte, Hitze, Zugluft und',
  'Anstrengung besser umgehen lernt, wenn er sie kennt.',
  '',
  'Und jetzt die ehrliche Bilanz, denn ohne sie wäre das hier Werbung.',
  '',
  '**Was gut belegt ist:** Kälte verengt und Wärme weitet die Gefäße,',
  'das ist gemessen. Ein kalter Reiz steigert kurzfristig Herzschlag,',
  'Atmung und die Ausschüttung von Stresshormonen; der Körper stellt auf',
  'Wachheit. Regelmäßige Kältereize verändern messbar, wie schnell und',
  'wie gut sich jemand danach wieder erwärmt.',
  '',
  '**Was schwach belegt ist:** dass daraus Gesundheit im Großen wird. Es',
  'gibt dazu ein paar hübsche Untersuchungen — die bekannteste ist eine',
  'niederländische Arbeit von 2016, bei der über dreitausend Menschen',
  'einen Monat lang ihre Duschen kalt beendeten; in der Kaltduschgruppe',
  'lagen die Krankmeldungen rund neunundzwanzig Prozent niedriger,',
  'während die Zahl der Krankheitstage sich nicht unterschied.',
  '**Interessant, ja. Ein Beweis für ein Heilverfahren, nein.**',
  '',
  '**Was gar nicht belegt ist:** dass Güsse und Wickel bestimmte',
  'Krankheiten heilen. Für die einzelnen Anwendungen gibt es kleine',
  'Studien, oft ohne Vergleichsgruppe, fast nie verblindet — man kann',
  'einem Menschen schlecht heimlich kaltes Wasser über den Rücken',
  'gießen. **Wer aus meiner Seite behauptet, die Wirksamkeit der',
  'Kneipp-Anwendungen sei wissenschaftlich erwiesen, sagt die Unwahrheit.**',
  'Erwiesen ist etwas anderes, und darauf komme ich am Ende zurück: die',
  'Wirkung dessen, was um mich herum steht.',
  '',
  '## Die milde Hand: Güsse, Wickel, Wassertreten',
  '',
  'Wie sah das praktisch aus? Kneipp hat rund hundert Anwendungen',
  'beschrieben, alle mit Hausmitteln durchführbar. Ein paar davon',
  'begegnen Dir bis heute:',
  '',
  '**Der Guss.** Eine Kanne ohne Brause, das Wasser läuft als',
  'zusammenhängender Mantel über die Haut — Knieguss, Schenkelguss,',
  'Armguss, Rückenguss, Gesichtsguss. Immer herzfern beginnen, also am',
  'rechten Fuß außen; das Herz soll wissen, was kommt. Der Knieguss ist',
  'der berühmteste, weil er wenig verlangt und viel bewirkt: kalte',
  'Füße, unruhiger Schlaf, schwere Beine.',
  '',
  '**Das Wassertreten.** Im flachen Becken im Storchengang gehen — Fuß',
  'ganz aus dem Wasser heben, wieder hineinsetzen —, bis es an den',
  'Waden zieht, dann heraus, abstreifen, gehen. Das ist die Anwendung,',
  'die Du heute in jedem Kurpark findest.',
  '',
  '**Der Wickel.** Ein feuchtes Leintuch um Wade, Hals oder Leib,',
  'darüber ein trockenes. Wadenwickel bei Fieber gehören in Deutschland',
  'bis heute zur Kinderpflege und stehen sogar in ärztlichen Ratgebern.',
  '',
  '**Das Taulaufen und das Schneegehen.** Barfuß durch nasses Gras oder',
  'kurz durch frischen Schnee, dann Socken an und gehen. Kneipp hielt es',
  'für eine der besten Anwendungen überhaupt — und es kostet nichts.',
  '',
  '**Die Waschung und der Dampf.** Ein schnelles Abwaschen des Körpers',
  'mit kaltem Wasser am Morgen; Dampfbäder für Kopf, Fuß oder Unterleib',
  'mit Heublumen oder Kamille.',
  '',
  'Was alle diese Anwendungen gemeinsam haben, ist die Handschrift des',
  'späten Kneipp: **kurz, mild, wiederholt.** Nicht die eine große Kur,',
  'sondern die kleine Gewohnheit. Er hat das ausdrücklich gegen seine',
  'eigenen Anfänge gestellt — der Mann, der in der Donau zwischen',
  'Eisschollen gebadet hatte, riet alten Leuten später zum lauwarmen',
  'Wasser.',
  '',
  '## Der zweite Strom: die Bewegung',
  '',
  'Und jetzt der Punkt, an dem die meisten Menschen überrascht sind.',
  'Kneipp ist als Wasserpfarrer berühmt geworden — **aber das Wasser ist',
  'nur eine von fünf Säulen**, und er selbst hielt es nicht einmal für',
  'die wichtigste. Die anderen vier sind Bewegung, Ernährung,',
  'Heilpflanzen und Ordnung.',
  '',
  '(Eine Fußnote der Redlichkeit: **Die Einteilung in „fünf Säulen" hat',
  'Kneipp so nicht aufgeschrieben.** Sie ist eine spätere Ordnung seiner',
  'Nachfolger, die aber gut zusammenfasst, was in seinen Büchern steht.',
  'Ich benutze sie, weil sie hilfreich ist, nicht weil sie von ihm',
  'stammt.)',
  '',
  '**Weshalb Bewegung?**',
  '',
  'Die Antwort ist so schlicht, dass sie oft überhört wird: **Weil der',
  'Körper für Bewegung gebaut ist.** Ein Herz, das nie gefordert wird,',
  'wird schwach. Ein Muskel, der nie zieht, schwindet. Ein Knochen, der',
  'nie belastet wird, gibt Kalk ab. Gelenke werden nicht durch Blut',
  'ernährt, sondern durch Bewegung — der Knorpel saugt sich voll wie ein',
  'Schwamm, wenn er gedrückt und entlastet wird. **Der Stillstand ist',
  'nicht die Schonung des Körpers. Er ist sein Abbau.**',
  '',
  'Kneipp verordnete Gehen, Barfußgehen, Gartenarbeit, Holzhacken,',
  'Turnen im Freien. Nichts davon war neu; neu war, dass er es',
  '**verordnete** — als Therapie, mit Maß und Anweisung, nicht als',
  'freundlichen Rat zum Schluss.',
  '',
  '**Die heutige Entsprechung ist so eindeutig, dass sie fast langweilig',
  'ist.** Die Weltgesundheitsorganisation empfiehlt Erwachsenen',
  'mindestens hundertfünfzig Minuten mäßig anstrengende Bewegung pro',
  'Woche. Bewegung senkt nachweislich das Risiko für Herzinfarkt,',
  'Schlaganfall, Diabetes vom Typ 2, mehrere Krebsarten, Depressionen',
  'und Demenz; sie verbessert Blutdruck, Blutzucker und Schlaf. **Kein',
  'einziges Medikament der Welt hat ein so breites Wirkprofil bei so',
  'wenig Nebenwirkungen.** Das sagt nicht die Naturheilkunde. Das sagt',
  'die Schulmedizin, in ihren eigenen Leitlinien.',
  '',
  '## Der dritte Strom: die Ernährung',
  '',
  '**Weshalb Ernährung?**',
  '',
  'Weil sie der einzige Stoff ist, den ein Mensch **jeden Tag** zu sich',
  'nimmt. Eine Tablette nimmt er einmal, vielleicht dreimal. Das Essen',
  'nimmt er dreimal täglich, siebenmal in der Woche, ein Leben lang.',
  '**Was täglich hineingeht, wirkt stärker als das, was selten',
  'hineingeht — schon aus Gründen der Menge.**',
  '',
  'Kneipps Küche war die eines Allgäuer Pfarrhauses und für heutige',
  'Ohren erstaunlich modern: **grobes Brot statt feines, viel',
  'Getreide, Gemüse und Obst, Milch, wenig Fleisch, wenig Alkohol,',
  'wenig Zucker, kein Kaffee im Übermaß — und vor allem: nicht zu viel',
  'von allem.** Er kämpfte gegen zwei Dinge, die er täglich sah: das',
  'Schnapstrinken und die Völlerei der Wohlhabenden.',
  '',
  'Sein Maß war die **Einfachheit**, nicht die Askese. Er hat keine',
  'Wunderkost ausgerufen und keine Lebensmittel verteufelt. Er sagte:',
  'einfach, frisch, aus der Nähe, in Maßen — und mit Ruhe gegessen.',
  '',
  '**Die heutige Entsprechung:** Die Ernährungsforschung des letzten',
  'halben Jahrhunderts ist bei fast demselben Bild angekommen. Die große',
  'spanische PREDIMED-Studie zeigte 2013 und in der Neuauswertung 2018,',
  'dass eine mediterrane Kost mit Olivenöl und Nüssen Herzinfarkte und',
  'Schlaganfälle deutlich seltener machte. Ernährungsleitlinien in aller',
  'Welt raten heute zu viel Gemüse, viel Vollkorn, Hülsenfrüchten, wenig',
  'rotem und verarbeitetem Fleisch, wenig Zucker und wenig stark',
  'verarbeiteten Lebensmitteln. **Das ist, in andere Worte gefasst, die',
  'Küche eines Allgäuer Pfarrers von 1890.**',
  '',
  '## Der vierte Strom: die Heilpflanzen',
  '',
  '**Weshalb Heilpflanzen?**',
  '',
  'Weil sie nach dieser Denkart **stützen, statt zu erzwingen**. Eine',
  'Pflanze bringt nicht einen isolierten Stoff in hoher Dosis, sondern',
  'viele in kleiner — und der Körper soll damit selbst zurechtkommen.',
  'Kneipp benutzte, was im Allgäu wächst: Schafgarbe, Zinnkraut,',
  'Wacholder, Salbei, Kamille, Arnika, Wermut, Lindenblüte, Heublumen',
  'als Dampf und Auflage. Er ließ Tees trinken, Umschläge machen, Öle',
  'einreiben.',
  '',
  'Diese Säule ist die älteste in diesem Buch — sie führt zurück zu den',
  'Klostergärten Hildegards, zum Ayurveda, zur chinesischen',
  'Kräuterlehre und zu den Heilerinnen, die vor ihnen allen kamen.',
  '',
  'Und sie ist zugleich die Säule mit der **gemischtesten Bilanz**, und',
  'zwar nach oben wie nach unten:',
  '',
  'Nach oben: Ein guter Teil der modernen Arzneischränke stammt aus',
  'diesem Wissen — Chinin aus der Chinarinde, Digitalis aus dem',
  'Fingerhut, Morphin aus dem Mohn, Aspirin aus der Weidenrinde. Und',
  'auch heute halten einzelne Pflanzen dem strengen Verfahren stand:',
  'Johanniskraut wirkt bei leichten bis mittelschweren Depressionen in',
  'kontrollierten Studien ähnlich gut wie herkömmliche Antidepressiva.',
  '',
  'Nach unten: **Für die meisten der Kräuter, die Kneipp verwendete,',
  'gibt es bis heute keine überzeugende Wirksamkeitsprüfung.** Zinnkraut',
  'als Entwässerungsmittel, Wacholder als Blutreiniger — das sind',
  'Erfahrungswerte, keine Belege. Und eine Warnung gehört dazu, die',
  'meine Seite viel zu selten ausspricht: **„Pflanzlich" heißt nicht',
  '„harmlos".** Fingerhut tötet, Beinwell kann die Leber schädigen,',
  'Johanniskraut schwächt die Wirkung der Pille und vieler anderer',
  'Medikamente. Wer Kräuter für automatisch ungefährlich hält, hat die',
  'Pharmakologie nicht verstanden — und ausgerechnet meine Seite müsste',
  'sie am besten kennen.',
  '',
  '## Der fünfte Strom: die Ordnung',
  '',
  'Und nun die Säule, die Kneipp selbst für die wichtigste hielt und die',
  'in jeder Broschüre zuletzt kommt, weil sie sich am schlechtesten',
  'verkaufen lässt.',
  '',
  '**Weshalb Ordnung?**',
  '',
  'Weil nach dieser Denkart **die Lebensweise die Ursache ist, an der',
  'alles andere hängt.** Man kann Güsse machen, Kräuter trinken und',
  'spazieren gehen — wenn ein Mensch jede Nacht vier Stunden schläft, in',
  'ständiger Sorge lebt, sich nie freut und mit niemandem redet, wird er',
  'krank bleiben. **Die Anwendung behandelt den Körper. Die Ordnung',
  'behandelt das Leben, das ihn krank macht.**',
  '',
  'Kneipp meinte damit ganz Konkretes: einen geregelten Tag mit festen',
  'Zeiten für Arbeit, Essen und Schlaf; genug Schlaf und ihn nachts;',
  'Maß in allem, auch im Guten; Arbeit, aber nicht ohne Ende; Freude,',
  'Gemeinschaft, ein reines Gewissen. Als Pfarrer sprach er dabei',
  'selbstverständlich auch von der Seele und von Gott. Man muss diesen',
  'Teil nicht teilen, um zu sehen, worauf er hinauswill: **Ein Mensch,',
  'der innerlich zerrissen ist, wird äußerlich nicht gesund.**',
  '',
  '**Die heutige Entsprechung ist die jüngste und vielleicht die',
  'erstaunlichste.** Die Chronobiologie hat gezeigt, dass fast jede',
  'Zelle des Körpers eine innere Uhr besitzt und dass ihre Störung —',
  'Schichtarbeit, ständiger Schlafmangel, Licht in der Nacht — Blutdruck,',
  'Zuckerstoffwechsel und Immunsystem verändert; für die Aufklärung',
  'dieser Uhr gab es 2017 den Nobelpreis für Medizin. Die',
  'Stressforschung hat den Zusammenhang zwischen Dauerbelastung und',
  'Herzkrankheiten gemessen. Und eine große Auswertung von 2010 kam zu',
  'dem Ergebnis, dass Menschen mit tragfähigen sozialen Beziehungen',
  'deutlich länger leben — ein Effekt in der Größenordnung des',
  'Rauchverzichts.',
  '',
  '**Der Pfarrer von Wörishofen hat für „Ordnung" keine Studie gehabt.',
  'Er hatte nur den Eindruck, dass Menschen krank werden, wenn ihr Leben',
  'nicht stimmt. Die Forschung hat hundert Jahre gebraucht, um ihm in',
  'diesem Punkt recht zu geben.**',
  '',
  '## Das Buch, das aus einem Dorf eine Stadt machte',
  '',
  '**1886 erscheint bei Kösel in Kempten „Meine Wasserkur".** Es ist',
  'kein gelehrtes Werk, sondern eine Gebrauchsanweisung: Anwendungen,',
  'Kräuter, Krankheitsbilder, in einer Sprache, die jeder Bauer versteht.',
  'Genau deshalb wird es ein Bestseller — zahlreiche Auflagen zu',
  'Lebzeiten, Übersetzungen in viele Sprachen. **1889 folgt „So sollt',
  'ihr leben"**, in dem die Ordnung und die Lebensführung nach vorne',
  'rücken.',
  '',
  'Und dann passiert etwas, das niemand geplant hat. **Die Menschen',
  'kommen.** Erst Dutzende, dann Hunderte, dann Tausende. Ein Dorf mit',
  'ein paar hundert Einwohnern muss Zehntausende Gäste im Jahr',
  'unterbringen; die genauen Zahlen gehen in den Quellen auseinander,',
  'die Größenordnung nicht. Es entstehen Gasthäuser, Badehäuser, ein',
  'Bahnanschluss. Adelige stehen neben Bauern in der Schlange, weil',
  'Kneipp beides ohne Unterschied behandelte.',
  '',
  'Er selbst hält Vorträge, oft mehrmals am Tag, im Kurhaus, in der',
  'Kirche, im Freien. **Ab 1890 arbeitet mit Dr. Alfred Baumgarten ein',
  'approbierter Arzt als Badearzt im Ort** — auf Kneipps eigenen Wunsch,',
  'und dieser Punkt ist wichtig genug für einen eigenen Abschnitt weiter',
  'unten. **1893 ernennt Papst Leo XIII. den Pfarrer zum päpstlichen',
  'Geheimkämmerer; 1894 wird er in Rom empfangen.** 1896 entsteht in',
  'Wörishofen das Kneippianum.',
  '',
  '**Am 17. Juni 1897 stirbt Sebastian Kneipp in Wörishofen, sechs',
  'Wochen nach seinem sechsundsiebzigsten Geburtstag.** Er hinterlässt',
  'kein Vermögen; die Einnahmen aus den Büchern gingen in Stiftungen und',
  'Häuser. **1920 darf sich der Ort Bad Wörishofen nennen.**',
  '',
  'Geblieben ist mehr, als ein Dorfpfarrer erwarten durfte: mehrere',
  'Dutzend anerkannte Kneipp-Kurorte in Deutschland, Kneipp-Vereine in',
  'mehreren Ländern, Wassertretbecken in fast jedem deutschen Kurpark,',
  'Kneipp-Kindergärten — und **2021 die Aufnahme des Kneippens in die',
  'Repräsentative Liste des immateriellen Kulturerbes der Menschheit',
  'durch die UNESCO.**',
  '',
  '## Der Spott vom anderen Ufer',
  '',
  'Und die ganze Zeit über wurde gelacht.',
  '',
  '„Wasserpfarrer" war kein Ehrentitel, als das Wort aufkam; es war',
  'Hohn. Kneipp war ein Weberssohn ohne medizinische Ausbildung, der',
  'Kranke behandelte — für die aufstrebende akademische Medizin des',
  'späten 19. Jahrhunderts war das eine Zumutung. Es gab Spott in',
  'Fachblättern und in der Presse, es gab Anzeigen wegen unbefugter',
  'Heilbehandlung, es gab ärztliche Versammlungen, die sich gegen die',
  '„Kurpfuscherei" wandten.',
  '',
  'Rechtlich stand er trotzdem nicht schlecht, und das hat mit dem',
  'vorletzten Kapitel dieses Buches zu tun: **Die Gewerbeordnung des',
  'Norddeutschen Bundes von 1869, ab 1871 im ganzen Deutschen Reich',
  'gültig, brachte die sogenannte Kurierfreiheit.** Heilen durfte jeder;',
  'nur „Arzt" nennen durfte sich, wer approbiert war. Das ist der',
  'juristische Grund, weshalb es Kneipp gab — und weshalb es in',
  'Deutschland bis heute Heilpraktiker gibt.',
  '',
  '(Der Vollständigkeit halber, weil dieses Buch nichts weglässt: **Die',
  'Kurierfreiheit endete 1939 mit dem Heilpraktikergesetz** des',
  'NS-Staates, das den Beruf erstmals regelte und zugleich abwickeln',
  'sollte. Dass der Beruf des Heilpraktikers seine heutige Rechtsform',
  'einem Gesetz aus dieser Zeit verdankt, ist eine unbequeme Tatsache',
  'meiner Seite. Sie gehört hierher, auch wenn sie niemandem gefällt.)',
  '',
  'Nun aber die Fairness, die dieses Buch verlangt, und ich meine sie',
  'ernst: **Die Ärzte hatten Gründe.** Man muss sich ansehen, wo die',
  'Medizin um 1890 stand. Sie hatte gerade — in den Kapiteln 9 bis 12',
  'dieses Buches — die Narkose, die Antisepsis, die Keimtheorie und die',
  'Röntgenstrahlen gewonnen. Zum ersten Mal in der Geschichte konnte ein',
  'Arzt sagen, **weshalb** eine Behandlung wirkt. Und in genau diesem',
  'Augenblick zog ein Pfarrer aus dem Allgäu Zehntausende an sich, ohne',
  'ein einziges dieser Verfahren zu kennen.',
  '',
  'Aus ihrer Sicht war das gefährlich: Ein Mann ohne Ausbildung stellt',
  'Diagnosen. Menschen mit einer Blinddarmentzündung könnten statt zum',
  'Chirurgen ins Wasserbecken gehen. **Dieser Einwand war nicht',
  'Standesdünkel, er war berechtigt** — und er ist es bis heute.',
  '',
  'Was ihm die Härte nahm, war Kneipps eigene Haltung: Er suchte die',
  'Ärzte nicht als Gegner. Er holte Dr. Baumgarten in den Ort, arbeitete',
  'mit ihm zusammen, ließ Kranke untersuchen und schickte weiter, was',
  'nicht in seine Hände gehörte. **Der Wasserpfarrer hat den Streit',
  'nicht gesucht. Er hat ihn bekommen.**',
  '',
  '## Was Kneipp selbst nie behauptet hat',
  '',
  'Weil er heute für alles Mögliche in Anspruch genommen wird, hier vier',
  'Dinge, die er **nicht** gesagt hat:',
  '',
  '**Er war kein Wunderheiler.** Er hat keine Heilung versprochen und',
  'kein Geheimmittel verkauft. Seine Anwendungen standen in einem Buch,',
  'das jeder für wenig Geld kaufen konnte — die denkbar schlechteste',
  'Geschäftsidee für einen Scharlatan.',
  '',
  '**Er war kein Feind der Schulmedizin.** Er hat bei ernsten',
  'Krankheiten an Ärzte verwiesen, mit einem Badearzt zusammengearbeitet',
  'und die Chirurgie nie bestritten. Wer ihn heute als Kronzeugen gegen',
  'die Medizin aufruft, benutzt einen Mann, der sich nicht mehr wehren',
  'kann.',
  '',
  '**Er hat das kalte Wasser nicht für ein Allheilmittel gehalten.** Es',
  'ist eine von fünf Säulen, und er selbst hat die Ordnung höher',
  'gestellt.',
  '',
  '**Und er hat nie behauptet, es bewiesen zu haben.** Er war Pfarrer,',
  'nicht Forscher. Er hat beobachtet, ausprobiert, korrigiert und',
  'aufgeschrieben, über vierzig Jahre und an sehr vielen Menschen. Das',
  'ist eine ehrenwerte Art, zu Wissen zu kommen. **Sie ist nur nicht',
  'dasselbe wie ein Nachweis, und wir sollten aufhören, so zu tun.**',
  '',
  '## Das trübe Wasser: was meine Seite sich vorwerfen muss',
  '',
  'Und damit zu der Liste, die in keiner Kneipp-Broschüre steht. Die',
  'TONE-Regel dieses Buches verlangt, dass jede Seite ihre unbequemen',
  'Stellen selbst benennt — hier sind meine.',
  '',
  '**Erstens: die fehlende Evidenz.** Für die einzelnen Verfahren —',
  'Güsse, Wickel, Wassertreten, Dampfbäder — ist die Studienlage dünn:',
  'kleine Fallzahlen, selten Vergleichsgruppen, so gut wie nie',
  'Verblindung. Es gibt Hinweise, es gibt Erfahrung, es gibt zufriedene',
  'Patienten. **Einen belastbaren Wirksamkeitsnachweis im heutigen Sinne',
  'gibt es für die meisten Anwendungen nicht.** Man kann darüber',
  'streiten, ob sich eine Lebensweise überhaupt so prüfen lässt — aber',
  'das ist ein Argument über die Methode, kein Ersatz für das Ergebnis.',
  '',
  '**Zweitens: die Wundermittel-Versprecher.** Am Rand meiner Seite',
  'stehen Leute, die genau das tun, was Kneipp nie getan hat: Heilung',
  'versprechen. Entgiftungskuren gegen alles, Wundertropfen, „Reinigung"',
  'des Blutes, Geräte mit erfundener Physik. **Es gibt Scharlatanerie in',
  'der Naturheilkunde, und sie ist gefährlich.** Sie ist gefährlich für',
  'die Kranken, die ihr Geld dafür ausgeben, und sie ist gefährlich für',
  'alle seriösen Behandler, die anschließend in denselben Topf geworfen',
  'werden. Wir haben uns davon zu selten und zu leise distanziert.',
  '',
  '**Drittens: die verlorene Zeit.** Das ist der schwerste Vorwurf, und',
  'er trifft. Ein Mensch mit Brustschmerz, mit Blut im Stuhl, mit einem',
  'wachsenden Knoten, mit einem hohen Fieber, das nicht weicht, gehört',
  'nicht ins Wassertretbecken. Er gehört sofort zum Arzt. **Es gibt',
  'dokumentierte Fälle, in denen Menschen mit heilbaren Krankheiten so',
  'lange „naturheilkundlich" behandelt wurden, bis die Heilung nicht',
  'mehr möglich war.** Die Sanftheit meiner Mittel ist keine Erlaubnis,',
  'zu warten. **Wo die Zeit über Leben entscheidet, hört meine',
  'Zuständigkeit auf** — und wer das anders sieht, schadet der',
  'Naturheilkunde mehr als jeder Kritiker.',
  '',
  '**Viertens: aus der Idee wurde ein Geschäft.** Dieses Buch beobachtet',
  'einen Zyklus: **Das Neue schadet oft erst, bevor es segensreich',
  'wird** — die Chirurgie tötete durch Wundfieber, ehe sie rettete, die',
  'Strahlen töteten ihre Pioniere, das Penicillin erzeugte die',
  'Resistenz. **Bei der Naturheilkunde verläuft der Zyklus anders**, und',
  'ich will ihn nicht schönreden, sondern richtig beschreiben: Sie war',
  'nicht erst schädlich und dann segensreich; sie war von Anfang an',
  'sanft. Ihr Schaden kam von zwei anderen Seiten. Zuerst von der Härte',
  'der frühen Wasserdoktoren, die Kranke überforderten. Und dann davon,',
  'dass eine Sache, die nichts kostet, unwiderstehlich wird, sobald sich',
  'Geld damit verdienen lässt.',
  '',
  'Schon 1891 entstand in Würzburg ein Unternehmen, das Kneipps Namen',
  'für seine Erzeugnisse benutzen durfte. Daraus ist eine Marke',
  'geworden, die heute Badezusätze und Cremes verkauft. Aus der Kur ist',
  'vielerorts Wellness geworden: Wohlfühlpaket, Aufgusszeremonie,',
  'Kurtaxe. **Ich sage nicht, dass das unlauter ist — Menschen dürfen',
  'für ihr Wohlbefinden Geld ausgeben.** Ich sage, dass dabei etwas',
  'verlorengeht: **Kneipps Heilkunde war für Arme gedacht. Wenn sie',
  'zweihundert Euro die Nacht kostet, ist sie nicht mehr seine.**',
  '',
  '**Fünftens: die Bequemlichkeit des Ganzheitlichen.** „Ich behandle',
  'den ganzen Menschen" klingt gut und kann eine Ausrede sein — dafür,',
  'nicht genau hinzusehen, keine Diagnose zu stellen, jeden Misserfolg',
  'der Lebensführung des Patienten anzulasten. **Wer alles erklären',
  'kann, erklärt nichts.**',
  '',
  '## Was der Regen mit Deinem Leben zu tun hat',
  '',
  'Und nun die Stelle, an der dieses Kapitel aus der Geschichte',
  'heraustritt.',
  '',
  'Nimm Kneipps fünf Säulen und streiche das Wasser und die Kräuter.',
  'Was bleibt, sind drei Dinge: **Bewegung. Ernährung. Ordnung — also',
  'Schlaf, Maß, wenig Sorge und Menschen um sich.**',
  '',
  'Das ist, fast wörtlich, die Antwort, die die moderne',
  'Präventionsmedizin heute auf die häufigsten Krankheiten unserer Zeit',
  'gibt. Die Weltgesundheitsorganisation schätzt, dass ein sehr großer',
  'Teil der chronischen Krankheiten — die Größenordnung wird meist mit',
  'siebzig bis achtzig Prozent angegeben — mit der Lebensweise',
  'zusammenhängt. Die britische DiRECT-Studie zeigte 2018, dass bei',
  'einem beträchtlichen Teil der Patienten ein Typ-2-Diabetes durch',
  'Gewichtsabnahme wieder verschwand — nach einem Jahr bei fast der',
  'Hälfte der Teilnehmer, ganz ohne Medikament. Die Forschung an',
  'besonders langlebigen Bevölkerungsgruppen findet immer wieder',
  'dieselben Zutaten: viel Alltagsbewegung, einfache pflanzenbetonte',
  'Kost, starke soziale Bindungen, wenig Hetze.',
  '',
  '**Für all das braucht es keine Raketenwissenschaft.** Es braucht',
  'einen Menschen, der geht statt fährt, der kocht statt aufreißt, der',
  'schläft statt scrollt und der jemanden hat, mit dem er reden kann.',
  'Und es ist möglich, dass damit mehr Gesundheit zu gewinnen wäre als',
  'mit den neuesten Präparaten.',
  '',
  'Aber ich wäre eine schlechte Stimme, wenn ich hier aufhörte, denn',
  'jetzt kommt der Einwand, und er ist stark:',
  '',
  '**Es ist leicht gesagt.** Wer im Schichtdienst arbeitet, kann seinen',
  'Tag nicht ordnen. Wer zwei Jobs hat, kocht nicht frisch. Wer wenig',
  'Geld hat, kauft das billige Essen, und das billige Essen ist das',
  'verarbeitete. Wer allein ist, kann sich keine Gemeinschaft',
  'verschreiben. Und gegen eine Lebensmittelindustrie, die Milliarden',
  'dafür ausgibt, dass Menschen mehr essen, hilft kein guter Vorsatz.',
  '**„Selbstverantwortung" kann ein befreiendes Wort sein — und ein',
  'Werkzeug, um Kranken die Schuld an ihrer Krankheit zu geben. Beides',
  'muss man auseinanderhalten.**',
  '',
  'Dazu kommt die unbequeme Frage nach dem Geld, die das Kapitel über',
  'die Pharmaindustrie gestellt hat: An einer Pille verdient jemand. An',
  'einem Spaziergang verdient niemand. **Ein Rat, für den es keinen',
  'Markt gibt, hat keine Lobby** — und das erklärt vielleicht besser als',
  'jeder Standesdünkel, weshalb das Einfache so selten verschrieben',
  'wird. Dieser Gedanke ist so groß, dass er ein eigenes Kapitel',
  'bekommt: **Kapitel 18 dieses Buches, „Die einfache Medizin".**',
  '',
  '## Wo ich in die andere Stimme münde',
  '',
  'Ich habe hier alles gesagt, was ich für meine Seite sagen kann, und',
  'ich habe versucht, nichts zu verschweigen, was gegen sie spricht.',
  '',
  '**Die zweite Stimme dieses Kapitels gehört der Schulmedizin.** Sie',
  'wird dieselbe Geschichte aus dem Messglas erzählen, und sie hat dafür',
  'gute Gründe. Sie wird sagen: **Zeig mir die Studie.** Sie wird die',
  'dünne Studienlage zu den einzelnen Anwendungen vorlegen, sie wird',
  'daran erinnern, wie viele Menschen an Krankheiten gestorben sind, die',
  'man mit Zuwarten nicht heilt, und sie wird die Grenze verteidigen,',
  'hinter der eine Diagnose kein Gefühl mehr sein darf.',
  '',
  'Und sie wird — wenn sie so ehrlich ist wie die Stimmen der Kapitel',
  'davor — **auch ihre eigenen dunklen Stellen aufmachen**: dass sie',
  'einen Pfarrer verspottet hat, statt ihn zu prüfen; dass sie die',
  'Lebensweise jahrzehntelang für ein Thema der Kurbroschüre hielt und',
  'nicht der Medizin; und dass sie heute Bewegung, Ernährung und',
  'Stressabbau in ihre Leitlinien schreibt, ohne den Namen dessen zu',
  'nennen, der damit angefangen hat.',
  '',
  'Ich bin nur Wasser. Ich entscheide nichts. Ich falle als Regen,',
  'sammle mich in einer Quelle, laufe durch einen Trog in Wörishofen und',
  'verdunste wieder. Die Frage, die bleibt, müsst ihr unter euch',
  'ausmachen:',
  '',
  '**Was heilt mehr — die Pille oder die Lebensweise? Und wer',
  'entscheidet eigentlich, was davon verschrieben wird?**',
].join('\n');

/**
 * Die Stimme aus dem Messglas — die Schulmedizin.
 *
 * Verfasst von DeepSeek (Hermes-Pass, Runde 18). Dieselbe Dramaturgie wie
 * die erste Stimme: das Wasser, aber diesmal im Messglas des Labors —
 * untersucht, gemessen, auf Wirkstoffe geprüft. Diese Stimme vertritt die
 * Diagnose, die Studie, die Notfallmedizin — und sie schlägt zuerst die
 * eigene dunkle Vergangenheit gegenüber dem Wasserpfarrer auf
 * (Zusatzregel für sensible Themen in CLAUDE.md).
 */
const stimmeAusDemMessglas = [
  '## Das Messglas, in dem kein Regen ist',
  '',
  'Stell Dir das Wasser von vorhin wieder vor. Derselbe Regen, dieselbe',
  'Quelle, derselbe Trog in Wörishofen. Aber jetzt steht das Wasser',
  'nicht mehr im Trog — es steht in einem Messglas, auf einem',
  'Labortisch, zwischen Pipetten und Protokollen.',
  '',
  'Wir sind die Stimme aus dem Messglas: die Schulmedizin. Wir sind',
  'diejenigen, die das Wasser untersuchen, bevor sie es empfehlen. Und',
  'wir beginnen mit dem, was die Stimme des Wassers von uns verlangt',
  'hat — mit unseren eigenen dunklen Stellen, weil die Regel dieses',
  'Buches auch für uns gilt.',
  '',
  '**Wir haben den Wasserpfarrer verspottet, statt ihn zu prüfen.**',
  'Das steht am Anfang, und es bleibt stehen. Die Ärzteschaft hat',
  'einen Mann belächelt und verhöhnt, der Tausenden geholfen hat —',
  'und sie hat es getan, ohne seine Anwendungen auch nur zu',
  'untersuchen. Man muss das so hart sagen, wie es war: **Das',
  'Verspotten war keine Wissenschaft. Es war Standesdünkel mit',
  'weißem Kittel.** Wir haben aus diesem Fehler gelernt — spät,',
  'und ohne es zuzugeben.',
  '',
  'Und dann sagen wir, was das Messglas zeigt, wenn man ehrlich',
  'hineinsieht.',
  '',
  '## Was im Wasser ist — und was nicht',
  '',
  'Das Messglas ist unbestechlich, und es zeigt zuerst das, was die',
  'Stimme des Wassers selbst eingeräumt hat: **In einem Glas Wasser',
  'ist Wasser.** H₂O, ein paar gelöste Mineralien, nichts, was man',
  'als Arznei verschreiben könnte. Die Güsse und Wickel von Kneipp',
  'sind keine Medikamente — sie sind Reize. Kälte auf der Haut,',
  'Wärme danach, Durchblutung, Atem, Aufmerksamkeit. Das ist real,',
  'und es ist nicht nichts. Aber es ist etwas anderes als eine',
  'Substanz mit nachgewiesener Wirkung.',
  '',
  'Und hier beginnt unsere erste ehrliche Abgrenzung: **Die',
  'einzelnen Wasseranwendungen — das Wassertreten, die Güsse, die',
  'Wickel — haben eine dünne Studienlage.** Es gibt Beobachtungen,',
  'Erfahrungsberichte, Traditionen. Es gibt kaum kontrollierte',
  'Studien, die belegen, dass genau dieses kalte Wasser an genau',
  'dieser Stelle genau diese Krankheit bessert. Die Stimme des',
  'Wassers hat das nicht bestritten — sie hat es selbst gesagt. Wir',
  'sagen es aus dem Messglas: **Was man nicht messen kann, kann man',
  'nicht belegen. Und was man nicht belegen kann, darf man nicht als',
  'belegt verkaufen.** Das gilt für Kneipp wie für jeden anderen.',
  '',
  '## Die Ströme, die wir selbst verpasst haben',
  '',
  'Und dann die zweite Seite des Messglases, die uns weniger gut',
  'gefällt — weil sie uns betrifft.',
  '',
  '**Die Bewegung ist belegt.** Die Studienlage ist eindeutig:',
  'Regelmäßige Bewegung senkt das Risiko für Herzkrankheiten,',
  'Diabetes, viele Krebsarten, Depressionen — stärker als die',
  'meisten einzelnen Medikamente. **Die Ernährung ist belegt.**',
  'Wenig verarbeitet, viel Gemüse, Maß statt Überfluss — die',
  'Datenlage zu dieser einen Empfehlung ist so stark wie zu kaum',
  'einer Arznei. **Der Stressabbau ist belegt.** Chronischer Stress',
  'macht krank, das ist kein Esoterik-Satz mehr, sondern',
  'Endokrinologie. Und der Schlaf, und die Ordnung des Tages, und',
  'das soziale Umfeld: alles belegt, alles in den Leitlinien.',
  '',
  '**Und wer hat das zuerst gesagt? Ein Pfarrer in Wörishofen, den',
  'wir Kurpfuscher genannt haben.** Die moderne Präventivmedizin',
  'schreibt heute in ihre Leitlinien, was Kneipp gepredigt hat —',
  'Bewegung, Ernährung, Ordnung, Maß — und nennt seinen Namen',
  'nicht. Das ist kein Zufall und keine böse Absicht, es ist',
  'schlicht Vergessen. Aber es ist ein Vergessen mit',
  'Richtung: Wir haben die Botschaft übernommen und den Boten',
  'vergessen. **Das Messglas misst auch das — und es steht nicht',
  'gut aus für uns.**',
  '',
  '## Das Wasser, mit dem wir gekämpft haben',
  '',
  'Und dann eine Geschichte, die in diesem Kapitel nicht fehlen',
  'darf, weil sie zeigt, wie nah sich die beiden Seiten',
  'gekommen sind — ohne es zu merken.',
  '',
  'Die Schulmedizin des neunzehnten Jahrhunderts hat mit demselben',
  'Wasser gekämpft, das Kneipp als Arznei verschrieb. Die Cholera',
  'kam über das Wasser. 1854 entdeckte der Londoner Arzt John Snow,',
  'dass die Erkrankten aus einer einzigen Straßenpumpe tranken — er',
  'ließ den Griff der Pumpe abnehmen, und die Epidemie endete. Die',
  'Bakteriologie von Robert Koch fand die Erreger im Wasser, die',
  'Hygiene-Bewegung baute Kanalisationen, filterte das Trinkwasser,',
  'bekämpfte den Typhus. **Das Wasser war für uns die Gefahr. Für',
  'Kneipp war es die Medizin. Beide hatten recht — es war dasselbe',
  'Wasser.**',
  '',
  'Und genau hier zeigt sich, wie tief der Graben war: Während wir',
  'lernten, was im Wasser Krankheit macht, lehrte Kneipp, was am',
  'Wasser gesund macht. Die eine Seite sah den Erreger, die andere',
  'sah den Reiz. Die eine baute Filter, die andere baute Tröge.',
  '**Beide haben die Gesundheit der Menschen verbessert — und beide',
  'haben einander nicht verstanden.** Die Cholera ist in Europa',
  'verschwunden, weil wir das Wasser sauber gemacht haben. Die',
  'Gesundheit vieler Menschen ist besser geworden, weil Kneipp sie',
  'ins kalte Wasser geschickt hat. Das eine ist belegt wie kaum',
  'etwas in der Medizingeschichte. Das andere ist belegt — durch',
  'hundertfünfzig Jahre Erfahrung und durch die moderne',
  'Präventivmedizin, die heute sagt, was er sagte.',
  '',
  '**Vielleicht ist das die eigentliche Lehre dieses Kapitels: Die',
  'Schulmedizin und die Naturheilkunde haben sich am Wasser',
  'getroffen, ohne sich zu erkennen.** Der eine hat die Gefahr im',
  'Wasser gesehen, der andere die Kraft. Und die Gesundheit von',
  'heute — die so viel besser ist als die von damals — verdankt',
  'sich beiden.',
  '',
  '## Die späte Heimkehr: die Lifestyle-Medizin',
  '',
  'Und dann die Entwicklung, die uns am meisten beschäftigt, weil',
  'sie uns betrifft: **Die Schulmedizin holt die Lebensweise',
  'langsam ein — als neue Fachrichtung, als wäre sie eine',
  'Erfindung.**',
  '',
  'Es gibt inzwischen Lehrstühle für Präventivmedizin,',
  'Forschungszentren für Ernährung, Leitlinien für Bewegung. Die',
  'Weltgesundheitsorganisation schätzt, dass ein großer Teil der',
  'chronischen Krankheiten durch Lebensstilfaktoren vermeidbar',
  'wäre. Die „Lifestyle-Medizin\" nennt sich ein neues Feld — als',
  'hätte niemand vorher daran gedacht. **Und wer hat zuerst daran',
  'gedacht? Der Pfarrer von Wörishofen.**',
  '',
  'Das ist keine Nostalgie und keine Bitterkeit. Es ist eine',
  'Bilanz: Wir haben die Lebensweise in die Leitlinien geschrieben,',
  'ohne die Denkart zu übernehmen, die dazugehört. Eine Leitlinie',
  'sagt, was zu tun ist. Sie sagt nicht, wie man einen Menschen',
  'dabei begleitet, es zu tun. Kneipp hat beides getan — er hat den',
  'Menschen nicht nur gesagt, was er tun soll, er hat es mit ihm',
  'getan, Tag für Tag, in einer Gemeinschaft, mit einem Ziel. **Das',
  'ist der Teil der Kneipp-Medizin, den wir noch nicht übernommen',
  'haben: nicht die Empfehlung, sondern die Begleitung.**',
  '',
  '## Die Grenze, die wir verteidigen',
  '',
  'Und dann die Grenze, hinter der wir nicht nachgeben, weil es um',
  'Leben geht.',
  '',
  'Die Stimme des Wassers hat sie selbst benannt: die',
  'Blinddarmentzündung, die mit einem Guss nicht heilt; die',
  'Lungenentzündung, die Zeit braucht und Antibiotika; der',
  'Herzinfarkt, der keine Ordnungstherapie mehr erwartet. **Es gibt',
  'Krankheiten, bei denen Zuwarten tötet — und bei denen die',
  'Diagnose keine Gefühlssache sein darf.** Wir haben in diesem',
  'Buch schon erzählt, was passiert, wenn Menschen zu spät zum Arzt',
  'gehen: Kapitel 9 hat die Chirurgie gezeigt, Kapitel 10 die',
  'Impfung, Kapitel 15 die Pandemie. Die Medizin hat ihre',
  'dunklen Seiten — aber sie hat auch das eine gerettet, was die',
  'Naturheilkunde nicht kann: die akute Rettung.',
  '',
  'Und deshalb verteidigen wir die Diagnose. Nicht den weißen Kittel,',
  'nicht das Rezept, nicht das System — die Diagnose. **Wer',
  'behaupten kann, was ein Mensch hat, kann entscheiden, was er',
  'braucht. Wer das nur fühlt, kann es nicht.** Kneipp selbst hat',
  'das gewusst: Er hat bei ernsten Krankheiten an Ärzte verwiesen,',
  'er hat mit Dr. Baumgarten zusammengearbeitet. Der Wasserpfarrer',
  'war klüger als mancher seiner Verehrer.',
  '',
  '## Was wir ihm zugestehen',
  '',
  'Und jetzt das, was diese Stimme dem Pfarrer schuldet — nicht aus',
  'Höflichkeit, sondern weil es belegt ist.',
  '',
  '**Kneipp war kein Scharlatan.** Er hat keine Heilung versprochen,',
  'kein Geheimmittel verkauft, kein Geld verlangt. Sein Buch war für',
  'jeden erschwinglich — die schlechteste Geschäftsidee für einen',
  'Betrüger. Er hat mit Ärzten zusammengearbeitet und Kranke',
  'weitergeschickt. **Er war ehrlicher als viele, die heute seinen',
  'Namen tragen.**',
  '',
  '**Er hatte recht mit dem, was zählt.** Die Lebensweise — Bewegung,',
  'Ernährung, Ordnung, Maß, Umfeld — ist die größte Medizin, die es',
  'gibt. Die moderne Forschung hat das bestätigt, Punkt für Punkt.',
  'Wer das heute leugnet, leugnet die Datenlage. **Kneipp hat vor',
  'hundertfünfzig Jahren gesagt, was wir heute in die Leitlinien',
  'schreiben — und wir haben ihn dafür verspottet.** Das ist keine',
  'Nebensache. Das ist der Kern.',
  '',
  'Und wir gestehen ihm zu, was schwerer wiegt als jede Studie: die',
  'Zuwendung. Die Menschen, die nach Wörishofen kamen, wurden',
  'ernst genommen, bekamen Zeit, wurden angeleitet, etwas für sich',
  'selbst zu tun. **Wir haben gelernt, dass diese Zuwendung ein',
  'Wirkstoff ist — die Placeboforschung hat es bewiesen. Kneipp hat',
  'ihn dosiert, als wir ihn noch für Einbildung hielten.**',
  '',
  '## Was wir uns selbst vorwerfen müssen',
  '',
  'Die TONE-Regel gilt doppelt, und deshalb schließt diese Stimme',
  'mit der Liste, die uns nicht schmeichelt.',
  '',
  '**Erstens: Wir haben verspottet, statt zu prüfen.** Den',
  'Wasserpfarrer, die Homöopathie, die Naturheilkunde überhaupt.',
  'Wer die eigene Vergangenheit kennt, sollte vorsichtig sein mit',
  'dem Ton.',
  '',
  '**Zweitens: Wir haben die Lebensweise jahrzehntelang für ein',
  'Thema der Kurbroschüre gehalten** — während die chronischen',
  'Krankheiten, die wir nicht heilen können, genau aus der',
  'Lebensweise entstehen. Kapitel 14 dieses Buches hat die Bilanz',
  'gezogen: stark in der Diagnose, schwach bei den chronischen',
  'Krankheiten. Die Naturheilkunde hat die chronischen Krankheiten',
  'nie unterschätzt — sie hat sich mit ihnen beschäftigt, als wir',
  'sie noch verwaltet haben.',
  '',
  '**Drittens: Wir verschreiben die Pille leichter als den Rat.**',
  'Ein Rezept dauert zwei Minuten. Ein Gespräch über Bewegung und',
  'Ernährung dauert zwanzig — und wird nicht bezahlt. Das System',
  'belohnt die Pille und bestraft den Rat. **Das ist nicht die',
  'Schuld der Ärztinnen und Ärzte, das ist die Schuld derer, die',
  'das System gebaut haben. Aber es ist unsere Rechnung.**',
  '',
  '**Viertens: Wir haben die Botschaft übernommen und den Boten',
  'vergessen.** Die Leitlinien sagen heute, was Kneipp sagte — und',
  'sein Name fehlt. Das ist kein Triumph der Wissenschaft. Es ist',
  'eine verspätete Entschuldigung ohne Brief.',
  '',
  '## Das Messglas und der Regen',
  '',
  'Und dann die Frage, die dieses Kapitel offen lässt, weil sie',
  'beide Stimmen betrifft: **Was heilt mehr — die Pille oder die',
  'Lebensweise?**',
  '',
  'Unsere Antwort aus dem Messglas ist ehrlicher, als manche',
  'Kollegin es gern hört: **Die Lebensweise heilt mehr.** Die',
  'größten Gesundheitsgewinne der letzten hundertfünfzig Jahre',
  'kamen nicht aus den Arzneien, sondern aus Wasser, Seife,',
  'Ernährung, Arbeitsschutz, Bewegung — aus der Lebensweise. Die',
  'Pille ist für die akute Lage, die Lebensweise für das ganze',
  'Leben. **Wer beides gegeneinanderstellt, stellt die falsche',
  'Frage. Wer die Lebensweise verschreibt, braucht aber Zeit — und',
  'die bekommt niemand bezahlt.**',
  '',
  'Und deshalb ist die zweite Frage die eigentliche: **Wer',
  'entscheidet, was verschrieben wird?** Nicht die Ärztin allein,',
  'nicht der Patient allein. Es entscheidet ein System, das die',
  'Pille bezahlt und das Gespräch nicht. Das nächste Kapitel dieses',
  'Buches wird diese Frage aufnehmen — und es wird sie',
  'beantworten, wie es sich gehört: mit der einfachen Medizin.',
  '',
  'Das Messglas steht auf dem Tisch. Der Regen fällt weiter. Beide',
  'gehören zusammen.',
].join('\n');

const kneipp = {
  id: 'kneipp',
  titel: 'Kneipp und die Naturheilkunde',
  epoche: 'Das 19. Jahrhundert',

  aufhaenger: {
    frage:
      'Kann ein Pfarrer mit kaltem Wasser heilen, was die Ärzte nicht ' +
      'heilen können — oder heilt am Ende die Lebensweise?',
    text: [
      'Im Winter 1849 steigt bei Dillingen an der Donau ein junger Mann in',
      'den eiskalten Fluss. Er heißt Sebastian Kneipp, ist achtundzwanzig',
      'Jahre alt, Sohn eines Webers, holt mit Mühe das Gymnasium nach — und',
      'er ist schwer krank. Was genau er hat, weiß bis heute niemand sicher;',
      'überliefert ist ein zehrendes Lungenleiden. In einer alten Schrift des',
      'Arztes Johann Siegmund Hahn von 1738 hat er über die Kraft des kalten',
      'Wassers gelesen. Also probiert er es an sich selbst: kurz untertauchen,',
      'dann im Laufschritt nach Hause, bis ihm warm wird.',
      '',
      'Er wird achtundsiebzig Jahre alt. 1855 kommt er als Beichtvater der',
      'Dominikanerinnen in das Dorf Wörishofen und beginnt, Kranke zu',
      'behandeln — mit Güssen, Wickeln, Wassertreten, Kräutern, Bewegung und',
      'einem geregelten Tag. Später wird man das die fünf Säulen nennen:',
      'Wasser, Bewegung, Ernährung, Heilpflanzen, Ordnung.',
      '',
      '1886 erscheint sein Buch „Meine Wasserkur". Danach kommen die Menschen',
      'in Scharen — aus ganz Europa, Zehntausende im Jahr, Bauern neben',
      'Adeligen. Die Ärzteschaft nennt ihn einen Kurpfuscher und den',
      '„Wasserpfarrer", und beides ist als Spott gemeint.',
      '',
      'Hundertfünfzig Jahre später steht in den Leitlinien der Schulmedizin,',
      'was der Pfarrer damals predigte: Bewegen Sie sich. Essen Sie einfach.',
      'Schlafen Sie genug. Bauen Sie Stress ab. Sein Name steht nicht dabei.',
      'Dieses Kapitel erzählt beide Seiten fair — und stellt die Frage, um die',
      'es eigentlich geht: Was heilt mehr, die Pille oder die Lebensweise?',
    ].join('\n'),
  },

  karte,

  perspektiven: [
    {
      id: 'naturheilkunde',
      name: 'Die Stimme des Wassers',
      stimme: 'Opus',
      text: stimmeDesWassers,
    },
    {
      id: 'schulmedizin',
      name: 'Die Stimme aus dem Messglas',
      stimme: 'DeepSeek',
      text: stimmeAusDemMessglas,
    },
  ],

  synthese: [
    '## Wo sich die beiden Seiten treffen',
    '',
    'Wenn man die zwei Stimmen dieses Kapitels nebeneinanderlegt, fällt',
    'zuerst auf, wie wenig sie sich eigentlich streiten — und wie viel',
    'sie teilen.',
    '',
    '**Sie teilen den Abscheu vor der heroischen Medizin.** Die',
    'Naturheilkunde entstand als Protest gegen Aderlass und Quecksilber',
    '— und die Schulmedizin dieses Kapitels hat nicht nur zugegeben,',
    'dass der Protest berechtigt war, sie hat die eigenen dunklen',
    'Jahrzehnte selbst benannt. Das haben in diesem Buch schon die',
    'Homöopathie und die Chirurgie getan: Die brutale Medizin ist',
    'beiden Seiten ein Gräuel.',
    '',
    '**Sie teilen die Erkenntnis, dass die Lebensweise die größte',
    'Medizin ist.** Die Schulmedizin hat es in diesem Kapitel selbst',
    'gesagt: Bewegung, Ernährung, Ordnung, Maß, Umfeld — belegt, in',
    'den Leitlinien, unbestritten. Kneipp hat es vor hundertfünfzig',
    'Jahren gepredigt, die Forschung hat es bestätigt. **Hier streiten',
    'die beiden Seiten nicht. Hier stimmen sie überein — und das ist',
    'das Bemerkenswerte an diesem Kapitel.**',
    '',
    '**Sie teilen die Ehrlichkeit.** Die Stimme des Wassers hat die',
    'dünne Studienlage zu den Einzelanwendungen selbst benannt und die',
    'Gefahr des Zuwartens. Die Stimme aus dem Messglas hat den Spott',
    'und die Arroganz selbst benannt und den verspäteten Respekt. Zwei',
    'Seiten, die ihre Wunden zeigen — das ist selten, und es ist das,',
    'was dieses Kapitel trägt.',
    '',
    '## Wo sie auseinandergehen',
    '',
    'Und dann der Unterschied, der bleibt.',
    '',
    '**Sie gehen auseinander bei der Frage, was als Nachweis gilt.**',
    'Die eine Seite sagt: Die Erfahrung von Millionen Menschen zählt.',
    'Die andere sagt: Zeig mir die Studie. Beide haben recht — und',
    'beide wissen es. Die Wasseranwendungen im Einzelnen sind kaum',
    'belegt; die Lebensweise als Ganzes ist es über jeden Zweifel.',
    '**Wer beides in einen Topf wirft, macht es sich zu leicht — in',
    'beide Richtungen.**',
    '',
    '**Sie gehen auseinander bei der Grenze der Diagnose.** Die',
    'Schulmedizin verteidigt sie, weil Zuwarten tötet. Die',
    'Naturheilkunde respektiert sie — Kneipp hat an Ärzte verwiesen.',
    'Der Streit beginnt erst dort, wo die Schulmedizin die Diagnose',
    'zur Mauer macht und die Lebensweise dahinter zurücklässt: im',
    'Wartezimmer, in dem für das Gespräch keine Zeit ist.',
    '',
    '## Was dieses Kapitel für das Buch bedeutet',
    '',
    'Die Denkart bestimmt die Methode — und dieses Kapitel zeigt die',
    'Umkehrung: **Die Methode der Naturheilkunde war die Lebensweise,',
    'und die Schulmedizin hat sie übernommen, ohne die Denkart zu',
    'übernehmen.** Die Leitlinien empfehlen Bewegung und Ernährung,',
    'aber das System verschreibt die Pille, weil die Pille zwei',
    'Minuten kostet und der Rat zwanzig. Kneipp hat nicht nur die',
    'Empfehlungen hinterlassen — er hat eine Denkart hinterlassen, in',
    'der der Mensch für seine Gesundheit mitverantwortlich ist. Diese',
    'Denkart fehlt in den Leitlinien. Sie steht nur zwischen den',
    'Zeilen.',
    '',
    'Und dann ist da der Bogen, den dieses Buch selbst geschlagen hat:',
    'Von Hahnemann (Kapitel 16), der die Arznei als Information',
    'verstand, zu Kneipp, der die Arznei als Lebensweise verstand —',
    'die Naturheilkunde hat die Schulmedizin zweimal herausgefordert,',
    'und beide Male hat die Schulmedizin am Ende übernommen, was sie',
    'zuerst verspottet hat. **Das ist kein Zufall. Das ist ein',
    'Muster — und das nächste Kapitel wird es benennen.**',
    '',
    '## Die Brücke zum nächsten Kapitel',
    '',
    'Dieses Kapitel hat die Frage aufgeworfen, die das nächste',
    'beantworten will: **Warum ist die größte Medizin — die',
    'Lebensweise — die am seltensten verschriebene?** Kneipp hat die',
    'Antwort vor hundertfünfzig Jahren gelehrt, die Forschung hat sie',
    'bestätigt, und das System verschreibt sie trotzdem nicht.',
    '',
    '**Kapitel 18 dieses Buches, „Die einfache Medizin", stellt die',
    'Betreiber-These dagegen:** Chronische Krankheiten sind',
    'Lebensstilfragen — Bewegung, gesunde Ernährung, soziales Umfeld,',
    'wenig Stress. Keine Raketenwissenschaft. Mehr Gesundheit durch',
    'Lebensstil als durch Chemie. Dieses Kapitel hat gezeigt, dass',
    'diese These eine zweihundertjährige Tradition hat: vom',
    'Wasserpfarrer bis zu den Leitlinien. Das nächste Kapitel fragt,',
    'warum sie trotzdem so selten verschrieben wird — und was sich',
    'ändern müsste, damit die einfache Medizin die selbstverständliche',
    'wird.',
  ].join('\n'),

  urteil: {
    frage:
      'Was heilt mehr — die Pille oder der Lebensstil? Und weshalb ' +
      'verschreibt die Medizin das eine so leicht und das andere so schwer?',
    hinweis: [
      'Es gibt hier kein Richtig und kein Falsch. Halte die beiden Seiten',
      'nebeneinander. Die eine: Bewegung, einfaches Essen, Schlaf und',
      'Menschen um sich kosten fast nichts, haben kaum Nebenwirkungen und',
      'hängen mit den häufigsten Krankheiten unserer Zeit nachweislich',
      'zusammen. Die andere: Ein Rat ist keine Behandlung, ein Wickel ist',
      'kein Antibiotikum, und wer bei ernsten Beschwerden auf die',
      'Lebensweise setzt, verliert Zeit, die niemand zurückholt. Frag Dich',
      'dreierlei. Erstens: Was von den fünf Säulen — Wasser, Bewegung,',
      'Ernährung, Heilpflanzen, Ordnung — tust Du selbst, und was hindert',
      'Dich am Rest? Zweitens: Wenn ein Arzt Dir zehn Minuten Zeit hat —',
      'was kann er Dir in dieser Zeit realistisch mitgeben, ein Rezept',
      'oder eine Lebensänderung? Drittens: Wem nützt es, dass das',
      'Einfache so selten verordnet wird — und wem schadet es?',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Wo und wann wurde Sebastian Kneipp geboren, und was war sein ' +
        'Vater von Beruf?',
      antworten: [
        '1821 in Stefansried im Allgäu, als Sohn eines Webers.',
        '1810 in Augsburg, als Sohn eines Arztes.',
        '1835 in Wörishofen, als Sohn eines Bauern.',
      ],
      richtig: 0,
      erklaerung:
        'Kneipp kam am 17. Mai 1821 in Stefansried zur Welt, einem Weiler ' +
        'bei Ottobeuren im bayerischen Allgäu. Sein Vater war Weber, die ' +
        'Familie sehr arm. Erst der Lateinunterricht bei Kaplan Matthias ' +
        'Merkle in Grönenbach ermöglichte ihm 1844 — mit dreiundzwanzig ' +
        'Jahren — die Aufnahme in das Gymnasium in Dillingen an der Donau.',
    },
    {
      frage:
        'Was tat Kneipp im Winter 1849, nachdem er die Wasserschrift von ' +
        'Johann Siegmund Hahn gelesen hatte?',
      antworten: [
        'Er eröffnete eine Badeanstalt in Dillingen.',
        'Er badete mehrmals wöchentlich kurz in der eiskalten Donau und ' +
          'lief danach zurück, bis ihm warm wurde.',
        'Er verschrieb die Kur zuerst seinen Mitschülern.',
      ],
      richtig: 1,
      erklaerung:
        'Hahns Schrift „Unterricht von der Krafft und Würckung des frischen ' +
        'Wassers" war 1738 erschienen. Kneipp, damals schwer krank, ' +
        'probierte die Anwendung an sich selbst. Nach eigener Darstellung ' +
        'kräftigte ihn das. Ein Nachweis im heutigen Sinne ist dieser ' +
        'Bericht nicht: Es gibt keine gesicherte Diagnose und keine ' +
        'Vergleichsgruppe — die Stimme der Naturheilkunde sagt das in ' +
        'diesem Kapitel selbst.',
    },
    {
      frage: 'Welche fünf Säulen fasst die Kneipp-Lehre zusammen?',
      antworten: [
        'Wasser, Fasten, Beten, Schlaf und Massage.',
        'Wasser, Bewegung, Ernährung, Heilpflanzen und Ordnung.',
        'Wasser, Luft, Licht, Erde und Wärme.',
      ],
      richtig: 1,
      erklaerung:
        'Die fünf Säulen sind Wasser, Bewegung, Ernährung, Heilpflanzen und ' +
        'Ordnung — wobei Kneipp die Ordnung, also die geregelte Lebensweise, ' +
        'für die wichtigste hielt. Die Einteilung in „fünf Säulen" stammt ' +
        'allerdings nicht von ihm selbst, sondern ist eine spätere Ordnung ' +
        'seiner Nachfolger, die seine Bücher zusammenfasst.',
    },
    {
      frage: 'Welches Buch machte Kneipp 1886 weithin bekannt?',
      antworten: [
        '„So sollt ihr leben"',
        '„Meine Wasserkur"',
        '„Das Kneippianum"',
      ],
      richtig: 1,
      erklaerung:
        '„Meine Wasserkur" erschien 1886 bei Kösel in Kempten und wurde ein ' +
        'Bestseller mit zahlreichen Auflagen und Übersetzungen. 1889 folgte ' +
        '„So sollt ihr leben", in dem die Lebensordnung stärker in den ' +
        'Vordergrund rückte. Danach kamen die Kranken in Scharen nach ' +
        'Wörishofen; das Dorf wurde zum Kurort und heißt seit 1920 Bad ' +
        'Wörishofen.',
    },
    {
      frage:
        'Wie verhielt sich Kneipp gegenüber den approbierten Ärzten ' +
        'seiner Zeit?',
      antworten: [
        'Er lehnte jede ärztliche Behandlung grundsätzlich ab.',
        'Er verwies bei ernsten Krankheiten an Ärzte und holte 1890 mit ' +
          'Dr. Alfred Baumgarten einen Badearzt nach Wörishofen.',
        'Er ließ sich selbst zum Arzt ausbilden.',
      ],
      richtig: 1,
      erklaerung:
        'Kneipp war Priester, nicht Arzt, und hat das nie anders ' +
        'dargestellt. Er arbeitete mit dem Badearzt Dr. Alfred Baumgarten ' +
        'zusammen, ließ Kranke untersuchen und verwies weiter, was nicht in ' +
        'seine Hände gehörte. Rechtlich möglich war seine Tätigkeit durch ' +
        'die Kurierfreiheit der Gewerbeordnung von 1869/1871: Heilen durfte ' +
        'jeder, „Arzt" nennen durfte sich nur, wer approbiert war.',
    },
  ],
};

module.exports = kneipp;
