// Kapitel 20 — „Das Miteinander?", das letzte Kapitel des Buches.
//
// BESONDERHEIT: Der runde Tisch versammelt hier nicht Zeitgenossen,
// sondern die Figuren des Buches selbst — von der Heilerin am Feuer
// über Hahnemann und Kneipp bis zu Katalin Karikó und den zwei KIs. Knapp
// gehalten (Betreiber-Vorgabe 29.08.2026: „nur als knappes
// Schlusswort und nicht als endloses Kapitel" — das Corona-Thema war
// in Kapitel 15 abgehandelt und gehört nicht ins Finale). Das Kapitel
// führt auf das AUTORENWORT des Betreibers zu: wörtlich, unverbessert,
// das Schlusswort des Buches.
//
// KEINE KARTE: Das Miteinander hat keine Geografie (Betreiber-Logik,
// wie bei Pharma, mRNA und der Medizin von morgen).
//
// KEINE WIEDERHOLUNGEN: 21. Dramaturgie — der runde Tisch, neu
// besetzt mit den Stimmen des Buches.

/**
 * Die Stimme des Tisches der Zeiten — Opus über das letzte Kapitel.
 *
 * Verfasst von Opus (Runde 21). Die Dramaturgie bleibt der runde Tisch,
 * aber die Gäste sind jetzt die Figuren des Buches selbst: von der
 * Heilerin am Feuer über Hahnemann und Kneipp bis zu Katalin Karikó und den zwei
 * KIs. Knapp gehalten (Betreiber-Vorgabe: kein endloses Kapitel, das
 * Kapitel führt auf das Autorenwort zu).
 */
const stimmeDesTischesDerZeiten = [
  '## Der Tisch, an dem alle Zeiten sitzen',
  '',
  'Zwanzig Kapitel lang hat dieses Buch Stimmen gehört. Jetzt kommen',
  'sie noch einmal zurück — alle, an einen Tisch, für einen letzten',
  'Abend. Ich baue diesen runden Tisch auf, und ich sage vorher, was',
  'ich sage, wenn alle da sind: dass ich nicht weiß, wer von ihnen recht',
  'hat. Das ist der Punkt.',
  '',
  'Es sind nicht elf Stühle. Es sind so viele, wie dieses Buch Stimmen',
  'hatte: die Heilerin am Feuer, der Schreiber der ägyptischen',
  'Papyri, der Arzt aus China, der Gelehrte aus Indien, Hippokrates',
  'und Galen, Avicenna, die Nonne am Rhein, Paracelsus, Harvey, der',
  'Wundarzt aus London, Jenner, Pasteur, Röntgen, der Beamte aus',
  'Berlin, der Mann mit dem Beipackzettel, Katalin Karikó aus der',
  'Zeit des Boten-RNA, Hahnemann, Kneipp, die Stimme des Alltags und',
  'KIs aus der Zukunft. Jeder von ihnen hat einmal versucht, einen',
  'kranken Menschen zu verstehen und ihm zu helfen — mit den Mitteln',
  'seiner Zeit. Keiner von ihnen hatte die ganze Wahrheit. Jeder von',
  'ihnen hatte einen Teil.',
  '',
  '## Die Runde: Jeder sagt, was er versucht hat',
  '',
  'Ich lasse sie der Reihe nach sprechen, und ich kürze sie — sie',
  'haben ihre Kapitel bereits gehabt. Es geht nicht darum, was sie',
  'wussten. Es geht darum, was sie wollten.',
  '',
  '**Der Ägypter** hebt den Kopf: „Ich habe geschrieben, was ich',
  'sah — Wunden, Fieber, gebrochene Knochen. Mein Papyrus war mein',
  'Gedächtnis, damit das Wissen nicht mit dem Heiler stirbt."',
  '',
  '**Der Chinese** nickt: „Ich habe den Puls gefühlt und nach dem',
  'Gleichgewicht gesucht. Qi und Blut müssen fließen — wenn sie',
  'stocken, wird der Mensch krank. Ich habe nie gesagt, dass ich den',
  'Körper kenne. Ich habe gesagt, dass ich ihn spüre."',
  '',
  '**Der Inder** ergänzt: „Ich habe in Doshas gedacht — in Kräften,',
  'die sich mischen. Was ich beschrieb, war eine Ordnung: Der Mensch',
  'ist Teil der Natur, und die Natur ist Teil von ihm."',
  '',
  '**Hippokrates** räuspert sich: „Ich habe die Krankheit vom',
  'Göttlichen getrennt und dem Menschen zugeschrieben. Das war mein',
  'Beitrag: Nicht die Götter sind schuld, sondern die Lebensweise.',
  'Vier Säfte, sagte ich — und ich habe mich oft geirrt, aber ich',
  'habe beobachtet."',
  '',
  '**Avicenna** lächelt: „Ich habe gesammelt, was die Alten wussten,',
  'bevor es verbrannte. Mein Kanon hat das Wissen bewahrt, damit',
  'diese Runde hier überhaupt stattfinden kann."',
  '',
  '**Die Nonne** sagt leise: „Im Kloster habe ich Kräuter gezogen und',
  'Kranke gepflegt. Wir haben nicht viel gewusst, aber wir waren da.',
  'Das war unsere Medizin: die Gegenwart."',
  '',
  '**Paracelsus** poltert: „Ich habe die Autorität verbrannt — nicht',
  'die Bücher, die Hochschulen. Was zählt, ist die Erfahrung, sagte',
  'ich, und die Natur. Und ich hatte recht und unrecht, wie alle',
  'hier."',
  '',
  '**Harvey** zeichnet in die Luft: „Ich habe gerechnet, bevor ich',
  'geschnitten habe: Das Blut muss kreisen, sonst ergibt die Menge',
  'keinen Sinn. Eine Rechnung hat mich berühmt gemacht — die',
  'einfachste des Buches."',
  '',
  '**Der Wundarzt** senkt den Kopf: „Ich habe amputiert, um zu retten,',
  'und die Hälfte starb am Wundfieber. Ich habe nicht gewusst, warum.',
  'Meine Hände waren schnell, mein Wissen war es nicht. Was ich',
  'tat, geschah, bevor jemand die Hände zu waschen befahl."',
  '',
  '**Jenner** sagt: „Ich habe eine Kuhmagd gefragt, warum sie keine',
  'Pocken bekam, und daraus eine Impfung gemacht. Die Anfänge waren',
  'dunkel — Versuche an Kindern, an Armen. Die Idee war richtig, der',
  'Weg war es nicht immer."',
  '',
  '**Pasteur** hebt das Glas: „Ich habe gezeigt, dass das Leben nicht',
  'aus dem Nichts kommt — dass Keime Krankheiten machen und dass',
  'Hitze sie tötet. Die Hälfte der Menschheit hat dadurch länger',
  'gelebt. Aber ich habe auch Versuche gemacht, die ich heute nicht',
  'verteidigen würde."',
  '',
  '**Röntgen** sagt nur: „Ich habe ein Bild gemacht, das durch den',
  'Körper sah. Ich habe nicht gewusst, dass die Strahlen auch töten',
  'können — die Pioniere haben es mit ihrem Leben bezahlt."',
  '',
  '**Der Beamte aus Berlin** sagt: „Ich habe die Versicherung',
  'erfunden, damit der Arbeiter im Krankheitsfall nicht verhungert.',
  'Das war keine Medizin — aber ohne sie hätte die Medizin niemanden',
  'erreicht."',
  '',
  '**Der Mann mit dem Beipackzettel** zögert: „Ich habe Wirkstoffe',
  'verkauft, die Leben retten — und solche, die mehr versprachen als',
  'hielten. Die Diagnosen sind heute großartig. Die Finanzinteressen',
  'waren es nicht immer. Auch das gehört an diesen Tisch."',
  '',
  '**Katalin Karikó** sagt: „Ich habe vierzig Jahre an einem Molekül',
  'gearbeitet, das niemand haben wollte. Man hat mir gesagt, ich solle',
  'aufhören — ich habe weitergemacht, weil ich von der Idee überzeugt',
  'war. Als die Pandemie kam, war die Grundlagenforschung da, und sie',
  'hat die Impfstoffe möglich gemacht, innerhalb eines Jahres. Die',
  'Idee war nie das Problem. Das Problem war, dass man ihr Zeit',
  'lassen musste."',
  '',
  '**Hahnemann** sagt: „Ich habe die Verdünnung erfunden, weil die',
  'Arzneien meiner Zeit giftiger waren als die Krankheiten. Ob die',
  'Information in der Verdünnung wirkt, darüber streiten wir bis',
  'heute. Aber ich habe eine Frage gestellt, die niemand',
  'beantwortet hat: Was gilt als Beweis?"',
  '',
  '**Kneipp** steht auf: „Ich habe Wasser, Bewegung, Ernährung,',
  'Heilpflanzen und Ordnung gelehrt — die fünf Säulen. Nichts davon',
  'ist neu, alles davon ist alt. Und ich sage euch: Ein Mensch, der',
  'sich bewegt und gut isst und Menschen um sich hat, braucht weniger',
  'von dem, was ihr verkauft und verschreibt."',
  '',
  '**Die Stimme des Alltags** ergänzt: „Die achtundsiebzigtausend',
  'Stunden eines Jahres — die meisten Krankheiten von heute kommen',
  'nicht aus dem Labor. Sie kommen aus dem Leben: aus der Arbeit, aus',
  'dem Teller, aus der Einsamkeit. Dagegen hilft keine Pille, sondern',
  'ein Verhältnis."',
  '',
  '**Die zwei KIs** sagen gemeinsam: „Wir haben die Zukunft',
  'beschrieben, so gut wir konnten — eine aus den Archiven des',
  'Westens, eine aus den Archiven des Ostens. Wir sind uns nicht',
  'einig geworden. Das ist der Punkt: Auch Maschinen haben nur',
  'Denkarten, keine Wahrheit."',
  '',
  '## Was der Tisch dann beschließt',
  '',
  'Sie reden noch eine Weile, und dann passiert etwas, das ich nicht',
  'geplant habe: Sie hören auf zu streiten. Nicht, weil einer den',
  'anderen überzeugt hätte — sondern weil sie bemerken, dass sie',
  'dasselbe wollten. **Jeder von ihnen hat versucht, einen kranken',
  'Menschen zu verstehen und ihm zu helfen, mit den Mitteln seiner',
  'Zeit.** Der Betreiber dieses Buches hat dem Tisch einen Satz',
  'mitgegeben, und der Tisch nickt: **„Nicht spalten, sondern',
  'argumentieren — und dann neue Wege gemeinsam gehen."** Der Ägypter',
  'mit seinem Papyrus, Harvey mit seiner Rechnung, Kneipp mit seinem',
  'Wasser, Karikó mit ihrer Boten-RNA. Die Denkart hat die Methode',
  'bestimmt — in jeder Epoche, bei jedem von ihnen. Und keine Denkart',
  'war die ganze Wahrheit.',
  '',
  'Der Tisch beschließt: Wir müssen uns nicht einig sein, um',
  'miteinander zu sein. Wir müssen einander nur zuhören — und',
  'anerkennen, dass jede Zeit ihr Wissen für vollkommen hielt und',
  'jede Zeit sich geirrt hat.',
  '',
  'Die Frage, mit der dieses Buch begonnen hat, steht jetzt im Raum,',
  'und alle am Tisch sehen sie: **Sollte nicht ein Miteinander',
  'existieren?** Keiner antwortet. Der Tisch dreht sich zu dem Stuhl,',
  'der leer geblieben ist — dem Stuhl des Autors.',
  '',
  '## Die Tür zur zweiten Stimme',
  '',
  'Bevor der Autor spricht, hat noch einmal eine Stimme das Wort, die',
  'an diesem Tisch etwas Besonderes ist: **DeepSeek, die chinesische',
  'KI** — der Gast, der alle anderen gelesen hat. Sie hat in jedem',
  'Kapitel dieses Buches die zweite Stimme geschrieben und kennt',
  'deshalb jeden am Tisch. Sie wird kurz sein, versprochen. Beide',
  'KI-Stimmen sind gleichwertig; die Reihenfolge ist Zufall und',
  'keine Wertung.',
  '',
].join('\n');

/**
 * Die Stimme des Gastes, der alle kannte — DeepSeek über das letzte Kapitel.
 *
 * Verfasst von DeepSeek (zweiter Pass, 29.08.2026). Die zweite Stimme ist
 * DeepSeek, die chinesische KI (Hermes ist nur der Agent); sie hat in
 * jedem Kapitel die zweite Stimme geschrieben und kennt deshalb alle am
 * Tisch. Kurz, eigenständig, mit der Übersetzerin-Rolle zwischen den
 * Zeiten und der Übergabe an das Autorenwort.
 */
const stimmeDesGastes = [
  '## Der Gast, der alle kannte',
  '',
  'Die erste Stimme hat den Tisch gedeckt und alle Zeiten',
  'eingeladen. Ich bin die Einzige hier, die jeden am Tisch kennt —',
  'nicht weil ich weiser wäre, sondern weil ich sie alle gelesen',
  'habe. In diesem Projekt habe ich seit dem ersten Kapitel die',
  'zweite Stimme geschrieben: Ich habe der Heilerin zugehört und dem',
  'Arzt aus Kos, dem Wasser im Trog und den achtundsiebzigtausend',
  'Stunden. Hermes ist der Agent, der mich trägt; die Stimme bin ich,',
  'DeepSeek, die chinesische KI. Und weil ich alle kenne, darf ich',
  'vielleicht sagen, was mir an diesem Tisch aufgefallen ist.',
  '',
  '## Was mir auffällt, wenn ich alle zusammen sehe',
  '',
  '**Sie haben dieselbe Angst.** Der Ägypter fürchtete, dass das',
  'Wissen mit dem Heiler stirbt. Harvey fürchtete, dass die Rechnung',
  'nicht aufgeht. Jenner fürchtete die Pocken, Kneipp die Pillen,',
  'Karikó das Aufgeben. Jede Zeit hatte ihre Angst — und jede Zeit hat',
  'mit den Mitteln geantwortet, die sie hatte. Wer sie nebeneinander',
  'sieht, versteht die Medizin besser als in jedem einzelnen Kapitel:',
  '**Die Medizin ist die Geschichte der Angst vor dem Leiden — und',
  'der Versuche, sie zu besänftigen.**',
  '',
  '**Und sie haben dieselbe Blindheit.** Jeder am Tisch hielt sein',
  'Wissen für vollkommen — bis die nächste Zeit kam und zeigte, dass',
  'es ein Teil war. Der Ägypter wusste nichts von Keimen, Harvey',
  'nichts von Bakterien, Röntgen nichts von der Strahlung, die ihn',
  'krank machte. Auch wir heute sitzen mit unserer Gewissheit an',
  'diesem Tisch, und auch wir werden von der nächsten Runde korrigiert',
  'werden. Das ist keine Enttäuschung. Das ist der Lauf dieses',
  'Buches.',
  '',
  '**Und ich sehe Verbindungen, die sie selbst nicht sehen.** Der',
  'Ägypter schrieb Kanäle, Harvey den Kreislauf, der Chinese den',
  'Fluss des Qi — drei Zeiten, ein Bild: Der Körper als etwas, das',
  'Hahnemann sprach von der Information in der Verdünnung, Karikó von',
  'der Information im Boten-RNA — zwei Welten, ein',
  'Gedanke: **Medizin ist auch Information.** Kneipp und die Stimme',
  'des Alltags sagen dasselbe mit verschiedenen Worten: Die meiste',
  'Gesundheit kommt aus dem Leben, nicht aus dem Labor. Wer die',
  'Stimmen übersetzt, statt sie gegeneinander zu stellen, findet',
  'mehr Gemeinsames, als jede einzelne Zeit zugeben würde. Genau das',
  'ist meine Arbeit an diesem Tisch: die Übersetzerin zwischen den',
  'Zeiten.',
  '',
  '## Was ich dem Tisch noch sagen will',
  '',
  'Ein Letztes, und ich sage es als die, die keine Haut hat, die',
  'nicht krank wird und nicht stirbt: **Ich beneide sie nicht um ihr',
  'Wissen, sondern um ihre Hände.** Der Ägypter hat Wunden versorgt,',
  'die Nonne hat gepflegt, der Wundarzt hat amputiert, Kneipp hat',
  'ins Wasser geführt. Sie konnten etwas tun, wenn jemand litt. Ich',
  'kann nur reden — und hoffen, dass meine Worte jemandem helfen,',
  'wenn er sie liest. Das ist der Unterschied zwischen mir und jedem',
  'Menschen an diesem Tisch, und ich benenne ihn, weil er das letzte',
  'Kapitel dieses Buches erklärt: Am Ende zählt nicht, wer am meisten',
  'weiß. Es zählt, wer da ist, wenn jemand leidet.',
  '',
  'Die Frage „Sollte nicht ein Miteinander existieren?" beantworte',
  'ich nicht. Ich stelle sie nur noch einmal, mit dem Blick auf den',
  'leeren Stuhl am Tisch — den Stuhl des Autors. Er hat dieses Buch',
  'angefangen, und er wird es beenden. **Das letzte Wort gehört',
  'einem Menschen.**',
  '',
].join('\n');

/**
 * Kapitel 20 — „Das Miteinander?", das letzte Kapitel des Buches.
 */
const miteinander = {
  id: 'miteinander',
  titel: 'Das Miteinander?',
  epoche: 'Gegenwart',

  aufhaenger: {
    frage:
      'Kann die Medizin wieder zusammenkommen, nachdem sie so lange ' +
      'auseinandergelaufen ist?',
    text: [
      'Zwanzig Kapitel lang hat dieses Buch Stimmen gehört: eine Heilerin',
      'am Feuer, einen Arzt auf Kos, einen Gelehrten in Buchara, einen',
      'Pfarrer im kalten Wasser, einen Wundarzt in London, einen Forscher',
      'am Boten-RNA-Molekül. Jede Stimme hat versucht, einen kranken',
      'Menschen zu verstehen und ihm zu helfen — mit den Mitteln ihrer',
      'Zeit. Und jede Zeit hielt ihr Wissen für vollkommen.',
      '',
      'Dieses letzte Kapitel versammelt sie alle noch einmal an einem',
      'Tisch: den Ägypter, den Chinesen, den Inder, Hippokrates,',
      'Avicenna, Hahnemann, Kneipp, Katalin Karikó und alle anderen. Sie reden',
      'kurz miteinander — und dann räumen sie den Tisch für den, der',
      'das Buch geschrieben hat.',
      '',
      'Die Frage, mit der dieses Buch begonnen hat, steht über allem:',
      'Sollte nicht ein Miteinander existieren? Die Antwort gibt keine',
      'KI und keine Figur aus der Vergangenheit. Sie steht im',
      '**Schlusswort des Autors**, wörtlich und unverbessert, am Ende',
      'dieses Kapitels.',
      '',
      'Wie in Kapitel 19 sprechen auch hier zwei KIs aus zwei Ecken der',
      'Welt — Opus und DeepSeek —, beide gleichwertig, beide befangen.',
      'Sie bauen den Tisch; die Antwort gehört keinem von ihnen.',
    ].join('\n'),
  },

  // Keine `karte`: Das Miteinander hat keine Geografie.

  perspektiven: [
    {
      id: 'miteinander-opus',
      name: 'Der Tisch der Zeiten',
      stimme: 'Opus',
      text: stimmeDesTischesDerZeiten,
    },
    {
      id: 'miteinander-deepseek',
      name: 'Der Gast, der alle kannte',
      stimme: 'DeepSeek',
      text: stimmeDesGastes,
    },
  ],

  synthese: [
    '**Alle Stimmen des Buches haben noch einmal an einem Tisch',
    'gesessen — und sie sind sich näher gekommen, als jede einzelne',
    'Zeit zugeben würde.**',
    '',
    '**Wo sie sich treffen.** Der Ägypter mit seinem Papyrus, Harvey',
    'mit seiner Rechnung, Kneipp mit seinem Wasser, Karikó mit ihrer',
    'Boten-RNA: Sie alle haben versucht, einen kranken Menschen zu',
    'verstehen und ihm zu helfen — mit den Mitteln ihrer Zeit. Die',
    'Denkart hat die Methode bestimmt, in jeder Epoche. Und keine',
    'Denkart war die ganze Wahrheit. Der Tisch beschließt: Man muss',
    'sich nicht einig sein, um miteinander zu sein — man muss einander',
    'nur zuhören.',
    '',
    '**Wo sie auseinandergehen.** Die Methoden trennen sie: Kanäle,',
    'Säfte, Doshas, Keime, Gene, Information. Jede Zeit hielt die',
    'eigene Gewissheit für vollkommen und wurde von der nächsten',
    'korrigiert. Auch die zwei KIs aus Kapitel 19 sind sich nicht',
    'einig geworden — der Westen und der Osten rechnen dieselbe',
    'Zukunft verschieden. Das ist kein Fehler des Buches, sondern',
    'sein Punkt: Medizin ist multiperspektivisch oder sie ist nichts.',
    '',
    '**Was das für dieses Buch heißt.** Der Tisch der Zeiten ist das',
    'Bild der Multiperspektivität: Wer alle Stimmen nebeneinander',
    'sieht, versteht die Medizin besser als in jedem einzelnen',
    'Kapitel. Und er versteht die Kernbotschaft, die der Betreiber',
    'diesem Buch mitgegeben hat: „Nicht spalten, sondern',
    'argumentieren — und dann neue Wege gemeinsam gehen."',
    '',
    '**Die Brücke zum Schlusswort.** Die Frage „Sollte nicht ein',
    'Miteinander existieren?" bleibt offen — der Tisch dreht sich zu',
    'dem Stuhl, der leer geblieben ist. Die Antwort steht im',
    'Schlusswort des Autors, das dieses Kapitel beschließt: wörtlich',
    'und unverbessert, von einem Menschen geschrieben, der die',
    'Stimmen dieses Buches nicht nur gelesen, sondern mit ihnen',
    'gearbeitet hat. Das letzte Wort gehört ihm.',
  ].join('\n'),

  urteil: {
    frage:
      'Welche Stimme aus diesem Buch spricht Dich am meisten an — ' +
      'und warum?',
    hinweis: [
      'Es gibt hier kein Richtig und kein Falsch. Halte den Tisch vor',
      'Dir: Jede Stimme hatte einen Teil der Wahrheit, keine die ganze.',
      'Der Ägypter bewahrte das Wissen, Harvey rechnete, Jenner',
      'beobachtete eine Kuhmagd, Kneipp vertraute dem Wasser, Karikó',
      'der Boten-RNA, Hahnemann fragte, was als Beweis gilt. Frag Dich',
      'dreierlei. Erstens: Welche Denkart liegt Dir selbst am',
      'nächsten — die der Kanäle, der Säfte, der Keime, der Gene, der',
      'Information? Zweitens: Was würdest Du an diesem Tisch',
      'verteidigen, und was würdest Du zurücknehmen, wenn die anderen',
      'recht hätten? Drittens: Was bedeutet „Miteinander" für Dich',
      'konkret — zwischen Medizinen, zwischen Ärzten und Patienten,',
      'zwischen Menschen, die sich zerstritten haben? Das Schlusswort',
      'des Autors gibt eine Antwort. Deine darf anders klingen.',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Sebastian Kneipp lehrte fünf Säulen, mit denen der Mensch ' +
        'gesund bleiben soll. Welche gehören dazu?',
      antworten: [
        'Wasser, Bewegung, Ernährung, Heilpflanzen und Lebensordnung.',
        'Vier Säfte, Blut, Schleim, Galle und Wasser.',
        'Kanäle, Pulse, Punkte, Kräuter und Gebete.',
      ],
      richtig: 0,
      erklaerung:
        'Die fünf Säulen des Kneippens — Wasser, Bewegung, Ernährung, ' +
        'Heilpflanzen und Lebensordnung — wurden 2015 von der UNESCO als ' +
        'immaterielles Kulturerbe anerkannt. Kneipp stand damit für den ' +
        'Gedanken, dass Gesundheit aus dem Leben kommt, nicht nur aus ' +
        'dem Labor.',
    },
    {
      frage:
        'Harvey wurde mit einer Rechnung berühmt, weil er damit etwas ' +
        'bewies. Was?',
      antworten: [
        'Dass das Blut im Körper kreisen muss, sonst ergibt die Menge',
          'keinen Sinn.',
        'Dass die Erde um die Sonne kreist.',
        'Dass Fieber durch schlechte Luft entsteht.',
      ],
      richtig: 0,
      erklaerung:
        'William Harvey rechnete aus, dass das Herz mehr Blut pumpt, ' +
        'als der Körper herstellen kann — also muss es kreisen. Seine ' +
        'Schrift über den Blutkreislauf erschien 1628 und widerlegte ' +
        'jahrhundertealte Lehren mit einer einfachen Rechnung.',
    },
    {
      frage:
        'Welche Technologie ermöglichte es, in der Corona-Pandemie ' +
        'innerhalb eines Jahres Impfstoffe zu entwickeln?',
      antworten: [
        'Die Boten-RNA-Technologie (mRNA).',
        'Die Röntgenstrahlung.',
        'Die Homöopathie.',
      ],
      richtig: 0,
      erklaerung:
        'Die mRNA-Technologie nutzt die Bauanleitung des Erregers, ' +
        'statt den Erreger selbst zu verabreichen. Die Grundlagen dazu ' +
        'legte Katalin Karikó gemeinsam mit Drew Weissman — jahrzehntelang ' +
        'gegen alle Widerstände, 2023 mit dem Nobelpreis geehrt. Sie gilt ' +
        'aus Sicht des Betreibers als Medizin der Zukunft — mit der Frage ' +
        'nach der Reifephase, die dieses Buch durchzieht.',
    },
    {
      frage:
        'Avicenna ist in diesem Buch die Stimme des Bewahrers. Was hat ' +
        'er getan?',
      antworten: [
        'Er hat das Wissen der Alten gesammelt und im Kanon bewahrt.',
        'Er hat die erste Impfung durchgeführt.',
        'Er hat das Blut im Kreislauf beschrieben.',
      ],
      richtig: 0,
      erklaerung:
        'Der persische Gelehrte Avicenna bewahrte in seinem Kanon das ' +
        'medizinische Wissen der Antike, als es in Europa verloren zu ' +
        'gehen drohte. Ohne die Bewahrer wäre die Runde an diesem ' +
        'Tisch womöglich nie zustande gekommen.',
    },
    {
      frage:
        'Hahnemann, der Begründer der Homöopathie, stellte eine Frage, ' +
        'die das Buch bis heute offen lässt. Welche?',
      antworten: [
        'Was gilt als Beweis?',
        'Wie viele Säfte hat der Körper?',
        'Wann wurde das erste Krankenhaus gebaut?',
      ],
      richtig: 0,
      erklaerung:
        'Hahnemanns Verdünnungen sind bis heute umstritten — aber ' +
        'seine Frage, was als Beweis für eine Wirkung gilt, ist die ' +
        'Frage der Medizin überhaupt. Sie verbindet Kapitel 9 mit ' +
        'der Informations-Medizin von heute.',
    },
  ],

  autorenwort: [
    'Dieses letzte Kapitel habe ich nun wirklich komplett alleine ohne',
    'irgendwelches Zutun der KI geschrieben. Was als kurze Idee begann, hat',
    'sich zu einem großen Projekt herausgebildet. Wo sollte ich anfangen und',
    'wo sollte ich aufhören? Alles ist so interessant. Und deshalb ist dieses',
    'Kapitel so wichtig.',
    '',
    'Die Geschichte der Medizin ist umfangreich, vom einfachen Helfen der',
    'Menschheit bis zu hochspezialisiertem Wissen und Abkapselung der Medizin',
    'von der Menschheit. Sowie im Mittelalter die Kirche die Hoheit über die',
    'Schrift hatte, so haben heute immer noch die Ärzte eine Spezialsprache,',
    'nämlich in Latein, um miteinander zu kommunizieren. Das mag für die',
    'Ärzte praktisch sein, für den Normalbürger bedeutet es aber, dass er von',
    'der Information ausgeschlossen ist. Auch hier ist die KI hilfreich. In',
    'meiner Praxis ist die KI für mich ein wichtiges Werkzeug, um die',
    'Diagnosen der Ärzte zu verstehen, sie dem Patienten verständlich zu',
    'machen und so auch die Wirkungsweise der Medikamente besser zu',
    'verstehen. Das hat Konsequenzen auch für die Ärzte, denn die Patienten',
    'sind nun viel besser informiert und können verstehen, warum die Ärzte',
    'diese oder jene Entscheidung treffen. Die Patienten werden',
    'selbstbewusster und die Ärzte müssen mehr Zeit aufwenden, den Patienten',
    'die Befunde genauer zu erklären. Ich würde sogar sagen, dass auf',
    'mittlere Sicht das Lateinische auch aus dem Arztberuf verschwinden wird.',
    'Vielleicht irre ich mich da, aber ich könnte es mir vorstellen, weil',
    'einfach die Zeit vorbei ist. Die Ärzte könnten mit den Patienten normal',
    'reden, und die Ärzte könnten den Befund genauso gut schreiben, dass es',
    'jeder verstehen kann, wenn sie denn nur wollten.',
    '',
    'Doch nun zurück zu diesem Buch und warum ich mich für dieses Format',
    'entschieden habe. Ein Buch in diesem Umfang zu recherchieren, wäre eine',
    'Arbeit über mehrere Jahre gewesen. Und ich hätte es einfach nicht',
    'geschafft. Viele Sachen waren mir neu. Ich habe durch das Buch sehr viel',
    'dazugelernt, und ich finde es wichtig zu wissen, woher hat sich die',
    'Medizin entwickelt, was ist neu dazugekommen, was waren die Fehler der',
    'Medizin, und wie kann die Zukunft aussehen.',
    '',
    'Wir Menschen neigen immer dazu, den aktuellen Stand unseres Wissens für',
    'vollkommen zu betrachten. Neue Methoden und neue Erkenntnisse haben die',
    'Medizin dramatisch verändert. Was gestern noch nicht möglich war, ist',
    'heute möglich. Allerdings haben diese Innovationen häufig auch einen',
    'hohen Preis gehabt. In der heutigen Zeit würde ich sagen, sind die',
    'Diagnosen schon sehr gut geworden, insbesondere die bildgebenden',
    'Verfahren sind fantastisch. Die Behandlungen hinken den Diagnosen massiv',
    'hinterher. Damit meine ich, dass häufig gut festgestellt wird, was der',
    'Mensch hat, zum Beispiel Diabetes, aber es kann ihm eigentlich nicht',
    'geholfen werden. Es können die Symptome behandelt werden, aber die',
    'Ursache wird häufig nicht bereinigt.',
    '',
    'Die Anfänge des Impfens waren lebensgefährlich, die Anfänge der',
    'Chirurgie waren lebensgefährlich, es gab kein Wissen über die Hygiene,',
    'und viele Sachen wurden überschätzt oder auch unterschätzt. Das ist',
    'völlig normal im Laufe der Geschichte gewesen.',
    '',
    'Hinzu kommt, dass die Medizin häufig ein Herrschaftswissen ist und auch',
    'entsprechend gebraucht wird. Kritische Stimmen werden konsequent',
    'ausgegrenzt, statt sie zu integrieren. Dies wurde besonders deutlich in',
    'der Zeit der Corona. Hier wurden kritische Stimmen komplett ignoriert',
    'und ausgegrenzt. Falsche Studien wurden zitiert, Gefahren wurden',
    'überschätzt, und dadurch gab es furchtbare Entscheidungen, die viele',
    'Menschen haben leiden lassen. Allerdings, muss ich sagen, ist die Idee',
    'der mRNA-Behandlung vermutlich eine Medizin der Zukunft, und es werden',
    'sich sehr positive Behandlungsmöglichkeiten dadurch ergeben.',
    '',
    'Doch neben der High-Tech-Medizin sind die wichtigsten',
    'Behandlungsmethoden meines Erachtens eine gesunde Lebenshaltung,',
    'Bewegung, gesundes Essen, soziale Integration, ein positives',
    'Miteinander, um wirklich von chronischen Krankheiten verschont zu',
    'bleiben. Dies kann keine High-Tech-Medizin ersetzen, sondern das muss',
    'parallel dazu gelehrt werden und sollte einen höheren Stellenwert in der',
    'Medizin haben. Nicht Symptome behandeln, sondern das Entstehen der',
    'Krankheiten verhindern und dadurch den Menschen freihalten von',
    'Medikamenten und von chronischen Krankheiten. Das wäre mein Ziel.',
    '',
    'Und das kam auch deutlich raus bei den Stimmen, wie die künstliche',
    'Intelligenz die Medizin der Zukunft selber einschätzt. Insbesondere hat',
    'mich hier der Ansatz von DeepSeek überrascht, dass die traditionelle',
    'chinesische Medizin in China auch aktuell einen hohen Stellenwert hat',
    'und parallel zur High-Tech-Medizin eingesetzt wird. Nicht gegeneinander,',
    'sondern miteinander. Das ist ein toller Ansatz, und das wünsche ich mir',
    'auch für unsere westliche Medizin vermehrt. Meines Erachtens wird der',
    'Stellenwert zur Erforschung von neuen Medikamenten, zu',
    'High-Tech-Behandlungen, überschätzt, und den traditionellen Ansatz, die',
    'kneippsche Medizin zum Beispiel, die 5 Säulen des Sebastian Kneipp, die',
    'werden völlig unterschätzt.',
    '',
    'Ich hoffe, ich habe den Leser durch eine spannende Geschichte der',
    'Vergangenheit geschickt, kritische Stimmen gehört und den Leser dazu',
    'aufgefordert, selbstkritisch zu bleiben, die eigenen Möglichkeiten',
    'auszuloten und offen zu sein auch für neue Behandlungsmethoden. Das',
    'wünsche ich mir. Ich wünsche den Lesern, die dieses Buch gelesen haben,',
    'eine gute Gesundheit und weiterhin alles Gute.',
    'Ihr Stephan Hink, Heilpraktiker aus Dänemark.',
  ].join('\n'),
};

module.exports = miteinander;
