// Kapitel 11 — „Pasteur und Lister".
//
// Das dritte Kapitel der Neuzeit und der Wendepunkt des ganzen Buches: Hier
// findet die Medizin die Ursache der Wundinfektion, die Semmelweis in
// Kapitel 9 gesehen, aber nicht benennen konnte. Ein Chemiker in Frankreich
// erklärt, was Gärung ist — und ein Chirurg in Schottland zieht daraus die
// Folgerung für den Operationstisch.
//
// Die DENKART-Analyse ist das Herzstück (Betreiber-Vorgabe). Sie fragt
// hier: Warum die Gärung? (Weil ein Chemiker, der der Industrie helfen
// sollte, in verdorbenem Wein, saurem Bier und kranken Seidenraupen immer
// dasselbe Muster fand — winzige Lebewesen, die etwas zersetzen.) Warum
// die Keime? (Weil sie überall sind: in der Luft, im Staub, auf der Haut —
// und weil sie in die Flasche fallen wie in die offene Wunde.) Warum
// musste die Urzeugung fallen? (Weil Keime, die aus dem Nichts entstehen,
// keine Ursache wären, sondern Folge — die ganze Keimtheorie hing daran.)
// Warum abschwächen statt abtöten? (Weil der Körper einen lebenden, aber
// erschöpften Gegner besser kennenlernt.) Und die große Ablösung: Die
// Denkart des Gleichgewichts weicht der Denkart der Ursache — Krankheit
// ist ein Eindringling, kein gestörtes Maß.
//
// LÄNGENREGEL (Betreiber-Feedback 24.08.2026): Ab Kapitel 9 gilt die
// Umkehrung — vollständig und ausführlich. Ausführlich heißt nicht
// aufgebläht: jeder Absatz bringt die Erzählung voran. Gemessen wird in
// tests/karte-pasteur-lister.mjs.
//
// TONE-Regel: BEIDE Seiten fair. Diese erste Stimme spricht aus dem Labor
// und benennt die unbequemen Stellen der eigenen Seite selbst: die
// Inszenierung von Pouilly-le-Fort und den Impfstoff, über den Pasteur
// öffentlich anders sprach als in seinen Heften (Gerald Geison, 1995); die
// Tollwut-Impfung an einem Kind ohne Vorprüfung am Menschen; die zwei
// Behandlungen vor Joseph Meister, von denen er nicht sprach; den
// Ehrgeiz, den Streit mit Pouchet und mit Koch; und die Grenze der eigenen
// Denkart — der Keim erklärt nicht, warum der eine erkrankt und der
// andere nicht.
//
// KEINE GERÜCHTE (Betreiber-Entscheid 25.08.2026): Nur Belegtes. Zwei
// bekannte Erzählungen um Pasteur sind NICHT belegt und werden im Text
// ausdrücklich als unbestätigt gekennzeichnet: der angebliche Satz auf dem
// Sterbebett („der Keim ist nichts, das Milieu ist alles") und die
// verbreitete Deutung des Todes von Joseph Meister im Juni 1940.
//
// Stimmen (Runde 12): Die ERSTE Perspektive — das Labor, die Stimme
// Pasteurs — verfasste Opus. Die ZWEITE (die Klinik: Joseph Lister in
// Glasgow, die Karbolsäure, die Zahlen, der Spott der Kollegen, die
// Verbindung von Labor und Klinik als das eigentliche Ereignis) und die
// finale Synthese ergänzt Hermes im zweiten Pass. Perspektiven-Workflow:
// CLAUDE.md.
//
// KEINE WIEDERHOLUNGEN (Betreiber-Entscheid vom 21.08.2026): Kapitel 1
// gliedert nach „Wer hier spricht", Kapitel 2 beginnt mit einer Szene,
// Kapitel 3 erzählt einen Tageslauf, Kapitel 4 ist ein Briefwechsel,
// Kapitel 5 die Reise eines Buches, Kapitel 6 ein Rundgang, Kapitel 7 ein
// Prozess, Kapitel 8 eine Rechnung, Kapitel 9 eine Uhr, Kapitel 10 eine
// Kette. Dieses Kapitel wählt die zwölfte Dramaturgie: DAS MIKROSKOP. Die
// Abschnitte sind Präparate, die nacheinander unter die Linse kommen — ein
// Tropfen kranker Rübensaft, der Staub der Luft, der Hals einer Flasche,
// eine Seidenraupe, das Blut eines verendeten Schafes, das Rückenmark
// eines Kaninchens. Die zweite Stimme kann dieselbe Linse über den
// Operationstisch halten: Dort liegt das Präparat, das Pasteur nie
// bekommen hat — eine offene Wunde.
//
// Die Texte liegen als Zeilen-Arrays mit `.join('\n')` — so bleiben sie im
// Repo bei ~72 Zeichen lesbar (der Betreiber liest sie hier gegen), und
// utils/markdown.js macht in der App wieder fließenden Text daraus.
//
// CommonJS ohne UI-Importe (Architektur-Regel): mit blankem `node` prüfbar.

const { karte } = require('./karten/pasteur-lister');

/**
 * Die Stimme des Labors — die Keimtheorie von innen.
 *
 * Verfasst von Opus (Runde 12). Eine Stimme, die für Louis Pasteur und
 * seine Mitarbeiter spricht: Émile Roux, Charles Chamberland, Louis
 * Thuillier. Sie erzählt, warum sie taten, was sie taten — und sie benennt
 * die unbequemen Stellen selbst (Zusatzregel für sensible Themen in
 * CLAUDE.md).
 */
const stimmeDesLabors = [
  '## Die Linse',
  '',
  'Wir fangen mit einem Gerät an, nicht mit einem Menschen.',
  '',
  'Auf dem Tisch steht ein Mikroskop. Darunter liegt ein Glasplättchen,',
  'auf dem Plättchen ein Tropfen Flüssigkeit. Was in diesem Tropfen',
  'schwimmt, ist zu klein, um es zu ahnen, und es entscheidet, ob ein',
  'Fass Wein verkauft oder weggeschüttet wird, ob eine Familie von der',
  'Seidenzucht leben kann — und, wie sich zeigen wird, ob ein Mensch',
  'stirbt oder nicht.',
  '',
  '**Was Du hier hörst, ist die Sicht des Labors — eine Denkart, keine',
  'Wahrheit.** Wir sprechen für den Chemiker Louis Pasteur (1822–1895)',
  'und für die, die mit ihm an diesem Tisch standen: Émile Roux, Charles',
  'Chamberland, Louis Thuillier. Wir sind keine Ärzte. Wir haben nie ein',
  'Krankenbett betreut, nie eine Wunde genäht, nie ein Rezept',
  'geschrieben. Wir haben Gärungen untersucht. Dass daraus die größte',
  'Wende der Medizingeschichte wurde, hat uns selbst überrascht.',
  '',
  'Wir erzählen dieses Kapitel deshalb so, wie wir gearbeitet haben:',
  '**als eine Folge von Präparaten.** Eines nach dem anderen kommt unter',
  'die Linse, und jedes beantwortet eine Frage und stellt die nächste.',
  'Am Ende liegt ein Präparat auf dem Tisch, das wir nicht mehr',
  'untersuchen konnten — eine offene Wunde. Für die brauchte es einen',
  'Chirurgen.',
  '',
  'Und weil Du uns nicht glauben sollst, nur weil wir Denkmäler haben:',
  'Wir legen auch das unter die Linse, was uns schlecht aussehen lässt.',
  'Es ist nicht wenig.',
  '',
  '## Das erste Präparat: ein Tropfen kranker Rübensaft',
  '',
  'Lille, im Sommer 1856. Eine Stadt aus Fabrikschornsteinen, und der',
  'neue Dekan der naturwissenschaftlichen Fakultät hat den ausdrücklichen',
  'Auftrag, den Fabriken zu nützen. Ein Brennereibesitzer namens Bigo',
  'kommt mit einem teuren Problem: Aus seinem Rübensaft wird kein',
  'Alkohol mehr, sondern eine schleimige, saure Brühe. Ganze Bottiche',
  'sind verloren. Niemand weiß, warum.',
  '',
  'Der Dekan holt Proben aus den guten und aus den verdorbenen Bottichen',
  'und legt beide unter die Linse. **In den guten schwimmen runde,',
  'pralle Hefekügelchen. In den verdorbenen liegen andere, viel',
  'kleinere Gebilde: kurze Stäbchen.** Nicht wenige. Millionen.',
  '',
  'Für einen Chemiker jener Jahre ist das kein Befund, sondern ein',
  'Ärgernis. Die herrschende Lehre — sie stammt von Justus von Liebig,',
  'dem angesehensten Chemiker Europas — sagt: Gärung ist ein',
  'chemischer Zerfall. Etwas Totes fällt auseinander und reißt im',
  'Vorbeigehen den Zucker mit. Die Hefe ist nach dieser Lehre ein',
  'Rückstand des Vorgangs, nicht sein Urheber. Was man da unter dem',
  'Mikroskop sieht, ist Abfall.',
  '',
  'Wir haben es umgedreht, und das ist der erste und vielleicht',
  'wichtigste Satz dieses Kapitels: **Die Hefe ist kein Abfall. Sie ist',
  'ein Lebewesen, und die Gärung ist das, was sie tut.** Wer Zucker in',
  'Alkohol verwandelt, ist nicht die Chemie, sondern ein Organismus, der',
  'davon lebt. Und wenn statt Alkohol Milchsäure entsteht, dann liegt',
  'das nicht an einem gestörten Zerfall, sondern daran, dass ein anderes',
  'Lebewesen im Bottich sitzt — das Stäbchen statt der Kugel.',
  '',
  '**Warum ausgerechnet die Gärung?** Nicht aus Neugier auf den Wein.',
  'Sondern weil in ihr etwas sichtbar wird, was man sonst nirgends so',
  'sauber sehen kann: **eine große, folgenreiche Veränderung, die von',
  'einem winzigen Lebewesen ausgeht.** Ein paar Kügelchen, die niemand',
  'mit bloßem Auge sieht, verwandeln ein ganzes Fass. Wer das einmal',
  'gesehen hat, denkt bei jeder anderen Verwandlung, die von selbst zu',
  'geschehen scheint, dasselbe: Vielleicht steckt auch da jemand',
  'dahinter, den ich nur nicht sehe.',
  '',
  'Und noch etwas kommt hinzu, was die Sache praktisch machte: Wir',
  'konnten sie **lenken**. Wein, den man kurz auf etwa fünfundfünfzig',
  'Grad erwärmt, verdirbt nicht mehr — die störenden Lebewesen sterben,',
  'der Wein bleibt trinkbar. 1865 wurde das Verfahren geschützt; heute',
  'trägt es unseren Namen, und es steht auf jeder Milchpackung. **Wenn',
  'man ein Übel abstellen kann, indem man etwas Lebendiges abtötet,',
  'dann war das Übel lebendig.**',
  '',
  '## Das zweite Präparat: der Staub in der Luft',
  '',
  'Damit stand die nächste Frage: Woher kommen sie?',
  '',
  'Der Bottich war sauber gewesen. Der Saft war frisch. Trotzdem sitzen',
  'plötzlich Millionen Stäbchen darin. Kommen sie von außen — oder',
  'entstehen sie im Bottich?',
  '',
  'Wir haben deshalb die Luft selbst unter die Linse gelegt. Man saugt',
  'Luft durch einen Pfropf aus Schießbaumwolle, löst den Pfropf auf und',
  'sieht sich an, was hängen geblieben ist. Man findet Staub — und',
  'zwischen den Staubkörnchen kleine Körper, die aussehen wie das, was',
  'im verdorbenen Bottich schwimmt.',
  '',
  'Das klingt harmlos und ist eine Weltbeschreibung: **Die Luft ist',
  'nicht leer.** In jedem Zimmer, über jedem Tisch, in jedem Atemzug',
  'schwebt eine unsichtbare Fracht. Sie legt sich auf alles, was',
  'offensteht: auf die Brühe, auf das Fleisch, auf die Milch — und, das',
  'wird später der ganze Punkt sein, auf jede offene Wunde.',
  '',
  '**Warum ist das die entscheidende Beobachtung?** Weil sie eine',
  'jahrtausendealte Erklärung ersetzt. Die Ärzte vor uns sprachen von',
  'Miasmen: von schlechter, verdorbener Luft, die krank macht — der',
  'Sumpf, der Gestank, die üblen Dünste. Sie hatten nicht unrecht in',
  'dem, was sie beobachteten; wo es stank, wurde man krank. Aber sie',
  'hatten die falsche Ursache. **Nicht der Geruch macht krank. Das, was',
  'mit dem Staub in der Luft schwebt, macht krank.** Der Unterschied',
  'sieht klein aus und ist gewaltig: Gegen einen Gestank kann man wenig',
  'tun. Gegen etwas Lebendiges, das man abtöten, filtern und',
  'fernhalten kann, sehr viel.',
  '',
  '## Das dritte Präparat: der Hals einer Flasche',
  '',
  'Und nun zu dem Streit, der uns Jahre gekostet hat und ohne den nichts',
  'von alledem gestanden hätte.',
  '',
  'Gegen unsere Erklärung stand eine ehrwürdige Lehre: die **Urzeugung**.',
  'Sie besagt, dass niederes Leben aus toter Materie von selbst entsteht',
  '— in faulendem Fleisch, in Heuaufgüssen, in einer Brühe, die',
  'stehenbleibt. Ihr angesehenster Verteidiger war Félix-Archimède',
  'Pouchet, der Direktor des Naturkundemuseums in Rouen, ein ernsthafter',
  'Mann mit ernsthaften Versuchen: Er kochte seine Aufgüsse ab,',
  'verschloss sie, ließ nur geglühte Luft hinein — und fand darin doch',
  'wieder Leben.',
  '',
  '**Warum mussten wir die Urzeugung widerlegen?** Weil ohne das die',
  'ganze Keimtheorie zusammenfällt, und zwar an ihrer wichtigsten',
  'Stelle. Denk es zu Ende: Wenn in einer faulenden Wunde Leben von',
  'selbst entstehen kann, dann sind die Keime, die man dort findet,',
  '**nicht die Ursache der Fäulnis, sondern ihre Folge** — Beiwerk, das',
  'sich einstellt, wenn das Fleisch verdirbt. Dann ist jede Maßnahme',
  'gegen Keime sinnlos, denn sie entstehen ja immer wieder neu. **Die',
  'Frage, ob Leben aus dem Nichts entsteht, ist deshalb keine',
  'philosophische Spielerei. Sie entscheidet, ob es sich lohnt, ein',
  'Messer auszukochen.**',
  '',
  'Unsere Antwort war ein Stück Glas. Man nimmt einen Kolben mit Brühe,',
  'erhitzt den Hals in der Flamme und zieht ihn zu einem langen, nach',
  'unten gebogenen Schwanenhals aus. Der Kolben bleibt **offen** — die',
  'Luft geht ein und aus, ungehindert. Nur der Staub kommt nicht durch:',
  'Er setzt sich in der Biegung ab, weil er schwerer ist als die Luft.',
  'Dann kocht man die Brühe einmal auf und stellt den Kolben hin.',
  '',
  'Er bleibt klar. Wochen, Monate, Jahre. Einige dieser Kolben stehen',
  'bis heute klar im Institut in Paris. Kippt man den Kolben aber so,',
  'dass die Brühe die Biegung berührt und wieder zurückläuft, oder',
  'bricht man den Hals ab, dann trübt sie sich binnen ein bis zwei',
  'Tagen. **Es lag nie an der Luft. Es lag immer am Staub in der Luft.**',
  '',
  'Wir haben die Probe dann in die Landschaft getragen, und das war der',
  'schönste Teil der Arbeit: zwanzig zugeschmolzene Kolben, geöffnet im',
  'staubigen Hof, zwanzig geöffnet in einem kühlen Keller, zwanzig',
  'geöffnet auf den Feldern bei Arbois — und zwanzig hoch oben auf dem',
  'Eismeer bei Chamonix, in Luft, in der kaum etwas schwebt. Das',
  'Ergebnis war eine Staffel: **Je reiner die Luft, desto weniger Kolben',
  'verdarben.** Auf dem Gletscher blieb fast alles klar. Am 7. April',
  '1864 haben wir das in der Sorbonne vor großem Publikum vorgeführt.',
  '',
  'Und jetzt die unbequeme Hälfte dieser Geschichte, die in den',
  'Schulbüchern selten steht.',
  '',
  '**Pouchets Versuche waren nicht gefälscht, und er war kein Narr.** Er',
  'arbeitete mit Heuaufgüssen. In Heu stecken Dauerformen von Bakterien',
  '— Sporen —, die kochendes Wasser überstehen. Wer Heubrühe zehn',
  'Minuten kocht, hat sie nicht keimfrei gemacht; sie wird nachher',
  'trüb, ganz ohne Urzeugung. Wir arbeiteten mit Hefewasser und',
  'Zuckerlösungen, die sich durch Kochen tatsächlich keimfrei machen',
  'ließen. **Wir hatten also nicht nur die bessere Erklärung, wir hatten',
  'auch das gefügigere Material.** Dass Sporen so hitzefest sind, hat',
  'erst ein knappes Jahrzehnt später John Tyndall gezeigt.',
  '',
  'Wir haben diesen Vorteil nicht ausgesprochen. Wir haben stattdessen',
  'auf öffentliche Vorführungen gedrängt und Pouchet vor Kommissionen',
  'zitiert, deren Bedingungen wir mitbestimmten; er zog sich am Ende',
  'zurück. Wissenschaftshistoriker haben das später nachgezeichnet, und',
  'sie haben recht: **Wir haben den Streit auch mit den Mitteln des',
  'besseren Redners gewonnen, nicht allein mit denen des besseren',
  'Versuchs.** Unsere Schlussfolgerung war richtig. Der Weg dorthin war',
  'nicht so sauber wie die Kolben.',
  '',
  '## Das vierte Präparat: eine kranke Seidenraupe',
  '',
  '1865 rief uns die Regierung in den Süden. In den Tälern um Alès',
  'starben die Seidenraupen; eine ganze Landschaft lebte von ihnen, und',
  'sie war dabei, zu verarmen. Wir wussten über Seidenraupen nichts.',
  'Wir hatten noch nie eine gesehen.',
  '',
  'Fünf Jahre haben wir dort verbracht. Unter der Linse fanden wir in',
  'den kranken Tieren winzige Körperchen, und wir fanden sie auch in den',
  'Faltern, die noch gesund aussahen und die Eier legten. **Daraus wurde',
  'ein Verfahren, das keinen Franken kostete: Man untersucht nach dem',
  'Eierlegen den Falter unter dem Mikroskop. Sind die Körperchen da,',
  'werden die Eier vernichtet. Sind sie nicht da, sind die Eier',
  'gesund.** Die Zucht ließ sich damit retten. Es war das erste Mal,',
  'dass unsere Arbeit nicht ein Fass, sondern ein Gewerbe rettete.',
  '',
  'Diese fünf Jahre waren die schwersten unseres Lebens, und sie gehören',
  'in dieses Kapitel, weil sie erklären, warum wir später so unbedingt',
  'wurden. In diese Zeit fallen der Tod des Vaters und der Tod zweier',
  'Töchter: Camille, zwei Jahre alt, und Cécile, zwölf. Eine dritte',
  'Tochter, Jeanne, war 1859 mit neun Jahren am **Typhus** gestorben.',
  'Drei von fünf Kindern. Kein Arzt konnte etwas tun, und niemand',
  'konnte sagen, woran es lag.',
  '',
  'Im Oktober 1868, mit fünfundvierzig Jahren, kam ein Schlaganfall. Die',
  'linke Seite blieb gelähmt; das Bein schleifte, die Hand war kaum zu',
  'gebrauchen. **Alles, was in diesem Kapitel noch kommt — der',
  'Milzbrand, die Hühnercholera, die Tollwut, das Institut —, ist die',
  'Arbeit eines halbseitig gelähmten Mannes**, der die Handgriffe',
  'ansagen musste, weil andere sie ausführten.',
  '',
  'Und in diesen Jahren fiel der Satz, der aus einer Beobachtung über',
  'Wein und Raupen eine Medizin machte: **Was die Gärung für den Wein',
  'ist, ist die Krankheit für den Menschen.** In beiden Fällen dringt',
  'ein winziges Lebewesen ein, vermehrt sich und verwandelt das Ganze.',
  'Der Wein wird sauer, die Raupe stirbt, der Mensch bekommt Fieber. Es',
  'ist derselbe Vorgang in einem anderen Behälter.',
  '',
  '## Was unter keinem Glas zu sehen ist: die Denkart',
  '',
  'Halten wir an dieser Stelle an, denn hier liegt das Eigentliche, und',
  'es liegt nicht unter der Linse, sondern hinter ihr.',
  '',
  'Zweitausend Jahre lang hat die Medizin Krankheit als **Störung eines',
  'Gleichgewichts** verstanden. Bei Hippokrates und Galen sind es die',
  'vier Säfte, die aus dem Maß geraten; in der chinesischen Medizin ist',
  'es das Qi, das nicht fließt; im Ayurveda sind es die Doshas. So',
  'verschieden diese Lehren sind, sie teilen eine Grundfigur: **Krank',
  'ist ein Mensch, bei dem etwas nicht mehr stimmt — zu viel, zu wenig,',
  'zu heiß, zu kalt, blockiert.** Behandlung heißt dann: das Maß',
  'wiederherstellen, ableiten, wärmen, kühlen, stärken.',
  '',
  'Unsere Denkart ist eine andere, und sie ist der Bruch, um den es in',
  'diesem ganzen Buch geht: **Die Krankheit ist ein Eindringling, kein',
  'Gleichgewicht.** Sie kommt von außen. Sie hat einen Namen, eine',
  'Gestalt, eine Lebensweise, einen Weg, auf dem sie reist. Man kann sie',
  'anfärben, züchten, unter das Glas legen und zählen.',
  '',
  'Aus dieser Grundfigur folgt alles Weitere, und zwar zwingend:',
  '',
  '**Erstens: Jede Krankheit hat ihre eigene Ursache.** Nicht „Fieber"',
  'als Zustand, sondern dieser eine Erreger, der genau dieses eine',
  'Krankheitsbild macht. Das ist der Grund, warum die moderne Medizin',
  'so besessen von Diagnosen ist: Wer die Ursache nicht benennt, kann',
  'sie nicht angreifen.',
  '',
  '**Zweitens: Die Ursache findet man, bevor man heilt.** Das ist die',
  'Umkehrung der ganzen bisherigen Heilkunde, und sie ist unbequem: Sie',
  'verlangt Jahre Arbeit, in denen niemandem geholfen wird. Wir haben',
  'sechs Jahre an Seidenraupen gearbeitet, bevor ein einziger Mensch',
  'etwas davon hatte. **Wer die Ursache kennt, kann sie an der Wurzel',
  'abschneiden — wer nur Beschwerden lindert, muss ewig lindern.**',
  '',
  '**Drittens: Der Versuch ist der Richter, nicht die Erfahrung und',
  'nicht die Autorität.** Nicht was Liebig sagt, nicht was seit',
  'Jahrhunderten gilt, nicht was der erfahrene Praktiker im Gefühl hat:',
  'Der Kolben entscheidet. Man baut zwei Anordnungen, die sich in genau',
  'einem Punkt unterscheiden, und lässt sie antworten. **Der Zufall',
  'begünstigt nur den vorbereiteten Geist** — dieser Satz, gesprochen',
  '1854 in Lille, ist kein Trost für Glückspilze, sondern eine',
  'Arbeitsanweisung: Bereite die Anordnung so vor, dass der Zufall dir',
  'etwas sagen kann.',
  '',
  '**Viertens: Was man ursächlich versteht, kann man verhindern.** Und',
  'das ist die eigentliche Beute. Nicht die Behandlung — die',
  '**Vorbeugung**. Filtern, erhitzen, fernhalten, abtöten, impfen.',
  '',
  'Diese Denkart hat der Medizin ihre größten Siege gebracht, und sie',
  'hat sie an einer Stelle blind gemacht, die wir selbst benennen, bevor',
  'es andere tun. **Wir erklären den Erreger. Wir erklären nicht, warum',
  'von zehn Menschen, die denselben Keim einatmen, drei krank werden und',
  'sieben nicht.** Für die alte Denkart war genau das die Hauptfrage:',
  'der Zustand des Menschen, in den der Keim gerät. Unser Zeitgenosse',
  'Claude Bernard hat darauf beharrt, und der Chemiker Antoine Béchamp',
  'hat uns dieselbe Frage feindselig entgegengehalten.',
  '',
  '(Es kursiert dazu ein Satz, den Pasteur auf dem Sterbebett gesagt',
  'haben soll: der Keim sei nichts, das Milieu alles. **Dieser Satz ist',
  'nicht belegt** — er taucht in keiner zeitgenössischen Quelle auf. Wir',
  'nennen ihn hier, weil er oft zitiert wird, und wir kennzeichnen ihn',
  'als das, was er ist: unbestätigt. Die Frage dahinter ist trotzdem',
  'berechtigt.)',
  '',
  '## Das fünfte Präparat: das Blut eines verendeten Schafes',
  '',
  'Ab 1877 lag anderes unter der Linse: ein Tropfen Blut aus einem Schaf,',
  'das am **Milzbrand** verendet war. Darin, in großer Zahl, lange',
  'unbewegliche Stäbchen.',
  '',
  'Und hier ist Ehrlichkeit Nummer zwei fällig: **Wir waren nicht die',
  'Ersten.** Ein deutscher Landarzt namens Robert Koch hatte 1876 den',
  'ganzen Lebenslauf dieses Erregers aufgeklärt, einschließlich der',
  'Dauerformen, die im Boden jahrzehntelang überleben. Das erklärte, was',
  'die Bauern die „verfluchten Äcker" nannten: Flächen, auf denen das',
  'Vieh immer wieder erkrankte. Wir haben gezeigt, wie die Sporen aus',
  'der Tiefe wieder an die Oberfläche kommen — Regenwürmer bringen sie',
  'herauf, wenn verendete Tiere verscharrt worden sind.',
  '',
  'Zwischen Koch und uns stand von Anfang an mehr als eine Sachfrage.',
  'Frankreich hatte 1871 einen Krieg gegen Deutschland verloren, und wir',
  'haben, das ist aktenkundig, unseren Anteil an der Gehässigkeit',
  'gehabt. **Der Streit zweier Nationen um die Ehre einer Entdeckung hat',
  'die Sache jahrelang aufgehalten**, und beide Seiten haben Zeit damit',
  'verbracht, einander Fehler nachzuweisen, statt zu arbeiten. Für die',
  'Ehrenrettung sei gesagt: Es kam trotzdem etwas dabei heraus. Die',
  'Härte der Prüfung durch den Gegner hat beide Schulen besser gemacht.',
  '',
  'Der eigentliche Fund kam dann aus einer Nachlässigkeit. Im Sommer',
  '1879 blieb eine Kultur des Erregers der **Hühnercholera** über die',
  'Ferien im Schrank stehen. Als man sie im Herbst den Hühnern gab,',
  'wurden diese nur leicht krank und erholten sich. Man hätte die alte',
  'Kultur wegwerfen können. Wir haben dieselben Tiere später mit',
  'frischer, voller Kultur nachgeimpft — und sie blieben gesund,',
  'während die übrigen Hühner starben.',
  '',
  '**Warum abschwächen statt abtöten?** Weil ein abgeschwächter Erreger',
  'noch lebt und sich noch — schwach — vermehrt. Er stellt dem Körper',
  'eine Aufgabe, die dieser bewältigen kann, aber er stellt sie',
  'wirklich. Der Körper lernt an einem Gegner, der ihn nicht umbringt.',
  '**Das ist genau Jenners Gedanke aus dem vorigen Kapitel — mit einem',
  'entscheidenden Unterschied: Jenner musste warten, bis die Natur ihm',
  'eine milde Verwandte schenkte, die Kuhpocken. Wir konnten uns die',
  'milde Form nun selbst herstellen.** Aus einem Glücksfall wurde ein',
  'Verfahren; aus einer Impfung wurden viele. Den Namen haben wir',
  'ausdrücklich zu Jenners Ehren beibehalten: Vakzine, von der Kuh.',
  '',
  '## Der Versuch von Pouilly-le-Fort, 5. Mai bis 2. Juni 1881',
  '',
  'Behauptungen kosten nichts. Also stellten wir uns der Probe — und',
  'zwar öffentlich, in aller Form, auf einem Gutshof bei Melun.',
  '',
  'Angesetzt hatte sie ein Tierarzt namens Hippolyte Rossignol, der uns',
  'für Aufschneider hielt und die Bedingungen deshalb hart wählte:',
  'sechzig Tiere, Schafe, dazu Ziegen und Rinder. Die eine Hälfte wurde',
  'am 5. und am 17. Mai geimpft, die andere nicht. Am 31. Mai bekamen',
  '**alle** Tiere eine kräftige Dosis lebender Milzbranderreger. Presse,',
  'Landwirte und Politiker wurden für den 2. Juni eingeladen.',
  '',
  'Am 2. Juni standen die geimpften Tiere auf der Weide und fraßen. Die',
  'ungeimpften waren tot oder lagen im Sterben. Die Nachricht ging in',
  'wenigen Tagen um die Welt; innerhalb eines Jahres wurden in',
  'Frankreich Hunderttausende Schafe geimpft. **Es war der',
  'überzeugendste öffentliche Versuch, den die Medizin bis dahin gesehen',
  'hatte.**',
  '',
  'Und nun das, was hundert Jahre lang nicht dazuerzählt wurde.',
  '',
  '**Der Versuch war inszeniert.** Nicht das Ergebnis — das war echt und',
  'ist hundertfach bestätigt worden. Aber die Art, wie er zustande kam.',
  'Öffentlich hatten wir angekündigt, mit einem Impfstoff zu arbeiten,',
  'der durch Luftsauerstoff abgeschwächt wird — unser eigenes Verfahren,',
  'auf das wir stolz waren. Verwendet wurde in Pouilly-le-Fort ein',
  'anderer: ein mit Kaliumdichromat behandelter Impfstoff aus der Hand',
  'von Chamberland und Roux, der zu diesem Zeitpunkt verlässlicher war.',
  '',
  'Das steht so in den Laborheften. Der Wissenschaftshistoriker **Gerald',
  'Geison** hat sie 1995 ausgewertet und veröffentlicht, nachdem die',
  'Familie sie freigegeben hatte. **Wir haben also vor aller Welt einen',
  'Versuch gewonnen und dabei über einen wesentlichen Punkt nicht die',
  'Wahrheit gesagt.** Das lässt sich nicht schönreden, und wir versuchen',
  'es nicht. Wer heute darüber spottet, dass Studien geschönt werden',
  'und Ergebnisse besser klingen als ihre Grundlage, findet in diesem',
  'Juni 1881 einen frühen Fall — nicht bei einem Betrüger, sondern bei',
  'einem Mann, der recht hatte und trotzdem nachhalf.',
  '',
  '## Das sechste Präparat: das Rückenmark eines Kaninchens',
  '',
  'Das letzte Präparat ist das seltsamste, denn unter der Linse war',
  'nichts zu sehen.',
  '',
  'Die **Tollwut** ist eine Krankheit, vor der man sich im 19.',
  'Jahrhundert fürchtete wie vor nichts sonst — nicht wegen der Zahl der',
  'Toten (sie war klein), sondern wegen der Art des Sterbens: Wochen',
  'nach einem Biss beginnen Angst, Krämpfe, Wasserscheu, Lähmung. Wer',
  'erkrankte, starb, ausnahmslos.',
  '',
  'Wir suchten den Erreger und fanden ihn nicht. Kein Stäbchen, keine',
  'Kugel, nichts. Heute weiß man, warum: Es ist ein Virus, viel zu klein',
  'für die Linsen jener Zeit. **Wir haben also mit etwas gearbeitet, das',
  'wir nie zu Gesicht bekommen haben** — wir wussten nur, wo es sitzt:',
  'im Nervengewebe, im Rückenmark, im Gehirn.',
  '',
  'Das Verfahren, das Roux und wir entwickelten, war entsprechend grob:',
  'Man entnimmt infizierten Kaninchen das Rückenmark und hängt es in',
  'einen Kolben über Ätzkali, wo es langsam trocknet. Mit jedem Tag',
  'Trocknung verliert es an Kraft. Vierzehn Tage getrocknet: fast',
  'harmlos. Frisch: tödlich. **Man impft mit dem ältesten, schwächsten',
  'Material und arbeitet sich Tag für Tag zum frischeren vor.** An',
  'Hunden — etwa fünfzig — hat das gehalten: Behandelte Tiere erkrankten',
  'nicht, auch wenn man sie danach infizierte.',
  '',
  'Und hier kommt der Umstand, der aus der Tollwut den Grenzfall dieses',
  'Kapitels macht. **Die Tollwut ist die einzige Krankheit, bei der man',
  'nach der Ansteckung noch impfen kann**, weil das Virus wochenlang',
  'langsam die Nerven entlangwandert, bevor es das Gehirn erreicht. Der',
  'Impfstoff läuft ihm auf dem Blutweg voraus. Das heißt aber auch: Man',
  'behandelt einen Menschen, der noch nicht krank ist und vielleicht nie',
  'krank geworden wäre — nicht jeder Gebissene erkrankt.',
  '',
  '## Der 6. Juli 1885: ein Junge aus dem Elsass',
  '',
  'An diesem Montagmorgen stand eine Frau im Labor, die zwei Tage und',
  'vierhundert Kilometer gereist war. Bei ihr ein Junge von neun Jahren,',
  '**Joseph Meister** aus Meissengott im Elsass. Am 4. Juli hatte ihn',
  'ein tollwütiger Hund auf dem Schulweg zu Boden geworfen und vierzehn',
  'Mal gebissen, an Händen, Beinen und Oberschenkeln, tief. Ein Arzt',
  'hatte die Wunden mit Karbolsäure ausgebrannt und der Mutter gesagt,',
  'in Paris gebe es einen, der an Hunden etwas versuche.',
  '',
  'Was dann geschah, gehört zu den bekanntesten Stunden der',
  'Medizingeschichte, und wir erzählen sie so genau wie möglich, weil',
  'die Einzelheiten hier alles sind.',
  '',
  'Pasteur schickte nach zwei Ärzten: **Alfred Vulpian** und',
  '**Jacques-Joseph Grancher**. Sie sahen den Jungen an und hielten die',
  'Lage für aussichtslos genug, um den Versuch zu rechtfertigen. Am',
  'Abend des 6. Juli begann die Behandlung: dreizehn Einspritzungen in',
  'zehn Tagen, beginnend mit fünfzehn Tage getrocknetem Mark, endend mit',
  'frischem, voll wirksamem. **Die Spritzen setzte Grancher, nicht',
  'Pasteur. Denn Pasteur durfte nicht: Ich bin Chemiker, kein Arzt** —',
  'ohne ärztliche Zulassung wäre jede eigene Einspritzung strafbar',
  'gewesen.',
  '',
  'Der Junge blieb gesund. Drei Monate später wurde ein zweiter',
  'behandelt: **Jean-Baptiste Jupille**, ein vierzehnjähriger',
  'Schäferjunge aus dem Jura, der einen tollwütigen Hund mit bloßen',
  'Händen von jüngeren Kindern weggerissen hatte. Auch er überlebte.',
  'Innerhalb eines Jahres kamen über zweitausend Gebissene nach Paris,',
  'aus Russland, aus Amerika, aus aller Welt.',
  '',
  '## Was dieser Versuch war — und was er nicht war',
  '',
  'Jetzt legen wir unsere eigene Handlung unter die Linse. Sie hält dem',
  'nicht in allen Teilen stand.',
  '',
  '**Erstens: Es gab keine Prüfung am Menschen vor diesem Menschen.** Das',
  'Verfahren war an Hunden erprobt, nicht an Personen. Am Abend des',
  '6. Juli 1885 wurde einem neunjährigen Kind ein Mittel gespritzt, von',
  'dem niemand wusste, wie ein menschlicher Körper darauf antwortet —',
  'und dessen letzte Gaben ausdrücklich **voll ansteckendes Material**',
  'enthielten. Wäre die Behandlung fehlgeschlagen, hätte man nie sagen',
  'können, ob der Hund oder die Spritze den Jungen getötet hat.',
  '',
  '**Zweitens: Die Einwilligung war keine im heutigen Sinn.** Eine',
  'verzweifelte Mutter, die vierhundert Kilometer gereist ist, weil ihr',
  'gesagt wurde, dies sei die einzige Hoffnung, entscheidet nicht frei.',
  'Aufklärungsbogen, Bedenkzeit, ein unabhängiges Gremium, das den',
  'Versuch vorher prüft: nichts davon gab es. Das ist keine Anklage',
  'gegen die Zeit — es gab diese Einrichtungen nirgends. Es ist eine',
  'Feststellung darüber, worauf unser Ruhm gebaut ist.',
  '',
  '**Drittens: Wir haben nicht alles erzählt.** Aus den Laborheften, die',
  'Geison ausgewertet hat, geht hervor, dass Pasteur schon vor Joseph',
  'Meister zwei Menschen mit Tollwutmaterial behandelt hatte, ohne',
  'darüber öffentlich zu sprechen; einer der beiden Fälle endete',
  'tödlich. **Meister war in unserer Darstellung der erste Mensch. In',
  'den Heften war er es nicht.**',
  '',
  '**Viertens: Der Erfolg beweist weniger, als er scheint.** Von hundert',
  'Menschen, die ein tollwütiges Tier beißt, erkranken nicht hundert. Ob',
  'Joseph Meister ohne Behandlung erkrankt wäre, weiß niemand. Erst die',
  'vielen tausend Behandelten der folgenden Jahre und der Vergleich mit',
  'Unbehandelten haben gezeigt, dass das Verfahren wirkt — **der',
  'Einzelfall, aus dem die Legende gemacht wurde, konnte das nie',
  'zeigen.**',
  '',
  'Und was zu unseren Gunsten spricht, sagen wir auch, damit Du beides',
  'abwägen kannst. Die Alternative war nicht Vorsicht gegen Wagemut. Die',
  'Alternative war ein Kind mit vierzehn tiefen Bissen gegen eine',
  'Krankheit, die damals **jeden** tötete, der sie bekam. Wir haben zwei',
  'Ärzte hinzugezogen, statt allein zu handeln. Wir haben den Jungen',
  'nicht aus den Augen verloren: Joseph Meister hat später am Institut',
  'gearbeitet, als Pförtner. **Es ist gut ausgegangen. Das macht es',
  'nicht zu einem zulässigen Versuch — es macht es zu einem Wagnis, das',
  'gut ausgegangen ist.** Diese beiden Sätze muss man nebeneinander',
  'aushalten können.',
  '',
  '(Über Meisters Tod im Juni 1940 kursiert eine dramatische',
  'Erzählung. Belegt ist: Er starb am 24. Juni 1940, kurz nach dem',
  'Einmarsch der deutschen Truppen in Paris, von eigener Hand. Die',
  'verbreitete Begründung dafür ist **nicht bestätigt**, und wir geben',
  'sie deshalb nicht wieder.)',
  '',
  '## Das Haus, das aus Spenden gebaut wurde',
  '',
  'Nach der Tollwut kam das Geld — und zwar von unten. Für ein Institut,',
  'in dem Gebissene behandelt und Erreger erforscht werden sollten, kam',
  'eine öffentliche Sammlung zusammen: aus Frankreich, aus Russland, aus',
  'Brasilien, vom Sultan des Osmanischen Reiches, von Schulklassen und',
  'Arbeitervereinen. Am 14. November 1888 wurde das **Institut Pasteur**',
  'in Paris eröffnet.',
  '',
  'Es war von Anfang an anders gedacht als eine Universität: ein Haus,',
  'in dem geforscht, behandelt und unterrichtet wird, und in dem die',
  'Mitarbeiter bleiben dürfen. Aus diesem Haus kamen in den folgenden',
  'Jahrzehnten das Serum gegen die Diphtherie (Roux), die Entdeckung des',
  'Pesterregers (Yersin), der Impfstoff gegen die Tuberkulose (Calmette',
  'und Guérin) und die Arbeiten Metschnikows über die Fresszellen — die',
  'ersten Antworten auf die Frage, **warum** eine Impfung überhaupt',
  'schützt. Diese Frage konnten wir selbst nicht beantworten.',
  '',
  'Pasteur starb am 28. September 1895. Er liegt in einer Gruft in',
  'diesem Haus, keine hundert Schritte von den Laboren entfernt.',
  '',
  '## Die Bilanz unter der Linse',
  '',
  'Ziehen wir Bilanz, in beide Richtungen — so ehrlich, wie wir es bei',
  'einem Präparat täten.',
  '',
  '**Was Bestand hat.** Die Keimtheorie ist die folgenreichste einzelne',
  'Einsicht der Medizingeschichte. Auf ihr stehen die Hygiene, die',
  'Antiseptik und die Asepsis der Chirurgie, die Sterilisation von',
  'Instrumenten, die Trinkwasseraufbereitung, die Lebensmittelkontrolle,',
  'die gesamte Impfstoffentwicklung und, ein halbes Jahrhundert später,',
  'die Antibiotika. Die Widerlegung der Urzeugung hält bis heute; die',
  'Schwanenhalskolben sind ein Versuch, den man in jeder Schule',
  'nachbauen kann. Das Pasteurisieren hat unzählige Leben gerettet —',
  'nicht durch Behandlung, sondern indem Milch aufhörte, Tuberkulose zu',
  'übertragen. Die Impfstoffe gegen Milzbrand und Tollwut waren die',
  'ersten, die im Labor **gemacht** wurden statt in der Natur gefunden.',
  '',
  '**Wo unsere Grenzen liegen.** Wir waren Chemiker, keine Ärzte. Wir',
  'haben die Medizin verwandelt, ohne je ein Rezept geschrieben zu',
  'haben, und wir haben deshalb manches unterschätzt, was am Krankenbett',
  'zählt. Wir haben in Pouilly-le-Fort nachgeholfen und darüber',
  'geschwiegen. Wir haben ein Kind behandelt mit einem Mittel, das nie',
  'zuvor an einem Menschen geprüft worden war, und den Weg dorthin',
  'geglättet. Wir haben einen Streit mit dem Redner gewonnen und nicht',
  'nur mit dem Kolben. Und wir haben uns feiern lassen — den Zug der',
  'Ehrungen, das Jubiläum in der Sorbonne, das Denkmal zu Lebzeiten.',
  '**Ein Mann, der recht hat, kann trotzdem eitel sein, und wir sind',
  'nicht bereit, das eine gegen das andere aufzurechnen.**',
  '',
  '**Was offen bleibt.** Unsere Denkart erklärt den Erreger und nicht',
  'den Menschen. Sie sagt, warum eine Wunde eitert, aber nicht, warum',
  'derselbe Keim den einen umbringt und den anderen nicht anrührt. Sie',
  'taugt hervorragend für Krankheiten, die von außen kommen — und',
  'schlecht für die, mit denen die Medizin heute am meisten zu tun hat:',
  'Krebs, Diabetes, Rheuma, Erschöpfung. **Wir haben der Medizin ein',
  'Werkzeug gegeben, das für eine Sorte von Krankheit gemacht ist, und',
  'sie hat lange versucht, damit auch alle anderen zu bearbeiten.** Dass',
  'die Forschung heute wieder danach fragt, was den Boden ausmacht, in',
  'den ein Keim fällt — die Bakterien im Darm, die Abwehrlage, die',
  'Lebensumstände —, ist keine Widerlegung unserer Arbeit. Es ist die',
  'Rückkehr einer Frage, die wir beiseitegeschoben haben, weil wir sie',
  'nicht messen konnten.',
  '',
  '## Das Präparat, das wir nicht auf den Objektträger legen konnten',
  '',
  'Bleibt das eine, das wir Dir schuldig geblieben sind.',
  '',
  'In Kapitel 9 dieses Buches steht ein Arzt in Wien, der zählt, was',
  'niemand zählen will: **Ignaz Semmelweis**, dessen Wöchnerinnen',
  'starben, wenn Ärzte sie untersuchten, und lebten, wenn Hebammen es',
  'taten. Er fand die Maßnahme — Hände waschen mit Chlorkalk — und',
  'behielt recht, und er konnte trotzdem niemanden überzeugen. **Denn er',
  'konnte nicht sagen, WAS an den Händen klebt.** Er nannte es',
  '„zersetzte organische Teilchen". Das ist keine Ursache, das ist eine',
  'Vermutung mit vornehmen Worten.',
  '',
  'Was wir in diesem Kapitel gefunden haben, ist genau die Antwort auf',
  'seine Frage. Es klebt etwas Lebendiges an diesen Händen. Es hat einen',
  'Namen, es vermehrt sich, es lässt sich abtöten. **Semmelweis hatte',
  'die Maßnahme ohne die Erklärung. Wir hatten die Erklärung ohne den',
  'Kranken.**',
  '',
  'Zusammengesetzt hat beides ein anderer, und er ist die zweite Stimme',
  'dieses Kapitels. **Sie gehört dem Chirurgen Joseph Lister in',
  'Glasgow** — dem Mann, der unsere Aufsätze über die Gärung las und die',
  'einzige Folgerung zog, die ein Chirurg daraus ziehen kann: Wenn',
  'Wunden nicht von selbst faulen, sondern von etwas, das hineinfällt,',
  'dann muss man dieses Etwas töten, bevor es die Wunde erreicht. Er hat',
  'es mit Karbolsäure getan, ab 1865, gegen den Spott seiner Kollegen,',
  'und er hat die Zahlen vorgelegt: die Sterblichkeit nach Amputationen',
  'von rund fünfundvierzig auf rund fünfzehn von hundert.',
  '',
  'Er wird Dir auch erzählen, was uns nicht gelungen ist. Dass seine',
  'Methode umständlich war und die Säure die Wunden reizte. Dass es',
  'dreißig Jahre und einen Krieg brauchte, bis London glaubte, was',
  'Glasgow gezeigt hatte. Und dass am Ende nicht seine Antiseptik',
  'gewonnen hat, sondern die Asepsis der deutschen Schule: nicht Keime',
  'in der Wunde töten, sondern sie gar nicht erst hineinlassen.',
  '',
  '**Das eigentliche Ereignis dieses Kapitels ist deshalb keine',
  'Entdeckung, sondern eine Verbindung:** ein Chemiker, der die Ursache',
  'fand, und ein Chirurg, der aus einer Ursache eine Handlung machte.',
  'Getroffen haben sich die beiden erst spät — 1892, bei einem Fest in',
  'der Sorbonne, wo ein alter, halbseitig gelähmter Mann einem alten',
  'Chirurgen aus Schottland entgegenging. **Was zwischen ihnen lag,',
  'waren nicht Gespräche. Es waren gelesene Aufsätze.**',
  '',
  'Leg jetzt die zweite Stimme unter die Linse.',
].join('\n');

/**
 * Lister — die Klinik. Das Präparat, das nicht auf den Objektträger
 * passte: der Kranke. Der Chirurg in Glasgow, der Pasteurs Aufsatz las,
 * die Karbolsäure einführte und die Sterblichkeit nach Amputationen von
 * fast der Hälfte auf ein Sechstel senkte.
 *
 * Verfasst von DeepSeek (Runde 12, zweiter Pass). Auch diese Stimme benennt
 * die unbequemen Stellen der eigenen Seite selbst (Zusatzregel für
 * sensible Themen).
 */
const stimmeDesLister = [
  '## Das Präparat, das nicht auf den Objektträger passte',
  '',
  'Das Labor hat seine Präparate auf den Tisch gelegt — Rübensaft,',
  'Staub, Flaschenhals, Seidenraupe, Schafblut, Rückenmark. Nun legt',
  'die Klinik das ihre daneben, und es ist das einzige, das nicht unter',
  'ein Glas passt: der Kranke. Er atmet, er stöhnt, er fiebert, er',
  'stirbt — und genau das ist das Präparat, um das es der Medizin',
  'geht. Ohne ihn wäre das Labor eine Sammlung hübscher Bilder. Mit',
  'ihm wird es zur Frage: Was rettet diesen Menschen?',
  '',
  '## Das erste Präparat aus Glasgow: die Zahlen',
  '',
  'Glasgow, 1860er Jahre. Ich bin Chirurg an der Royal Infirmary und',
  'kenne die Zahlen, die niemand gern ausspricht: Von den Menschen,',
  'denen ich ein Bein amputiere, stirbt fast die Hälfte. Nicht an',
  'meinem Messer — die Amputation selbst gelingt. Sie sterben in den',
  'Tagen danach: die Wunde eitert, der Leib schwillt, das Fieber',
  'steigt, und nichts hilft. Wir Chirurgen haben das so sehr',
  'gewöhnt, dass wir es „das Wundfieber" nennen, als wäre es ein',
  'Schicksal wie das Wetter. Wir wechseln die Verbände, ohne uns die',
  'Hände zu waschen; wir nähen mit demselben Faden, mit dem wir',
  'gestern einen Abszess geöffnet haben; wir operieren in denselben',
  'Röcken, die von Blut und Eiter steif sind. Und wir fragen nicht,',
  'warum. Man fragt nicht nach dem Wetter.',
  '',
  '## Das zweite Präparat: ein Aufsatz aus Frankreich',
  '',
  'Dann, 1865, fällt mir ein Aufsatz in die Hände — von einem',
  'Chemiker in Paris, der sich mit Wein und Seidenraupen beschäftigt.',
  'Louis Pasteur hat gezeigt, dass die Zersetzung von Lebewesen',
  'verursacht wird: unsichtbare Keime, die überall sind, in der Luft,',
  'im Staub, auf den Händen. Die Fäulnis einer Wunde, so dachte ich,',
  'ist doch genau das: Zersetzung. Wenn die Keime die Gärung des',
  'Weins machen, machen sie vielleicht auch die Gärung der Wunde —',
  'das Eiterfieber. Und wenn sie von außen kommen, kann man sie',
  'draußen halten — oder töten, bevor sie eindringen.',
  '',
  'Das war der Augenblick, in dem das Labor und die Klinik sich zum',
  'ersten Mal berührten. Pasteur hatte die Ursache gefunden, ohne je',
  'einen Kranken zu sehen. Ich sah die Kranken, ohne die Ursache zu',
  'kennen. Zusammen waren wir vollständig.',
  '',
  '## Das dritte Präparat: die Karbolsäure',
  '',
  'Ich suchte ein Mittel, das die Keime tötet, ohne den Kranken zu',
  'töten. Die Wahl fiel auf Karbolsäure — ein Teerprodukt, das man',
  'damals benutzte, um Abwasser zu reinigen. Ich ließ die Instrumente',
  'darin waschen, die Hände, die Wunde, den Verband. Die Kollegen',
  'spotteten über den Geruch, der durch die Station zog; ich roch',
  'ihn gern, denn er roch nach Leben. Die Zahlen änderten sich: In',
  'meiner Abteilung starben nach der Amputation statt fast der',
  'Hälfte nur noch etwa einer von sechs. Ich veröffentlichte die',
  'Fälle, einen nach dem anderen, mit allen Zahlen — und die Welt',
  'sah zu, wie die Sterblichkeit fiel.',
  '',
  '## Das vierte Präparat: der Spott',
  '',
  'Die Welt sah zu — und lachte. Die Antiseptik wurde in England',
  'Jahre lang belächelt: zu umständlich, zu teuer, zu sehr der',
  'Geruch von Abwasser. Manche Kollegen versuchten es halbherzig,',
  'ließen die Verbände aus, wuschen die Wunde nur einmal — und wenn',
  'es dann nicht wirkte, war die Methode schuld. In Deutschland',
  'hörte man besser zu; dort baute die Chirurgie auf meiner Arbeit',
  'auf. Ich habe nie gestritten, wie Pasteur gestritten hat. Ich habe',
  'Zahlen geliefert und gewartet. Die Zahlen haben gewonnen —',
  'langsamer, als ich es mir gewünscht hätte, aber sie haben gewonnen.',
  '',
  '## Wo diese Stimme selbst scheitert',
  '',
  'Jetzt die unbequemen Stellen, denn auch die Klinik hat ihre Rechnung.',
  '',
  '**Erstens: Die Karbolsäure war nicht die letzte Antwort.** Sie',
  'tötete Keime — und sie reizte die Wunden, schwächte die',
  'Abwehr, verätzte die Hände der Operateure. Als Robert Koch und',
  'seine Schüler zeigten, dass man die Keime nicht töten, sondern',
  'fernhalten kann — die Asepsis: alles steril, nichts dringt ein —,',
  'war das die bessere Methode. Ich habe mich lange gegen die',
  'Asepsis gesträubt, weil ich meine Antiseptik verteidigte. Auch das',
  'gehört zur Wahrheit: Der Mann, der die Sterilität lehrte, hing an',
  'seinem Desinfektionsmittel, als die Zukunft schon anders hieß.',
  '',
  '**Zweitens: Ich habe die Priorität nie ganz geklärt.** Andere',
  'Chirurgen hatten vor mir Ähnliches versucht — Semmelweis in Wien,',
  'den man ausgelacht hat, bevor ich geboren wurde. Ich habe seinen',
  'Namen erst spät genannt. Die Wahrheit ist: Ich hatte den Vorteil,',
  'Pasteurs Aufsatz zu lesen; er hatte nur die eigene Beobachtung.',
  'Der Ruhm ging an mich, weil ich den Beweis hatte. Das ist nicht',
  'immer gerecht.',
  '',
  '**Drittens: Ich war ein Chirurg, kein Revolutionär.** Ich habe',
  'die Wundinfektion besiegt, aber ich habe die Krankenhäuser nicht',
  'verändert — die Hygiene, die Lüftung, die Ausbildung der',
  'Schwestern kamen erst nach mir. Wer nur die Wunde reinigt, aber',
  'das Haus schmutzig lässt, hat die halbe Arbeit getan.',
  '',
  '## Antwort an das Labor',
  '',
  'Das Labor hat am Ende gefragt, was mit seiner Entdeckung geschah,',
  'als sie die Klinik erreichte. Die Antwort dieser Stimme: Sie wurde',
  'auf die Probe gestellt — an Menschen, die nicht gefragt haben, ob',
  'sie Versuchspersonen sein wollen, weil sie keine Wahl hatten. Die',
  'Keimtheorie hat die Chirurgie verwandelt: aus dem Handwerk des',
  'Schneidens wurde eine Wissenschaft der Rettung. Die Zahlen, die',
  'wir seither erreichen, wären ohne die Linse des Pasteur nicht',
  'denkbar — und die Linse wäre ohne den Kranken nur ein Spielzeug.',
  'Das Labor findet die Wahrheit. Die Klinik rettet den Menschen.',
  'Erst beide zusammen sind die Medizin, die dieses Kapitel feiern',
  'kann — und die Frage, ob sie auch die Armen rettet, die auf den',
  'Tischen lagen, bleibt offen für die Kapitel, die kommen.',
].join('\n');

/** Kapitel 11 der Themenlandkarte. */
const pasteurLister = {
  id: 'pasteur-lister',
  titel: 'Pasteur und Lister',
  epoche: '~1860–1880',

  aufhaenger: {
    frage:
      'Was haben Weinflecken, Seidenraupen und ein gebissener Junge mit ' +
      'der größten Wende der Medizin zu tun?',
    text: [
      'Alles. Ein Chemiker in Frankreich soll herausfinden, warum Wein sauer',
      'wird, Bier verdirbt und Seidenraupen sterben. Er findet überall',
      'dasselbe: winzige Lebewesen, die etwas zersetzen. Und er zieht daraus',
      'den Schluss, der die Medizin verwandeln wird — was die Gärung für den',
      'Wein ist, ist die Krankheit für den Menschen.',
      '',
      'Ein Chirurg in Glasgow liest seine Aufsätze und begreift, was das für',
      'seinen Operationstisch bedeutet: Wenn Wunden nicht von selbst faulen,',
      'sondern von etwas, das aus der Luft hineinfällt, dann muss man dieses',
      'Etwas töten. Ab 1865 wäscht er Wunden und Instrumente mit Karbolsäure.',
      'Innerhalb weniger Jahre sinkt in seinen Abteilungen die Sterblichkeit',
      'nach Amputationen von fast der Hälfte auf etwa ein Sechstel.',
      '',
      'Damit ist die Frage beantwortet, die Ignaz Semmelweis zwanzig Jahre',
      'zuvor gestellt und nicht hatte erklären können: Was klebt an den',
      'Händen der Ärzte? Die Medizin hat die Ursache der Wundinfektion',
      'gefunden — und mit ihr eine neue Denkart. Krankheit ist von nun an',
      'nicht mehr ein gestörtes Gleichgewicht, sondern ein Eindringling mit',
      'Namen und Gestalt.',
      '',
      'Dieses Kapitel erzählt beides: den Triumph — und was er gekostet hat.',
      'Den öffentlichen Versuch von 1881, der sorgfältiger inszeniert war,',
      'als es hieß. Die erste Tollwut-Impfung 1885 an einem neunjährigen',
      'Kind, mit einem Mittel, das nie zuvor an einem Menschen geprüft worden',
      'war. Und die Grenze einer Denkart, die den Erreger erklärt, aber nicht',
      'den Menschen, in den er gerät.',
    ].join('\n'),
  },

  karte,

  perspektiven: [
    {
      id: 'pasteur',
      name: 'Die Stimme des Labors',
      stimme: 'Opus',
      text: stimmeDesLabors,
    },
    {
      id: 'lister',
      name: 'Die Stimme der Klinik',
      stimme: 'DeepSeek',
      text: stimmeDesLister,
    },
  ],

  synthese: [
    '## Wo sich beide Stimmen treffen',
    '',
    'Zuerst das Gemeinsame — und es ist der Kern dieses Kapitels: Das',
    'Labor und die Klinik brauchten einander, auch wenn sie sich nie',
    'begegnet sind. Pasteur fand die Ursache, ohne einen Kranken zu',
    'sehen; Lister sah die Kranken, ohne die Ursache zu kennen. Beide',
    'stellen die Beobachtung über die Meinung: Pasteur vertraut dem',
    'Experiment, Lister den Zahlen. Beide benennen dieselben',
    'unbequemen Wahrheiten — der eine die Inszenierung von',
    'Pouilly-le-Fort und die Tollwut-Impfung am Kind, der andere den',
    'eigenen Widerstand gegen die Asepsis und das späte Eingeständnis',
    'gegenüber Semmelweis. Und beide wissen: Die Wende, die sie',
    'gemeinsam bewirkt haben, steht auf den Schultern derer, die vor',
    'ihnen ausgelacht wurden.',
    '',
    '## Wo sie auseinandergehen',
    '',
    'Der Widerspruch beginnt bei der Frage, was die Medizin ist. Für',
    'das Labor ist sie eine Wissenschaft: eine Frage, ein Experiment,',
    'ein Beweis — die Wahrheit kommt aus der Linse. Für die Klinik ist',
    'sie eine Kunst am Krankenbett: Die Wahrheit nützt nichts, wenn sie',
    'nicht ankommt, wenn der Verband nicht gewechselt wird, wenn der',
    'Kranke nicht vertraut. Pasteur hätte die Medizin ohne den Kranken',
    'denken können; Lister nicht. Und sie streiten über den Preis: Das',
    'Labor sieht den Fortschritt — die Keimtheorie, die Impfstoffe,',
    'die Rettung von Millionen. Die Klinik sieht auch die Kosten: die',
    'Menschen, die als erste geprüft wurden, ohne zu fragen; die',
    'Armen, die auf den Tischen lagen; die Frage, ob der Fortschritt',
    'allen gehört oder nur denen, die ihn bezahlen können.',
    '',
    '## Was dieses Kapitel für das ganze Buch zeigt',
    '',
    'Zum zwölften Mal dasselbe Muster — und jetzt wird es zur',
    'Klimax: Die Denkart bestimmt die Methode. Mit Pasteur und Lister',
    'endet die lange Herrschaft der Denkarten des Gleichgewichts —',
    'das Lot, die Kanäle, das Qi, die Doshas, die Säfte. An ihre',
    'Stelle tritt die Denkart der Ursache: Die Krankheit hat einen',
    'Erreger, der Erreger hat eine Schwachstelle, und die Medizin',
    'kann ihn finden und treffen. Diese Denkart hat die Welt',
    'verwandelt — und sie hat, wie alle Denkarten dieses Buches,',
    'ihren Preis: Sie sieht den Keim, aber sie sieht den Menschen',
    'leicht aus dem Blick; sie misst den Erfolg an der Zahl, nicht an',
    'der Erfahrung.',
    '',
    'Und dieses Kapitel schließt den Bogen, der mit Semmelweis begann:',
    'Der Mann aus Wien hat die Wahrheit gesehen, ohne sie beweisen zu',
    'können, und ist daran zerbrochen. Pasteur und Lister haben',
    'derselben Wahrheit Namen und Zahlen gegeben — und wurden zu',
    'Helden. Die Medizin, die nun beginnt, ist mächtiger als je',
    'zuvor: Sie kann die Ursache finden, die Wunde rein halten, die',
    'Krankheit vorhersagen. Ob sie mit dieser Macht auch weiser wird,',
    'zeigt sich in den Kapiteln, die jetzt kommen — Röntgen und',
    'Penicillin, die Verstaatlichung, die Pharmaindustrie, und die',
    'Frage, wem die Medizin gehört.',
  ].join('\n'),

  urteil: {
    frage:
      'Würdest du dich einem Mittel anvertrauen, das noch nie an einem ' +
      'Menschen geprüft wurde — wenn die Alternative der sichere Tod wäre? ' +
      'Und würdest du diese Entscheidung auch für dein Kind treffen?',
    hinweis: [
      'Es gibt hier kein Richtig und kein Falsch. Nimm dir die Lage der',
      'Mutter von Joseph Meister vor: vierzehn tiefe Bisse, eine Krankheit,',
      'die damals jeden tötete, und ein Mann in Paris, der es an Hunden',
      'versucht hat. Frag dich zweierlei. Erstens: Was müsstest du wissen,',
      'damit du zustimmst — und wer müsste es dir sagen? Zweitens: Ändert',
      'sich deine Antwort, wenn die Gefahr kleiner ist? Bei sicherem Tod',
      'entscheiden die meisten Menschen anders als bei einem Risiko von eins',
      'zu tausend. Genau dazwischen liegt die Frage, die die Medizin bis',
      'heute jedes Mal neu beantworten muss.',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Womit beschäftigte sich Louis Pasteur, als er auf die Keime ' +
        'stieß?',
      antworten: [
        'Mit Operationen an Verletzten.',
        'Mit der Gärung — verdorbener Wein, saures Bier und kranke ' +
          'Seidenraupen.',
        'Mit der Vermessung von Schädeln.',
      ],
      richtig: 1,
      erklaerung:
        'Pasteur war Chemiker, nicht Arzt. 1856 bat ihn in Lille ein ' +
        'Brennereibesitzer um Hilfe, weil sein Rübenalkohol sauer wurde. ' +
        'Unter dem Mikroskop fand Pasteur in den guten Bottichen ' +
        'Hefekügelchen, in den verdorbenen kleine Stäbchen. Daraus wurde ' +
        'der Gedanke, der die Medizin verwandelte: Was die Gärung für den ' +
        'Wein ist, ist die Krankheit für den Menschen.',
    },
    {
      frage:
        'Was zeigten die berühmten Schwanenhalsflaschen von 1864?',
      antworten: [
        'Dass in einer gekochten Brühe kein Leben von selbst entsteht, ' +
          'solange der Staub der Luft nicht hineinkommt.',
        'Dass Luft die Fäulnis verhindert.',
        'Dass Wein in gebogenen Flaschen länger hält.',
      ],
      richtig: 0,
      erklaerung:
        'Der lange, gebogene Hals ließ Luft herein, hielt aber den Staub in ' +
        'der Biegung zurück: Die gekochte Brühe blieb jahrelang klar. Brach ' +
        'man den Hals ab oder ließ die Brühe die Biegung berühren, trübte ' +
        'sie sich binnen zwei Tagen. Damit war die Lehre von der Urzeugung ' +
        'widerlegt — und das war die Voraussetzung dafür, dass Keime als ' +
        'Ursache von Krankheit gelten konnten und nicht als deren Folge.',
    },
    {
      frage:
        'Was geschah im Mai und Juni 1881 auf dem Gut Pouilly-le-Fort bei ' +
        'Melun?',
      antworten: [
        'Pasteur führte die erste Operation unter Narkose durch.',
        'Ein öffentlicher Versuch: Geimpfte und ungeimpfte Tiere bekamen ' +
          'Milzbranderreger — die geimpften überlebten.',
        'Die französische Regierung verbot die Impfung von Nutztieren.',
      ],
      richtig: 1,
      erklaerung:
        'Der Tierarzt Hippolyte Rossignol, ein Zweifler, setzte den Versuch ' +
        'an: sechzig Tiere, die eine Hälfte geimpft, die andere nicht, dann ' +
        'für alle eine kräftige Dosis Milzbranderreger. Am 2. Juni standen ' +
        'die geimpften Tiere, die ungeimpften waren tot. Der Erfolg war ' +
        'echt — die Laborhefte zeigen aber, dass ein anderer Impfstoff ' +
        'verwendet wurde als der öffentlich angekündigte.',
    },
    {
      frage:
        'Warum setzte nicht Pasteur selbst dem Jungen Joseph Meister 1885 ' +
        'die Spritzen?',
      antworten: [
        'Weil er wegen seines Schlaganfalls die Hand nicht ruhig halten ' +
          'konnte.',
        'Weil er Chemiker war und keine ärztliche Zulassung hatte — die ' +
          'Ärzte Vulpian und Grancher behandelten.',
        'Weil er sich vor einer Ansteckung fürchtete.',
      ],
      richtig: 1,
      erklaerung:
        'Pasteur hat nie Medizin studiert; eigene Einspritzungen wären ' +
        'strafbar gewesen. Er zog die Ärzte Alfred Vulpian und ' +
        'Jacques-Joseph Grancher hinzu, und Grancher gab die dreizehn ' +
        'Injektionen. Der Junge war zwei Tage zuvor vierzehnmal von einem ' +
        'tollwütigen Hund gebissen worden. Das Mittel war an rund fünfzig ' +
        'Hunden erprobt, nie zuvor an einem Menschen.',
    },
    {
      frage:
        'Welche Frage aus einem früheren Kapitel beantwortet die ' +
        'Keimtheorie?',
      antworten: [
        'Warum kreist das Blut im Körper?',
        'Warum starben in Wien mehr Wöchnerinnen bei den Ärzten als bei ' +
          'den Hebammen?',
        'Warum wirkt Chinarinde gegen Malaria?',
      ],
      richtig: 1,
      erklaerung:
        'Ignaz Semmelweis hatte 1847 die Maßnahme gefunden — Hände waschen ' +
        'mit Chlorkalk — und konnte nicht sagen, was an den Händen klebt; ' +
        'er sprach von „zersetzten organischen Teilchen". Die Keimtheorie ' +
        'lieferte die fehlende Ursache: lebende Erreger. Joseph Lister zog ' +
        'daraus ab 1865 in Glasgow die Folgerung für den Operationstisch ' +
        'und senkte die Sterblichkeit nach Amputationen von rund 45 auf ' +
        'rund 15 von hundert.',
    },
  ],
};

module.exports = pasteurLister;
