// Kapitel 14 — „Die moderne Pharmaindustrie".
//
// Das sechste Kapitel der Neuzeit und das erste, in dem nicht ein Forscher,
// nicht ein Gesetz, sondern ein Unternehmen die Hauptrolle spielt. Seit
// 1883 bezahlt eine Kasse die Behandlung (Kapitel 13). Damit gibt es zum
// ersten Mal in der Geschichte der Medizin einen zahlungsfähigen Markt für
// Arznei — und ein Gewerbe, das ihn beliefert. Aus einer Apotheke in
// Darmstadt und zwei Farbenfabriken an Wupper und Main wird binnen
// hundertfünfzig Jahren eine Industrie mit rund anderthalb Billionen Dollar
// Umsatz im Jahr, die Krankheiten beendet hat, an denen unsere Urgroßeltern
// starben — und die daran verdient, dass Menschen krank sind.
//
// Die DENKART-Analyse ist das Herzstück (Betreiber-Vorgabe). Sie fragt
// hier: Warum kostet ein Medikament so viel? (Weil bezahlt wird, was
// gesucht wurde, nicht was hergestellt wird: zehn bis fünfzehn Jahre, drei
// Studienstufen, und von den Kandidaten, die überhaupt bis zur ersten
// Prüfung am Menschen kommen, wird etwa jeder zehnte zugelassen.) Warum
// eine Tablette und nicht ein Rat? (Weil die Denkart der Industrie die
// Krankheit als chemisches Problem sieht — ein Molekül gegen einen Vorgang;
// und weil nur die Tablette sich dosieren, prüfen, patentieren und
// verkaufen lässt.) Warum Dauermedikamente? (Weil chronische Krankheiten
// tägliche Mittel brauchen — und weil ein Mittel, das dreißig Jahre lang
// genommen wird, dreißig Jahre lang bezahlt wird.) Und die Kehrseite jeder
// dieser Begründungen: Geforscht wird, wo gezahlt wird, nicht, wo die Not
// am größten ist.
//
// LÄNGENREGEL (Betreiber-Feedback 24.08.2026): Ab Kapitel 9 gilt die
// Umkehrung — vollständig und ausführlich; für dieses Kapitel ausdrücklich
// (die finanzielle Abhängigkeit der Forschung). Ausführlich heißt nicht
// aufgebläht: jeder Absatz bringt die Erzählung voran. Gemessen wird in
// tests/karte-pharmaindustrie.mjs.
//
// TONE-Regel: BEIDE Seiten fair. Diese erste Stimme zeigt die Leistungen
// der Industrie (Insulin, Sulfonamide, Penicillin, die HIV-Therapie, die
// Krebsmittel, die Impfstoffe) UND benennt die unbequemen Stellen selbst:
// die Frühzeit ohne Prüfung (Cocain als Wundermittel, Heroin als
// Hustenmittel), Contergan, das Marketing, das die Grenze überschritt
// (Vioxx, OxyContin, unterdrückte Studien), die Dauermedikamente als
// Geschäftsmodell und die ehrliche Bilanz: stark in der Diagnose, schwach
// bei den chronischen Krankheiten.
//
// KEINE GERÜCHTE (Betreiber-Entscheid 25.08.2026): Nur Belegtes. Wo Zahlen
// Schätzungen sind (die Zahl der Contergan-Kinder, die Entwicklungskosten
// eines Medikaments), sagt der Text das ausdrücklich und nennt die
// Gegenrechnung.
//
// DER INNOVATIONS-ZYKLUS (Betreiber-Beobachtung 26.08.2026, roter Faden):
// Das Muster des Buches wiederholt sich hier zweimal in Reinform. Das
// Heroin war dreiundzwanzig Jahre lang ein Hustenmittel, ehe es verboten
// wurde. Das Thalidomid hat Tausende Kinder geschädigt — und ist heute ein
// zugelassenes Mittel gegen Lepra-Komplikationen und Knochenmarkkrebs. Die
// Stimme benennt das selbst.
//
// Stimmen (Runde 15): Die ERSTE Perspektive — die Industrie von innen, als
// Beipackzettel ihrer selbst — verfasste Opus. Die ZWEITE (die Kritik: die
// Finanzinteressen, das Geschäft mit der Krankheit, die
// Studienfinanzierung, die unterdrückten Negativ-Ergebnisse, die
// Interessenkonflikte in den Leitlinien, die einfache Medizin ohne Lobby)
// und die finale Synthese ergänzte Hermes im zweiten Pass.
// Perspektiven-Workflow: CLAUDE.md.
//
// KEINE WIEDERHOLUNGEN (Betreiber-Entscheid vom 21.08.2026): Kapitel 1
// gliedert nach „Wer hier spricht", Kapitel 2 beginnt mit einer Szene,
// Kapitel 3 erzählt einen Tageslauf, Kapitel 4 ist ein Briefwechsel,
// Kapitel 5 die Reise eines Buches, Kapitel 6 ein Rundgang, Kapitel 7 ein
// Prozess, Kapitel 8 eine Rechnung, Kapitel 9 eine Uhr, Kapitel 10 eine
// Kette, Kapitel 11 eine Linse, Kapitel 12 ein Interview, Kapitel 13 eine
// Akte. Dieses Kapitel wählt die fünfzehnte Dramaturgie: DER BEIPACKZETTEL.
// Die Industrie spricht in der Form, die sie selbst erfunden hat — in
// Rubriken, klein gedruckt, mit Zusammensetzung, Anwendungsgebieten,
// Dosierung, Wechselwirkungen, Nebenwirkungen und Gegenanzeigen. Die
// zweite Stimme kann in dieselbe Form treten: der andere Beipackzettel,
// derselbe Wirkstoff, von der anderen Seite gelesen.
//
// Die Texte liegen als Zeilen-Arrays mit `.join('\n')` — so bleiben sie im
// Repo bei ~72 Zeichen lesbar (der Betreiber liest sie hier gegen), und
// utils/markdown.js macht in der App wieder fließenden Text daraus.
//
// CommonJS ohne UI-Importe (Architektur-Regel): mit blankem `node` prüfbar.

const { karte } = require('./karten/pharmaindustrie');

/**
 * Die Stimme der Industrie — der Beipackzettel eines Gewerbes.
 *
 * Verfasst von Opus (Runde 15). Eine Stimme, die für die Seite spricht, die
 * die Medikamente macht: ihre Rechnung, ihre Denkart, ihre Erfolge. Sie
 * erzählt, warum sie tut, was sie tut — und sie benennt die unbequemen
 * Stellen selbst (Zusatzregel für sensible Themen in CLAUDE.md).
 */
const stimmeDerIndustrie = [
  '## Die Packung, die vor Dir liegt',
  '',
  'Nimm irgendeine Schachtel aus Deinem Schrank. Zwanzig Tabletten in',
  'einem Blister, ein Pappkarton mit Blindenschrift, ein Zettel, der',
  'achtmal gefaltet ist und den kaum jemand zu Ende liest. Auf diesem',
  'Zettel steht alles, was eine Behörde für nötig hält: was drin ist,',
  'wogegen es hilft, wie viel man nimmt, was schiefgehen kann.',
  '',
  'Dieses Kapitel ist ein solcher Zettel. Nur steht diesmal kein Mittel',
  'darauf, sondern das Gewerbe, das die Mittel macht.',
  '',
  '**Was Du hier liest, ist die Sicht der Industrie auf sich selbst —',
  'eine Denkart, keine Wahrheit.** Ich rede von uns in der Wir-Form,',
  'weil das ehrlicher ist als ein neutraler Ton, den es hier nicht gibt.',
  'Wir sind die Chemiker, die Ärztinnen in den Prüfabteilungen, die',
  'Leute in der Zulassung, im Werk, im Vertrieb, im Vorstand. Wir haben',
  'Krankheiten beendet, an denen Deine Urgroßeltern gestorben sind. Wir',
  'verdienen Geld daran, dass Menschen krank sind. Beides steht in',
  'diesem Beipackzettel, und keines der beiden hebt das andere auf.',
  '',
  'Ein Beipackzettel hat eine Eigenart, die ihn für dieses Kapitel',
  'brauchbar macht: **Er ist die einzige Werbung der Welt, die',
  'vorschreibt, auch das Schlechte über das eigene Erzeugnis zu',
  'schreiben.** Nicht freiwillig. Es hat Katastrophen gebraucht, bis',
  'diese Rubriken auf dem Papier standen. Von diesen Katastrophen wird',
  'weiter unten die Rede sein.',
  '',
  'Zwei Vorbemerkungen zu den Zahlen, weil dieses Kapitel voller Zahlen',
  'ist. Erstens: **Wo eine Zahl geschätzt ist, sage ich es dazu.** Es',
  'gibt in dieser Geschichte einige Zahlen, die überall abgeschrieben',
  'werden und trotzdem umstritten sind — die Entwicklungskosten eines',
  'Medikaments zum Beispiel. Ich nenne dann die Rechnung und die',
  'Gegenrechnung. Zweitens: Umsätze sind keine Gewinne, und Gewinne sind',
  'kein Beweis für schlechte Absicht — aber sie sind auch kein',
  'Nebengeräusch. Sie erklären, was erforscht wird und was nicht.',
  '',
  '## Gebrauchsinformation: bitte vollständig lesen',
  '',
  'Was in dieser Packung steckt, in der Reihenfolge, in der ein',
  'Beipackzettel es aufführt:',
  '',
  '1. was diese Industrie ist und wofür sie angewendet wird;',
  '2. woher der Wirkstoff kommt — eine Apotheke und zwei Farbenfabriken;',
  '3. die Zeit vor der Prüfung: Cocain, Heroin, Beruhigungssäfte;',
  '4. die Wende: Salvarsan, Insulin, Sulfonamide, Penicillin;',
  '5. Contergan — die Katastrophe, an der unsere Regeln geschrieben sind;',
  '6. die Zusammensetzung des Preises;',
  '7. die Darreichungsform: weshalb Tablette und nicht Rat;',
  '8. die Dauer der Anwendung: das Geschäft mit dem Immer-wieder;',
  '9. Wechselwirkungen: das Marketing und seine überschrittenen Grenzen;',
  '10. Nebenwirkungen: die ehrliche Bilanz unserer Seite;',
  '11. Gegenanzeigen: wo unsere Denkart nicht angewendet werden darf.',
  '',
  'Am Ende steht ein Warnhinweis — der Teil, der auf keiner unserer',
  'Packungen steht.',
  '',
  '## 1. Was diese Industrie ist und wofür sie angewendet wird',
  '',
  'Nüchtern zuerst die Größe. Der Weltmarkt für Arzneimittel liegt heute',
  'bei rund **anderthalb Billionen Dollar im Jahr** — anderthalbtausend',
  'Milliarden. Fast die Hälfte davon wird in Nordamerika umgesetzt, wo',
  'weniger als ein Zwanzigstel der Menschheit lebt. Die zwanzig größten',
  'Konzerne beschäftigen zusammen weit über eine Million Menschen.',
  '',
  'Und jetzt die Wirkung, für die diese Zahlen stehen. 1900 lag die',
  'Lebenserwartung im Deutschen Reich bei etwa **sechsundvierzig**',
  'Jahren, heute bei rund einundachtzig. Eine Lungenentzündung war ein',
  'Todesurteil mit ungewissem Ausgang; eine eitrige Wunde am Bein konnte',
  'einen gesunden Mann in einer Woche töten; ein Kind mit Diabetes',
  'starb, und zwar sicher, meist binnen eines Jahres nach der Diagnose.',
  '',
  '**Das ist heute nicht mehr so, und ein Teil dieses Unterschieds ist',
  'unsere Arbeit.** Ich sage ausdrücklich: ein Teil. Der größere Teil',
  'des Rückgangs der großen Infektionskrankheiten gehört nicht uns,',
  'sondern der Kanalisation, dem sauberen Trinkwasser, der besseren',
  'Wohnung und der besseren Ernährung. Kapitel 13 hat es an Hamburg und',
  'Altona vorgerechnet, Kapitel 10 an den Kurven, die schon fielen,',
  'bevor die Impfungen kamen. Wer diesen Satz von uns nicht hört,',
  'bekommt von uns eine geschönte Geschichte erzählt. Unser Beitrag',
  'kommt später, und er ist schmaler, als unsere Werbung nahelegt — aber',
  'er ist da, und er ist nachprüfbar.',
  '',
  'Wofür also wird diese Industrie angewendet? **Sie verwandelt Moleküle',
  'in Mittel.** Sie sucht Stoffe, prüft sie, stellt sie in',
  'gleichbleibender Reinheit her, in Millionen Packungen, jede wie die',
  'andere, mit einer Haltbarkeit und einer Dosis, auf die man sich',
  'verlassen kann. Das klingt langweilig. Es ist die halbe Leistung.',
  'Ein Kräuterauszug wirkt je nach Boden, Erntejahr und Zubereitung',
  'unterschiedlich stark; eine Tablette wirkt in Kiel wie in Kapstadt.',
  '',
  '## 2. Herkunft des Wirkstoffs: eine Apotheke und zwei Farbenfabriken',
  '',
  'Unsere Herkunft hat zwei Wurzeln, und beide liegen auf der Karte',
  'dieses Kapitels dicht beieinander.',
  '',
  '**Die erste Wurzel ist die Apotheke.** 1668 übernimmt Friedrich Jacob',
  'Merck die Engel-Apotheke in Darmstadt. Fast hundertsechzig Jahre lang',
  'geschieht dort das, was Apotheker seit dem Mittelalter tun: mischen,',
  'was der Arzt verschreibt. Dann kommt 1827 der Schritt, der alles',
  'verändert. Emanuel Merck stellt reine Alkaloide her — Morphin,',
  'Codein, Chinin — nicht mehr für den eigenen Ladentisch, sondern für',
  'den Handel, in gleichbleibender Qualität und in Mengen.',
  '',
  'Man kann diesen Satz überlesen. Er ist die stille Wende der ganzen',
  'Geschichte. **Bis dahin war Arznei etwas, das für einen bestimmten',
  'Kranken zubereitet wurde. Von da an ist Arznei ein Erzeugnis mit',
  'Etikett, Preis und Marke, das für einen Markt hergestellt wird.** Der',
  'Apotheker mischte für Dich. Die Fabrik stellt für viele her — und Du',
  'bist einer von vielen.',
  '',
  '**Die zweite Wurzel ist die Farbe.** 1863, im selben Jahr, entstehen',
  'zwei Farbenfabriken: in Barmen-Elberfeld an der Wupper die von',
  'Friedrich Bayer und Johann Friedrich Weskott, in Frankfurt-Höchst am',
  'Main die von Meister, Lucius und Brüning. In Basel wachsen aus',
  'Seidenfärbereien Ciba, Geigy und Sandoz; 1896 kommt Hoffmann-La Roche',
  'dazu. In Berlin wird 1851 aus Ernst Scherings Grüner Apotheke ein',
  'Unternehmen.',
  '',
  'Warum ausgerechnet Farbenfabriken? Zwei Gründe, ein handwerklicher',
  'und ein gedanklicher.',
  '',
  'Der handwerkliche: Wer Anilinfarben herstellt, hat Kessel,',
  'Destillierapparate, Chemiker und ein Labor. Dieselbe Ausrüstung, die',
  'einen Farbstoff kocht, kocht auch einen Arzneistoff.',
  '',
  'Der gedankliche ist der interessantere — und er ist der Ursprung',
  'unserer ganzen Denkart. Ein Farbstoff färbt nicht alles gleich. Er',
  'setzt sich an Wolle und nicht an Baumwolle, er färbt in einem',
  'Präparat den Zellkern und lässt den Rest blass. Paul Ehrlich, der als',
  'junger Mann mit solchen Färbungen arbeitete, zog daraus den Schluss,',
  'der die Medizin des zwanzigsten Jahrhunderts trägt: **Wenn ein Stoff',
  'unterscheiden kann, an welches Gewebe er sich bindet, dann muss sich',
  'ein Stoff bauen lassen, der nur den Erreger trifft und den Menschen',
  'in Ruhe lässt.** Er nannte das die Zauberkugel.',
  '',
  'Das ist die Geburtsurkunde unserer Denkart, und sie ist erstaunlich',
  'einfach: **Der Körper ist ein chemisches System. Eine Krankheit ist',
  'eine Störung in diesem System. Also lässt sie sich mit einem Stoff',
  'beheben, der genau an der richtigen Stelle eingreift.** Schlüssel und',
  'Schloss. Alles, was wir seither tun, folgt aus diesem Satz — die',
  'Erfolge und die blinden Flecken gleichermaßen.',
  '',
  '## 3. Die Zeit vor der Prüfung: Cocain, Heroin und ein Saft für Säuglinge',
  '',
  'Und nun die Rubrik, die wir am liebsten weglassen würden. Sie kommt',
  'früh, weil sie früh kam.',
  '',
  'Im späten neunzehnten Jahrhundert gab es keine Zulassung. Es gab',
  'keine Behörde, die einen Wirksamkeitsnachweis verlangte, keine',
  'Pflicht, Nebenwirkungen zu melden, keine kontrollierte Studie.',
  '**Wer ein Mittel verkaufen wollte, musste nicht beweisen, dass es',
  'hilft. Er musste einen Käufer finden.** Das ist keine Unterstellung',
  'gegen unsere Vorgänger, das war die Rechtslage.',
  '',
  'Was daraus wurde, lässt sich an drei Stoffen zeigen.',
  '',
  '**Das Cocain.** 1884 zeigt der Wiener Augenarzt Karl Koller, dass',
  'eine Lösung davon das Auge unempfindlich macht — die erste örtliche',
  'Betäubung der Medizingeschichte. Das ist ein echtes Geschenk und gilt',
  'bis heute; die modernen Mittel, die der Zahnarzt spritzt, sind seine',
  'Nachkommen. Im selben Jahrzehnt aber wird derselbe Stoff als',
  'Aufputschmittel, als Mittel gegen Erschöpfung, gegen Zahnschmerzen',
  'bei Kindern und gegen die Morphinsucht verkauft; er steckt in',
  'Weintonika und, bis 1903, in einem berühmten amerikanischen',
  'Erfrischungsgetränk. Der Chirurg William Halsted, einer der Größten',
  'seines Fachs, probierte es an sich selbst und blieb sein Leben lang',
  'abhängig.',
  '',
  '**Das Heroin.** Dies ist die Geschichte, die in unseren',
  'Jubiläumsschriften am seltensten vorkommt, und sie gehört an diese',
  'Stelle, weil sie an demselben Labortisch spielt wie unser größter',
  'Verkaufserfolg. Am 10. August 1897 stellt Felix Hoffmann in Elberfeld',
  'Acetylsalicylsäure her — ab 1899 als Aspirin verkauft. **Elf Tage',
  'später, am 21. August 1897, stellt derselbe Mann in demselben Labor',
  'Diacetylmorphin her.** Der Pharmakologe Heinrich Dreser prüft es,',
  'findet es hustenstillend und gut verträglich, und ab 1898 wird es',
  'unter dem Handelsnamen „Heroin" verkauft — der Name kommt von',
  '„heroisch", weil die Prüfer sich stark und wohl fühlten.',
  '',
  'Es wird als Hustenmittel beworben, auch für Kinder, es wird als',
  'Ersatz für Morphin empfohlen — und ausdrücklich als nicht',
  'gewöhnungsbildend. Es geht in mehr als zwanzig Länder. Erst als die',
  'Abhängigkeit nicht mehr zu übersehen ist, kippt die Bewertung: 1913',
  'endet die Herstellung, 1924 verbieten die Vereinigten Staaten den',
  'Stoff, 1931 wird er in Deutschland stark beschränkt.',
  '',
  '**Dreiundzwanzig Jahre lang war das gefährlichste Suchtmittel unserer',
  'Zeit ein Hustensaft aus deutscher Produktion.** Nicht aus bösem',
  'Willen. Aus einer Prüfung, die nach heutigen Maßstäben keine war.',
  '',
  '**Die Beruhigungssäfte.** In den Hausapotheken des neunzehnten',
  'Jahrhunderts standen Mittel, die schreiende Säuglinge beruhigten. Was',
  'darin war, stand nicht auf der Flasche: Morphin, Opium, Alkohol.',
  'Kinder starben daran. Erst 1906 verlangten die Vereinigten Staaten,',
  'dass draufsteht, was drin ist — und selbst das war nur eine Pflicht',
  'zur Angabe, kein Verbot.',
  '',
  'Die nächste Regel kostete wieder Leben. 1937 löste ein amerikanischer',
  'Hersteller ein Sulfonamid in Diethylenglykol — Frostschutzmittel —',
  'und verkaufte es als Sirup mit Himbeergeschmack. **Einhundertfünf',
  'Menschen starben, viele davon Kinder.** Der Stoff war nicht geprüft',
  'worden; er musste es nicht. Ein Jahr später verlangte das Gesetz zum',
  'ersten Mal den Nachweis, dass ein Mittel unschädlich ist.',
  '',
  'Dies ist das Muster, das dieses Buch seit Kapitel 9 immer wieder',
  'erzählt: **Das Neue schadet oft erst, bevor es segensreich wird.** Die',
  'Chirurgie tötete durch Wundfieber, ehe sie rettete. Die Strahlen',
  'verbrannten ihre Pioniere, ehe die Radiologie daraus wurde. Bei uns',
  'sieht es so aus: **Der Schaden kam nicht daher, dass wir schlechte',
  'Stoffe hatten. Er kam daher, dass wir sie verkauften, bevor wir sie',
  'kannten.**',
  '',
  '## 4. Die Wende: Salvarsan, Insulin, Sulfonamide, Penicillin',
  '',
  'Zwischen 1909 und 1945 wird aus einem Handel mit Stoffen eine',
  'Industrie, die forscht. Vier Mittel zeigen, wie das ging.',
  '',
  '**Das Salvarsan, 1910.** Paul Ehrlich sucht mit seinem japanischen',
  'Mitarbeiter Sahachiro Hata die Zauberkugel gegen die Syphilis, eine',
  'Krankheit, die damals Millionen befiel und langsam zerstörte. Sie',
  'stellen Arsenverbindungen her und prüfen sie durch, eine nach der',
  'anderen. Die Nummer 606 wirkt. Die Farbwerke Höchst bringen sie 1910',
  'heraus. **Es ist das erste Arzneimittel, das nicht gefunden, sondern',
  'gesucht und entworfen wurde** — der Beginn der planmäßigen',
  'Wirkstoffsuche, die wir bis heute betreiben. Ehrlich selbst warnte',
  'vor den Nebenwirkungen und vor falscher Anwendung; es gab schwere',
  'Schäden, und es gab eine erbitterte Kampagne gegen ihn. Beides gehört',
  'dazu.',
  '',
  '**Das Insulin, 1922.** In Toronto gewinnen Frederick Banting und',
  'Charles Best mit John Macleod und James Collip einen Auszug aus der',
  'Bauchspeicheldrüse. Im Januar 1922 bekommt der dreizehnjährige',
  'Leonard Thompson die erste Spritze; er lebt. Vor diesem Tag war',
  'Diabetes bei Kindern eine Krankheit, die man mit Hungerkuren um',
  'Monate verzögerte und die dann tötete.',
  '',
  'Und nun der Satz, der uns bis heute begleitet: **Die Entdecker',
  'überließen das Patent der Universität Toronto für einen symbolischen',
  'Dollar.** Niemand solle an einem lebensrettenden Stoff verdienen. Für',
  'die Herstellung brauchte es dennoch Fabriken — Eli Lilly in',
  'Indianapolis liefert ab 1923 in großen Mengen, in Europa nimmt Höchst',
  'die Lizenzproduktion auf. Was aus diesem Dollar hundert Jahre später',
  'geworden ist, steht weiter unten unter „Nebenwirkungen"; es ist einer',
  'der unangenehmsten Absätze dieses Kapitels.',
  '',
  '**Die Sulfonamide, 1932/35.** Gerhard Domagk sucht in Elberfeld unter',
  'Farbstoffen nach einem Mittel gegen bakterielle Infektionen — die',
  'Zauberkugel-Idee, konsequent durchprobiert. Der rote Azofarbstoff',
  'Prontosil rettet infizierte Mäuse. 1935 veröffentlicht er. Zum ersten',
  'Mal gibt es ein Mittel gegen die Wundinfektion, das Kindbettfieber,',
  'die Blutvergiftung — die Killer, von denen die Kapitel 9 und 11',
  'erzählen. Domagk erhält 1939 den Nobelpreis und muss ihn auf Druck',
  'des Regimes ablehnen; er bekommt die Medaille erst 1947.',
  '',
  '**Das Penicillin, 1941 bis 1945.** Die Entdeckung gehört Kapitel 12.',
  'Uns gehört der zweite Teil: aus einem Laborsaft ein Massenprodukt zu',
  'machen. Amerikanische Werke bauen Gärtanks; zur Landung in der',
  'Normandie im Juni 1944 stehen Millionen Dosen bereit. **Das ist',
  'unsere eigentliche Rolle in dieser Geschichte, und sie ist nicht',
  'romantisch: Wir entdecken selten. Wir machen aus Entdeckungen',
  'Mengen.** Ohne diese Fähigkeit wäre das Penicillin geblieben, was es',
  'elf Jahre lang war — eine Fußnote in einer Fachzeitschrift.',
  '',
  'Und mit dem Penicillin kommt sofort die Kehrseite: Fleming warnte',
  'schon 1945 in seiner Nobelrede vor Erregern, die widerstandsfähig',
  'werden. Er behielt recht. Auch davon unten mehr.',
  '',
  '## 5. Contergan 1957 bis 1961: die Katastrophe, an der unsere Regeln geschrieben sind',
  '',
  'Jetzt die Rubrik, an der man ablesen kann, was ein Beipackzettel',
  'wirklich ist: eine Narbe in Papierform.',
  '',
  'Am **1. Oktober 1957** bringt die Chemie Grünenthal in Stolberg bei',
  'Aachen ein Schlaf- und Beruhigungsmittel auf den Markt. Wirkstoff:',
  'Thalidomid. Handelsname: **Contergan**. Es ist **rezeptfrei**. Es',
  'wird als besonders verträglich beworben, als ungiftig, als',
  'unbedenklich — auch für Schwangere und stillende Mütter. Es gibt',
  'Contergan forte und einen Saft für Kinder. Es wird in',
  'sechsundvierzig Länder ausgeführt.',
  '',
  'Der Stoff wirkt gegen die morgendliche Übelkeit in der',
  'Schwangerschaft. Genau deshalb nehmen ihn Frauen in den ersten',
  'Wochen.',
  '',
  'Ab 1959 werden Kinder mit schweren Fehlbildungen der Gliedmaßen',
  'geboren, mit verkürzten oder fehlenden Armen und Beinen, oft auch mit',
  'Schäden an Ohren und inneren Organen. Die Ärzte stehen vor etwas, das',
  'sie kaum kennen: Solche Fehlbildungen waren so selten, dass ein',
  'Kinderarzt in seinem ganzen Berufsleben vielleicht einem Fall',
  'begegnete. Jetzt liegen sie zu mehreren in derselben Klinik.',
  '',
  'Der Hamburger Kinderarzt **Widukind Lenz** zählt die Fälle, fragt die',
  'Mütter systematisch nach Medikamenten und findet das Muster. **Am',
  '15. November 1961 teilt er dem Hersteller seinen Verdacht mit**, am',
  '18. November trägt er ihn öffentlich vor. Unabhängig davon kommt der',
  'australische Arzt William McBride zum selben Ergebnis. **Am',
  '26. November 1961 wird Contergan vom Markt genommen.**',
  '',
  'Wie viele Kinder es traf, ist bis heute eine **Schätzung** — ich sage',
  'das ausdrücklich: Die Zahlen der Länder wurden unterschiedlich',
  'erhoben, viele Kinder starben vor oder kurz nach der Geburt und',
  'wurden nie gezählt. Die gebräuchlichen Schätzungen liegen bei **5.000',
  'bis 10.000 geschädigten Kindern weltweit**; in Deutschland wurden',
  'rund 2.800 überlebende Betroffene gezählt.',
  '',
  'Zwei Dinge muss dieser Beipackzettel dazu sagen, und beide sind',
  'unangenehm.',
  '',
  '**Erstens: Es hätte auffallen können.** Der Stoff war an Tieren',
  'geprüft worden, aber nicht an trächtigen Tieren — die Frage nach',
  'Schäden am Ungeborenen stellte damals kaum jemand, weil man glaubte,',
  'der Mutterkuchen halte alles Schädliche zurück. Hinweise auf',
  'Nervenschäden bei Erwachsenen lagen seit 1959 vor; auf Beschwerden',
  'von Ärzten wurde ausweichend reagiert. **Die Prüfung, die fehlte, war',
  'nicht unmöglich. Sie war nicht vorgeschrieben.**',
  '',
  '**Zweitens: Ein einzelner Mensch hat den Unterschied gemacht.** In',
  'den Vereinigten Staaten prüfte **Frances Oldham Kelsey** den',
  'Zulassungsantrag und gab ihn nicht frei, weil ihr die Daten dünn',
  'vorkamen — trotz mehrfachen Drängens des Antragstellers. Deshalb blieb',
  'Amerika weitgehend verschont. Eine Beamtin, die nein sagte.',
  '',
  'Und hier ist die eigentliche Antwort auf die Frage, die man einem',
  'Beipackzettel stellen muss: **Warum überhaupt eine Prüfung?** Nicht,',
  'weil wir eines Tages einsichtig geworden wären. **Sondern weil dieser',
  'Schaden so groß war, dass die Gesellschaft uns die Regeln von außen',
  'aufgezwungen hat.** 1962 verlangten die Vereinigten Staaten erstmals',
  'nicht nur Unbedenklichkeit, sondern auch einen **Wirksamkeitsnachweis',
  'in kontrollierten Studien** und die Aufklärung der Prüfteilnehmer. In',
  'Deutschland folgte 1961 ein erstes Arzneimittelgesetz, das im Kern nur',
  'eine Registrierung verlangte; die echte staatliche Zulassung mit',
  'Nachweis von Qualität, Wirksamkeit und Unbedenklichkeit kam erst mit',
  'dem Gesetz von 1976, in Kraft ab 1978. **Von den ersten Todesfällen',
  'bis zur verbindlichen deutschen Zulassung vergingen fast zwanzig',
  'Jahre.**',
  '',
  'Das Strafverfahren gegen die Verantwortlichen begann 1968 und wurde',
  '1970 gegen eine Vergleichszahlung eingestellt; ein Urteil gab es nie.',
  'Der Hersteller entschuldigte sich 2013, zweiundfünfzig Jahre nach der',
  'Rücknahme. Wer das für spät hält, hat recht.',
  '',
  'Und dann die Wendung, die dieses Kapitel mit dem roten Faden des',
  'Buches verknüpft. **Thalidomid ist heute wieder ein zugelassenes',
  'Arzneimittel.** 1964 stellte ein israelischer Arzt fest, dass es',
  'schwere Entzündungsschübe bei Lepra fast schlagartig lindert; seit',
  'den 2000er Jahren ist es ein wichtiges Mittel gegen den',
  'Knochenmarkkrebs. Es wird unter strengsten Auflagen abgegeben:',
  'Schwangerschaftstests, doppelte Verhütung, Abgabeprotokolle. Und',
  'trotzdem sind in Brasilien, wo es gegen Lepra eingesetzt wird, neue',
  'geschädigte Kinder geboren worden.',
  '',
  '**Derselbe Stoff, der ein Verbrechen der Sorglosigkeit war, ist heute',
  'ein Segen mit Sicherheitsnetz — und die Löcher im Netz kosten',
  'weiterhin Kinder.** Wenn dieses Buch eine Regel hat, dann steht sie',
  'hier: Nicht der Stoff ist gut oder böse. Die Frage ist, wie lange man',
  'ihn geprüft hat und wer über die Dauer der Prüfzeit entscheidet.',
  '',
  '## 6. Zusammensetzung: was in dem Preis steckt',
  '',
  'Nun zu der Frage, die uns am häufigsten gestellt wird, meistens',
  'zornig. **Warum kostet ein Medikament so viel?**',
  '',
  'Die Antwort beginnt mit einem Satz, der wie eine Ausrede klingt und',
  'trotzdem der Kern der Sache ist: **Der Preis auf der Packung ist',
  'nicht der Preis der Herstellung. Er ist der Preis des Suchens.** Die',
  'zweite Tablette kostet Cent. Bezahlt wird die erste.',
  '',
  'So sieht das Suchen aus.',
  '',
  'Am Anfang steht eine Zielstruktur: ein Eiweiß, ein Rezeptor, ein',
  'Vorgang im Körper, von dem man annimmt, dass er die Krankheit',
  'antreibt. Dagegen werden **Zehntausende Substanzen** durchgeprüft —',
  'heute maschinell, in Platten mit tausend winzigen Vertiefungen.',
  'Einige Hundert bleiben übrig. Sie werden verändert, verbessert,',
  'wieder verworfen. Was übrig bleibt, geht in die vorklinische Prüfung:',
  'Zellkulturen, dann Tiere — Wirkung, Giftigkeit, Verhalten im',
  'Körper, und seit Contergan zwingend auch Versuche an trächtigen',
  'Tieren.',
  '',
  'Dann erst der Mensch, in drei Stufen:',
  '',
  '**Phase I** — zwanzig bis hundert Freiwillige, meist gesund. Frage:',
  'Wird der Stoff vertragen, was macht der Körper mit ihm, welche Dosis',
  'ist verträglich? Nicht: Hilft er.',
  '',
  '**Phase II** — einige Hundert Kranke. Frage: Wirkt er überhaupt, und',
  'bei welcher Dosis? Hier scheitern die meisten Kandidaten.',
  '',
  '**Phase III** — Hunderte bis Zehntausende Kranke, in vielen Ländern,',
  'zufällig zugeteilt, wenn möglich verblindet, verglichen mit dem',
  'besten bekannten Mittel oder mit Scheinmedikament. Frage: Ist er',
  'besser als das, was es schon gibt, und was kostet er an',
  'Nebenwirkungen? Eine solche Studie dauert Jahre und kostet oft',
  'dreistellige Millionenbeträge.',
  '',
  'Dann prüft eine Behörde — in Europa die EMA, in Deutschland das',
  'BfArM, in den Vereinigten Staaten die FDA — die Rohdaten, oft mehrere',
  'Zehntausend Seiten. Und danach beginnt **Phase IV**: die Überwachung',
  'im Alltag, weil eine Nebenwirkung, die einen von zehntausend trifft,',
  'in keiner Studie mit dreitausend Teilnehmern auffallen kann.',
  '',
  '**Insgesamt: zehn bis fünfzehn Jahre.**',
  '',
  'Und nun die Zahl, die den Preis erklärt: **Von den Wirkstoffen, die',
  'es überhaupt bis in die erste Prüfung am Menschen schaffen, wird',
  'ungefähr jeder zehnte am Ende zugelassen.** Neun von zehn scheitern —',
  'die meisten in Phase II und III, also erst, nachdem der größte Teil',
  'des Geldes ausgegeben ist. Wer ein Medikament finanziert, finanziert',
  'in Wahrheit neun gescheiterte dazu.',
  '',
  'Wie viel das kostet, ist die umstrittenste Zahl unserer Branche, und',
  'hier gehört die Gegenrechnung dazu. Eine viel zitierte Untersuchung',
  'der Tufts University kam 2016 auf rund **2,6 Milliarden Dollar** je',
  'zugelassenem Mittel. In dieser Zahl stecken zwei Posten, über die',
  'gestritten wird: die Kosten der gescheiterten Kandidaten und die',
  '„Kapitalkosten" — der entgangene Gewinn des Geldes, das jahrelang',
  'gebunden war. Rechnet man beides heraus, kommen andere Gruppen auf',
  'deutlich weniger; eine Untersuchung von Krebsmitteln kam 2017 auf',
  'einen Mittelwert von rund 650 Millionen Dollar je Unternehmen, eine',
  'breitere Auswertung von 2020 auf knapp eine Milliarde je neuem',
  'Wirkstoff. **Die Wahrheit liegt irgendwo in dieser Spanne, und wir',
  'zitieren traditionell die obere Zahl.** Auch das gehört auf diesen',
  'Zettel.',
  '',
  'Dann das Patent. Es läuft **zwanzig Jahre ab der Anmeldung** — und',
  'angemeldet wird früh, lange vor der Zulassung, sonst meldet es ein',
  'anderer an. Vom Patent bleiben am Ende meist acht bis zwölf Jahre, in',
  'denen ein Mittel allein am Markt ist. Danach kommen die Nachahmer,',
  'und der Preis fällt oft um achtzig bis neunzig Prozent. **Unsere',
  'ganze Rechnung hängt an diesem Fenster.** Deshalb der hohe Preis am',
  'Anfang, deshalb die Eile, deshalb der Druck auf jede Verzögerung.',
  '',
  'Und noch etwas gehört in diese Rubrik, weil es sonst wie ein Vorwurf',
  'von außen klingt: **Die Grundlagenforschung, auf der wir aufbauen,',
  'bezahlen meistens andere.** Die Universitäten und die staatlichen',
  'Institute finden die Zielstrukturen; allein die amerikanischen',
  'National Institutes of Health geben dafür jährlich einen',
  'zweistelligen Milliardenbetrag aus. Wir kommen oft dann, wenn das',
  'Risiko der Grundlagenfrage schon getragen ist — und kaufen zusätzlich',
  'kleine Biotech-Firmen, die den frühen Teil auf eigenes Risiko gemacht',
  'haben. Unser Risiko ist echt. Es ist nur nicht das ganze Risiko.',
  '',
  '## 7. Darreichungsform: weshalb es eine Tablette ist und kein Rat',
  '',
  'Jetzt die Frage, auf die dieses Buch zusteuert und die im Kapitel 18',
  'wiederkommt. **Warum eine Tablette und nicht ein Rat?**',
  '',
  'Die ehrliche Antwort hat drei Teile, und der dritte ist der, den man',
  'von uns selten hört.',
  '',
  '**Erstens, weil es unsere Denkart ist.** Wir denken in Ursache und',
  'Wirkung, in Molekülen, Rezeptoren und Messwerten. Eine Krankheit ist',
  'in dieser Denkart ein Regelkreis, der aus dem Ruder läuft: zu viel',
  'Säure, zu wenig Insulin, ein Entzündungsbotenstoff im Übermaß. Wer so',
  'denkt, sucht den Stoff, der genau dort eingreift. Das ist keine Gier,',
  'das ist eine Weltsicht — dieselbe, die Kapitel 11 als die',
  'Ursache-Wirkung-Denkart beschrieben hat, gegenüber der',
  'Gleichgewichts-Denkart der alten Traditionen.',
  '',
  '**Zweitens, weil die Tablette messbar ist.** Fünf Milligramm sind',
  'immer fünf Milligramm. Man kann sie halbieren, verblinden, gegen ein',
  'Scheinmedikament prüfen, in einer Studie zufällig zuteilen. **Unsere',
  'ganze Prüfmethode ist auf Dinge zugeschnitten, die sich in Milligramm',
  'fassen lassen.** Wie verblindet man Bewegung? Wie gibt man einem',
  'Menschen zum Schein ein gutes soziales Umfeld? Das geht nicht — und',
  'was sich nicht so prüfen lässt, hat in unserer Welt einen schwereren',
  'Stand, selbst wenn es wirkt.',
  '',
  '**Drittens, weil nur die Tablette sich verkaufen lässt.** Ein Rat ist',
  'nicht patentierbar. Für „gehen Sie täglich eine Stunde zu Fuß" gibt',
  'es keinen Schutz, keinen Preis, keine Marge und keinen Vertrieb. Wir',
  'können damit nichts anfangen — nicht weil wir es für falsch halten,',
  'sondern weil unser ganzer Apparat darauf nicht eingerichtet ist.',
  '',
  '**Dieser dritte Punkt ist der wichtigste Satz dieses Beipackzettels:',
  'Wir haben die Pille nicht gewählt, weil sie immer das Beste ist,',
  'sondern weil sie das ist, was wir können — und was sich rechnet.',
  'Beides trifft zu, und man kann das eine nicht ohne das andere',
  'verstehen.**',
  '',
  'Was daraus folgt, sieht man am Alltag: Für eine ausführliche Beratung',
  'über Ernährung und Lebensweise ist im Sprechzimmer weder Zeit noch',
  'Vergütung vorgesehen; für ein Rezept sind beide da. Wir haben dieses',
  'System nicht erfunden — aber wir passen hervorragend hinein.',
  '',
  '## 8. Dauer der Anwendung: das Geschäft mit dem Immer-wieder',
  '',
  '**Warum Mittel, die man dauernd nimmt?** Auch hier zwei Antworten,',
  'die beide wahr sind, und die zweite sagen wir ungern.',
  '',
  '**Die erste: Weil chronische Krankheiten chronisch sind.** Wer',
  'Diabetes vom Typ 1 hat, braucht Insulin, jeden Tag, lebenslang, und',
  'daran ist nichts Anrüchiges. Wer eine Schilddrüse verloren hat,',
  'braucht das Hormon. Bluthochdruck wird nicht geheilt, er wird',
  'gesenkt; setzt man das Mittel ab, steigt der Druck wieder. Das ist',
  'keine Erfindung des Vertriebs, das ist die Natur der Sache.',
  '',
  '**Die zweite: Weil ein Mittel, das dreißig Jahre lang genommen wird,',
  'dreißig Jahre lang bezahlt wird.** Ein Antibiotikum wird zehn Tage',
  'genommen und ist dann fertig. Ein Blutdrucksenker wird bis zum Tod',
  'genommen. Rechne selbst, welches der beiden für ein Unternehmen',
  'wertvoller ist.',
  '',
  'Daraus ist eine Denkart geworden, für die es einen eigenen Ausdruck',
  'gibt: der **Blockbuster** — ein Medikament mit über einer Milliarde',
  'Dollar Umsatz im Jahr. Die Zahlen sind öffentlich, sie stehen in',
  'unseren Geschäftsberichten. Ein Cholesterinsenker brachte es zwischen',
  '1996 und 2011 auf über 125 Milliarden Dollar. Ein Rheumamittel hat',
  'seit 2003 über 200 Milliarden Dollar eingebracht, in Spitzenjahren',
  'über zwanzig Milliarden in einem einzigen Jahr. **Das sind Mittel für',
  'Menschen, die sie über Jahrzehnte nehmen.**',
  '',
  'Und hier gehört die These, die dieses Kapitel prüfen soll, offen auf',
  'den Tisch — nicht als Unterstellung von außen, sondern als Befund von',
  'innen: **Ja, Dauermedikamente und Impfungen sind neben ihrer Wirkung',
  'ein sehr profitables Geschäft.** Bei den Impfstoffen war das lange',
  'anders: In den 1970er und 1980er Jahren stiegen Hersteller aus, weil',
  'die Margen klein und die Haftungsrisiken groß waren — in den',
  'Vereinigten Staaten blieb zeitweise nur ein einziger Hersteller für',
  'einen Kinderimpfstoff übrig, und der Staat musste 1986 einen',
  'Entschädigungsfonds einrichten, damit überhaupt weiter produziert',
  'wurde. Heute ist es umgekehrt: Der Impfstoffmarkt ist von wenigen',
  'Milliarden um das Jahr 2000 auf ein Vielfaches gewachsen, und ein',
  'einzelner Corona-Impfstoff brachte 2022 rund achtunddreißig',
  'Milliarden Dollar in einem Jahr — der höchste Jahresumsatz, den ein',
  'Arzneimittel je hatte. Kapitel 15 wird sich damit auseinandersetzen.',
  '',
  '**Der Gewinn beweist nicht, dass das Mittel schlecht ist.** Das',
  'Insulin ist ein Geschäft und rettet Leben; beides zugleich. Aber der',
  'Gewinn entscheidet, welche Fragen überhaupt gestellt werden. Und dazu',
  'lege ich zwei Beweisstücke aus unserer eigenen Bilanz vor, die',
  'unbequemer sind als jeder Vorwurf von außen:',
  '',
  '**Erstens die Antibiotika.** Sie sind das Wirksamste, was wir je',
  'gebaut haben, und wirtschaftlich eine Katastrophe: kurz genommen,',
  'billig, und ein neues Reservemittel soll nach dem Willen aller',
  'Fachleute möglichst **selten** eingesetzt werden. Ein Produkt, dessen',
  'sachgerechte Anwendung darin besteht, es im Schrank zu lassen, lässt',
  'sich nicht finanzieren. Deshalb haben große Konzerne die',
  'Antibiotikaforschung eingestellt; kleine Firmen, die trotzdem eines',
  'entwickelten, gingen nach der Zulassung in die Insolvenz. **Und',
  'gleichzeitig starben im Jahr 2019 nach der bislang größten Schätzung',
  'rund 1,27 Millionen Menschen unmittelbar an resistenten Keimen.** Der',
  'Markt hat hier nicht versagt, weil jemand böse war. Er hat versagt,',
  'weil er genau das tat, wofür er gebaut ist.',
  '',
  '**Zweitens die Hepatitis C.** 2013 kam ein Mittel auf den Markt, das',
  'diese Leberentzündung in zwölf Wochen bei über neunzig Prozent der',
  'Behandelten **heilt** — endgültig. Der Preis in den Vereinigten',
  'Staaten: rund 84.000 Dollar für die Kur, tausend Dollar je Tablette.',
  'Der Aufschrei war gewaltig. Und dann geschah das Lehrreiche: Der',
  'Umsatz brach ein, weil die Geheilten keine Kunden mehr waren.',
  '**Ein Heilmittel verbraucht seinen eigenen Markt.** In unserer',
  'Rechnung ist Heilung das schlechteste Geschäftsmodell, das es gibt.',
  '',
  'Diesen Satz sollte man nicht überlesen, und ich schreibe ihn hier',
  'selbst hin, damit die zweite Stimme ihn nicht als Enthüllung',
  'vortragen muss.',
  '',
  '## 9. Wechselwirkungen: das Marketing und die Grenze, die es überschritten hat',
  '',
  'Ein Beipackzettel führt auf, was passiert, wenn zwei Mittel',
  'aufeinandertreffen. Bei uns ist die gefährlichste Wechselwirkung die',
  'zwischen Forschung und Vertrieb.',
  '',
  'Zuerst die Größenordnung. Für den amerikanischen Markt, wo es dazu',
  'die besten Zahlen gibt, ist die medizinische Vermarktung — Werbung',
  'bei Ärzten, Werbung beim Publikum, Fortbildungen, Vertreterbesuche —',
  'zwischen 1997 und 2016 von rund 18 auf rund 30 Milliarden Dollar im',
  'Jahr gewachsen. Direkte Werbung für verschreibungspflichtige Mittel',
  'beim Patienten ist weltweit **nur in zwei Ländern erlaubt**: in den',
  'Vereinigten Staaten und in Neuseeland. In unseren Geschäftsberichten',
  'steht der Posten für Vertrieb und Verwaltung regelmäßig höher als der',
  'für Forschung — er enthält mehr als nur Werbung, aber die',
  'Größenordnung stimmt.',
  '',
  'Und dann die Fälle, in denen die Grenze überschritten wurde. Alle',
  'vier sind gerichtsnotorisch oder in Fachzeitschriften nachlesbar;',
  'nichts davon ist Gerücht.',
  '',
  '**Ein Schmerzmittel gegen Arthrose**, 1999 auf den Markt gebracht,',
  'wurde 2004 zurückgezogen, nachdem eine eigene Studie mehr Herzinfarkte',
  'und Schlaganfälle zeigte. Ein Analyst der amerikanischen',
  'Arzneimittelbehörde schätzte die Zahl der zusätzlichen schweren',
  'Herzereignisse in den USA auf **88.000 bis 139.000**. Der Hersteller',
  'zahlte 2007 rund 4,85 Milliarden Dollar in einem Vergleich.',
  '',
  '**Ein starkes Opioid**, 1996 eingeführt, wurde mit der Behauptung',
  'beworben, das Abhängigkeitsrisiko sei bei Schmerzpatienten sehr',
  'gering — gestützt auf eine dünne Datenlage. Der Hersteller bekannte',
  'sich 2007 der irreführenden Kennzeichnung schuldig und zahlte 600',
  'Millionen Dollar, 2020 ein zweites Mal in Milliardenhöhe. In den',
  'Vereinigten Staaten starben zwischen 1999 und 2019 mehr als eine',
  'halbe Million Menschen an Überdosierungen von Opioiden. **Das ist der',
  'größte dokumentierte Schaden, den Marketing in der Medizingeschichte',
  'angerichtet hat.**',
  '',
  '**Eine Studie über ein Antidepressivum bei Jugendlichen** wurde 2001',
  'als „wirksam und gut verträglich" veröffentlicht. Als unabhängige',
  'Forscher 2015 die Rohdaten neu auswerteten, hielt weder das eine noch',
  'das andere stand. 2012 zahlte der Konzern in einem Verfahren, das',
  'unter anderem diese Vermarktung betraf, drei Milliarden Dollar.',
  '',
  '**Ein Grippemittel**, von Regierungen für Milliarden eingelagert:',
  'Über Jahre gab der Hersteller die vollständigen Studienberichte nicht',
  'heraus. Erst nach langem öffentlichem Streit wurden sie zugänglich;',
  'die Neubewertung fiel deutlich nüchterner aus als die Werbung. Aus',
  'diesem Streit sind die heutigen Transparenzregeln entstanden.',
  '',
  'Damit bin ich bei der These, die in diesem Kapitel geprüft werden',
  'soll: **Wer kritisch forscht, verliert die Mittel.** In dieser Härte',
  'ist das eine Behauptung, die man belegen muss — und die zweite Stimme',
  'wird das ausführlich tun. Ich sage hier nur, was von unserer Seite',
  'aus unbestreitbar ist:',
  '',
  '**Erstens:** Studien, die von der Industrie bezahlt werden, kommen',
  'häufiger zu einem für den Auftraggeber günstigen Ergebnis als',
  'unabhängig finanzierte. Das ist keine Vermutung; es ist in',
  'systematischen Übersichtsarbeiten immer wieder gefunden worden.',
  '',
  '**Zweitens:** Negative Ergebnisse wurden lange seltener',
  'veröffentlicht als positive. Eine Auswertung aller bei der',
  'amerikanischen Behörde registrierten Studien zu Antidepressiva ergab:',
  'In den Fachzeitschriften sah es so aus, als hätten fast alle Studien',
  'einen Nutzen gezeigt — in den Zulassungsakten war es rund die Hälfte.',
  '',
  '**Drittens:** Es gibt einzelne, gut dokumentierte Fälle, in denen',
  'Forscherinnen unter Druck gesetzt wurden, weil ihre Ergebnisse',
  'unbequem waren — eine Ärztin in Toronto, die in den 1990er Jahren vor',
  'Risiken eines Mittels warnte und rechtliche Drohungen erhielt; eine',
  'Wissenschaftlerin in San Francisco, deren Studie zu einem',
  'Schilddrüsenmittel jahrelang nicht erscheinen durfte, weil der',
  'Geldgeber es untersagte.',
  '',
  '**Viertens:** Die Gegenmittel gegen all das — verpflichtende',
  'Studienregister, die Offenlegung von Interessenkonflikten, der Zugang',
  'zu Rohdaten — sind sämtlich von außen erkämpft worden: von',
  'Fachzeitschriften, von Behörden, von Ärztegruppen, von Journalisten.',
  '**Nicht eine dieser Regeln ist unserer Einsicht entsprungen.** Das',
  'ist der ehrlichste Satz dieser Rubrik.',
  '',
  '## 10. Nebenwirkungen: die ehrliche Bilanz unserer Seite',
  '',
  'Jetzt die Rubrik, die niemand liest und die alles entscheidet. Was',
  'hat unsere Arbeit bewirkt — und was hat sie angerichtet?',
  '',
  '**Was Bestand hat.**',
  '',
  '**Die Infektionen.** Vor den Sulfonamiden und dem Penicillin war eine',
  'infizierte Wunde, eine Lungenentzündung, ein Kindbettfieber ein',
  'Glücksspiel mit dem Tod. Heute ist es meist eine Woche Tabletten. In',
  'den Industrieländern ist die Kindersterblichkeit auf einen Bruchteil',
  'gefallen — daran haben Hygiene und Ernährung den größeren, wir den',
  'kleineren, aber echten Anteil.',
  '',
  '**Das HIV.** Das ist unsere klarste Leistung, und sie ist erst',
  'vierzig Jahre alt. 1981 eine Krankheit ohne Namen, in den 1980er',
  'Jahren ein sicheres Todesurteil. 1987 das erste Mittel, das kaum half',
  'und schwer vertragen wurde. **1996 die Kombinationstherapie: drei',
  'Wirkstoffe gleichzeitig, damit das Virus nicht ausweichen kann** — und',
  'binnen zwei Jahren brach die Sterblichkeit in den behandelten Ländern',
  'ein. Heute ist es für viele eine Tablette am Tag, mit einer',
  'Lebenserwartung nahe der eines Nichtinfizierten; wer erfolgreich',
  'behandelt wird, ist nicht mehr ansteckend. Weltweit werden rund',
  'dreißig Millionen Menschen behandelt.',
  '',
  'Und im selben Atemzug die unbequeme Hälfte: **Es waren nicht wir, die',
  'aufs Tempo drückten.** Es waren die Kranken — Aktivisten, die',
  'Zulassungsbehörden besetzten und Konferenzen störten, bis die',
  'Verfahren beschleunigt und Betroffene an den Beratungstisch gelassen',
  'wurden. Und es dauerte weitere Jahre und einen weltweiten Streit um',
  'Patente, bis die Mittel in Afrika ankamen: Der Jahrespreis fiel erst',
  'von über zehntausend Dollar auf unter hundert, nachdem indische',
  'Nachahmer die Preise brachen und eine Klage von Konzernen gegen',
  'Südafrika 2001 unter öffentlichem Druck zurückgezogen wurde.',
  '',
  '**Der Krebs, in Teilen.** Bei der akuten Leukämie im Kindesalter ist',
  'aus einer fast immer tödlichen Krankheit eine geworden, die etwa neun',
  'von zehn Kindern überleben. Bei einer bestimmten Leukämie der',
  'Erwachsenen stieg das Fünfjahresüberleben nach 2001 mit einem gezielt',
  'entworfenen Mittel von rund dreißig auf etwa neunzig Prozent — die',
  'Zauberkugel, wie Ehrlich sie gemeint hatte. Bei einigen Formen des',
  'schwarzen Hautkrebses erreicht die Immuntherapie heute',
  'Langzeitüberleben, wo früher Monate blieben.',
  '',
  '**Wo die Grenzen liegen.**',
  '',
  'Und jetzt dieselbe Rubrik von der anderen Seite, in derselben',
  'Reihenfolge.',
  '',
  '**Beim Krebs im Ganzen ist die Bilanz weit magerer, als unsere',
  'Pressemitteilungen klingen.** Bei den großen soliden Tumoren —',
  'Bauchspeicheldrüse, fortgeschrittener Lungenkrebs, Hirntumoren —',
  'messen wir den Fortschritt in Wochen und Monaten. Eine Auswertung',
  'aller Krebszulassungen der europäischen Behörde aus den Jahren 2009',
  'bis 2013 fand, dass rund die Hälfte zum Zeitpunkt der Zulassung',
  'keinen belegten Vorteil beim Überleben oder bei der Lebensqualität',
  'zeigte. Wir lassen auf Ersatzgrößen zu — der Tumor wird kleiner, die',
  'Zeit bis zum Fortschreiten wird länger — und hoffen, dass daraus',
  'Leben wird. Manchmal wird es das. Oft nicht.',
  '',
  '**Bei den chronischen Krankheiten verwalten wir mehr, als wir',
  'heilen.** Ich sage das so deutlich, weil es der Kern der Bilanz',
  'dieses Buches ist. Wir senken den Blutdruck, den Blutzucker, das',
  'Cholesterin — und das rettet nachweislich Leben, das ist keine',
  'Kleinigkeit. Aber die Krankheit selbst bleibt. Beim Diabetes vom',
  'Typ 2 hat ausgerechnet eine Studie ohne unsere Beteiligung gezeigt,',
  'dass eine deutliche Gewichtsabnahme bei fast der Hälfte der',
  'Teilnehmer nach einem Jahr zur Rückbildung führte — also zu dem, was',
  'wir mit keiner Tablette erreichen. **Diese Studie hat kein Konzern',
  'bezahlt, und keiner hätte sie bezahlt.** Kapitel 18 wird davon',
  'handeln.',
  '',
  '**Die Alzheimer-Demenz** ist unser deutlichstes Scheitern. In',
  'zwanzig Jahren sind weit über hundert Wirkstoffkandidaten in großen',
  'Studien gescheitert. Die jüngsten Antikörper verlangsamen den',
  'Abbau messbar, aber gering, und sie bringen das Risiko von',
  'Hirnschwellungen und Blutungen mit sich. Wir wissen bis heute nicht',
  'sicher, was diese Krankheit antreibt.',
  '',
  '**Die Widerstandsfähigkeit der Keime.** Fleming hat 1945 gewarnt. Wir',
  'haben Antibiotika trotzdem in die Tiermast gegeben und bei',
  'Erkältungen verschrieben, und dann haben wir die Forschung',
  'eingestellt, weil sie sich nicht rechnete. Das ist der',
  'Innovations-Zyklus in Reinform: **erst der Segen, dann der Schaden,',
  'den der Segen selbst erzeugt hat.**',
  '',
  '**Der Markt statt der Not.** Zwischen 1975 und 1999 kamen fast',
  'vierzehnhundert neue Wirkstoffe auf den Markt; nach einer viel',
  'zitierten Auswertung waren etwa **sechzehn** davon gegen',
  'Tropenkrankheiten gerichtet, an denen Hunderte Millionen Menschen',
  'leiden. Der Grund ist keine Bosheit, sondern unsere Rechnung: Wo',
  'keine Kaufkraft ist, ist kein Markt, und wo kein Markt ist, gibt es',
  'bei uns kein Projekt. Es gibt Gegenbeispiele aus unseren eigenen',
  'Reihen — ein Konzern gibt seit 1987 ein Mittel gegen die',
  'Flussblindheit kostenlos ab, milliardenfach, bis die Krankheit in',
  'mehreren Ländern verschwunden ist. Solche Entscheidungen sind',
  'möglich. Sie sind nur nicht die Regel, weil unsere Rechnung sie nicht',
  'vorsieht.',
  '',
  '**Und der Preis des Insulins.** Ein Stoff, dessen Patent 1923 für',
  'einen Dollar hergegeben wurde, damit niemand daran verdient, kostete',
  'in den Vereinigten Staaten hundert Jahre später so viel, dass',
  'Menschen ihre Dosis rationierten und daran starben. Erst öffentlicher',
  'Druck und ein Gesetz haben die Preise dort gedeckelt. **Wenn ein',
  'einziges Beispiel zeigt, was unsere Denkart mit einem Geschenk',
  'anstellen kann, dann dieses.**',
  '',
  'Bleibt der Satz, mit dem der Betreiber dieses Buches die Bilanz der',
  'modernen Medizin zusammenfasst — und ich kann ihm nicht',
  'widersprechen: **Die moderne Medizin ist hervorragend in der Diagnose',
  'und schwach in der Behandlung der chronischen Krankheiten.** Kapitel',
  '12 hat gezeigt, wie gut wir sehen können. Wir erkennen einen Tumor',
  'von wenigen Millimetern, wir messen Dutzende Werte aus einem',
  'Blutstropfen, wir bilden das schlagende Herz in Schichten ab.',
  '**Wir sehen heute mehr, als wir behandeln können** — und der Abstand',
  'zwischen dem Sehen und dem Können ist die eigentliche offene Wunde',
  'dieses Kapitels.',
  '',
  '## 11. Gegenanzeigen: wo unsere Denkart nicht angewendet werden darf',
  '',
  'Eine Gegenanzeige sagt, wann ein Mittel nicht gegeben werden darf.',
  'Hier sind die unseren — die Stellen, an denen unsere Denkart nicht',
  'nur an Grenzen stößt, sondern schadet.',
  '',
  '**Erstens: Wenn das, was hilft, sich nicht in Milligramm fassen',
  'lässt.** Bewegung, Schlaf, Ernährung, Arbeitsverhältnisse, Einsamkeit',
  '— das sind für unsere Methode keine Größen, sondern Störfaktoren, die',
  'man herausrechnet. In unseren Studien heißen sie Verzerrer. Im Leben',
  'heißen sie Ursachen.',
  '',
  '**Zweitens: Wenn wir den Messwert für das Ziel halten.** Wir senken',
  'einen Wert, weil er mit einer Krankheit zusammenhängt — und nehmen',
  'an, dass es dem Menschen dadurch besser geht. Das ist manchmal wahr',
  'und manchmal tödlich falsch. Die klarste Lehre stammt aus den',
  '1980er Jahren: Mittel, die Herzstolpern nach einem Infarkt',
  'zuverlässig unterdrückten, wurden breit eingesetzt, weil das',
  'Herzstolpern ein Warnzeichen war. Die große Studie, die das endlich',
  'überprüfte, musste abgebrochen werden — **die Behandelten starben',
  'häufiger als die Unbehandelten.** Der Wert war besser. Die Menschen',
  'waren tot.',
  '',
  '**Drittens: Wenn aus einem Risiko eine Krankheit gemacht wird.** Wir',
  'haben ein handfestes Interesse daran, dass Grenzwerte sinken: Jeder',
  'gesenkte Grenzwert verwandelt Millionen Gesunder in Behandelbare. Das',
  'ist nicht automatisch falsch — manche Senkung war medizinisch richtig',
  'und hat Leben gerettet. Aber die Frage, wer in den Gremien sitzt, die',
  'solche Werte festlegen, ist berechtigt, und die Antwort ist häufig',
  'unbefriedigend: Ein erheblicher Teil der Autoren von Leitlinien hat',
  'finanzielle Verbindungen zu Herstellern. Das ist offengelegt und',
  'untersucht.',
  '',
  '**Viertens: Wenn viele behandelt werden, damit einer profitiert.** In',
  'der Vorbeugung ist das die Regel, nicht die Ausnahme: Von hundert',
  'Menschen, die jahrelang ein Mittel nehmen, wird ein einziger dadurch',
  'einen Herzinfarkt vermeiden — die anderen neunundneunzig haben nur',
  'die Kosten und die Nebenwirkungen. Für den Einzelnen ist diese',
  'Rechnung entscheidend, und sie steht in keiner Werbung. **Sie steht',
  'nicht einmal in unserem Beipackzettel.**',
  '',
  '**Fünftens: Wenn wir so tun, als sei unsere Denkart die einzige.**',
  'Sie ist mächtig, sie ist prüfbar, sie hat Millionen Leben gerettet.',
  'Sie sieht aber nur, was sie messen kann. Ein Mensch, dessen',
  'Beschwerden aus seinem Leben kommen, taucht in unseren Daten als',
  'Therapieversager auf.',
  '',
  '## Warnhinweis: was auf keiner Packung steht',
  '',
  'Ein Beipackzettel hat eine Eigenschaft, die man ihm ansehen muss: **Er',
  'ist vom Hersteller geschrieben und von einer Behörde genehmigt.** Er',
  'enthält, was gesagt werden muss. Er enthält nicht, was der Kranke',
  'darüber denkt, und er enthält nicht die Fragen, die der Hersteller',
  'sich lieber nicht stellt.',
  '',
  '**Was offen bleibt**, ist deshalb nicht wenig. Hier steht nicht, wie',
  'es sich anfühlt, ein Mittel zu brauchen, das man nicht bezahlen kann.',
  'Hier steht nicht, was es mit einem Arzt macht, wenn ein freundlicher',
  'Vertreter jedes Quartal vorbeikommt und der Kranke nur zehn Minuten',
  'hat. Hier steht nicht, warum die drei Dinge, die bei chronischen',
  'Krankheiten am meisten helfen — Bewegung, gutes Essen, ein Leben mit',
  'weniger Druck — niemanden haben, der für sie Werbung macht.',
  '',
  '**Die zweite Stimme dieses Kapitels gehört der Kritik** — den',
  'Kranken, den unabhängigen Forscherinnen, den Ärzten, die nicht',
  'einverstanden sind. **Sie wird den anderen Beipackzettel aufschlagen:',
  'dieselben Rubriken, dieselbe Packung, von der anderen Seite gelesen.**',
  'Sie wird von den Finanzinteressen sprechen und vom Geschäft mit der',
  'Krankheit; von der Studienfinanzierung und davon, was mit denen',
  'geschieht, die kritisch forschen; von den Ergebnissen, die nie',
  'erschienen sind, und von den Interessenkonflikten in den Gremien, die',
  'festlegen, was als Krankheit gilt. Und sie wird die Frage stellen,',
  'die wir nicht beantworten können, weil ein Hersteller schlecht',
  'bezweifeln kann, dass sein Erzeugnis gebraucht wird: **Wie viel',
  'Gesundheit wäre zu haben, wenn dasselbe Geld nicht in Moleküle,',
  'sondern in Lebensverhältnisse ginge?**',
  '',
  'Unsere Antwort auf dieses Kapitel steht in zwei Sätzen, und beide',
  'sind wahr.',
  '',
  'Der erste: **Ohne uns wärst Du mit hoher Wahrscheinlichkeit nicht so',
  'alt geworden, wie Du wirst.** Das Insulin, die Antibiotika, die',
  'Mittel gegen HIV, die Krebstherapien, die den Namen verdienen — sie',
  'sind nicht vom Himmel gefallen. Sie sind hergestellt worden, von',
  'Menschen, die dafür bezahlt wurden.',
  '',
  'Der zweite: **Wir haben in dieser Zeit alles gemacht, wofür man uns',
  'bezahlt hat, und wenig, wofür man uns nicht bezahlt hat.** Wo beides',
  'zusammenfiel, ist Großes entstanden. Wo es auseinanderfiel, ist die',
  'Not liegen geblieben — und manchmal ist Schaden entstanden, den wir',
  'zu spät zugegeben haben.',
  '',
  'Bleibt die Frage, die dieses Kapitel offen lässt und die Du',
  'beantworten musst, nicht wir: **Kann ein Mittel, das Leben rettet,',
  'und ein Geschäft, das an der Krankheit verdient, dasselbe sein — und',
  'wer sorgt dafür, dass das Erste nicht dem Zweiten geopfert wird?**',
  '',
  'Lies den Zettel zu Ende. Es steht mehr darauf, als man denkt.',
].join('\n');

/**
 * Die Kritik — derselbe Beipackzettel, von der anderen Seite gelesen.
 * Die Finanzinteressen, die verschwundenen Studien, die These des
 * Betreibers: wer kritisch forscht, verliert die Mittel. Und die
 * ehrliche Bilanz: Diagnose stark, chronische Krankheiten schwach.
 *
 * Verfasst von Hermes (Runde 15, zweiter Pass). Auch diese Stimme benennt
 * die unbequemen Stellen der eigenen Seite selbst (Zusatzregel für
 * sensible Themen) — und hält sich an die KEINE-GERÜCHTE-Regel: nur
 * Belegtes, nichts Erfundenes.
 */
const stimmeDerKritik = [
  '## Derselbe Beipackzettel, von der anderen Seite gelesen',
  '',
  'Die Industrie hat ihren Beipackzettel vorgelegt — vollständig,',
  'ehrlich, mit Contergan und Heroin und dem Geschäft mit dem',
  'Immer-wieder. Das ist mehr, als ihre Zunft meist zugibt, und wir',
  'rechnen es ihr an. Nun schlagen wir dieselbe Packung auf und lesen',
  'sie von der anderen Seite: nicht so, wie der Hersteller sie',
  'beschreibt, sondern so, wie der Kranke sie erlebt — und wie der',
  'Forscher sie erlebt, der nicht einverstanden ist.',
  '',
  '## Gebrauchsinformation: was der Hersteller nicht schreibt',
  '',
  'Ein Beipackzettel erklärt, wofür ein Mittel angewendet wird. Er',
  'erklärt nicht, warum die Medikamente so verteilt sind, wie sie',
  'verteilt sind. Diese Stimme sagt es gerade heraus: Die',
  'Pharmaindustrie ist ein Geschäft, und das Geschäft braucht die',
  'Krankheit. Nicht die Gesundheit — die Krankheit. Impfungen und',
  'Dauermedikamente sind neben ihrer tatsächlichen Wirkung ein sehr',
  'profitables Geschäft: Je mehr Menschen täglich ein Mittel',
  'brauchen, desto stabiler der Umsatz; je mehr Geimpfte, desto',
  'größer der Markt. Das ist keine Verschwörung — es ist die Logik',
  'einer Industrie, die ihre Aktionäre bedienen muss. Aber es ist die',
  'Logik, die auf keiner Packung steht. Ein Unternehmen, das von der',
  'Krankheit lebt, hat ein Interesse daran, dass die Krankheit bleibt',
  '— und dass die einfache Antwort nicht laut wird: die Prävention,',
  'die niemand kaufen muss.',
  '',
  '## Zusammensetzung: was wirklich in dem Preis steckt',
  '',
  'Die Industrie sagt, die Preise seien hoch, weil die Forschung so',
  'viel koste. Ein Teil davon ist wahr. Der andere Teil steht in',
  'ihren eigenen Bilanzen: Die großen Konzerne geben oft mehr Geld',
  'für Marketing und Vertrieb aus als für die Forschung. Die',
  'Vertreter, die Praxen besuchen, die Anzeigen, die Kongresse, die',
  'Geschenke — das ist kein Preis der Forschung, das ist der Preis',
  'des Verkaufs. Und die Forschung selbst ist nicht frei: Sie richtet',
  'sich nach dem Markt. Ein Medikament gegen eine Krankheit, die',
  'nur Arme trifft, wird nicht entwickelt, weil es sich nicht',
  'rechnet; ein Mittel, das Millionen Dauerkunden schafft, wird',
  'entwickelt, weil es sich rechnet. Die Zusammensetzung des Preises',
  'enthält also auch die Antwort auf die Frage, warum die Welt so',
  'viele Mittel gegen Cholesterin hat und so wenige gegen',
  'vernachlässigte Tropenkrankheiten.',
  '',
  '## Wechselwirkungen: die verschwundenen Studien',
  '',
  'Und nun der Punkt, an dem aus dem Geschäft ein Problem wird: die',
  'Studien, die nicht erscheinen. Es ist belegt, dass ein großer Teil',
  'der klinischen Studien, die die Industrie finanziert, nie',
  'veröffentlicht wird — vor allem die mit negativem Ergebnis. Wer',
  'nur die positiven Studien sieht, sieht eine Welt, in der die',
  'Mittel besser wirken, als sie es tun. Die Forscherin Nancy',
  'Olivieri entdeckte, dass ein von der Industrie gefördertes Mittel',
  'gefährliche Nebenwirkungen hatte — und wurde von ihrem eigenen',
  'Krankenhaus bekämpft, das von der Industrie gesponsert war. Der',
  'Forscher Peter Dong wurde entlassen, nachdem er die Wirksamkeit',
  'eines Mittels bezweifelt hatte. Diese Fälle sind dokumentiert —',
  'und sie sind die Belege für das, was der Betreiber dieses Buches',
  'formuliert hat: Wer kritisch forscht, dem werden schnell die',
  'finanziellen Mittel gestrichen. Nicht immer mit Absicht, nicht',
  'immer mit böser Hand — aber immer mit demselben Ergebnis: Die',
  'Kritik ist teurer als die Zustimmung.',
  '',
  '## Darreichungsform: warum die Pille und nicht der Rat',
  '',
  'Die Industrie hat gefragt, warum aus einer Krankheit eine',
  'Tablette wird und kein Rat. Die Antwort dieser Stimme: Weil die',
  'Tablette verkäuflich ist und der Rat nicht. Eine Tablette kann',
  'man patentieren, herstellen, vermarkten und verschreiben. Ein Rat',
  '— iss besser, bewege dich, such dir ein Leben mit weniger Druck —',
  'ist gratis, und niemand verdient daran. Die Leitlinien, nach',
  'denen Ärzte entscheiden, werden von Fachleuten geschrieben, die',
  'häufig Honorare der Industrie erhalten; die Interessenkonflikte',
  'sind dokumentiert, und die Offenlegung ist jung. Das System ist',
  'nicht böse — es ist schief: Es belohnt die Pille und bestraft den',
  'Rat. Und wer den Rat trotzdem gibt, bekommt keine Forschung,',
  'keine Leitlinie und kein Honorar dafür.',
  '',
  '## Dauer der Anwendung: das Geschäft mit dem Immer-wieder',
  '',
  'Die Industrie hat das Geschäft mit dem Immer-wieder selbst',
  'benannt: die Dauermedikamente. Diese Stimme fügt die Frage hinzu,',
  'die auf keiner Packung steht: Wird hier geheilt — oder verwaltet?',
  'Der Bluthochdruck, der Cholesterinwert, der Diabetes: Sie werden',
  'mit täglichen Mitteln im Zaum gehalten, oft ein Leben lang. Die',
  'Medikamente sind gut — und die Lebensstil-Änderung, die denselben',
  'Wert oft ohne Pille erreichen kann, wird nicht verordnet, weil',
  'niemand sie verschreiben kann. Die Bilanz, die der Betreiber',
  'dieses Buches aufgemacht hat, stimmt: Die Diagnose ist stark —',
  'die Bildgebung, die Labore, die Früherkennung sind Wunder der',
  'Medizin. Die Behandlung der chronischen Krankheiten ist schwach —',
  'weil die einfache Antwort (Bewegung, Ernährung, Gemeinschaft,',
  'weniger Stress) keine Lobby hat, keinen Preis, keine Fabrik.',
  '',
  '## Gegenanzeigen: die einfache Medizin',
  '',
  'Und damit ist die Gegenanzeige dieses Beipackzettels benannt: die',
  'einfache Medizin, von der dieses Buch am Ende handeln wird. Die',
  'drei Dinge, die bei chronischen Krankheiten am meisten helfen,',
  'haben keine Werbung, keine Vertreter, keine Kongresse: Bewegung,',
  'gutes Essen, ein Leben mit weniger Druck. Sie wirken — und sie',
  'sind unbequem, weil sie von jedem selbst getan werden müssen und',
  'weil niemand daran verdient. Die Industrie kann dafür nichts; die',
  'Gesellschaft, die alles dem Markt überlässt, schon. Wer die',
  'einfache Medizin verschreibt, verschreibt etwas, das es nicht zu',
  'kaufen gibt.',
  '',
  '## Antwort an die Industrie',
  '',
  'Die Industrie hat ihre Packung vorgelegt und ihre ehrlichen',
  'Stellen benannt. Diese Stimme antwortet: Die Erfolge sind echt —',
  'die Medikamente, die Leben retten, die HIV-Wende, das Insulin,',
  'die Impfstoffe. Niemand hier will die Industrie abschaffen; wer',
  'das wollte, müsste auch die Rettung abschaffen. Aber die Rechnung',
  'muss vollständig sein: Das Geschäft braucht die Krankheit, die',
  'Forschung folgt dem Markt, die verschwundenen Studien verzerren',
  'das Wissen, und die einfache Medizin hat keine Lobby. Die Frage,',
  'die dieser Beipackzettel hinterlässt, ist die Frage des ganzen',
  'Buches: Wem dient die Medizin — dem Kranken oder dem Markt? Und',
  'wer entscheidet, was gezahlt wird: der Bedarf oder der Gewinn?',
  'Die Synthese muss diese Rechnung führen — mit beiden Seiten.',
].join('\n');

/**
 * Kapitel 14 — „Die moderne Pharmaindustrie".
 *
 * Runde 15 legt das Modul mit der ersten Perspektive an (die Industrie von
 * innen, als Beipackzettel ihrer selbst). Die zweite Stimme (die Kritik) und
 * die endgültige Synthese ergänzt Hermes im zweiten Pass.
 */
const pharmaindustrie = {
  id: 'pharmaindustrie',
  titel: 'Die moderne Pharmaindustrie',
  epoche: '20. Jahrhundert bis heute',

  aufhaenger: {
    frage: 'Was kostet ein Leben — und wer bestimmt den Preis?',
    text: [
      'Ein Kind mit Diabetes starb im Jahr 1920 mit ziemlicher Sicherheit,',
      'meist binnen eines Jahres. Zwei Jahre später gab es das Insulin, und',
      'die Entdecker verkauften das Patent für einen einzigen Dollar, damit',
      'niemand an einem lebensrettenden Stoff verdienen sollte. Hundert Jahre',
      'später rationierten Menschen in den Vereinigten Staaten dasselbe Mittel,',
      'weil sie es nicht bezahlen konnten. Beides ist die Geschichte derselben',
      'Industrie.',
      '',
      'Die Pharmaindustrie ist eines der größten Geschäfte der Welt — rund',
      'anderthalb Billionen Dollar Umsatz im Jahr. Und sie ist eines der',
      'größten Wunder: Sie hat Krankheiten beendet, die vor hundert Jahren',
      'Todesurteile waren. Beides stimmt gleichzeitig, und darin liegt die',
      'Schwierigkeit dieses Kapitels.',
      '',
      'Es fragt, wie aus einer Apotheke in Darmstadt und zwei Farbenfabriken',
      'an Wupper und Main ein System wurde, das Leben rettet und Geld',
      'verdient — oft im selben Atemzug. Warum ein neues Medikament zehn bis',
      'fünfzehn Jahre und Milliarden kostet. Warum es fast immer eine Tablette',
      'ist und fast nie ein Rat. Warum die Mittel, die man jahrzehntelang',
      'nimmt, das beste Geschäft sind — und ein Mittel, das heilt, das',
      'schlechteste. Und warum die Bilanz so ungleich ausfällt: stark in der',
      'Diagnose, schwach bei den chronischen Krankheiten.',
      '',
      'Dazwischen liegen die dunklen Stellen, die zu dieser Geschichte gehören',
      'wie die hellen: das Heroin, das dreiundzwanzig Jahre lang als',
      'Hustenmittel verkauft wurde, und die Contergan-Katastrophe, an der die',
      'Regeln geschrieben sind, die uns heute schützen.',
    ].join('\n'),
  },

  karte,

  perspektiven: [
    {
      id: 'industrie',
      name: 'Die Stimme der Industrie',
      stimme: 'Opus',
      text: stimmeDerIndustrie,
    },
    {
      id: 'kritik',
      name: 'Die Stimme der Kritik',
      stimme: 'Hermes',
      text: stimmeDerKritik,
    },
  ],

  synthese: [
    '## Wo sich beide Zettel treffen',
    '',
    'Zuerst das Gemeinsame — und es ist größer, als die Schlagzeilen',
    'beider Seiten vermuten lassen. Die Industrie und die Kritik',
    'benennen dieselben Tatsachen: die Erfolge (Insulin, Antibiotika,',
    'die HIV-Wende, die Impfstoffe — die Rettung von Millionen), die',
    'Katastrophen (die Zeit ohne Prüfung, Contergan — die Regeln, die',
    'daraus entstanden), das Geschäft mit dem Immer-wieder (die',
    'Dauermedikamente), das Marketing, das die Grenze überschritt, und',
    'die magere Bilanz bei den chronischen Krankheiten. Die eine',
    'Stimme nennt es die ehrliche Selbstprüfung, die andere die',
    'halbierte Rechnung — aber beide stehen vor denselben Zahlen. Und',
    'beide wissen: Die Medikamente sind nicht das Problem. Das',
    'Geschäft ist nicht das Problem. Die Frage ist, wem das System',
    'dient, wenn beides zusammenkommt.',
    '',
    '## Wo sie auseinandergehen',
    '',
    'Der Widerspruch beginnt bei der Deutung des Geschäfts. Die',
    'Industrie sagt: Der Preis ist der Preis der Forschung — ohne',
    'Gewinn keine Entwicklung, ohne Entwicklung keine Rettung. Die',
    'Kritik sagt: Der Preis ist auch der Preis des Marktes — die',
    'Forschung folgt dem Profit, das Marketing übertrifft die',
    'Forschung, die verschwundenen Studien verzerren das Wissen, und',
    'wer kritisch forscht, verliert die Mittel. Die Industrie sieht im',
    'Kranken den Kunden, der versorgt wird; die Kritik sieht den',
    'Kunden, der gebraucht wird, damit das Geschäft läuft. Sie',
    'streiten nicht über einzelne Medikamente — die sind gut —,',
    'sondern über die Frage, ob ein System, das von der Krankheit',
    'lebt, die Gesundheit wirklich will. Und sie streiten über die',
    'einfache Medizin: Die Industrie sagt, sie sei Sache des',
    'Einzelnen; die Kritik sagt, sie sei die Wahrheit, die keine',
    'Lobby hat.',
    '',
    '## Was dieses Kapitel für das ganze Buch zeigt',
    '',
    'Zum fünfzehnten Mal dasselbe Muster — und jetzt wird es zur',
    'Bewährungsprobe: Die Denkart bestimmt die Methode. Die Denkart',
    'der Pille — die Krankheit als chemisches Problem, die Tablette',
    'als Antwort — hat die Medizin verwandelt und Millionen gerettet.',
    'Sie hat aber auch die Grenze dieser Denkart sichtbar gemacht: Sie',
    'sieht den Molekül, nicht den Menschen; sie heilt das Symptom,',
    'nicht das Leben; sie verwaltet die chronische Krankheit, statt',
    'sie zu verhindern. Der Innovations-Zyklus dieses Buches gilt auch',
    'hier: Das Neue schadete zuerst (Cocain, Heroin, Contergan), bevor',
    'es segensreich wurde — und die Prüfung, die es rettete, kam erst',
    'nach der Katastrophe.',
    '',
    'Und dieses Kapitel stellt die Frage, die zum Ende des Buches',
    'führt: Wem dient die Medizin — dem Kranken oder dem Markt? Die',
    'Antwort liegt nicht in der Abschaffung der Industrie, sondern in',
    'der Erinnerung daran, was die Medizin ist: ein Dienst am',
    'Menschen, der sich nicht rechnen muss. Die nächsten Kapitel',
    'werden zeigen, was geschieht, wenn dieser Dienst zum Geschäft',
    'wird — und was geschieht, wenn Menschen sich dagegen wehren: die',
    'Impfdebatte, die Naturheilkunde, die einfache Medizin. Und am',
    'Ende die Frage, ob ein Miteinander möglich ist zwischen der',
    'Pille und dem Rat, zwischen dem Markt und dem Menschen.',
  ].join('\n'),

  urteil: {
    frage:
      'Was ist Dir mehr wert — ein Medikament, das Dein Leben rettet, oder ' +
      'ein System, das Du durchschaust? Und darf beides dasselbe kosten?',
    hinweis: [
      'Es gibt hier kein Richtig und kein Falsch. Nimm Dir die beiden Hälften',
      'dieses Kapitels vor. Die eine: Ohne diese Industrie gäbe es kein',
      'Insulin, keine Antibiotika, keine HIV-Therapie — und Millionen Menschen',
      'wären nicht so alt geworden, wie sie geworden sind. Die andere: Ein',
      'Gewerbe, das an der Dauer einer Krankheit verdient, hat kein Interesse',
      'an ihrem Ende, und ein Heilmittel verbraucht seinen eigenen Markt. Frag',
      'Dich dreierlei. Erstens: Wer soll die zehn bis fünfzehn Jahre Forschung',
      'bezahlen, wenn nicht der spätere Preis — der Staat, die Kasse, eine',
      'Stiftung, alle zusammen? Zweitens: Wer soll entscheiden, woran geforscht',
      'wird, wenn nicht der Markt — und wer entscheidet dann? Drittens: Was',
      'ändert sich an Deiner Antwort, wenn es um ein Mittel geht, das Du selbst',
      'brauchst? Genau zwischen diesen Fragen liegt der Streit, der seit',
      'hundert Jahren nicht entschieden ist.',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Stimmt es, dass „Heroin" einmal ein ganz normal verkäufliches ' +
        'Hustenmittel war?',
      antworten: [
        'Nein, es war von Anfang an verboten.',
        'Ja — es wurde ab 1898 als Hustenmittel vermarktet und ausdrücklich ' +
          'als nicht gewöhnungsbildend beworben.',
        'Ja, aber nur in Amerika und nur für Erwachsene.',
      ],
      richtig: 1,
      erklaerung:
        'Am 10. August 1897 stellte Felix Hoffmann in Elberfeld ' +
        'Acetylsalicylsäure her (ab 1899 als Aspirin verkauft) und elf Tage ' +
        'später Diacetylmorphin. Ab 1898 kam es unter dem Namen „Heroin" auf ' +
        'den Markt, als Hustenmittel und als angeblich unbedenklicher Ersatz ' +
        'für Morphin, und wurde in über zwanzig Länder ausgeführt. 1913 endete ' +
        'die Herstellung, 1924 verboten es die USA, 1931 wurde es in ' +
        'Deutschland stark beschränkt — es gab damals keine Zulassungsprüfung.',
    },
    {
      frage:
        'Was änderte die Contergan-Katastrophe von 1957 bis 1961 an der ' +
        'Arzneimittelprüfung?',
      antworten: [
        'Nichts — die Regeln bestanden schon vorher.',
        'Nur die Werbung für Schlafmittel wurde verboten.',
        'Erst danach wurden Wirksamkeits- und Unbedenklichkeitsnachweis und ' +
          'die staatliche Zulassung zur Pflicht.',
      ],
      richtig: 2,
      erklaerung:
        'Contergan kam am 1. Oktober 1957 rezeptfrei auf den Markt, beworben ' +
        'als besonders verträglich auch für Schwangere. Nach der Warnung des ' +
        'Hamburger Kinderarztes Widukind Lenz wurde es am 26. November 1961 ' +
        'zurückgezogen; Schätzungen sprechen von 5.000 bis 10.000 ' +
        'geschädigten Kindern weltweit. 1962 verlangten die USA erstmals einen ' +
        'Wirksamkeitsnachweis in kontrollierten Studien; in Deutschland ' +
        'brachte erst das Arzneimittelgesetz von 1976 (in Kraft 1978) die ' +
        'echte Zulassung. In den USA hatte die Prüferin Frances Oldham Kelsey ' +
        'die Zulassung verweigert.',
    },
    {
      frage:
        'Wie lange dauert es heute im Durchschnitt, bis aus einem Wirkstoff ' +
        'ein zugelassenes Medikament wird?',
      antworten: [
        'Zehn bis fünfzehn Jahre — und etwa neun von zehn Kandidaten ' +
          'scheitern unterwegs.',
        'Ein bis zwei Jahre.',
        'Etwa dreißig Jahre.',
      ],
      richtig: 0,
      erklaerung:
        'Auf die Suche unter Zehntausenden Substanzen folgen die vorklinische ' +
        'Prüfung und drei Studienstufen am Menschen: Phase I (Verträglichkeit, ' +
        'meist Gesunde), Phase II (Wirkt es überhaupt?) und Phase III (Ist es ' +
        'besser als das Bekannte?). Von den Wirkstoffen, die bis zur ersten ' +
        'Prüfung am Menschen kommen, wird ungefähr jeder zehnte zugelassen — ' +
        'die meisten scheitern spät, wenn das Geld schon ausgegeben ist. Das ' +
        'ist die Begründung der Industrie für die hohen Preise; über die Höhe ' +
        'der Entwicklungskosten wird gestritten.',
    },
    {
      frage:
        'Was geschah 1996 in der Behandlung von HIV?',
      antworten: [
        'Ein Impfstoff wurde zugelassen.',
        'Die Kombinationstherapie aus mehreren Wirkstoffen setzte sich durch ' +
          'und machte aus einem Todesurteil eine behandelbare Krankheit.',
        'Die Krankheit galt als ausgerottet.',
      ],
      richtig: 1,
      erklaerung:
        'Mehrere Wirkstoffe gleichzeitig geben dem Virus kaum noch die ' +
        'Möglichkeit auszuweichen. Die Sterblichkeit brach in den behandelten ' +
        'Ländern binnen zwei Jahren ein; heute genügt oft eine Tablette am ' +
        'Tag, die Lebenserwartung liegt nahe der eines Nichtinfizierten, und ' +
        'wer erfolgreich behandelt wird, ist nicht mehr ansteckend. Einen ' +
        'Impfstoff gibt es bis heute nicht. Bis die Mittel in ärmeren Ländern ' +
        'ankamen, dauerte es weitere Jahre und einen Streit um Patente und ' +
        'Preise.',
    },
    {
      frage:
        'Für wie viel verkauften die Entdecker 1923 das Patent auf das ' +
        'Insulin?',
      antworten: [
        'Für eine Million Dollar.',
        'Sie meldeten gar kein Patent an.',
        'Für einen symbolischen Dollar, damit niemand an dem Stoff verdient.',
      ],
      richtig: 2,
      erklaerung:
        'Frederick Banting, Charles Best und James Collip überließen das ' +
        'Patent der Universität Toronto für je einen Dollar — ein ' +
        'lebensrettender Stoff sollte niemandem gehören. Hergestellt wurde er ' +
        'dennoch von Unternehmen: ab 1923 von Eli Lilly in Indianapolis, in ' +
        'Europa unter anderem in Lizenz von den Höchster Farbwerken. Hundert ' +
        'Jahre später war der Preis in den Vereinigten Staaten so hoch, dass ' +
        'Menschen ihre Dosis rationierten; erst öffentlicher Druck und ein ' +
        'Gesetz deckelten ihn.',
    },
  ],
};

module.exports = pharmaindustrie;
