// Kapitel 13 — „Die Verstaatlichung des Gesundheitswesens".
//
// Das fünfte Kapitel der Neuzeit und das erste, in dem nicht ein Forscher,
// sondern ein Gesetz die Hauptrolle spielt. Bis 1883 gab es am Krankenbett
// zwei Parteien: den Kranken und den, der ihn behandelte. Am 15. Juni 1883
// tritt eine dritte hinzu — der Staat. Er zahlt nicht selbst, aber er
// schreibt vor, dass gezahlt wird, von wem, wie viel und wofür. Aus dem
// Kranken wird ein Versicherter, aus dem Arzt ein Kassenarzt, aus der
// Behandlung ein Anspruch. Seitdem ist die Frage, wem die Gesundheit
// gehört, eine der größten Streitfragen der Gesellschaft.
//
// Die DENKART-Analyse ist das Herzstück (Betreiber-Vorgabe). Sie fragt
// hier: Warum überhaupt der Staat? (Weil die Industrialisierung die alten
// Netze zerrissen hat — wer in der Zechenkolonie krank wird, hat weder
// Land noch Sippe noch Zunft, sondern nur den ausbleibenden Lohn; und weil
// unzufriedene Massen die Ordnung bedrohen.) Warum eine Versicherung und
// keine Wohltätigkeit? (Weil Almosen abhängig machen und in Preußen sogar
// das Wahlrecht kosteten — die Versicherung schafft einen Rechtsanspruch,
// den man einklagen kann, ohne zu bitten.) Warum die Pflicht? (Weil die
// Freiwilligkeit die Gesunden fernhält und damit genau die Kasse leert,
// die den Kranken tragen soll.) Und die Kehrseite jeder dieser
// Begründungen: Wer zahlt, bestimmt mit; wer verwaltet, kontrolliert; wer
// zulässt, schließt aus.
//
// LÄNGENREGEL (Betreiber-Feedback 24.08.2026): Ab Kapitel 9 gilt die
// Umkehrung — vollständig und ausführlich. Ausführlich heißt nicht
// aufgebläht: jeder Absatz bringt die Erzählung voran. Gemessen wird in
// tests/karte-verstaatlichung.mjs.
//
// TONE-Regel: BEIDE Seiten fair. Diese erste Stimme zeigt den Segen der
// Sozialgesetze (der Zugang zum Arzt für alle, die Hygiene als
// Staatsaufgabe, die sinkende Sterblichkeit, das Vorbild für die Welt) UND
// benennt die unbequemen Stellen selbst: die politische Absicht neben dem
// Sozialistengesetz, die Kontrolle und die Bürokratie, den Kranken mit
// Nummer, die wirtschaftliche Verdrängung der Naturheilkunde — und das,
// was ein späterer Staat mit demselben Werkzeug angerichtet hat.
//
// KEINE GERÜCHTE (Betreiber-Entscheid 25.08.2026): Nur Belegtes. Zwei
// Wendungen, die Bismarck gern zugeschrieben werden, stehen so in keinem
// Protokoll; der Text sagt das ausdrücklich und stellt die aktenkundigen
// Sätze daneben.
//
// DER INNOVATIONS-ZYKLUS (Betreiber-Beobachtung 26.08.2026, roter Faden):
// Auch eine Einrichtung ist eine Erfindung. Der Sozialstaat hat Millionen
// geholfen — und dem Staat ein Werkzeug in die Hand gegeben, das ein
// späterer Staat gegen die Menschen gedreht hat. Die Stimme benennt das
// selbst.
//
// Stimmen (Runde 14): Die ERSTE Perspektive — der Staat von innen, die
// Akte des Reichskanzleramts — verfasste Opus. Die ZWEITE (die
// Versicherten und die Verdrängten: die Arbeiter mit der Kassenkarte, die
// neue Sicherheit und die neue Abhängigkeit; die Heilpraktiker,
// Kräuterfrauen und Bader, denen die Kassen die Grundlage entzogen) und
// die finale Synthese ergänzte Hermes im zweiten Pass. Perspektiven-
// Workflow: CLAUDE.md.
//
// KEINE WIEDERHOLUNGEN (Betreiber-Entscheid vom 21.08.2026): Kapitel 1
// gliedert nach „Wer hier spricht", Kapitel 2 beginnt mit einer Szene,
// Kapitel 3 erzählt einen Tageslauf, Kapitel 4 ist ein Briefwechsel,
// Kapitel 5 die Reise eines Buches, Kapitel 6 ein Rundgang, Kapitel 7 ein
// Prozess, Kapitel 8 eine Rechnung, Kapitel 9 eine Uhr, Kapitel 10 eine
// Kette, Kapitel 11 eine Linse, Kapitel 12 ein Interview. Dieses Kapitel
// wählt die vierzehnte Dramaturgie: DIE AKTE. Der Staat spricht so, wie er
// wirklich spricht — in Blättern, Vorgängen, Paragraphen und
// Randbemerkungen. Die zweite Stimme kann in dieselbe Form treten: die
// andere Akte, die Versichertenakte, in der derselbe Vorgang von unten
// aussieht.
//
// Die Texte liegen als Zeilen-Arrays mit `.join('\n')` — so bleiben sie im
// Repo bei ~72 Zeichen lesbar (der Betreiber liest sie hier gegen), und
// utils/markdown.js macht in der App wieder fließenden Text daraus.
//
// CommonJS ohne UI-Importe (Architektur-Regel): mit blankem `node` prüfbar.

const { karte } = require('./karten/verstaatlichung');

/**
 * Die Stimme des Staates — die Akte des Reichskanzleramts.
 *
 * Verfasst von Opus (Runde 14). Eine Stimme, die für die Seite spricht, die
 * die Gesetze gemacht hat: ihre Lage, ihre Rechnung, ihre Absicht. Sie
 * erzählt, warum sie tat, was sie tat — und sie benennt die unbequemen
 * Stellen selbst (Zusatzregel für sensible Themen in CLAUDE.md).
 */
const stimmeDesStaates = [
  '## Die Akte, die im Reichskanzleramt liegt',
  '',
  'Ein Staat denkt nicht in Erzählungen. Er denkt in Vorgängen. Was ihn',
  'beschäftigt, bekommt eine Nummer, einen Umschlag und eine Reihenfolge;',
  'wer später wissen will, warum etwas geschah, schlägt die Blätter auf',
  'und liest von hinten nach vorn.',
  '',
  'Dieses Kapitel ist eine solche Akte. Sie trägt den Titel „Die soziale',
  'Frage" und liegt zwischen 1871 und 1911 im Reichskanzleramt zu Berlin.',
  'Sie enthält Berichte aus den Zechen, Zeitungsausschnitte,',
  'Gesetzentwürfe, Sitzungsprotokolle, Beitragstabellen, Beschwerden von',
  'Ärzten, Eingaben von Vereinen — und ein paar Zettel, die eigentlich',
  'nicht hineingehören.',
  '',
  '**Was Du hier liest, ist die Sicht des Staates auf sich selbst — eine',
  'Denkart, keine Wahrheit.** Der Staat hat sich in diesen Jahren für den',
  'Beschützer der Schwachen gehalten, und er hatte Gründe dafür. Er hat',
  'sich gleichzeitig für den Hüter der Ordnung gehalten und hatte auch',
  'dafür Gründe. Beides steht in derselben Akte, oft auf demselben Blatt.',
  '',
  'Zwei Sätze, die dem Reichskanzler gern in den Mund gelegt werden,',
  'stehen so in keinem Protokoll: dass das soziale Elend die schärfste',
  'Waffe der Sozialdemokratie sei, und dass der Staat den Arbeiter so',
  'behandeln müsse, dass dieser ihn liebe. Sie treffen den Sinn der Sache,',
  'aber sie sind nicht aktenkundig. **Wo etwas nur überliefert ist und',
  'sich nicht belegen lässt, sage ich es dazu.** Die Sätze, die wirklich',
  'gefallen sind, stehen weiter unten, und sie sind deutlich genug.',
  '',
  '## Blatt 1: Der Befund — was die Fabrik mit den Menschen macht',
  '',
  'Das erste Blatt ist kein Gesetz, sondern eine Beschreibung. Ohne sie',
  'ergibt der Rest der Akte keinen Sinn.',
  '',
  'Nach der Reichsgründung von 1871 wächst das Land schneller, als',
  'irgendjemand es einrichten kann. Die Bevölkerung steigt von rund',
  'einundvierzig Millionen auf fünfundsechzig Millionen im Jahr 1910. Vor',
  'allem aber wandert sie: 1871 lebt gut ein Drittel der Menschen in',
  'Städten, 1910 sind es rund zwei Drittel. Berlin wächst von etwa',
  'achthundertzwanzigtausend Einwohnern auf über anderthalb Millionen. Ins',
  'Ruhrrevier kommen aus Ostpreußen, Masuren, Posen und Schlesien mehrere',
  'Hunderttausend.',
  '',
  'Diese Zahlen sind der eigentliche Vorgang. **Denn ein Mensch, der vom',
  'Dorf in die Zechenkolonie zieht, verliert nicht nur seine Heimat. Er',
  'verliert sein ganzes Sicherungsnetz auf einmal.**',
  '',
  'Auf dem Land war der Kranke nie allein. Es gab ein Stück Acker, das',
  'weiterlief; eine Großfamilie, die einsprang; einen Pfarrer, eine',
  'Gemeinde, einen Gutsherrn mit einer wie auch immer gearteten Pflicht;',
  'eine Zunft mit ihrer Lade, aus der die Witwe des Meisters etwas bekam;',
  'ein Kräuterwissen im Haus und eine Heilkundige im Ort. Das war weder',
  'gerecht noch zuverlässig — aber es war da.',
  '',
  'In der Mietskaserne ist nichts davon mehr da. In der Berliner',
  'Ackerstraße steht seit 1874 ein Haus mit sechs Hinterhöfen, in dem über',
  'tausend Menschen wohnen. Wer selbst dafür kein Geld hat, wird',
  '**Schlafgänger**: Er mietet nicht eine Wohnung, nicht ein Zimmer,',
  'sondern ein Bett — und zwar stundenweise, weil im selben Bett vor ihm',
  'die Nachtschicht geschlafen hat. Die Kinder sterben in den Hinterhöfen',
  'an Durchfall, Masern, Diphtherie und Tuberkulose. Um 1900 stirbt im',
  'Reich rund jedes fünfte Kind im ersten Lebensjahr.',
  '',
  'Und wer arbeitet, arbeitet gefährlich. Unter Tage bricht ein Stollen',
  'ein, in der Hütte kippt flüssiges Eisen, an der Maschine reißt ein',
  'Riemen. Bis 1884 hat der Verunglückte genau einen Weg: Er verklagt den',
  'Unternehmer und muss ihm ein **Verschulden nachweisen**. Ein Bergmann',
  'ohne Bein und ohne Geld, der einem Zechenbesitzer vor Gericht',
  'Fahrlässigkeit beweisen soll — das ist kein Rechtsweg, das ist ein',
  'Hohn.',
  '',
  'Bleibt die Armenpflege der Gemeinde. Die gibt es, und sie hat einen',
  'Preis, der heute schwer zu glauben ist: **Wer in Preußen',
  'Armenunterstützung bezog, verlor sein Wahlrecht.** Er wurde',
  'aktenkundig, er wurde besichtigt, er wurde als Almosenempfänger',
  'geführt. Deshalb gingen die Menschen nicht hin, solange sie noch',
  'kriechen konnten.',
  '',
  '**Warum überhaupt der Staat?** Hier ist die Antwort, und sie hat zwei',
  'Hälften, die beide wahr sind.',
  '',
  'Die erste Hälfte: **Weil sonst niemand mehr da ist.** Die',
  'Industrialisierung hat die alten Netze nicht beschädigt, sie hat sie',
  'zerschnitten. Familie, Zunft, Dorf, Grundherr — alles, was den Kranken',
  'jahrhundertelang getragen hat, liegt vierhundert Kilometer entfernt.',
  'Übrig bleiben Lohn und Miete. Und der Lohn hört in dem Augenblick auf,',
  'in dem der Mensch ihn am dringendsten braucht.',
  '',
  'Die zweite Hälfte: **Weil eine unzufriedene Masse gefährlich ist.** Ich',
  'beschönige das nicht. Millionen Menschen, die nichts zu verlieren',
  'haben, in Städten zusammengedrängt, lesend, organisiert, wütend — das',
  'ist für jede Regierung eine Frage der Sicherheit, nicht des',
  'Mitgefühls. Wer die Akte ehrlich liest, findet beide Motive auf',
  'demselben Blatt, und er wird sie nicht sauber trennen können.',
  '',
  '## Blatt 2: Die Peitsche — das Sozialistengesetz vom 21. Oktober 1878',
  '',
  'Das nächste Blatt ist das unangenehmste der ganzen Akte, und es kommt',
  'in den Erzählungen über den Sozialstaat meistens nicht vor. Es gehört',
  'aber an diese Stelle, denn es kam zuerst.',
  '',
  'Im Jahr 1878 wird zweimal auf Kaiser Wilhelm I. geschossen: am 11. Mai',
  'von einem Klempnergesellen namens Max Hödel, am 2. Juni von einem',
  'Doktor der Nationalökonomie namens Karl Nobiling; der Kaiser wird schwer',
  'verletzt. **Keiner der beiden gehörte der sozialdemokratischen Partei',
  'an** — Hödel war aus ihr ausgeschlossen worden, Nobiling war nie',
  'Mitglied. Das ist aktenkundig, und es hat die Regierung nicht',
  'aufgehalten.',
  '',
  'Am 21. Oktober 1878 beschließt der Reichstag das „Gesetz gegen die',
  'gemeingefährlichen Bestrebungen der Sozialdemokratie". Verboten werden',
  'Vereine, Versammlungen, Zeitungen, Schriften, Sammlungen. Über',
  'einzelne Orte wird der Belagerungszustand verhängt; rund neunhundert',
  'Menschen werden ausgewiesen, weit über tausend zu Haftstrafen',
  'verurteilt. Das Gesetz wird viermal verlängert und läuft erst am',
  '30. September 1890 aus.',
  '',
  'Eine Lücke blieb: **Kandidieren durfte man weiter.** Weil das',
  'Wahlrecht nicht angetastet wurde, saßen sozialdemokratische',
  'Abgeordnete während der ganzen zwölf Jahre im Reichstag. Sie waren',
  'verboten und gewählt zugleich.',
  '',
  'Warum steht dieses Blatt in einer Akte über das Gesundheitswesen? Weil',
  'die Sozialgesetze ohne es nicht zu verstehen sind. **Die Regierung hat',
  'nicht zuerst geholfen und dann verboten. Sie hat zuerst verboten und',
  'dann geholfen** — und sie hat beides als ein einziges Vorgehen',
  'betrachtet. Die Nachwelt nennt es Zuckerbrot und Peitsche. Die Akte',
  'nennt es Ordnung und Fürsorge. Gemeint ist dasselbe.',
  '',
  '## Blatt 3: Das Zuckerbrot — die Kaiserliche Botschaft vom 17. November 1881',
  '',
  'Drei Jahre nach dem Verbot verliest der Reichskanzler im Reichstag eine',
  'Botschaft des Kaisers. Sie ist der Gründungstext des deutschen',
  'Sozialstaats, und ihr Kernsatz sagt die Absicht so offen, dass man ihn',
  'nicht ausdeuten muss. Er lautet, dass die Heilung der sozialen Schäden',
  '**„nicht ausschließlich im Wege der Repression sozialdemokratischer',
  'Ausschreitungen, sondern gleichmäßig auf dem der positiven Förderung',
  'des Wohles der Arbeiter zu suchen sein werde"**.',
  '',
  'Man lese das langsam. Es steht nicht da: Wir haben uns geirrt, das',
  'Verbot war falsch. Es steht da: Das Verbot allein genügt nicht, wir',
  'brauchen zusätzlich das andere. Die Botschaft kündigt an, was daraus',
  'werden soll: eine Versicherung gegen Krankheit, eine gegen Unfall, eine',
  'für das Alter und die Invalidität.',
  '',
  'Und drei Jahre später, am 9. Mai 1884, sagt der Kanzler im Reichstag',
  'einen Satz, der noch weniger Auslegung braucht: **„Wenn es keine',
  'Sozialdemokratie gäbe und wenn nicht eine Menge Leute sich vor ihr',
  'fürchteten, würden die mäßigen Fortschritte, die wir überhaupt in der',
  'Sozialreform bisher gemacht haben, auch noch nicht existieren."**',
  '',
  'Sein Vertrauter Moritz Busch hat aufgezeichnet, wie er es im',
  'Privatgespräch formulierte: Sein Gedanke sei gewesen, die arbeitenden',
  'Klassen zu gewinnen — oder solle er sagen: zu bestechen —, den Staat',
  'als eine soziale Einrichtung anzusehen, die ihretwegen bestehe und für',
  'ihr Wohl sorgen wolle. **Diese Fassung ist keine Rede, sondern eine',
  'Aufzeichnung aus zweiter Hand; sie ist als solche gekennzeichnet.** Am',
  'Befund ändert sie nichts.',
  '',
  'Es wäre bequem, daraus zu schließen: also war alles nur Berechnung.',
  'Die Akte gibt das nicht her. Ein Gesetz, das aus Berechnung entsteht,',
  'wirkt darum nicht weniger. Der Bergmann, dessen gebrochenes Bein 1886',
  'auf Kosten der Kasse geschient wird, hat keinen Nutzen davon zu wissen,',
  'aus welchem Motiv der Paragraph geschrieben wurde. **Die Frage ist',
  'nicht, ob die Absicht rein war. Die Frage ist, was das Gesetz getan',
  'hat.**',
  '',
  '## Blatt 4: Die Denkart — aus Almosen wird Anspruch',
  '',
  'Jetzt kommt das Blatt, auf das es ankommt. Denn die eigentliche',
  'Neuerung von 1883 ist nicht das Geld. Es ist eine andere Art zu denken,',
  'was Hilfe überhaupt ist.',
  '',
  'Bis dahin kannte Europa zwei Formen: die **Wohltätigkeit** und die',
  '**Selbsthilfe**. Die Wohltätigkeit war das Almosen — der Stiftungsfonds,',
  'die Klosterpforte, das Krankenhaus als milde Stiftung, die Armenkasse',
  'der Gemeinde. Sie half unregelmäßig, sie half nach Ansehen der Person,',
  'und sie half von oben herab. Die Selbsthilfe war die Lade, die Kasse,',
  'die Bruderschaft: die Bergleute mit ihren jahrhundertealten',
  '**Knappschaften**, die Handwerksgesellen mit ihren Zunftkassen, später',
  'die freien Hilfskassen der Arbeitervereine. Sie half gerechter, aber sie',
  'reichte nur so weit wie die Gruppe.',
  '',
  '**Warum eine Versicherung und keine Wohltätigkeit?** Weil die',
  'Wohltätigkeit den Menschen zum Bittsteller macht und die Versicherung',
  'ihn zum Berechtigten. Das ist der ganze Unterschied, und er ist',
  'gewaltig.',
  '',
  'Wer ein Almosen empfängt, muss darum bitten, muss würdig erscheinen,',
  'muss sich besichtigen lassen — und büßt in Preußen sogar sein Wahlrecht',
  'ein. Wer versichert ist, hat einen **Rechtsanspruch**. Er bittet nicht,',
  'er fordert. Er kann sich beschweren, und er kann klagen. Er muss nicht',
  'dankbar sein. **Aus einer Gnade wird ein Recht — und wer ein Recht hat,',
  'muss den Kopf nicht senken.** Genau darum hat der Staat dieses Modell',
  'gewählt und nicht die Aufstockung der Armenkassen, die billiger gewesen',
  'wäre.',
  '',
  'Die Rechnung dahinter ist einfach und uralt; die Kaufleute der Hanse',
  'kannten sie für ihre Schiffe. **Viele zahlen wenig, damit der Einzelne',
  'im Unglück viel bekommt.** Niemand weiß vorher, wen es trifft. Zahlen',
  'alle, kann jeder getragen werden. Das ist keine Umverteilung von Reich',
  'zu Arm — die Beiträge kamen aus denselben schmalen Löhnen. Es ist eine',
  'Umverteilung **von den Gesunden zu den Kranken und von den guten Jahren',
  'in die schlechten.** Der Arbeiter versichert sich im Grunde bei seinem',
  'eigenen künftigen Unglück.',
  '',
  'Und das führt zu der Formel, die die ganze Denkart trägt: **Gesundheit',
  'ist kein Geschäft und keine Gnade, sondern eine Angelegenheit des',
  'Gemeinwesens.** Ob jemand behandelt wird, soll nicht davon abhängen,',
  'wie viel er in der Tasche hat.',
  '',
  'Diese Formel hat eine Kehrseite, und ich nenne sie sofort, damit sie',
  'nicht später wie ein Vorwurf klingt: **Wer zahlt, bestimmt mit.** Wenn',
  'die Allgemeinheit die Behandlung trägt, dann bekommt die Allgemeinheit',
  'ein Wort darüber, was behandelt wird, von wem, wie lange und zu welchem',
  'Preis. Dieser Satz steht 1883 in keinem Paragraphen. Er ist trotzdem',
  'von Anfang an im Gesetz enthalten, so wie der Baum im Kern enthalten',
  'ist.',
  '',
  '## Blatt 5: Der Zwang — warum die Pflicht und nicht die Freiwilligkeit',
  '',
  'Ein Einwand kam sofort, und er kam von den Liberalen: Warum Zwang?',
  'Lasst die Leute doch selbst entscheiden, ob sie sich versichern. Es',
  'gibt Hilfskassen, es gibt Vereine, es gibt Sparbücher. Der Staat soll',
  'nicht in den Lohnbeutel greifen.',
  '',
  'Die Antwort steht in den Erfahrungen mit eben diesen freien',
  'Hilfskassen, und sie ist nüchtern: **Die Freiwilligkeit versagt genau',
  'da, wo sie gebraucht wird.**',
  '',
  'Wer jung, kräftig und gesund ist, tritt nicht bei. Er hat andere',
  'Verwendung für seine Groschen und fühlt sich unverwundbar. Wer alt,',
  'schwach oder chronisch krank ist, tritt bei, sobald er kann. Damit',
  'sammelt eine freiwillige Kasse genau die Menschen, die viel kosten, und',
  'verliert die, die tragen könnten. Sie muss die Beiträge erhöhen,',
  'woraufhin die verbliebenen Gesunden austreten, woraufhin sie die',
  'Beiträge wieder erhöhen muss. Am Ende steht eine teure Kasse für arme',
  'Kranke — oder gar keine.',
  '',
  'Dazu kommt der Wechsel des Arbeitsplatzes. Die Hilfskassen hingen an',
  'Betrieb, Ort oder Verein; wer weiterzog, verlor seine Anwartschaft und',
  'fing von vorn an. In einem Land, in dem Millionen umzogen, war das ein',
  'Konstruktionsfehler.',
  '',
  'Deshalb die Pflicht. **Die Pflicht ist nicht der Gegensatz zur',
  'Solidarität, sie ist ihre Voraussetzung** — solidarisch ist eine Kasse',
  'nur, wenn auch die drin sind, die sie im Augenblick nicht brauchen.',
  '',
  'Und auch hier gehört die Kehrseite auf dasselbe Blatt: **Pflicht heißt',
  'Zwang.** Von 1883 an ist ein Teil des Lohns kein Lohn mehr; er wird',
  'einbehalten, bevor der Arbeiter ihn in die Hand bekommt, und über seine',
  'Verwendung entscheiden andere. Wer sagt, das sei eine Bevormundung, hat',
  'in der Sache recht — er sagt nur nicht dazu, was die Alternative war.',
  '',
  '## Blatt 6: Das Gesetz vom 15. Juni 1883 — was wirklich darin steht',
  '',
  'Nun der Vorgang selbst. Am 15. Juni 1883 wird das',
  'Krankenversicherungsgesetz beschlossen; am 1. Dezember 1884 tritt es in',
  'Kraft. Es ist das erste Gesetz dieser Art auf der Welt.',
  '',
  '**Wer ist versichert?** Zunächst gewerbliche Arbeiter in Fabriken,',
  'Bergwerken, Hütten, Werkstätten und beim Bau, unterhalb einer',
  'Verdienstgrenze. Das sind 1885 rund **4,3 Millionen Menschen** — etwa',
  'jeder zehnte Einwohner des Reiches. Landarbeiter, Dienstboten,',
  'Heimarbeiter und die Ehefrauen bleiben zunächst draußen. Die',
  'Ausdehnung auf sie dauert dreißig Jahre.',
  '',
  '**Wer zahlt?** Der Beitrag beträgt bis zu drei Prozent des',
  'ortsüblichen Tagelohns. Davon trägt der **Arbeiter zwei Drittel, der',
  'Arbeitgeber ein Drittel**. Der Arbeiter zahlt also rund zwei Prozent',
  'seines Lohnes, der Unternehmer noch einmal die Hälfte davon obendrauf.',
  'Das ist kein Nebendetail, sondern der Grund, warum die Wirtschaft nicht',
  'stärker Sturm lief — und der Grund für das, was gleich folgt.',
  '',
  '**Was bekommt man?** Freie ärztliche Behandlung und die Arznei vom',
  'ersten Tag an. Krankengeld ab dem dritten Tag in Höhe des halben',
  'ortsüblichen Tagelohns, für bis zu dreizehn Wochen. Dazu ein',
  'Sterbegeld und eine Unterstützung für Wöchnerinnen. **Für einen',
  'Fabrikarbeiter von 1884 ist der erste Punkt der ungeheuerlichste: Der',
  'Arzt kommt, und es kostet ihn nichts.** Vorher hat man den Arzt geholt,',
  'wenn es fast zu spät war, weil sein Besuch einen halben Wochenlohn',
  'kostete.',
  '',
  '**Wer verwaltet?** Nicht das Reich. Die Kassen bleiben selbständig:',
  'Ortskrankenkassen, Betriebskrankenkassen, Innungskrankenkassen, die',
  'alten Knappschaftskassen der Bergleute, eingeschriebene Hilfskassen. Es',
  'gibt Tausende davon, verschieden groß, verschieden gut. Und weil die',
  'Arbeiter zwei Drittel der Beiträge tragen, stellen sie zwei Drittel der',
  'Vertreter in den Kassenorganen.',
  '',
  '**Dieser eine Satz hat die Rechnung des Kanzlers verdorben.** Denn wo',
  'Arbeiter mehrheitlich wählen, verwalten und beschließen, entsteht ein',
  'öffentliches Amt für Leute, deren Partei gerade verboten ist. In den',
  'Kassen lernen Arbeiter Buchführung, Sitzungsleitung, Satzungen und',
  'Verhandlungen. Sie werden Kassenvorsteher, sie stellen Angestellte ein,',
  'sie beziffern Haushalte. Als das Sozialistengesetz 1890 fällt, steht',
  'eine geübte Organisation bereit. Die Sozialdemokratie wird 1890 nach',
  'Stimmen die stärkste Partei und 1912 die stärkste Fraktion des',
  'Reichstags. **Das Gesetz, das den Sozialismus aushungern sollte, hat',
  'ihm eine Schule gebaut.**',
  '',
  '## Blatt 7: Die beiden anderen Gesetze — 1884 und 1889',
  '',
  'Die Akte wird dicker. Am 6. Juli 1884 folgt das',
  '**Unfallversicherungsgesetz**, in Kraft ab Oktober 1885. Träger sind',
  'die Berufsgenossenschaften der Gewerbezweige, und diesmal zahlen die',
  'Arbeitgeber **allein**. Sie übernimmt, wo das Krankengeld nach dreizehn',
  'Wochen endet, und zahlt Renten an Verletzte und Hinterbliebene.',
  '',
  'Ihre wichtigste Neuerung steht nicht bei den Zahlen. Sie lautet: **kein',
  'Verschuldensnachweis mehr.** Es ist gleichgültig, ob der Steiger',
  'nachlässig war oder der Bergmann unvorsichtig; entschädigt wird der',
  'Unfall, nicht die Schuld. Dafür verliert der Verletzte den Klageweg',
  'gegen seinen Unternehmer. Beide Seiten haben etwas aufgegeben: Der',
  'Arbeiter den Prozess, den er ohnehin fast nie gewonnen hätte; der',
  'Unternehmer die Möglichkeit, mit einem guten Anwalt davonzukommen.',
  '',
  'Und weil die Arbeitgeber nun jeden Unfall bezahlen, bekommen sie zum',
  'ersten Mal ein handfestes Interesse daran, dass keiner geschieht. Die',
  'Genossenschaften erlassen **Unfallverhütungsvorschriften** und stellen',
  'technische Aufsichtsbeamte ein. So entsteht nebenbei etwas, das es in',
  'der Medizin bis dahin kaum gab: **Vorbeugung, die sich rechnet.**',
  '',
  'Am 22. Juni 1889 kommt das Gesetz über die **Invaliditäts- und',
  'Altersversicherung**, in Kraft ab 1891. Arbeiter und Arbeitgeber zahlen',
  'je die Hälfte, und das Reich legt auf jede laufende Rente fünfzig Mark',
  'im Jahr darauf. Zwei Fälle sind gedeckt: die dauernde',
  'Erwerbsunfähigkeit — die **Invalidenrente**, die in jedem Lebensalter',
  'greift — und das Erreichen des **siebzigsten Lebensjahres**.',
  '',
  'Über diese Siebzig wird bis heute gespottet, und der Spott hat einen',
  'wahren Kern: Die durchschnittliche Lebenserwartung bei der Geburt lag',
  'im Reich der 1880er Jahre bei etwa fünfunddreißig bis achtunddreißig',
  'Jahren. **Diese Zahl täuscht allerdings**, weil sie von der',
  'Kindersterblichkeit nach unten gezogen wird; wer das zwanzigste',
  'Lebensjahr erreichte, hatte gute Aussicht auf das sechzigste. Siebzig',
  'aber erreichte nur eine Minderheit. Das war den Verfassern bekannt, und',
  'es war einkalkuliert. Deshalb war die **Invalidenrente** in der Praxis',
  'der wichtigere Teil: Sie zahlte dem verbrauchten Fünfzigjährigen, dem',
  'Rücken und Lunge den Dienst versagten.',
  '',
  'Reich war davon niemand. Die Renten lagen bei etwa hundertzwanzig bis',
  'knapp zweihundert Mark im Jahr, während ein Industriearbeiter im Jahr',
  'sechs- bis achthundert Mark verdiente. **Das war ein Zuschuss, kein',
  'Auskommen** — gedacht als Ergänzung zu dem, was die Familie beisteuerte.',
  '',
  'Praktisch sah die Sache so aus: Jeder Versicherte bekam eine',
  '**Quittungskarte**, in die Woche für Woche eine **Beitragsmarke**',
  'geklebt wurde. Wer arbeitete, klebte Marken. Vierzig Jahre Arbeit',
  'wurden zu einem Stapel Karten, und was am Ende dabei herauskam, hing',
  'daran, dass diese Karten vollständig waren. Der Ausdruck „Marken',
  'kleben" für ein Arbeitsleben stammt von hier.',
  '',
  '## Blatt 8: Was der Kanzler nicht bekommen hat',
  '',
  'In den Erzählungen steht meistens, Bismarck habe den Sozialstaat',
  'gemacht. Die Akte zeigt einen Mann, der drei entscheidende',
  'Auseinandersetzungen verloren hat.',
  '',
  '**Erstens** wollte er eine große **Reichsversicherungsanstalt** —',
  'staatlich geführt, aus einer Hand. Der Reichstag wollte das nicht.',
  'Besonders die Zentrumspartei bestand darauf, dass die kleineren',
  'Gemeinschaften ihre Aufgaben behalten. Herausgekommen ist die',
  '**Selbstverwaltung**: Tausende eigenständiger Kassen und',
  'Berufsgenossenschaften unter staatlicher Aufsicht. Das deutsche',
  'Gesundheitswesen ist bis heute deshalb so unübersichtlich — und',
  'deshalb auch nie ganz in einer Hand.',
  '',
  '**Zweitens** wollte er einen kräftigen **Reichszuschuss**, finanziert',
  'unter anderem aus einem Tabakmonopol. Das Monopol scheiterte, der',
  'Zuschuss wurde bei der Unfallversicherung gestrichen und blieb bei der',
  'Rente auf fünfzig Mark je Rente begrenzt. Zwei Entwürfe zur',
  'Unfallversicherung fielen 1881 und 1882 durch, ehe der dritte 1884',
  'durchkam.',
  '',
  '**Drittens** wollte er die Zustimmung derer, um die es ging. Die',
  'sozialdemokratischen Abgeordneten stimmten gegen das',
  'Krankenversicherungsgesetz. Ihre Begründung: zu wenig, zu eng, und im',
  'Grunde ein Almosen, das von der eigentlichen Frage nach den',
  'Verhältnissen ablenken solle. Erst später erkannten sie, was die',
  'Selbstverwaltung ihnen bot, und ergriffen sie mit beiden Händen.',
  '',
  'Ich halte das fest, weil es die bequeme Geschichte zerstört: **Der',
  'Sozialstaat ist nicht der Entwurf eines Kanzlers, sondern das Ergebnis',
  'eines Streits, in dem niemand ganz bekam, was er wollte.** Genau',
  'deshalb hat er gehalten.',
  '',
  '## Blatt 9: Die Wirkungen — was aus den Zahlen wurde',
  '',
  '**Was Bestand hat.** Zuerst die Zahl, die alles andere trägt: Aus 4,3',
  'Millionen Versicherten im Jahr 1885 werden bis 1914 rund **sechzehn',
  'Millionen**. 1911 fasst die **Reichsversicherungsordnung** vom',
  '19. Juli alle drei Zweige in einem Gesetzbuch zusammen; im selben Jahr',
  'kommt die Angestelltenversicherung hinzu, und Landarbeiter und',
  'Dienstboten werden einbezogen. Aus einem Gesetz für Fabrikarbeiter ist',
  'ein System für ein Volk geworden.',
  '',
  'Dann die Lebenserwartung. Für die Jahre 1871 bis 1881 weist die',
  'Statistik bei der Geburt rund 35,6 Jahre für Männer und 38,5 für Frauen',
  'aus. Für 1901 bis 1910 sind es 44,8 und 48,3 Jahre. Für die Mitte der',
  '1920er Jahre 56,0 und 58,8. **In gut fünfzig Jahren gewinnt ein',
  'deutsches Leben im Durchschnitt zwanzig Jahre.**',
  '',
  '**Diese zwanzig Jahre gehören nicht der Kassenmedizin allein — der',
  'größere Teil gehört dem Wasser.** Das ist wichtig und wird in diesem',
  'Buch noch einmal gebraucht. Der Rückgang der großen',
  'Infektionskrankheiten hat vor allem mit Kanalisation, sauberem',
  'Trinkwasser, besserer Wohnung und besserer Ernährung zu tun, nicht mit',
  'Arzneien. München baute unter Max von Pettenkofer schon in den 1860er',
  'Jahren Kanalisation und Wasserleitung; Berlin begann 1873 nach den',
  'Plänen James Hobrechts, durchgesetzt von dem Stadtverordneten und',
  'Pathologen Rudolf Virchow.',
  '',
  'Der Beweis kam 1892 in **Hamburg**. Die Stadt nahm ihr Trinkwasser',
  'ungefiltert aus der Elbe; das unmittelbar angrenzende **Altona** ließ',
  'seines durch Sandfilter laufen. Als die Cholera kam, starben in Hamburg',
  'rund 8.600 Menschen, während Altona fast verschont blieb. An einzelnen',
  'Straßen lief die Stadtgrenze mitten durch die Häuserzeile: dieselben',
  'Menschen, dieselbe Luft, dieselbe Arbeit — zwei Wasserwerke, zwei',
  'Ergebnisse. Robert Koch kam und drängte auf Filtration.',
  '',
  '**Danach war die Frage entschieden.** Wasser, Abwasser und',
  'Seuchenabwehr waren keine Sache des guten Willens mehr, sondern eine',
  'Sache der Behörden; 1900 regelte ein Reichsgesetz die Bekämpfung',
  'gemeingefährlicher Krankheiten. Dazu kamen Wohnungsaufsicht,',
  'Gewerbeaufsicht, Schulärzte, Säuglingsfürsorge und Milchküchen. **Die',
  'Verstaatlichung des Gesundheitswesens war nicht in erster Linie eine',
  'Verstaatlichung der Ärzte. Sie war eine Verstaatlichung der',
  'Bedingungen, unter denen Menschen leben.**',
  '',
  'Und schließlich die Wirkung nach außen: Österreich führte 1887 und',
  '1888 nach, Ungarn 1891, andere folgten. 1908 reiste der britische',
  'Schatzkanzler David Lloyd George nach Deutschland, um sich das System',
  'anzusehen; 1911 beschloss das Vereinigte Königreich seinen National',
  'Insurance Act. **Von hier aus hat die Idee, dass ein Staat für die',
  'Gesundheit seiner Bürger einzustehen hat, die Welt erobert.**',
  '',
  '## Blatt 10: Der Preis — der Kranke bekommt eine Nummer',
  '',
  '**Was geschadet hat.** Jetzt die Blätter, die eine Behörde ungern',
  'vorlegt. Sie gehören dazu, denn sie sind kein Betriebsunfall, sondern',
  'die logische Fortsetzung derselben Denkart.',
  '',
  '**Erstens: Wer zahlt, kontrolliert.** Eine Kasse, die Krankengeld',
  'auszahlt, will wissen, ob wirklich jemand krank ist. Also stellt sie',
  '**Krankenkontrolleure** ein, die unangemeldet in der Wohnung',
  'erscheinen und nachsehen, ob der Kranke im Bett liegt. Aus dem',
  'Leidenden wird ein möglicher Simulant. Das war in den Kassenordnungen',
  'ausdrücklich vorgesehen, und es hat den Ton zwischen Versichertem und',
  'Kasse dauerhaft geprägt.',
  '',
  '**Zweitens: Aus dem Kranken wird ein Vorgang.** Jeder bekommt eine',
  'Mitgliedsnummer, eine Karte, einen Krankenschein. Behandlung geschieht',
  'nicht mehr, weil ein Mensch leidet, sondern weil ein',
  'Leistungstatbestand erfüllt ist. Das ist der Preis des Rechtsanspruchs,',
  'und er ist unvermeidlich: **Ein Anspruch muss nachprüfbar sein, sonst',
  'ist er keiner. Nachprüfbar aber ist nur, was sich in Formulare',
  'schreiben lässt.** Was sich nicht in Formulare schreiben lässt —',
  'Erschöpfung, Kummer, ein Leben, das nicht mehr trägt —, verschwindet',
  'aus der Akte, ohne aus der Welt zu verschwinden.',
  '',
  '**Drittens: Der Arzt bekommt einen Vertragspartner.** Vor 1883 hatte',
  'der Arzt einen Patienten, der ihn bezahlte. Danach hat er eine Kasse,',
  'die ihn bezahlt, und einen Patienten, den die Kasse schickt. Die Kassen',
  'schlossen Verträge mit einzelnen Ärzten, setzten die Honorare fest und',
  'entschieden, wer zugelassen wurde und wer nicht. Die Ärzteschaft wehrte',
  'sich: 1900 gründete sich in Leipzig der Verband, der später',
  'Hartmannbund hieß; es kam zu Boykotten und Streiks, bis 1913 das',
  '**Berliner Abkommen** einen reichsweiten Ärztestreik abwendete — mit',
  'einem festen Schlüssel von einem Kassenarzt je 1.350 Versicherte und',
  'gemeinsamen Ausschüssen. **Seit diesem Tag verhandeln in Deutschland',
  'Verbände darüber, was ein Kranker wert ist. Am Verhandlungstisch sitzt',
  'er selbst nicht.**',
  '',
  '**Viertens: Die Verwaltung wächst von selbst.** Jede Regel erzeugt',
  'einen Streitfall, jeder Streitfall eine neue Regel. Aus dem Gesetz von',
  '1883 mit seinen überschaubaren Paragraphen wurde 1911 ein Gesetzbuch',
  'mit über achtzehnhundert. Das ist kein deutsches Unglück, sondern die',
  'Eigenart der Sache: **Ein System, das gerecht sein will, muss',
  'unterscheiden. Wer unterscheidet, braucht Regeln. Wer Regeln hat,',
  'braucht Beamte.**',
  '',
  '## Blatt 11: Der andere Preis — die Kurierfreiheit und die Kassen',
  '',
  'Ein Blatt für sich, weil es die Seite betrifft, die in der Akte des',
  'Staates am wenigsten vorkommt: die Heilkundigen ohne Approbation.',
  '',
  'Zuerst eine Tatsache, die den meisten überraschend vorkommt: **Das',
  'Kaiserreich hat das Heilen nicht verboten, sondern freigegeben.** Die',
  'Gewerbeordnung von 1869 brachte die **Kurierfreiheit** — die Ausübung',
  'der Heilkunde war jedermann erlaubt. Geschützt war allein die',
  'Bezeichnung „Arzt". Der Gedanke dahinter war ein liberaler: Heilen ist',
  'ein Gewerbe wie andere, und der mündige Bürger wählt selbst, wem er',
  'sich anvertraut.',
  '',
  'Verdrängt wurden die Heilkundigen also nicht durch ein Verbot. **Sie',
  'wurden durch das Geld verdrängt.** Von 1883 an bezahlte die Kasse den',
  'zugelassenen Arzt — und nur ihn. Wer zur Kräuterfrau, zum Bader, zum',
  'Magnetiseur, zum Naturheilkundigen ging, zahlte weiter aus der eigenen',
  'Tasche, obwohl er jede Woche seinen Beitrag abgeführt hatte. Für einen',
  'Arbeiterhaushalt war damit entschieden. **Nicht der Paragraph hat die',
  'alte Heilkunde aus dem Alltag der einfachen Leute gedrängt, sondern der',
  'Krankenschein.**',
  '',
  'Die ärztlichen Verbände wollten mehr. Ab 1900 forderten sie in',
  'mehreren Anläufen ein Gesetz gegen die „Kurpfuscherei". Die Entwürfe',
  'scheiterten im Reichstag — auch, weil die Naturheilbewegung sich',
  'organisiert hatte: Hunderte Vereine für naturgemäße Lebens- und',
  'Heilweise mit weit über hunderttausend Mitgliedern, mit Zeitschriften,',
  'Bädern und Abgeordneten, die sie hörten. **Die Kurierfreiheit ist im',
  'Kaiserreich verteidigt worden, und zwar von unten.**',
  '',
  'Wie erfolgreich die andere Seite war, zeigt der Ort, der auf der Karte',
  'dieses Kapitels ganz im Süden liegt. In **Bad Wörishofen** behandelte',
  'ein katholischer Pfarrer namens **Sebastian Kneipp** mit kaltem Wasser,',
  'Kräutern, Bewegung und geregelter Lebensweise. Sein Buch „Meine',
  'Wasserkur" von 1886 wurde in viele Sprachen übersetzt; in den 1890er',
  'Jahren kamen Zehntausende Kurgäste im Jahr in das schwäbische Dorf, und',
  '1894 empfing ihn der Papst. Er hatte keine Approbation. Er war nach',
  'dem Gesetz von 1869 vollkommen im Recht. Und keine Kasse hat je eine',
  'seiner Anwendungen bezahlt. Kapitel 17 erzählt seine Geschichte.',
  '',
  'Wie es weiterging, gehört der Vollständigkeit halber hierher, auch wenn',
  'es über die Zeit dieser Akte hinausreicht: Die Kurierfreiheit endete',
  '**1939** mit dem Heilpraktikergesetz. Von da an brauchte es eine',
  'staatliche Erlaubnis, und nach dem Willen der damaligen Regierung',
  'sollten keine neuen mehr erteilt werden — der Beruf sollte aussterben.',
  'Nach 1945 hatte diese Sperre vor dem Grundgesetz keinen Bestand;',
  'seither wird die Erlaubnis wieder erteilt. **Ausgerechnet ein Gesetz,',
  'das den Beruf beenden sollte, ist zur Grundlage seiner Existenz',
  'geworden.**',
  '',
  '## Blatt 12: Das Werkzeug in fremder Hand',
  '',
  'Und nun das Blatt, bei dem der Staat am schlechtesten aussieht — es',
  'gehört in diese Akte, weil es aus derselben Denkart folgt.',
  '',
  'Dieses Buch erzählt seit Kapitel 9 immer wieder dasselbe Muster: **Das',
  'Neue schadet oft erst, bevor es segensreich wird.** Die Chirurgie',
  'tötete durch Wundfieber, ehe sie rettete. Die Strahlen verbrannten ihre',
  'Pioniere, ehe daraus die Radiologie wurde. Das Penicillin rettete',
  'Millionen und erzeugte die Widerstandsfähigkeit der Keime.',
  '',
  'Bei einer Einrichtung sieht dieses Muster anders aus, aber es ist',
  'dasselbe. **Ein Werkzeug fragt nicht, wer es in die Hand nimmt.** Wer',
  'die Gesundheit zur Sache des Gemeinwesens erklärt, schafft dafür',
  'Ämter, Meldewege, Register, Statistiken und die Gewohnheit, dass eine',
  'Behörde über den Körper mitredet. Solange dieses Werkzeug in der Hand',
  'einer Ordnung liegt, die dem Einzelnen helfen will, hilft es dem',
  'Einzelnen.',
  '',
  'Fünfzig Jahre nach 1883 lag es in anderen Händen. Ein Gesetz von 1933',
  'ordnete die Unfruchtbarmachung von Menschen an, die man für erbkrank',
  'hielt; bis 1945 wurden rund vierhunderttausend Menschen zwangsweise',
  'sterilisiert. Aus der „Volksgesundheit", die 1911 auf einer',
  'Ausstellung in Dresden noch Zähneputzen und Säuglingspflege bedeutet',
  'hatte, wurde die Frage, welches Leben der Allgemeinheit nützt. **Der',
  'Gedanke, dass Gesundheit nicht nur dem Einzelnen gehört, kann das',
  'Beste hervorbringen und das Schlimmste.** Kapitel 14 und 15 werden das',
  'Thema wieder aufnehmen.',
  '',
  'Ich schreibe das nicht als Anklage gegen die Gesetze von 1883, 1884 und',
  '1889 — die haben das nicht beabsichtigt und nicht verschuldet. Ich',
  'schreibe es als das, was in der Akte hinter jedem geschaffenen Amt',
  'stehen müsste: **Ein Werkzeug ist so gut wie die Hand, die es hält,',
  'und die Hand wechselt.**',
  '',
  '## Der Zettel, der nicht in die Akte gehört — der Kanzler und sein Arzt',
  '',
  'Zum Schluss ein Blatt, das eigentlich Privatsache ist und das trotzdem',
  'mehr über dieses Kapitel sagt als die meisten Paragraphen.',
  '',
  'Der Mann, der die Kassenmedizin ins Werk setzte, war selbst ein',
  'schwerkranker Mann: schlaflos, jähzornig, an Magen und Nerven leidend,',
  'stark übergewichtig, ein gewaltiger Esser und Trinker. Die ersten Ärzte',
  'Berlins hatten ihn behandelt, ohne dass es besser wurde.',
  '',
  '1883 — im Jahr des Krankenversicherungsgesetzes — übernahm ihn',
  '**Ernst Schweninger**, ein Arzt, den die Berliner Fakultät für einen',
  'Außenseiter hielt und dem sie den Lehrstuhl nur auf Druck von oben gab.',
  'Schweninger verordnete kaum Arznei. Er verordnete **Ordnung**: Maß beim',
  'Essen und Trinken, geregelten Schlaf, Bewegung, Wickel, ein',
  'strenges Regiment und die Bedingung, dass der Patient sich fügt. Der',
  'Kanzler nahm rund dreißig Kilogramm ab und wurde ein anderer Mensch. Er',
  'ist 1898 mit dreiundachtzig Jahren gestorben.',
  '',
  'Dazu passt der Ort, an den er über Jahrzehnte immer wieder fuhr:',
  '**Bad Kissingen**, Heilquellen, Trinkkur, Bäder, Spaziergänge, ein',
  'geregelter Tag. Genau das, was in den frühen Kapiteln dieses Buches',
  'unter Diätetik und Lebensordnung steht, von Hippokrates bis in die',
  'Klostergärten.',
  '',
  '**Der Urheber der Kassenmedizin ist von etwas gesund geworden, was',
  'keine Kasse bezahlt hätte.** Ich lasse diesen Zettel unkommentiert in',
  'der Akte liegen. Er widerlegt kein Gesetz. Aber er zeigt, dass die',
  'Grenze, die ab 1883 durch die Heilkunde lief, keine Grenze zwischen',
  'Wirksam und Unwirksam war, sondern eine zwischen Abrechenbar und Nicht-',
  'abrechenbar. Wer es sich leisten konnte, hat sie nie beachtet.',
  '',
  '## Nachtrag: was diese Akte nicht enthält',
  '',
  'Eine Akte ist ein Standpunkt in Papierform. Sie enthält, was die',
  'Behörde wissen musste, und sie enthält nicht, was der Behörde nie',
  'gemeldet wurde.',
  '',
  '**Was offen bleibt**, ist deshalb nicht wenig. In diesen Blättern steht',
  'nicht, wie es sich anfühlt, zum ersten Mal einen Arzt zu holen, ohne',
  'vorher das Haushaltsgeld zu zählen — und wie es sich anfühlt, dafür',
  'nach der Nummer gefragt zu werden, bevor jemand nach dem Namen fragt.',
  'Hier steht nicht, was eine Kräuterfrau in einem Dorf dachte, als die',
  'Leute aufhörten zu kommen, weil der Krankenschein nur beim Doktor galt.',
  'Hier steht nicht, wie ein Bergmann darüber urteilte, dass sein Beitrag',
  'zwar seine Behandlung bezahlte, aber nicht die Behandlung, die er',
  'wollte.',
  '',
  '**Die zweite Stimme dieses Kapitels gehört den Versicherten und den',
  'Verdrängten** — den Arbeitern, die über Nacht Kassenpatienten wurden,',
  'und den Heilkundigen, denen dieselbe Neuerung die Grundlage entzog.',
  'Sie wird die andere Akte aufschlagen: die Versichertenakte, in der',
  'derselbe Vorgang von unten aussieht. Sie wird von der neuen Sicherheit',
  'erzählen und von der neuen Abhängigkeit; von der Quittungskarte, den',
  'Marken und dem Kontrolleur an der Tür; von den Badern, Kräuterfrauen',
  'und Naturheilkundigen, die jahrhundertelang behandelt hatten und nun',
  'nicht mehr bezahlt wurden.',
  '',
  'Und sie wird die Frage stellen, die diese Akte nicht beantworten kann,',
  'weil eine Behörde die eigene Zuständigkeit schlecht bezweifeln kann:',
  '**Wem gehört die Gesundheit — dem Staat, dem Markt oder dem Menschen,',
  'der sie hat?**',
  '',
  'Der Staat hat 1883 seine Antwort gegeben, und sie war kein Fehler: Wer',
  'krank ist, soll behandelt werden, gleich ob er zahlen kann. Millionen',
  'Menschen verdanken dieser Antwort ihr Leben. Bezahlt hat man sie mit',
  'einem Stück Selbstbestimmung, mit einer Verwaltung, die nie wieder',
  'kleiner wurde, und mit dem Verschwinden all dessen aus dem Alltag der',
  'einfachen Leute, was sich nicht abrechnen ließ.',
  '',
  '**Beides zusammen ist die Wahrheit dieses Kapitels. Welche Hälfte',
  'schwerer wiegt, entscheidet die Akte nicht. Das entscheidest Du.**',
].join('\n');

/**
 * Die Versicherten und die Verdrängten — die andere Akte. Was die Akte
 * im Reichskanzleramt nicht enthält: der Arbeiter mit der Kassenkarte,
 * die neue Sicherheit und die neue Abhängigkeit, die Kurierfreiheit und
 * die Verdrängung der Naturheilkunde.
 *
 * Verfasst von Hermes (Runde 14, zweiter Pass). Auch diese Stimme benennt
 * die unbequemen Stellen der eigenen Seite selbst (Zusatzregel für
 * sensible Themen).
 */
const stimmeDerVersicherten = [
  '## Die andere Akte: ein Versicherter',
  '',
  'Die Akte im Reichskanzleramt erzählt die Geschichte von oben: die',
  'Befunde, die Peitsche, das Zuckerbrot, die Gesetze. Nun legen wir',
  'die andere Akte daneben — die eines Mannes, der nie gefragt wurde,',
  'ob er in die Geschichte eintreten will. Sein Name steht nicht in',
  'den Geschichtsbüchern, aber seine Nummer steht in den Registern: Er',
  'ist der erste Jahrgang der Versicherten, die der Staat erfunden hat.',
  '',
  '## Blatt 1: Der Befund — die Fabrik von innen',
  '',
  'Der Mann arbeitet in einer Fabrik an der Ruhr, zwölf Stunden am',
  'Tag, sechs Tage die Woche. Wenn er krank wird, verliert er den',
  'Lohn; wenn er lange krank ist, verliert er die Arbeit; wenn er die',
  'Arbeit verliert, zieht die Familie ins Armenhaus, in dem Männer',
  'und Frauen getrennt hausen und die Kinder in die Anstalt kommen.',
  'Das ist die soziale Frage, von der die Akte spricht — nur dass sie',
  'für ihn kein Begriff ist, sondern der Alltag. Sein Vater ist',
  'verarmt gestorben, ohne je einen Arzt gesehen zu haben. Er selbst',
  'hat noch nie einen von innen gesehen.',
  '',
  '## Blatt 2: Die Kassenkarte — was sich änderte',
  '',
  '1884 bekommt er eine Karte. Auf ihr steht seine Nummer, sein Name,',
  'der Beitrag: zwei Prozent des Lohns, der Arbeitgeber zahlt die',
  'Hälfte. Und mit der Karte kommt etwas, das es für seinesgleichen',
  'nie gegeben hat: das Recht. Wenn er krank wird, bekommt er',
  'Krankengeld; wenn er zum Arzt geht, wird der Arzt bezahlt — von',
  'der Kasse, nicht aus der eigenen Tasche, die leer ist. Zum ersten',
  'Mal in der Geschichte seiner Klasse ist die Medizin nicht ein',
  'Geschenk der Reichen, sondern ein Anspruch. Die Kindersterblichkeit',
  'sinkt, die Lebenserwartung steigt, die Seuchen weichen — nicht',
  'allein wegen der Kasse, aber auch wegen ihr. Wer das nicht',
  'anerkennt, hat die Akte nicht gelesen.',
  '',
  '## Blatt 3: Der Preis — der Patient mit Nummer',
  '',
  'Aber nun die andere Seite der Karte, denn auch diese Stimme ist',
  'ehrlich. Mit dem Anspruch kam die Verwaltung. Der Kranke wurde',
  'zum Versicherten: ein Fall, eine Nummer, ein Tarif. Der Arzt,',
  'bisher ein freier Herr über seine Kunst, wurde zum Kassenarzt —',
  'gebunden an die Gebührenordnung, an die Kassen, an die Kontrolle.',
  'Wer behandelt wurde, wurde geprüft: Ob die Krankheit „echt" war,',
  'entschied nicht mehr der Kranke mit seinem Leib, sondern der',
  'Kassenvertrauensarzt mit seinem Stempel. Der Mensch, der zum Arzt',
  'ging, um gehört zu werden, hörte zuerst die Frage nach seiner',
  'Nummer. Die Sicherheit hatte einen Preis, und der Preis war ein',
  'Stück Freiheit.',
  '',
  '## Blatt 4: Die Verdrängten — die Kurierfreiheit',
  '',
  'Und dann die zweite Rechnung: die Freiheit, die nicht verwaltet,',
  'sondern abgeschafft wurde. Deutschland hatte eine jahrhundertealte',
  'Kurierfreiheit: Jeder durfte heilen, wer heilen konnte — der',
  'Bader, die Kräuterfrau, der Naturheiler, der Pfarrer mit dem',
  'Kräuterbuch. Die Menschen auf dem Land gingen zu dem, dem sie',
  'vertrauten, nicht zu dem mit dem Titel. Mit der Verstaatlichung',
  'kam der Feldzug gegen die „Kurpfuscherei": Die Kassen zahlten nur',
  'approbierte Ärzte; die anderen wurden zu Verbotenen erklärt,',
  'verfolgt, an den Rand gedrängt. Manches daran war berechtigt — es',
  'gab Scharlatane, die mit Wundermitteln Geld machten. Aber der',
  'Feldzug traf auch die Traditionen, die dieses Buch in den ersten',
  'Kapiteln gewürdigt hat: das Kräuterwissen, die Naturheilkunde, die',
  'Kunst der Hebammen. Sebastian Kneipp, der Pfarrer aus',
  'Wörishofen, wurde von der Ärzteschaft bekämpft und von den',
  'Menschen geliebt — die Kassen kannten ihn nicht. Die Medizin',
  'wurde staatlich, und was nicht staatlich war, wurde verdächtig.',
  '',
  '## Blatt 5: Was die Akte nicht enthält',
  '',
  'Die Akte enthält auch nicht die Stimmen derer, die gar nicht erst',
  'hineinkamen. Die Frauen, die keinen eigenen Anspruch hatten; die',
  'Kinder, deren Karte an den Vater gebunden war; die Landarbeiter,',
  'die oft außen vor blieben; die Arbeitslosen, die mit der Arbeit',
  'auch die Kasse verloren. Der Sozialstaat, der hier erfunden wurde,',
  'war eine Versicherung der Arbeiter — nicht der Armen. Die Lücke',
  'zwischen Anspruch und Wirklichkeit gehört zur Wahrheit dieser',
  'Akte, und wer sie verschweigt, erzählt nur die halbe Geschichte.',
  '',
  '## Antwort an den Staat',
  '',
  'Die Akte im Reichskanzleramt endet mit der Frage, was aus dem Werk',
  'wurde, das der Staat sich nicht erträumt hatte. Die Antwort dieser',
  'anderen Akte: Es wurde das größte Geschenk — und die größte',
  'Verwaltung —, das die Medizin je bekommen hat. Der Arbeiter hat',
  'den Arzt bekommen, den er nie gehabt hätte; und er hat die Freiheit',
  'verloren, selbst zu wählen, wer ihn heilt. Der Staat hat die',
  'Gesundheit zur Bürgerpflicht gemacht — und den Bürger zum',
  'Versicherten. Die Frage, die beide Akten gemeinsam hinterlassen,',
  'ist die Frage des ganzen Buches: Wem gehört die Gesundheit? Dem,',
  'der sie lebt? Dem, der sie heilt? Dem, der sie bezahlt? Oder dem,',
  'der sie verwaltet? Die Antwort darauf sucht dieses Buch bis zur',
  'letzten Seite.',
].join('\n');

/** Kapitel 13 der Themenlandkarte. */
const verstaatlichung = {
  id: 'verstaatlichung',
  titel: 'Die Verstaatlichung des Gesundheitswesens',
  epoche: '~1883 ff.',

  aufhaenger: {
    frage:
      'Wer gehört der Kranke — dem Arzt, dem Staat oder sich selbst?',
    text: [
      'Bis 1883 gab es am Krankenbett zwei Parteien. Den Kranken, der bezahlte,',
      'und den, der behandelte. Wer nicht bezahlen konnte, ging zur Kräuterfrau,',
      'zum Bader, zur Armenpflege — oder er blieb ohne Hilfe. In Preußen kostete',
      'das Almosen der Gemeinde sogar das Wahlrecht.',
      '',
      'Dann trat eine dritte Partei hinzu. Am 15. Juni 1883 beschloss der',
      'Reichstag das Krankenversicherungsgesetz, 1884 folgte die',
      'Unfallversicherung, 1889 die Rentenversicherung. Der Staat behandelte',
      'niemanden selbst — er schrieb vor, dass gezahlt wird, von wem, wie viel',
      'und wofür. Es war das erste Gesetz dieser Art auf der Welt, und fast alle',
      'Industrieländer haben es nachgebaut.',
      '',
      'Was daraus wurde, ist beides: der Arzt für alle, gleich ob jemand Geld',
      'hat — die Kanalisation, das saubere Wasser, die Seuchenabwehr, zwanzig',
      'gewonnene Lebensjahre in zwei Generationen. Und: die Nummer statt des',
      'Namens, der Kontrolleur an der Wohnungstür, der Arzt als Vertragspartner',
      'einer Kasse, ein Gesetzbuch mit achtzehnhundert Paragraphen — und eine',
      'Heilkunde, die niemand verbot, die aber niemand mehr bezahlte.',
      '',
      'Dieses Kapitel liest die Akte von beiden Seiten. Denn die Frage, wem die',
      'Gesundheit gehört, ist seit 1883 nicht mehr verstummt: gerecht und',
      'bürokratisch, rettend und bevormundend, für alle da und am Ende doch für',
      'niemanden ganz.',
    ].join('\n'),
  },

  karte,

  perspektiven: [
    {
      id: 'staat',
      name: 'Die Stimme des Staates',
      stimme: 'Opus',
      text: stimmeDesStaates,
    },
    {
      id: 'versicherte',
      name: 'Die Versicherten und die Verdrängten',
      stimme: 'Hermes',
      text: stimmeDerVersicherten,
    },
  ],

  synthese: [
    '## Wo sich beide Akten treffen',
    '',
    'Zuerst das Gemeinsame — und es ist der Kern des Kapitels: Beide',
    'Akten erzählen dieselbe Geschichte von zwei Seiten. Der Staat und',
    'der Versicherte stimmen überein, dass die Kasse ein Geschenk war —',
    'der Zugang zur Medizin für alle, das Krankengeld, die sinkende',
    'Sterblichkeit; die eine Akte nennt es den Anspruch, die andere das',
    'Recht. Beide benennen denselben Preis: die Kontrolle, die Nummer,',
    'die Verwaltung — der Staat nennt ihn die Bürokratie, der',
    'Versicherte nennt ihn die Freiheit. Und beide wissen um die',
    'Verdrängten: Die Akte des Kanzlers räumt ein, dass die Kassen die',
    'alte Heilkunde verdrängt haben; die andere Akte erzählt, was das',
    'für die Kräuterfrauen und die Kneipp-Vereine bedeutete. Wer nur',
    'eine Akte liest, liest die halbe Geschichte.',
    '',
    '## Wo sie auseinandergehen',
    '',
    'Der Widerspruch beginnt bei der Frage, was der Staat eigentlich',
    'wollte. Für die Akte des Kanzlers ist die Versicherung ein Werk',
    'der Fürsorge: der Staat, der seine Arbeiter schützt, weil er sie',
    'braucht — die Peitsche und das Zuckerbrot gehören zur selben',
    'Hand. Für die Akte des Versicherten ist die Fürsorge auch ein',
    'Zügel: Wer die Gesundheit verwaltet, verwaltet den Menschen; wer',
    'die Kurierfreiheit abschafft, schafft die Selbstbestimmung ab. Sie',
    'streiten nicht über die Zahlen — die sind gut —, sondern über die',
    'Absicht und über den Preis der Sicherheit. Und sie streiten über',
    'die Zukunft: Der Staat sieht die Ordnung, die wächst; der',
    'Versicherte sieht die Entmündigung, die wächst. Beide haben ein',
    'Stück recht — und genau das macht die Frage, wem die Gesundheit',
    'gehört, bis heute ungelöst.',
    '',
    '## Was dieses Kapitel für das ganze Buch zeigt',
    '',
    'Zum vierzehnten Mal dasselbe Muster — und jetzt wendet es sich',
    'der Gegenwart zu: Die Denkart bestimmt die Methode. Mit der',
    'Verstaatlichung tritt eine neue Denkart in die Medizin: die',
    'Gesundheit als Bürgerrecht, verwaltet vom Staat. Diese Denkart',
    'hat die Medizin für alle geöffnet — und sie hat die Medizin zur',
    'Institution gemacht, mit Tarifen, Kassen und Kontrolle. Der Arzt,',
    'der in den frühen Kapiteln frei war, ist heute ein Rädchen; der',
    'Patient, der früher wählte, ist heute ein Versicherter.',
    '',
    'Und dieses Kapitel stellt die Frage, die das Buch bis zum Ende',
    'begleiten wird: Wem gehört die Gesundheit? Der Staat hat sie zur',
    'Bürgerpflicht gemacht — und damit den Boden bereitet für das',
    'nächste Kapitel: die Pharmaindustrie, die aus derselben',
    'Versicherung ihr Geschäft macht. Wer die Kasse verwaltet,',
    'verwaltet auch den Markt; wer den Markt verwaltet, bestimmt, was',
    'gezahlt wird — und was nicht. Die Frage der nächsten Kapitel',
    'lautet: Wer profitiert von der kranken Gesellschaft — und wer',
    'zahlt den Preis?',
  ].join('\n'),

  urteil: {
    frage:
      'Wem gehört deine Gesundheit — dir, deinem Arzt, deiner Kasse oder ' +
      'dem Staat? Und wer soll entscheiden, wenn es teuer wird?',
    hinweis: [
      'Es gibt hier kein Richtig und kein Falsch. Nimm dir die beiden Hälften',
      'dieses Kapitels vor. Die eine: Seit 1883 wird ein Kranker behandelt,',
      'gleich ob er zahlen kann — das ist ein Rechtsanspruch, kein Almosen, und',
      'Millionen Menschen verdanken ihm ihr Leben. Die andere: Wer zahlt,',
      'bestimmt mit, und was bezahlt wird, hat sich durchgesetzt. Frag dich',
      'dreierlei. Erstens: Würdest du selbst freiwillig einzahlen, wenn du jung',
      'und gesund bist — und was folgt aus deiner Antwort für die Pflicht?',
      'Zweitens: Wer soll entscheiden, welche Behandlung bezahlt wird — die',
      'Ärzteschaft, die Kasse, die Politik oder du? Drittens: Was ändert sich an',
      'deiner Antwort, wenn die Behandlung, die dir hilft, nicht auf der Liste',
      'steht? Genau zwischen diesen Fragen liegt der Streit, der seit hundertund-',
      'vierzig Jahren nicht entschieden ist.',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Welche drei Sozialgesetze schuf das Deutsche Reich zwischen 1883 ' +
        'und 1889?',
      antworten: [
        'Kranken-, Unfall- und Rentenversicherung (1883, 1884, 1889).',
        'Kranken-, Arbeitslosen- und Pflegeversicherung.',
        'Unfall-, Feuer- und Lebensversicherung.',
      ],
      richtig: 0,
      erklaerung:
        'Am 15. Juni 1883 kam das Krankenversicherungsgesetz (in Kraft ab ' +
        'Dezember 1884), am 6. Juli 1884 die Unfallversicherung und am ' +
        '22. Juni 1889 die Invaliditäts- und Altersversicherung. Die ' +
        'Arbeitslosenversicherung folgte erst 1927, die Pflegeversicherung ' +
        '1995.',
    },
    {
      frage:
        'Wie wurde der Beitrag zur Krankenversicherung von 1883 zwischen ' +
        'Arbeiter und Arbeitgeber aufgeteilt?',
      antworten: [
        'Der Arbeitgeber zahlte alles allein.',
        'Beide zahlten genau die Hälfte.',
        'Der Arbeiter zahlte zwei Drittel, der Arbeitgeber ein Drittel.',
      ],
      richtig: 2,
      erklaerung:
        'Der Beitrag betrug bis zu drei Prozent des ortsüblichen Tagelohns; ' +
        'davon trug der Arbeiter zwei Drittel. Weil sich die Sitze in den ' +
        'Kassenorganen nach den Beitragsanteilen richteten, stellten die ' +
        'Arbeiter dort zwei Drittel der Vertreter — und die Kassen wurden ' +
        'für sie zur Schule der Selbstverwaltung. Die Unfallversicherung von ' +
        '1884 zahlten dagegen die Arbeitgeber allein.',
    },
    {
      frage:
        'In welchem Verhältnis standen die Sozialgesetze zum ' +
        'Sozialistengesetz von 1878?',
      antworten: [
        'Die Sozialgesetze hoben das Sozialistengesetz auf.',
        'Sie liefen nebeneinander: Das Verbot der Sozialdemokratie galt von ' +
          '1878 bis 1890, die Sozialgesetze kamen ab 1883 hinzu.',
        'Beide wurden am selben Tag beschlossen.',
      ],
      richtig: 1,
      erklaerung:
        'Das „Gesetz gegen die gemeingefährlichen Bestrebungen der ' +
        'Sozialdemokratie" vom 21. Oktober 1878 verbot Vereine, ' +
        'Versammlungen und Zeitungen der Partei; es wurde viermal verlängert ' +
        'und lief erst 1890 aus. Die Kaiserliche Botschaft vom 17. November ' +
        '1881 kündigte die Sozialgesetze ausdrücklich als Ergänzung zur ' +
        'Repression an. Kandidieren blieb erlaubt, deshalb saßen ' +
        'sozialdemokratische Abgeordnete die ganze Zeit über im Reichstag.',
    },
    {
      frage:
        'Was bedeutete die „Kurierfreiheit" der Gewerbeordnung von 1869?',
      antworten: [
        'Kuren in Heilbädern waren für alle kostenlos.',
        'Nur approbierte Ärzte durften Kranke behandeln.',
        'Heilen war jedermann erlaubt; geschützt war allein die Bezeichnung ' +
          '„Arzt".',
      ],
      richtig: 2,
      erklaerung:
        'Die Ausübung der Heilkunde war ein freies Gewerbe. Verdrängt wurden ' +
        'Bader, Kräuterfrauen und Naturheilkundige nicht durch ein Verbot, ' +
        'sondern durch die Kassen: Diese bezahlten ab 1883 nur zugelassene ' +
        'Ärzte. Mehrere Anläufe zu einem Gesetz gegen die „Kurpfuscherei" ' +
        'scheiterten nach 1900 im Reichstag. Erst das Heilpraktikergesetz ' +
        'von 1939 beendete die Kurierfreiheit.',
    },
    {
      frage:
        'Was zeigte der Vergleich von Hamburg und Altona bei der Cholera ' +
        'von 1892?',
      antworten: [
        'Dass die Krankheit sich nur in Hafenstädten ausbreitete.',
        'Dass die Stadt mit gefiltertem Trinkwasser fast verschont blieb, ' +
          'die Nachbarstadt mit ungefiltertem Elbwasser dagegen rund 8.600 ' +
          'Tote hatte.',
        'Dass Impfungen die Epidemie beendeten.',
      ],
      richtig: 1,
      erklaerung:
        'Hamburg entnahm sein Trinkwasser ungefiltert der Elbe, das ' +
        'angrenzende Altona ließ seines durch Sandfilter laufen. An manchen ' +
        'Straßen lief die Stadtgrenze mitten durch die Häuserzeile — ' +
        'dieselben Menschen, zwei Wasserwerke, zwei Ergebnisse. Robert Koch ' +
        'drängte auf Filtration. Danach war entschieden, dass Wasser, ' +
        'Abwasser und Seuchenabwehr Sache der Behörden sind; 1900 folgte ein ' +
        'Reichsgesetz.',
    },
  ],
};

module.exports = verstaatlichung;
