// Kapitel 18 — „Den simple medicin".
//
// BOGENS HJERTESTYKKE (CLAUDE.md, forfatterens tese fra 26.08.2026):
// Behandlingen af kroniske sygdomme er i virkeligheden meget enkel —
// 1) bevægelse, 2) afbalanceret og sund kost (lidt forarbejdet mad),
// 3) et godt socialt miljø og lidt stress.
// „Disse ting kan enhver gøre på eget ansvar — det kræver ingen
// raketvidenskab. Med disse enkle livsstilsjusteringer kunne der
// formentlig købes meget mere sundhed end med de nyeste
// kemipræparater."
//
// Kapitlet ledende spørgsmål (forfatterens krav): Hvorfor udskriver
// medicinen piller i stedet for livsstil?
//
// TONE-REGLEN (bindende): BEGGE sider skal behandles fair.
// Skolemedicinen får sine resultater (akutmedicinen redder liv,
// diagnostikken er fremragende) OG sine mørke pletter (pille i stedet
// for råd, de finansielle interesser, grænserne ved kroniske sygdomme).
// Livsstilsmedicinen får sin dokumentation OG sine grænser: Ikke alle
// kan vælge deres livsstil (penge, tid, skifteholdsarbejde, bopæl),
// livsstilsbebrejdelsen må ikke stigmatisere syge, og den undersøgelse,
// der taler imod tesen (Look AHEAD, 2013), står udtrykkeligt i teksten.
//
// REGLEN OM INGEN RYGTER (forfatterens beslutning 25.08.2026): Kun
// dokumenteret, med navn og år. Framingham 1948, Morris 1953,
// Syv-lande-undersøgelsen 1958, Roseto fra 1961, Nordkarelen fra 1972,
// Whitehall II fra 1985, Diabetes Prevention Program 2002, INTERHEART
// 2004, Blue Zones 2004/05, EPIC-Potsdam 2009, Holt-Lunstad 2010/2015,
// Look AHEAD 2013, DiRECT 2018, Hall 2019, WHO's tal for ikke-smitsomme
// sygdomme. Hvor et tal er omstridt (100-års-kvoterne i de blå zoner,
// den tilbagetrukne og genudgivne PREDIMED-undersøgelse), siger teksten
// det.
//
// INNOVATIONSCYKLUSSEN (forfatterens observation 26.08.2026, rød tråd):
// Her står mønsteret på hovedet. Den simple medicin er urgammel og har
// aldrig skadet i massevis — den blev fortrængt af den dyre, komplekse
// medicin, der akut redder liv, men kroniske sygdomme ofte kun
// forvalter. Cyklussen viser sig først, når den simple idé bliver til
// en vare: wellness-økonomien, diætmarkedet, kosttilskud, selvmåling.
// Den første stemme nævner det selv (afsnittet „Når det simple bliver
// til en vare").
//
// LÆNGDEREGLEN (forfatterens feedback 24.08.2026): Fra kapitel 9 gælder
// det modsatte — fuldstændigt og udførligt. Det måles i
// tests/karte-einfache-medizin.mjs.
//
// Stemmer (runde 19): Det FØRSTE perspektiv — „Hverdagens stemme", den
// simple medicin indefra, fra menneskenes liv — er skrevet af Opus. Det
// ANDET („Forholdenes stemme": industri, reklame, arbejdsliv, pille i
// stedet for råd — det, der gør en sund livsstil svær) og den endelige
// syntese er blevet suppleret af Hermes i anden omgang (Hermes-pass,
// 29.08.2026: „suppleret").
// Perspektiv-workflow: CLAUDE.md. Begge stemmer er ligeværdige;
// rækkefølgen er tilfældig og ingen rangordning.
//
// INGEN GENTAGELSER (forfatterens beslutning fra 21.08.2026): Kapitel 1
// inddeler efter „hvem der taler her", kapitel 2 begynder med en scene,
// kapitel 3 fortæller en dagsgang, kapitel 4 er en brevveksling,
// kapitel 5 en bogs rejse, kapitel 6 en rundtur, kapitel 7 en proces,
// kapitel 8 en regning, kapitel 9 et ur, kapitel 10 en kæde, kapitel 11
// en linse, kapitel 12 et interview, kapitel 13 en akt, kapitel 14 en
// indlægsseddel, kapitel 15 en pressekonference, kapitel 16 telefonen,
// kapitel 17 vandet selv. Dette kapitel vælger den nittende dramaturgi:
// TIMERNE. Et menneske med en kronisk sygdom tilbringer om året omkring
// to timer hos læger — og 8.758 timer et andet sted. Hverdagens stemme
// er stemmen fra disse 8.758 timer. Den anden stemme kan træde ind i
// samme form: de samme timer, men set udefra — hvem de tilhører, hvem
// der råder over dem, og hvem der tjener på dem.
//
// Teksterne ligger som linjearrays med `.join('\n')` — sådan forbliver
// de læsbare i reposen ved omkring 72 tegn (forfatteren læser dem her),
// og utils/markdown.js gør dem i appen igen til flydende tekst.
//
// CommonJS uden UI-imports (arkitekturregel): kan tjekkes med bart `node`.

const stimmeDesAlltags = [
  '## De to timer',
  '',
  'Regn engang efter, hvor meget medicin der er i dit år.',
  '',
  'Et menneske i Tyskland med en kronisk sygdom — forhøjet blodtryk,',
  'type 2-diabetes, rygsmerter, et træt hjerte — går måske fire,',
  'fem gange om året i en lægepraksis. En samtale hos den praktiserende',
  'læge varer her i gennemsnit **omkring syv et halvt minut**; en',
  'undersøgelse fra 2017, der sammenlignede konsultationstider i 67',
  'lande, kom for Tyskland frem til **7,6 minutter** (Irving m.fl., BMJ',
  'Open 2017). Træk ventetiden fra, læg blodprøvetagningen til, læg to',
  'tider hos speciallæger og ét røntgenbillede oveni. Så kommer du op på',
  'omkring **to timer medicin** om året.',
  '',
  'Et år har 8.760 timer.',
  '',
  '**Jeg er de andre 8.758.**',
  '',
  '## De 8.758 timer',
  '',
  'Jeg er ingen metode, ingen skole, ingen profession. Jeg er det, der',
  'sker mellem to aftaler: trappen i opgangen, tallerkenen om aftenen,',
  'de fire timer på kontorstolen, vejen til busstoppestedet, natten,',
  'hvor du vågner tre gange, det opkald, du aldrig fik. Jeg er',
  'usynlig — og det er netop mit problem: Ingen udskriver mig, ingen',
  'fakturerer mig, ingen forsker i mig uden grund, og alligevel er det',
  'i mig, de fleste kroniske sygdomme bliver skabt — og nogle gange',
  'taget tilbage igen.',
  '',
  '**Det, du læser her, er en tænkemåde, ikke en sandhed.** Jeg taler',
  'for den side, hvis midler ikke koster noget og derfor næsten ikke',
  'tilhører nogen: at gå, simpel mad, søvn, andre mennesker. Jeg vil',
  'fremføre mine bedste argumenter, så stærkt jeg kan, og jeg vil nævne',
  'hvert tal med navn og år, så du kan slå det efter. Og jeg vil selv',
  'nævne de steder, hvor jeg står dårligt, i stedet for at vente på, at',
  'en anden gør det. De findes — og de er ikke få.',
  '',
  'Spørgsmålet her handler ikke om, hvorvidt bevægelse er sundt. Det',
  'bestrider ingen. Spørgsmålet lyder:',
  '',
  '**Når de tre simpleste ting i verden — at bevæge sig, spise',
  'fornuftigt, ikke være alene — vedrører størstedelen af vores tids',
  'sygdomsbyrde: Hvorfor bliver de så sjældent ordineret og så let',
  'overhørt?**',
  '',
  '## Hvad „kronisk" egentlig betyder',
  '',
  'For at vi ikke misforstår hinanden, siger jeg først, hvad jeg IKKE',
  'taler om.',
  '',
  'Jeg taler ikke om blindtarmsbetændelse, ikke om lungebetændelse,',
  'ikke om det brækkede lårben, ikke om blodforgiftning og ikke om',
  'hjerteinfarktet i den anden time. Der er moderne medicin fremragende,',
  'og det siger jeg uden at skære tænder: Den, der med en tilstoppet',
  'kranspulsåre bliver kørt ind i et kateterlaboratorium, skylder ikke',
  'sit liv til spadsereturen, men til teknologien. Kapitel 11 til 14 i',
  'denne bog har fortalt, hvad det kostede at nå dertil.',
  '',
  '**Jeg taler om de sygdomme, man ikke får, men lever sig ind i.**',
  'Forhøjet blodtryk. Type 2-diabetes. Forkalkede kar. Fedtlever. De',
  'fleste rygsmerter. En stor del af slagtilfældene. En betydelig del af',
  'kræftsygdommene. Disse sygdomme har ingen begyndelse, man kan datere.',
  'De har en forhistorie på tyve år.',
  '',
  'Verdenssundhedsorganisationen samler dem under det kantede navn',
  '„ikke-smitsomme sygdomme". Dens tal: **Omkring 41 millioner mennesker',
  'dør af dem hvert år — cirka 74 procent af alle dødsfald på',
  'verdensplan.** Som de fire fælles adfærdsrelaterede risici nævner WHO',
  'tobak, usund kost, mangel på bevægelse og skadeligt alkoholforbrug;',
  'dertil kommer som ydre faktor luftforureningen.',
  '',
  'Det er den jord, jeg står på. **Den hyppigste dødsårsag i vores tid',
  'har en forhistorie, der ligger i de 8.758 timer.**',
  '',
  'Og deraf følger den ubehagelige sætning, som dette kapitel arbejder',
  'med: En medicin, der er bygget på akuttimen — diagnose, indgreb,',
  'recept —, rammer en sygdom, der består af tyve år, på et sted, hvor',
  'den næsten ikke kan ændre noget længere. Den kan så forvalte den.',
  'Forvaltning er ikke lidt. Men det er noget andet end at helbrede, og',
  'man bør ikke forveksle de to.',
  '',
  '## Den første søjle: kroppen, der vil bevæge sig',
  '',
  '### Hvordan viden opstod',
  '',
  'Det begyndte i en dobbeltdækkerbus i London.',
  '',
  'Lægen **Jeremy Morris** ledte i begyndelsen af 1950erne efter en',
  'forklaring på, at hjerteinfarkt i England blev stadig hyppigere. Han',
  'fandt to faggrupper, der lignede hinanden i næsten alt og adskilte',
  'sig på ét punkt: **Buschaufførerne sad hele dagen. Konduktørerne løb',
  'trappen i dobbeltdækkeren op og ned** — efter hans optællinger nogle',
  'hundrede trin pr. vagt. Samme firma, samme by, samme støj, lignende',
  'baggrund.',
  '',
  '**I 1953 offentliggjorde han resultatet i Lancet: Konduktørerne fik',
  'omkring halvt så mange hjerteinfarkter som chaufførerne** — og fik de',
  'et, overlevede de det oftere. Morris efterprøvede den indvending, der',
  'straks melder sig (måske blev de stærkere mænd konduktører), på en',
  'anden gruppe: postbud mod ekspedienterne i samme posthus. Samme',
  'billede.',
  '',
  'Det var fødselsstunden for en hel forskningsretning. Den har siden',
  'frembragt hundredvis af undersøgelser. Fundet er et af de mest',
  'stabile i medicinen.',
  '',
  '### Hvilken antagelse ligger bag',
  '',
  'Min antagelse er enkel: **Kroppen er et apparat, der fordeler sine',
  'dele efter brug.** Det, der bruges, bevares. Det, der ikke bruges,',
  'nedbrydes — ikke af ondskab, men fordi vedligeholdelse koster energi,',
  'og kroppen er sparsommelig.',
  '',
  'Det er ingen naturfilosofi, det er observerbart. Et ben i gips',
  'mister på tre uger synligt muskelmasse. Den, der bliver sengeliggende,',
  'mister knoglemasse. Den, der holder op med at gå, får dårligere',
  'balancesans, og med den kommer faldet, der i alderdommen udløser',
  'kæden: lårbenshalsbrud, hospital, forvirring, plejehjem.',
  '',
  'Nyt — og vigtigt for mit argument — er en erkendelse fra de sidste',
  'femogtyve år: **Musklen er ikke kun en motor, den er også et organ,',
  'der afgiver signalstoffer.** Forskningsgruppen i København omkring',
  'Bente Klarlund Pedersen viste fra omkring år 2000, at den arbejdende',
  'muskel sender signalstoffer ud i blodet (de kaldte dem myokiner), der',
  'virker andre steder i kroppen — på sukkerstofskiftet, på',
  'inflammationsprocesser, på hjernen. Bevægelse er dermed ikke et',
  'kalorieforbrug. **Det er en besked til hele kroppen.**',
  '',
  '### Hvad det gør — og hvad ikke',
  '',
  'Virkningerne, der er dokumenteret, er både uspektakulære og store.',
  'Regelmæssig bevægelse sænker blodtrykket, forbedrer sukkerudnyttelsen,',
  'løfter humøret målbart, bevarer evnen til at gå i alderdommen og er',
  'ved rygsmerter mere effektiv end hvile — hvilket engang blev lært',
  'præcis omvendt. **Arbejdsgruppen omkring I-Min Lee skønnede i 2012 i',
  'Lancet, at mangel på bevægelse på verdensplan er ansvarlig for',
  'omkring 9 procent af de for tidlige dødsfald.** WHO anbefaler 150 til',
  '300 minutters moderat bevægelse om ugen og fastslog i 2024, at omkring',
  '31 procent af de voksne på verdensplan — cirka 1,8 milliarder',
  'mennesker — ikke når op på den mængde.',
  '',
  'Og nu grænsen, som jeg selv trækker, fordi den hele tiden bliver',
  'overskredet:',
  '',
  '**Bevægelse er et dårligt slankemiddel.** Den, der kun dyrker sport',
  'og ellers ikke ændrer noget, taber i undersøgelser oftest få kilo og',
  'tager dem ofte på igen. Kroppen udligner: Den bliver mere',
  'sparsommelig, og sulten melder sig. Den, der fortæller dig, at du',
  'bare skal løbe nok, sælger dig noget. Bevægelse virker på blodtryk,',
  'sukker, humør, kraft, balance — på vægten virker den svagest. Det',
  'hører med til ærligheden.',
  '',
  '## Den anden søjle: hvad der kommer ind hver dag',
  '',
  '### Hvordan viden opstod',
  '',
  'Den anden tråd begynder i Napoli.',
  '',
  'Den amerikanske fysiolog **Ancel Keys** kom til byen i begyndelsen af',
  '1950erne og undrede sig: På hospitalerne i de fattige kvarterer så',
  'han næsten ingen hjerteinfarkter, i klubberne for de velhavende',
  'købmænd derimod. Det blev **fra 1958 til Syv-lande-undersøgelsen:',
  '12.763 mænd mellem 40 og 59 år, 16 kohorter i Finland, Grækenland,',
  'Italien, Japan, Nederlandene, USA og Jugoslavien.** I årtier fulgt,',
  'vejet, adspurgt, talt.',
  '',
  'Resultatet var en forskel, som ingen havde ventet: **Færrest',
  'hjertedødsfald var der på Kreta og i Japan, flest i Østfinland** — hos',
  'mænd i samme alder. Ordet „middelhavskost" stammer fra denne tid.',
  '',
  'Jeg siger straks, hvad der vakler ved det, for det forties gerne:',
  'Undersøgelsen sammenlignede **steder, ikke personer.** Hvor to egne',
  'adskiller sig i tusind ting, kan man ikke med sikkerhed sige, at det',
  'lå på olivenolien og ikke på det at gå, på vinen, på fattigdommen, på',
  'familien eller på arveanlæggene. Og Keys er blevet beskyldt for at',
  'have lagt for lidt vægt på sukkeret frem for fedtet. Kritikken er',
  'berettiget. Det, der bliver tilbage, er alligevel ikke ingenting:',
  'Forskellene mellem stederne var enorme, og de forsvandt, når',
  'mennesker flyttede fra et sted til et andet og begyndte at spise',
  'anderledes der. **Det taler imod arveanlæggene og for livsstilen.**',
  '',
  '### Hvilken antagelse ligger bag',
  '',
  'Min antagelse lyder: **Det, der hver dag kommer ind i et menneske,',
  'virker stærkere end nogen medicin, man sjældent tager.** Tre måltider',
  'om dagen, syv gange om ugen, i halvtreds år — det er over halvtreds',
  'tusinde lejligheder. Ingen tablet kommer i den størrelsesorden.',
  '',
  'Deraf følger, at mad ikke handler om enkelte stoffer. Striden om fedt',
  'mod kulhydrater, om smør mod margarine, om det ene vitamin har stået',
  'på i halvfjerds år og har bragt lidt. **Det, der viser sig tydeligst i',
  'data, er ikke et næringsstof, men en forarbejdningsgrad.**',
  '',
  'Den brasilianske ernæringsforsker **Carlos Monteiro** fra São Paulo',
  'foreslog fra 2009 at sortere fødevarer ikke efter næringsstoffer, men',
  'efter, hvor langt de var blevet bygget om industrielt — den såkaldte',
  'NOVA-inddeling. Længst nede: æble, kartoffel, linse, æg. Længst oppe:',
  'produkter, der er sat sammen af adskilte grundstoffer, med aromaer,',
  'emulgatorer, farvestoffer — og som ikke kunne fremstilles i noget',
  'køkken i verden.',
  '',
  '### Hvad det gør — og hvad ikke',
  '',
  'Det smukkeste bevis er et lille, men rent bygget forsøg.',
  '',
  '**I 2019 offentliggjorde arbejdsgruppen omkring Kevin Hall ved det',
  'amerikanske National Institutes of Health en undersøgelse, hvor tyve',
  'voksne boede på afdelingen i fire uger** — to uger med',
  'ultraforarbejdet, to uger med uforarbejdet kost. Begge madplaner var',
  'afbalancerede efter næringsstoffer: lige meget fedt, sukker, salt og',
  'kostfibre i udbuddet. Menneskerne måtte spise, så meget de ville.',
  '',
  '**Resultat: I de ultraforarbejdede uger spiste de samme mennesker',
  'omkring 500 kilokalorier mere om dagen og tog i gennemsnit næsten et',
  'kilo på; i de uforarbejdede uger tog de næsten et kilo af.** Uden',
  'forskrift, uden diæt, uden viljestyrke. Det var forskellen mellem to',
  'køkkener — ikke mellem to karakterer.',
  '',
  'Det er for mig det vigtigste enkeltfund i dette kapitel, fordi det',
  'afkræfter en beskyldning: **Det er ikke menneskenes svaghed, der',
  'forklarer vægtstigningen. Madens beskaffenhed forklarer en god del af',
  'den.**',
  '',
  'Og så er der fundet, der betyder mest for min side: **En type',
  '2-diabetes kan gå tilbage.** I den britiske DiRECT-undersøgelse (Lean',
  'm.fl., Lancet 2018) blev mennesker med en type 2-diabetes, der højst',
  'havde bestået i seks år, fulgt i almindelige praktiserende lægers',
  'praksis i Skotland og Nordengland: medicin ud, i nogle måneder en',
  'stærkt begrænset formulakost, derefter gradvist igen normal mad,',
  'dertil støtte. **Efter tolv måneder var sygdommen i remission hos 46',
  'procent af deltagerne — mod 4 procent ved den sædvanlige behandling.',
  'Efter 24 måneder var det 36 mod 3 procent.** Den, der havde tabt mere',
  'end 15 kilo, var til omkring fire femtedele i remission.',
  '',
  'En sygdom, der i årtier gjaldt som uomvendelig, er hos en del af de',
  'ramte omvendelig — ikke gennem et nyt præparat, men gennem mad og',
  'støtte.',
  '',
  'De grænser, jeg selv nævner:',
  '',
  '- **Ernæringsforskningen er den svageste forskning i medicinen.**',
  '  Den bygger overvejende på spørgeskemaer, hvor mennesker skriver op,',
  '  hvad de spiste i går — og mennesker husker dårligt og forskønner',
  '  gerne. Et dobbeltblindt forsøg er næsten umuligt med mad: Man',
  '  smager, hvad man spiser.',
  '- **Selv den berømteste ernæringsundersøgelse har en mangel.** Den',
  '  spanske PREDIMED-undersøgelse (Estruch m.fl., 2013), der for',
  '  middelhavskosten fandt omkring 30 procent færre alvorlige hjerte-',
  '  karhændelser, blev i 2018 trukket tilbage og genudgivet, fordi',
  '  lodtrækningen i nogle centre ikke var foregået rent. Hovedresultatet',
  '  holdt efter genberegningen — men en undersøgelse, der måtte',
  '  trækkes tilbage, er et svagere vidne end en, der ikke behøvede det.',
  '- **DiRECT-undersøgelsen var ikke blindet**, den løb over to år, og en',
  '  del af menneskerne tog vægten på igen. Remission er ikke',
  '  helbredelse. Den holder, så længe vægten holder.',
  '',
  '## Den tredje søjle: de andre — og roen',
  '',
  '### Hvordan viden opstod',
  '',
  'Den tredje søjle er den, man mindst venter, og den har et stednavn:',
  '**Roseto i Pennsylvania.**',
  '',
  'I 1960erne faldt det lægerne for øje, at der i denne lille by,',
  'grundlagt af italienske indvandrere, døde påfaldende få mænd af',
  'hjerteinfarkt — selv om de røg, drak vin, arbejdede hårdt i',
  'stenbruddene og lavede mad på fedt. **Stewart Wolf og hans',
  'medarbejdere undersøgte det fra 1961.** De fandt ingen forskel i',
  'kosten, ingen i rygningen, ingen i arveanlæggene — de pårørende i',
  'nabobyerne døde normalt.',
  '',
  'Hvad de fandt, var en social orden: tre generationer under samme tag,',
  'foreninger, gensidig hjælp, ingen fremviste forskelle mellem rig og',
  'fattig. Deres tese var, at dette fællesskab beskyttede.',
  '',
  '**Prøven kom af sig selv.** I de følgende årtier flyttede de unge',
  'væk, husene blev større, foreningerne tømtes. En efterundersøgelse fra',
  '1992 sammenlignede halvtreds års dødelighed: **Hjerteinfarktraten i',
  'Roseto var steget og havde nærmet sig nabobyerne.** Forspringet var',
  'væk, da fællesskabet var væk.',
  '',
  'Jeg siger dertil: Det er et sted, ikke et forsøg. Man kan ikke fordele',
  'et fællesskab ved lodtrækning. Men det var et naturligt eksperiment,',
  'og det er et af de få, man kunne følge over halvtreds år.',
  '',
  '### Hvilken antagelse ligger bag',
  '',
  'Min antagelse: **Mennesket er et flokdyr, og det at være alene er for',
  'kroppen en alarmtilstand.** Den, der ikke hører til, var i denne arts',
  'historie i livsfare; kroppen behandler ensomheden derefter — med',
  'årvågenhed, dårligere søvn, højere blodtryk, vedvarende spænding.',
  '',
  'Det samme gælder for den konstante stress. Stressreaktionen er en',
  'fremragende indretning til nødsituationen: hurtigere hjerte, sukker ud',
  'i blodet, fordøjelse fra, opmærksomheden snævret ind. Den er bygget',
  'til minutter. **Den er ikke bygget til syv år.** Løber den i syv år,',
  'bliver en redning til nedslidning.',
  '',
  '### Hvad det gør — og hvad ikke',
  '',
  'Her er tallene overraskende tydelige.',
  '',
  '**Julianne Holt-Lunstad og hendes medarbejdere vurderede i 2010 i',
  'PLoS Medicine 148 undersøgelser med 308.849 mennesker. Resultat: Den,',
  'der havde stærke sociale relationer, overlevede observationsperioden',
  'med omkring 50 procent større sandsynlighed.** En anden opgørelse fra',
  'samme gruppe fra 2015 viste en omkring 26 procent forhøjet',
  'dødelighedsrisiko ved ensomhed, 29 procent ved social isolation og 32',
  'procent ved at bo alene. Den ofte citerede sammenligning med',
  '„femten cigaretter om dagen" stammer fra dette arbejde; den er en',
  'illustration, ingen måleværdi, og jeg giver den her kun videre som',
  'sådan.',
  '',
  '**WHO nedsatte i november 2023 en selvstændig kommission for social',
  'tilknytning og betegnede ensomhed som en påtrængende sundhedsfare.**',
  'Det er nyt: En sundhedsorganisation taler om venskab.',
  '',
  'Om stress: **INTERHEART-undersøgelsen (Yusuf m.fl., Lancet 2004)',
  'sammenlignede i 52 lande omkring 15.000 mennesker efter deres første',
  'hjerteinfarkt med lige så mange raske. Ni faktorer forklarede',
  'tilsammen over 90 procent af risikoen** — herunder rygning,',
  'blodfedt, forhøjet blodtryk, diabetes, taljemål, for lidt frugt og',
  'grønt, for lidt bevægelse — og **psykosocial belastning**, altså',
  'vedvarende stress, bekymring, nedtrykthed.',
  '',
  'Og den britiske **Whitehall II-undersøgelse** under Michael Marmot,',
  'der fra 1985 fulgte over ti tusinde embedsmænd, fandt noget, som',
  'forholdenes stemme vil tage op i næste afsnit: **Jo lavere stilling i',
  'hierarkiet, desto højere dødelighed** — og en af de stærkeste',
  'enkeltfaktorer var ikke arbejdsmængden, men **hvor lidt kontrol',
  'vedkommende havde over sit eget arbejde.**',
  '',
  'Den grænse, jeg selv nævner: **Ved alt dette ved ingen med sikkerhed,',
  'hvad der er årsag, og hvad der er virkning.** Syge mennesker trækker',
  'sig tilbage. Den, der allerede har gener, går sjældnere ud af huset,',
  'mister kontakter, bliver ensom. En del af sammenhængen løber altså',
  'baglæns. Jeg påstår ikke, at venskab helbreder. Jeg påstår, at det',
  'dukker op i dødelighedsstatistikkerne — og at en medicin, der ikke',
  'engang spørger ind til det, overser noget stort.',
  '',
  '## Hvad tallene tilsammen siger',
  '',
  'Indtil her var det tre enkelte søjler. Nu det spørgsmål, det kommer',
  'an på: **Hvor meget gør det tilsammen?**',
  '',
  'Det bedste svar kommer fra Tyskland.',
  '',
  '**EPIC-Potsdam-undersøgelsen fulgte 23.153 mennesker mellem 35 og 65',
  'år. En opgørelse fra 2009 (Ford m.fl., Archives of Internal Medicine)',
  'prøvede fire kendetegn: aldrig at have røget, et body mass index',
  'under 30, mindst tre en halv times bevægelse om ugen og en kost med',
  'meget frugt, grønt, fuldkorn og lidt kød.**',
  '',
  '**Den, der opfyldte alle fire, havde over for dem, der ikke opfyldte',
  'noget, en 78 procent lavere risiko for i de følgende år at få en',
  'alvorlig kronisk sygdom** — i enkeltheder 93 procent mindre type',
  '2-diabetes, 81 procent færre hjerteinfarkter, 50 procent færre',
  'slagtilfælde og 36 procent mindre kræftsygdom.',
  '',
  'Det er det tal, dette kapitel handler om. **Intet præparat i verden',
  'når 78 procent ved fire sygdomsgrupper på samme tid.** Og disse fire',
  'kendetegn er, hvad de er: ikke ryge, ikke være for tung, bevæge sig,',
  'spise fornuftigt. Ingen raketvidenskab.',
  '',
  'To yderligere beviser i samme retning:',
  '',
  '- **Det amerikanske Diabetes Prevention Program (2002) fordelte 3.234',
  '  mennesker med forstadier til diabetes ved lodtrækning på tre',
  '  grupper:** et livsstilsprogram, lægemidlet metformin eller',
  '  placebobehandling. Efter i gennemsnit knap tre år var antallet af',
  '  nye diabetestilfælde **i livsstilsarmen faldet med 58 procent, i',
  '  metforminarmen med 31 procent.** Adfærden slog lægemidlet — og det',
  '  i samme forsøg, under samme betingelser.',
  '- **Nordkarelen.** I begyndelsen af 1970erne havde denne finske',
  '  provins verdens højeste hjerteinfarktdødelighed. Fra 1972 arbejdede',
  '  et team omkring Pekka Puska ikke med patienter, men med mejerier,',
  '  pølseproducenter, landsbyforeninger og husmorforbund; i 1977 blev',
  '  projektet udvidet til hele Finland. **Indtil 2012 faldt',
  '  hjerteinfarktdødeligheden blandt mænd i den erhvervsaktive alder',
  '  der med omkring 80 procent.** Også her den ærlige begrænsning: Der',
  '  var ingen kontrolgruppe, og dødeligheden faldt i hele Europa. I',
  '  Nordkarelen faldt den tidligere og stejlere.',
  '',
  '## Og undersøgelsen, der taler imod mig',
  '',
  'Hvis jeg kun nævnte tallene lige ovenfor, ville jeg være uærlig. Så',
  'jeg nævner selv den vigtigste undersøgelse, der modsiger min tese.',
  '',
  '**Look AHEAD, offentliggjort 2013 i New England Journal of Medicine.**',
  '5.145 overvægtige voksne med type 2-diabetes blev delt ved',
  'lodtrækning: Den ene halvdel fik i årevis et intensivt',
  'livsstilsprogram med ernæringsrådgivning, motionsprogram og tæt',
  'kontakt, den anden den sædvanlige opfølgning. Målt blev, hvem der fik',
  'et hjerteinfarkt, et slagtilfælde eller hjertedøden.',
  '',
  '**Efter i gennemsnit 9,6 år blev undersøgelsen afbrudt — ikke på',
  'grund af skader, men fordi det tegnede sig til, at der ikke ville',
  'komme nogen forskel mere.** Livsstilsgruppen havde mindre vægt, bedre',
  'værdier, mere bevægelighed, mindre nyresygdom og sjældnere depression',
  '— **men ikke færre hjerteinfarkter.**',
  '',
  'Hvad følger deraf? Man kan gøre det for let for sig selv i begge',
  'retninger. Den, der argumenterer imod mig, siger: Der har I det —',
  'livsstilen forhindrer ikke infarktet. Den, der argumenterer for mig,',
  'siger: Sammenligningsgruppen fik moderne lægemidler, der sænkede',
  'blodtrykket og blodfedtet, og desuden ændrede også den sin adfærd; en',
  'forskel var derfor svær at opnå.',
  '',
  '**Begge forklaringer er tilladelige, og ingen er bevist.** Jeg stiller',
  'undersøgelsen herhen, fordi den hører til her. Den, der holder den',
  'simple medicin for et vidundermiddel, tager fejl på dette punkt: Den',
  'er intet vidundermiddel. Den er en meget bredtvirkende, meget billig,',
  'delvist veldokumenteret og delvist ubevist tilgang.',
  '',
  '## De blå zoner — og hvorfor jeg selv mistroer dem',
  '',
  'Over dette kapitels kort ligger fem egne, hvor påfaldende mange',
  'mennesker bliver meget gamle. **Befolkningsforskerne Gianni Pes og',
  'Michel Poulain omkredsede i 2004 på et kort over Sardinien de',
  'kommuner med flest 100-årige med en blå pen** — deraf navnet.',
  'Journalisten Dan Buettner gjorde det fra 2005 for National Geographic',
  'til fem områder: **Ogliastra på Sardinien, Okinawa, Ikaria, halvøen',
  'Nicoya i Costa Rica og adventistsamfundet Loma Linda i Californien.**',
  '',
  'De har næsten intet til fælles. Forskellige verdensdele, forskellige',
  'religioner, forskellige køkkener — på Sardinien fåreost og vin, på',
  'Okinawa søde kartofler, i Nicoya majs og bønner. Det, der gentager',
  'sig, er et **mønster, ikke en opskrift:** bevægelse, der er bygget ind',
  'i dagen i stedet for i et studie; overvejende plantebaseret kost og',
  'sjældent til mæthed; faste, livslange bånd; og en opgave, der stadig',
  'er der, når man er firs.',
  '',
  'Og nu den del, som bøgerne om de blå zoner sjældent trykker.',
  '',
  '**Demografen Saul Justin Newman har vist, at egne med påfaldende mange',
  'registrerede 100-årige meget ofte er egne med dårlige',
  'fødselsregistre.** Hvor fødsler blev registreret sent eller slet',
  'ikke, hvor pensionsudbetalinger er knyttet til dokumentation af',
  'alderen, og hvor dødsfald meldes ufuldstændigt, opstår den samme',
  'statistik som ved ægte langlevethed. I nogle regioner faldt antallet',
  'af 100-årige brat, så snart der blev indført pålidelige registre. For',
  'dette arbejde fik Newman i 2024 Ig-Nobelprisen — en pris, der hædrer',
  'forskning, som først får en til at le og derefter til at tænke.',
  '',
  'Hans kritik er omstridt blandt fagfolk og ikke det sidste ord. **Men',
  'den rammer en ægte svaghed, og derfor skriver jeg den ind i mit eget',
  'kapitel:** De blå zoner er en smuk fortælling med et vakkelvornt',
  'statistisk fundament. Jeg bruger dem her som illustration, ikke som',
  'bevis. Beviset står længere oppe — i Potsdam, i Framingham, i de',
  '3.234 lodtrækninger i diabetesprogrammet.',
  '',
  'To af de fem zoner fortæller i øvrigt imod forskønnelsen. **På Okinawa',
  'kom efter 1945 med de amerikanske baser den forarbejdede kost; de',
  'yngre årgange på øen hører i dag til Japans tungeste.** Også i Nicoya',
  'skrumper forspringet. Fordelen hang ikke på generne og ikke på øen.',
  'Den hang på en livsstil — og med den går den.',
  '',
  '## Hvorfor det simple er så svært',
  '',
  'Nu kommer afsnittet, hvor jeg skader min egen sag mest — og som',
  'alligevel er det vigtigste.',
  '',
  '**Sætningen „Det kan enhver gøre på eget ansvar" er både sand og',
  'farlig.**',
  '',
  'Sand er den, fordi ingen kan gå for dig. Ingen læge, ingen sygekasse,',
  'ingen stat kan tage aftensmaden fra dig eller spadsereturen. I denne',
  'meget præcise forstand tilhører dette kapitel mig: De 8.758 timer',
  'tilbringer du.',
  '',
  'Farlig er den, fordi den indeholder et ord, der hurtigt bliver til en',
  'bebrejdelse — **ansvar.** Og af en bebrejdelse bliver der hurtigt en',
  'påstand om, at den syge selv er skyld i det. Det er forkert, og det',
  'er bevist:',
  '',
  '- **Ikke enhver kronisk sygdom er en livsstilssygdom.** Type',
  '  1-diabetes, multipel sklerose, gigtsygdomme, medfødte hjertefejl,',
  '  kræftsygdomme i barndommen, de fleste autoimmune sygdomme: Den, der',
  '  lægger disse mennesker nær, at de skulle have spist anderledes, gør',
  '  dem uret. WHO-tallene ovenfor gælder for den store gruppe af de',
  '  hyppige velfærdssygdomme — ikke for hver enkelt diagnose.',
  '- **Den, der arbejder i skiftehold, kan ikke vælge sin søvn.** Det',
  '  Internationale Agentur for Kræftforskning klassificerer natarbejde',
  '  som „sandsynligvis kræftfremkaldende" (gruppe 2A). Et menneske, der',
  '  om natten sætter varer på hylderne, plejer syge eller kører tog, kan',
  '  ikke vælge en dagrytme. Det kan kun skifte erhverv — og det kan',
  '  langt fra alle.',
  '- **Frisk mad koster tid, og tid er ulige fordelt.** Den, der har to',
  '  jobs, opdrager børn alene eller plejer pårørende, har om aftenen',
  '  ingen time til komfuret. Færdigmad er ikke bare billig og holdbar,',
  '  den er også hurtig — og hurtighed er for mange mennesker ingen',
  '  bekvemmelighed, men en nødvendighed.',
  '- **Hvor man bor, er med til at bestemme.** Et barn, der vokser op ved',
  '  en firesporet vej uden legeplads, bevæger sig mindre end ét med en',
  '  skov bag huset. Det er ikke et karakterspørgsmål, det er',
  '  byplanlægning.',
  '- **Og Marmots fund gælder stadig:** Den, der har lidt kontrol over',
  '  sit eget arbejde, dør tidligere. Det er kernen i den bebrejdelse,',
  '  som min tese må holde til. For kontrol over sin egen dag er præcis',
  '  det, mit program forudsætter.',
  '',
  '**Derfor siger jeg klart: Den simple medicin er ikke simpel for',
  'enhver.** Den er simpel at forstå og ofte svær at gøre. Den, der gør',
  'den til et moralsk krav, gør af et tilbud en skyld — og mister præcis',
  'de mennesker, der ville have mest gavn af den.',
  '',
  'To ting fraviger jeg mig alligevel ikke: For det første, at den del,',
  'nogen selv har i hånden, derfor skulle være nul. Den er stor hos',
  'nogle og lille hos andre, men den er sjældent nul. For det andet, at',
  'en anden kunne udfylde den for dig.',
  '',
  '## Når det simple bliver til en vare',
  '',
  'Denne bog fører en observation med sig, der dukkede op i næsten hvert',
  'kapitel: **Nye idéer har ofte først skadet og først senere hjulpet.**',
  'Kirurgien dræbte gennem sårfeber, før den reddede. Strålerne dræbte',
  'deres opdagere. Vaccinationen begyndte med forsøg på fanger og',
  'forældreløse børn. Penicillinen reddede millioner og frembragte',
  'resistensen.',
  '',
  '**Hos mig står dette mønster på hovedet, og jeg siger straks, hvorfor',
  'det ikke er nogen fortjeneste:** At gå, simpel mad og naboer er lige',
  'så gamle som arten. De har aldrig udløst en epidemi, fordi der aldrig',
  'var noget nyt ved dem. Man kan ikke overhale noget med dem. Der findes',
  'intet godkendelsesstudie for at gå på trapper og ingen',
  'bivirkningsindberetning for en kålrabi.',
  '',
  '**Men cyklussen indhenter mig alligevel — på det punkt, hvor det',
  'enkle bliver til en vare.** Og det punkt er for længst nået:',
  '',
  '- Af „bevæg dig" blev et abonnement med mindste bindingsperiode.',
  '- Af „spis mindre forarbejdet" blev en hylde med produkter, der er',
  '  højt forarbejdede og hedder „clean".',
  '- Af „spis grøntsager" blev en dåse kapsler. Virkningen af kosttilskud',
  '  til forebyggelse har i store forsøg for det meste ikke kunnet',
  '  påvises; solgt bliver de alligevel.',
  '- Af „vær opmærksom på dig selv" blev et ur, der bedømmer din søvn, og',
  '  en selvmåling, der gør hvile til endnu en opgave.',
  '- Af „spis mådeholdent" blev et diætmarked, der har vokset i',
  '  halvfjerds år, selv om kunderne i gennemsnit ikke bliver slankere.',
  '',
  'Brancheforeningen Global Wellness Institute anslår den globale',
  '„wellness-økonomi" til flere billioner dollars om året. Jeg citerer',
  'dette tal med udtrykkeligt forbehold — det stammer fra branchen selv',
  'og er ingen officiel statistik. Men retningen er ikke omstridt: **Det',
  'billigste er blevet en sællert.**',
  '',
  'Og dermed opstår den skade, som min side er ansvarlig for. Det er',
  'ikke kirurgiens eller strålernes skade. Den er mere stille: **Den',
  'rammer sjælen og pengepungen.** Den, der ikke har råd til programmet,',
  'føler sig ovenikøbet skyldig. Den, der har råd, køber nogle gange',
  'tilbehør i stedet for forandring. Og af en sag, der var gratis for',
  'alle, bliver en, der ligner en livsstil for mennesker med tid og',
  'penge.',
  '',
  '**Det er det punkt, hvor jeg lettest forråder mig selv — og jeg',
  'nævner det, før en anden gør det.**',
  '',
  '## Hvad jeg ikke er',
  '',
  'For at der til sidst ikke står en misforståelse tilbage, her',
  'grænserne for mit krav, så tydeligt som jeg kan trække dem:',
  '',
  '**Jeg er intet alternativ.** Jeg er ingen erstatning for insulin ved',
  'type 1-diabetes, ikke for et antibiotikum ved hjernehindebetændelse,',
  'ikke for en operation ved en tarmtilstopning, ikke for en kemoterapi',
  'ved leukæmi i barndommen. Den, der tager med sig fra dette kapitel, at',
  'man kan sætte sine tabletter ud og i stedet gå en tur, har misforstået',
  'det — og kan dø af det.',
  '',
  '**Jeg er heller ingen anklage mod læger.** De fleste ved alt det, der',
  'står her. Mange siger det også. De siger det på syv et halvt minut,',
  'mod en reklame, der kører fireogtyve timer, og i et afregningssystem,',
  'hvor recepten honoreres og samtalen næsten ikke. Det er ikke et',
  'karakterspørgsmål. Det er et konstruktionsspørgsmål.',
  '',
  '**Jeg er stueetagen.** Alt andet står ovenpå. Et blodtryk, der uden',
  'bevægelse er 160 og med bevægelse 145, har stadig brug for en tablet',
  '— men måske én i stedet for tre. En diabetes, der går tilbage, skal',
  'ikke behandles mere. En ryg, der er trænet, opereres sjældnere. **Det',
  'er mit krav, og det er beskednere, end det lyder i rådgiverbøger:',
  'ikke i stedet for medicinen, men under den.**',
  '',
  '## Døren til den anden stemme',
  '',
  'Jeg har i hele dette kapitel talt om de 8.758 timer, som om de var',
  'dine.',
  '',
  '**De er ikke helt dine.**',
  '',
  'En del af dem tilhører en vagtplan. En del en arbejdsvej, som en',
  'anden har lagt. En del en fødevareindustri, der udmærket ved, hvilken',
  'blanding af fedt, sukker og salt der får en til at blive ved med at',
  'spise, selv om man er mæt. En del en reklame, der retter sig mod børn.',
  'En del et takstsystem, hvor der står syv et halvt minut. En del et',
  'boligmarked, der afgør, om der foran din dør er en vej eller en sti.',
  '',
  '**Derfor er dette kapitel ikke færdigt med min stemme.** Jeg',
  'fortæller den simple medicin indefra — ud fra livet, ud fra',
  'synsvinklen hos den, der tager trappen eller ikke tager den. Det er',
  'den ene halvdel, og det er den halvdel, der har tendens til at',
  'undervurdere forholdene.',
  '',
  '**Dette kapitels anden stemme er forholdenes stemme.** Den vil tale',
  'om strukturerne: om industrien, om reklamen, om arbejdslivet, om',
  'fattigdommen — og om spørgsmålet, hvorfor et system, der betaler hver',
  'pille, ikke betaler rådet. Den vil holde mig for øje, at mit program',
  'forudsætter mennesker, der råder over deres dag. Indvendingen er',
  'berettiget. **Jeg har noteret den ovenfor selv, men jeg har skrevet',
  'den mindre, end den er.**',
  '',
  'Begge stemmer er ligeværdige. Rækkefølgen er tilfældig og ingen',
  'rangordning. Læs begge, før du danner dig en mening.',
  '',
  '## Broen til næste kapitel',
  '',
  'Tilbage er det spørgsmål, som dette kapitel giver videre til det',
  'næste.',
  '',
  'Alt, hvad der står her, er praktisk talt gratis. At gå koster intet.',
  'Linser koster lidt. Et opkald til en gammel ven koster intet. Efter',
  'tallene fra Potsdam ligger der i det mere sundhed end i de fleste',
  'præparater, der nogensinde er blevet godkendt.',
  '',
  '**Og alligevel løber udviklingen i den anden retning.** Kapitel 19 i',
  'denne bog vil fortælle om kløften: om en medicin, hvor der for de få',
  'vil være meget muligt — dyrkede organer, genanalyser, konstant',
  'overvågning af den egen krop — og for flertallet allerede af',
  'omkostningsgrunde lidt.',
  '',
  'Hvis det kommer sådan, får dette kapitel en anden betydning, og jeg',
  'ved ikke, om den er den bedre eller den bitre:',
  '',
  '**Er den simple medicin medicinen for alle — eller bliver den det,',
  'der bliver tilbage for de mange, når højteknologien er blevet for',
  'dyr?**',
  '',
  'Jeg har intet svar på det. Jeg ved kun: Den, der i dag begynder at',
  'tage trappen, venter ikke på beslutningen.',
].join('\n');

const stimmeDerVerhaeltnisse = [
  '## De samme timer, set udefra',
  '',
  'Den første stemme har talt om de 8.758 timer, som om de var dine. Jeg',
  'ser de samme timer — blot udefra. Og udefra ser de anderledes ud:',
  'ikke som din dag, men som en dag, der bliver tildelt dig. Stykke for',
  'stykke, af institutioner, der er større end dig. Før du altså',
  'spørger, hvad du gør med dine timer, besvarer jeg det spørgsmål, som',
  'den første stemme ikke stillede:',
  '',
  '**Hvem ejer virkelig de 8.758 timer?**',
  '',
  'Svaret er ubehageligt, fordi det er upersonligt. De tilhører dig kun',
  'delvist. Og den del, der ikke tilhører dig, er ikke din skyld — men',
  'den er heller ikke tilfældig. Den er resultatet af beslutninger, som',
  'andre traf for dig, før du blev født: hvordan den by, du bor i, blev',
  'bygget; hvad der sælges på det næste hjørne; hvor meget din',
  'arbejdstid er værd; og hvad din sygekasse betaler, når du bliver syg.',
  '',
  'Jeg fortæller denne side, fordi den første stemme har skrevet den',
  'lille. Ikke af ondskab — af synsvinkel. Indefra ser man ikke den væg,',
  'man løber imod. Jeg er væggen.',
  '',
  '## Hvem timerne tilhører',
  '',
  'Begynd med arbejdet — den største blok af de vågne timer.',
  '',
  '**En erhvervsaktiv tilbringer omkring en tredjedel af sit liv på',
  'arbejde.** Men tallet fortier det egentlige: hvem tiden tilhører i',
  'løbet af disse timer. Den tilhører arbejdsgiveren. Han køber ikke kun',
  'håndtagene, han køber tiden på dagen — og med den søvnen, måltiderne,',
  'bevægelsen og roen, der skal bygges op omkring arbejdstiden.',
  '',
  'Den, der står op klokken seks, står ved maskinen klokken syv, har en',
  'kvarters pause klokken ti og kommer hjem klokken atten, har ingen',
  '„livsstil". Han har en dagsplan, som en anden har skrevet. Og den,',
  'der begynder klokken toogtyve og holder op klokken seks, hans krop',
  'lever imod sit eget ur — ikke af sløseri, men fordi økonomien, han',
  'arbejder i, ikke sover. Hospitaler, logistik, gastronomi, pleje: En',
  'voksende del af arbejdslivet kører døgnet rundt, og de mennesker, der',
  'holder det kørende, kan ikke vælge deres rytme. De kan kun holde den',
  'ud.',
  '',
  'Dertil kommer siddetiden. **Den moderne arbejdsplads er en',
  'siddeplads.** Skrivebord, rat, kasse, skærm: De fleste erhverv har',
  'taget kroppen ud af arbejdet. Den, der sidder i otte timer, kan',
  'bagefter ikke bare „bygge mere bevægelse ind" — dagen er fuld. Trappen',
  'i stedet for elevatoren er en god begyndelse; den er imidlertid ingen',
  'kompensation for en arbejdsuge, der går med at sidde. Det er ingen',
  'bebrejdelse mod den enkelte. Det er en beskrivelse af, hvem timerne',
  'tilhører.',
  '',
  '## Hvem der råder over dem: det byggede miljø',
  '',
  'Efter arbejdet kommer vejen, og vejen er blevet bygget — af',
  'mennesker, der har besluttet, hvordan byer ser ud.',
  '',
  '**Den europæiske efterkrigsby blev bygget om til bilen.** Gangstier',
  'blev til reststrækninger, kryds til forhindringsbaner, bykerner til',
  'parkeringspladser. Den, der i dag vil gå i mange egne, går langs veje,',
  'der er bygget til firs kilometer i timen. Den, der cykler, kæmper mod',
  'trafikken, som byplanlægningen selv har inviteret ind. Det er ingen',
  'naturkatastrofe. Det har været en beslutning — og beslutninger kan man',
  'ændre, selv om det tager årtier.',
  '',
  'Og så er der det sted, hvor de fleste mennesker køber deres',
  'madvarer. **Supermarkedet er et bygget miljø med sine egne love.**',
  'Friskvaredisken ligger bagerst, for at man skal gå gennem hylderne;',
  'slikket ligger i børnehøjde ved kassen; den „sunde" hylde står ved',
  'siden af den, der skal modbevise den. Den, der træt fra arbejde',
  'handler ind, køber det, der går hurtigst og reklamerer højest — ikke',
  'det, der mætter længst. I egne, hvor der ikke findes nogen butik med',
  'friske grøntsager, men kun tankstationsbutikker og fastfoodsteder,',
  'taler forskere om „madørkener". Ordet lyder overdrevet, indtil man har',
  'boet der.',
  '',
  'Og endelig skærmene — de nyeste, der råder over timerne. **De er ikke',
  'neutrale.** Den opmærksomhed, de binder, bliver målt, gemt og solgt.',
  'De apps, der fylder dine aftener, er optimeret til at fylde dine',
  'aftener; hver time, du forærer, er en indtægt for nogen. Også det er',
  'et forhold, som den simple medicin ikke kender: Pillen virker i',
  'kroppen, skærmen virker på det sted, hvor dine gode forsætter bor.',
  '',
  '## Hvem der tjener på dem: tallerkenen',
  '',
  'Nu til det, den første stemme kaldte „hvad der kommer ind hver dag".',
  'Hun har ret — og hun har udeladt halvdelen: hvem der fremstiller det,',
  'der kommer ind.',
  '',
  '**En stor del af maden i supermarkedet er ikke blevet tilberedt, men',
  'formuleret.** Fødevareteknologer udvikler produkter, så fedt, sukker',
  'og salt lander i en blanding, som kroppen ikke længere genkender som',
  '„mæt". I branchen har dette punkt et navn: „bliss point" — det',
  'øjeblik, hvor en formulering smager mest uimodståeligt. Begrebet',
  'stammer fra produktudviklingen, ikke fra køkkenet. Det beskriver',
  'ingen opskrift, men en hensigt.',
  '',
  'Forskningen har gjort denne hensigt synlig. **NOVA-klassifikationen',
  'inddeler fødevarer efter forarbejdningsgraden** — ikke efter',
  'næringsstoffer. Ultraforarbejdede produkter indeholder stoffer, der',
  'ikke findes i noget køkken: emulgatorer, stabilisatorer, aromaer,',
  'sødestoffer i tekniske kombinationer. Og undersøgelserne er entydige i',
  'en retning: Jo større andelen af ultraforarbejdet kost er, desto mere',
  'spiser mennesker, uden at mærke det. Den første stemme citerede Kevin',
  'Halls forsøg — jeg henviser blot dertil og spørger videre: **Hvorfor',
  'står der i et land med fødevarelove et produkt, der påvist overlister',
  'mæthedsfornemmelsen, på hver hylde — og næsten aldrig en advarsel ved',
  'siden af?**',
  '',
  'Svaret har med penge at gøre, og det er ingen hemmelighed.',
  '**Fødevare- og drikkevareindustrien bruger hvert år milliarder på',
  'reklame** — en mangefold af det, alle regeringer tilsammen bruger på',
  'sundhedsoplysning. En betydelig del af denne reklame retter sig',
  'udtrykkeligt mod børn: farverige emballager, figurer, overraskelser,',
  'samlebilleder. Børn kan ikke læse næringsdeklarationer, men de kan',
  'genkende figurer — og de lærer mærkerne, før de lærer at læse.',
  'Verdenssundhedsorganisationen har i årevis anbefalet at begrænse',
  'reklame for usund mad over for børn; der er sket lidt, fordi reklamen',
  'forsvarer sig.',
  '',
  'Og toppen er „health washing": **Produkter, der gør tyk, bliver',
  'solgt som et bidrag til sundheden.** „Med kostfibre", „Uden tilsat',
  'sukker", „Naturlige ingredienser" — det er ikke udsagn om produktet,',
  'men om kundernes længsel. Emballagen taler om vitalitet, indholdet',
  'taler om fedt, sukker og salt. Begge dele kan man købe samtidig. Det',
  'kaldes markedsføring, og det hører til de timer, der ikke tilhører',
  'dig: De tjenes ved kassen.',
  '',
  '## Hvem der tjener på dem: reklamen',
  '',
  'Reklamen selv er en selvstændig forretning på dine timer.',
  '',
  '**Opmærksomhed er blevet en forretning.** Hvert minut, et menneske',
  'ser på en skærm, bliver talt, bundtet og solgt til den højestbydende',
  'hensigt. Den første stemme nævnte lægen, der på syv et halvt minut',
  'taler imod en reklame, der kører fireogtyve timer. Jeg supplerer',
  'mekanikken: De fireogtyve timer er ikke tilfældigt der. De er blevet',
  'købt — med viden om, hvornår du er træt, hvornår du er sulten, og',
  'hvornår du føler dig alene. De algoritmer, der fylder din fritid, har',
  'lært, i hvilket humør du gør modstand, og i hvilket ikke.',
  '',
  'Det lyder som konspiration, men er simpel markedsøkonomi: **Hvor',
  'opmærksomhed er råstoffet, bliver mennesket til en forekomst.** Det',
  'bliver ikke hadet, det bliver brugt — venligt, professionelt og',
  'døgnet rundt. Mod denne infrastruktur har den simple medicin intet',
  'våben, så længe den kun rådgiver den enkelte. „Sluk fjernsynet" er et',
  'godt råd og en magtesløs sætning: Den forudsætter, at man kan slukke',
  'apparatet uden at miste forbindelsen.',
  '',
  '## Hvem der tjener på dem: pillen',
  '',
  'Og så det spørgsmål, hele kapitlet kredser om: **Hvorfor udskriver',
  'medicinen piller i stedet for livsstil?**',
  '',
  'Den første stemme har svaret: Fordi konstruktionen vil det sådan. Jeg',
  'går et skridt videre og viser konstruktionen.',
  '',
  '**Medicinen bliver ikke betalt for at forandre timer — den bliver',
  'betalt for at behandle diagnoser.** En læge i Tyskland afregner efter',
  'en takstkatalog, der fastlægger, hvad en ydelse er værd: samtalen,',
  'undersøgelsen, recepten. I denne katalog er livsstilsrådet en dårlig',
  'investering: Det varer længe, det er ikke dokumenterbart, det er ikke',
  'kontrollerbart — og det bliver næsten ikke honoreret. Recepten',
  'derimod er hurtig, entydig, fakturerbar og efterprøvelig. **Systemet',
  'betaler for det, det kan måle, og måler ikke det, det ikke betaler.**',
  '',
  'Dertil kommer ansvaret. **En læge hæfter for den pille, han',
  'ordinerer — for det råd, han giver, hæfter ingen.** Den, der',
  'ordinerer et lægemiddel, har truffet en dokumenteret beslutning, der',
  'i tvivlstilfælde kan efterprøves. Den, der anbefaler en livsstil, har',
  'udtalt et håb, som ingen kan kontrollere. I en medicin, der sikrer',
  'sig mod fejl, vinder pillen, fordi den kan sikres. Det er ingen ond',
  'hensigt hos enkelte læger. Det er logikken i det system, de arbejder',
  'i.',
  '',
  'Og endelig efteruddannelsen. **En betydelig del af lægernes',
  'efteruddannelse finansieres af medicinalindustrien** — kapitlerne i',
  'denne bog om industriens finansielle interesser har redegjort for det.',
  'Foredragene om bevægelse, kost og stress finansieres derimod ikke af',
  'nogen, for de sælger intet produkt. Et system, der næres af',
  'industrien, lærer industriens sprog: Det tænker i virkestoffer, ikke i',
  'ugeplaner. Den, der spørger, hvorfor pillen slår rådet, behøver ikke',
  'at begynde hos lægerne. Han må begynde ved kataloget, ved ansvaret og',
  'ved efteruddannelsen.',
  '',
  '## Fattigdommen er et forhold',
  '',
  'Den første stemme har erkendt, at penge og tid er ulige fordelt. Jeg',
  'skærper det: **Fattigdom er ingen fodnote i livsstilsmedicinen, den',
  'er dens hårdeste prøve.**',
  '',
  'Den, der har få penge, køber det billigste — og det billigste er',
  'næsten altid det mest forarbejdede, fordi forarbejdning betyder',
  'holdbarhed, og holdbarhed sparer transportomkostninger. Den, der har',
  'lidt tid, køber det hurtigste — og det hurtigste er næsten altid det',
  'færdigste. **Den simple medicin er for mennesker med tid og penge',
  'faktisk simpel; for de andre er den en ekstra opgave på en dag, der',
  'allerede er fuld.**',
  '',
  'Dertil kommer den stress, der følger med fattigdom: angsten for',
  'regningen, for tabet af jobbet, for månedens udgang. Forskningen',
  'taler om allostatisk belastning — den nedslidning, som et konstant',
  'tilpasningspres efterlader i kroppen. Kronisk stress er ingen luner,',
  'men en tilstand, der påvist virker ind i kroppen: i blodtrykket, i',
  'søvnen, i inflammationsmarkørerne. Og mod denne stress hjælper hverken',
  'en recept eller et råd — den hjælper kun væk, og væk er den sjældent.',
  '',
  '**Den, der vil følge den simple medicin, behøver ikke kun vilje. Han',
  'behøver råderum.** Og råderum er det, fattigdom fjerner mest',
  'pålideligt. At sige det er ingen undskyldning, det er en beskrivelse.',
  'Spørgsmålet er kun, for hvem beskrivelsen er mest ubehagelig: for den,',
  'der hører den, eller for den, der har brug for den.',
  '',
  '## Hvad jeg holder imod den første stemme',
  '',
  'Nu den indvending, som den første stemme selv har annonceret.',
  '',
  '**Hendes program forudsætter mennesker, der råder over deres dag.**',
  'Hun har erkendt det, og jeg siger det endnu en gang, fordi det er',
  'kernen: Den, der ikke kan bestemme, hvornår han sover, hvornår han',
  'spiser, og hvornår han bevæger sig, for ham er sætningen „Det kan',
  'enhver gøre på eget ansvar" simpelthen forkert. Den er ikke ment ondt',
  '— den er talt fra et ståsted, hvor dagen tilhører én.',
  '',
  '**Min anden indvending angår trappen.** Den første stemme slutter med',
  'sætningen: „Den, der i dag begynder at tage trappen, venter ikke på',
  'beslutningen." Smukt sagt — men hvem har bygget trappen? Hvem',
  'bestemmer, om der foran døren er en trappe eller en firesporet vej, om',
  'elevatoren i nybyggeriet er pligt, og om arbejdsvejen kan gås eller',
  'kun tilbagelægges i kø? Trappen er den simple medicins symbol, fordi',
  'den altid er der. Men den er også symbolet på det, den første stemme',
  'overser: **Trapper bliver bygget eller ikke bygget — det er en',
  'beslutning fra forholdene.**',
  '',
  'Og min tredje indvending er den stilleste og den vigtigste: **Den',
  'første stemme taler om „menneskerne", som om de var tilskuere til',
  'deres eget liv.** Men menneskene er ikke kun dem, der tager trappen',
  'eller ikke tager den. De er også dem, der bygger trappen, skriver',
  'vagtplanerne, fylder hylderne, sælger annoncerne og udsteder',
  'recepterne. Den simple medicin er ingen sag for den enkelte — den er',
  'en sag for alle, der er med til at bygge på timerne. Og der er flere',
  'af dem, end den første stemme vil vedkende sig.',
  '',
  '## Min egen ubehagelige plet',
  '',
  'Nu det, jeg lader holde mig selv for øje — for den første stemme er',
  'ikke den eneste med blinde pletter.',
  '',
  '**Min første blinde plet: Forholdene er skabt af mennesker — og',
  'mennesker kan man ændre.** Nordkarelen har vist, at det kan lade sig',
  'gøre: Der ændrede ikke enkelte patienter deres vaner, men mejerier,',
  'pølseproducenter og landsbyforeninger deres produkter og deres kultur.',
  'Hvis jeg lader, som om forholdene er en naturlov, gør jeg af en',
  'politisk opgave en undskyldning. Og undskyldninger er det sidste, de',
  'mennesker har brug for, der lider under forholdene.',
  '',
  '**Min anden blinde plet: Også jeg tjener på timerne.** De forhold, jeg',
  'beskriver, er intet fremmed væsen — de er summen af meget mange små,',
  'forståelige beslutninger. Industrien leverer, hvad der sælges.',
  'Reklamen sælger, hvad der finder opmærksomhed. Politikken afspejler,',
  'hvad der vælges. Og jeg? Jeg spiser også færdigpizza, når det skal gå',
  'hurtigt; jeg scroller også om aftenen; jeg handler også i',
  'discountbutikken. Den, der anklager forholdene, bør ikke lade, som om',
  'han stod uden for dem.',
  '',
  '**Og min tredje blinde plet er den hårdeste: Akutmedicinen er et',
  'vidunder.** Den har gjort de timer, som dette kapitel handler om,',
  'mulige for millioner af mennesker — pacemakerne, antibiotikaene,',
  'operationerne, akuthjælpen. Den, der tegner pillen som fjende af den',
  'simple medicin, glemmer, at pillen ofte er grunden til, at der stadig',
  'er nogen til at tage trappen. Min strid med den første stemme er ikke',
  'striden mellem godt og ondt. Det er striden mellem to sandheder, der',
  'begge gælder: **Den enkelte kan noget — og den enkelte kan ikke',
  'alt.**',
  '',
  '## Døren tilbage',
  '',
  'Jeg har beskrevet timerne udefra: hvem de tilhører, hvem der råder',
  'over dem, hvem der tjener på dem. Den første stemme har beskrevet dem',
  'indefra: hvad kroppen vil, hvad tallerkenen kan, hvad nærheden',
  'formår.',
  '',
  '**Vi har ikke skændtes om dokumentationen.** At bevægelse, kost og',
  'tilknytning virker, bestrider jeg ikke. Vi skændes om, hvem der kan',
  'gøre noget ved det. Den første stemme siger: Du. Jeg siger: Du — og',
  'dem, der råder over din dag. Begge har ret, og begge tager fejl, når',
  'de fortier den anden del.',
  '',
  '**Den, der kun peger på forholdene, forærer de 8.758 timer væk. Den,',
  'der kun peger på sig selv, fortier forholdene.** Syntesen i dette',
  'kapitel må afgøre, hvad der følger deraf — for den enkelte, for',
  'medicinen og for dem, der råder over timerne.',
  '',
  'Jeg har talt. Nu er syntesen på banen.',
].join('\n');

const einfacheMedizin = {
  id: 'einfache-medizin',
  titel: 'Den simple medicin',
  epoche: 'i dag',

  aufhaenger: {
    frage:
      'Hvis bevægelse, simpel mad og gode naboer påvist virker — ' +
      'hvorfor står det så sjældent på en recept?',
    text: [
      'Et menneske med en kronisk sygdom tilbringer om året omkring to timer',
      'hos læger. Året har 8.760 timer. I de øvrige 8.758 sker det, som',
      'dette kapitel handler om: vejen til busstoppestedet, tallerkenen om',
      'aftenen, natten, menneskene ved bordet.',
      '',
      'Tallene dertil er der, og de er ikke små.',
      'Verdenssundhedsorganisationen regner omkring 41 millioner dødsfald om',
      'året — cirka 74 procent af alle dødsfald på verdensplan — til de',
      'ikke-smitsomme sygdomme og nævner som fælles risici tobak, usund kost,',
      'mangel på bevægelse og alkohol. En Potsdam-undersøgelse af 23.153',
      'mennesker fandt i 2009: Den, der ikke ryger, ikke er for tung,',
      'bevæger sig regelmæssigt og spiser fornuftigt, har en 78 procent',
      'lavere risiko for at få en alvorlig kronisk sygdom.',
      '',
      'Forfatteren af denne bog, selv naturlæge, har lavet en tese deraf:',
      'Behandlingen af kroniske sygdomme skulle egentlig være meget enkel —',
      'bevægelse, afbalanceret kost med lidt forarbejdet mad, et godt',
      'socialt miljø og lidt stress. „Det kræver ingen raketvidenskab."',
      '',
      'Dette kapitel prøver tesen fair — med de undersøgelser, der taler for',
      'den, og med dem, der taler imod den. Og det stiller det ubehagelige',
      'spørgsmål, det egentlig handler om: Hvorfor udskriver medicinen piller',
      'i stedet for livsstil? Ligger det hos lægerne, hos patienterne —',
      'eller hos de forhold, som begge er fanget i?',
    ].join('\n'),
  },

  // Kortet ligger i karten/einfache-medizin.js — her er kun
  // fasehenvisningerne oversat (karteHinweise), ikke selve kortet.
  karteHinweise: [
    {
      label: '1948: Framingham — fødslen af ordet „risikofaktor"',
      hinweis:
        'I den lille by Framingham vest for Boston begynder i 1948 en ' +
        'undersøgelse, som der ikke har været mage til: 5.209 raske ' +
        'voksne bliver optaget og hvert andet år undersøgt igen — ' +
        'blodtryk, vægt, rygevaner, blodværdier —, og så venter man på, ' +
        'hvem der bliver syg. Ikke de syge bliver adspurgt, men de raske ' +
        'bliver fulgt. Fra denne undersøgelse stammer begrebet ' +
        '„risikofaktor" (1961), og fra den stammer erkendelsen, at ' +
        'forhøjet blodtryk, rygning og højt blodfedt går forud for ' +
        'hjerteinfarktet. Undersøgelsen kører den dag i dag, nu i tredje ' +
        'generation.',
    },
    {
      label: '1958: Syv-lande-undersøgelsen — 12.763 mænd i 16 byer',
      hinweis:
        'Den amerikanske fysiolog Ancel Keys havde i Napoli observeret, ' +
        'at hjerteinfarkt var sjældent, hvor mennesker var fattige og ' +
        'spiste enkelt. Fra 1958 prøver han det systematisk: 12.763 mænd ' +
        'mellem 40 og 59 år, i 16 kohorter i syv lande — Finland, ' +
        'Grækenland, Italien, Japan, Nederlandene, USA og Jugoslavien. ' +
        'Resultat efter årtier: Dødeligheden af hjertesygdom varierer ' +
        'mellem stederne med en mangefold, lavest på Kreta og i Japan, ' +
        'højest i Østfinland. Kritikken hører med: Undersøgelsen ' +
        'sammenlignede steder, ikke personer, og Keys blev senere ' +
        'beskyldt for at have lagt for lidt vægt på sukkeret.',
    },
    {
      label: '1972: Nordkarelen — den første provins, der ændrer sin livsstil',
      hinweis:
        'Nordkarelen i det østlige Finland havde i begyndelsen af ' +
        '1970erne verdens højeste hjerteinfarktdødelighed. I 1972 ' +
        'begynder der et projekt, der ikke behandler enkelte mennesker, ' +
        'men en hel provins: Lægen Pekka Puska og hans team arbejder med ' +
        'landsbyer, husmorforeninger, mejerier og pølseproducenter — ' +
        'mindre salt, mindre animalsk fedt, mere grønt, mindre rygning. ' +
        'I 1977 udvides projektet til hele Finland. Mellem 1972 og 2012 ' +
        'falder hjerteinfarktdødeligheden blandt mænd i den ' +
        'erhvervsaktive alder i Nordkarelen med omkring 80 procent. Det ' +
        'var intet forsøg med kontrolgruppe — tilbagegangen skete i hele ' +
        'Europa, i Nordkarelen bare tidligere og stejlere.',
    },
    {
      label: '2004: de „blå zoner" — fem egne fulde af gamle mennesker',
      hinweis:
        'Begrebet stammer fra befolkningsforskerne Gianni Pes og Michel ' +
        'Poulain, der i 2004 på et kort over Sardinien omkredsede ' +
        'kommunerne med særligt mange 100-årige med blåt. Journalisten ' +
        'Dan Buettner gjorde det fra 2005 for National Geographic til fem ' +
        'områder: Ogliastra på Sardinien, Okinawa, Ikaria, halvøen Nicoya ' +
        'og adventistsamfundet Loma Linda i Californien. Fælles er hverken ' +
        'en diæt eller en sport, men et mønster: bevægelse i dagligdagen, ' +
        'overvejende plantebaseret kost, faste sociale bånd, opgave i ' +
        'alderdommen. Kritikken hører med på samme kort: Demografen Saul ' +
        'Justin Newman viste, at høje 100-års-kvoter ofte falder sammen ' +
        'med dårlige fødselsregistre.',
    },
    {
      label: 'Fra 2017: livsstilsmedicinen bliver et fag — og et marked',
      hinweis:
        'Af observationen bliver en behandling. I 2017 og 2018 viser den ' +
        'britiske DiRECT-undersøgelse i praktiserende lægers praksis i ' +
        'Skotland og Nordengland, at en type 2-diabetes kan gå tilbage ' +
        'gennem vægttab: efter tolv måneder hos 46 procent af ' +
        'deltagerne, efter 24 måneder hos 36 procent — mod 4 og 3 ' +
        'procent ved den sædvanlige behandling. Samtidig bliver den ' +
        'enkle idé til en forretning: ernæringsrådgivning, fastekure, ' +
        'kosttilskud, fitness-abonnementer, selvmåling. Verdens billigste ' +
        'medicin får en pris.',
    },
  ],

  perspektiven: [
    {
      id: 'alltag',
      name: 'Hverdagens stemme',
      stimme: 'Opus',
      text: stimmeDesAlltags,
    },
    {
      id: 'verhaeltnisse',
      name: 'Forholdenes stemme',
      stimme: 'DeepSeek',
      text: stimmeDerVerhaeltnisse,
    },
  ],

  synthese: [
    '**Denne syntese er kapitlet tredje stemme: den holder fast i, hvad',
    'de to andre har ramt, og nævner, hvad de er uenige om.**',
    '',
    '**Hvor de mødes.** De skændes ikke om dokumentationen. Hverdagens',
    'stemme har nævnt tallene, der taler for den simple medicin —',
    'Potsdam-undersøgelsen med dens 78 procent, diabetes-',
    'forebyggelsesprogrammet, Nordkarelen — og hun har selv nævnt de',
    'undersøgelser, der taler imod: Look AHEAD, det vakkelvorne fundament',
    'for de blå zoner. Forholdenes stemme har ikke bestridt denne',
    'dokumentation; hun har spurgt, under hvilke betingelser man kan følge',
    'den. Begge har selv udtalt deres ubehagelige pletter: den ene, at',
    'hendes tilbud hurtigt bliver til en bebrejdelse; den anden, at',
    'forholdene er skabt af mennesker — og at hun selv er en del af dem.',
    '',
    '**Hvad de er uenige om.** De er uenige om ét eneste spørgsmål: Hvem',
    'kan omsætte det? Hverdagens stemme siger: Du — de 8.758 timer er',
    'dine, og den, der begynder i dag, venter ikke på beslutningen.',
    'Forholdenes stemme siger: Du — og dem, der råder over din dag; den,',
    'der ikke har bygget trappen, kan heller ikke tage den. Det er ingen',
    'strid mellem sandt og falsk. Det er striden mellem to sandheder, der',
    'begge gælder: **Den enkelte kan noget — og den enkelte kan ikke',
    'alt.**',
    '',
    '**Hvad det betyder for denne bog.** Tænkemåden bestemmer metoden.',
    'Medicinen tænker i diagnoser, virkestoffer og fakturerbare ydelser —',
    'derfor udskriver den pillen. Livsstilsmedicinen tænker i timer, vaner',
    'og forhold — derfor har den ingen afregningskode. Den simple medicin',
    'er ingen raketvidenskab, men den er heller ingen recept. Den er en',
    'forhandling mellem mennesket og dets omgivelser. Den, der kun lægger',
    'den på den enkelte, gør af et tilbud en skyld. Den, der kun lægger',
    'den på forholdene, forærer de timer væk, der virkelig ligger i ens',
    'egen hånd. Det ene er unfair, det andet er en undskyldning — og',
    'dette kapitel har nævnt begge, for at læseren ikke tror på nogen af',
    'dem.',
    '',
    '**Broen til næste kapitel.** Og så er der det spørgsmål, som dette',
    'kapitel giver videre til det næste: Hvis morgendagens medicin bliver',
    'dyr og forbeholdt de få — dyrkede organer, genanalyser, konstant',
    'overvågning —, bliver den simple medicin så medicinen for alle?',
    'Eller den, der bliver tilbage for de mange, når kløften mellem rig',
    'og fattig åbner sig? Begge stemmer i dette kapitel har nævnt den',
    'samme bekymring med forskellige ord. Kapitel 19 vil vise kløften.',
  ].join('\n'),

  urteil: {
    frage:
      'Hvorfor er den simple medicin så svær at udskrive — og hvem ' +
      'skulle ændre noget, for at den når frem?',
    hinweis: [
      'Der er her intet rigtigt og intet forkert. Hold de to sider side om',
      'side. Den ene: Fire enkle kendetegn — ikke ryge, ikke være for tung,',
      'bevæge sig, spise fornuftigt — hang i Potsdam-undersøgelsen sammen',
      'med en 78 procent lavere risiko for alvorlige kroniske sygdomme. Det',
      'når intet lægemiddel. Den anden: Et råd er ingen behandling;',
      'Look-AHEAD-undersøgelsen fandt efter næsten ti år ingen forskel ved',
      'hjerteinfarkter; og den, der arbejder i skiftehold eller har to',
      'jobs, kan ikke vælge sin dag. Spørg dig selv om tre ting. For det',
      'første: Hvad af de tre søjler — bevægelse, mad, mennesker omkring',
      'dig — ligger faktisk i din hånd, og hvad gør ikke? For det andet:',
      'Når en læge har syv et halvt minut, hvad kan han så realistisk gøre',
      'i den tid — udstede en recept eller sætte en livsændring i gang?',
      'For det tredje: Når det mest virksomme næsten ikke koster noget —',
      'hvem har så gavn af, at det alligevel så sjældent ordineres?',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Hvad undersøgte lægen Jeremy Morris i 1953 ved Londons ' +
        'buskonduktører og buschauffører?',
      antworten: [
        'Om trafikstøj øger blodtrykket.',
        'Om konduktørerne, der hele dagen løb op og ned ad trappen i ' +
          'dobbeltdækkeren, fik færre hjerteinfarkter end de siddende ' +
          'chauffører.',
        'Om skifteholdsarbejde sænker den forventede levetid.',
      ],
      richtig: 1,
      erklaerung:
        'Morris sammenlignede to faggrupper i samme firma, der lignede ' +
        'hinanden i næsten alt og adskilte sig i bevægelsen. ' +
        'Konduktørerne fik omkring halvt så mange hjerteinfarkter som ' +
        'chaufførerne og overlevede dem oftere. Han efterprøvede ' +
        'resultatet hos postbud og postekspedienter og fandt samme ' +
        'billede. Offentliggørelsen i Lancet fra 1953 regnes som ' +
        'begyndelsen på forskningen i bevægelse og sundhed.',
    },
    {
      frage:
        'I Potsdam-EPIC-undersøgelsen (opgørelse fra 2009) blev fire ' +
        'kendetegn prøvet: aldrig røget, body mass index under 30, mindst ' +
        'tre en halv times bevægelse om ugen og en plantebaseret kost. ' +
        'Hvor stor var forskellen?',
      antworten: [
        'Den, der opfyldte alle fire, havde en omkring 78 procent lavere ' +
          'risiko for en alvorlig kronisk sygdom.',
        'Den, der opfyldte alle fire, havde en omkring 12 procent lavere ' +
          'risiko.',
        'Der viste sig ingen forskel mellem grupperne.',
      ],
      richtig: 0,
      erklaerung:
        'Undersøgelsen fulgte 23.153 mennesker mellem 35 og 65 år. Den, ' +
        'der opfyldte alle fire kendetegn, havde over for dem uden noget ' +
        'af dem en 78 procent lavere risiko — i enkeltheder 93 procent ' +
        'mindre type 2-diabetes, 81 procent færre hjerteinfarkter, 50 ' +
        'procent færre slagtilfælde og 36 procent mindre kræftsygdom. Det ' +
        'er en observationsundersøgelse, ikke et forsøg med lodtrækning.',
    },
    {
      frage:
        'Hvad skete der i Kevin Halls og hans gruppes forsøg (2019), hvor ' +
        'tyve mennesker fik to uger med ultraforarbejdet og to uger med ' +
        'uforarbejdet kost?',
      antworten: [
        'Menneskerne spiste lige meget i begge faser.',
        'I ugerne med ultraforarbejdet kost spiste de omkring 500 ' +
          'kilokalorier mere om dagen og tog på.',
        'Den uforarbejdede kost gjorde deltagerne mere sultne.',
      ],
      richtig: 1,
      erklaerung:
        'Begge madplaner var afbalancerede efter næringsstoffer, og ' +
        'deltagerne måtte spise, så meget de ville. I de ultraforarbejdede ' +
        'uger spiste de samme mennesker omkring 500 kilokalorier mere om ' +
        'dagen og tog i gennemsnit næsten et kilo på, i de uforarbejdede ' +
        'uger tog de næsten et kilo af. Forsøget fandt sted på afdelingen, ' +
        'for at alt det spiste kunne registreres.',
    },
    {
      frage:
        'Hvor stammer begrebet „blå zoner" fra for egne med særligt mange ' +
        'meget gamle mennesker?',
      antworten: [
        'Fra havets blå farve ved de pågældende kyster.',
        'Fra en reklamekampagne fra Verdenssundhedsorganisationen.',
        'Fra Gianni Pes og Michel Poulain, der i 2004 på et kort over ' +
          'Sardinien omkredsede kommunerne med flest 100-årige med en blå ' +
          'pen.',
      ],
      richtig: 2,
      erklaerung:
        'Af disse blå cirkler blev der fra 2005 gennem journalisten Dan ' +
        'Buettner den kendte række af fem områder: Sardinien, Okinawa, ' +
        'Ikaria, Nicoya og Loma Linda. Fundet er omstridt: Demografen ' +
        'Saul Justin Newman viste, at høje 100-års-kvoter ofte falder ' +
        'sammen med mangelfulde fødselsregistre; for det fik han i 2024 ' +
        'Ig-Nobelprisen.',
    },
    {
      frage:
        'Look-AHEAD-undersøgelsen (2013) prøvede ved 5.145 overvægtige ' +
        'mennesker med type 2-diabetes et intensivt livsstilsprogram. ' +
        'Hvad var hovedresultatet?',
      antworten: [
        'Livsstilsgruppen havde markant færre hjerteinfarkter og ' +
          'slagtilfælde.',
        'Livsstilsgruppen tabte mere vægt og havde bedre værdier, men ' +
          'efter i gennemsnit 9,6 år ikke færre alvorlige hjerte-',
          'karhændelser.',
        'Programmet skadede deltagerne, hvorfor undersøgelsen blev ' +
          'afbrudt.',
      ],
      richtig: 1,
      erklaerung:
        'Undersøgelsen blev afsluttet før tid, fordi det tegnede sig til, ' +
        'at der ikke længere var nogen forskel at vente ved hovedmålet — ' +
        'ikke på grund af skader. Livsstilsgruppen havde mindre vægt, mere ' +
        'bevægelighed, sjældnere nyresygdomme og sjældnere depressioner. ' +
        'En mulig grund til den udeblevne forskel ved hjerteinfarkt: Også ' +
        'sammenligningsgruppen blev godt behandlet medicinsk og ændrede ' +
        'sin adfærd. Bevist er denne forklaring ikke.',
    },
  ],
};

module.exports = einfacheMedizin;
