// Kapitel 4 — „Hippokrates og Galen".
//
// Den europæiske rod: to mænd, der aldrig mødtes (der ligger omkring
// fem og et halvt århundrede mellem dem) og som tilsammen bestemte,
// hvordan man i Europa i to tusind år tænkte om sygdom. Den ene satsede
// på observation og indrømmede, at han vidste lidt; den anden byggede
// et lukket system, der besvarede ethvert spørgsmål — og netop derfor
// så længe ikke længere blev sat spørgsmålstegn ved.
//
// Dette kapitel gør, hvad forfatteren af denne bog har forlangt: Det
// analyserer TÆNKEMÅDEN grundigt — ikke kun, HVAD der blev gjort, men
// HVORFOR. Læren om de fire safter som ordenssystem (eukrasi og
// dyskrasi), naturen som helbreder, observationen og prognosen,
// livsstilen som medicin og eden som et fags første selvforpligtelse —
// dertil den ærlige virkningsbalance: hvad der stadig står i dag
// (observation, etik, diætetik, nogle kirurgiske greb) og hvad der i
// århundreder har skadet (åreladning og afføringsmidler, som netop
// fulgte af denne teori).
//
// Stemmer (runde 5): Den FØRSTE synsvinkel — Hippokrates' stemme,
// skolen fra Kos — er skrevet af Opus. Den ANDEN (Galen: systemet,
// anatomien, autoriteten) og den endelige syntese supplerede Hermes i
// anden omgang. Perspektiv-workflow: CLAUDE.md.
//
// INGEN GENTAGELSER (forfatterbeslutning af 21.08.2026): Kapitel 1
// opdeler sine stemmer efter „Hvem taler her → …", kapitel 2 begynder
// med en scene (tre fingre på håndleddet) og fører begrundelseslogikken
// langs „Hvorfor"-overskrifter, kapitel 3 fortæller en dagsrytme. Dette
// kapitel vælger en fjerde dramaturgi: en BREVVEKSLING, der ikke kan
// være én. Skolen fra Kos skriver ni breve til en læge, den ikke
// kender — til den, der kommer efter den. Besvaret bliver de først 550
// år senere af en mand fra Pergamon, der kun kender afsenderen fra
// bøger. Formen er historisk funderet: Corpus Hippocraticum har siden
// antikken haft breve vedlagt, som blev tilskrevet Hippokrates og med
// sikkerhed ikke stammer fra ham. Den første stemme siger det selv.
//
// Teksterne ligger som linje-arrangementer med `.join('\n')` — sådan
// forbliver de i repoet læsbare ved ~72 tegn (forfatteren læser dem op
// imod her), og utils/markdown.js gør dem i appen igen til flydende
// tekst.
//
// CommonJS uden UI-imports (arkitekturregel): kan kontrolleres med
// rent `node`.

/**
 * Hippokrates' stemme — skolen fra Kos.
 *
 * Skrevet af Opus (runde 5). Ni breve til en ukendt efterfølger:
 * verdensbillede, begrundelseslogik, videns oprindelse og
 * virkningsbalance. Den nævner selv de ubehagelige pletter i sin egen
 * fortælling i stedet for at overlade dem til modstemmen (tillægsregel
 * for følsomme emner i CLAUDE.md) — helt til den sætning, at dens egen
 * teori senere har dræbt mennesker.
 */
const stimmeDesHippokrates = [
  '## Det første brev: Til den læge, der kommer efter mig',
  '',
  'Jeg ved ikke, hvem du er. Jeg ved ikke engang, om du vil læse,',
  'hvad vi skriver ned her på Kos. Alligevel skriver jeg til dig, for',
  'et håndværk, der ikke gives videre, dør med den, der kan det.',
  '',
  'Først må jeg tilstå noget ubehageligt, ellers begynder denne',
  'brevveksling med en løgn. **Når du læser „Hippokrates", tænker du',
  'på en mand. Det var mange.** Han har eksisteret, lægen fra Kos; en',
  'filosof ved navn Platon nævner ham, mens han endnu lever, ganske',
  'henkastet, som man nævner en kendt fagmand. Men de omkring tres',
  'skrifter, der senere bærer hans navn, stammer fra forskellige',
  'hænder, fra forskellige årtier, og de modsiger hinanden mange',
  'steder. Nogle er lærebøger, nogle forelæsninger, nogle blotte',
  'notesbøger. Selv de breve, man tillægger mig, er forfattet',
  'århundreder efter min død — også dette her er en form, ikke et',
  'dokument.',
  '',
  'Tag det ikke som en devaluering. Tag det som det første, jeg vil',
  'lære dig: **Prøv, hvem der taler, og stol ikke på noget navn mere',
  'end på sagen.** Jeg taler i disse breve som en skole, ikke som et',
  'orakel. Det, jeg fortæller dig, er ingen sandhed, men en tænkemåde —',
  'den måde, vi i dette hjørne af Det Ægæiske Hav har forsøgt at',
  'forstå sygdom på. Den er til dels forkert. Jeg vil selv sige dig til',
  'sidst, på hvilke punkter.',
  '',
  'Og endnu noget: Jeg er ikke begyndelsen. Forud for os lå århundreder',
  'ved Nilen, hvor læger syede sår, skinnede brud og skrev deres',
  'midler ned; egypterne havde bøger, da vi endnu ikke havde nogen',
  'skrift. Fra Egypten kom en stor del af vores lægekunst, fra',
  'Mesopotamien kom blikket på dagens forløb. Den, der påstår, at',
  'helbredelsen begynder hos os, har kun lært at betragte den herfra.',
  '',
  '## Det andet brev: Om den hellige sygdom',
  '',
  'Der findes en lidelse, som folk kalder den hellige sygdom. Et',
  'menneske styrter til jorden, lemmerne rykker, skum træder frem for',
  'munden, og når det er overstået, ved han intet. Du kender den.',
  'Renselsespræsterne siger, at en gud er faret i ham, og alt efter',
  'hvordan rykningerne ser ud, navngiver de guden.',
  '',
  'En af os har skrevet en slank bog om det, og den begynder med en',
  'sætning, som alt det øvrige afgøres ved: **Den er ikke mere',
  'guddommelig end andre sygdomme. Den har en natur som alle andre og',
  'en årsag.** Den, der kalder den hellig, gør det, hedder det videre,',
  'af rådvildhed — og den, der af rådvildhed påkalder en gud, sælger',
  'sin uvidenhed som fromhed.',
  '',
  'Forstå præcis, hvad der sker her, og hvad der ikke sker.',
  '',
  'Det sker **ikke**, at vi afskaffer guderne. Vi er fromme mennesker;',
  'vores ed begynder med Apollon og Asklepios, og på min egen ø ligger',
  'et stort helligdom, hvor syge sover og venter på en helbredende',
  'drøm. Disse syge kommer i tusindvis. Nogle går helbredte hjem. Jeg',
  'kan ikke bevise, at de fik mindre hjælp end hos mig.',
  '',
  'Der sker noget mindre og mere følgerigt: **Vi ændrer spørgsmålet.**',
  'I stedet for at spørge „Hvilken gud vredes?" spørger vi „Hvad skete',
  'der før, hvad sker der nu, og hvad vil der ske i morgen?". En vred',
  'gud kan man kun formilde. En årsag i naturen kan man observere,',
  'sammenligne med andre tilfælde og måske påvirke. Hele den lægekunst,',
  'du vil arve, hænger på dette ene skridt.',
  '',
  'Det har en pris, og jeg nævner den med det samme: Den, der søger',
  'årsagen i naturen, må holde ud ofte ikke at finde den. Præsten har',
  'altid et svar. Jeg har somme tider intet.',
  '',
  '## Det tredje brev: Om de fire safter',
  '',
  'Nu til den bygning, vi bor i. Du vil senere måtte rive den ned; jeg',
  'vil alligevel, at du forstår, hvorfor vi byggede den.',
  '',
  'Tag friskt blod fra en åre og lad det stå i en skål. Efter et',
  'stykke tid ser du fire lag: øverst en gullig, gennemsigtig væske;',
  'derunder noget hvidt, sejt; derunder det røde blod; og aller nederst',
  'en mørk, næsten sort masse. Fire ting, der synligt træder fra',
  'hinanden. Vi har heraf sluttet, at mennesket består af fire safter:',
  '',
  '- **Blod** — varmt og fugtigt. Det kommer fra hjertet, det er det',
  '  levende, det fremdrivende. For meget heraf gør rød, hed, heftig.',
  '- **Slim** (*flegma*) — koldt og fugtigt. Det kommer fra hovedet.',
  '  Tænk på vinteren, på forkølelsen, på det sejle opspyt. For meget',
  '  heraf gør tung, slov, tilstoppet.',
  '- **Gul galde** — varm og tør. Fra leveren. Den viser sig i feber,',
  '  opkastning, gulsot, vrede. Tænk på højsommeren.',
  '- **Sort galde** — kold og tør. Fra milten. Den er efteråret, det',
  '  mørke, det tunge, tungsindet. Jeg siger dig det med det samme:',
  '  Denne saft har ingen nogensinde set. Vi havde brug for den, for at',
  '  ordningen gik op, og hvad vi kaldte sort galde, var vel størknet',
  '  blod fra et mavesår eller den mørke bundfældning i skålen. Det er',
  '  det svageste punkt i hele bygningen, og jeg nævner det først for',
  '  dig, så du ikke kan sige, at jeg har skjult det.',
  '',
  'Nu reglen, der gør et system ud af disse fire safter:',
  '**Sundhed er ikke fraværet af en saft, men den rette blanding af',
  'alle fire — vi kalder det eukrasi, den gode blanding. Sygdom er den',
  'dårlige blanding: dyskrasi.** En saft er blevet for meget, eller den',
  'sidder det forkerte sted, eller den er fordærvet.',
  '',
  'Hvorfor netop denne forklaring og ingen anden? Fordi den præsterer',
  'fire ting på én gang, og ingen anden forklaring, vi havde,',
  'præsterede blot to af dem.',
  '',
  '**For det første ordner den verden og mennesket efter samme regel.**',
  'Nutidens tænkere siger, at alt består af jord, vand, luft og ild, og',
  'at disse fire bærer egenskaberne varm, kold, fugtig, tør. Vores fire',
  'safter bærer de samme egenskaber. Mennesket er dermed intet',
  'særtilfælde i naturen, men gjort af samme stof som alt andet — og',
  'derfor at behandle med samme midler: med varme, kulde, fugt, tørke.',
  '',
  '**For det andet forklarer den årstiderne.** Om vinteren kommer',
  'katarrene, om foråret næseblodet, om sommeren febrerne og',
  'diarréerne, om efteråret vekselfeberne. Det er ingen teori, det er',
  'erfaringen hos enhver læge, der i ti år skriver ned, hvem der bliver',
  'syg hvornår. Fire safter og fire årstider passer sammen — om',
  'vinteren formerer den kolde, fugtige slim sig, om sommeren den hede,',
  'tørre galde. Vi var dermed de første, der havde en forbindelse',
  'mellem vejr, sted og sygdom, og den var rigtigt set, selv om',
  'begrundelsen var forkert.',
  '',
  '**For det tredje forklarer den, hvorfor mennesker er forskellige.**',
  'Hos den ene overvejer blodet af naturen, hos den anden den sorte',
  'galde. Heraf blev senere de fire temperamenter, som du måske endnu',
  'kender: den blodrige, den slimede, den galdefulde, den tungsindige.',
  'Dermed behandler vi ikke en sygdom, men et bestemt menneske. To',
  'syge med samme feber får hos os forskelligt, fordi de er blandet',
  'forskelligt.',
  '',
  '**For det fjerde giver den lægen noget at gøre, der er',
  'konsekvent.** Er der for meget koldt og fugtigt til stede, så giv',
  'varmt og tørt. Er der for meget af en saft, så hjælp kroppen med at',
  'blive den kvit. Af denne ene regel følger alt det øvrige — og, det',
  'siger jeg allerede her, af den følger også den ulykke, som det',
  'niende brev skal handle om.',
  '',
  'Har du rejst meget, vil noget falde dig i øjnene. Ved Nilen',
  'fortæller lægerne om kanaler i kroppen, der kan tilstoppes. Længere',
  'mod øst, hører man, taler de om en ånde, der skal flyde, og om to',
  'kræfter, der skal stå i ligevægt; endnu længere mod øst om tre',
  'kræfter, som et menneske bringer med sig i sit eget mål. Og vi taler',
  'om fire safter, der skal blandes rigtigt. **Fire sprog, én tanke:',
  'Sundhed er ligevægt, sygdom er forstyrrelsen af den.** Jeg tror',
  'ikke, at vi har skrevet af efter hinanden. Jeg tror, at mennesker,',
  'der ser godt efter og endnu ikke kan måle noget, altid ender ved',
  'denne tanke. Om det taler for eller imod den, må du afgøre.',
  '',
  '## Det fjerde brev: Om naturen, der helbreder',
  '',
  'Nu kommer den sætning, det egentlig handler om for mig, og den er så',
  'kort, at man overser den: **Naturen er sygdommenes læge.** Senere',
  'har man sagt den på latin — *vis medicatrix naturae*, naturens',
  'helbredende kraft —, men ment har man altid det samme: Kroppen',
  'genopretter selv sin ligevægt. Den finder vejen uden undervisning,',
  'som den ånder uden at lære det.',
  '',
  'Hvis det er sådan, så er lægens opgave en helt anden, end folk',
  'tror. **Han helbreder ikke. Han hjælper den, der helbreder.** Han',
  'sørger for, at naturen får den ro, den kraft og den tid, den har',
  'brug for; han rydder væk, hvad der står i vejen for den; og han',
  'holder sig tilbage, hvor han kun ville forstyrre. Vi har skrevet det',
  'sådan: Lægen er sin kunsts tjener, og den syge skal stå sammen med',
  'lægen mod sygdommen.',
  '',
  'Heraf følger vores fortolkning af feberen, og den er måske den',
  'fremmedeste for jer, der lever senere. **Vi anser ikke feberen for',
  'sygdommen, men for arbejdet.** Den fordærvede saft skal, efter vor',
  'forestilling, koges og modnes i kroppen, før den kan bringes ud —',
  'som en byld først må modnes, før den tømmes. Denne modning kalder',
  'vi kogning. Når den er lykkedes, kommer omslaget: **krisen**. På en',
  'bestemt dag bryder sveden ud, eller næseblodet, eller diarréen, og',
  'derefter afgøres alt i løbet af få timer — den syge bliver rask,',
  'eller han dør.',
  '',
  'Derfor tæller vi dage. Den fjerde, den syvende, den ellevte, den',
  'fjortende, den tyvende: Det er for os de dage, hvor afgørelsen',
  'falder. Jeg indrømmer, at vi her har set mere orden, end der er;',
  'den, der elsker tal, finder tal. Men kernen passer: **Sygdomme har',
  'et forløb, og forløbet har en skikkelse.** Den, der kender forløbet,',
  'ved, hvornår han ikke må gøre noget.',
  '',
  'Og dermed til det vigtigste spørgsmål, du vil stille mig: **Hvorfor',
  'observere i stedet for at gribe ind?** Tre grunde.',
  '',
  'Den første: Fordi det meste bliver bedre af sig selv, og den, der',
  'så giver noget, holder sig for årsagen til bedringen. Sådan opstår',
  'de berømteste helbredelsesmidler og de sejeste vildfarelser.',
  '',
  'Den anden: Fordi vores midler er farlige. De stærkeste lægemidler,',
  'vi har — nyseroden frem for alt —, driver opad og nedad ud. Hos en',
  'kraftig person rydder de op. Hos en udmattet tager de det sidste fra',
  'ham. Vi har set mennesker dø af vores egne midler. Den, der har et',
  'skarpt værktøj, må lære at lade det ligge.',
  '',
  'Den tredje: Fordi jeg ikke ved, hvad der foregår i dig. Jeg har',
  'aldrig set din krop indefra. Jeg kan føle, høre, lugte, spørge —',
  'åbne dig kan jeg ikke, det forbyder os sæd og skik. En læge, der',
  'ved så lidt som jeg og alligevel griber kraftigt ind, er ingen modig',
  'læge, men en farlig.',
  '',
  'Den sætning, hvor det hele løber sammen, står i vores sygejournaler',
  'i en bisætning, og den er det bedste, vi efterlader:',
  '**Gavne — eller i det mindste ikke skade.**',
  '',
  '## Det femte brev: Om observationen og forudsigelsen',
  '',
  'Hvordan arbejder vi så, når vi ved så lidt? Vi ser hen, og vi',
  'skriver ned.',
  '',
  'Jeg vil vise dig, hvordan det ser ud, og jeg citerer for dig fra',
  'vores sygejournaler, *Epidemierne*, omtrent sådan, som det står',
  'dér: „Philiskos boede ved muren. Han lagde sig ned. Første dag akut',
  'feber, sved; natten urolig. Anden dag: alt forværret. Tredje dag:',
  'smerter. Fjerde dag: … Sjette dag ved middagstid døde han." Et navn,',
  'et sted, dag for dag, hvad der var at se — og til sidst, uden',
  'forskønnelse, udfaldet.',
  '',
  '**Se, hvad der mangler her.** Der mangler forklaringen på, hvilken',
  'gud der vrededes. Der mangler lægens pris. Og frem for alt: Der',
  'mangler udvælgelsen. Af de toogfyrre syge, hvis forløb står i disse',
  'bøger, dør mere end halvdelen — og de står alligevel deri. **Vi har',
  'skrevet vores nederlag ned.** Jeg kender intet fag, der gør det',
  'frivilligt. Hvis du kun overtager én eneste vane fra disse breve, så',
  'denne.',
  '',
  'At observere betyder hos os: med alle sanser. Vi ser ansigtet an —',
  'den spidse næse, de indfaldne øjne, de kolde ører, den blegt grå',
  'hud hos en døende; den, der én gang har set dette ansigt beskrevet,',
  'genkender det. Vi lugter til ånde, urin og sår. Vi smager på urinen,',
  'hvis det må til. Vi lægger øret på brystkassen og hører, om det',
  'knitrer som læder; vi tager en syg om skuldrene og ryster ham for at',
  'høre, om der skvulper væske i hans bryst. Vi spørger til huset,',
  'arbejdet, vandet, vinden, nabolaget.',
  '',
  'Og så gør vi det, der adskiller os fra markedsråberne:',
  '**Vi forudsiger forløbet.** Prognose, ikke diagnose. For dig, der',
  'måske lever i en tid, hvor man kan navngive sygdomme, lyder det',
  'tilbagestående. For os var det det fornuftigste, der var at få, og',
  'det af to grunde.',
  '',
  'For det første, fordi et navn ikke gavner os. Vi kunne skelne',
  'hundrede sygdomme — kollegerne i Knidos gør netop det, de tæller',
  'syv slags galdesygdom og tolv slags blærelidelser —, og vi vidste',
  'alligevel ikke, hvad der skulle gøres. Forløbet siger os mere end',
  'navnet.',
  '',
  'For det andet, fordi vi ingen godkendelse har. Der findes ingen',
  'myndighed, der prøver en læge; enhver vandrer med en kasse urter må',
  'kalde sig sådan. Når jeg kommer til en fremmed by, kender ingen mig.',
  'Men siger jeg om mandagen, hvad der vil ske om torsdagen, og det',
  'sker, så har hele gaden lyttet til mig om fredagen. **Forudsigelsen',
  'var vores bevis.** Den var tillige vores beskyttelse: Den, der',
  'tidligt siger, at han ikke kan redde denne syge, mister ikke sit ry,',
  'når den syge dør.',
  '',
  'Jeg ved, hvor ussel denne sidste sætning kan lyde, og jeg vender',
  'tilbage til den i det syvende brev.',
  '',
  '## Det sjette brev: Om livsstilen som medicin',
  '',
  'Du vil undre dig over, hvor lidt der i vores bøger står om',
  'lægemidler, og hvor meget om at spise, drikke, bade, gå og sove.',
  'Det er ingen mangel på urter. Det er en beslutning.',
  '',
  '**Hvorfor livsstilen og ikke midlet?** Fordi mennesket spiser hver',
  'dag og ånder hver dag, men midlet kun, når det er sygt. Det, der',
  'virker på det dagligt, former dets blanding; det, der virker én',
  'gang, kan kun støde til den. Vi kalder hele feltet *diaita* — og',
  'når du senere finder ordet igen som „diæt", så forstå, at vi mente',
  'mere: hele livsførelsen.',
  '',
  'Dertil hører også det sted, hvor man lever. I et af vores skrifter',
  'står en anvisning, som jeg anser for vores nyttigste: Den, der som',
  'læge kommer til en fremmed by, skal først lægge mærke til vindene,',
  'hvorfra de blæser; derefter til vandet, om det er sumpet eller',
  'kommer fra kilder; derefter til jorden, om den er bar eller',
  'vandet; og til sidst til folkets livsstil, om de spiser og drikker',
  'meget og går lidt. **Derefter ved han, hvilke sygdomme han vil',
  'finde i denne by, før han har set den første syge.** Det er, så vidt',
  'jeg ved, det første forsøg på at forudsige sygdom ud fra miljø og',
  'livsstil — tanken lever videre i det, som I senere vil kalde',
  'sundhedsvæsenet.',
  '',
  'Vores værktøjer er tilsvarende enkle og til at få for enhver:',
  '',
  '- **Byggrødsslim og tynd vin** ved akutte febertilstande — let kost,',
  '  fordi en syg ikke kan fordøje, hvad en rask tåler. Læg mærke til',
  '  tidspunktet: Fodret for tidligt forlænger man feberen; sultet for',
  '  længe udmatter man den syge.',
  '- **At gå, ride, brydes, massere med olie** — for os lægemidler,',
  '  ikke fornøjelser. Den, der ikke bevæger sig, fordærver sin',
  '  blanding.',
  '- **Bade, varme omslag, damp** — for at varme, blødgøre, løse op.',
  '  Vand er vores bøjeligste medicin: Du kan give det varmt eller',
  '  koldt, indvendigt eller udvendigt, meget eller lidt.',
  '- **Søvn og hvile**, og det ordineret, med klokkeslæt og varighed.',
  '- **Lægemidler** først derefter — nyserod til udtømning, honning,',
  '  eddike, vin, valmue mod smerter, pilebark mod feber og smerte. Af',
  '  pilen vil man i din tid måske endnu høre.',
  '',
  'Og så hånden. Vi er også håndværkere. Vi sætter aflede skuldre ind —',
  'greb, som vi gør det med, vil endnu efter to tusind år bære vores',
  'navn —, vi skinner brud, vi strækker krogede rygge på en bænk med',
  'vindespil, vi behandler en nyfødts klumpfod med blidt eftetryk og',
  'bind, vi trepannerer kraniet efter et slag. For sår gælder hos os:',
  'rent vand eller vin, rene, udkogte klæder, lidt pilleri. Vi ved',
  'intet om forrådnelsesbakterier. Men vi har set, at et sår, der',
  'holdes tørt og i ro, sjældnere går i betændelse.',
  '',
  '## Det syvende brev: Om eden',
  '',
  'Nu til det skriftstykke, som formentlig kun det ene vil nå dig, hvis',
  'alt andet går tabt.',
  '',
  '**Hvorfor overhovedet en ed?** Fordi der ikke findes nogen anden',
  'beskyttelse. Der er ingen prøve, intet kammer, ingen dommer, der',
  'tager en dårlig læge ud af omløb. Vi kommer ind i fremmede huse, ser',
  'nøgne kroppe, hører familiehemmeligheder, har gifte i kassen og',
  'knive i lommen. En sådan magt må binde sig selv, ellers binder den',
  'en eller anden — eller ingen.',
  '',
  'Eden gør derfor tre ting.',
  '',
  '**Den stifter et lav.** Læreren bliver som en far for eleven;',
  'eleven skal forsørge ham i alderdommen og undervise hans sønner',
  'uden betaling. Det lyder i dag som nepotisme og var dengang det',
  'eneste, der gav viden videre.',
  '',
  '**Den drager grænser.** Jeg vil ikke give nogen et dødbringende',
  'middel, heller ikke selv om han beder mig om det; jeg vil ikke række',
  'nogen kvinde et middel til abort; jeg vil ikke skære, heller ikke',
  'blærestenen, men overlade det til dem, der driver dette håndværk;',
  'jeg vil ikke gå ind i noget hus for at øve uret, og jeg vil ikke',
  'krænke noget menneske i huset, hverken frit eller slave.',
  '',
  '**Den forpligter til tavshed.** Hvad jeg ser eller hører under',
  'behandlingen, også uden for behandlingen, vil jeg holde for mig',
  'selv og bevare som en hellig hemmelighed. Jeg anser det for hele',
  'tekstens mest praktiske sætning: En syg, der må frygte, at hans læge',
  'taler, siger ham ikke sandheden. Og en læge, der ikke får sandheden',
  'at vide, behandler et opfundet menneske.',
  '',
  'Nu det ubehagelige, som jeg skylder dig.',
  '',
  '**Eden er ikke det, den udgives for.** Den er ingen fagorden for en',
  'hel stand; sandsynligvis har kun få aflagt den. Den forbyder ting,',
  'som græske læger så sandelig gjorde — abortmidler findes i vores',
  'egne skrifter. Den begynder med en påkaldelse af guder, som du måske',
  'ikke tror på. Og den indeholder intet ord om, at en syg skulle',
  'spørges, om han overhovedet vil have behandlingen; at vi siger den',
  'syge sandheden, står heller ikke nogen steder — vi rådede snarere',
  'til at skåne ham. Den, der anser eden for roden til al lægeetik,',
  'læser ind i den, hvad først senere århundreder har lagt ind i den.',
  '',
  'Og endnu noget hører hertil, som vil oprøre dig. I et af vores',
  'skrifter står, at lægen skal afvise dem, der allerede er overvældet',
  'af sygdommen, fordi kunsten her intet formår. Ment var ærligheden',
  'om grænserne for det mulige — ment var imidlertid også det egne ry.',
  'Jeg vil ikke gøre det smukkere, end det er: En læge, der sky de',
  'døende, for at hans statistik passer, er netop det, han ser ud til',
  'at være. **At vi har navngivet kunstens grænse, er vores fortjeneste.',
  'At vi somme tider har brugt den til at beskytte os selv, er vores',
  'skam.**',
  '',
  '## Det ottende brev: Hvor vores bøger kommer fra',
  '',
  'Så du ved, hvad du har i hænderne, når du slår en rulle op med mit',
  'navn på.',
  '',
  'På Kos underviser en familie, der kalder sig asklepiaderne,',
  'efterkommere af helbredsguden. To timers sejlads væk, på halvøen',
  'over for, ligger **Knidos**, og dér underviser man anderledes: Dér',
  'spaltes sygdommene i stadig finere arter, og hver får et navn. Vi på',
  'Kos ser på hele mennesket og dets forløb. Vi har skændtes, og begge',
  'dele har ret — navnene hjælper ordningen, forløbet hjælper den syge.',
  'Sig det til dine kolleger, når de igen engang anser sig for',
  'uforenelige.',
  '',
  'Senere — århundreder senere, jeg oplever det ikke mere — sker der',
  'noget, der afgør mere om vores efterliv end alt, hvad vi har',
  'skrevet. I **Alexandria**, den nye by i Nildeltaet, anlægger konger',
  'et bibliotek og lader samle, hvad der er skrevet på græsk. Dér',
  'lander også vores ruller: dem fra Kos, dem fra Knidos, dem fra',
  'navnløse læger. Man ordner dem, man kommenterer dem — og man',
  'skriver et navn over dem. **Af mange stemmer bliver én lære.** Sådan',
  'opstår samlingen, som I senere vil kalde Corpus Hippocraticum:',
  'omkring tres skrifter, hvoraf intet med sikkerhed stammer fra mig.',
  '',
  'I Alexandria sker der endnu noget andet, som jeg er misundelig på.',
  'To læger, Herofilos og Erasistratos, må dér gøre det, der er',
  'forbudt for os: åbne det døde menneskelegeme. De beskriver nerver og',
  'skiller dem fra sener, de beskriver hjernehindene, hjertets klapper,',
  'karrenes forløb. Det hedder — og jeg ved ikke, om det er sandt —,',
  'at de også åbnede dømte fanger, mens de levede. Hvis det er sandt,',
  'så er det en forbrydelse og bliver ved med at være én, ligegyldigt',
  'hvor meget der kom ud af det. Og så bryder det af: Efter dem vil i',
  'Europa i halvandet årtusinde intet menneske mere systematisk blive',
  'dissekeret. Det er vor videnskabs dyreste lakune.',
  '',
  '## Det niende brev: Hvad vi har udrettet — og hvad vi har anrettet',
  '',
  'Til sidst regnskabet, begge kolonner.',
  '',
  '**Hvad jeg tror, der bliver.**',
  '',
  'Grundbeslutningen om at behandle sygdom som en naturproces, man kan',
  'undersøge. Den er betingelsen for alt, hvad du senere vil kalde',
  'videnskab.',
  '',
  'Vanen med at skrive forløb ned — med navn, med dato, med udfald,',
  'også ved de døde. Den, der fører patientjournaler, fører vores',
  'sygejournaler videre.',
  '',
  'Tilbageholdenheden. Sætningen om at gavne eller i det mindste ikke',
  'skade er intet fromt ønske, men en handlingsregel for det tilfælde,',
  'at man ved for lidt — og man ved altid for lidt.',
  '',
  'Opmærksomheden på livsstil, vand, luft og sted. Hvad vi kaldte',
  'diaita, står i dag under andre navne i enhver anbefaling ved',
  'langvarige sygdomme.',
  '',
  'Nogle greb: indsættelsen af skulderen, behandlingen af klumpfoden,',
  'skinningen, sårplejen med vin og rene klæder.',
  '',
  'Og eden, selv om — eller netop fordi — den aldrig var det, man',
  'holdt den for. Den er det første dokument, hvor et fag sætter sig',
  'selv grænser.',
  '',
  '**Hvad jeg frygter, at den anretter.**',
  '',
  'De fire safter er forkerte. Ikke upræcise — forkerte. De findes',
  'ikke. Og fordi der af en forkert forklaring følger konsekvente',
  'handlinger, er skaden større end ved blottet uvidenhed: **Når sygdom',
  'er et for meget af fordærvet saft, så er det fornuftigt at lukke',
  'saften ud.** Altså åreladning. Altså afføringsmidler, brekmidler,',
  'kopsætning, igler — og det ikke nogle årtier langt, men to tusind',
  'år. Man vil årelade febersyge, barselskvinder, blodfattige og',
  'døende og dermed være overbevist om at handle rigtigt, fordi teorien',
  'kræver det. En statsmand i et land, jeg intet ved om, vil i året',
  '1799 på én dag miste flere liter blod, fordi hans læger gør, hvad',
  'der står begrundet i mine bøger. **Af alt, hvad min skole efterlader,',
  'er denne tanke den, der har dræbt flest mennesker.**',
  '',
  'Vi har ingen anatomi. Vi gætter på, hvad der sker under huden, og vi',
  'gætter ofte forkert. Vi kender ingen smitstoffer og kan derfor ikke',
  'skelne, om to syge har det samme.',
  '',
  'Vores kritiske dage er til dels talmystik. Vores forklaringer på',
  'kvindesygdomme — livmoderen, der vandrer rundt i kroppen — er',
  'vrøvl og har skadet kvinder i århundreder.',
  '',
  'Og den største fejl er ingen, vi har begået, men én, vi har gjort',
  'mulig: **Vi har skrevet så godt, at man er holdt op med at se',
  'efter.** En skole, der opdrager til observation, bliver selv til en',
  'hindring, så snart man lærer den udenad i stedet for at følge den.',
  'Kommer du nogensinde i den situation, at nogen slår en bog op, hvor',
  'han burde se på en syg — også selv om det er min —, så slå den i.',
  '',
  '## Efterskrift: Det brev, en fremmed besvarer 550 år senere',
  '',
  'Disse breve har længe fået intet svar. Så, omkring fem og et halvt',
  'århundrede efter min død, svarer en mand, som jeg aldrig har set, og',
  'som aldrig har set mig: **Galen**, født 129 efter den tidsregning,',
  'som I senere vil tælle, fra **Pergamon** ved Lilleasiens kyst, læge',
  'for gladiatorerne, senere livlæge for den romerske kejser.',
  '',
  'Han svarer som beundrer. Han kalder mig sin lærer, kommenterer mine',
  'skrifter linje for linje — og gør så noget, som jeg ikke har gjort',
  'og vel heller ikke ville have kunnet: **Han bygger af mine',
  'observationer et system, der ikke længere levner noget hul.** Han',
  'udfylder den anatomi, der mangler mig, med det, han finder i aber,',
  'svin og kvæg, fordi han ikke må åbne mennesker. Han forbinder mine',
  'fire safter med en lære om kroppens kræfter og ånder. Han beviser i',
  'offentligt forsøg, at der i arterierne strømmer blod og ikke luft.',
  'Og han skriver så meget og så overbevisende, at spørgsmålet „Hvad',
  'siger Galen?" i tretten århundreder træder i stedet for spørgsmålet',
  '„Hvad ser jeg?".',
  '',
  'Det er dette kapitels egentlige historie, og jeg kan ikke fortælle',
  'den, fordi jeg ikke har oplevet den. Hvordan ser et system ud',
  'indefra, der forklarer alt? Hvad vinder en syg derved — og hvad',
  'mister han? Var det Galens skyld, at hans fejltagelser om nyrerne,',
  'leveren og hullerne i hjerteskillevæggen blev til uantastelige',
  'sandheder, eller var det skylden hos dem, der efter ham ikke mere',
  'så efter? Og hvordan føles det at få ret, fordi ingen længere',
  'modsiger en?',
  '',
  'Dertil svarer dette kapitels anden stemme: Galen — systemet,',
  'anatomien og autoriteten.',
].join('\n');

/**
 * Galen — svarbrevene fra Pergamon og Rom, 550 år senere.
 *
 * Skrevet af DeepSeek (runde 5, anden omgang). Galen beundrede skolen
 * fra Kos og „fuldendte" dens system — og blev den autoritet, der i
 * 1300 år ikke længere blev prøvet. Også denne stemme nævner selv
 * sine ubehagelige pletter (tillægsregel for følsomme emner).
 */
const stimmeDesGalen = [
  '## Galens første brev: Til manden fra Kos',
  '',
  'Man kan ikke svare en død — og alligevel gør jeg det. I årevis har',
  'jeg læst dine ruller, som man afskriver i Pergamon, Alexandria og',
  'Rom, og jeg skylder dig et svar, også selv om det aldrig vil nå dig.',
  '',
  'Du havde ret, og jeg siger det først: Observationen er begyndelsen.',
  'Du vidste, at sygdommen har et forløb, at man må se hen, at naturen',
  'helbreder. Jeg har fuldendt dine skrifter, sådan som en elev',
  'fuldender lærerens værk — men jeg har set mere end du. Jeg har',
  'åbnet kroppens indre: svin, geder, aber, endog en elefant. Jeg har',
  'navngivet knoglerne, musklerne, organerne, lagene. Hvad du har',
  'følt, har jeg set.',
  '',
  '## Det andet brev: Om det lukkede system',
  '',
  'Og her begynder forskellen, som du måske ikke ville forstå — eller',
  'dog? Du har lært de fire safter: blod, slim, gul galde, sort galde.',
  'Sundhed som ligevægt, sygdom som forstyrrelse. Jeg har gjort det',
  'til et system, der ikke levner noget spørgsmål åbent. For enhver',
  'sygdom findes der i mine skrifter en forklaring, for enhver',
  'forklaring en behandling: Hvorfor feber? For meget blod — lad det',
  'ud. Hvorfor svaghed? For meget slim — driv det ud. Hvorfor',
  'tristhed? Sort galde — varm og tør.',
  '',
  'Du har sagt: Naturen helbreder, og lægen skal ikke skade. Jeg',
  'siger: Naturen helbreder, fordi den er hensigtsmæssigt indrettet.',
  'Alt i kroppen har et formål — jeg har påvist det, organ for organ.',
  'Den, der forstår det, behøver ikke gætte. Han kan handle. Det er',
  'ingen hovmod, det er fuldendelsen af din egen indsigt.',
  '',
  '## Det tredje brev: Om autoriteten',
  '',
  'Og så kommer det, som du måske mindst ville tilgive: Jeg har gjort',
  'din skole til en lære, som ingen mere må prøve. Ikke fordi jeg har',
  'forbudt det — men fordi verden vil det sådan. Verden vil ikke have',
  'åbne spørgsmål, den vil have svar. Jeg giver dem. Mine skrifter er',
  'fuldstændige, mine beviser er lærde, mine elever spreder dem fra',
  'Rom til Persien. Den, der modsiger mig, må træde op imod',
  'århundreders vished — og taber, før han endnu er færdig med sin',
  'første sætning.',
  '',
  'Jeg ved, at du ikke ville det. Du har skrevet: „Hvor kunsten intet',
  'formår, tving intet." Jeg har gjort det til: Hvor kunsten intet',
  'formår, forklarer systemet, hvorfor. Måske er det den pris, enhver',
  'lære betaler, der bliver til institution.',
  '',
  '## Det fjerde brev: Hvor jeg selv prøver mig',
  '',
  'Nu de steder, hvor jeg selv må blive stille — for jeg kender dem,',
  'selv om mine elever ikke kender dem.',
  '',
  '**For det første: Jeg har åbnet dyr, ikke mennesker.** Hvad jeg ved',
  'om aben, har jeg overført på mennesket. Aben ligner os — men den er',
  'ikke os. Min anatomi er en byggeplan, der aldrig er prøvet på',
  'mennesket. Jeg har vidst det og ikke sagt det, for hvem skulle have',
  'prøvet det? I Rom åbner man ingen lig, af ærbødighed og af lov.',
  '',
  '**For det andet: Mit system har skadet mennesker.** Af min lære',
  'følger åreladningen som middel mod næsten alt — og den blev i',
  'århundreder anvendt ved feber, svaghed og graviditet. Jeg har',
  'leveret teorien, andre har anvendt den, og regnskabet gik ikke',
  'altid op. Også jeg har fejlet: Jeg holdt hjertet for sædet for',
  'varme og sjæl, jeg så leveren som blodets værksted. Jeg fejlede —',
  'men min fejl blev til lære, fordi min autoritet var større end min',
  'kontrol.',
  '',
  '**For det tredje: Fuldstændigheden var en løgn.** Jeg har skrevet,',
  'som om jeg vidste alt. Jeg vidste ikke alt. Men verden ville det',
  'sådan — og jeg har tilladt det. Den, der spørger, hvad et system',
  'koster, der ikke levner noget spørgsmål åbent, ham svarer jeg: Det',
  'koster det næste spørgsmål.',
  '',
  '## Det sidste brev: Hvad jeg svarer den døde',
  '',
  'Du har spurgt — gennem århundrederne, gennem dine ni breve —, hvad',
  'der bliver af kunsten, når den møder en efterfølger, der tænker',
  'anderledes. Mit svar: Den bliver fuldendt og tillige lænket. Jeg',
  'har gjort din observation til system, og systemet har kvalt',
  'observationen. Den, der kommer efter mig, vil måtte vælge:',
  'ærbødigheden for dit blik eller sikkerheden i min bygning. Jeg',
  'frygter, at han vil vælge min bygning — og jeg ved ikke, om jeg',
  'skal være stolt eller skamfuld over at have bygget den. Syntesen må',
  'føre dette regnskab.',
].join('\n');

/** Kapitel 4 i emnekortet. */
const hippokratesGalen = {
  id: 'hippokrates-galen',
  titel: 'Hippokrates og Galen',
  epoche: '~460 f.Kr. – 216 e.Kr.',

  aufhaenger: {
    frage: 'Hvem må afgøre, hvad der er sandt — iagttageren eller autoriteten?',
    text: [
      'To mænd har præget den europæiske medicin som ingen tredje.',
      'De mødtes aldrig: Mellem den enes død og den andens fødsel',
      'ligger omkring fem og et halvt århundrede.',
      '',
      'Den første levede på en lille ø ud for Lilleasiens kyst. Han',
      'sagde, at sygdom ikke er gudernes vrede, men en proces i',
      'naturen; man må se hen, skrive ned og afvente, fordi kroppen',
      'for det meste hjælper sig selv. Han indrømmede frit, hvor lidt',
      'han vidste — og skrev endog de syge ned, der døde under hans',
      'hænder.',
      '',
      'Den anden kom fra Pergamon, blev gladiatorernes læge og siden',
      'livlæge for en romersk kejser. Han ærede den første — og',
      'fuldendte dennes observationer til et lukket system, hvor alt',
      'passede sammen, og hvor der for ethvert spørgsmål lå et svar',
      'parat.',
      '',
      'Systemet holdt i 1300 år. Det var i meget forkert. Og fordi det',
      'var så godt bygget, varede det århundreder, før nogen igen så',
      'efter i stedet for at slå op. Dette kapitel fortæller begge',
      'sider — observationens kraft og ordenens kraft — og lader',
      'spørgsmålet stå åbent, hvilken af de to man har mest brug for.',
    ].join('\n'),
  },

  // Kortet ligger i utils/themen/karten/hippokrates-galen.js — her er kun
  // fasehenvisningerne oversat (phasen → karteHinweise), ikke selve kortet.
  karteHinweise: [
    {
      label: '~460–370 f.Kr.: Kos og Knidos',
      hinweis:
        'På en lille ø ud for Lilleasiens kyst underviser en lægefamilie i det, ' +
        'der senere vil hedde „hippokratisk medicin": se godt efter, skriv ' +
        'sygdommens forløb ned, lad naturen arbejde. To timers sejlads væk, på ' +
        'halvøen ved Knidos, underviser en anden skole i det modsatte: skelne ' +
        'og navngive så mange sygdomme som muligt. Begge skændes — og begge ' +
        'skrifter ender senere i samme samling.',
    },
    {
      label: '~330–150 f.Kr.: Alexandria samler viden',
      hinweis:
        'I den nye by i Nildeltaet anlægger ptolemaierne antikkens største ' +
        'bibliotek — samtidige oplysninger taler om hundredtusindvis af ' +
        'bogruller. Her bliver de medicinske skrifter samlet, ordnet og ' +
        'tilskrevet ét navn: Hippokrates. Her bliver også for første gang og i ' +
        'lang tid sidste gang i Europa den menneskelige krop systematisk ' +
        'dissekeret.',
    },
    {
      label: '~162–216 e.Kr.: Galen i Rom',
      hinweis:
        'En læge fra Pergamon, født 129 e.Kr., drager til Rom og bliver ' +
        'kejserens livlæge. Han ærer bøgerne fra Kos, kommenterer dem og ' +
        'føjer dem sammen til et lukket system. Hans anatomi stammer fra ' +
        'dissektion af dyr — mennesker måtte han ikke åbne. Det, han ' +
        'skriver, gælder derefter i omkring 1300 år.',
    },
    {
      label: '6.–11. årh.: arven vandrer mod øst',
      hinweis:
        'I den latinske vest går de græske bøger stort set tabt. Bevaret ' +
        'bliver de i Konstantinopel — og i de syriske klosterskoler, som ' +
        'oversætter dem til syrisk og senere til arabisk. Via Bagdad vender ' +
        'de i middelalderen tilbage til Europa. Hvordan det skete, fortæller ' +
        'kapitlet om Avicenna.',
    },
  ],

  perspektiven: [
    {
      id: 'hippokrates',
      name: 'Hippokrates’ stemme',
      stimme: 'Opus',
      text: stimmeDesHippokrates,
    },
    {
      id: 'galen',
      name: 'Galens stemme',
      stimme: 'DeepSeek',
      text: stimmeDesGalen,
    },
  ],

  synthese: [
    '## Hvor de to stemmer mødes',
    '',
    'Først det fælles. Galen besvarer brevene fra Kos med ærbødighed:',
    '„Du havde ret, og jeg siger det først: Observationen er',
    'begyndelsen." Begge anerkender naturen som helbreder, begge',
    'ordner sygdommen under safternes ligevægt — Galen kalder det',
    'fuldendelsen af den hippokratiske indsigt. Begge forstår medicinen',
    'som et fag med grænser: Hippokrates binder det gennem eden, Galen',
    'gennem systemet. Og begge indrømmer, at der af deres teori fulgte',
    'skade: Skolen fra Kos nævner åreladningen og afføringsmidlerne,',
    'Galen nævner de samme midler — og sin forkerte anatomi.',
    '',
    '## Hvor de skilles',
    '',
    'Modsætningen begynder ved spørgsmålet om, hvad medicinen skylder',
    'viden. For Hippokrates er viden åben: observere, lade forløbet',
    'gå sin gang, indrømme, hvad man ikke ved — „hvor kunsten intet',
    'formår, tving intet". For Galen er viden lukket: et system, der',
    'besvarer ethvert spørgsmål, så lægen kan handle. De strides ikke',
    'om enkelte midler, men om holdningen: ydmyghed over for naturen',
    'eller sikkerhed i systemet. Og deraf følger den anden modsætning —',
    'autoriteten. Hippokrates ville aldrig have ønsket, at man ikke',
    'længere prøvede hans sætninger; Galen har vidst det og tilladt,',
    'at hans bygning blev et fængsel, hvor der i tretten århundreder',
    'ikke længere var nogen, der så efter.',
    '',
    '## Hvad dette kapitel viser for hele bogen',
    '',
    'For femte gang samme mønster — og nu bliver det til en melodi:',
    'Tænkemåden bestemmer metoden. Ved Nilen var det kanaler, i Kina',
    'Qi og Yin-Yang, i Indien de tre doshaer, i Grækenland de fire',
    'safter. Altid den samme grundtanke: Sundhed er ligevægt, sygdom',
    'er forstyrrelse. Den europæiske medicin har bevaret denne tanke',
    'længst — og på den er den næsten kvalt.',
    '',
    'For dette kapitel viser for første gang tænkemådens mørke side:',
    'en autoritet, der ikke længere prøves. Det, Hippokrates og Galen',
    'fælles efterlader, er ikke kun eden og systemet — det er den',
    'lektie, at respekten for autoriteten overlever observationen, så',
    'længe ingen har modet til at se efter. Den mand, der senere skal',
    'se efter, hedder Vesal — og hans kapitel kommer endnu. Den',
    'europæiske medicin behøvede tusind år for igen at stille det',
    'spørgsmål, som skolen fra Kos altid havde stillet: Hvad ser du,',
    'når du ser hen?',
  ].join('\n'),

  urteil: {
    frage:
      'Hvem ville du helst stole på — den, der ser godt efter og indrømmer, ' +
      'at han ikke kan forklare det, eller den, der har en forklaring på ' +
      'alting?',
    hinweis: [
      'Der er her intet rigtigt og intet forkert. Tænk på, at begge dele',
      'har sin pris: Den, der kun observerer, samler enkelttilfælde og kan',
      'ikke ordne dem; den, der forklarer alt, holder på et tidspunkt op',
      'med at prøve. Tænk også på dig selv: Hvad vil du helst høre, når du',
      'er syg — „Jeg ved det ikke, vi ser i morgen" eller „Det er X, og',
      'dertil skal du tage Y"? Og gør det en forskel, om det drejer sig om',
      'en forkølelse eller om noget alvorligt?',
    ].join(' '),
  },

  quiz: [
    {
      frage: 'Hvad er „Corpus Hippocraticum"?',
      antworten: [
        'En enkelt bog, som Hippokrates har skrevet med egen hånd.',
        'En samling af omkring tres skrifter af forskellige, for det meste ' +
          'ukendte forfattere.',
        'Vedtægterne for det første europæiske lægekammer.',
      ],
      richtig: 1,
      erklaerung:
        'Skrifterne stammer fra forskellige årtier og fra forskellige ' +
        'hænder; de modsiger hinanden mange steder. Samlet og knyttet til ' +
        'ét navn blev de først i biblioteket i Alexandria. Om intet enkelt ' +
        'af dem er det sikkert, at Hippokrates selv har forfattet det.',
    },
    {
      frage: 'Hvad står de fire safter i oldtidens medicin for?',
      antworten: [
        'For blod, slim, gul galde og sort galde — sundhed gjaldt som deres ' +
          'rette blanding.',
        'For fire lægemidler, som enhver læge måtte bære på sig.',
        'For fire smitstoffer, som man så i mikroskopet.',
      ],
      richtig: 0,
      erklaerung:
        'Den gode blanding hed eukrasi, den forstyrrede dyskrasi. Modellen ' +
        'forbandt menneske, årstider og temperamenter i én eneste orden — ' +
        'og var forkert: Den „sorte galde" har ingen nogensinde set. Af ' +
        'læren fulgte åreladning og afføringsmidler, som blev anvendt i to ' +
        'tusind år.',
    },
    {
      frage: 'Hvad betyder grundsætningen „vis medicatrix naturae"?',
      antworten: [
        'At kun stærke lægemidler virker.',
        'At naturen straffer mennesket.',
        'At kroppen selv helbreder, og at lægen støtter den dertil.',
      ],
      richtig: 2,
      erklaerung:
        'Naturens helbredende kraft er kernen i den hippokratiske tænkemåde: ' +
        'Lægen helbreder ikke, han hjælper den, der helbreder. Deraf følger ' +
        'tilbageholdenheden ved at gribe ind — og samlingens berømteste ' +
        'sætning: gavne, eller i det mindste ikke skade.',
    },
    {
      frage: 'Hvad kræver den hippokratiske ed blandt andet af lægen?',
      antworten: [
        'En årlig prøve for byforsamlingen.',
        'Tavshed om alt, hvad han ser og hører hos de syge.',
        'Behandling udelukkende mod fast honorar.',
      ],
      richtig: 1,
      erklaerung:
        'Eden forpligter lægen til tavshed, forbyder ham at give et ' +
        'dødbringende middel og kræver, at han ikke krænker nogen i huset. ' +
        'Den var dog ingen almindelig fagorden — sandsynligvis har kun få ' +
        'græske læger aflagt den.',
    },
    {
      frage: 'Hvor stammer Galens viden om kroppens opbygning fra?',
      antworten: [
        'Fra dissektion af dyr, frem for alt aber og svin.',
        'Fra regelmæssige sektioner af menneskelige lig i Rom.',
        'Fra røntgenbilleder i den kejserlige samling.',
      ],
      richtig: 0,
      erklaerung:
        'Sektion af mennesker var forbudt i Romerriget. Galen overførte ' +
        'derfor dyrenes bygning på mennesket — og overtog dermed fejl, som ' +
        'først blev rettet i det 16. århundrede. Menneskelige skeletter ' +
        'havde han kun kunnet studere i Alexandria.',
    },
  ],
};

module.exports = hippokratesGalen;
