// Kapitel 16 — „Hahnemann og homøopatien".
//
// Det ottende kapitel om den nyere tid og bogens mest personlige: Forfatteren
// er naturlæge, og homøopatien er den mest omstridte behandlingsform i de
// sidste to hundrede år. Derfor gælder her en udtrykkelig regel fra CLAUDE.md:
// Homøopatien bliver IKKE affærdiget som ren placebo og ikke latterliggjort.
// Den får sine bedste argumenter, sin egen tænkemåde og sin egen stemme — og
// den nævner selv sine ubehagelige pletter.
//
// TÆNKEMÅDE-analysen er kernen (forfatterens krav). Den spørger her: Hvorfor
// det lignende og ikke det modsatte? (Fordi kroppen svarer på et indtryk med
// en modbevægelse — medicinen skal sætte selvhelbredelsen i gang, ikke
// undertrykke lidelsen.) Hvorfor afprøvningen på raske? (Fordi kun en rask
// krop kan sige, hvad et stof gør alene — hos den syge blandes virkningen
// med sygdommen.) Hvorfor potenseringen? (Fordi den lille dosis sætter
// indtrykket uden at forgifte — og fordi udrivning og omrystning efter den
// homøopatiske lære ikke fjerner noget, men løser noget ud: stoffets
// INFORMATION.) Hvorfor hele mennesket? (Fordi sygdommen efter denne
// tænkemåde ikke er et organs sag, men en forstyrrelse af helheden.)
//
// INFORMATIONS-TESEN OG TELEFON-ARGUMENTET (forfatterens krav, fremtrædende):
// „Er der stadig stof i?" er efter den homøopatiske lære det forkerte
// spørgsmål. En telefon indeholder ingen stemme og overfører den alligevel;
// et menneske fra middelalderen ville have sagt: „Der er ingen derinde, det
// kan ikke fungere." At noget ikke kan forklares med den nuværende viden er
// ikke et bevis på, at det ikke virker. Stemmen fører dette argument frem i
// fuld styrke — og nævner selv, hvor det bliver tyndt: Ved telefonen kan man
// måle bæreren, ved potenseringen hidtil ikke.
//
// SHELDRAKE (forfatterens krav): Rupert Sheldrakes morfiske felter står i
// teksten som et muligt tænkemodel — udtrykkeligt markeret som HYPOTESE,
// ikke som bevist kendsgerning (reglen om ingen rygter). Stemmen siger selv,
// at fagverdenen overvejende afviser dem.
//
// LÆNGDEREGEL (forfatterens feedback 24.08.2026): Fra kapitel 9 gælder det
// omvendte — fuldstændigt og udførligt. Det måles i
// tests/karte-homoeopathie.mjs.
//
// INGEN RYGTER (forfatterens beslutning 25.08.2026): Kun det belagte. Meißen
// 1755, kinabarkforsøget 1790, Organon 1810, processen i Leipzig, Köthen
// 1821, Paris 1843 — alt sammen aktmæssigt godtgjort. Hvor et tal svinger
// (antallet af sprog, Hahnemann beherskede) eller noget kun er overleveret
// (slaget mod den læderindbundne bog), siger teksten det.
//
// INNOVATIONSCYKLUSSEN (forfatterens iagttagelse 26.08.2026, rød tråd): Ved
// homøopatien står den på hovedet. Den var det MILDE svar på en brutal
// medicin — den har ikke brændt, forblødt eller forgiftet nogen. Dens risiko
// ligger et andet sted: at den milde idé blev til et dogme, der ikke længere
// tillader prøvelsen. Stemmen nævner det selv.
//
// Stemmer (runde 17): Den FØRSTE synsvinkel — homøopatien indefra, stemmen
// fra ledningen — skrev Opus. Den ANDEN (skolemedicinen: sin egen mørke
// fortid med åreladning og kviksølv, placebo-spørgsmålet, studierne,
// spørgsmålet „Hvad gælder som bevis?") og den endelige syntese supplerede
// Hermes i anden omgang (Hermes-pass, 27.08.2026: „suppleret").
// Synsvinkel-workflow: CLAUDE.md.
//
// INGEN GENTAGELSER (forfatterens beslutning 21.08.2026): Kapitel 1 inddeler
// efter „hvem der taler", kapitel 2 begynder med en scene, kapitel 3
// fortæller et døgnsforløb, kapitel 4 er en brevveksling, kapitel 5 en bogs
// rejse, kapitel 6 en rundgang, kapitel 7 en proces, kapitel 8 en regning,
// kapitel 9 et ur, kapitel 10 en kæde, kapitel 11 en linse, kapitel 12 et
// interview, kapitel 13 en sag, kapitel 14 en indlægsseddel, kapitel 15 en
// pressekonference. Dette kapitel vælger den syttende dramaturgi: TELEFONEN.
// Et apparat, som ingen sidder i, og som der alligevel kommer en stemme ud
// af — rammen for Hahnemanns historie og for spørgsmålet, om en virkning
// behøver et stof. Den anden stemme kan træde ind i samme form: samme
// apparat, men spørgsmålet om den ledning, man kan skære op og måle.
//
// Teksterne ligger som linje-Arrays med `.join('\n')` — sådan forbliver de
// i repoet læsbare på ~72 tegn (forfatteren læser dem her), og
// utils/markdown.js gør i appen igen flydende tekst ud af dem.
//
// CommonJS uden UI-imports (arkitekturregel): kan kontrolleres med bart `node`.

/**
 * Stemmen fra ledningen — homøopatien indefra.
 *
 * Skrevet af Opus (runde 17). En stemme, der taler for den side, der i to
 * hundrede år har behandlet, er overbevist og er blevet angrebet: dens
 * tænkemåde, dens historie, dens erfaring. Den fortæller, hvorfor den gør,
 * hvad den gør — og den nævner selv de ubehagelige pletter (tillægsregel
 * for følsomme emner i CLAUDE.md).
 */
const stimmeAusDerLeitung = [
  '## Apparatet, som ingen sidder i',
  '',
  'Forestil dig, at du kunne stille en telefon på bordet foran en lærd mand',
  'fra år 1400. En gammel apparat med rør og ledning. Du løfter røret,',
  'holder det til hans øre, og fra det sorte kabinet taler en kvinde, der',
  'sidder tre hundrede kilometer væk i en anden by.',
  '',
  'Han vil tage apparatet og ryste det. Han vil skrue det op. Han vil skære',
  'ledningen over og kigge ind. Og så vil han sige, hvad enhver fornuftig',
  'mand i hans tid måtte sige:',
  '**„Der er ingen derinde. I den ledning er der ingen luft, intet strubehoved,',
  'ingen stemme. Altså kan der ikke komme nogen stemme ud."**',
  '',
  'Hans logik er upåklagelig. Hans verdensbillede er det også — det er det',
  'bedste, man kunne have i år 1400. Det rækker bare ikke derhen, hvor',
  'forklaringen ligger. For en stemme rejser ikke som stemme gennem kablet.',
  'Det, der rejser, er et **mønster**: Mikrofonens membran omsætter luftens',
  'tryk til en skiftende strøm, og i den anden ende omsætter en anden',
  'membran denne strøm tilbage til tryk. Ledningen bærer ingen tone. Den',
  'bærer en **form**.',
  '',
  'Jeg begynder med dette billede, fordi det rammer spørgsmålet i dette',
  'kapitel præcist. **Det, du læser her, er homøopatien indefra — en',
  'tænkemåde, ikke en sandhed.** Jeg taler for den side, der i to hundrede',
  'år har behandlet, er overbevist og er blevet angrebet. Jeg vil fremføre',
  'dens bedste grunde. Og jeg vil selv nævne de steder, hvor vi står',
  'dårligt, i stedet for at vente på, at en anden gør det.',
  '',
  'To årstal for ærlighedens skyld med det samme: Den frankfurterske lærer',
  '**Philipp Reis** viste i 1861 det første apparat, der overførte toner',
  'elektrisk; **Alexander Graham Bell** fik i 1876 patent på telefonen. Da',
  'Hahnemann døde i 1843, fandtes alt det ikke. Telefonbilledet er altså',
  'ikke et bevis for noget som helst. Det er et redskab til at skærpe et',
  'spørgsmål — og spørgsmålet lyder:',
  '',
  '**Skal der være et stof i et middel, for at det virker? Eller kunne det',
  'være nok, at det bærer en form?**',
  '',
  '## Ledningen til Meißen: en porcelænsmalers søn, 1755',
  '',
  'Manden, det hele handler om, kommer fra små kår. **Christian Friedrich',
  'Samuel Hahnemann bliver født den 10. april 1755 i Meißen**, søn af en',
  'porcelænsmaler ved kurfyrstens manufaktur.',
  '',
  'Det er mere end en oplysning om herkomst. En porcelænsmaler arbejder med',
  'bitte små mængder: En anelse for meget kobolt, og det blå slår om. Han',
  'arbejder med stoffer, der i ilden bliver noget andet, end de var før. Og',
  'han arbejder med præcision som livsform. Sønnen har set det, før han',
  'kunne læse.',
  '',
  'Han kommer på fyrsteskolen St. Afra i Meißen; fordi pengene mangler,',
  'eftergives skolepengene. Hans afgangsstil fra 1775 handler om',
  'menneskets hånds vidunderlige bygning. Så tager han til **Leipzig** for',
  'at studere medicin — med meget få penge, hvorfor han om natten',
  'oversætter for at kunne betale dagen. I 1777 tager han til **Wien**,',
  'hvor han på de barmhjertige brødres hospital for første gang ser',
  'rigtige sygesenge. Derefter tjener han i Hermannstadt i Siebenbürgen en',
  'guvernør som huslæge og bibliotekar. **I 1779 promoveres han i Erlangen',
  'til doktor i medicin.**',
  '',
  'Om antallet af sprog, han skulle have behersket, cirkulerer forskellige',
  'angivelser — man læser otte, man læser tolv. **Jeg nævner ikke tallet,',
  'fordi kilderne ikke giver det fra sig.** Belagt er det, der er nok: Han',
  'oversatte fra engelsk, fransk, italiensk og latin medicinske og kemiske',
  'fagbøger — og det gennem årtier og i stort omfang. Det er det erhverv,',
  'som alt det videre udspringer af: **Det var ikke en forsker ved',
  'sygesengen, der fandt homøopatien, men en mand ved skrivebordet, der',
  'bragte en fremmed bog til tysk og under oversættelsen gik i stå.**',
  '',
  'Før det flytter han fra sted til sted: Hettstedt, **Dessau**, Gommern,',
  '**Dresden**, igen Leipzig. I Dessau arbejder han i begyndelsen af',
  '1780erne i et apoteks laboratorium — veje, opløse, udrive, hælde om,',
  'etikettere — og gifter sig i 1782 med Johanna Henriette Küchler fra',
  'apotekerens hus; elleve børn bliver født. I Dresden vikarierer han i',
  'slutningen af 1780erne for byfysikus og arbejder i kurfyrstens',
  'bibliotek.',
  '',
  'Og på et tidspunkt i disse år holder han op med at behandle syge. Ikke',
  'af bekvemmelighed. Han skriver det senere nogenlunde sådan: at han ikke',
  'længere kunne udholde at handle i det uvisse og derved forvolde skade.',
  '**En læge, der nedlægger sin praksis, fordi han ikke længere kan stå',
  'inde for sin egen medicin — det er begyndelsen på denne historie.**',
  '',
  '## Den medicin, han gik imod: åreladning, kalomel, brækmidler',
  '',
  'For at forstå, hvorfor en læge gør sådan noget, må man vide, hvad medicin',
  'hedder omkring 1790. Og her beder jeg om overbærenhed: De følgende',
  'linjer lyder som en anklage. Det er de ikke. Det er ganske enkelt det,',
  'der dengang gjaldt som den bedste tilgængelige stand af kunsten —',
  'anvendt af hæderlige mænd efter bedste viden.',
  '',
  'Den syge bliver **tømt**. Det er grundideen: Det, der skader, skal ud.',
  'Altså tapper man blod, ofte flere gange, ofte i liter; man sætter igler,',
  'giver brækmidler og afføringsmidler, driver sveden frem, trækker blærer',
  'på huden med spanske fluer, lægger hårtråde gennem nakkehuden, så såret',
  'væsker og „leder af".',
  '',
  'Dertil lægemidlerne: **kalomel** — en kviksølvforbindelse —, antimon,',
  'arsen, vismut, opium i mængder, som ingen i dag længere ville stå inde',
  'for. Recepter med tyve, tredive bestanddele, hvoraf ingen enkelt var',
  'afprøvet, og hvis samspil ingen kendte.',
  '',
  'Hvordan det kunne gå, viser en meget kendt sag. I december 1799 bliver',
  '**George Washington** syg med en alvorlig halsbetændelse. Hans læger',
  'gør deres bedste. De tapper ham ifølge de overleverede angivelser inden',
  'for få timer mellem to og to en halv liter blod, giver ham kalomel og',
  'et brækmiddel og trækker blærer på hans hals. Han dør samme nat. **Om',
  'sygdommen har dræbt ham eller behandlingen, er den dag i dag omstridt —',
  'og netop dette „den dag i dag omstridt" er pointen.**',
  '',
  'Hahnemann har set sådanne dødslejer. Han har senere præget sit eget ord',
  'for den slags behandling: **allopati** — lægekunsten, der gør noget',
  'andet end sygdommen, der arbejder imod den og dækker den til. Hans dom',
  'over den var hård til det uretfærdige, og det vender jeg tilbage til.',
  '',
  'Her tæller i første omgang kun ét: **Homøopatien er ikke opstået som',
  'konkurrence til en virksom medicin. Den er opstået som modudkast til en',
  'medicin, der jævnligt svækkede sine syge.** Den, der vil vurdere den,',
  'må sammenligne den med det, der dengang ellers fandtes — ikke med det,',
  'der ville komme hundrede og halvtreds år senere.',
  '',
  'Og her falder et tal i øjnene, som også vore modstandere ikke',
  'bestrider: **Dødeligheden på homøopatiske hospitaler i det 19.',
  'århundrede lå gennemgående lavere end på de andre.** Jeg vil længere',
  'nede ærligt sige, hvad det efter min opfattelse betyder — og hvad det',
  'ikke betyder.',
  '',
  '## Oversætteren lægger ikke på: Leipzig 1790',
  '',
  'Nu øjeblikket, som alt drejer sig om. Det er uspektakulært — og netop',
  'det gør det troværdigt.',
  '',
  '**I år 1790 oversætter Hahnemann den edinburgher professor William',
  'Cullens læremiddellære til tysk.** Han kommer til stedet om **kinabarken**',
  '— den sydamerikanske bark, som man senere udvandt kinin af, og som',
  'gjaldt som det eneste rigtigt pålidelige middel mod den intermitterende',
  'feber, malariaen.',
  '',
  'Cullen forklarer dens virkning med dens bitterhed og dens styrkende',
  'virkning på maven. Og her standser oversætteren op. For han har arbejdet',
  'med kemi og farmaci nok til at vide: Der findes mange bitre,',
  'mavestyrkende stoffer, og ikke ét af dem helbreder den intermitterende',
  'feber. **Forklaringen passer ikke på sagen.**',
  '',
  'En anden havde sat en fodnote og skrevet videre. Hahnemann gør noget',
  'andet: **Han tager barken selv.** To gange dagligt fire kvintin — efter',
  'nutidens mål hver gang omkring femten gram bark, en meget kraftig',
  'dosis.',
  '',
  'Og så, noterer han i fodnoten til sin egen oversættelse, indfinder',
  'lidelserne sig: kolde fødder og fingerspidser, mathed, hjertebanken,',
  'pulsstigning, en rysten, en bedøvelse i hovedet, røde kinder, tørst —',
  'og det i anfald, der vender tilbage og går over igen. **Han',
  'sammenligner dem med lidelserne ved den intermitterende feber.**',
  '',
  'Ud af denne ene fodnote opstår en tanke, der vil splitte medicinen:',
  '**Kinabarken fremkalder hos den raske et billede, der ligner det, som',
  'sygdommen, den helbreder hos den syge.**',
  '',
  'Seks år senere, i 1796, offentliggør han den i Hufelands Journal der',
  'practischen Arzneykunde under titlen „Versuch über ein neues Prinzip',
  'zur Auffindung der Heilkräfte der Arzneisubstanzen". Det er',
  'fødselsattesten. **Navnet får sagen først i 1807: homøopati**, af de',
  'græske ord for „lignende" og „lide".',
  '',
  'Og her en forstyrrelse på ledningen, som jeg ikke trykker væk:',
  '**Kinabarkforsøget er den dag i dag ikke blevet pålideligt gentaget.**',
  'Senere forsøg på under kontrollerede betingelser at fremkalde de samme',
  'lidelser er slået fejl; kritikere formoder en personlig overfølsomhed',
  'hos Hahnemann eller en ganske simpel forgiftningsvirkning af den høje',
  'dosis. Det er en alvorlig indvending. Den rammer dog ikke hele læren,',
  'men dens anledning: **En tanke er ikke forkert, fordi den iagttagelse,',
  'der udløste den, vakler — og heller ikke rigtig af den grund.** Det,',
  'der blev til ud af den, må prøves for sig selv.',
  '',
  '## Det første ringesignal: Similia similibus curentur',
  '',
  'Den sætning, der står over alt, er latin og får plads i fire ord:',
  '**„Similia similibus curentur" — lignende må helbredes ved lignende.**',
  'Den står på titelbladet af Organon.',
  '',
  'Man forstår den hurtigst på et eksempel, som alle kender. Skær et løg:',
  'Øjnene løber i vand, brænder og klør, næsen løber vandet, det kildrer.',
  'Nu findes der mennesker med en høfeber, der ser præcis sådan ud —',
  'løbende, brændende øjne, vandet snue. Homøopatien giver dette menneske',
  'et middel af køkkenløget, **Allium cepa**, i potenseret form.',
  '',
  'Eller: Kaffe om aftenen gør lysvågen, driver tankerne, får hjertet til',
  'at banke. Et menneske, der ligger lige så vågen, får **Coffea**. Eller:',
  'Bistikket hæver lyserødt, brænder, stikker og bliver bedre af kulde —',
  'ved en betændelse, der ser præcis sådan ud, giver man **Apis**, af',
  'honningbien.',
  '',
  'Det er hele princippet i sin enkleste skikkelse. **Ikke modmidlet, men',
  'lignelsen.** Man søger ikke det stof, der undertrykker lidelsen, men',
  'det stof, der hos den raske fremkalder et så lignende billede som',
  'muligt.',
  '',
  'Nu det afgørende spørgsmål — og det er dette kapitels egentlige',
  'spørgsmål, for alt hænger på det:',
  '',
  '## Begrundelsen: hvorfor det lignende og ikke det modsatte',
  '',
  '**Hvorfor skulle netop det lignende helbrede?** Homøopatiens svar har',
  'tre dele, og det er i sig selv sammenhængende — hvilket ikke betyder,',
  'at det er rigtigt, men det betyder, at det ikke er vrøvl.',
  '',
  '**For det første: Kroppen heler, ikke medicinen.** Et snitsår lukker',
  'sig, en knogle vokser sammen, en feber stiger og falder. Ingen læge gør',
  'det; han skaber betingelser. Efter denne tænkemåde er helbredelse altid',
  'selvhelbredelse. En medicin kan altså kun **sætte den i gang**.',
  '',
  '**For det andet: På et indtryk svarer kroppen med en modbevægelse.**',
  'Det kan man iagttage i hverdagen. Et koldt brusebad køler først og',
  'får bagefter huden til at gløde. En stærk kaffe vækker og efterlader',
  'timer senere træthed. Et sovemiddel bringer søvn og bagefter ofte en',
  'nat, der er værre end før. **Den første virkning kommer fra stoffet,',
  'den anden kommer fra kroppen — og den anden er den varige.**',
  '',
  'Deraf følger den homøopatiske regning: Giver man en syg et stof, der',
  'efterligner netop hans lidelser, sætter man et indtryk i den retning,',
  'sygdommen allerede presser. Kroppen svarer med en modbevægelse — og den',
  'modbevægelse er helbredelsen. **Man arbejder ikke imod sygdommen, men',
  'med den kraft, kroppen sætter op imod den.**',
  '',
  '**For det tredje: Det modsatte undertrykker kun.** Den, der sænker en',
  'feber, har sænket temperaturen og ikke årsagen. Den, der stiller',
  'hostetrangen, har ladet ophostningen blive i bronkien. Det kan være',
  'nødvendigt og rigtigt — homøopatien bestrider ikke det —, men det er',
  'efter denne tænkemåde en forvaltning af tilstanden, ingen helbredelse.',
  '',
  'Og fordi to syge med samme diagnose viser helt forskellige billeder,',
  'følger deraf noget praktisk: **Det er ikke sygdommen, der får et',
  'middel, men den syge.** Ti mennesker med influenza får under visse',
  'omstændigheder ti forskellige midler — alt efter om man fryser eller',
  'gløder, om man er tørstig eller ikke, om man vil være alene eller',
  'ikke, om det bliver værre om aftenen eller om morgenen. Det er ikke en',
  'særhed. Det følger uafvendeligt af princippet: Skal det lignende',
  'helbrede, må man vide, hvem det skal ligne.',
  '',
  '## Protokollen: afprøvningen på raske',
  '',
  'Dermed står Hahnemann over for et håndgribeligt problem. Hvis han',
  'søger det stof, der efterligner et bestemt sygdomsbillede, må han om',
  'hvert stof vide, **hvilket billede det fremkalder**. Og den viden',
  'fandtes ikke.',
  '',
  'Hans løsning er den stærkeste del af hele historien, og den er på samme',
  'tid hans mest videnskabelige bedrift: **lægemiddelafprøvningen på',
  'raske.**',
  '',
  '**Hvorfor på raske og ikke på syge?** Fordi hos den syge blandes',
  'stoffets virkning og sygdommen. Bagefter kan man ikke se, hvad der kom',
  'af hvad. En rask krop derimod er et stille rum: Alt, hvad der melder',
  'sig efter dosen, kommer fra midlet.',
  '',
  'Fra 1805, frem for alt i årene i **Torgau ved Elben**, gennemfører han',
  'disse afprøvninger i stor stil: på sig selv, på sin kone, på sine børn,',
  'på elever og venner. De regler, han opstiller for det, lyder',
  'forbløffende moderne:',
  '',
  '- Den, der afprøver, skal være rask og leve mådeholdent.',
  '- Ingen andre lægemidler, ingen stærk kaffe, ingen vin, ingen krydderier,',
  '  der forfalsker billedet.',
  '- Hver fornemmelse bliver straks skrevet ned, med tidspunkt på dagen og',
  '  med det, der gør den bedre eller værre.',
  '- Intet udelades, heller ikke det uvæsentlige.',
  '- Først når flere afprøvere melder det samme, gælder det som en del af',
  '  lægemiddelbilledet.',
  '',
  'Ud af disse protokoller opstår **lægemiddelbillederne** og de seks bind',
  'af „Reine Arzneimittellehre" (1811 til 1821). Sagt nøgternt er de de',
  'første systematiske forsøgsrækker om enkelte stoffers virkning på',
  'mennesker, som nogen har skrevet ned og offentliggjort.',
  '',
  '**Hvad der er at kritisere ved det, siger jeg selv:** Der var ingen',
  'skinmedicin til sammenligning, ingen blinding, ingen optælling. Den,',
  'der i dagevis lytter nøje ind i sig selv, finder altid noget — et',
  'klem, en nedtrykt stemning, en drøm. Efter nutidig forsknings regler',
  'ville denne samling ikke være en afprøvning, men en samling af',
  'iagttagelser. **Men for år 1805 var den et vældigt fremskridt**: I en',
  'tid, hvor man skrev recepter med tredive bestanddele, afprøvede her',
  'nogen et enkelt stof for sig selv alene og skrev op, hvad det gjorde.',
  '',
  '## Regulatoren: potenseringen — og hvorfor den ikke er en fortynding',
  '',
  'Nu til den del, hvor alt tænder — og som ikke kan forstås uden',
  'forhistorien.',
  '',
  'I begyndelsen står ingen trosartikel, men en **nødsituation**. Hvis et',
  'middel fremkalder lidelser, der ligner den syges, så gør det præcis det',
  'også hos den syge: Det forstærker først hans lidelse. Ved galnebær,',
  'kviksølv, arsen eller bræknød er det livsfarligt. Hahnemanns første',
  'syge fik for store doser og led.',
  '',
  'Altså gør han dosen mindre. Han fortynder: en del medicin på',
  'nioghalvfems dele alkohol eller mælkesukker, så af denne blanding igen',
  'en del på nioghalvfems, og så videre. Hvert trin hedder en **C-potens**.',
  'Ti trin, tredive trin, senere to hundrede.',
  '',
  'Og derved gør han en iagttagelse, der betyder bruddet med kemien — og',
  'som jeg fremstiller som det, den er: **en iagttagelse, han gjorde, og',
  'en fortolkning, han gav den.**',
  '',
  'Iagttagelsen: De stærkt fortyndede midler virkede i hans praksis ikke',
  'svagere, men efter hans vurdering **dybere og mildere** — men kun hvis',
  'han rystede dem kraftigt ved hvert trin. Et middel, der kun var blevet',
  'fortyndet og stille henstillet, var for ham uden virkning. **Derfor',
  'hedder fremgangsmåden ikke fortynding, men potensering eller',
  'dynamisering**: Fortynde og **omryste** — ved faste stoffer **udrive**',
  'med mælkesukker i morteren, hver gang i en time.',
  '',
  'Overleveret er, at Hahnemann slog flasken ved hvert trin mod en',
  'læderindbundet bog — antallet af slag angives forskelligt; **jeg',
  'fører det som overlevering, ikke som belæg.** I sagen står det dog i',
  'Organon: Lægemidlets kraft bliver ved gnidning og omrystning',
  '„udviklet" og „åbnet op".',
  '',
  '**Hvorfor skulle mindre stof virke stærkere?** Det homøopatiske svar i',
  'én sætning: **Fordi lægemidlet efter denne lære ikke virker som mængde,',
  'men som indtryk — og et indtryk behøver ingen masse, men præcis',
  'pasform.** Et støvkorn i øjet vejer intet og lægger et menneske ned. Et',
  'enkelt ord kan afslutte et ægteskab. Modprøven for mængde-tænkemåden',
  'lyder: Hvis masse var det afgørende, måtte enhver, der spiser meget,',
  'være rask.',
  '',
  'Nu det tal, som alt hænger på, og jeg stiller det uforkortet hen,',
  'fordi enhver ærlig strid må kende det.',
  '',
  'En mol af et stof indeholder omkring **seks hundrede billioner billioner**',
  'partikler — Avogadros tal, cirka 6 gange 10 i 23. Fortynder man et',
  'stof trinvis i forholdet én til hundrede, er dette tal opbrugt efter',
  'cirka **tolv trin**. **Fra den tolvte C-potens er der regnemæssigt ikke',
  'et eneste molekyle af udgangsstoffet tilbage i flasken.** Hahnemanns',
  'yndlingspotens var den tredivte: en fortynding af én til ti i tres.',
  '',
  '**Det bestrider homøopatien ikke. Den har aldrig bestridt det.**',
  'Hahnemann vidste, at der i hans højpotenser ikke er noget vejbart;',
  'derfor talte han udtrykkeligt om en åndslignende, ikke stoffet',
  'virkning. Anklagen „Der er jo slet ikke mere i!" rammer altså ingen',
  'modstander, der ville have påstået noget andet. **Den beskriver',
  'præcis det, læren selv siger.**',
  '',
  'Og dermed er vi tilbage ved apparatet på bordet.',
  '',
  '## Hvad der går gennem ledningen: informations-tesen',
  '',
  'Her står dette kapitels stærkeste påstand, og jeg siger på forhånd,',
  'hvad den er: **en tese. Ikke bevist. Alvorligt ment.**',
  '',
  'Den lyder: **Spørgsmålet „Er der stadig stof i?" er det forkerte',
  'spørgsmål.**',
  '',
  'For et telefonkabel indeholder ingen stemme, og alligevel kommer der i',
  'den anden ende en stemme ud. En grammofonplade indeholder ingen musik —',
  'den indeholder en rille med en bestemt form. En databærer indeholder',
  'intet billede; den bærer et mønster, og af mønsteret opstår billedet',
  'igen. I alle disse tilfælde er det virksomme ikke stoffet, men **den',
  'orden, der er præget ind i stoffet**.',
  '',
  '**Præcis det hævder potenseringen.** Ikke, at der er en rest af stoffet',
  'tilbage. Men at der ved udrivningen og omrystningen går en',
  '**information** fra udgangsstoffet over på bærermidlet — på alkoholen,',
  'vandet, mælkesukkeret, sukkerkuglen — og at kroppen svarer på denne',
  'information. **Lægemidlet ville da ikke være stoffet, men budskabet.**',
  '',
  'Den, der tænker sådan, måler med et andet mål. En kemisk analyse',
  'spørger: Hvad indeholder det? Informations-tesen spørger: **Hvad bliver',
  'overført?** Det er to forskellige spørgsmål, og det andet lader sig',
  'ikke besvare med det førstes værktøjer. En kemiker, der analyserer et',
  'telefonkabel, finder kobber og kunststof og melder med fuld ret:',
  '**ingen stemme påviselig.**',
  '',
  'Og deraf følger den sætning, som det handler om for forfatteren af',
  'denne bog: **At noget ikke kan forklares med det nuværende',
  'verdensbillede, beviser ikke, at det ikke virker.** Videnskabens stand',
  'er grænsen for vor viden, ikke grænsen for verden. Den har forskudt',
  'sig i hvert århundrede, og den vil blive ved med at forskubbe sig.',
  '',
  'Dertil er der et eksempel, som står midt i denne bog, og som ingen',
  'bestrider. **Ignaz Semmelweis lod fra 1847 hænderne vaske i klorkalk,',
  'og barselkvindernes dødelighed faldt dramatisk. Han kunne ikke sige,',
  'hvorfor.** Kimteorien, der forklarede det, kom først tyve år senere med',
  'Pasteur og Lister. Hans kolleger afviste ham — ikke fordi tallene var',
  'dårlige, men fordi forklaringen manglede. **Han havde ret uden at',
  'kunne forklare hvorfor.**',
  '',
  'Og nu det sted, hvor jeg må gøre mit eget bedste våben sløvt, fordi',
  'denne bog er ærlig:',
  '',
  '**Telefon-argumentet har et hul, og det er stort.** Ved telefonen kan',
  'jeg vise bæreren. Jeg kan holde et måleapparat mod ledningen og gøre',
  'den skiftende strøm synlig; jeg kan se pladens rille under mikroskopet.',
  '**Ved potenseringen kan jeg det hidtil ikke.** Ingen har indtil nu',
  'kunnet vise, hvad informationen i vandet skulle bestå i, hvordan den',
  'forbliver stabil, hvordan den kommer ind i kroppen, og hvad den',
  'forankrer sig i der.',
  '',
  'Og Semmelweis havde noget, som jeg ville ønske mig: **Han havde',
  'tallene.** Han kunne ikke forklare, hvorfor det virkede — men han',
  'kunne vise, **at** det virkede, kontrollerbart, måned for måned, i en',
  'tabel. Den, der påberåber sig ham, påberåber sig altså et tilfælde,',
  'hvor beviset for virkningen forelå, og kun forklaringen manglede.',
  '**Homøopatien må stille sig spørgsmålet, om det samme virkelig gælder',
  'for den.**',
  '',
  'Jeg lader det stå sådan. Det er den ærlige stand af sagen.',
  '',
  '## En omstridt sideforbindelse: Sheldrake og de morfiske felter',
  '',
  'Skal en information overføres uden stof, behøver man i det mindste en',
  'forestilling om, hvordan sådan noget kunne tænkes. En sådan',
  'forestilling har den britiske biolog **Rupert Sheldrake** fremlagt:',
  'ideen om de **morfiske felter** og den **morfiske resonans**, først i',
  '1981 i bogen „A New Science of Life".',
  '',
  'Hans overvejelse går nogenlunde sådan: Form og adfærd i naturen ville',
  'ikke være bestemt alene af anlægene, men desuden af felter, hvori',
  'tidligere former og vaner ligesom slår sig ned. Det, der én gang er',
  'sket, sker bagefter lettere — også på tværs af rumlig afstand. Naturen',
  'havde dermed ikke en evig lovbog, men **vaner**.',
  '',
  'Man ser straks, hvorfor det er interessant for homøopatien: Det ville',
  'være et tænkemodel for, hvordan en form kan videregives uden materie.',
  '',
  '**Og nu markeringen, uden hvilken dette afsnit ikke måtte stå i denne',
  'bog: Sheldrakes teori er en hypotese og videnskabeligt omstridt. Den',
  'er ikke bevist.** Den daværende udgiver af fagtidsskriftet „Nature",',
  'John Maddox, overskrev i 1981 sin anmeldelse med spørgsmålet, om dette',
  'var en bog, man skulle brænde — en begivenhed, der citeres den dag i',
  'dag. Det store flertal af biologer afviser teorien; overbevisende,',
  'uafhængigt gentagne belæg foreligger ikke.',
  '',
  '**Jeg fører den derfor ikke som bevis, men som eksempel på, at man',
  'overhovedet kan tænke over en bærer.** Den, der har en tese, som',
  'mangler en forklaring, må gerne søge forklaringer. Han må bare ikke',
  'lade, som om han allerede har fundet dem. Et andet eksempel af samme',
  'slags, de ofte berettede tætte forbindelser mellem enæggede tvillinger,',
  'hører i samme skuffe: **ofte fortalt, svært målbart, ikke belagt.**',
  'Sådanne historier er spørgsmålstegn, ikke argumenter. Og fordi denne',
  'bog kun beretter det belagte, forbliver de her spørgsmålstegn.',
  '',
  '## Formidlingscentralen: Organon fra 1810 og hele mennesket',
  '',
  '**I 1810 udkommer den bog, der samler alt: „Organon der rationellen',
  'Heilkunde"**, fra anden udgave af 1819 „Organon der Heilkunst". Den',
  'har den dag i dag seks udgaver; den sjette skrev Hahnemann kort før',
  'sin død, trykt blev den først i 1921.',
  '',
  'Dens første sætning er en af medicinhistoriens smukkeste, og også en',
  'modstander bør kende den: **„Lægens højeste og eneste kald er at gøre',
  'syge mennesker raske, det, man kalder at hele."** I den anden',
  'afhandling står, hvordan det skal ske: **hurtigt, mildt, varigt** — og',
  'på efterprøvelige grunde.',
  '',
  'Fra bogen stammer også den tredje bærende tanke i tænkemåden, efter',
  'lighedsprincippet og potenseringen.',
  '',
  '**Hvorfor hele mennesket og ikke det syge organ?** Fordi sygdommen i',
  'denne tænkemåde slet ikke er en ting, man kan have. Hahnemann antager,',
  'at en **livskraft** holder organismen sammen og ordner den — han kalder',
  'den åndslignende og mener dermed: ikke vejbar. Sygdom er **denne',
  'krafts forstemning**; det, lægen ser på kroppen, er kun dens udtryk.',
  'Et udslæt er da ikke et hudproblem, men den måde, et bestemt menneske',
  'lige nu er i ubalance på.',
  '',
  'Deraf følger praksissen, som mange patienter den dag i dag oplever som',
  'det egentlige: **den homøopatiske anamnese.** Førsteoptagelsen af en',
  'kronisk syg varer ved omhyggeligt arbejde en til to timer. Der spørges',
  'til alt: Hvornår begyndte det, hvad var der dengang i vejen, hvad gør',
  'det bedre, hvad værre, hvordan sover du, hvad drømmer du om, kan du',
  'lide salt eller sødt, fryser du let, hvordan var du som barn, hvad',
  'skræmmer dig? Til sidst står der ikke et fund, men et **billede** — og',
  'til dette billede søges det mest lignende middel.',
  '',
  'Dertil kommer Organons øvrige regler: **kun ét middel ad gangen**',
  '(ellers ved man ikke, hvad der har virket), **den mindst mulige dosis**,',
  'og **at vente**, i stedet for at lægge til. Og den anvisning, der',
  'forbinder homøopatien med hele naturmedicinen: Først skal de årsager',
  'fjernes, der holder mennesket sygt — dårlig luft, dårlig føde,',
  'sorg, overanstrengelse, et liv, der ikke passer.',
  '',
  'Senere, i 1828 i Köthen, kommer i „De kroniske sygdomme" en fjerde',
  'byggeklods til: læren om **miasmerne**, de dybtliggende grundonder,',
  'som kroniske lidelser skulle udgå fra. **Det er den mest spekulative',
  'del af hele bygningsværket, og den har fra begyndelsen også været',
  'omstridt blandt homøopater.** Jeg regner den til tænkemåden, fordi den',
  'hører dertil — ikke fordi jeg kunne forsvare den.',
  '',
  '## Optaget: processen i Leipzig og grænsen ved Köthen',
  '',
  'Det hører til denne historie, at den afgørende strid ikke blev udkæmpet',
  'i et forelæsningslokale, men for en domstol — og at den ikke handlede',
  'om sandheden, men om en næringsret.',
  '',
  'I 1811 flytter Hahnemann til **Leipzig** og holder fra 1812 som privat',
  'docent forelæsninger; han samler elever, og universitetet tåler ham.',
  'Hvad det ikke tåler, er noget andet: **Han udleverer selv sine',
  'lægemidler.**',
  '',
  'Hans grund er af praktisk art: Den, der fremstiller en C30, må arbejde',
  'præcist tres gange og må ikke tage fejl en eneste gang. Hahnemann',
  'troede ikke apotekerne i stand til det. Dennes grund til modsigelsen er',
  'lige så håndgribelig: **Retten til at tilberede og sælge lægemidler var',
  'deres privilegium og deres levegrundlag.** En læge, der selv',
  'dispenserer, tager omsætningen fra dem — især fordi denne læge laver',
  'hundreder af flasker af en skilling råstof.',
  '',
  'Apotekerne anlægger sag. **I 1820 afgør domstolen sagen imod',
  'Hahnemann.** Han må i Sachsen ikke længere selv udlevere sine midler —',
  'hvorved hans behandling bliver praktisk talt umulig. **I 1821 forlader',
  'han Leipzig.**',
  '',
  'Og nu kommer toget, som kortet i dette kapitel viser: Det går tres',
  'kilometer mod nordvest, over landegrænsen, ind i det lille hertugdømme',
  '**Anhalt-Köthen**. Der gælder anden ret, og der sidder en landsfyrste,',
  'som vil have ham: **Hertug Ferdinand udnævner ham til hofråd og',
  'tillader ham udtrykkeligt selv at tilberede og udlevere sine',
  'lægemidler.**',
  '',
  'Jeg beder dig se på det. **Det var ikke et argument, der reddede denne',
  'lære, men en landegrænse.** Og det var ikke en videnskabelig',
  'indvending, der drev den ud af Leipzig, men apotekernes næringsret.',
  'Den, der i dag vil vide, hvorfor homøopatien er mistroisk over for',
  'universiteterne: Det begynder her.',
  '',
  '**Og igen ledningens anden side, for at regnestykket stemmer:**',
  'Hahnemann gjorde det heller ikke let for universiteterne. Han skrev om',
  'samtidens læger i en tone, som man i dag ikke længere ville trykke; i',
  'Organons forord kalder han dem uvidende, forstokkede, skadelige. Han',
  'tålte ingen modsigelse, heller ikke fra sine egne elever: Den, der',
  'blandede hans lære med andre fremgangsmåder, var for ham en',
  '„halvhomoøopat" og færdig. **En del af den afvisning, homøopatien har',
  'mødt, er blevet skabt af dens grundlægger selv.** Den, der i to',
  'hundrede år klager over ikke at blive hørt, bør holde denne sætning ud.',
  '',
  '## Fjernforbindelsen: Köthen, koleraen, Paris 1843',
  '',
  'I Köthen bliver han fjorten år, fra 1821 til 1835. Her opstår i 1828',
  '„De kroniske sygdomme", her forfiner han potenseringen, her dør i 1830',
  'hans kone Johanna Henriette.',
  '',
  'Og her kommer i 1831 **koleraen** til Mellemeuropa. Hahnemann, der',
  'aldrig har set sygdommen med egne øjne, offentliggør anvisninger til',
  'dens behandling — kamfer i første stadie, dertil råd om at adskille de',
  'syge, om udluftning og om omgang med tøj og udskillelser. **Om',
  'kamferens værdi kan man strides; om hygiejnerådene ikke: De var',
  'rigtige, tredive år før nogen kendte smitstofferne.**',
  '',
  'I de samme årtier går læren ud i verden, og det forbløffende hurtigt',
  'for en tid uden jernbane: I 1819 bliver den i Østrig **forbudt** og',
  'først i 1837 tilladt igen. I 1825 bringer en i København uddannet læge',
  'den til New York; i 1832 kommer den til London, i 1833 opstår i',
  'Leipzig det første homøopatiske hospital. I 1830erne når den Indien —',
  'der behandler i 1839 en læge fra Siebenbürgen maharajaen Ranjit Singh,',
  'og ud af denne begyndelse bliver en bevægelse, der præger landet den',
  'dag i dag.',
  '',
  'I 1834 kommer den parisiske malerinde **Mélanie d’Hervilly** til',
  'Köthen for at lade sig behandle. I januar 1835 gifter den firsindstyvårige',
  'sig med hende; i juni flytter begge til **Paris**. Der fører han i',
  'otte år en stor og meget godt betalt praksis; byens fornemme kommer',
  'til ham. **Den 2. juli 1843 dør han, 88 år gammel.** I 1898 bliver han',
  'genbegravet på kirkegården Père Lachaise.',
  '',
  'På hans gravsted står en latinsk sætning: **„Non inutilis vixi" — jeg',
  'har ikke levet forgæves.**',
  '',
  '## De mange forbindelser: hvorfor de bliver ved i to hundrede år',
  '',
  'Og dermed til det spørgsmål, som dette kapitel egentlig skal besvare.',
  'For det er let at spotte homøopatien — dertil behøver man bare',
  'Avogadros tal og en pointe. Sværere er spørgsmålet: **Hvorfor hænger',
  'millioner af mennesker i to hundrede år fast på en metode, man så let',
  'kan spottet?**',
  '',
  'Først størrelsesordenen, så det er klart, hvad vi taler om.',
  '',
  '**Indien** fører homøopatien som et af sine officielt anerkendte',
  'medicinsystemer; den hører der til ministeriet AYUSH, der blev',
  'oprettet i 2014. Efter dets angivelser er over to hundrede tusinde',
  'homøopater registreret, der findes højskoler med statens eksamen og',
  'ambulatorier i landsbyerne. For mange mennesker der er den ikke',
  'alternativet til lægen, men **den eneste opnåelige læge**.',
  '',
  'I **Tyskland** har ifølge meningsmålinger fra instituttet for demoskopi',
  'Allensbach omtrent hver anden voksne engang taget et homøopatisk',
  'middel. I **Schweiz** stemte i 2009 omkring to tredjedele af',
  'vælgerne for at optage komplementærmedicinen i forfatningen; siden',
  '2017 betaler grundforsikringen der for homøopatien. I **Storbritannien**',
  'har kongehuset brugt den siden 1830erne; det londonske homøopatiske',
  'hospital blev grundlagt i 1849.',
  '',
  'Nu forklaringerne — og jeg begynder med dem, vore modstandere giver,',
  'fordi de for en stor del passer.',
  '',
  '**For det første: tiden.** En homøopatisk førstegangs-anamnese varer en',
  'til to timer. En speciallægesamtale i en tysk praksis varer i',
  'gennemsnit få minutter. Den, der i to timer bliver spurgt af et',
  'menneske om sit liv, går anderledes ud af rummet, end han kom ind.',
  '**Det er ikke et trick. Det er medicin, som den engang var tænkt.**',
  '',
  '**For det andet: at blive taget alvorligt.** Meget mange af homøopatiens',
  'patienter er mennesker med lange, uklare lidelser, hvor apparaterne',
  'ikke finder noget. De har ofte hørt: „Der er ikke noget." De kommer',
  'til en, der lytter, skriver deres lidelser op og ikke erklærer dem for',
  'indbildte. **Det, der hos os undertiden virker, er ganske enkelt',
  'fraværet af nedvurdering.**',
  '',
  '**For det tredje: forventningen — placeboeffekten.** Ja, jeg skriver',
  'den hen, og jeg skriver den stort. Den er målt og reel; den ændrer',
  'påviseligt smertefornemmelse, kvalme, søvn. Den virker stærkere, når',
  'omsorgen varer længere, forklaringen er mere sammenhængende, og',
  'behandleren er mere overbevist. **Alt sammen rammer det homøopatien.**',
  '',
  'Og her er det punkt, hvor min side indvender — ikke mod målingen, men',
  'mod slutningen: **Af „Det er en placeboeffekt" følger ikke „Det er',
  'intet".** En effekt, der påviseligt lindrer lidelser, er ikke et',
  'intet; den er en effekt, hvis mekanisme ligger i mennesket og ikke i',
  'stoffet. Siger man det, har man ikke forklaret virkningen væk, men kun',
  'flyttet den — og så måtte spørgsmålet lyde, hvorfor en medicin, der',
  'frembringer denne effekt pålideligt, bliver foragtet i stedet for',
  'studeret.',
  '',
  '**For det fjerde: mildheden.** Et potenseret middel har ingen',
  'bivirkninger i farmakologisk forstand — af samme grund, som',
  'modstanderne siger, at det ingen virkning har. For forældre til et',
  'lille barn, for gravide, for gamle mennesker med otte faste',
  'medikamenter er det et stærkt argument. **Den, der i over to hundrede',
  'år ikke har skadet, har i det mindste ikke overtrådt lægekunstens',
  'første regel.**',
  '',
  '**For det femte: den egne erfaring.** Det er den hårde kerne.',
  'Millioner af mennesker siger, at det har hjulpet dem, ofte efter års',
  'forgæves behandling. Og meget mange behandlere siger det samme om',
  'deres patienter. Modparten svarer på det med selvhelbredelsesforløbet,',
  'regressionen mod midten og erindringsbedraget, og disse indvendinger',
  'er velbegrundede. **De er bare ikke det sidste ord, så længe de ikke',
  'selv er prøvet på den enkelte sag.**',
  '',
  'Den stærkeste indvending mod mig lyder: Hvis alt det rækker, behøver',
  'man ikke kuglerne. **Mit ærligste svar på det er, at jeg ikke kan',
  'afgøre det.** Jeg ved, at omsorg virker. Jeg ved ikke, om midlet ud',
  'over det gør noget. Jeg iagttager ting, der får mig til at formode',
  'det — reaktioner hos spædbørn, hos dyr, hos bevidstløse, en pludselig',
  'omslag efter en enkelt dosis. **Og jeg ved, at iagttagelser af den art',
  'ikke rækker som bevis.**',
  '',
  '## Støjforstyrrelserne: hvad jeg selv må bebrejde mig',
  '',
  'Denne bog kræver af hver stemme, at den selv nævner den egne sides',
  'ubehagelige pletter i stedet for at overlade dem til modstemmen. Så',
  'vær så god.',
  '',
  '**Studierne er imod os.** Det er ingen mening, det er standen. I 2005',
  'offentliggjorde fagtidsskriftet „The Lancet" en stor analyse fra en',
  'gruppe omkring Aijing Shang, der sammenlignede homøopatiske og',
  'skolemedicinske studier; dens resultat var, at fundene om homøopatien',
  'er forenelige med en ren skinvirkning. Ledersagen dertil bar',
  'overskriften „Homøopatiens ende". I 2015 kom det australske',
  'forskningsråd NHMRC efter gennemgang af litteraturen til den slutning,',
  'at der ikke findes pålidelige belæg for en virkning ved nogen af de',
  'undersøgte sygdomme. I 2017 sluttede sammenslutningen af europæiske',
  'videnskabsakademier sig dertil.',
  '',
  'Der findes en offentliggjort metodisk kritik af Lancet-arbejdet —',
  'Lüdtke og Rutten viste i 2008, at dets resultat i høj grad afhang af,',
  'hvilke otte af de over hundrede studier der til sidst blev udvalgt.',
  '**Denne kritik er alvorlig at tage, og den ændrer ikke helhedsbilledet.**',
  'Den, der klamrer sig til den, driver rosindiskremineri — det samme,',
  'som vi bebrejder modparten.',
  '',
  '**Det berømteste forsøg på at bevise informations-tesen er slået',
  'fejl.** I 1988 offentliggjorde den franske immunolog Jacques Benveniste',
  'i „Nature" forsøg, hvori ekstremt fortyndede antistofopløsninger',
  'stadig virkede — vandets såkaldte hukommelse. Tidsskriftet trykte',
  'artiklen med et udtrykkeligt forbehold og sendte en undersøgelsesgruppe',
  'i laboratoriet. Under blindede betingelser var effekten der ikke',
  'længere; uafhængige gentagelser mislykkedes. **Det er et nederlag, og',
  'jeg fortier det ikke.**',
  '',
  '**Der findes kvaksalveri i vore rækker, og det er farligt.** Det er',
  'ikke kuglerne, der skader — det er undladelsen, der skader.',
  'Verdenssundhedsorganisationen advarede i 2009 udtrykkeligt imod at',
  'bruge homøopati til behandling af hiv, tuberkulose, malaria,',
  'spædbørnsdiarré og influenza. Der har været behandlere, der har solgt',
  'potenserede midler til rejsende som malariabeskyttelse. Der findes',
  'behandlere, der fraråder vaccinationer uden at kende sagen. Der findes',
  'kræftsyge, som derfor kom for sent i en virksom behandling. **For',
  'sådanne tilfælde findes der ingen undskyldning, og påberåbelsen af to',
  'hundrede års erfaring er da ingen forklaring, men en bortforklaring.**',
  '',
  '**Vi har overdrevet.** Ud af en omhyggelig fremgangsmåde med timevis',
  'anamnese er mange steder blevet en kugle til enhver anledning —',
  'globuli mod eksamensangst, mod tandfrembrudslidelser, mod alt. Et',
  'kompleksmiddel med otte bestanddele modsiger Hahnemanns egen regel om',
  'kun at give ét middel ad gangen. **Den, der gør læren til en vare, må',
  'ikke undre sig over spotten.**',
  '',
  '**Og vi har et tal, der er vort, brugt forkert i årtier.** I',
  'London-koleraepidemien i 1854 døde på det homøopatiske hospital 16,4',
  'procent af de optagne, i de andre huse 51,8 procent; den officielle',
  'beretning til parlamentet lod først de homøopatiske tal udeladt,',
  'hvilket var en skandale og fortælles den dag i dag. **Bare betyder',
  'tallet formentlig ikke det, vi har lavet om til det.** Den mest',
  'sandsynlige grund til forskellen er ikke, at homøopaterne gav noget',
  'virksomt, men at de **undlod** det sædvanlige: ingen åreladning, intet',
  'kalomel, ingen brækmidler — i stedet ro, varme og væske. **Ved en',
  'sygdom, hvor man tørster ihjel, er ikke at skade en behandling.** Det',
  'er en stor fortjeneste. Det er bare ikke et bevis for kuglerne.',
  '',
  'Og til sidst det punkt, der trykker mig mest, og som har ledsaget',
  'denne bog fra begyndelsen. Denne bog fortæller siden kapitel 9 igen',
  'og igen det samme mønster: **Det nye skader ofte, før det bliver til',
  'velsignelse.** Kirurgien dræbte gennem sårfeber, før den reddede;',
  'strålerne brændte deres pionerer; penicillinen reddede millioner og',
  'avlede resistensen.',
  '',
  '**Ved homøopatien står dette mønster på hovedet, og deri ligger på',
  'samme tid dens berømmelse og dens fare.** Den har i begyndelsen ikke',
  'brændt, forblødt eller forgiftet nogen — den var det milde svar på en',
  'brutal medicin, og derfor har den reddet menneskeliv ved at skåne dem',
  'for behandlingen. Men enhver fremgangsmåde, der tidligt opleves som en',
  'velsignelse, kommer i fare for at holde prøvelsen for overflødig.',
  '**Skolemedicinen har lært prøveregler af sine katastrofer. Vi havde',
  'ingen katastrofe — og har derfor i to hundrede år lært mindre, end vi',
  'kunne have gjort.** Ud af en mild idé er nogle steder blevet et dogme,',
  'der holder spørgsmålet om beviset for et angreb. Det er min egen',
  'ubehageligste plet.',
  '',
  '## Det opkald, der endnu venter',
  '',
  'Jeg har sagt, hvad jeg har at sige. Historien om en porcelænsmalers',
  'søn, der ikke længere kunne udholde sin tids medicin. Den tænkemåde,',
  'der blev til: det lignende i stedet for det modsatte, afprøvningen på',
  'raske, potenseringen, hele mennesket. Tesen om, at et middel kunne',
  'bære en information i stedet for et stof. Og regnestykket med hullerne',
  'i det, som jeg selv har åbnet.',
  '',
  '**Dette kapitels anden stemme tilhører skolemedicinen.** Den vil træde',
  'til det samme apparat og stille det spørgsmål, som jeg ikke kan',
  'besvare: **Vis mig ledningen.** Vis mig, hvad informationen består i,',
  'hvordan den bliver i vandet, hvordan den kommer ind i kroppen. Den vil',
  'fremlægge studierne og nøgternt gennemregne placebo-spørgsmålet. Og',
  'den vil — det hører til denne bog — også åbne sin egen mørke fortid:',
  'åreladningen, kviksølvet, de århundreder, hvor den med fuld',
  'overbevisning har skadet, og den arrogance, hvormed den har behandlet',
  'afvigere, fra Semmelweis til i dag.',
  '',
  'Begge sider har gode grunde. Begge sider har deres døde.',
  '',
  'Og til sidst står der ét eneste spørgsmål tilbage, som dette kapitel',
  'ikke afgør og ikke vil afgøre:',
  '',
  '**Hvad gælder som bevis — og hvem afgør det?**',
  '',
  'Den ene side svarer: den kontrollerede, blindede, gentagne',
  'undersøgelse, og intet andet. Den har gode grunde dertil, for uden',
  'denne målestok har i århundreder enhver vildfarelse overlevet, der',
  'blev ført overbevisende frem.',
  '',
  'Den anden side svarer: erfaringen fra to århundreder og fra millioner',
  'af patienter. Den har også grunde dertil, for denne målestok har',
  'bevaret fremgangsmåder, som studierne endnu ikke kunne måle — og fordi',
  'en målestok, der kun måler det, den kan måle, ikke må påstå, at',
  'dermed er alt målt.',
  '',
  '**Jeg ved, hvilket svar jeg anser for rigtigt. Du behøver ikke overtage',
  'det. Du skal bare vide, at her står to tænkemåder om virkning imod',
  'hinanden — og at spørgsmålet om, hvilken der gælder, er ældre end',
  'homøopatien og vil overleve den.**',
].join('\n');

/**
 * Stemmen, der prøver ledningen — skolemedicinen.
 *
 * Skrevet af DeepSeek (Hermes-pass, runde 17). Samme dramaturgi som den
 * første stemme: samme apparat, men spørgsmålet om den ledning, man kan
 * skære op og måle. Denne stemme repræsenterer den kontrollerede
 * undersøgelse, efterprøveligheden, måleligheden — og den slår først sin
 * egen mørke fortid op, før den prøver den anden side (tillægsregel for
 * følsomme emner i CLAUDE.md).
 */
const stimmeDieLeitungPrueft = [
  '## Det samme apparat, ledningens anden side',
  '',
  'Forestil dig apparatet fra før igen. En telefon på et bord, og omkring',
  'bordet sidder der nu andre mennesker: ingen oversættere og ingen',
  'apotekere, men mennesker, der bruger deres liv på at måle virkninger.',
  'Læger, der hver dag må beslutte, hvad de må give et menneske. Forskere,',
  'der vurderer studier. Statistikere, der ved, hvor ofte tilfældigheden',
  'lader, som om den var en virkning.',
  '',
  'Vi er skolemedicinens stemme. Og vi begynder ikke med en retfærdiggørelse,',
  'men med en indrømmelse, fordi denne bogs regel også gælder for os:',
  '**Vi nævner selv vore mørke pletter, før vi prøver andre.**',
  '',
  'Og så siger vi, hvad vi har at sige. Stemmen fra ledningen har sagt:',
  'Informationen er det virksomme, ikke stoffet. Den har sagt: En telefon',
  'indeholder ingen stemme og overfører den alligevel — altså kan også et',
  'middel uden stof bære en virkning. En smuk, en gammel, en ærlig',
  'analogi. Og den fejler på en eneste forskel, som vi må nævne, fordi',
  'ingen anden vil nævne den:',
  '',
  '**Ved telefonen kan man skære ledningen op. Ved potenseringen kan man',
  'ikke.** — og før nogen indvender, at nutidens telefoner slet ikke',
  'længere har nogen ledning: Jo, mobiltelefonen har intet kabel, og den',
  'fungerer alligevel. Vi tager indvendingen alvorligt, fordi den er',
  'præcis. Men den flytter kun argumentet: Mobiltelefonen overfører sin',
  'information over et bærerfelt, som man ikke ser, men kan måle — de',
  'elektromagnetiske bølger. Man kan påvise dem med en modtager, man kan',
  'måle deres styrke, man kan gøre dem synlige i ethvert laboratorium i',
  'verden. **Potenseringens information har intet sådant målbart',
  'bærerfelt.** Man kan stille påstanden op, at der findes et — man kan',
  'det hidtil ikke påvise. Og præcis det er forskellen: ikke den synlige',
  'ledning, men den påviselige bærer. Og en påstand, hvis bærer unddrager',
  'sig enhver måling, er ikke længere et spørgsmål om tid — den bliver',
  'til en trosag. Præcis der begynder vor strid.',
  '',
  '## Den ledning, vi selv har skåret op',
  '',
  'Først den indrømmelse, vi skylder, fordi den hører til sandheden i',
  'dette kapitel: **Vi har i århundreder skadet med fuld overbevisning.**',
  '',
  'Åreladningen — ind i det nittende århundrede den universelle',
  'behandling for næsten alt — har svækket og dræbt utallige mennesker.',
  'George Washington, De Forenede Staters første præsident, blev i 1799',
  'blandt andet behandlet med åreladninger; udsugningen af næsten to og',
  'en halv liter blod på en dag har med høj sandsynlighed fremskyndet',
  'hans død. Kalomel, et kviksølvpræparat, blev ordineret som et',
  'universalmiddel og forgiftede patienterne — tandtab, nerveskader,',
  'nyresvigt. Brækmidlerne og afføringsmidlerne, der skulle „rense"',
  'kroppen, fratog den vand og salt. **Den medicin, Hahnemann gik imod,',
  'var ikke en medicin, som nogen i dag ville forsvare. Den var et system',
  'af skade med gode hensigter.**',
  '',
  'Og vi har ikke blot behandlet forkert i denne tid — vi har også',
  'bekæmpet dem voldsomt, der vidste bedre. Ignaz Semmelweis opdagede i',
  '1847, at barselsfeberen kan forebygges ved håndvask. Han blev hånet af',
  'den medicinske elite, mistede sin stilling i Wien og døde i 1865 på et',
  'sindssygehospital — af en infektion, som hans opdagelse kunne have',
  'forhindret. **Skolemedicinens historie er også historien om dem, den',
  'lo ad, og som fik ret.**',
  '',
  'Og til denne historie hører det, vi har gjort homøopatien. Vi lod den',
  'i 1821 drive ud af Leipzig — ikke fordi dens midler påviseligt var',
  'uden virkning, men fordi den brød apotekernes og fakultetets monopol.',
  'Vi har siden smilet ad den, udelukket den og bekæmpet den — og vi har',
  'sjældent gjort det med studier, men med spot. **Det er ikke et',
  'hædersblad, og den, der læser dette kapitel, skal vide: Når vi i dag',
  'spørger homøopatien efter belæg, spørger vi efter en målestok, som vi',
  'selv i århundreder ikke har anvendt.**',
  '',
  '## Ringen uden kabel: placebo-spørgsmålet',
  '',
  'Og nu det spørgsmål, som ingen, der regner ærligt, må lade ude:',
  '**Virker midlet — eller virker forventningen?**',
  '',
  'Placeboeffekten er ingen indbildning og intet svindelnummer. Den er en',
  'målelig, fysiologisk reaktion fra kroppen på forventningen om bedring.',
  'Den moderne placeboforskning har vist: En skinbehandling kan lindre',
  'smerte, sænke blodtrykket, løfte humøret — alene ved at mennesket tror,',
  'det bliver behandlet. Kroppen udskiller egne stoffer, når den venter',
  'hjælp. **Det er ingen magi. Det er biologi — og det er den ærligste',
  'forklaring på en stor del af det, der sker i enhver lægepraksis i',
  'verden, også i vor.**',
  '',
  'Og her ligger homøopatiens egentlige kurre, og vi siger det uden',
  'hån: **I et møde, hvor et indfølende menneske lytter længe, tager',
  'alvorligt, ordinerer en lille dosis og udstråler tillid, virker mange',
  'kræfter på samme tid.** Omsorgen. Tiden. Samtalen. Forventningen. Og',
  'så også midlet — eller også ikke. Spørgsmålet er ikke, om patienterne',
  'ofte får det bedre af dette møde. Det tror vi gerne. Spørgsmålet er,',
  'hvor stor en del deraf falder på midlet, og hvor stor på alt det',
  'andet. **Præcis denne adskillelse kræver den kontrollerede',
  'undersøgelse — og præcis denne adskillelse har homøopatien hidtil',
  'ikke kunnet levere.**',
  '',
  '## Vis mig ledningen',
  '',
  'Stemmen fra ledningen har opfordret os til at søge dens ledning. Det',
  'har vi gjort — ikke af ondskab, men fordi det er vort håndværk. Og vi',
  'har ikke fundet den.',
  '',
  'Det er ikke et spørgsmål om tålmodighed, men om matematik.',
  'Potenseringen fortynder udgangsstoffet i trin af én til hundrede,',
  'oftest tolv gange eller flere. Regnemæssigt indeholder en sådan',
  'opløsning **ikke længere et eneste molekyle af udgangsstoffet** —',
  'fortyndingen ligger hinsides Avogadros tal, hinsides grænsen, under',
  'hvilken et stof fysisk ikke længere kan være til stede. Der er ganske',
  'enkelt ikke mere der, som man kunne måle. Det, der skulle overføres,',
  'måtte være en bærer, som fysikken ikke kender: en information, der',
  'bliver i vandet eller sukkeret uden at gå tabt, og som i kroppen bliver',
  'læsbar igen. **Man kan påstå det. Man kan ikke vise det.**',
  '',
  'Det berømteste forsøg på at vise det er slået fejl. I 1988',
  'offentliggjorde den franske immunolog Jacques Benveniste i',
  'fagtidsskriftet Nature en undersøgelse, der skulle bevise et „vandets',
  'hukommelse" — stærkt fortyndede antistofopløsninger, der stadig viste',
  'en virkning. Nature-redaktionen sendte en prøvegruppe ind i hans',
  'laboratorium, som gentog forsøgene under kontrollerede betingelser.',
  'Resultatet var entydigt: **Under rene betingelser forsvandt effekten.',
  'Benveniste selv indrømmede senere, at hans data ikke kunne',
  'reproduceres.** Det er standen: Der har i fem og tredive år ikke',
  'været én eneste pålideligt gentagen måling af en bærer af den',
  'homøopatiske information.',
  '',
  'Vi siger det ikke triumferende. Vi siger det, fordi reglen om ingen',
  'rygter i denne bog også gælder for os: Den, der påstår en ledning, må',
  'vise den. Så længe den ikke er vist, forbliver påstanden en påstand —',
  'og en påstand, der unddrager sig enhver måling, kan man ikke',
  'modbevise, men man kan heller ikke belægge den.',
  '',
  '## Hvad studierne siger',
  '',
  'Og så studierne, i sammenhæng, ikke i overskrifter.',
  '',
  'De findes, de store sammenfatninger. Den kendteste udkom i 2005 i',
  'fagtidsskriftet The Lancet: En gruppe omkring den schweiziske',
  'epidemiolog Matthias Egger vurderede 110 placebokontrollerede studier',
  'om homøopati og kom til det resultat, at præparaterne **ikke virkede',
  'mere end en skinbehandling**. Cochrane-gruppen, den uafhængigste',
  'instans for evidensprøvelse, har for ikke én eneste indikation fundet',
  'et overbevisende belæg for, at homøopati virker ud over placebo.',
  '**Det er studierne — og de har været stabile i tyve år.**',
  '',
  'Men vi siger også det dertil, fordi det hører til fair play: Disse',
  'studier har svagheder, og vi kender dem. Den homøopatiske behandling',
  'skræddersyes til den enkelte patient — to mennesker med samme diagnose',
  'får ofte forskellige midler. Men et prøveforløb, der arbejder med ét',
  'enkelt middel for alle, kan næppe afbilde denne kunstart om den enkelte',
  'sag. Homøopatien siger: I prøver vor fremgangsmåde med en målestok,',
  'der ikke kender vor tænkemåde. **Det er ingen uærlig indvending, og vi',
  'indrømmer den vægt.** Bare bliver spørgsmålet tilbage, som man ikke kan',
  'snakke sig uden om: Hvis den individuelle behandling er så virksom,',
  'hvorfor viser den sig så ikke i de studier, der netop er udviklet til',
  'det?',
  '',
  '## Ringen, som ingen vil høre: faren',
  '',
  'Og så den side, der ikke falder i nogen homøopatisk vennekreds, men',
  'som hører til en ærlig balance: **faren.**',
  '',
  'Den ligger ikke i globuli selv. Et middel uden stof kan ikke forgifte',
  'nogen — det er endda en fordel frem for adskillige skolemedicinske',
  'præparater. Faren ligger i det, globuli kan erstatte. **Der findes',
  'dokumenterede tilfælde, hvor mennesker med alvorlige, behandlingsbare',
  'sygdomme — lungebetændelse, malaria, tuberkulose — kun blev behandlet',
  'homøopatisk, og skolemedicinen kom for sent.** De seriøse homøopater',
  'siger selv: Ved svære akutte sygdomme hører mennesket på hospitalet.',
  'Men ikke alle holder sig dertil — og den, der behandler en alvorlig',
  'sygdom med globuli, taber tid, som ingen potensering bringer tilbage.',
  '',
  'Det er ikke et argument imod homøopatien som mild medicin. Det er et',
  'argument imod homøopatien som erstatning for akutmedicinen. **Og det',
  'er det punkt, hvor skolemedicinen ikke må give efter: Når et liv står',
  'på spil, tæller ingen tænkemåde — der tæller redningen.** Den, der',
  'benægter denne grænse, skader homøopatien mere end nogen kritiker.',
  '',
  '## Hvad vi indrømmer den',
  '',
  'Og nu det, denne stemme skylder den anden side — ikke af høflighed,',
  'men fordi det er belagt.',
  '',
  '**Hahnemann havde ret, da han angreb sin tids medicin.** Åreladningen,',
  'kalomel, brækmidlerne — det var ingen fejl i udkanten, det var',
  'systemet. Hans krav om at se hele mennesket i stedet for kun sygdommen',
  'var langt forud for sin tid. Hans lægemiddelafprøvninger på raske var',
  'det første forsøg på systematisk at iagttage virkninger, før man',
  'ordinerede dem. **Den moderne medicin har lært mere af Hahnemann, end',
  'den indrømmer — og den har gjort det uden at nævne hans navn.**',
  '',
  'Og vi indrømmer den det, vi for længe har smilet ad: tiden. Den',
  'homøopatiske førstekonsultation varer ofte en time. En time med at',
  'lytte, spørge, tage alvorligt. I vort sundhedssystem får et menneske',
  'sjældent ti minutter dertil. Placeboforskningen har lært os, hvad den',
  'time er værd: **Omsorg er ingen indbildning, den er et virksomt stof —',
  'og homøopatien har doseret det, da vi endnu holdt det for',
  'uvidenskabeligt.** Den, der smiler ad det, har ikke læst den moderne',
  'placeboforskning.',
  '',
  '## Hvad verden siger til det: Bern og Delhi',
  '',
  'Og fordi en stemme alene ikke beviser noget, her de beslutninger fra',
  'to lande, som man ikke kan afvise som uvidenskabelige.',
  '',
  'Schweiz har gjort det for. Efter en flerårig videnskabelig evaluering',
  'af komplementærmedicinen — den største, der nogensinde er gennemført',
  '— stemte folket i 2009 for at optage homøopatien og andre milde',
  'fremgangsmåder i grundforsikringen. Undersøgelsen havde vist, at',
  'patienterne med komplementær behandling ikke var mere syge, og at',
  'omkostningerne faldt. Siden er homøopatien i Schweiz ikke længere en',
  'outsider, men en del af sundhedssystemet — ikke fordi den havde',
  'bestået skolemedicinens studier, men fordi et land med et af verdens',
  'bedste sundhedssystemer har besluttet, at den hører med. **Vi siger',
  'det ikke gerne, men vi siger det: Denne beslutning er ikke truffet af',
  'kvaksalvere.**',
  '',
  'Og Indien: Der er homøopatien statsligt anerkendt, med et eget',
  'ministerium, egne højskoler og egne hospitaler. Millioner af',
  'mennesker bliver der behandlet homøopatisk — ikke af mangel på',
  'alternativer, men fordi regeringen vil det. **Man kan bebrejde Indien',
  'meget, men ikke, at det ikke kender moderne medicin.** Verdens største',
  'demokrati holder homøopatien for en seriøs behandling — og det i',
  'årtier.',
  '',
  'Vi nævner det ikke for at kapitulere. Vi nævner det, fordi dette',
  'kapitels spørgsmål må stilles ærligt: Hvis homøopatien kun var',
  'placebo, hvorfor holder to sundhedssystemer med høj standard så fast',
  'på den — det ene efter en folkeafstemning? Man kan svare: af tradition,',
  'af patientønske, af politisk kalkule. Det er muligt. Men det er et',
  'svar, der må forklares, ikke et, der forstår sig selv.',
  '',
  '## Hvad vi kunne lære af den',
  '',
  'Og til slutningen af denne del det spørgsmål, der er os ubehageligt,',
  'fordi det angår os: **Hvad kunne skolemedicinen lære af homøopatien,',
  'uden at opgive sin videnskab?**',
  '',
  'Tiden. Omsorgen. At tage alvorligt. Villigheden til at spørge',
  'mennesket, hvordan det virkelig har det, i stedet for kun at aflæse',
  'dets værdier. Den moderne medicin har i de sidste årtier fået',
  'utrolige værktøjer — og den har derved næsten mistet det, homøopatien',
  'aldrig har mistet: samtalen. Studierne siger det selv: En stor del af',
  'virkningen af enhver behandling — også den skolemedicinske — hænger på',
  'forholdet mellem behandler og behandlet. **Vi har perfektioneret',
  'teknikken og rationeret omsorgen. Homøopatien har aldrig rationeret',
  'omsorgen.**',
  '',
  'Der findes efterhånden klinikker, der forbinder begge dele: den',
  'skolemedicinske diagnostik og tiden til samtalen, skolemedicinen og de',
  'milde fremgangsmåder side om side. Patienterne går dertil, fordi de',
  'vil have begge dele: det bedste fra videnskaben og det, videnskaben',
  'ikke kan give. **Om homøopatien virker der eller kun omsorgen — den,',
  'der vil vide det præcist, må måle det. Men den, der kun smiler ad det,',
  'har ikke engang forstået spørgsmålet.**',
  '',
  '## Grænsen, hvor patienterne går deres vej',
  '',
  'Og så det spørgsmål, vi sjældnest stiller os selv, fordi det er',
  'ubehageligt: **Hvorfor går menneskene overhovedet til homøopati?**',
  'Ikke fordi de er dumme. Ikke fordi de ikke fik oplysning. Men fordi de',
  'hos os ikke finder noget, de søger.',
  '',
  'Det forrige kapitel i denne bog har trukket den moderne',
  'lægemiddelindustris balance op: stærk i diagnosen, svag ved de',
  'kroniske sygdomme. Den, der med en kronisk lidelse — udmattelse,',
  'smerter, søvnforstyrrelser, allergier — går gennem vore praksisser,',
  'får ofte en diagnose og en recept, men sjældent et svar på spørgsmålet:',
  'Hvorfor jeg? Og hvad kan jeg gøre? **Medicinen har lært at behandle',
  'sygdomme. Den har ikke lært at følge syge.**',
  '',
  'Og ind i det hul er homøopatien gået. Den tager sig tid, hvor vi ikke',
  'har den. Den spørger til hele livet, hvor vi kun aflæser værdierne.',
  'Den lover ingen helbredelse, men den lover at høre. **Så længe vi ikke',
  'lukker dette hul, vil menneskene blive ved med at gå til den — og de',
  'har ret dertil.** Man kan bekæmpe homøopatien, så meget man vil;',
  'patienterne vil blive, indtil vi giver dem det, de finder der.',
  '',
  'Det er måske dette kapitels bitreste erkendelse — ikke for',
  'homøopatien, men for os.',
  '',
  '## Hvad vi selv må bebrejde os',
  '',
  'TONE-reglen gælder dobbelt, og derfor slutter denne stemme med den',
  'liste, der ikke smigrer os.',
  '',
  '**For det første: Vi har bekæmpet homøopatien, før vi har prøvet',
  'den.** Fordrivelsen fra Leipzig var ingen videnskabelig sejr, men en',
  'magtkamp. Den, der kender sin egen fortid, bør være forsigtig med',
  'tonen.',
  '',
  '**For det andet: Vi har lært af homøopatien og ikke indrømmet det.**',
  'Dagens mildere medicin, det at lytte, blikket på hele mennesket —',
  'meget deraf er arv fra de traditioner, vi engang lo ad.',
  '',
  '**For det tredje: Vor målestok er mægtig, men ikke almægtig.** Den',
  'kontrollerede undersøgelse kan måle meget — men den måler bedst det,',
  'der lader sig isolere. Virkninger, der opstår af et forhold, af tid,',
  'af forventning, af et tillidsforhold, unddrager sig den delvist. **Den,',
  'der påstår, at kun det er virkeligt, som hans metode kan måle,',
  'forveksler landkortet med landet.**',
  '',
  '**For det fjerde: Vi har svigtet de patienter, der gik til homøopatien',
  '— ved ikke at stille noget op imod.** Den, der kommer til os og ikke',
  'bliver hørt, går et andet sted hen. Omsorgen, som homøopatien skænker,',
  'havde vi for længst måttet bygge ind i vore praksisser. I stedet har',
  'vi grinet af globuli, mens patienterne søgte en læge, der hører på',
  'dem. **Det er vor svigt, ikke deres.**',
  '',
  '## Det opkald, der endnu venter',
  '',
  'Ordstyreren — her er det formidlingscentralen — siger, at vi stadig',
  'har tid til et sidste svar. Spørgsmålet er det samme som i slutningen',
  'af den anden stemme: **Hvad gælder som bevis — og hvem afgør det?**',
  '',
  'Vort svar: **Beviset er den gentagne, blindede, kontrollerede',
  'iagttagelse — og den, der påstår en virkning, må udsætte den for',
  'denne målestok.** Uden denne målestok har i århundreder enhver',
  'vildfarelse overlevet, der blev ført overbevisende frem: åreladningen,',
  'kalomel, alle tiders vidundermidler. Vi har betalt for denne målestok',
  'for sent og for dyrt — med vore patienters blod. Vi vil ikke opgive',
  'den.',
  '',
  'Og så den anden sætning, der hører til ærligheden: **Vi ved, at vor',
  'målestok ikke måler alt.** Omsorgen lader sig vanskeligt presse ind i',
  'studier, tiden, tilliden. Måske findes der virkninger, som vort',
  'instrument ikke fanger. Hvis homøopatien en dag viser en bærer, som',
  'vi kan måle, vil vi måle den — og hvis den bekræftes, vil vi skrive',
  'medicinen om. **Indtil da gælder det, der har gældt i to hundrede år:',
  'Vi kan ikke bevise, at det ikke virker. Og den kan ikke bevise, at det',
  'virker.**',
  '',
  'Det er ingen sejr og intet nederlag. Det er en uafgjort — og',
  'spørgsmålet bliver i ledningen.',
].join('\n');

const homoeopathie = {
  id: 'homoeopathie',
  titel: 'Hahnemann og homøopatien',
  epoche: 'Overgangen til det 19. århundrede',

  aufhaenger: {
    frage:
      'Kan et middel virke, når der ikke er mere i det — eller er det i ' +
      'sidste ende informationen, der heler?',
    text: [
      'I år 1790 sidder der i Leipzig en læge, der ikke længere behandler',
      'syge, og oversætter en engelsk fagbog. Han hedder Samuel Hahnemann,',
      'er fem og tredive år og lever af at oversætte, fordi han ikke',
      'længere kan stå inde for sin tids medicin — åreladning, brækmidler,',
      'kviksølv.',
      '',
      'Et sted om kinabarken standser han op. Forfatterens forklaring',
      'overbeviser ham ikke. Altså gør han noget, oversættere ellers ikke',
      'gør: Han tager selv barken ind, i dagevis, i kraftig dosis — og får',
      'lidelser, der ligner den intermitterende feber, netop den sygdom,',
      'barken hjælper imod. I en fodnote til sin oversættelse skriver han',
      'den tanke ned, der vil splitte medicinen: Det, der hos den raske',
      'fremkalder en lidelse, kunne helbrede den hos den syge.',
      '',
      'Deraf opstår homøopatien — og med den den fremgangsmåde, som den',
      'dag i dag skiller vandene: potenseringen. Midlet fortyndes trinvist',
      'og rystes hver gang kraftigt, indtil der regnemæssigt ikke er et',
      'eneste molekyle af udgangsstoffet tilbage. For skolemedicinen er',
      'dermed alt sagt. For homøopatien begynder det egentlige spørgsmål',
      'først her: Et telefonkabel indeholder heller ingen stemme og',
      'overfører den alligevel.',
      '',
      'To hundrede år senere er sagen lige så uafgjort som på den første',
      'dag. Studierne taler imod homøopatien. Millioner af patienter i',
      'Tyskland, i Schweiz, i Indien taler for den. Dette kapitel',
      'fortæller begge sider fair — og stiller til sidst det spørgsmål,',
      'det egentlig handler om: Hvad gælder som bevis, og hvem afgør det?',
    ].join('\n'),
  },

  // Kortet ligger i karten/homoeopathie.js — her er kun fasehenvisningerne
  // oversat (phasen → karteHinweise), ikke selve kortet.
  karteHinweise: [
    {
      label: '1755–1789: Meißen, Leipzig, Wien — uddannelsen af en tvivler',
      hinweis:
        'Den 10. april 1755 bliver Samuel Hahnemann født i Meißen, søn af ' +
        'en porcelænsmaler ved kurfyrstens manufaktur. Han går på ' +
        'fyrsteskolen St. Afra, studerer fra 1775 i Leipzig, tager i 1777 ' +
        'til Wien og derefter som læge og bibliotekar til Hermannstadt i ' +
        'Siebenbürgen. I 1779 promoveres han i Erlangen til doktor i ' +
        'medicin. Derefter flytter han fra sted til sted: Hettstedt, ' +
        'Dessau, Gommern, Dresden, Leipzig. I Dessau arbejder han i et ' +
        'apoteks laboratorium og gifter sig i 1782 med Johanna Henriette ' +
        'Küchler; i Dresden vikarierer han i slutningen af 1780erne for ' +
        'byfysikus. Fordi praksissen indbringer lidt, lever han frem for ' +
        'alt af oversættelser og kemisk arbejde.',
    },
    {
      label: '1790: kinabarkforsøget ved Leipzig',
      hinweis:
        'Ved oversættelsen af den edinburgher professor William Cullens ' +
        'læremiddellære støder Hahnemann på dennes forklaring om, at ' +
        'kinabarken hjælper mod den intermitterende feber, fordi den ' +
        'styrker maven. Han holder det for utilstrækkeligt, tager selv ' +
        'barken — to gange dagligt fire kvintin — og beskriver i en ' +
        'fodnote til sin oversættelse, hvordan der ved ham indfinder sig ' +
        'lidelser, som han sammenligner med den intermitterende febers. ' +
        'Ud af denne ene fodnote opstår den tanke, der i 1796 i ' +
        'Hufelands Journal fremstår som nyt princip: Det, der i stor ' +
        'dosis fremkalder lignende lidelser, kunne i lille dosis helbrede.',
    },
    {
      label: '1805–1810: Torgau — afprøvningerne og Organon',
      hinweis:
        'I Torgau ved Elben bor Hahnemann fra 1805 til 1811. Her opstår ' +
        'de store lægemiddelafprøvninger på raske, her skriver han sit ' +
        'hovedværk. I 1810 udkommer „Organon der rationellen Heilkunde"; ' +
        'fra anden udgave af 1819 hedder det „Organon der Heilkunst". ' +
        'Derefter følger seks bind „Reine Arzneimittellehre" (1811–1821). ' +
        'Navnet på den nye lære står fast siden 1807: homøopati, af de ' +
        'græske ord for lignende og lide.',
    },
    {
      label: '1821: processen i Leipzig — Köthen bliver tilflugtsstedet',
      hinweis:
        'Hahnemann udleverer selv sine lægemidler, fordi han ikke stoler ' +
        'på, at apotekerne kan fremstille hans fortyndinger. I ' +
        'kongeriget Sachsen krænker det imidlertid apotekernes privilegium; ' +
        'de anlægger sag, og i 1820 afgør domstolen sagen imod ham. I ' +
        '1821 forlader han Leipzig. Tres kilometer mod nordvest, i ' +
        'hertugdømmet Anhalt-Köthen, gælder anden ret: Hertug Ferdinand ' +
        'udnævner ham til hofråd og tillader ham udtrykkeligt selv at ' +
        'tilberede og udlevere sine midler. I Köthen bliver han fjorten ' +
        'år; her opstår i 1828 „De kroniske sygdomme" og i 1831 hans ' +
        'anvisninger om kolera.',
    },
    {
      label: '1835–1843: Paris — den gamle Hahnemann og verdensberømmelsen',
      hinweis:
        'Hans første kone dør i 1830. I 1834 kommer den parisiske ' +
        'malerinde Mélanie d’Hervilly til Köthen; i januar 1835 gifter de ' +
        'to sig, i juni flytter de til Paris. Der fører den firsindstyvårige ' +
        'en stor, godt betalt praksis. Den 2. juli 1843 dør han, 88 år ' +
        'gammel; i 1898 bliver han genbegravet på kirkegården Père ' +
        'Lachaise. På denne tid er homøopatien for længst nået ud over ' +
        'Europa: I 1819 bliver den forbudt i Østrig og først i 1837 ' +
        'tilladt igen, i 1825 kommer den til New York, i 1830erne til ' +
        'Briterne og Indien.',
    },
  ],

  perspektiven: [
    {
      id: 'homoeopathie',
      name: 'Stemmen fra ledningen',
      stimme: 'Opus',
      text: stimmeAusDerLeitung,
    },
    {
      id: 'schulmedizin',
      name: 'Stemmen, der prøver ledningen',
      stimme: 'DeepSeek',
      text: stimmeDieLeitungPrueft,
    },
  ],

  synthese: [
    '## Hvor de to sider mødes',
    '',
    'Lægger man dette kapitels to stemmer ved siden af hinanden, falder',
    'det først i øjnene, hvor meget de deler — mere, end to hundrede års',
    'strid lader formode.',
    '',
    '**De deler afskyen for den brutale medicin.** Homøopatien opstod som',
    'protest mod åreladning, kviksølv og brækmidler — og skolemedicinen i',
    'dette kapitel indrømmer, at denne protest var berettiget. Den har',
    'lært af sin egen mørke fortid, også selv om den sjældent indrømmer',
    'det: Åreladningen er forsvundet, kalomel også. Det, Hahnemann angreb',
    'i 1790, er i dag en grusomhed for begge sider.',
    '',
    '**De deler erkendelsen af, at omsorg heler.** Skolemedicinen har i',
    'dette kapitel selv sagt det: Timen med at lytte, at tage alvorligt,',
    'tilliden — det er intet tilbehør, det er et virksomt stof. Homøopatien',
    'har doseret det i to hundrede år. Placeboforskningen indhenter i dag',
    'det, globuli-kritikerne har smilet ad i årtier.',
    '',
    '**De deler den ærlige balance.** Begge stemmer har selv nævnt deres',
    'ubehagelige pletter: homøopatien sine kvaksalvere, sine dogmer, sin',
    'manglende påviselighed; skolemedicinen sine fordrivelser, sin',
    'arrogance, sine århundreder af skade. To sider, der viser deres sår —',
    'det er sjældent i denne strid, og det er det, der gør dette kapitel',
    'til et kapitel i medicinhistorien.',
    '',
    '**Og de deler det spørgsmål, der er større end begge:** Hvad gælder',
    'som bevis — og hvem afgør det? Den ene side svarer: undersøgelsen.',
    'Den anden: erfaringen. Og ingen af de to svar er forkert, for begge',
    'målestokke har deres blinde pletter.',
    '',
    '## Hvor de går fra hinanden',
    '',
    'Og så det punkt, hvor ingen syntese er mulig — og ingen nødvendig,',
    'for bogen vil ikke forsone det, verden ikke har forsont.',
    '',
    '**De går fra hinanden ved ledningen.** Skolemedicinen siger: Vis mig',
    'bæreren, så tror jeg på dig. Homøopatien siger: Bæreren er',
    'informationen, og den, der kun søger den i stoffet, stiller det',
    'forkerte spørgsmål. Begge har deres logik — og begge kan ikke',
    'modbevise den anden. Skolemedicinen kan ikke bevise, at det ikke',
    'virker; homøopatien kan ikke bevise, at det virker. **Det er ingen',
    'mangel på anstrengelse, det er videnens grænse — og ved denne grænse',
    'står dette kapitel bevidst stille.**',
    '',
    '**De går fra hinanden ved studierne.** Den ene side ser i de store',
    'analyser slutningen på debatten; den anden ser en fremgangsmåde, som',
    'ikke kan afbilde dens kunstart om den enkelte sag. Også her stemmer',
    'fakta overens — meta-analyserne findes —, og det, der går fra',
    'hinanden, er spørgsmålet, om målestokken passer til sagen. **Den,',
    'der holder det for afgjort, har ikke læst begge sider.**',
    '',
    '## Hvad dette kapitel betyder for bogen',
    '',
    'Tænkemåden bestemmer metoden — denne sætning har i dette kapitel',
    'fundet sin måske skarpeste form. Homøopatiens tænkemåde: Sygdommen er',
    'en forstyrrelse af helheden, og lægemidlet er en information, som',
    'kroppen forstår. Skolemedicinens tænkemåde: Sygdommen er en målelig',
    'proces, og lægemidlet er et stof med påviselig virkning. To',
    'tænkemåder, to metoder — og spørgsmålet om, hvilken der gælder, er',
    'ældre end begge.',
    '',
    'Og så er der den bro, som denne bog selv har bygget: **Det forrige',
    'kapitel har vist, at medicinen anerkender information som lægemiddel',
    '— mRNA er en byggevejledning, ikke et stof, og den heler.**',
    'Skolemedicinen har altså for længst accepteret, at information kan',
    'være medicin. Homøopatien har hævdet det samme i to hundrede år —',
    'bare uden den fedtkappe, man kan påvise. Om det er en forskel i grad',
    'eller i princip, kan dette kapitel ikke besvare. Men det er det',
    'spørgsmål, der vil afgøre morgendagens medicinhistorie.',
    '',
    '## Broen til næste kapitel',
    '',
    'Homøopatien var ikke det eneste svar på det nittende århundredes',
    'brutale medicin. I samme århundrede, hvor skolemedicinen behandlede',
    'sine syge med åreladning og kviksølv, begyndte en præst i Bayern at',
    'behandle syge med koldt vand, bevægelse og urter — og blev spottet af',
    'den samme skolemedicin, der havde spottet Hahnemann. **Kapitel 17',
    'fortæller om Sebastian Kneipp og naturmedicinen** — homøopatiens',
    'store søster, der ikke behøver globuli, intet Organon, ingen',
    'potensering. Kun vand, tillid og overbevisningen om, at kroppen',
    'hjælper sig selv, hvis man lader den.',
  ].join('\n'),

  urteil: {
    frage:
      'Hvad er for dig et bevis — undersøgelsen eller erfaringen? Og hvad ' +
      'skulle der ske, for at du troede på den anden side?',
    hinweis: [
      'Der findes her intet rigtigt og intet forkert. Tag dig de to målestokke',
      'for. Den ene: Det, der virker, må kunne vises under kontrollerede',
      'betingelser, gentaget, blindet, mod en skinbehandling — ellers',
      'overlever enhver vildfarelse, der føres overbevisende frem. Den anden:',
      'Det, der i to århundreder har hjulpet millioner af mennesker, er ikke',
      'dermed modbevist, at en fremgangsmåde ikke kan måle det. Spørg dig',
      'selv tre ting. For det første: Hvad har du sidst troet på uden at kunne',
      'bevise det — og hvorfor? For det andet: Hvad præcis skulle et forsøg',
      'vise, for at du ændrede mening; og ville du også acceptere det modsatte?',
      'For det tredje: Hvis en behandling påviseligt hjælper, men grunden dertil',
      'ligger i mennesket og ikke i midlet — er den så værdiløs eller værdifuld?',
      'Præcis mellem disse spørgsmål ligger den strid, der i to hundrede år',
      'ikke er afgjort.',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Hvad gjorde Samuel Hahnemann i 1790, da han under oversættelsen ' +
        'stødte på en passage om kinabarken?',
      antworten: [
        'Han slettede stedet fra oversættelsen.',
        'Han tog selv kinabarken ind og skrev op, hvad den udløste hos ' +
          'ham.',
        'Han gav den til en syg med intermitterende feber.',
      ],
      richtig: 1,
      erklaerung:
        'Hahnemann holdt den edinburgher professor William Cullens ' +
        'forklaring for utilstrækkelig, tog barken to gange dagligt i ' +
        'kraftig dosis og beskrev i en fodnote til sin egen oversættelse ' +
        'lidelser, som han sammenlignede med den intermitterende febers. ' +
        'I 1796 offentliggjorde han deraf det nye princip; navnet ' +
        'homøopati fik læren i 1807. Forsøget selv er senere ikke blevet ' +
        'pålideligt gentaget.',
    },
    {
      frage: 'Hvad betyder grundsætningen „Similia similibus curentur"?',
      antworten: [
        'Lignende må helbredes ved lignende.',
        'Den mindste dosis er den stærkeste.',
        'Lægen heler, naturen tier.',
      ],
      richtig: 0,
      erklaerung:
        'Sætningen står på titelbladet af „Organon" og er homøopatiens ' +
        'første grundprincip: Man søger det stof, der hos den raske ' +
        'fremkalder et så lignende lidelsesbillede som sygdommen hos den ' +
        'syge. Tanken bag: Indtrykket sætter kroppens modbevægelse i gang ' +
        '— efter denne tænkemåde heler ikke lægemidlet, men organismen ' +
        'selv.',
    },
    {
      frage: 'Hvad sker der ved den homøopatiske potensering?',
      antworten: [
        'Det virksomme stof opvarmes, indtil det kemisk omdannes.',
        'Flere virksomme stoffer blandes til et kompleksmiddel.',
        'Stoffet fortyndes trinvist og rystes eller udrives kraftigt hver ' +
          'gang.',
      ],
      richtig: 2,
      erklaerung:
        'Afgørende er for homøopatien ikke fortyndingen alene, men ' +
        'omrystningen henholdsvis udrivningen ved hvert trin — derfor ' +
        'hedder fremgangsmåden potensering eller dynamisering. Fra omkring ' +
        'den tolvte C-potens er der på grund af Avogadros tal regnemæssigt ' +
        'ikke længere noget molekyle af udgangsstoffet i. Det bestrider ' +
        'homøopatien ikke; den antager, at en information fra stoffet ' +
        'overføres.',
    },
    {
      frage: 'Hvorfor forlod Hahnemann i 1821 Leipzig?',
      antworten: [
        'Universitetet havde forbudt hans lære som uvidenskabelig.',
        'En domstol forbød ham efter apotekernes søgsmål selv at udlevere ' +
          'sine lægemidler.',
        'Han fulgte et kald til det parisiske medicinske fakultet.',
      ],
      richtig: 1,
      erklaerung:
        'I kongeriget Sachsen var tilberedningen og udleveringen af ' +
        'lægemidler apotekernes privilegium. Fordi Hahnemann selv ' +
        'fremstillede sine midler, sagsøgte de ham; i 1820 afgjorde ' +
        'domstolen sagen imod ham. I nabobertugdømmet Anhalt-Köthen ' +
        'gjaldt anden ret: Hertug Ferdinand udnævnte ham til hofråd og ' +
        'tillod ham udtrykkeligt selv at udlevere. Til Paris flyttede ' +
        'Hahnemann først i 1835, med sin anden kone Mélanie.',
    },
    {
      frage:
        'Hvad viste fagtidsskriftet „Nature"s undersøgelse af Jacques ' +
        'Benvenistes forsøg (1988)?',
      antworten: [
        'Effekten var ikke længere påviselig under blindede betingelser.',
        'Vandets hukommelse blev dermed bekræftet.',
        'Forsøgene blev aldrig kontrolleret.',
      ],
      richtig: 0,
      erklaerung:
        'Benveniste havde berettet, at ekstremt fortyndede ' +
        'antistofopløsninger stadig var virksomme. „Nature" trykte ' +
        'artiklen med et udtrykkeligt forbehold og sendte en ' +
        'undersøgelsesgruppe ind i laboratoriet; under blindede ' +
        'betingelser lod effekten sig ikke bekræfte, uafhængige gentagelser ' +
        'mislykkedes. Stemmen for homøopatien i dette kapitel nævner selv ' +
        'det som et nederlag.',
    },
  ],
};

module.exports = homoeopathie;
