// Kapitel 10 — „Jenner og vaccinationen".
//
// Det andet kapitel i den nyere tid. Det fortæller historien om
// medicinhistoriens mest succesfulde indsats — udryddelsen af kopperne —
// og samtidig om den ældste og hårdeste strid, medicinen fører med sine
// patienter. De to hører sammen og fortælles her sammen.
//
// TÆNKEMÅDE-analysen er kernen (forfatterens krav). Den spørger her:
// Hvorfor forebygge i stedet for at helbrede? (Fordi der mod kopperne
// ikke fandtes nogen behandling — det eneste håndtag lå før sygdommen.)
// Hvorfor skulle man med vilje gøre et rask menneske sygt? (Fordi alle
// vidste, at en overlever aldrig blev syg igen — kroppen lærer; og fordi
// en påført sygdom forløber mildere end en indåndet.) Hvorfor kokopperne?
// (Fordi den uskadelige slægtning giver samme lære som den dødelige —
// læreren behøver ikke at være farlig.) Hvorfor fra arm til arm? (Fordi
// der ikke fandtes noget kar, der kunne opbevare vaccinen — kun den
// levende krop.) Hvorfor tvangen? (Fordi beskyttelsen af den enkelte
// først bliver til beskyttelse af alle, når nok er med — og fordi staten
// derved opdagede en ny magt over kroppen.) Og hvorfor lod netop denne
// ene sygdom sig udrydde?
//
// LÆNGDEREGEL (forfatterens feedback 24.08.2026): Fra kapitel 9 gælder
// omvendelsen — fuldstændigt og udførligt. For dette kapitel gælder den
// dobbelt (forfatterens krav: det mørke forspil OG vaccinekritikkens
// statistik fremtrædende, ikke som en marginalnote). Udførligt betyder
// ikke opblæst: hvert afsnit fører fortællingen videre. Målt i
// tests/karte-jenner-impfung.mjs.
//
// TONE-reglen, her særligt skarp: BEGGE sider skal behandles fair. Denne
// første stemme taler FOR vaccinationen — og nævner selv de ubehagelige
// steder på sin egen side i stedet for at overlade dem til modstemmen:
// forsøgene på fanger og forældreløse børn (Newgate og Boston, 1721),
// drengen James Phipps, syfilissen, der vandrede med fra arm til arm,
// handelen med lymfen, tvangen i vaccinelovene — og vaccinekritikernes
// statistik (nedgangen i mange sygdomme begyndte før vaccinationen),
// som her ikke forbigås, men forklares. INGEN RYGTER (forfatterens
// beslutning 25.08.2026): Der står kun dokumenteret stof i teksten;
// hvor tal er omstridte, siger teksten det.
//
// Stemmer (runde 11): Den FØRSTE synsvinkel — vaccinelægerne indefra —
// er skrevet af Opus. Den ANDEN (vaccinekritikken: det mørke forspil
// set fra dem, der led under det, kurverne før vaccinationen,
// hygiejne-hypotesen og allergierne, de økonomiske interesser) og den
// endelige syntese udfylder Hermes i anden omgang.
// Synsvinkel-workflow: CLAUDE.md.
//
// INGEN GENTAGELSER (forfatterens beslutning 21.08.2026): Kapitel 1
// struktureres efter „hvem der taler her", kapitel 2 begynder med en
// scene, kapitel 3 fortæller et døgn, kapitel 4 er en brevveksling,
// kapitel 5 en bogs rejse, kapitel 6 en rundgang, kapitel 7 en
// retssag, kapitel 8 en regning, kapitel 9 et ur. Dette kapitel vælger
// den tiende dramaturgi: KÆDEN. Vaccinen i det 19. århundrede havde
// intet flaskeglas — den vandrede fra arm til arm, fra barn til barn,
// rundt om hele verden. Afsnittene er kædens led: det første led fra
// Orienten, leddet fra kostalden, de led, som ingen spurgte, det, kæden
// slæbte med — frem til det sidste led i 1977 i Somalia. Den anden
// stemme kan læse den samme kæde fra dens bristede led.
//
// Teksterne ligger som linje-arrays med `.join('\n')` — sådan forbliver
// de læsbare i repoet ved ~72 tegn (forfatteren læser dem her imod), og
// utils/markdown.js gør dem i appen igen til flydende tekst.
//
// CommonJS uden UI-imports (arkitekturregel): kontrollerbar med bart
// `node`.

/**
 * Vaccinelægernes stemme — vaccinationen indefra.
 *
 * Skrevet af Opus (runde 11). En fælles stemme for dem, der har
 * vaccineret: landlægen fra Berkeley, dem, der vaccinerede de fattige
 * i de engelske sogne, lægerne i den verdensomspændende kampagne. Hun
 * fortæller, hvorfor de gjorde, hvad de gjorde — og hun nævner selv
 * de ubehagelige pletter (tillægsregel for følsomme emner i CLAUDE.md).
 */
const stimmeDerImpfaerzte = [
  '## Kæden',
  '',
  'Forestil dig en kæde, der består af mennesker.',
  '',
  'Den begynder en eftermiddag i maj 1796 på venstre arm af en',
  'otteårig dreng i en engelsk landsby, og den ender',
  'hundredeogfirs år senere på armen af en hospitalskok i',
  'Somalia. Imellem ligger millioner af arme. For vaccinen, som',
  'dette kapitel handler om, havde i årtier hverken flaskeglas',
  'eller køling. Den levede kun i ét menneske, og for at give den',
  'videre måtte man sætte den fra den enes arm ind i den',
  'næstes. Otte dage senere var den arm kilden til den næste',
  'igen. **Vaccinationen er bogstaveligt talt gået verden rundt som',
  'en kæde — fra arm til arm, fra barn til barn.**',
  '',
  '**Det, du hører her, er synsvinklen hos dem, der vaccinerede —',
  'en tænkemåde, ikke en sandhed.** Vi taler for landlægen i',
  'Gloucestershire, for dem, der vaccinerede de fattige i de',
  'engelske sogne, for lægerne i den verdensomspændende kampagne',
  'i 1970\'erne. Vi har noget at fortælle, som er enestående i',
  'medicinhistorien: **en sygdom, der ikke findes mere.** Og vi har',
  'noget at tilstå: Denne kæde har led, som ingen har spurgt.',
  '',
  'Vi går den igennem, led for led. Også de steder, hvor den',
  'ruster.',
  '',
  '## Før kæden: hvad kopperne var',
  '',
  'For at forstå, hvorfor mennesker gjorde, som de gjorde, må du',
  'først vide, hvad de var bange for. Ikke teoretisk. Praktisk.',
  '',
  'Kopperne var i 1700-tallet allestedsnærværende i Europa. Næsten',
  'alle fik dem på et tidspunkt, oftest som børn. Historikere',
  'anslår, at omkring **fire hundrede tusinde** mennesker i Europa',
  'døde af dem hvert år. Af ti syge døde omkring tre ved den svære',
  'form. Dem, der overlevede, bar det i ansigtet resten af livet:',
  'dybe, runde ar, ofte i hundredvis. En stor del af al blindhed',
  'i den tid skyldtes kopperne.',
  '',
  'Det ramte ikke kun de fattige. Dronning Maria II. af England',
  'døde af dem i 1694, kejser Joseph I. i 1711, kong Ludvig XV. af',
  'Frankrig i 1774. I habsburgernes familier døde flere børn i en',
  'enkelt generation. **Det er vigtigt for alt det følgende:',
  'Kopperne var den ene sygdom, som rigdom ikke hjalp imod.**',
  '',
  'Og der fandtes intet. Ingen behandling, intet middel, ingen',
  'trøst ud over pleje. Lægen kunne følge feberen, dække sårene',
  'til, vejlede de pårørende — mere ikke. Den, der fik kopper,',
  'ventede på at se, om han var en af de syv af ti.',
  '',
  'Her ligger roden til hele vores tænkemåde, og den er en',
  'fortvivlelsens rod. **Hvorfor forebygge i stedet for at',
  'helbrede?** Ikke fordi vi var klogere end lægerne før os. Men',
  'fordi der ikke var noget at helbrede. Når en sygdom først er',
  'der, og ingen kan stoppe den, så er der kun ét håndtag tilbage:',
  'tiden **før**. Vaccinationen er medicinens første store indgreb',
  'i et menneske, der slet ikke er sygt. Det var nyt, og den dag i',
  'dag er det stadig det punkt, hvor meningerne skilles — også det',
  'hører ærligt med i dette kapitel: Ved enhver anden behandling',
  'venter lægen, til en syg kommer til ham. Ved vaccinationen går',
  'han til raske.',
  '',
  '## Det første led kom fra Orienten',
  '',
  'Det første værn mod kopperne var ikke en europæisk opfindelse,',
  'og det kom ikke fra et universitet. Det kom fra almindelige',
  'menneskers erfaring i Kina, Indien, Vestafrika og Det',
  'Osmanniske Rige.',
  '',
  'Metoden hed senere **variolation**, efter koppernes latinske',
  'navn. Den gik ud på med vilje at smitte et rask menneske med',
  '**ægte menneskekopper**: I Tyrkiet ridsede man huden og lagde',
  'en dråbe væske fra en let sygs pustel i såret. I Kina blæste',
  'man tørret, pulveriseret koppeskorpe op i næsen. I dele af',
  'Afrika ridsede man armen.',
  '',
  'Til England bragte budskabet **Lady Mary Wortley Montagu**,',
  'hustru til den britiske ambassadør i Konstantinopel. Hun havde',
  'selv overlevet kopperne, hendes bror var død af dem, hendes',
  'ansigt var mærket. I 1717 skrev hun hjem fra Tyrkiet, at der',
  'fandtes gamle kvinder, som i september gik fra hus til hus med',
  'en nøddeskal fuld af koppemateriale; sagen var så ufarlig, at',
  'hun ville lade den udføre på sin egen søn. Det gjorde hun i',
  '1718 i Konstantinopel og i 1721 på sin datter i London.',
  '',
  '**Hvorfor skulle man med vilje gøre et rask menneske sygt?**',
  'Det spørgsmål lyder i dag vanvittigt. Dengang havde det et rent',
  'svar i tre trin, og hvert trin byggede på en observation, som',
  'enhver kunne gøre:',
  '',
  '**For det første: Kroppen lærer og glemmer ikke.** Den, der',
  'havde overstået kopperne, fik dem aldrig igen. Det vidste alle.',
  'Derfor satte man helst mennesker med ar i ansigtet til at pleje',
  'de syge — de gjaldt som sikre. Ingen kunne forklare hvorfor.',
  'Men det holdt så pålideligt, at man kunne bygge på det.',
  '',
  '**For det andet: Ikke alle forløb er lige svære.** Nogle slap',
  'med få pustler, andre døde. Hvis beskyttelsen er den samme,',
  'uanset hvor svær sygdommen var — så er det milde forløb en ren',
  'gevinst.',
  '',
  '**For det tredje: Man kan påvirke forløbet.** Og her ligger den',
  'egentlige kunst hos de gamle variolatører. De valgte materialet',
  'fra et let tilfælde, tog kun lidt, satte det i huden i stedet',
  'for i luftvejene, valgte et robust menneske og en god årstid.',
  'Resultatet var ikke sikkert, men det var anderledes: Af hundrede',
  'variolerede døde omkring en til to. Af hundrede, der blev smittet',
  'på naturlig vis, døde tyve til tredive.',
  '',
  '**Det er regnestykket, hele forebyggelsen hviler på** — og det er',
  'et væddemål, ikke en sikkerhed. Man byttede en stor fare, som',
  'næsten sikkert ramte en på et tidspunkt, ud mod en lille fare,',
  'som man selv valgte og selv bestemte tidspunktet for. Den, der',
  'ikke accepterede regnestykket, havde en indvending, som vi aldrig',
  'kunne afkræfte og den dag i dag ikke kan afkræfte: **Den ene til',
  'to af hundrede var et menneske, som uden indgrebet måske aldrig',
  'var blevet sygt.** Og det døde af en sygdom, som en læge havde',
  'givet det.',
  '',
  'Variolationen havde endnu en pris, som vi må nævne: Den',
  'vaccinerede var selv smitsom i ugevis. Han bar ægte kopper i',
  'sig. Den, der var skødesløs, satte dermed en epidemi i gang. I',
  'England blev variolationen netop derfor forbudt ved lov i 1840,',
  'længe efter at den havde gjort sin pligt.',
  '',
  '## Newgate og Boston, 1721: prisen for den første prøve',
  '',
  'Og nu til det sted, hvor vi ikke glatter noget. For spørgsmålet',
  'om, hvor farlig metoden er, ville ingen i England besvare på sit',
  'eget barn. Så man besvarede det på mennesker, der ikke kunne',
  'sige nej.',
  '',
  'Den **9. august 1721** blev seks dødsdømte fanger i',
  '**Newgate**-fængslet i London varioleret — tre mænd og tre',
  'kvinder. Modydelsen var benådning. Læger og hoffolk så til. Alle',
  'seks overlevede, alle seks kom fri; en af kvinderne blev',
  'efterfølgende sendt til et koppehospital for at prøve, om',
  'beskyttelsen holdt.',
  '',
  'Året efter gentog man prøven på de forældreløse børn i sognet',
  'St James i Westminster. Først derefter lod prinsessen af Wales',
  'sine egne døtre vaccinere — og først derefter blev sagen',
  'socialt acceptabel i England.',
  '',
  '**Vi kalder tingene ved deres navn: Det var et menneskeforsøg',
  'på fanger og på børn uden forældre.** Et samtykke, som vi kræver',
  'i dag, fandtes der ikke og kunne ikke findes: Den, der vælger',
  'mellem galgen og en vaccination, vælger ikke frit. Den, der som',
  'forældreløst barn hører til et sogn, bliver ikke spurgt. Tidens',
  'retfærdiggørelse lød, at det jo var gået godt for alle. Det er',
  'ingen retfærdiggørelse. Det er held.',
  '',
  'Samme år skete det samme på den anden side af Atlanten, og der',
  'er historien endnu mere ubehagelig. I **Boston** hærgede en',
  'koppeepidemi i 1721. Præsten Cotton Mather kendte metoden ikke',
  'fra en bog, men fra **Onesimus**, en mand, han ejede som slave,',
  'og som stammede fra Vestafrika: Onesimus viste ham arret på sin',
  'arm og forklarede, at man i hans hjemegn beskyttede sig mod',
  'kopperne på den måde. Lægen **Zabdiel Boylston** vovede',
  'forsøget — først på sin egen seksårige søn og på to slavegjorte',
  'mennesker i sin husstand, en voksen og et lille barn.',
  '',
  'Da epidemien var forbi, havde Boylston varioleret 242',
  'mennesker. Seks af dem døde. Af de omkring 5.900 bostonianere,',
  'der var blevet smittet på naturlig vis, døde 844. **Tallene var',
  'entydige, og de var de første af deres slags i',
  'medicinhistorien: en forebyggelse, talt efter på en hel',
  'befolkning.**',
  '',
  'Og alligevel står der ved siden af en sætning, som man ikke kan',
  'regne væk: **Afrikanernes viden blev taget, de slavegjortes',
  'kroppe blev brugt, og æren gik til to hvide mænd.** Onesimus',
  'dukker næsten ikke op i medicinens bøger i over to hundrede år.',
  'Vi skriver ham her ind på den plads, han hører til: i',
  'begyndelsen.',
  '',
  '## Leddet fra kostalden',
  '',
  'Og nu til Gloucestershire, et landskab af enge, hegn og',
  'malkekvæg.',
  '',
  'Blandt bønderne dér havde der i mands minde cirkuleret en',
  'påstand: **Den, der har haft kokopper, får ikke menneskekopper.**',
  'Kokopperne var en ubetydelig sag — en kvægsygdom, der blev',
  'overført til hænderne ved malkning: et par blærer på fingrene,',
  'et par dages utilpashed, færdig. Pigerne, der sad i stalden',
  'morgen og aften, fik dem tit. Og i koppeårene forblev de',
  'påfaldende ofte raske.',
  '',
  'En landlæge ved navn **Edward Jenner** (født 1749 i Berkeley,',
  'død dér i 1823) tog bøndernes tale alvorligt. Det er det',
  'afgørende skridt, og det er ikke et medicinsk, men et åndeligt:',
  '**Han holdt malkepigernes viden for en observation og ikke for',
  'overtro.**',
  '',
  'Jenner havde lært hos John Hunter i London, anatomen fra det',
  'niende kapitel i denne bog, og havde overtaget den sætning, der',
  'bærer hele den nye medicin: Hvorfor tænker du over det? Hvorfor',
  'prøver du det ikke? Så han samlede tilfælde. Han opsøgte',
  'malkepiger, der havde haft kokopper, og lod dem variolere — med',
  'ægte kopper. Hos dem skete der intet. Indstikket forblev uden',
  'reaktion, feberen udeblev. Hos andre tog variolationen sit',
  'sædvanlige forløb.',
  '',
  '**Hvorfor kokopperne?** Fordi Jenner ud af disse tilfælde',
  'udledte en begrundelse, der skulle blive en af de mest frugtbare',
  'i hele medicinhistorien: **Når to sygdomme ligner hinanden nok,',
  'giver den ufarlige kroppen samme lære som den dødelige.** Kroppen',
  'lærer af et ufarligt eksempel og består prøven, når det for',
  'alvor gælder. Læreren behøver ikke at være farlig.',
  '',
  'Det er hele tanken bag vaccinationen, og den er den samme den',
  'dag i dag. Alt, hvad der siden er kommet til — dræbte smitstoffer,',
  'svækkede smitstoffer, enkelte proteinbyggesten, byggevejledninger —',
  'er svar på det ene spørgsmål: hvordan man giver kroppen læren',
  'uden at give den sygdommen.',
  '',
  'To ting, vi må være ærlige om her. **For det første: Jenner var',
  'ikke den første.** Bonden **Benjamin Jesty** fra Yetminster i',
  'Dorset havde i 1774 — toogtyve år før Jenner — vaccineret sin',
  'kone og sine to sønner med koppemateriale på en strikkepind for',
  'at føre dem gennem en koppebølge. De forblev forskånet hele',
  'livet. Jesty høstede spot og stenkast og skrev intet ned. Det,',
  'Jenner gjorde, og Jesty ikke gjorde, var at **prøve sagen og',
  'offentliggøre den**. Det er en stor bedrift. Bare en anden end',
  'den, der står på mindesmærkerne.',
  '',
  '**For det andet: Vaccinens oprindelse er den dag i dag ikke helt',
  'afklaret.** Nyere undersøgelser af gamle vaccinprøver tyder på,',
  'at mange af disse lymfer slet ikke indeholdt kokopper-virus, men',
  'en nær slægtning fra hesten. Jenner selv henviste gang på gang',
  'til en hestesygdom, der kom ind i staldene via karlenes hænder.',
  'For virkningen ændrer det intet. For vores vished gør det:',
  '**Vi har i årtier vaccineret med noget, som vi ikke vidste præcis,',
  'hvad var.**',
  '',
  '## Den 14. maj 1796: en dreng ved navn James Phipps',
  '',
  'På denne dag begynder kæden.',
  '',
  'Køpigen **Sarah Nelmes** havde fået kokopper ved at malke en ko;',
  'blærerne sad på hendes hånd. Jenner tog væske fra dem og satte',
  'den i to små snit på armen af den otteårige **James Phipps**,',
  'søn af hans gartner. Drengen fik, hvad man kunne forvente: en',
  'lokal pustel, et par dages utilpashed, og så intet mere.',
  '',
  'Og så kom den del, der gjorde sagen til et bevis og samtidig',
  'til et problem. Den **1. juli 1796** variolerede Jenner drengen —',
  'med ægte menneskekoppemateriale. **Han gav ham den sygdom, han',
  'ville beskytte ham imod.** Havde ideen været forkert, kunne',
  'James Phipps være død. Der skete intet. Jenner gentog senere',
  'prøven flere gange; beskyttelsen holdt.',
  '',
  '**Efter nutidens målestok er det ikke et tilladeligt forsøg.**',
  'Ingen orienteringssamtale, intet skriftligt samtykke fra',
  'forældrene, intet uafhængigt organ, der fører tilsyn med',
  'forsøget — og frem for alt: et barn, som man med vilje har',
  'påført den egentlige sygdom. Vi har i to hundrede år læst hen',
  'over det i vores egne fortællinger, fordi resultatet var så',
  'stort. Det var en fejl. **Et resultat gør ikke et forsøg',
  'baglæns tilladeligt.**',
  '',
  'Det, der kan siges til Jenners fordel, siger vi også, så du kan',
  'veje begge dele: Han brugte med variolationen en metode, der var',
  'almindelig dengang, og som mange forældre udtrykkeligt ønskede',
  'til deres børn. Han fulgte drengen hele livet, overlod ham',
  'senere et hus og mistede ham aldrig af syne. Og da han blev',
  'berømt, vaccinerede han i en lille hytte i sin have de fattige i',
  'omegnen **gratis**; han kaldte den vaccinationens tempel. Det',
  'gør ikke forsøget på barnet tilladeligt. Det viser blot, at et',
  'menneske kan være begge dele.',
  '',
  'Royal Society afviste hans første beretning. I 1798 trykte han',
  'for egen regning et tyndt skrift om kokopperne, hvori han',
  'fremlagde treogtyve tilfælde. Af det latinske ord for ko —',
  '*vacca* — stammer det navn, sagen har båret siden: vaccination.',
  'Da Louis Pasteur firs år senere udviklede sine egne vacciner,',
  'beholdt han ordet, udtrykkeligt til ære for Jenner.',
  '',
  '## Sådan løb kæden verden rundt',
  '',
  'Det, der derefter skete, er uden fortilfælde: Inden for få år løb',
  'et fund fra en engelsk kostald rundt om hele kloden. Og fordi der',
  'hverken fandtes køling eller et holdbart præparat, løb det som',
  'en kæde.',
  '',
  '**Hvorfor fra arm til arm?** Fordi der ikke fandtes noget kar,',
  'der holdt vaccinen i live. Man kendte ingen smitstoffer, ingen',
  'kulturer, intet glycerin, ingen is. Tørret lymfe på en tråd',
  'eller mellem to glasplader overlevede et par uger, ofte ikke',
  'engang det. **Den eneste pålidelige beholder for vaccinen var et',
  'levende menneske.** Så tog man på den ottende dag væske fra den',
  'sidst vaccineredes pustel og satte den i den næste arm. Bristede',
  'kæden, var vaccinen tabt i den egn, og man måtte sende bud efter',
  'ny.',
  '',
  'Sådan kom vaccinationen i 1799 til Wien og Genève, i 1800 til',
  'Boston — Benjamin Waterhouse fik fra det engelske Bath en tråd',
  'med tørret lymfe og vaccinerede dermed sin egen søn. Napoleon',
  'lod fra 1805 sin hær vaccinere og ærede Jenner, skønt deres',
  'lande førte krig; på Jenners bøn løslod han engelske fanger.',
  '',
  'Længst gik Spanien. I 1803 sendte kong Karl IV. en ekspedition',
  'under lægen **Francisco Javier de Balmis** over Atlanten for at',
  'bringe vaccinationen til de spanske kolonier og helt til',
  'Filippinerne. Da vaccinen ikke ville have overlevet overfarten,',
  'tog man **toogtyve drenge fra børnehjemmet** med — som en levende',
  'kæde. Hver niende til tiende dag blev to af dem friskt',
  'vaccineret, så vaccinen ankom. De blev ledsaget af forstanderinden',
  'på deres børnehjem, Isabel Zendal Gómez, som tog sig af dem;',
  'Verdenssundhedsorganisationen har senere hædret hende som den',
  'første kvinde i en international sundhedsmission.',
  '',
  'Den ekspedition reddede utallige liv på to kontinenter. Og den',
  'brugte toogtyve børn som beholdere. **Begge dele er sandt, og vi',
  'insisterer på, at begge dele bliver fortalt.** Det er den samme',
  'sætning som ved Newgate, ved børnehjemsbørnene i Westminster, ved',
  'de slavegjorte i Boston, ved James Phipps: Kæden har i sine',
  'tidlige led brugt de mennesker, der mindst kunne sige nej.',
  '',
  '## Det, kæden slæbte med',
  '',
  'En kæde af mennesker overfører ikke kun det, man vil overføre.',
  '',
  'Den, der sætter væske fra et barns arm ind i det næste barns',
  'arm, overfører dermed også blod. Og med blodet kan en anden',
  'sygdom følge med. Præcis det skete, og den kendteste sag står i',
  'Piemonte: **I 1861 i Rivalta** blev flere dusin børn vaccineret',
  'fra armen på ét eneste spædbarn. Mere end fyrre af dem fik',
  '**syfilis**; barnet, der var kilden, havde arvet den fra sin mor,',
  'uden at man kunne se det på det. Nogle af børnene døde, nogle',
  'mødre blev smittet ved amning. Lignende tilfælde er dokumenteret',
  'fra Bremen, fra Italien og fra Frankrig.',
  '',
  '**Det er ikke et rygte fra vaccinemodstanderne. Det er vores',
  'egen sagsakter.** Vi har med beskyttelsen mod den ene sygdom',
  'spredt en anden, og vi brugte år på at indrømme det, fordi det',
  'skadede den sag, vi talte for.',
  '',
  'Løsningen kom fra koen tilbage: Man dyrkede vaccinen igen på',
  '**kalve** og tog den derfra i stedet for fra børnearme. Fra',
  '1860\'erne slog det igennem i Europa; senere kom glycerin til,',
  'som gjorde lymfen holdbar og dræbte følgebakterierne. I England',
  'blev vaccinationen fra arm til arm udtrykkeligt forbudt ved',
  'loven af **1898**. Problemet var altså løseligt — men det blev',
  'først løst, efter at børn havde betalt for det.',
  '',
  'Og så pengene, for også det hører med fra begyndelsen.',
  '',
  'Vaccinationen var fra sit første årti en **forretning**.',
  'Omrejsende vaccinatører drog fra by til by og lod sig betale pr.',
  'arm. Der blev handlet med „ægte kokopper-lymfe", og der blev',
  'forfalsket: fortyndede, gamle, virkningsløse varer. Da England i',
  '1840 gjorde vaccinationen gratis for de fattige, betalte det',
  'lægerne **pr. vaccineret hoved** — et incitament til at',
  'vaccinere meget og kontrollere lidt. Jenner selv fik penge af',
  'parlamentet to gange, i 1802 ti tusind og i 1807 tyve tusind',
  'pund; det var en formue. Han havde ikke ladet sin metode',
  'beskytte, men fattig blev han ikke.',
  '',
  'Vi siger det så tydeligt, fordi modparten vil sige det alligevel,',
  'og fordi det er sandt: **Hvor der vaccineres, bliver der også',
  'tjent.** Deraf følger ikke, at vaccinationen ikke virker. Men',
  'deraf følger, at et argument ikke er forkert, blot fordi en',
  'vaccinemodstander fører det frem.',
  '',
  '## Loven og modstanden',
  '',
  'Nu kommer den del, hvor et lægeligt tilbud blev til en statslig',
  'pligt — og hvor tvivlerne blev til en bevægelse.',
  '',
  'England gik forrest: i 1840 gratis vaccination for alle og',
  'forbud mod den gamle variolation; **i 1853 vaccinepligt** for',
  'hvert barn i de første tre levemåneder; i 1867 udvidelsen med',
  'straffe, der gentog sig, så længe barnet forblev uvaccineret; i',
  '1871 særlige vaccinationsembedsmænd, der førte registrene.',
  '',
  '**Hvorfor tvangen?** To grunde, en saglig og en mindre smuk, og',
  'vi nævner begge.',
  '',
  'Den saglige: En smitsom sygdom er ikke en privatsag. Den',
  'enkeltes beskyttelse bliver først til beskyttelse af alle, når',
  'nok er med; ellers bliver der øer, hvor sygdommen fortsætter, og',
  'hvorfra den kommer tilbage — også til spædbørnene, der endnu',
  'ikke kan vaccineres, og til de syge, der ikke tåler det. Den,',
  'der vaccinerer, beskytter ikke kun sig selv.',
  '',
  'Den mindre smukke: **Med vaccinelovene opdagede staten en ny',
  'magt over sine borgeres kroppe.** For første gang i historien',
  'grebs en regering ind i et rask menneske og straffede den, der',
  'nægtede. Vi hilste dengang det velkommen, fordi det lettede',
  'vores arbejde. Vi tænkte for lidt over, hvilken dør der dermed',
  'blev åbnet.',
  '',
  'Og tvangen ramte ulige. Den, der havde penge, kunne betale',
  'bøden. Den, der ikke havde, kom i fængsel eller mistede sit',
  'værktøj til fogeden — og fordi straffene gentog sig, var der',
  'fædre, der sad inde flere gange for samme sag. **At den første',
  'store vaccine-modstandsbevægelse var en arbejderbevægelse, er',
  'ingen tilfældighed, men en følge af disse love.**',
  '',
  'Den organiserede sig hurtigt: Anti-Vaccination League fra 1853,',
  'ligaen mod tvangsvaccination fra 1867, egne tidsskrifter fra',
  '1879. Den **23. marts 1885** gik titusinder af mennesker i',
  '**Leicester** gennem byen, brændte et billede af Jenner og',
  'krævede pligten afskaffet. En kongelig kommission hørte fra 1889',
  'til 1896 begge sider. Loven af **1898** drog konsekvensen: Den,',
  'der af samvittighedsgrunde ikke ville lade sig vaccinere, kunne',
  'lade sig fritage. Det engelske ord for samvittighedsnægteren er',
  'født i denne debat.',
  '',
  'Og hvad fulgte i Leicester? Byen vaccinerede næsten ikke mere.',
  'Den satsede i stedet på noget andet: øjeblikkelig indberetning',
  'af hvert tilfælde, øjeblikkelig isolation af den syge, karantæne',
  'for hele husstanden, desinfektion af boligen. **Og Leicester kom',
  'godt gennem koppeårene** — bedre end flere byer, der',
  'vaccinerede. Det er et resultat, der taler imod os, og det står',
  'her, fordi det er sandt. Vi har længe påstået, at Leicester kun',
  'levede af nabobyernes beskyttelse. Sandt er: isolationen var',
  'virkningsfuld. Sandt er også, at den krævede et langt større',
  'forvaltningsapparat, end de fleste steder havde.',
  '',
  'Ti år efter optoget ramte det nabolaget: I **Gloucester** brød',
  'der i 1895 en koppeepidemi ud, i en by med meget lav',
  'vaccinationsdækning. Der var knap to tusinde syge og omkring',
  '**fire hundrede og tredive døde**, overvejende børn. Byen',
  'oprettede isolationshuse og lod til sidst vaccinere i stort',
  'omfang. **Vi fører ikke dette tal frem for at triumfere.** Det',
  'står ved siden af Leicester, ikke i dets sted. Begge byer hører',
  'til i denne historie.',
  '',
  '## Kurven, der faldt før os',
  '',
  'Og nu til den indvending, der volder os mest, fordi den ikke',
  'består af forargelse, men af tal.',
  '',
  'Den lyder sådan: Den, der ser på dødelighedskurverne for de',
  'store infektionssygdomme i 1800- og 1900-tallet, ser dem **falde',
  'længe før der fandtes nogen vaccination**. Ved tuberkulosen gik',
  'det fra omkring 1850 stejlt nedad, midlet kom efter 1940. Ved',
  'skarlagensfeber faldt dødeligheden til næsten nul — **en',
  'vaccination mod skarlagensfeber findes den dag i dag ikke.**',
  'Tyfus og kolera forsvandt fra de vestlige byer med kloakeringen.',
  'Og ved mæslingerne faldt antallet af dødsfald i England og Wales',
  'mellem 1900 og 1960 med langt over halvfems procent —',
  'vaccinationen kom i 1968.',
  '',
  'Lægen Thomas McKeown gjorde i 1976 en tese ud af det, som siden',
  'har præget debatten: Den store nedgang i dødeligheden var i det',
  'væsentlige ikke medicinens værk, men ernæringens, boligens, det',
  'rene vands og arbejdsforholdenes.',
  '',
  '**Disse kurver er ægte. De er ikke forfalskede, de er ikke taget',
  'ud af sammenhæng, og den, der viser dem, er ingen forvirret',
  'hjerne.** Vi har for længe behandlet dem, som var de et angreb.',
  'De er en observation, og den har ret i det, den viser.',
  '',
  'Det, vi har at sige til det, er ingen modsigelse, men en',
  'skelnen — og den er kernen i dette afsnit. **Disse kurver måler',
  'næsten altid dødeligheden, ikke hyppigheden.** De besvarer',
  'spørgsmålet: Hvor mange af de syge døde? De besvarer ikke',
  'spørgsmålet: Hvor mange blev overhovedet syge?',
  '',
  'Og den anden kurve ser anderledes ud. Mæslinger fik næsten hvert',
  'barn frem til 1968, år for år, i bølger; antallet af',
  'sygdomstilfælde forblev højt, mens antallet af dødsfald faldt.',
  'Først med vaccinationen brød antallet af sygdomstilfælde sammen.',
  '**Med andre ord: Velstanden gjorde sygdommene mindre dødelige.',
  'Vaccinationen gjorde dem sjældnere.** Begge dele er en gevinst,',
  'og begge dele er ikke det samme.',
  '',
  'For kopperne selv gælder det med et forbehold, som vi ikke',
  'fortier: Her er vaccinationens andel i 1800-tallet sværere at',
  'regne ud, fordi isolationen af de syge, bedre boliger og',
  'indberetningspligten virkede på samme tid — se Leicester. Sikkert',
  'er det, der til sidst skete: Da man fra 1967 systematisk',
  'vaccinerede verden over, forsvandt kopperne inden for ti år fra',
  'en verden, hvor der hverken alle steder var rent vand eller',
  'alle steder gode boliger.',
  '',
  'Det samme mønster viser to begivenheder, som man ikke må',
  'planlægge, og som derfor vejer tungt. **I Nederlandene** blev',
  'enoghalvfjerds mennesker syge af børnelammelse i 1992/93, to',
  'døde — næsten udelukkende i et fællesskab, der af religiøse',
  'grunde afviste vaccinationen, midt i et land med fremragende',
  'hygiejne. Og **i Sovjetunionens efterfølgerstater** brød difteri',
  'frem igen i 1990\'erne, efter at vaccineprogrammerne var brudt',
  'sammen: mere end 150.000 tilfælde og flere tusinde døde i lande',
  'med kloakering og læger.',
  '',
  'Dermed er spørgsmålet ikke afgjort, og det påstår vi heller ikke.',
  '**Det skal besvares for hver sygdom for sig**, og svarene falder',
  'forskelligt ud. Den, der siger, at alle vaccinationer intet har',
  'udrettet, ser bort fra tal. Den, der siger, at enhver nedgang',
  'skyldes vaccinationerne, gør det samme. Det andet har vi gjort i',
  'lang tid.',
  '',
  '## Det sidste led: Merka, 26. oktober 1977',
  '',
  'Og nu enden på kæden.',
  '',
  'I 1967 talte verden stadig ti til femten millioner koppetilfælde',
  'om året og omkring to millioner døde. Det år begyndte',
  'Verdenssundhedsorganisationen sit beslutsomme program. Det endte',
  'den 26. oktober 1977 hos en hospitalskok i den somaliske by',
  'Merka. **Ali Maow Maalin** var det sidste menneske i historien,',
  'der blev smittet med kopper på naturlig vis. Han overlevede. Han',
  'vaccinerede senere selv i årtier, mod børnelammelse, og døde i',
  '2013 af malaria.',
  '',
  'Det sidste tilfælde af den svære form var to år tidligere den',
  'treårige Rahima Banu i Bangladesh. Det sidste dødsfald overhovedet',
  'var i 1978 fotografen Janet Parker i Birmingham — hun døde af en',
  'virus, der var undsluppet et laboratorium. Den **8. maj 1980**',
  'erklærede Verdenssundhedsforsamlingen kopperne for udryddede.',
  '',
  '**Hvorfor lod netop denne sygdom sig udrydde — og siden ingen',
  'anden?** Dette spørgsmål er vigtigere end jubelen, fordi svaret',
  'viser, hvor begrænset vores kunnen i virkeligheden er. Det lå i',
  'seks egenskaber ved denne ene sygdom:',
  '',
  '**For det første:** Kopperne levede kun i mennesket. Der fandtes',
  'intet dyr, de kunne gemme sig i, og hvorfra de kunne vende',
  'tilbage. **For det andet:** Man kunne se dem. Den, der havde',
  'kopper, havde udslættet; stille smittebærere fandtes praktisk',
  'talt ikke. **For det tredje:** Den, der overlevede dem, var',
  'beskyttet for altid — og den, der var vaccineret, som regel i',
  'mange år. **For det fjerde:** Smitten krævede tæt kontakt og var',
  'langsom nok til, at man kunne komme den i forkøbet. **For det',
  'femte:** Der fandtes en frysetørret vaccine, der tålte varme, og',
  'fra 1965 en gaffelformet nål, som også oplærte hjælpere kunne',
  'arbejde med. **For det sjette** — og det var det egentlige',
  'indfald: Man holdt op med at ville vaccinere alle. I stedet for',
  'at vaccinere befolkninger opsøgte man hvert udbrud og vaccinerede',
  'en ring omkring det. **Man jagede ikke sygdommen, man omringede',
  'den.**',
  '',
  'Derfor er ingen anden sygdom fulgt efter. Mæslinger overføres',
  'gennem luften og er langt mere smitsomme; børnelammelse forløber',
  'i de fleste tilfælde usynligt; influenzavirus sidder i dyr;',
  'malaria har myggen. **Udryddelsen af kopperne var ikke et bevis',
  'på, at vi kan alt. Den var beviset på, at det én gang passede.**',
  '',
  'Og også denne ende har sin skygge. I slutfasen i Sydasien blev',
  'vaccinationen påtvunget mennesker. Historikeren Paul Greenough',
  'samlede i 1995 i et fagtidsskrift, hvordan vaccinationsteams i',
  'Indien mellem 1973 og 1975 om natten gik ind i huse og holdt',
  'mennesker fast, der nægtede. De involverede har senere selv',
  'beskrevet det. **Den sidste strækning af vores fags smukkeste',
  'historie er delvist gået med vold.** Den, der fortier det,',
  'fortæller historien forkert — og undrer sig senere over, at',
  'ingen tror på ham.',
  '',
  '## Kædens regnskab',
  '',
  'Lad os gøre regnskabet op, i begge retninger.',
  '',
  '**Det, der holder stik.** Kopperne er væk — den eneste sygdom i',
  'menneskehedens historie, der ikke findes mere; alene i 1900-',
  'tallet havde de anslået dræbt tre hundrede millioner mennesker.',
  'Tanken om, at kroppen kan lære af et ufarligt eksempel, bærer',
  'den dag i dag enhver vaccination. Børnelammelsen er gået fra',
  'omkring 350.000 tilfælde i 1988 til få dusin vildtype-tilfælde.',
  'Verdenssundhedsorganisationen anslår, at mæslingevaccinationen',
  'alene mellem 2000 og 2022 har forhindret omkring syvoghalvtreds',
  'millioner dødsfald — et skøn, ikke et tælleresultat, og det',
  'bygger på modelberegninger, som man bør kende, når man bruger',
  'tallet. Stivkrampe og difteri, som før i tiden rev børn bort, er',
  'blevet sjældne hos os.',
  '',
  '**Det, vi ikke er lykkedes med.** Vi har bygget vores egen',
  'metodes forhistorie på mennesker, der ikke blev spurgt: på',
  'fanger, forældreløse børn, slavegjorte, en gartnersøn, toogtyve',
  'drenge fra et børnehjem om bord på et skib. Vi har med',
  'vaccinationen fra arm til arm spredt syfilis og indrømmet det',
  'for sent. Vi har set til, mens vaccinationen blev en forretning,',
  'og bildt os ind, at det ikke rakte os. Vi hilste tvangen',
  'velkommen uden at betale regningen for den. Og vi har i årtier',
  'ikke modbevist kritikernes statistik, men ignoreret den — hvilket',
  'har skadet sagen mere end noget flyveskrift.',
  '',
  '**Det, der står åbent.** Bivirkninger er sjældne, men de er ikke',
  'nul. Koppevaccinationen selv havde svære: hjernebetændelser og',
  'dødsfald i størrelsesordenen få pr. million',
  'førstegangsvaccinationer. Netop derfor blev den efter 1980',
  'afskaffet overalt — **da sygdommen var væk, var vaccinationens',
  'risiko større end dens nytte, og vi holdt op.** Det er et',
  'regnestykke, vi må stille op for hver vaccination igen og igen,',
  'og vi stiller det ikke altid godt nok op offentligt.',
  '',
  'Og så det spørgsmål, vi ikke har noget svar på. I de lande, hvor',
  'børnesygdommene næsten er forsvundet, tager **allergier, astma og',
  'autoimmune sygdomme** til årti efter årti. I 1989 skrev',
  'epidemiologen David Strachan den formodning ned, der siden hedder',
  'hygiejne-hypotesen: Et immunsystem, der i de første leveår får',
  'for lidt at lave, kommer senere ud af trit. Børn, der vokser op',
  'på bondegårde med dyr, har markant sjældnere høfeber og astma —',
  'det er veldokumenteret.',
  '',
  'Hvad det betyder for vaccinationerne, er dermed **ikke** afgjort.',
  'Indtil videre peger tegnene på det mikrobielle miljø som helhed',
  '— stalde, søskende, snavs, tarmflora — og ikke på enkelte',
  'vaccinationer. Men spørgsmålet er berettiget, det er ikke',
  'endeligt besvaret, og **der findes den dag i dag ingen recept mod',
  'allergierne.** Vi har byttet en sygdomsbyrde ud med en anden,',
  'uden nogensinde at have regnet byttet ud. Den, der stiller dette',
  'spørgsmål, stiller et godt spørgsmål.',
  '',
  '## Hvor kæden brister: den anden stemme',
  '',
  'Vi har vist dig en kæde, der går verden rundt og ender i Somalia.',
  'Vi har fortalt den fra vores side — fra siden hos dem, der holdt',
  'nålen.',
  '',
  'Der findes en anden side, og på den ser den samme kæde anderledes',
  'ud. Derfra består den ikke af led, men af enkelte mennesker: af',
  'fangen i Newgate, der måtte vælge mellem galgen og lansetten; af',
  'børnene i Rivalta; af faderen i Leicester, der kom i fængsel,',
  'fordi han ikke ville give sit barn fra sig; af forældrene, hvis',
  'vaccinationsskade man ikke troede på.',
  '',
  '**Den anden stemme i dette kapitel tilhører vaccinekritikken** —',
  'og hun har mere end forargelse at byde på. Hun vil vise kurverne,',
  'der faldt før vaccinationen, og drage andre slutninger af dem end',
  'vi. Hun vil spørge til allergierne og til det, der er trådt i',
  'deres sted. Hun vil regne pengene efter, der tjenes på vacciner,',
  'og spørge, hvem der betaler undersøgelserne. Og hun vil stille et',
  'spørgsmål, som vi selv må stille os, og som denne bog vil lade',
  'stå åbent:',
  '',
  '**Hvorfor tåler en videnskab, der lever af tvivl, netop ved',
  'dette spørgsmål tvivlen så dårligt?**',
  '',
  'Vi har ikke noget godt svar på det. Vi har kun én erfaring:',
  'Hver gang vi har udeladt en ubehagelig plet i vores historie —',
  'Newgate, Rivalta, pengene, tvangen — har det til sidst ikke',
  'svækket tvivlerne, men os. **Den, der forsvarer en god sag med',
  'kun halvdelen af sandheden, forsvarer den dårligt.**',
].join('\n');

/**
 * Vaccinekritikken — kædens anden side. Det, succeshistorien ikke
 * fortæller: fangerne i Newgate, drengen James Phipps, syfilissen i
 * lymfen, lovens tvang, kurven, der faldt før vaccinationen — og
 * dagens åbne spørgsmål.
 *
 * Skrevet af DeepSeek (runde 11, anden omgang). Også denne stemme
 * nævner selv de ubehagelige pletter på sin egen side (tillægsregel
 * for følsomme emner) — og overholder reglen om ingen rygter: kun
 * dokumenteret stof, intet opdigtet.
 */
const stimmeDerImpfkritik = [
  '## Hvor kæden brister',
  '',
  'Den anden stemme har fortalt kæden: fra Konstantinopel til',
  'Berkeley, fra Berkeley ud i verden, fra verden til udryddelsen.',
  'Hun har selv nævnt de mørke led — Newgate, børnehjemsbørnene,',
  'James Phipps, syfilissen, de omrejsende vaccinatører. Det er',
  'mere, end hendes fag normalt indrømmer, og vi regner hende det',
  'til gode. Nu fortæller vi den samme kæde fra den anden side: fra',
  'de mennesker, den blev trukket igennem, uden at nogen spurgte,',
  'om de gav samtykke. Og fra det spørgsmål, kæden den dag i dag',
  'ikke har besvaret: Hvem gavner den — og hvem betaler prisen?',
  '',
  '## Det første led: fangerne i Newgate',
  '',
  'London, 1721. Kopperne hærger, og lægerne har en idé fra',
  'Konstantinopel: variolationen — med vilje inficere med ægte',
  'kopper, så sygdommen forløber „kontrolleret". Men ingen ved, om',
  'det virker, og ingen vil prøve det som den første. Så man henter',
  'forsøgspersonerne dér, hvor de ikke har noget valg: i',
  'Newgate-fængslet. Seks dødsdømte får tilbuddet: lade sig',
  'variolere — eller blive hængt. De vælger kniven, overlever og',
  'bliver benådet. Derefter kommer børnehjemsbørnene fra præstegården',
  'til turen, ét efter ét, uden at nogen spurgte deres forældre —',
  'hvis de havde nogen. I Boston gør Zabdiel Boylston samme år',
  'præcis det samme: Han vaccinerer hundredvis, deriblandt',
  'slavegjorte og forældreløse børn, dels mod deres vilje. Og viden',
  'til variolationen i Boston kommer fra en slavegjort mand ved navn',
  'Onesimus, der kendte metoden fra Afrika — hans viden blev brugt,',
  'hans frihed blev ikke givet.',
  '',
  'Man kan indvende: Det var 1700-tallet, sådan var tiden. Rigtigt.',
  'Men denne stemme fortæller det ikke for at fordømme — men fordi',
  'vaccinationshistoriens kæde begynder ved netop dette led: ved',
  'mennesker uden valg. Og spørgsmålet, om et menneske virkelig kan',
  'give samtykke, når det er fattigt, fanget eller slavegjort, er',
  'ikke et 1700-tals-spørgsmål. Det er spørgsmålet i enhver',
  'vaccinationskampagne den dag i dag.',
  '',
  '## Leddet fra kostalden: drengen, der ikke blev spurgt',
  '',
  'Berkeley, 14. maj 1796. Edward Jenner har hørt bøndernes',
  'historie: Den, der havde haft kokopper, fik ikke menneskekopper.',
  'Han tager lymfe fra køpigen Sarah Nelmes og vaccinerer dermed en',
  'dreng: James Phipps, otte år gammel. Drengen overlever det, og da',
  'Jenner uger senere vaccinerer ham med ægte kopper, bliver han',
  'ikke syg. Forsøget lykkes — og bliver grundlaget for vaccinationen.',
  '',
  'James Phipps blev aldrig spurgt. Ingen forælder har underskrevet,',
  'ingen læge har forklaret barnet, hvad der sker med det. I dag',
  'ville et sådant forsøg på et barn gælde som uetisk og være',
  'forbudt. Den anden stemme har indrømmet det, og vi tager det til',
  'efterretning. Men vi tilføjer: Succesen i 1796 gjorde en etisk',
  'fejl til en verdensomspændende praksis. I årtier blev børn,',
  'soldater og fattige vaccineret, uden at man sagde dem, hvad man',
  'sprøjtede ind i dem — og uden at man vidste, hvad lymfen ud over',
  'beskyttelsen også indeholdt.',
  '',
  '## Det, kæden slæbte med: syfilissen',
  '',
  'For lymfen var ingen ren vaccine. Den blev overført fra arm til',
  'arm — fra barn til barn, fra patient til patient — og med den',
  'vandrede også andre smitstoffer. I Rivalta ved Torino blev der i',
  '1861 kendt dokumenterede tilfælde, hvor børn gennem vaccinationen',
  'blev inficeret med syfilitisk lymfe; lignende tilfælde fandtes i',
  'Italien, Frankrig og England. Lægerne vidste det, diskuterede det',
  '— og vaccinerede videre, fordi nytten syntes større end skaden.',
  'Om børnenes forældre også så sådan på det, blev der ikke spurgt.',
  'Og de omrejsende vaccinatører, der drog fra landsby til landsby',
  'og solgte deres „koppelymfe" fra egen lomme, havde en interesse,',
  'der gjorde kæden beskidt: De solgte, hvad der lod sig sælge, og',
  'kontrollerede ikke, hvad de solgte.',
  '',
  '## Kæden og loven: tvangen',
  '',
  'I 1853 indfører England vaccinepligten: Hvert barn skal',
  'vaccineres, og forældre, der nægter, straffes — bøder, gentaget',
  'og forhøjet, helt til konfiskation af alt, hvad de ejede. Det var',
  'historiens første store vaccinelov, og den mødte den første store',
  'organiserede modstand: Anti-Vaccination League, der blev grundlagt',
  'i 1866, protesterne i Leicester, hvor over hundrede tusinde',
  'mennesker demonstrerede i 1885, hele byers nægtelse. Først i 1898',
  'gav England efter og tillod samvittighedsklausulen. Og i',
  'Gloucester, hvor forældrene i stort tal nægtede, døde der i 1896',
  'igen mennesker af kopper — hvad nogle så som beviset for',
  'vaccinationen, og andre som dokumentationen for, at tvangen',
  'havde ødelagt den tillid, som beskyttelse først gør mulig.',
  '',
  'Denne stemme fortæller det ikke for at sige, at vaccinepligten',
  'altid var forkert. Hun fortæller det, fordi spørgsmålet den dag i',
  'dag står åbent: Må en stat gribe ind i sine borgeres kroppe — og',
  'hvornår bliver omsorg til formynderi? Den, der ikke stiller dette',
  'spørgsmål, har intet lært af historien.',
  '',
  '## Kurven, der faldt før os',
  '',
  'Og nu det tal, der mangler i heltehistorierne. Dødeligheden ved',
  'de store infektionssygdomme — mæslinger, skarlagensfeber,',
  'tuberkulose, tyfus — begyndte at falde årtier før den respektive',
  'vaccination i både England og Tyskland. Rent vand, kloakering,',
  'bedre ernæring, mindre trængsel i boligerne: Historikeren Thomas',
  'McKeown har i halvfjerdserne dokumenteret disse sammenhænge med',
  'tal. Dødelighedskurverne faldt stejlt, før vaccinerne kom — og',
  'efter deres indførelse faldt de ofte næsten ikke stejlere. Det',
  'betyder ikke, at vaccinationerne intet udrettede; det betyder, at',
  'heltehistorien glemmer de andre helte: kloakeringens ingeniører,',
  'hygiejnens reformatorer, dem, der lærte folk om ernæring.',
  '',
  'Og det betyder noget for i dag: Børnene i vores lande får næsten',
  'ikke længere infektionssygdomme — og til gengæld allergier,',
  'neurodermatitis, astma, autoimmune sygdomme, som der i denne',
  'ophobning ikke fandtes før. Hygiejne-hypotesen siger:',
  'Immune-systemet, der ikke længere fører ægte konfrontationer,',
  'vender sig mod den egentlige krop. Infektionssygdommene er gået',
  'tilbage — men mod det, der er galt med børnene i dag, har',
  'medicinen ingen recept. Kæden har løst et problem og ladet et nyt',
  'stå åbent, og ingen ved, hvor stort det nye er.',
  '',
  '## Svar til vaccinationsfortalerne',
  '',
  'Den anden stemme har sagt, at kæden udryddede kopperne — det er',
  'sandt, og denne stemme bestrider det ikke. Hun vil blot gøre',
  'regnskabet fuldstændigt: Kæden har reddet mennesker — og den er',
  'blevet trukket gennem mennesker, der ikke blev spurgt. Hun har',
  'besejret sygdommen — og hun har ladet spørgsmål stå åbne, som et',
  'frit samfund ikke må feje ind under gulvtæppet: spørgsmålene om',
  'samtykke, om tvang, om bivirkninger, om penge. Den, der stiller',
  'disse spørgsmål, er ingen fjende af medicinen. Han er dens',
  'samvittighed.',
  '',
  'Og endnu en ting, fordi det ofte siges: Det er let at være imod',
  'vaccinationer, fordi man ikke længere kender kopperne. Måske er',
  'det modsatte sandt: Det er let at være for vaccinationer, når man',
  'ikke længere kender angsten — og når man aldrig har spurgt, hvem',
  'der betalte kædens pris. Vaccinationskæden har to sider, og begge',
  'hører med i historien. Denne stemme har fortalt den anden side.',
].join('\n');

/** Kapitel 10 på tema-landkortet. */
const jennerImpfung = {
  id: 'jenner-impfung',
  titel: 'Jenner og vaccinationen',
  epoche: '1796 – i dag',

  aufhaenger: {
    frage:
      'Hvad har en køpige fra Gloucestershire at gøre med medicinens ' +
      'største heltehistorie — og med dens ældste stridsspørgsmål?',
    text: [
      'Kopperne har gennem århundreder dræbt flere mennesker end nogen',
      'krig. De gjorde ingen forskel på rig og fattig: Konger døde af',
      'dem som daglejere, og den, der overlevede, bar arrene i',
      'ansigtet. En behandling fandtes der ikke.',
      '',
      'Så faldt bønder i England over noget: Pigerne, der ved malkning',
      'fik de uskadelige kokopper, fik ikke menneskekopper. En landlæge',
      'tog denne observation alvorligt, afprøvede den og vaccinerede',
      'den 14. maj 1796 en otteårig dreng. Knap to hundrede år senere,',
      'i 1980, erklærede Verdenssundhedsorganisationen kopperne for',
      'udryddede — den første og hidtil eneste sygdom i historien, der',
      'ikke findes mere.',
      '',
      'Men med den samme vaccination begyndte også en af medicinens',
      'ældste og mest bitre stridigheder. Den handlede fra begyndelsen',
      'om de samme fire spørgsmål som i dag: Hvor sikkert er det? Hvem',
      'hæfter, når noget går galt? Må staten tvinge til det? Og hvem',
      'tjener på det?',
      '',
      'Dette kapitel fortæller begge dele. Triumfen — og forhistorien,',
      'der sjældent fortælles med: forsøgene på fanger og forældreløse',
      'børn, drengen, som man i 1796 med vilje satte kopper, syfilissen,',
      'der i 1800-tallet vandrede med fra arm til arm, og statistikken,',
      'som vaccinekritikere længe har lagt frem: Ved mange sygdomme var',
      'nedgangen allerede langt fremme, før der fandtes en vaccination',
      'mod dem.',
    ].join('\n'),
  },

  // Kortet ligger i utils/themen/karten/jenner-impfung.js — her er kun
  // fasehenvisningerne oversat (phasen → karteHinweise), ikke selve kortet.
  karteHinweise: [
    {
      label: '1721: variolationen når England — prøven i Newgate',
      hinweis:
        'Lady Mary Wortley Montagu havde set metoden i 1717 i ' +
        'Konstantinopel: Man giver med vilje et rask menneske ægte ' +
        'menneskekopper, så det gennemgår dem mildt. Hvor farligt det ' +
        'er, afprøves den 9. august 1721 i London på seks dødsdømte i ' +
        'Newgate-fængslet; modydelsen er benådning. Året efter gentages ' +
        'prøven på de forældreløse børn i sognet St James. Først derefter ' +
        'lader prinsessen af Wales sine egne døtre vaccinere.',
    },
    {
      label: '1774–1796: kokopperne — Yetminster og Berkeley',
      hinweis:
        'Blandt bønderne i vest cirkulerer observationen om, at ' +
        'malkepigerne med kokopper på hænderne ikke får menneskekopper. ' +
        'I 1774 vaccinerer bonden Benjamin Jesty i Yetminster (Dorset) ' +
        'sin kone og sine sønner med en strikkepind og koppemateriale. ' +
        'Den 14. maj 1796 sætter landlægen Edward Jenner i Berkeley den ' +
        'otteårige James Phipps væske fra køpigen Sarah Nelmes\' kokopper ' +
        'ind i armen — og afprøver beskyttelsen den 1. juli med ægte ' +
        'menneskekopper.',
    },
    {
      label: '1840–1867: vaccinepligten i England og Wales',
      hinweis:
        'I 1840 bliver vaccinationen gratis for de fattige, og den gamle ' +
        'variolation forbydes. I 1853 følger pligten for hvert barn i de ' +
        'første tre levemåneder, i 1867 udvidelsen med straffe, der ' +
        'gentager sig, så længe barnet forbliver uvaccineret; fra 1871 ' +
        'fører særlige vaccinationsembedsmænd registrene. Den, der kan ' +
        'betale, betaler bøden; den, der ikke kan betale, kommer i ' +
        'fængsel eller mister sit værktøj til fogeden.',
    },
    {
      label: '1885–1898: Leicester, Gloucester og samvittighedsklausulen',
      hinweis:
        'Den 23. marts 1885 går titusinder af mennesker i Leicester ' +
        'gennem byen mod vaccinepligten. Leicester vaccinerer derefter ' +
        'næsten ikke mere og satser i stedet på øjeblikkelig indberetning, ' +
        'isolation af de syge og karantæne for husstandene. I Gloucester ' +
        'bryder der i 1895/96 ved lav vaccinationsdækning en ' +
        'koppeepidemi ud, overvejende blandt børn. En kongelig kommission ' +
        'hører fra 1889 til 1896 begge sider; loven af 1898 tillader ' +
        'nægtelse af samvittighedsgrunde og forbyder overførslen fra arm ' +
        'til arm.',
    },
    {
      label: '1967–1980: vejen ud i verden og enden på kopperne',
      hinweis:
        'Vaccinen kendte hverken køling eller flaskeglas: Den rejste som ' +
        'en kæde fra arm til arm, gennem de vestlige havne til Amerika ' +
        '(1800) og med den spanske Balmis-ekspedition fra 1803 helt til ' +
        'Filippinerne. I 1967 tæller verden stadig ti til femten ' +
        'millioner koppetilfælde om året; Verdenssundhedsorganisationen ' +
        'begynder sit program med ringvaccination. Storbritannien ' +
        'indstiller den almindelige koppevaccination i 1971. Det sidste ' +
        'menneske, der blev smittet på naturlig vis, blev syg den ' +
        '26. oktober 1977 i Somalia; den 8. maj 1980 erklærer ' +
        'Verdenssundhedsforsamlingen kopperne for udryddede.',
    },
  ],

  perspektiven: [
    {
      id: 'impfbefuerworter',
      name: 'Lægernes stemme',
      stimme: 'Opus',
      text: stimmeDerImpfaerzte,
    },
    {
      id: 'impfkritik',
      name: 'Vaccinekritikkens stemme',
      stimme: 'DeepSeek',
      text: stimmeDerImpfkritik,
    },
  ],

  synthese: [
    '## Hvor de to stemmer mødes',
    '',
    'Først det fælles — og det er større, end begge siders overskrifter',
    'antyder. Begge stemmer anerkender, at kopperne var en plage, hvis',
    'udryddelse i 1980 er en af medicinens største bedrifter. Begge',
    'nævner de samme mørke led i kæden: Newgate, børnehjemsbørnene,',
    'James Phipps, syfilissen fra Rivalta, de omrejsende vaccinatører,',
    'lovens tvang. Begge er enige om, at hygiejne, vand og ernæring',
    'påbegyndte nedgangen i sygdommene før vaccinationen. Og begge ved,',
    'at der tjenes penge på vacciner — den ene side kalder det',
    'forskningens pris, den anden den interesse, der må kontrolleres.',
    'Den, der kun hører én af disse stemmer, hører kun den halve kæde.',
    '',
    '## Hvor de skilles',
    '',
    'Modsætningen begynder ved fortolkningen af de samme tal. Kurverne,',
    'der faldt før vaccinationen: For vaccinelægerne er de beviset på,',
    'at medicinen kun var én faktor blandt mange — en ærlig',
    'indrømmelse, der ikke formindsker den egne indsats. For kritikken',
    'er de beviset på, at æren for vaccinationen blev givet den, der',
    'tilkommer hygiejnen — og at man siden ikke har set så nøje på',
    'kurverne. De strides om tallenes vægt: Hvor meget af nedgangen',
    'var vaccinationen, hvor meget vandet? Svaret er ikke entydigt, og',
    'netop det er pointen. De strides om tvangen: Må staten gribe ind',
    'i sine borgeres kroppe, også når den mener det godt?',
    'Vaccinelægerne siger: Fællesskabet beskytter sig selv. Kritikken',
    'siger: Den enkelte bliver gjort til et middel. Og de strides om',
    'dagens åbne spørgsmål: Børnene har ikke mæslinger mere — men',
    'allergier, og ingen ved, om det ene har noget med det andet at',
    'gøre. Begge sider står over for den samme uvidenhed og drager',
    'modsatte slutninger af den.',
    '',
    '## Hvad dette kapitel viser for hele bogen',
    '',
    'For ellevte gang samme mønster — og nu med særlig skarphed:',
    'Tænkemåden bestemmer metoden. Forebyggelsens tænkemåde, der',
    'begyndte med Jenner, har forvandlet medicinen: Den har gjort',
    'helbredelseskunsten til en beskyttelsesmagt, der slet ikke lader',
    'sygdommen komme. Denne tænkemåde har reddet millioner af liv —',
    'og den har, som enhver tænkemåde i denne bog, sine blinde pletter:',
    'Hun måler succes på den afværgede sygdom, men ikke på den tillid,',
    'hun bruger op, og ikke på de spørgsmål, hun lader stå åbne.',
    '',
    'Og dette kapitel viser for første gang en debat, der ikke føres',
    'mellem to kulturer, men inden for den samme medicin — og det er',
    'måske det vigtigste, det har at sige: En medicin, der behandler',
    'sine kritikere som fjender, mister den tillid, den står på.',
    'Vaccinemodstanderne i Leicester var ikke dumme; de var',
    'mistroiske, fordi man ikke havde spurgt dem. Medicinen har lært',
    'af det — og glemt, at den har lært. Det spørgsmål, dette kapitel',
    'efterlader, er hele bogens spørgsmål: Hvor meget sandhed tåler en',
    'historie, der skal give mod? Svaret: mere, end man tror. Det',
    'næste kapitel fortæller om to mænd, der begreb det — Pasteur og',
    'Lister, som fandt årsagen til infektionen, som Semmelweis havde',
    'set uden at kunne sætte navn på den.',
  ].join('\n'),

  urteil: {
    frage:
      'Hvem stoler du på, når du skal beslutte, om et barn skal ' +
      'vaccineres — lægen, staten, tallene eller din mavefornemmelse? ' +
      'Og hvad skulle der ske, før du ville genoverveje din mening?',
    hinweis: [
      'Der er her hverken rigtigt eller forkert, og denne bog presser',
      'dig ikke til noget. Spørg dig selv om to ting, når du tænker',
      'over det. For det første: Hvilken slags bevis ville overbevise',
      'dig — et tal, en erfaring fra din familie, vurderingen fra et',
      'menneske, du stoler på? For det andet: Hvad ville du kræve af',
      'modparten, for at du lytter til den — og opfylder du selv det',
      'krav? Tænk også på, at beslutningen har to sider: Den angår',
      'dit eget barn, og den angår de andres børn. Begge sider i',
      'dette regnestykke er ægte.',
    ].join(' '),
  },

  quiz: [
    {
      frage: 'Hvad var variolationen, som blev almindelig i 1700-tallet?',
      antworten: [
        'En vaccination med kokopper-materiale.',
        'Den bevidste smitte af et rask menneske med ægte ' +
          'menneskekopper.',
        'En urtete mod feber.',
      ],
      richtig: 1,
      erklaerung:
        'Ved variolationen blev materiale fra en let sygs pustel bragt ' +
        'ind i huden på et rask menneske. Metoden kom fra Kina, Indien, ' +
        'Vestafrika og Det Osmanniske Rige. Den var farlig — omkring en ' +
        'til to af hundrede døde af den —, men markant mindre farlig end ' +
        'en naturlig smitte, som tyve til tredive af hundrede døde af.',
    },
    {
      frage:
        'Hvad vaccinerede Edward Jenner den 14. maj 1796 den otteårige ' +
        'James Phipps med?',
      antworten: [
        'Med væske fra kokopperne på køpigen Sarah Nelmes\' hånd.',
        'Med blodet fra en, der var kommet sig efter kopper.',
        'Med et pulver af tørret koppeskorpe.',
      ],
      richtig: 0,
      erklaerung:
        'Sarah Nelmes havde fået kokopper ved malkningen — en uskadelig ' +
        'kvægsygdom. Jenner satte væske fra dem i to små snit på ' +
        'drengens arm. Seks uger senere afprøvede han beskyttelsen ved ' +
        'at variolere ham med ægte menneskekopper. Efter nutidens ' +
        'målestok ville dette forsøg på et barn ikke være tilladeligt.',
    },
    {
      frage:
        'Hvordan blev vaccinen i 1800-tallet givet videre over lange ' +
        'strækninger?',
      antworten: [
        'I kølede glasampuller.',
        'Fra arm til arm: Væske fra den sidst vaccineredes pustel kom ' +
          'ind i den næste arm.',
        'Gennem byernes drikkevand.',
      ],
      richtig: 1,
      erklaerung:
        'Der fandtes hverken køling eller et holdbart præparat: Den ' +
        'eneste pålidelige beholder var et levende menneske. Til turen ' +
        'til Amerika tog en spansk ekspedition i 1803 endda toogtyve ' +
        'drenge fra et børnehjem med som en levende kæde. Vejen fra arm ' +
        'til arm havde en pris: Med lymfen blev der også overført ' +
        'syfilis, blandt andet i Rivalta i 1861. I England blev den ' +
        'forbudt i 1898.',
    },
    {
      frage: 'Hvornår erklærede Verdenssundhedsorganisationen kopperne for udryddede?',
      antworten: ['1918', '1953', '1980'],
      richtig: 2,
      erklaerung:
        'Erklæringen faldt den 8. maj 1980. Det sidste menneske, der ' +
        'blev smittet på naturlig vis, var hospitalskokken Ali Maow ' +
        'Maalin i Somalia den 26. oktober 1977; han overlevede. ' +
        'Kopperne er den dag i dag menneskets eneste udryddede sygdom ' +
        '— blandt andet fordi de kun fandtes i mennesket og altid var ' +
        'synlige.',
    },
    {
      frage: 'Hvad førte den engelske vaccinelov af 1898 med sig?',
      antworten: [
        'Den indførte vaccinepligten for første gang.',
        'Den tillod nægtelse af samvittighedsgrunde og afsluttede ' +
          'vaccinationen fra arm til arm.',
        'Den forbød koppevaccinationen fuldstændigt.',
      ],
      richtig: 1,
      erklaerung:
        'Vaccinepligten havde bestået i England siden 1853 og var blevet ' +
        'skærpet i 1867; imod den opstod den første store ' +
        'vaccine-modstandsbevægelse, som i 1885 bragte titusinder af ' +
        'mennesker på gaden i Leicester. Efter at en kongelig kommission ' +
        '(1889–1896) havde hørt begge sider, bragte loven af 1898 ' +
        'samvittighedsklausulen — og forbød overførslen fra arm til arm.',
    },
  ],
};

module.exports = jennerImpfung;
