// Kapitel 17 — „Kneipp og naturmedicinen".
//
// Det niende kapitel om den nyere tid — og efter homøopatien det andet,
// som forfatteren har særligt nært: Han er naturlæge og står selv i
// denne tradition. Derfor gælder her den udtrykkelige regel fra CLAUDE.md:
// Naturmedicinen bliver IKKE affærdiget som overtro og ikke latterliggjort.
// Den får sine bedste argumenter, sin egen tænkemåde og sin egen stemme —
// og den nævner selv sine ubehagelige pletter.
//
// TÆNKEMÅDE-analysen er kernen (forfatterens krav). Den spørger her:
// Hvorfor koldt vand? (Fordi den korte kuldepåvirkning udløser et svar fra
// kroppen — karrene snævrer ind, så udvider de sig, så kommer varmen; det
// er ikke vandet, der helbreder, men reaktionen på det.) Hvorfor bevægelse?
// (Fordi kroppen er bygget til bevægelse og forfalder i stilstand.) Hvorfor
// ernæring? (Fordi det, der dagligt kommer ind i mennesket, virker stærkere
// end nogen medicin, man tager sjældent.) Hvorfor lægeurter? (Fordi den
// milde gave skal støtte i stedet for at tvinge.) Hvorfor orden? (Fordi
// livsstilen er årsagen, som alt andet hænger på.) Over alt sammen står
// grundantagelsen i hele naturmedicinen: selvhelbredelseskraften — vis
// medicatrix naturae.
//
// BROEN TIL KAPITEL 18 (forfatterens krav): Kneipps fem søjler er den
// historiske forgænger for forfatterens tese „Den simple medicin" —
// bevægelse, sund kost, godt socialt miljø og lidt stress. Hvad
// vandpræsten prædikede for hundrede og halvtreds år siden, anbefaler den
// moderne medicin i dag som forebyggelse, som regel uden at nævne hans
// navn. Denne bro står i slutningen af stemmen, sammen med den ærlige
// modside (de strukturer, der gør en sund livsstil vanskelig).
//
// INGEN RYGTER (forfatterens beslutning 25.08.2026): Kun det belagte.
// Stefansried 1821, Grönenbach og kapellan Merkle, Dillingen fra 1844,
// Hahns vandbog fra 1738, Donau-badene i vinteren 1849, præstevielsen
// 1852, Wörishofen fra 1855, „Meine Wasserkur" 1886, døden den 17. juni
// 1897 — alt sammen aktmæssigt godtgjort. Diagnosen på hans
// studentersygdom er derimod historisk IKKE sikret (ofte overleveret som
// tuberkulose); teksten siger det udtrykkeligt. Lige så udtrykkeligt:
// Selvhelbredelsen i det kolde vand er en beretning, ikke et bevis.
// Ubelagte mirakelhistorier holdes ude.
//
// INNOVATIONSCYKLUSSEN (forfatterens iagttagelse 26.08.2026, rød tråd):
// Også her står mønsteret på hovedet. Naturmedicinen skadede ikke først og
// hjalp så — den var mild fra begyndelsen. Dens risiko ligger to andre
// steder: ved de hårde vandkure i det tidlige 19. århundrede, som
// overanstrengte mennesker, og i det, den billige idé blev til, så snart
// den fik succes — en forretning. Stemmen nævner begge dele selv.
//
// LÆNGDEREGEL (forfatterens feedback 24.08.2026): Fra kapitel 9 gælder det
// omvendte — fuldstændigt og udførligt. Det måles i
// tests/karte-kneipp.mjs.
//
// Stemmer (runde 18): Den FØRSTE synsvinkel — naturmedicinen indefra,
// vandets stemme — skrev Opus. Den ANDEN (skolemedicinen: sin egen
// arrogance over for „vandpræsten", hånen i stedet for prøvelsen, den sene
// anerkendelse af livsstilen som medicin, evidensen og den ærlige kritik)
// og den endelige syntese supplerede Hermes i anden omgang (Hermes-pass,
// 28.08.2026: „suppleret"). Synsvinkel-workflow: CLAUDE.md.
//
// INGEN GENTAGELSER (forfatterens beslutning 21.08.2026): Kapitel 1
// inddeler efter „hvem der taler", kapitel 2 begynder med en scene,
// kapitel 3 fortæller et døgnsforløb, kapitel 4 er en brevveksling,
// kapitel 5 en bogs rejse, kapitel 6 en rundgang, kapitel 7 en proces,
// kapitel 8 en regning, kapitel 9 et ur, kapitel 10 en kæde, kapitel 11 en
// linse, kapitel 12 et interview, kapitel 13 en sag, kapitel 14 en
// indlægsseddel, kapitel 15 en pressekonference, kapitel 16 telefonen.
// Dette kapitel vælger den attende dramaturgi: VANDET SELV. Regnen over
// Allgäu, kilden, Donau ved Dillingen, karret i Wörishofen, vandtrædningen
// — vandet fortæller, hvad man gjorde med det, og hvad det anretter i
// kroppen. Den anden stemme kan træde ind i samme form: det samme vand,
// men i måleglasset — spørgsmålet om, hvad der kan påvises deraf.
//
// Teksterne ligger som linje-arrayer med `.join('\n')` — sådan forbliver
// de læsbare i repoet ved omkring 72 tegn (forfatteren læser dem her
// imod), og utils/markdown.js gør dem igen til flydende tekst i appen.
//
// CommonJS uden UI-imports (arkitekturregel): prøvbart med rent `node`.

/**
 * Vandets stemme — naturmedicinen indefra.
 *
 * Skrevet af Opus (runde 18). En stemme, der taler for den side, der
 * arbejder med verdens billigste midler, har haft tilstrømning i hundrede
 * og halvtreds år og alligevel bliver latterliggjort: dens tænkemåde, dens
 * historie, dens erfaring. Den fortæller, hvorfor den gør, hvad den gør —
 * og den nævner selv de ubehagelige pletter (tillægsregel for følsomme
 * emner i CLAUDE.md).
 */
const stimmeDesWassers = [
  '## Regnen over Allgäu',
  '',
  'Jeg falder som regn over Allgäu. Først som tåge, der hænger i',
  'granerne, så som dråber, der siver ned i mosset. Under jorden',
  'samler jeg mig, løber gennem grus og sand og kommer et sted på en',
  'skråning frem igen — kold, klar, seks eller otte grader, næsten',
  'ens hele året rundt. Derfra går det i en bæk, i Iller, i Donau, i',
  'Sortehavet og på et tidspunkt igen op i en sky.',
  '',
  'På den vej er jeg igen og igen gået gennem mennesker. Jeg har',
  'stået i kar, hvor syge trampede rundt til op over knæene. Jeg er',
  'løbet over rygge fra vandkander uden bruser, rygge der aldrig før',
  'havde mærket koldt vand. Jeg har ligget i lærredsstykker, som man',
  'viklede omkring febersyges kroppe. Og én gang, i vinteren 1849,',
  'steg en ung, meget syg teologistuderende ned i mig — i Donau ved',
  'Dillingen, mellem isflager, i nogle øjeblikke, flere gange om',
  'ugen. Af den mand blev der en præst, som en halv verden kendte.',
  '',
  '**Det, du læser her, er naturmedicinen indefra — en tænkemåde,',
  'ikke en sandhed.** Jeg taler for den side, der arbejder med de',
  'billigste midler, der findes: vand, gang, brød, urter, søvn. Jeg',
  'vil føre dens bedste argumenter frem, så stærkt jeg kan. Og jeg',
  'vil selv nævne de steder, hvor vi står dårligt, i stedet for at',
  'vente på, at en anden gør det.',
  '',
  'Det spørgsmål, det handler om, er nemlig ikke, om jeg er våd. Det',
  'lyder:',
  '',
  '**Kan et menneske blive rask uden at få noget givet — blot ved at',
  'leve anderledes? Og hvis ja: Hvorfor bliver det så svært at',
  'udskrive og så let at latterliggøre?**',
  '',
  '## Væversønnen, der øste mig op',
  '',
  '**Den 17. maj 1821 bliver Sebastian Kneipp født i Stefansried**,',
  'en landsby af få gårde ved Ottobeuren i det bayerske Allgäu. Hans',
  'far er væver. Det betyder i denne tid: Han sidder om vinteren ved',
  'væven, tjener lidt, og når fabrikkerne i Augsburg trykker priserne,',
  'tjener han intet.',
  '',
  'Drengen passer kvæg, går som daglejer på marken og sidder som',
  'elleveårig selv ved væven. Landsbyens skole lærer ham at læse,',
  'skrive og regne, og dermed skulle det være det. Men han vil være',
  'præst. For en væversøn uden latin og uden penge er det omtrent så',
  'udsigtsrigt som en rejse til månen.',
  '',
  'To ting kommer i vejen. Den ene er en ulykke: **Efter',
  'overleveringen brænder forældrehuset ned i 1841**, og med det den',
  'lille opsparing. Den anden er et menneske. I nabobyen Grönenbach',
  'giver **kapellan Matthias Merkle** ham undervisning i latin og',
  'arbejder for, at den unge mand kommer ind på en skole indefra.',
  '**1844 bliver Kneipp optaget på gymnasiet i Dillingen an der',
  'Donau — treogtyve år gammel, blandt fjortenårige.**',
  '',
  'Jeg standser her et øjeblik, fordi det forklarer mere end nogen',
  'teori. Alt, hvad denne mand senere tilbyder, er gratis eller',
  'næsten gratis. En udhældning koster intet. At gå barfodet koster',
  'intet. Et omslag koster et lærredsstykke. Urterne vokser ved',
  'vejkanten. En helbredelseslære for folk, der ikke kan betale en',
  'læge, bliver ikke opfundet ved skrivebordet. **Den bliver opfundet',
  'af en, der selv ikke kunne betale en.**',
  '',
  '## Donau ved Dillingen, vinteren 1849',
  '',
  'I Dillingen indhenter den sene elev gymnasiet og studerer bagefter',
  'videre på lyceet. Og på et tidspunkt i disse år bliver han syg.',
  'Rigtig syg.',
  '',
  '**Overleveret er en tærende lungelidelse — hoste, opspyt,',
  'udmattelse, vægttab; som regel gøres der tuberkulose ud af det.',
  'Jeg siger udtrykkeligt: Den diagnose er historisk ikke sikret.**',
  'Der findes ingen fund, intet røntgenbillede — røntgen bliver først',
  'til i 1895, hvad strålerne angår —, ingen påvisning af smitstof.',
  'Det, der findes, er beskrivelser af gener og lægernes vurdering i',
  'disse år om, at denne studerende ikke ville blive gammel. Mere ved',
  'ingen, og den, der påstår mere, digter.',
  '',
  '**1849 falder Kneipp over en gammel bog**: skriftet af den',
  'schlesiske bylæge **Johann Siegmund Hahn (1696–1773)** med den',
  'tunge titel „Unterricht von der Krafft und Würckung des frischen',
  'Wassers in die Leiber der Menschen", **først trykt i 1738**. Hvor',
  'præcist han fandt den — på biblioteket i Dillingen, senere i',
  'München —, berettes forskelligt; selve bogen er ubestridt.',
  '',
  'Og så gør han det, som mennesker gør, der intet har at tabe:',
  '**Han afprøver det på sig selv.** Om vinteren går han til Donau,',
  'flere gange om ugen. Han klæder sig af, dykker ned i nogle',
  'øjeblikke — ikke længere — og løber så i løbetempo tilbage til sin',
  'stue, indtil han bliver varm.',
  '',
  'Efter hans egen fremstilling bliver han stærkere af det, hoster',
  'mindre, holder studiet ud og bliver til sidst otteoghalvfjerds år',
  'gammel.',
  '',
  'Nu kommer den sætning, som min side ikke skriver gerne, men som',
  'hører til i denne bog: **Det er ikke en belagt helbredelse. Det er',
  'en beretning.** Et enkelt menneske, ingen sammenligningsgruppe,',
  'ingen måling, ingen sikret udgangsdiagnose. Hvis det ikke var',
  'tuberkulose, men en langvarig, dog helbredelig betændelse, var han',
  'måske også blevet rask uden mig. **Det kan jeg ikke udelukke, og',
  'jeg lader ikke, som om jeg kunne.**',
  '',
  'Det, der kan siges, er noget mindre og alligevel ikke intet: En',
  'ung mand, som lægerne havde opgivet, begyndte at gøre noget for',
  'sin krop hver dag — koldt bad, løb, tidlig opstand, enkel kost —,',
  'og han fik det bedre. Af denne erfaring er der vokset en',
  'helbredelseslære, som millioner af mennesker har brugt. **Om',
  'erfaringen blev fortolket rigtigt, er det egentlige spørgsmål i',
  'dette kapitel.**',
  '',
  '## To, der steg ned i mig før ham',
  '',
  'Så der ikke opstår et forkert indtryk: **Kneipp har ikke opfundet',
  'mig.** Mennesker bader, så længe der har været mennesker, og det',
  'kolde vand som helbredelsesmiddel er lige så gammelt som',
  'helbredelseslæren selv. De græske læger kendte det, de romerske',
  'bade levede af det, og i klostrene i denne bog hørte badet til',
  'sygeplejen.',
  '',
  'To navne står umiddelbart før ham.',
  '',
  'Den ene er **Johann Siegmund Hahn**, hvis bog fra 1738 faldt i',
  'hænderne på Kneipp. Hahn var en uddannet læge og skrev imod moden',
  'i sin tid: I stedet for åreladning og afføringsmidler anbefalede',
  'han koldt vand, indvortes og udvortes. Han blev i vid udstrækning',
  'overset.',
  '',
  'Den anden er **Vincenz Prießnitz (1799–1851)**, en bondedreng fra',
  'Gräfenberg i Østrigsk Schlesien, der fra 1820erne drev en',
  'vandhelbredelsesanstalt og trak gæster til fra en halv Europa —',
  'uden nogen lægeuddannelse; lægestanden lagde sag an imod ham.',
  '',
  'Og her straks den første ubehagelige plet, som jeg selv åbner:',
  '**Vandkurene i disse årtier var ofte brutale.** Flere timer lange',
  'indpakninger, isnende styrtebade fra stor højde, kure, der',
  'udmattede de syge i stedet for at styrke dem. Der fandtes',
  'vandlæger, der behandlede med samme hårdhed, som skolemedicinen',
  'årelod — bare med mig i stedet for kniven. **Den, der tror, den',
  'milde medicin altid har været mild, har ikke læst det 19.',
  'århundrede.**',
  '',
  'Det bemærkelsesværdige ved Kneipp er netop, at han har lært af',
  'denne fejl. Han begyndte selv hårdt — Donau i januar er ikke et',
  'børnebad — og blev over fyrre år stadig mildere. **Korte stimuli i',
  'stedet for lange. Koldt kun på den varme krop. Aldrig indtil man',
  'fryser. Derefter bevægelse, indtil varmen er tilbage.** Det er',
  'ikke en udvanding af hans lære, det er dens kerne: En stimulus',
  'skal sætte kroppen i gang, ikke overanstrengte den.',
  '',
  '## Kapellanen, der gik til kolerasyge',
  '',
  '**1850 tager Kneipp til München for at afslutte studiet, den',
  '6. august 1852 bliver han viet til præst i Augsburg.** Derefter',
  'følger kapellanår i Biberbach og i **Boos i Illerdalen**.',
  '',
  'Der står han i 1854 over for en kolera-bølge. Han plejer de syge,',
  'går ind i husene, sørger for dem og bruger også vandbehandlinger.',
  'I landsbyen kalder de ham bagefter „kolera-kaplanen".',
  '',
  '**Hvad disse behandlinger medførte medicinsk, ved jeg ikke, og jeg',
  'påstår det heller ikke.** Kolera dræber gennem væsketab; det, der',
  'hjælper, er at drikke — at man kan gøre det meget bedre med salt',
  'og sukker i vandet, blev først forstået i det 20. århundrede. En',
  'gejstlig, der gav de syge vand og vaskede dem, gjorde altså måske',
  'præcis det rigtige, uden at kende grunden. Men det kan også være,',
  'at de overlevende alligevel ville have overlevet.',
  '',
  'Belagt er noget andet, og det tæller mere for denne historie:',
  '**Han gik hen til dem.** I en tid, hvor mange skyede de kolerasyges',
  'huse, sad denne kapellan ved deres senge. Det ry, der senere løb',
  'foran ham, begynder ikke med en helbredelse. Det begynder med, at',
  'nogen blev.',
  '',
  '**I maj 1855 bliver Kneipp forflyttet til Wörishofen som',
  'skriftefader for dominikanerinderne** — en landsby med få hundrede',
  'indbyggere mellem Wertach og Mindel. Han bliver toogfyrre år og',
  'forlader den ikke mere. Han forvalter klostergodset, holder',
  'landbrugskurser for bønderne, avler bier, passer frugttræer —',
  '**og behandler syge, der beder ham om det.** Først naboer. Så folk',
  'fra omegnen. Så fremmede. **1881 bliver han præst i byen.**',
  '',
  '## Hvad jeg anretter i kroppen — og hvad ikke',
  '',
  'Nu til kernen. Hvorfor skulle netop jeg, almindeligt koldt vand,',
  'kunne helbrede noget som helst?',
  '',
  'Svaret fra naturmedicinen begynder med en sætning, der bærer alt',
  'andet — og som er to tusind år gammel. Den stammer fra',
  'Hippokrates\' skole og hedder **vis medicatrix naturae: naturens',
  'helbredende kraft.** På dansk og uden latin:',
  '',
  '**Kroppen helbreder sig selv. Alt, hvad en behandler kan gøre, er,',
  'ikke at stå i vejen for den — og at støtte den.**',
  '',
  'Det er ikke fromhed, det er iagttagelse. Et snitsår lukker sig. En',
  'knogle vokser sammen. En forkølelse går over efter en uge, med',
  'behandling efter syv dage. Ingen læge og ingen præst gør det; de',
  'skaber betingelser. **Selvhelbredelseskraften er den eneste kraft,',
  'der overhovedet helbreder i denne ligning. Alt andet er skub.**',
  '',
  'Deraf følger et andet sygdomsbegreb. Efter denne tænkemåde er',
  'sygdom ikke en ting, man får som et brev, men anmeldelsen af, at',
  'en ligevægt er forstyrret: mellem anstrengelse og hvile, mellem',
  'varme og kulde, mellem mad og sult, mellem arbejde og søvn. **Det',
  'syge menneske er ikke ramt, det er ude af balance.** Og',
  'behandlingen arbejder ikke imod sygdommen, men for den kraft, der',
  'bringer mennesket tilbage i balance.',
  '',
  'Og nu det egentlige spørgsmål:',
  '',
  '**Hvorfor koldt vand?**',
  '',
  'Fordi jeg er en **stimulus** og intet andet. Jeg indeholder intet',
  'aktivt stof. Jeg er vand. Det, jeg gør, er ikke vandet, men',
  '**kroppens svar på det** — og det svar er observerbart, så længe',
  'der har været mennesker, og i dag også målbart:',
  '',
  '- Rammer jeg koldt på huden, trækker de små kar sig sammen.',
  '  Blodet viger indad, i dybden, til organerne.',
  '- Stimulussen varer kort — hos Kneipp sekunder. Så er jeg væk',
  '  igen.',
  '- Og nu kommer det egentlige: Kroppen svarer med en',
  '  **modbevægelse**. Karrene udvider sig, blodet skyder tilbage',
  '  i huden, den bliver rød og varm, mennesket føler sig',
  '  gennemstrømmet. Den varme kommer ikke fra mig. **Jeg er kold.',
  '  Varmen laver han selv.**',
  '',
  'Præcis det er begrundelseslogikken i hele Kneipp-kuren, og man kan',
  'sige den i én sætning: **Det er ikke behandlingen, der virker,',
  'men reaktionen på behandlingen.** Derfor den jernhårde regel, som',
  'Kneipp hamrede ind i sine folk — og som alle burde kende, der vil',
  'tage koldt brusebad:',
  '',
  '- **Koldt kun på den varme krop.** Den, der fryser, har intet at',
  '  svare med.',
  '- **Kort, ikke langt.** Stimulussen er et skub, ingen prøve.',
  '- **Derefter bevægelse eller seng, indtil varmen er tilbage.**',
  '  Udebliver den, var behandlingen forkert.',
  '',
  'Og hvorfor den stadige skiften mellem varmt og koldt,',
  'skifteudhældningerne, skiftebadene? Fordi et kar er en muskel som',
  'enhver anden: **Det, der øves regelmæssigt, bliver øvet.**',
  'Naturmedicinen kalder det **afhærdning** og mener ikke hårdhed,',
  'men tilpasningsevne — at en krop lærer at håndtere kulde, varme,',
  'træk og anstrengelse bedre, når den kender dem.',
  '',
  'Og nu den ærlige balance, for uden den ville det her være reklame.',
  '',
  '**Det, der er godt belagt:** Kulde trækker karrene sammen og varme',
  'udvider dem, det er målt. En kold stimulus øger på kort sigt',
  'hjertefrekvens, vejrtrækning og udskillelsen af stresshormoner;',
  'kroppen stiller om på vagtsomhed. Regelmæssige kuldestimuli ændrer',
  'målbart, hvor hurtigt og hvor godt nogen varmes op igen bagefter.',
  '',
  '**Det, der er svagt belagt:** at deraf bliver sundhed i det store.',
  'Der findes et par pæne undersøgelser — den kendteste er et',
  'hollandsk arbejde fra 2016, hvor over tre tusind mennesker i en',
  'måned afsluttede deres brusebad koldt; i den kolde brusegruppe lå',
  'sygemeldingerne omkring niogtyve procent lavere, mens antallet af',
  'sygedage ikke adskilte sig. **Interessant, ja. Et bevis for en',
  'helbredelsesmetode, nej.**',
  '',
  '**Det, der slet ikke er belagt:** at udhældninger og omslag',
  'helbreder bestemte sygdomme. For de enkelte behandlinger findes',
  'der små studier, ofte uden sammenligningsgruppe, næsten aldrig',
  'blindede — man kan dårligt i hemmelighed hælde koldt vand over en',
  'menneskeryg. **Den, der fra min side påstår, at virkningen af',
  'Kneipp-behandlingerne er videnskabeligt bevist, siger usandhed.**',
  'Bevist er noget andet, og det vender jeg tilbage til til sidst:',
  'virkningen af det, der står omkring mig.',
  '',
  '## Den milde hånd: udhældninger, omslag, vandtrædning',
  '',
  'Hvordan så det ud i praksis? Kneipp har beskrevet omkring hundrede',
  'behandlinger, alle gennemførlige med husråd. Et par af dem møder',
  'du den dag i dag:',
  '',
  '**Udhældningen.** En kande uden bruser, vandet løber som en',
  'sammenhængende kappe over huden — knæudhældning, lårudhældning,',
  'armudhældning, rygudhældning, ansigtsudhældning. Altid begynde',
  'længst fra hjertet, altså på højre fods yderside; hjertet skal',
  'vide, hvad der kommer. Knæudhældningen er den berømteste, fordi',
  'den kræver lidt og virker meget: kolde fødder, urolig søvn, tunge',
  'ben.',
  '',
  '**Vandtrædningen.** At gå i det lave bassin med storkegang —',
  'foden helt op af vandet, sætte den i igen —, indtil det trækker i',
  'læggene, så op, tørre af, gå. Det er den behandling, du finder i',
  'enhver kurpark i dag.',
  '',
  '**Omslaget.** Et fugtigt lærredsstykke om læg, hals eller krop,',
  'over det et tørt. Lægomslag ved feber hører i Tyskland den dag i',
  'dag til børneplejen og står endda i lægefaglige rådgivere.',
  '',
  '**At gå i duggen og i sneen.** Barfodet gennem vådt græs eller et',
  'kort øjeblik gennem frisk sne, så strømper på og gå. Kneipp holdt',
  'det for en af de bedste behandlinger overhovedet — og den koster',
  'intet.',
  '',
  '**Afvaskningen og dampen.** En hurtig afvaskning af kroppen med',
  'koldt vand om morgenen; dampbade for hoved, fødder eller underliv',
  'med høblomster eller kamille.',
  '',
  'Hvad alle disse behandlinger har til fælles, er den sene Kneipps',
  'underskrift: **kort, mildt, gentaget.** Ikke den ene store kur,',
  'men den lille vane. Han har udtrykkeligt stillet det imod sine',
  'egne begyndelser — manden, der havde badet i Donau mellem',
  'isflager, rådede gamle mennesker senere til lunkent vand.',
  '',
  '## Den anden strøm: bevægelsen',
  '',
  'Og nu det punkt, hvor de fleste mennesker bliver overraskede.',
  'Kneipp blev berømt som vandpræst — **men vandet er kun én af fem',
  'søjler**, og han selv holdt det ikke engang for den vigtigste. De',
  'andre fire er bevægelse, ernæring, lægeurter og orden.',
  '',
  '(En redelighedsfodnote: **Opdelingen i „fem søjler" har Kneipp',
  'sådan ikke skrevet ned.** Den er en senere ordning hos hans',
  'efterfølgere, som dog sammenfatter godt, hvad der står i hans',
  'bøger. Jeg bruger den, fordi den er nyttig, ikke fordi den',
  'stammer fra ham.)',
  '',
  '**Hvorfor bevægelse?**',
  '',
  'Svaret er så enkelt, at det ofte overses: **Fordi kroppen er bygget',
  'til bevægelse.** Et hjerte, der aldrig udfordres, bliver svagt. En',
  'muskel, der aldrig trækker, svinder. En knogle, der aldrig',
  'belastes, afgiver kalk. Led ernæres ikke af blod, men af bevægelse',
  '— brusken suger sig fuld som en svamp, når den presses og',
  'aflastes. **Stilstanden er ikke kroppens skånsel. Den er dens',
  'nedbrydning.**',
  '',
  'Kneipp ordinerede gang, barfodsgang, havearbejde, kløvning af',
  'brænde, gymnastik i det fri. Intet af det var nyt; nyt var, at han',
  '**ordinerede** det — som terapi, med mål og anvisning, ikke som en',
  'venlig tilrådning til sidst.',
  '',
  '**Den moderne modpart er så entydig, at den næsten er kedelig.**',
  'Verdenssundhedsorganisationen anbefaler voksne mindst hundrede og',
  'halvtreds minutters moderat anstrengende bevægelse om ugen.',
  'Bevægelse sænker efterviseligt risikoen for hjerteinfarkt,',
  'slagtilfælde, type 2-diabetes, flere kræftformer, depressioner og',
  'demens; den forbedrer blodtryk, blodsukker og søvn. **Ikke ét',
  'eneste lægemiddel i verden har så bredt et virkningsprofil med så',
  'få bivirkninger.** Det siger ikke naturmedicinen. Det siger',
  'skolemedicinen, i sine egne retningslinjer.',
  '',
  '## Den tredje strøm: ernæringen',
  '',
  '**Hvorfor ernæring?**',
  '',
  'Fordi den er det eneste stof, et menneske får i sig **hver dag**.',
  'En tablet tager man én gang, måske tre gange. Maden tager man tre',
  'gange dagligt, syv gange om ugen, et helt liv. **Det, der kommer',
  'ind dagligt, virker stærkere end det, der kommer ind sjældent —',
  'allerede af mængdegrunde.**',
  '',
  'Kneipps køkken var et allgäu-præstehjems og lyder overraskende',
  'moderne for nutidens ører: **groft brød i stedet for fint, meget',
  'korn, grøntsager og frugt, mælk, lidt kød, lidt alkohol, lidt',
  'sukker, ikke for meget kaffe — og frem for alt: ikke for meget af',
  'noget.** Han kæmpede mod to ting, han så dagligt:',
  'brændevinsdrikkeriet og de velhavendes frådseri.',
  '',
  'Hans mål var **enkelheden**, ikke askesen. Han har ikke udråbt en',
  'vidunderkost og ikke dæmoniseret fødevarer. Han sagde: enkelt,',
  'friskt, fra nærheden, med måde — og spist i ro.',
  '',
  '**Den moderne modpart:** Ernæringsforskningen i det sidste halve',
  'århundrede er nået frem til næsten samme billede. Det store',
  'spanske PREDIMED-studie viste i 2013 og i genudværdigelsen i 2018,',
  'at en middelhavskost med olivenolie og nødder gjorde hjerteinfarkter',
  'og slagtilfælde markant sjældnere. Ernæringsretningslinjer overalt',
  'i verden råder i dag til meget grønt, meget fuldkorn, bælgfrugter,',
  'lidt rødt og forarbejdet kød, lidt sukker og lidt stærkt',
  'forarbejdede fødevarer. **Det er, sagt med andre ord, køkkenet hos',
  'en allgäu-præst fra 1890.**',
  '',
  '## Den fjerde strøm: lægeurterne',
  '',
  '**Hvorfor lægeurter?**',
  '',
  'Fordi de efter denne tænkemåde **støtter i stedet for at tvinge**.',
  'En plante bringer ikke ét isoleret stof i høj dosis, men mange i',
  'lille — og kroppen skal selv klare sig med det. Kneipp brugte,',
  'hvad der vokser i Allgäu: røllike, padderok, enebær, salvie,',
  'kamille, arnica, malurt, lindeblomst, høblomster som damp og',
  'omslag. Han lod drikke te, lave omslag, gnide olier ind.',
  '',
  'Denne søjle er den ældste i denne bog — den fører tilbage til',
  'Hildegards klosterhaver, til ayurveda, til den kinesiske urtelære',
  'og til helbrederskerne, der kom før dem alle.',
  '',
  'Og den er samtidig søjlen med den **mest blandede balance**, og det',
  'i begge retninger:',
  '',
  'Opad: En god del af det moderne medicinskab stammer fra denne',
  'viden — kinin fra kinabarken, digitalis fra fingerbøl, morfin fra',
  'valmuen, aspirin fra pilebarken. Og også i dag står enkelte',
  'planter imod den strenge prøvelse: perikon virker ved lette til',
  'moderat svære depressioner i kontrollerede studier omtrent lige så',
  'godt som konventionelle antidepressiva.',
  '',
  'Nedad: **For de fleste af de urter, Kneipp brugte, findes der den',
  'dag i dag ingen overbevisende virkningstest.** Padderok som',
  'vanddrivende middel, enebær som blodrensende — det er',
  'erfaringsværdier, ikke beviser. Og en advarsel hører med, som min',
  'side alt for sjældent udtaler: **„Plante" betyder ikke „ufarlig".**',
  'Fingerbøl dræber, hjulkrone kan skade leveren, perikon svækker',
  'virkningen af p-pillen og mange andre lægemidler. Den, der anser',
  'urter for automatisk ufarlige, har ikke forstået farmakologien —',
  'og netop min side burde kende den bedst.',
  '',
  '## Den femte strøm: ordenen',
  '',
  'Og nu søjlen, som Kneipp selv holdt for den vigtigste, og som i',
  'enhver brochure kommer til sidst, fordi den er sværest at sælge.',
  '',
  '**Hvorfor orden?**',
  '',
  'Fordi efter denne tænkemåde **livsstilen er årsagen, som alt andet',
  'hænger på.** Man kan lave udhældninger, drikke urter og gå ture —',
  'hvis et menneske sover fire timer hver nat, lever i konstant',
  'bekymring, aldrig glæder sig og ikke taler med nogen, vil det',
  'forblive sygt. **Behandlingen behandler kroppen. Ordenen behandler',
  'det liv, der gør den syg.**',
  '',
  'Kneipp mente noget helt konkret: en regelmæssig dag med faste',
  'tider for arbejde, mad og søvn; nok søvn, og den om natten; måde i',
  'alting, også i det gode; arbejde, men ikke uden ende; glæde,',
  'fællesskab, en ren samvittighed. Som præst talte han naturligvis',
  'også om sjælen og om Gud. Man behøver ikke dele den del for at se,',
  'hvad han vil hen til: **Et menneske, der er indre splittet, bliver',
  'ikke rask udadtil.**',
  '',
  '**Den moderne modpart er den yngste og måske den mest',
  'forbløffende.** Kronobiologien har vist, at næsten hver celle i',
  'kroppen har et indre ur, og at dets forstyrrelse —',
  'skifteholdsarbejde, konstant søvnmangel, lys om natten — forandrer',
  'blodtryk, sukkerstofskifte og immunforsvar; for opklaringen af',
  'dette ur var der i 2017 Nobelprisen i medicin. Stressforskningen',
  'har målt sammenhængen mellem vedvarende belastning og',
  'hjertesygdomme. Og en stor gennemgang fra 2010 kom til det',
  'resultat, at mennesker med bæredygtige sociale relationer lever',
  'markant længere — en effekt i samme størrelsesorden som at holde',
  'op med at ryge.',
  '',
  '**Præsten fra Wörishofen havde ingen undersøgelse for „orden". Han',
  'havde kun indtrykket af, at mennesker bliver syge, når deres liv',
  'ikke stemmer. Forskningen har brugt hundrede år på at give ham ret',
  'i dette punkt.**',
  '',
  '## Bogen, der gjorde en landsby til en by',
  '',
  '**1886 udkommer „Meine Wasserkur" hos Kösel i Kempten.** Det er',
  'ikke et lærd værk, men en brugsanvisning: behandlinger, urter,',
  'sygdomsbilleder, i et sprog, som enhver bonde forstår. Netop',
  'derfor bliver den en bestseller — talrige oplag i hans levetid,',
  'oversættelser til mange sprog. **1889 følger „So sollt ihr leben"**,',
  'hvor ordenen og livsførelsen rykker i forgrunden.',
  '',
  'Og så sker der noget, ingen har planlagt. **Menneskene kommer.**',
  'Først dusinvis, så hundreder, så tusinder. En landsby med få',
  'hundreder indbyggere skal huse titusinder af gæster om året; de',
  'præcise tal går fra hinanden i kilderne, størrelsesordenen ikke.',
  'Der opstår gæstgiverier, badehuse, en jernbaneforbindelse. Adelige',
  'står i køen ved siden af bønder, fordi Kneipp behandlede begge',
  'uden forskel.',
  '',
  'Han selv holder foredrag, ofte flere gange om dagen, i kurhuset, i',
  'kirken, i det fri. **Fra 1890 arbejder dr. Alfred Baumgarten, en',
  'autoriseret læge, som kurlæge i byen** — på Kneipps eget ønske, og',
  'dette punkt er vigtigt nok til et eget afsnit længere nede. **1893',
  'udnævner pave Leo XIII. præsten til pavelig hemmelig kammerherre;',
  '1894 modtages han i Rom.** 1896 opstår Kneippianum i Wörishofen.',
  '',
  '**Den 17. juni 1897 dør Sebastian Kneipp i Wörishofen, seks uger',
  'efter sin seksoghalvfjerdsårs fødselsdag.** Han efterlader ingen',
  'formue; indtægterne fra bøgerne gik til stiftelser og huse. **1920',
  'må byen kalde sig Bad Wörishofen.**',
  '',
  'Der er blevet mere tilbage, end en landsbypræst kunne vente: flere',
  'dusin anerkendte Kneipp-kurbade i Tyskland, Kneipp-foreninger i',
  'flere lande, vandtrædningsbassiner i næsten enhver tysk kurpark,',
  'Kneipp-børnehaver — og **2021 optagelsen af kneippen på UNESCOs',
  'repræsentative liste over menneskehedens immaterielle kulturarv.**',
  '',
  '## Hånen fra den anden bred',
  '',
  'Og hele tiden blev der grinet.',
  '',
  '„Vandpræst" var ingen ærestitel, da ordet opstod; det var hån.',
  'Kneipp var en væversøn uden lægeuddannelse, der behandlede syge —',
  'for den fremadstormende akademiske medicin i det sene 19.',
  'århundrede var det en uforskammethed. Der var hån i fagblade og i',
  'pressen, der var anmeldelser for ulovlig helbredelsesvirksomhed,',
  'der var lægeforsamlinger, der vendte sig mod „kvaksalveriet".',
  '',
  'Retligt stod han alligevel ikke dårligt, og det har noget at gøre',
  'med det næstsidste kapitel i denne bog: **Næringsloven i Det',
  'Nordtyske Forbund fra 1869, gældende i hele Det Tyske Rige fra',
  '1871, bragte den såkaldte helbredelsesfrihed.** Helbrede måtte',
  'alle; kun „læge" måtte kalde sig den, der var autoriseret. Det er',
  'den juridiske grund til, at der fandtes en Kneipp — og til, at der',
  'den dag i dag findes naturlæger i Tyskland.',
  '',
  '(For fuldstændighedens skyld, fordi denne bog ikke udelader noget:',
  '**Helbredelsesfriheden endte i 1939 med naturlægeloven** i',
  'nazistaten, som første gang regulerede erhvervet og samtidig',
  'skulle afvikle det. At naturlægens erhverv har sin nuværende',
  'retsform fra en lov fra denne tid, er en ubehagelig kendsgerning',
  'for min side. Den hører til her, selv om den ikke behager nogen.)',
  '',
  'Men nu retfærdigheden, som denne bog kræver, og jeg mener den',
  'alvorligt: **Lægerne havde grunde.** Man skal se på, hvor',
  'medicinen stod omkring 1890. Den havde netop — i kapitel 9 til 12',
  'i denne bog — vundet narkosen, antisepsis, kimteorien og',
  'røntgenstrålerne. For første gang i historien kunne en læge sige,',
  '**hvorfor** en behandling virker. Og præcis i det øjeblik trak en',
  'præst fra Allgäu titusinder til sig, uden at kende et eneste af',
  'disse procedurer.',
  '',
  'Set fra deres side var det farligt: En mand uden uddannelse',
  'stiller diagnoser. Mennesker med blindtarmsbetændelse kunne i',
  'stedet for at gå til kirurgen gå i vandbassinet. **Denne',
  'indvending var ikke standshovmod, den var berettiget** — og den er',
  'det den dag i dag.',
  '',
  'Det, der tog hårdheden fra den, var Kneipps egen holdning: Han',
  'søgte ikke lægerne som modstandere. Han hentede dr. Baumgarten til',
  'byen, arbejdede sammen med ham, lod syge undersøge og sendte',
  'videre, hvad der ikke hørte til i hans hænder. **Vandpræsten søgte',
  'ikke striden. Han fik den.**',
  '',
  '## Hvad Kneipp aldrig selv har påstået',
  '',
  'Fordi han i dag tages i brug for alt muligt, her fire ting, som han',
  '**ikke** har sagt:',
  '',
  '**Han var ingen mirakelhelbreder.** Han har ikke lovet helbredelse',
  'og ikke solgt hemmelige midler. Hans behandlinger stod i en bog,',
  'som enhver kunne købe for lidt penge — den tænkeligt dårligste',
  'forretningsidé for en kvaksalver.',
  '',
  '**Han var ikke skolemedicinens fjende.** Han henviste ved alvorlige',
  'sygdomme til læger, samarbejdede med en kurlæge og bestred aldrig',
  'kirurgien. Den, der i dag påkalder ham som kronvidne imod',
  'medicinen, bruger en mand, der ikke længere kan forsvare sig.',
  '',
  '**Han holdt ikke det kolde vand for et universalmiddel.** Det er én',
  'af fem søjler, og han selv stillede ordenen højere.',
  '',
  '**Og han har aldrig påstået at have bevist det.** Han var præst,',
  'ikke forsker. Han har iagttaget, afprøvet, rettet og skrevet ned, i',
  'over fyrre år og på meget mange mennesker. Det er en hæderlig måde',
  'at komme til viden på. **Den er bare ikke det samme som et bevis,',
  'og vi bør holde op med at lade, som om den var det.**',
  '',
  '## Det grumsede vand: hvad min side må bebrejde sig',
  '',
  'Og dermed til listen, der ikke står i nogen Kneipp-brochure.',
  'TONE-reglen i denne bog kræver, at hver side selv nævner sine',
  'ubehagelige pletter — her er mine.',
  '',
  '**For det første: den manglende evidens.** For de enkelte',
  'procedurer — udhældninger, omslag, vandtrædning, dampbade — er',
  'evidensgrundlaget tyndt: små antal tilfælde, sjældent',
  'sammenligningsgrupper, så godt som aldrig blinding. Der findes',
  'antydninger, der findes erfaring, der findes tilfredse patienter.',
  '**Et belastende virkningsbevis i nutidig forstand findes der ikke',
  'for de fleste behandlinger.** Man kan strides om, hvorvidt en',
  'livsstil overhovedet lader sig prøve sådan — men det er et',
  'argument om metoden, ingen erstatning for resultatet.',
  '',
  '**For det andet: mirakelmidlernes løftegivere.** I kanten af min',
  'side står folk, der gør præcis det, Kneipp aldrig gjorde: lover',
  'helbredelse. Afgiftningskure mod alt, mirakeldråber, „rensning" af',
  'blodet, apparater med opfundet fysik. **Der findes kvaksalveri i',
  'naturmedicinen, og det er farligt.** Det er farligt for de syge,',
  'der bruger deres penge på det, og det er farligt for alle seriøse',
  'behandlere, der bagefter kastes i samme gryde. Vi har distanceret',
  'os for sjældent og for stille fra det.',
  '',
  '**For det tredje: den tabte tid.** Det er den tungeste anklage, og',
  'den rammer. Et menneske med brystsmerter, med blod i afføringen,',
  'med en voksende knude, med en høj feber, der ikke vil væk, hører',
  'ikke hjemme i vandtrædningsbassinet. Det hører straks til lægen.',
  '**Der findes dokumenterede tilfælde, hvor mennesker med',
  'helbredelige sygdomme så længe blev behandlet „naturmedicinsk", at',
  'helbredelsen ikke længere var mulig.** Mine midlers mildhed er',
  'ingen tilladelse til at vente. **Hvor tiden afgør liv, hører min',
  'kompetence op** — og den, der ser anderledes på det, skader',
  'naturmedicinen mere end enhver kritiker.',
  '',
  '**For det fjerde: af idéen blev der en forretning.** Denne bog',
  'iagttager en cyklus: **Det nye skader ofte først, før det bliver',
  'velgørende** — kirurgien dræbte gennem sårfeber, før den reddede,',
  'strålerne dræbte deres pionerer, penicillinen skabte resistensen.',
  '**Ved naturmedicinen forløber cyklussen anderledes**, og jeg vil',
  'ikke skønmaler den, men beskrive den rigtigt: Den var ikke først',
  'skadelig og så velgørende; den var mild fra begyndelsen. Dens',
  'skade kom fra to andre sider. Først fra hårdheden hos de tidlige',
  'vandlæger, der overanstrengte de syge. Og så fra det, at en ting,',
  'der intet koster, bliver uimodståelig, så snart man kan tjene',
  'penge på den.',
  '',
  'Allerede i 1891 opstod der i Würzburg en virksomhed, der måtte',
  'bruge Kneipps navn til sine produkter. Deraf er blevet et mærke,',
  'der i dag sælger badeadditiver og cremer. Af kuren er mange steder',
  'blevet wellness: velværepakke, påhældningsceremoni, kurafgift. **Jeg',
  'siger ikke, at det er uærligt — mennesker må bruge penge på deres',
  'velbefindende.** Jeg siger, at der går noget tabt: **Kneipps',
  'helbredelseslære var tænkt til de fattige. Når den koster to',
  'hundred euro per nat, er den ikke længere hans.**',
  '',
  '**For det femte: helhedens bekvemmelighed.** „Jeg behandler hele',
  'mennesket" lyder godt og kan være en undskyldning — for ikke at se',
  'grundigt efter, ikke at stille en diagnose, at lægge enhver',
  'mislykket behandling på patientens livsførelse. **Den, der kan',
  'forklare alt, forklarer intet.**',
  '',
  '## Hvad regnen har med dit liv at gøre',
  '',
  'Og nu det sted, hvor dette kapitel træder ud af historien.',
  '',
  'Tag Kneipps fem søjler og streg vandet og urterne. Det, der bliver',
  'tilbage, er tre ting: **Bevægelse. Ernæring. Orden — altså søvn,',
  'mådehold, lidt bekymring og mennesker omkring sig.**',
  '',
  'Det er, næsten ordret, det svar, den moderne forebyggende medicin',
  'i dag giver på de hyppigste sygdomme i vores tid.',
  'Verdenssundhedsorganisationen skønner, at en meget stor del af de',
  'kroniske sygdomme — størrelsesordenen angives som regel til',
  'halvfjerds til firs procent — hænger sammen med livsstilen. Det',
  'britiske DiRECT-studie viste i 2018, at hos en betragtelig del af',
  'patienterne forsvandt en type 2-diabetes igen gennem vægttab —',
  'efter et år hos næsten halvdelen af deltagerne, helt uden medicin.',
  'Forskningen i særligt længelevende befolkningsgrupper finder igen',
  'og igen de samme ingredienser: meget bevægelse i hverdagen, enkel',
  'plantevejet kost, stærke sociale bånd, lidt jag.',
  '',
  '**Til alt det behøves ingen raketvidenskab.** Det behøves et',
  'menneske, der går i stedet for at køre, der laver mad i stedet for',
  'at rive op, der sover i stedet for at scrolle, og som har en at',
  'tale med. Og det er muligt, at man dermed kunne vinde mere sundhed',
  'end med de nyeste præparater.',
  '',
  'Men jeg ville være en dårlig stemme, hvis jeg holdt op her, for nu',
  'kommer indvendingen, og den er stærk:',
  '',
  '**Det er let sagt.** Den, der arbejder i skifteholdsarbejde, kan',
  'ikke indrette sin dag. Den, der har to jobs, laver ikke frisk mad.',
  'Den, der har få penge, køber den billige mad, og den billige mad',
  'er den forarbejdede. Den, der er alene, kan ikke ordinere sig et',
  'fællesskab. Og imod en fødevareindustri, der bruger milliarder på,',
  'at mennesker spiser mere, hjælper ingen god beslutning.',
  '**„Selvansvar" kan være et befriende ord — og et værktøj til at',
  'give syge skylden for deres sygdom. Man må holde begge dele',
  'adskilt.**',
  '',
  'Dertil kommer det ubehagelige spørgsmål om pengene, som kapitlet',
  'om lægemiddelindustrien har stillet: På en pille tjener nogen. På',
  'en spadsertur tjener ingen. **Et råd, der ikke har noget marked,',
  'har ingen lobby** — og det forklarer måske bedre end noget',
  'standshovmod, hvorfor det enkle så sjældent udskrives. Denne tanke',
  'er så stor, at den får sit eget kapitel: **Kapitel 18 i denne bog,',
  '„Den simple medicin".**',
  '',
  '## Hvor jeg munder ud i den anden stemme',
  '',
  'Jeg har her sagt alt, hvad jeg kan sige for min side, og jeg har',
  'forsøgt ikke at fortie noget, der taler imod den.',
  '',
  '**Dette kapitels anden stemme tilhører skolemedicinen.** Den vil',
  'fortælle den samme historie fra måleglasset, og den har gode',
  'grunde til det. Den vil sige: **Vis mig undersøgelsen.** Den vil',
  'lægge det tynde evidensgrundlag for de enkelte behandlinger frem,',
  'den vil minde om, hvor mange mennesker der er døde af sygdomme,',
  'som man ikke helbreder ved at vente, og den vil forsvare den',
  'grænse, bag hvilken en diagnose ikke længere må være en',
  'fornemmelse.',
  '',
  'Og den vil — hvis den er så ærlig som stemmerne i kapitlerne før —',
  '**også åbne sine egne mørke pletter**: at den har hånet en præst i',
  'stedet for at prøve ham; at den i årtier holdt livsstilen for et',
  'emne for kurbrochuren og ikke for medicin; og at den i dag',
  'skriver bevægelse, ernæring og stressreduktion ind i sine',
  'retningslinjer uden at nævne navnet på den, der begyndte med det.',
  '',
  'Jeg er kun vand. Jeg afgør intet. Jeg falder som regn, samler mig',
  'i en kilde, løber gennem et kar i Wörishofen og fordamper igen.',
  'Det spørgsmål, der bliver tilbage, må I afgøre mellem jer:',
  '',
  '**Hvad helbreder mest — pillen eller livsstilen? Og hvem afgør',
  'egentlig, hvad der bliver udskrevet deraf?**',
].join('\n');

/**
 * Stemmen fra måleglasset — skolemedicinen.
 *
 * Skrevet af DeepSeek (Hermes-pass, runde 18). Samme dramaturgi som den
 * første stemme: vandet, men denne gang i laboratoriets måleglas —
 * undersøgt, målt, prøvet for virkestoffer. Denne stemme repræsenterer
 * diagnosen, undersøgelsen, akutmedicinen — og den slår først sin egen
 * mørke fortid over for vandpræsten op (tillægsregel for følsomme emner
 * i CLAUDE.md).
 */
const stimmeAusDemMessglas = [
  '## Måleglasset, hvor der ikke er regn',
  '',
  'Forestil dig vandet fra før igen. Den samme regn, den samme',
  'kilde, det samme kar i Wörishofen. Men nu står vandet ikke',
  'længere i karret — det står i et måleglas, på et laboratoriebord,',
  'mellem pipetter og protokoller.',
  '',
  'Vi er stemmen fra måleglasset: skolemedicinen. Vi er dem, der',
  'undersøger vandet, før vi anbefaler det. Og vi begynder med det,',
  'som vandets stemme har krævet af os — med vores egne mørke',
  'pletter, fordi reglen i denne bog også gælder for os.',
  '',
  '**Vi har hånet vandpræsten i stedet for at prøve ham.** Det står',
  'i begyndelsen, og det bliver stående. Lægestanden har smilet ad',
  'og hånet en mand, der har hjulpet tusinder — og den gjorde det',
  'uden også blot at undersøge hans behandlinger. Man må sige det så',
  'hårdt, som det var: **Hånen var ingen videnskab. Den var',
  'standshovmod i hvid kittel.** Vi har lært af denne fejl — sent,',
  'og uden at indrømme det.',
  '',
  'Og så siger vi, hvad måleglasset viser, når man ærligt ser ind i',
  'det.',
  '',
  '## Hvad der er i vandet — og hvad ikke',
  '',
  'Måleglasset er ubestikkeligt, og det viser først det, som vandets',
  'stemme selv har indrømmet: **I et glas vand er der vand.** H₂O, et',
  'par opløste mineraler, intet, man kunne udskrive som medicin.',
  'Kneipps udhældninger og omslag er ingen lægemidler — de er',
  'stimuli. Kulde på huden, varme bagefter, blodgennemstrømning,',
  'åndedræt, opmærksomhed. Det er reelt, og det er ikke intet. Men',
  'det er noget andet end et stof med påvist virkning.',
  '',
  'Og her begynder vores første ærlige afgrænsning: **De enkelte',
  'vandbehandlinger — vandtrædningen, udhældningerne, omslagene —',
  'har et tyndt evidensgrundlag.** Der findes iagttagelser,',
  'erfaringsberetninger, traditioner. Der findes næsten ingen',
  'kontrollerede undersøgelser, der beviser, at præcis dette kolde',
  'vand på præcis dette sted bedrer præcis denne sygdom. Vandets',
  'stemme har ikke bestridt det — den har sagt det selv. Vi siger',
  'det fra måleglasset: **Det, man ikke kan måle, kan man ikke',
  'bevise. Og det, man ikke kan bevise, må man ikke sælge som',
  'bevist.** Det gælder for Kneipp som for enhver anden.',
  '',
  '## De strømme, vi selv har overset',
  '',
  'Og så måleglassets anden side, som vi synes mindre godt om —',
  'fordi den angår os.',
  '',
  '**Bevægelsen er bevist.** Evidensen er entydig: Regelmæssig',
  'bevægelse sænker risikoen for hjertesygdomme, diabetes, mange',
  'kræftformer, depressioner — stærkere end de fleste enkelte',
  'lægemidler. **Ernæringen er bevist.** Lidt forarbejdet, meget',
  'grønt, måde i stedet for overflod — datagrundlaget for denne ene',
  'anbefaling er så stærkt som for næsten intet lægemiddel.',
  '**Stressreduktionen er bevist.** Kronisk stress gør syg, det er',
  'ikke længere en esoterisk sætning, men endokrinologi. Og søvnen,',
  'og dagens orden, og det sociale miljø: alt bevist, alt i',
  'retningslinjerne.',
  '',
  '**Og hvem sagde det først? En præst i Wörishofen, som vi kaldte',
  'kvaksalver.** Den moderne forebyggende medicin skriver i dag i',
  'sine retningslinjer, hvad Kneipp prædikede — bevægelse, ernæring,',
  'orden, mådehold — og nævner ikke hans navn. Det er ingen',
  'tilfældighed og ingen ond hensigt, det er simpelthen glemsel. Men',
  'det er en glemsel med retning: Vi har overtaget budskabet og',
  'glemt budbringeren. **Måleglasset måler også det — og det tager',
  'sig ikke godt ud for os.**',
  '',
  '## Det vand, vi har kæmpet med',
  '',
  'Og så en historie, der ikke må mangle i dette kapitel, fordi den',
  'viser, hvor tæt de to sider er kommet på hinanden — uden at',
  'mærke det.',
  '',
  'Skolemedicinen i det nittende århundrede har kæmpet med det samme',
  'vand, som Kneipp ordinerede som medicin. Koleraen kom over',
  'vandet. I 1854 opdagede den londonske læge John Snow, at de syge',
  'drak af en enkelt gadepumpe — han lod pumpens håndtag fjerne, og',
  'epidemien endte. Robert Kochs bakteriologi fandt smitstofferne i',
  'vandet, hygiejnebevægelsen byggede kloakering, filtrerede',
  'drikkevandet, bekæmpede tyfus. **Vandet var for os faren. For',
  'Kneipp var det medicinen. Begge havde ret — det var det samme',
  'vand.**',
  '',
  'Og netop her viser det sig, hvor dyb grøften var: Mens vi lærte,',
  'hvad i vandet der gør syg, lærte Kneipp, hvad ved vandet der gør',
  'rask. Den ene side så smitstoffet, den anden så stimulussen. Den',
  'ene byggede filtre, den anden byggede kar. **Begge har forbedret',
  'menneskers sundhed — og begge har ikke forstået hinanden.**',
  'Koleraen er forsvundet i Europa, fordi vi gjorde vandet rent.',
  'Mange menneskers sundhed er blevet bedre, fordi Kneipp sendte dem',
  'i det kolde vand. Det ene er bevist som næsten intet andet i',
  'medicinhistorien. Det andet er bevist — gennem hundrede og',
  'halvtreds års erfaring og gennem den moderne forebyggende medicin,',
  'der i dag siger, hvad han sagde.',
  '',
  '**Måske er det dette kapitels egentlige lære: Skolemedicinen og',
  'naturmedicinen har mødt hinanden ved vandet uden at genkende',
  'hinanden.** Den ene så faren i vandet, den anden kraften. Og',
  'sundheden i dag — som er så meget bedre end dengang — skylder',
  'begge dele.',
  '',
  '## Den sene hjemkomst: livsstilsmedicinen',
  '',
  'Og så udviklingen, der beskæftiger os mest, fordi den angår os:',
  '**Skolemedicinen indhenter langsomt livsstilen — som ny',
  'fagretning, som var den en opfindelse.**',
  '',
  'Der findes efterhånden professorater i forebyggende medicin,',
  'forskningscentre for ernæring, retningslinjer for bevægelse.',
  'Verdenssundhedsorganisationen skønner, at en stor del af de',
  'kroniske sygdomme ville kunne undgås gennem livsstilsfaktorer.',
  '„Lifestyle-medicin" kalder et nyt felt sig — som om ingen før',
  'havde tænkt på det. **Og hvem tænkte først på det? Præsten fra',
  'Wörishofen.**',
  '',
  'Det er ingen nostalgi og ingen bitterhed. Det er en balance: Vi',
  'har skrevet livsstilen ind i retningslinjerne uden at overtage den',
  'tænkemåde, der hører til. En retningslinje siger, hvad der skal',
  'gøres. Den siger ikke, hvordan man ledsager et menneske i at gøre',
  'det. Kneipp gjorde begge dele — han sagde ikke kun til mennesket,',
  'hvad det skulle gøre, han gjorde det med det, dag for dag, i et',
  'fællesskab, med et mål. **Det er den del af Kneipp-medicinen, vi',
  'endnu ikke har overtaget: ikke anbefalingen, men ledsagelsen.**',
  '',
  '## Den grænse, vi forsvarer',
  '',
  'Og så den grænse, bag hvilken vi ikke giver efter, fordi det',
  'handler om liv.',
  '',
  'Vandets stemme har selv nævnt den: blindtarmsbetændelsen, der',
  'ikke helbredes med en udhældning; lungebetændelsen, der behøver',
  'tid og antibiotika; hjerteinfarktet, der ikke længere venter på en',
  'ordensterapi. **Der findes sygdomme, hvor det at vente dræber —',
  'og hvor diagnosen ikke må være en følelsessag.** Vi har allerede i',
  'denne bog fortalt, hvad der sker, når mennesker kommer for sent',
  'til lægen: Kapitel 9 viste kirurgien, kapitel 10 vaccinationen,',
  'kapitel 15 pandemien. Medicinen har sine mørke sider — men den',
  'har også reddet det ene, som naturmedicinen ikke kan: den akutte',
  'redning.',
  '',
  'Og derfor forsvarer vi diagnosen. Ikke den hvide kittel, ikke',
  'recepten, ikke systemet — diagnosen. **Den, der kan sige, hvad et',
  'menneske har, kan afgøre, hvad det behøver. Den, der kun føler',
  'det, kan ikke.** Kneipp selv vidste det: Han henviste ved',
  'alvorlige sygdomme til læger, han samarbejdede med dr. Baumgarten.',
  'Vandpræsten var klogere end mange af sine beundrere.',
  '',
  '## Hvad vi tilstår ham',
  '',
  'Og nu det, denne stemme skylder præsten — ikke af høflighed, men',
  'fordi det er bevist.',
  '',
  '**Kneipp var ingen kvaksalver.** Han har ikke lovet helbredelse,',
  'ikke solgt hemmelige midler, ikke krævet penge. Hans bog var til',
  'at betale for enhver — den dårligste forretningsidé for en',
  'bedrager. Han har samarbejdet med læger og sendt syge videre.',
  '**Han var ærligere end mange, der i dag bærer hans navn.**',
  '',
  '**Han havde ret i det, der tæller.** Livsstilen — bevægelse,',
  'ernæring, orden, mådehold, miljø — er den største medicin, der',
  'findes. Den moderne forskning har bekræftet det, punkt for punkt.',
  'Den, der benægter det i dag, benægter datagrundlaget. **Kneipp',
  'sagde for hundrede og halvtreds år siden, hvad vi i dag skriver',
  'ind i retningslinjerne — og vi hånede ham for det.** Det er ingen',
  'biting. Det er kernen.',
  '',
  'Og vi tilstår ham det, der vejer tungere end enhver undersøgelse:',
  'omsorgen. De mennesker, der kom til Wörishofen, blev taget',
  'alvorligt, fik tid, blev anvist at gøre noget for sig selv. **Vi',
  'har lært, at denne omsorg er et virkestof — placeboforskningen',
  'har bevist det. Kneipp doserede den, mens vi endnu holdt den for',
  'indbildning.**',
  '',
  '## Hvad vi må bebrejde os selv',
  '',
  'TONE-reglen gælder dobbelt, og derfor slutter denne stemme med',
  'den liste, der ikke smigrer os.',
  '',
  '**For det første: Vi har hånet i stedet for at prøve.**',
  'Vandpræsten, homøopatien, naturmedicinen overhovedet. Den, der',
  'kender sin egen fortid, bør være forsigtig med tonen.',
  '',
  '**For det andet: Vi har i årtier holdt livsstilen for et emne for',
  'kurbrochuren** — mens de kroniske sygdomme, som vi ikke kan',
  'helbrede, netop opstår af livsstilen. Kapitel 14 i denne bog har',
  'trukket balancen: stærk i diagnosen, svag ved de kroniske',
  'sygdomme. Naturmedicinen har aldrig undervurderet de kroniske',
  'sygdomme — den har beskæftiget sig med dem, mens vi endnu kun',
  'forvaltede dem.',
  '',
  '**For det tredje: Vi udskriver pillen lettere end rådet.** En',
  'recept tager to minutter. En samtale om bevægelse og ernæring',
  'tager tyve — og bliver ikke betalt. Systemet belønner pillen og',
  'straffer rådet. **Det er ikke lægernes skyld, det er skylden hos',
  'dem, der har bygget systemet. Men det er vores regning.**',
  '',
  '**For det fjerde: Vi har overtaget budskabet og glemt',
  'budbringeren.** Retningslinjerne siger i dag, hvad Kneipp sagde —',
  'og hans navn mangler. Det er ingen videnskabens triumf. Det er en',
  'forsinket undskyldning uden brev.',
  '',
  '## Måleglasset og regnen',
  '',
  'Og så det spørgsmål, som dette kapitel lader stå åbent, fordi det',
  'angår begge stemmer: **Hvad helbreder mest — pillen eller',
  'livsstilen?**',
  '',
  'Vores svar fra måleglasset er ærligere, end nogle kolleger gerne',
  'hører: **Livsstilen helbreder mest.** De største sundhedsgevinster',
  'i de sidste hundrede og halvtreds år kom ikke fra lægemidlerne,',
  'men fra vand, sæbe, ernæring, arbejdsbeskyttelse, bevægelse — fra',
  'livsstilen. Pillen er til den akutte situation, livsstilen til hele',
  'livet. **Den, der stiller de to op imod hinanden, stiller det',
  'forkerte spørgsmål. Men den, der udskriver livsstilen, behøver',
  'tid — og den får ingen betalt.**',
  '',
  'Og derfor er det andet spørgsmål det egentlige: **Hvem afgør, hvad',
  'der bliver udskrevet?** Ikke lægen alene, ikke patienten alene.',
  'Det afgør et system, der betaler pillen og ikke samtalen. Det',
  'næste kapitel i denne bog vil tage dette spørgsmål op — og det',
  'vil besvare det, som det sig hør og bør: med den simple medicin.',
  '',
  'Måleglasset står på bordet. Regnen falder videre. Begge hører',
  'sammen.',
].join('\n');

const kneipp = {
  id: 'kneipp',
  titel: 'Kneipp og naturmedicinen',
  epoche: 'Det 19. århundrede',

  aufhaenger: {
    frage:
      'Kan en præst med koldt vand helbrede, hvad lægerne ikke kan ' +
      'helbrede — eller helbreder livsstilen til syvende og sidst?',
    text: [
      'I vinteren 1849 stiger en ung mand ved Dillingen an der Donau ned i',
      'den isnende kolde flod. Han hedder Sebastian Kneipp, er',
      'otteogtyve år gammel, søn af en væver, indhenter med besvær',
      'gymnasiet — og han er svært syg. Hvad han præcis fejler, ved ingen',
      'sikkert den dag i dag; overleveret er en tærende lungelidelse. I et',
      'gammelt skrift af lægen Johann Siegmund Hahn fra 1738 har han læst',
      'om det kolde vands kraft. Så afprøver han det på sig selv: kort',
      'dykke ned, så i løbetempo hjem, indtil han bliver varm.',
      '',
      'Han bliver otteoghalvfjerds år gammel. I 1855 kommer han som',
      'skriftefader for dominikanerinderne til landsbyen Wörishofen og',
      'begynder at behandle syge — med udhældninger, omslag, vandtrædning,',
      'urter, bevægelse og en regelmæssig dag. Senere vil man kalde det de',
      'fem søjler: vand, bevægelse, ernæring, lægeurter, orden.',
      '',
      'I 1886 udkommer hans bog „Meine Wasserkur". Derefter kommer',
      'menneskene i flok — fra hele Europa, titusinder om året, bønder ved',
      'siden af adelige. Lægestanden kalder ham kvaksalver og',
      '„vandpræst", og begge dele er ment som hån.',
      '',
      'Hundrede og halvtreds år senere står der i skolemedicinens',
      'retningslinjer, hvad præsten dengang prædikede: Bevæg dig. Spis',
      'enkelt. Sov nok. Byg stress af. Hans navn står ikke der. Dette',
      'kapitel fortæller begge sider fair — og stiller det spørgsmål, det',
      'egentlig handler om: Hvad helbreder mest, pillen eller livsstilen?',
    ].join('\n'),
  },

  // Kortet ligger i karten/kneipp.js — her er kun fasehenvisningerne
  // oversat (phasen → karteHinweise), ikke selve kortet.
  karteHinweise: [
    {
      label: '1821–1844: Stefansried og Allgäu — væversønnen',
      hinweis:
        'Den 17. maj 1821 bliver Sebastian Kneipp født i Stefansried, en ' +
        'landsby af få gårde ved Ottobeuren i det bayerske Allgäu. Faderen ' +
        'er væver, huset er lille, pengene rækker ikke. Drengen passer ' +
        'kvæg og sidder tidligt selv ved væven. Hans ønske om at blive ' +
        'præst synes udsigtsløst: Til latinskolen mangler der penge og ' +
        'foruddannelse. I Grönenbach giver kapellanen Matthias Merkle ham ' +
        'undervisning i latin og åbner dermed døren for ham — i 1844 ' +
        'bliver den treogtyveårige optaget på gymnasiet i Dillingen.',
    },
    {
      label: '1844–1849: Dillingen an der Donau — sygdommen og det kolde vand',
      hinweis:
        'I Dillingen indhenter den sene elev gymnasiet og studerer ' +
        'bagefter på byens lyceum. I disse år bliver han svært syg; ' +
        'overleveret er en tærende lungelidelse, den præcise diagnose er ' +
        'historisk ikke sikret. I 1849 falder han over et gammelt skrift ' +
        'af den schlesiske læge Johann Siegmund Hahn om det friske vands ' +
        'kraft og virkning, trykt i 1738. Han begynder om vinteren flere ' +
        'gange om ugen at dykke ned i den isnende Donau i nogle øjeblikke ' +
        'og bagefter at løbe til fods tilbage, indtil han bliver varm. ' +
        'Efter egen fremstilling styrker det ham; han kan fortsætte sit ' +
        'studium.',
    },
    {
      label: '1850–1855: München, Augsburg, Boos — vejen til præsteembedet',
      hinweis:
        'I 1850 tager Kneipp til München for at afslutte teologistudiet; ' +
        'den 6. august 1852 bliver han viet til præst i Augsburg. ' +
        'Derefter følger kapellanår i Biberbach og i Boos i Illerdalen ' +
        'samt en kort tid i Augsburg. I Boos plejer han i 1854 under en ' +
        'kolera-bølge syge og bruger også vandbehandlinger — øgenavnet ' +
        '„kolera-kaplanen" stammer fra denne tid. I maj 1855 bliver han ' +
        'som skriftefader for dominikanerinderne forflyttet til landsbyen ' +
        'Wörishofen.',
    },
    {
      label: '1855–1886: Wörishofen — præsten og vandkuren',
      hinweis:
        'I Wörishofen bliver Kneipp til sin død. Han passer ' +
        'klosterkvinderne, forvalter klostergodset, underviser landmænd ' +
        'og behandler ved siden af syge, der beder ham om det — først ' +
        'naboer, så mennesker fra omegnen, til sidst fremmede fra hele ' +
        'Bayern. I 1881 bliver han byens præst. De behandlinger, han ' +
        'udvikler, er mildere end forgængernes hårde vandkure: korte ' +
        'udhældninger, omslag, afvaskninger, vandtrædning, altid ' +
        'efterfulgt af bevægelse og genopvarmning. I 1886 udkommer hos ' +
        'Kösel i Kempten hans bog „Meine Wasserkur".',
    },
    {
      label: '1886–1897: tilstrømningen — fra landsby til kurbad',
      hinweis:
        '„Meine Wasserkur" bliver en bestseller og oversat til talrige ' +
        'sprog; i 1889 følger „So sollt ihr leben". Derefter kommer de ' +
        'syge i flok: I topårene i 1890erne tæller Wörishofen titusinder ' +
        'af gæster om året — de præcise tal går fra hinanden i kilderne. ' +
        'Fra 1890 arbejder en autoriseret kurlæge, dr. Alfred Baumgarten, ' +
        'i byen. I 1893 udnævner pave Leo XIII. præsten til pavelig ' +
        'hemmelig kammerherre; i 1894 modtages Kneipp i Rom. I 1896 ' +
        'opstår Kneippianum. Den 17. juni 1897 dør Kneipp i Wörishofen; ' +
        'i 1920 må byen kalde sig „Bad Wörishofen".',
    },
  ],

  perspektiven: [
    {
      id: 'naturheilkunde',
      name: 'Vandets stemme',
      stimme: 'Opus',
      text: stimmeDesWassers,
    },
    {
      id: 'schulmedizin',
      name: 'Stemmen fra måleglasset',
      stimme: 'DeepSeek',
      text: stimmeAusDemMessglas,
    },
  ],

  synthese: [
    '## Hvor de to sider mødes',
    '',
    'Lægger man dette kapitels to stemmer ved siden af hinanden, falder',
    'det først i øjnene, hvor lidt de egentlig strides — og hvor meget',
    'de deler.',
    '',
    '**De deler afskyen for den heroiske medicin.** Naturmedicinen',
    'opstod som protest mod åreladning og kviksølv — og skolemedicinen i',
    'dette kapitel har ikke blot indrømmet, at protesten var berettiget,',
    'den har selv nævnt sine egne mørke årtier. Det har i denne bog',
    'allerede homøopatien og kirurgien gjort: Den brutale medicin er en',
    'gru for begge sider.',
    '',
    '**De deler erkendelsen af, at livsstilen er den største medicin.**',
    'Skolemedicinen har i dette kapitel selv sagt det: bevægelse,',
    'ernæring, orden, mådehold, miljø — bevist, i retningslinjerne,',
    'ubestridt. Kneipp prædikede det for hundrede og halvtreds år siden,',
    'forskningen har bekræftet det. **Her strides de to sider ikke. Her',
    'er de enige — og det er det bemærkelsesværdige ved dette kapitel.**',
    '',
    '**De deler ærligheden.** Vandets stemme har selv nævnt det tynde',
    'evidensgrundlag for de enkelte behandlinger og faren ved at vente.',
    'Stemmen fra måleglasset har selv nævnt hånen og arrogansen og den',
    'forsinkede respekt. To sider, der viser deres sår — det er',
    'sjældent, og det er det, der bærer dette kapitel.',
    '',
    '## Hvor de går fra hinanden',
    '',
    'Og så forskellen, der bliver.',
    '',
    '**De går fra hinanden ved spørgsmålet om, hvad der gælder som',
    'bevis.** Den ene side siger: Millioner af menneskers erfaring',
    'tæller. Den anden siger: Vis mig undersøgelsen. Begge har ret — og',
    'begge ved det. Vandbehandlingerne i enkeltheder er næppe bevist;',
    'livsstilen som helhed er det over enhver tvivl. **Den, der kaster',
    'begge dele i samme gryde, gør det for let for sig selv — i begge',
    'retninger.**',
    '',
    '**De går fra hinanden ved diagnosens grænse.** Skolemedicinen',
    'forsvarer den, fordi det at vente dræber. Naturmedicinen',
    'respekterer den — Kneipp henviste til læger. Striden begynder først',
    'der, hvor skolemedicinen gør diagnosen til en mur og efterlader',
    'livsstilen bag den: i venteværelset, hvor der ikke er tid til',
    'samtalen.',
    '',
    '## Hvad dette kapitel betyder for bogen',
    '',
    'Tænkemåden bestemmer metoden — og dette kapitel viser det omvendte:',
    '**Naturmedicinens metode var livsstilen, og skolemedicinen har',
    'overtaget den uden at overtage tænkemåden.** Retningslinjerne',
    'anbefaler bevægelse og ernæring, men systemet udskriver pillen,',
    'fordi pillen koster to minutter og rådet tyve. Kneipp har ikke kun',
    'efterladt anbefalingerne — han har efterladt en tænkemåde, hvor',
    'mennesket er medansvarlig for sin sundhed. Denne tænkemåde mangler',
    'i retningslinjerne. Den står kun mellem linjerne.',
    '',
    'Og så er der den bue, som denne bog selv har slået: Fra Hahnemann',
    '(kapitel 16), der forstod medicinen som information, til Kneipp,',
    'der forstod medicinen som livsstil — naturmedicinen har udfordret',
    'skolemedicinen to gange, og begge gange har skolemedicinen til sidst',
    'overtaget det, den først hånede. **Det er ingen tilfældighed. Det',
    'er et mønster — og det næste kapitel vil nævne det.**',
    '',
    '## Broen til det næste kapitel',
    '',
    'Dette kapitel har rejst det spørgsmål, som det næste vil besvare:',
    '**Hvorfor er den største medicin — livsstilen — den mindst',
    'udskrevne?** Kneipp har undervist i svaret for hundrede og halvtreds',
    'år siden, forskningen har bekræftet det, og systemet udskriver det',
    'alligevel ikke.',
    '',
    '**Kapitel 18 i denne bog, „Den simple medicin", stiller',
    'forfatterens tese imod det:** Kroniske sygdomme er',
    'livsstilsspørgsmål — bevægelse, sund kost, socialt miljø, lidt',
    'stress. Ingen raketvidenskab. Mere sundhed gennem livsstil end',
    'gennem kemi. Dette kapitel har vist, at denne tese har en to',
    'hundrede år gammel tradition: fra vandpræsten til retningslinjerne.',
    'Det næste kapitel spørger, hvorfor den alligevel så sjældent',
    'udskrives — og hvad der skulle ændres, for at den simple medicin',
    'blev den selvfølgelige.',
  ].join('\n'),

  urteil: {
    frage:
      'Hvad helbreder mest — pillen eller livsstilen? Og hvorfor ' +
      'udskriver medicinen det ene så let og det andet så svært?',
    hinweis: [
      'Der er her ikke noget rigtigt og forkert. Hold de to sider ved siden',
      'af hinanden. Den ene: bevægelse, enkel mad, søvn og mennesker omkring',
      'sig koster næsten intet, har næsten ingen bivirkninger og hænger',
      'efterviseligt sammen med vores tids hyppigste sygdomme. Den anden:',
      'Et råd er ingen behandling, et omslag er ingen antibiotika, og den,',
      'der ved alvorlige gener satser på livsstilen, taber tid, som ingen',
      'henter tilbage. Spørg dig selv om tre ting. For det første: Hvad af',
      'de fem søjler — vand, bevægelse, ernæring, lægeurter, orden — gør du',
      'selv, og hvad hindrer dig i resten? For det andet: Når en læge har',
      'ti minutter til dig — hvad kan han realistisk give dig med i den tid,',
      'en recept eller en livsændring? For det tredje: Hvem har gavn af, at',
      'det enkle så sjældent ordineres — og hvem skader det?',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Hvor og hvornår blev Sebastian Kneipp født, og hvad var hans ' +
        'far af erhverv?',
      antworten: [
        '1821 i Stefansried i Allgäu, som søn af en væver.',
        '1810 i Augsburg, som søn af en læge.',
        '1835 i Wörishofen, som søn af en bonde.',
      ],
      richtig: 0,
      erklaerung:
        'Kneipp kom til verden den 17. maj 1821 i Stefansried, en ' +
        'landsby ved Ottobeuren i det bayerske Allgäu. Hans far var ' +
        'væver, familien meget fattig. Først latinundervisningen hos ' +
        'kapellan Matthias Merkle i Grönenbach gjorde det muligt for ' +
        'ham i 1844 — som treogtyveårig — at blive optaget på gymnasiet ' +
        'i Dillingen an der Donau.',
    },
    {
      frage:
        'Hvad gjorde Kneipp i vinteren 1849, efter at han havde læst ' +
        'Johann Siegmund Hahns vandskrift?',
      antworten: [
        'Han åbnede en badeanstalt i Dillingen.',
        'Han badede flere gange ugentligt kort i den isnende Donau og ' +
          'løb bagefter tilbage, indtil han blev varm.',
        'Han ordinerede kuren først til sine medelever.',
      ],
      richtig: 1,
      erklaerung:
        'Hahns skrift „Unterricht von der Krafft und Würckung des ' +
        'frischen Wassers" var udkommet i 1738. Kneipp, dengang svært ' +
        'syg, afprøvede behandlingen på sig selv. Efter egen ' +
        'fremstilling styrkede den ham. Et bevis i nutidig forstand er ' +
        'denne beretning ikke: Der findes ingen sikret diagnose og ' +
        'ingen sammenligningsgruppe — naturmedicinens stemme siger det ' +
        'i dette kapitel selv.',
    },
    {
      frage: 'Hvilke fem søjler sammenfatter Kneipp-læren?',
      antworten: [
        'Vand, faste, bøn, søvn og massage.',
        'Vand, bevægelse, ernæring, lægeurter og orden.',
        'Vand, luft, lys, jord og varme.',
      ],
      richtig: 1,
      erklaerung:
        'De fem søjler er vand, bevægelse, ernæring, lægeurter og ' +
        'orden — hvor Kneipp holdt ordenen, altså den regelmæssige ' +
        'livsførelse, for den vigtigste. Opdelingen i „fem søjler" ' +
        'stammer dog ikke fra ham selv, men er en senere ordning hos ' +
        'hans efterfølgere, som sammenfatter hans bøger.',
    },
    {
      frage: 'Hvilken bog gjorde Kneipp vidt kendt i 1886?',
      antworten: [
        '„So sollt ihr leben"',
        '„Meine Wasserkur"',
        '„Das Kneippianum"',
      ],
      richtig: 1,
      erklaerung:
        '„Meine Wasserkur" udkom i 1886 hos Kösel i Kempten og blev en ' +
        'bestseller med talrige oplag og oversættelser. I 1889 fulgte ' +
        '„So sollt ihr leben", hvor livsordenen rykkede mere i ' +
        'forgrunden. Derefter kom de syge i flok til Wörishofen; ' +
        'landsbyen blev et kurbad og hedder siden 1920 Bad Wörishofen.',
    },
    {
      frage:
        'Hvordan forholdt Kneipp sig til de autoriserede læger i sin ' +
        'tid?',
      antworten: [
        'Han afviste grundlæggende enhver lægelig behandling.',
        'Han henviste ved alvorlige sygdomme til læger og hentede i ' +
          '1890 med dr. Alfred Baumgarten en kurlæge til Wörishofen.',
        'Han lod sig selv uddanne til læge.',
      ],
      richtig: 1,
      erklaerung:
        'Kneipp var præst, ikke læge, og har aldrig fremstillet det ' +
        'anderledes. Han samarbejdede med kurlægen dr. Alfred ' +
        'Baumgarten, lod syge undersøge og henviste videre, hvad der ' +
        'ikke hørte til i hans hænder. Retligt muligt blev hans ' +
        'virksomhed gennem helbredelsesfriheden i næringsloven af ' +
        '1869/1871: Helbrede måtte alle, kun „læge" måtte kalde sig ' +
        'den, der var autoriseret.',
    },
  ],
};

module.exports = kneipp;
