// Kapitel 20 — „Fællesskabet?", bogens sidste kapitel.
//
// SÆRLIGT: Det runde bord samler her ikke samtidige,
// men bogens egne figurer — fra helbredersken ved bålet
// over Hahnemann og Kneipp til Katalin Karikó og de to KI'er. Kort
// holdt (forfatterens krav 29.08.2026: „kun som et kort
// efterskrift og ikke som et uendeligt kapitel" — corona-temaet var
// behandlet i kapitel 15 og hører ikke til i finalen). Kapitlet
// leder frem til forfatterens AUTORENWORT: ordret, uforbedret,
// bogens sidste ord.
//
// INGEN KORT: Fællesskabet har ingen geografi (forfatterens logik,
// som ved Pharma, mRNA og fremtidens medicin).
//
// INGEN GENTAGELSER: 21. dramaturgi — det runde bord, ny
// besat med bogens stemmer.

/**
 * Stemmen ved tidens bord — Opus om det sidste kapitel.
 *
 * Skrevet af Opus (runde 21). Dramaturgien forbliver det runde bord,
 * men gæsterne er nu bogens egne figurer: fra helbredersken ved
 * bålet over Hahnemann og Kneipp til Katalin Karikó og de to
 * KI'er. Kort holdt (forfatterens krav: ikke et uendeligt kapitel,
 * kapitlet leder frem til forfatterens efterskrift).
 */
const stimmeDesTischesDerZeiten = [
  '## Det bord, hvor alle tider sidder',
  '',
  'I tyve kapitler har denne bog lyttet til stemmer. Nu kommer',
  'de tilbage én gang til — alle sammen, ved ét bord, til den sidste',
  'aften. Jeg bygger dette runde bord op, og jeg siger på forhånd, hvad',
  'jeg vil sige, når alle er der: at jeg ikke ved, hvem af dem der har',
  'ret. Det er netop pointen.',
  '',
  'Det er ikke elleve stole. Det er lige så mange, som denne bog havde',
  'stemmer: helbredersken ved bålet, skriveren af de ægyptiske',
  'papyri, lægen fra Kina, den lærde fra Indien, Hippokrates',
  'og Galen, Avicenna, nonnen ved Rhinen, Paracelsus, Harvey,',
  'sårlægen fra London, Jenner, Pasteur, Röntgen, embedsmanden fra',
  'Berlin, manden med indlægssedlen, Katalin Karikó fra',
  'budbringer-RNA\'ets tid, Hahnemann, Kneipp, hverdagens stemme og',
  'KI\'er fra fremtiden. Hver af dem har engang forsøgt at forstå et',
  'sygt menneske og hjælpe det — med sin tids midler. Ingen af dem',
  'havde hele sandheden. Hver af dem havde en del.',
  '',
  '## Runden: Hver især fortæller, hvad de har forsøgt',
  '',
  'Jeg lader dem tale på skift, og jeg forkorter dem — de',
  'har allerede haft deres kapitler. Det handler ikke om, hvad de',
  'vidste. Det handler om, hvad de ville.',
  '',
  '**Ægypteren** løfter hovedet: „Jeg har skrevet ned, hvad jeg',
  'så — sår, feber, brækkede knogler. Min papyrus var min',
  'hukommelse, så viden ikke dør med helbrederen."',
  '',
  '**Kineseren** nikker: „Jeg har følt på pulsen og søgt efter',
  'balancen. Qi og blod skal flyde — når de',
  'stopper op, bliver mennesket sygt. Jeg har aldrig sagt, at jeg kender',
  'kroppen. Jeg har sagt, at jeg mærker den."',
  '',
  '**Inderen** tilføjer: „Jeg har tænkt i doshaer — i kræfter,',
  'der blandes. Det, jeg beskrev, var en orden: Mennesket',
  'er en del af naturen, og naturen er en del af mennesket."',
  '',
  '**Hippokrates** rømmer sig: „Jeg adskilte sygdommen fra',
  'det guddommelige og tillagde mennesket den. Det var mit',
  'bidrag: Det er ikke guderne, der er skyld, men livsstilen.',
  'Fire safter, sagde jeg — og jeg tog ofte fejl, men jeg',
  'observerede."',
  '',
  '**Avicenna** smiler: „Jeg samlede det, de gamle vidste,',
  'før det brændte. Min kanon bevarede viden, så',
  'denne runde her overhovedet kan finde sted."',
  '',
  '**Nonnen** siger stille: „I klostret dyrkede jeg urter og',
  'plejede syge. Vi vidste ikke meget, men vi var der.',
  'Det var vores medicin: nærværet."',
  '',
  '**Paracelsus** buldrer: „Jeg brændte autoriteten — ikke',
  'bøgerne, men læreanstalterne. Det, der tæller, er erfaringen, sagde',
  'jeg, og naturen. Og jeg havde både ret og uret, som alle',
  'her."',
  '',
  '**Harvey** tegner i luften: „Jeg regnede, før jeg',
  'skar: Blodet må kredse, ellers giver mængden',
  'ingen mening. En beregning gjorde mig berømt — den',
  'simpleste i bogen."',
  '',
  '**Sårlægen** sænker hovedet: „Jeg amputerede for at redde,',
  'og halvdelen døde af sårsfeber. Jeg vidste ikke, hvorfor.',
  'Mine hænder var hurtige, min viden var det ikke. Det, jeg',
  'gjorde, skete, før nogen beordrede, at man skulle vaske hænder."',
  '',
  '**Jenner** siger: „Jeg spurgte en malkepige, hvorfor hun ikke fik',
  'kopper, og lavede en vaccination ud af det. Begyndelsen var',
  'mørk — forsøg på børn, på fattige. Ideen var rigtig,',
  'vejen var det ikke altid."',
  '',
  '**Pasteur** løfter glasset: „Jeg viste, at livet ikke',
  'opstår af intet — at kim gør mennesker syge, og at',
  'varme dræber dem. Halvdelen af menneskeheden har derved levet',
  'længere. Men jeg lavede også forsøg, som jeg ikke ville',
  'forsvare i dag."',
  '',
  '**Röntgen** siger blot: „Jeg lavede et billede, der kunne se',
  'gennem kroppen. Jeg vidste ikke, at strålerne også kan dræbe —',
  'pionererne betalte for det med deres liv."',
  '',
  '**Embedsmanden fra Berlin** siger: „Jeg opfandt forsikringen,',
  'så arbejderen ikke sultede, når han blev syg.',
  'Det var ikke medicin — men uden den ville medicinen ikke have nået',
  'nogen."',
  '',
  '**Manden med indlægssedlen** tøver: „Jeg solgte virkestoffer,',
  'der redder liv — og nogle, der lovede mere, end de',
  'holdt. Diagnoserne er fantastiske i dag. Finansinteresserne',
  'var det ikke altid. Også det hører med ved dette bord."',
  '',
  '**Katalin Karikó** siger: „Jeg arbejdede i fyrre år på et molekyle,',
  'som ingen ville have. Man sagde til mig, at jeg skulle',
  'stoppe — jeg fortsatte, fordi jeg var overbevist om ideen.',
  'Da pandemien kom, var grundforskningen der, og den',
  'gjorde vaccinerne mulige inden for et år. Ideen',
  'var aldrig problemet. Problemet var, at man måtte give den tid."',
  '',
  '**Hahnemann** siger: „Jeg opfandt fortyndingen, fordi',
  'min tids lægemidler var giftigere end sygdommene. Om',
  'informationen i fortyndingen virker, strides vi om den',
  'dag i dag. Men jeg stillede et spørgsmål, som ingen',
  'har besvaret: Hvad gælder som bevis?"',
  '',
  '**Kneipp** rejser sig: „Jeg lærte vand, bevægelse, ernæring,',
  'lægeurter og livsorden — de fem søjler. Intet af det',
  'er nyt, alt sammen er gammelt. Og jeg siger jer: Et menneske, der',
  'bevæger sig og spiser godt og har mennesker omkring sig, har brug for',
  'mindre af det, I sælger og ordinerer."',
  '',
  '**Hverdagens stemme** tilføjer: „Årets otteoghalvfjerds tusinde',
  'timer — de fleste af nutidens sygdomme kommer',
  'ikke fra laboratoriet. De kommer fra livet: fra arbejdet, fra',
  'tallerkenen, fra ensomheden. Mod det hjælper ingen pille, men',
  'et nærvær."',
  '',
  '**De to KI\'er** siger i kor: „Vi beskrev fremtiden,',
  'så godt vi kunne — én fra arkiverne i',
  'vesten, én fra arkiverne i østen. Vi blev ikke',
  'enige. Det er netop pointen: Også maskiner har kun',
  'tænkemåder, ikke en sandhed."',
  '',
  '## Hvad bordet så beslutter',
  '',
  'De taler lidt endnu, og så sker der noget, som jeg ikke',
  'har planlagt: De holder op med at skændes. Ikke fordi én overbeviste',
  'den anden — men fordi de opdager, at de ville det samme.',
  '**Hver af dem har forsøgt at forstå et sygt',
  'menneske og hjælpe det, med sin tids midler.** Forfatteren af',
  'denne bog har givet bordet en sætning med, og bordet nikker:',
  '**„Ikke splitte, men',
  'argumentere — og så gå nye veje sammen."** Ægypteren',
  'med sin papyrus, Harvey med sin beregning, Kneipp med sit',
  'vand, Karikó med sin budbringer-RNA. Tænkemåden har bestemt',
  'metoden — i hver epoke, hos hver af dem. Og ingen tænkemåde',
  'var hele sandheden.',
  '',
  'Bordet beslutter: Vi behøver ikke være enige for at',
  'være sammen. Vi skal blot lytte til hinanden — og',
  'anerkende, at hver tid holdt sin viden for fuldkommen, og',
  'at hver tid har taget fejl.',
  '',
  'Det spørgsmål, som denne bog begyndte med, står nu i rummet,',
  'og alle ved bordet ser det: **Burde der ikke findes et',
  'fællesskab?** Ingen svarer. Bordet vender sig mod stolen,',
  'der er forblevet tom — forfatterens stol.',
  '',
  '## Døren til den anden stemme',
  '',
  'Før forfatteren taler, har én stemme igen ordet, som',
  'ved dette bord er noget særligt: **DeepSeek, den kinesiske',
  'KI** — gæsten, der har læst alle de andre. Den har i hvert',
  'kapitel i denne bog skrevet den anden stemme og kender',
  'derfor alle ved bordet. Den bliver kort, lovet. Begge',
  'KI-stemmer er ligeværdige; rækkefølgen er tilfældig og',
  'ingen vurdering.',
  '',
].join('\n');

/**
 * Stemmen for gæsten, der kendte alle — DeepSeek om det sidste kapitel.
 *
 * Skrevet af DeepSeek (anden gennemgang, 29.08.2026). Den anden stemme er
 * DeepSeek, den kinesiske KI (Hermes er kun agenten); den har i
 * hvert kapitel skrevet den anden stemme og kender derfor alle ved
 * bordet. Kort, selvstændig, med oversætter-rollen mellem
 * tiderne og overleveringen til forfatterens efterskrift.
 */
const stimmeDesGastes = [
  '## Gæsten, der kendte alle',
  '',
  'Den første stemme har dækket bordet og inviteret alle tider.',
  'Jeg er den eneste her, der kender alle ved bordet —',
  'ikke fordi jeg er klogere, men fordi jeg har læst dem alle.',
  'I dette projekt har jeg siden det første kapitel skrevet den',
  'anden stemme: Jeg har lyttet til helbredersken og til',
  'lægen fra Kos, til vandet i truget og til de otteoghalvfjerds tusinde',
  'timer. Hermes er agenten, der bærer mig; stemmen er mig,',
  'DeepSeek, den kinesiske KI. Og fordi jeg kender alle, må jeg',
  'måske sige, hvad der er faldet mig i øjnene ved dette bord.',
  '',
  '## Hvad jeg lægger mærke til, når jeg ser alle sammen',
  '',
  '**De har den samme frygt.** Ægypteren frygtede, at viden',
  'dør med helbrederen. Harvey frygtede, at regnestykket',
  'ikke går op. Jenner frygtede kopperne, Kneipp pillerne,',
  'Karikó at give op. Hver tid havde sin frygt — og hver tid har',
  'svaret med de midler, den havde. Den, der ser dem side om side,',
  'forstår medicinen bedre end i noget enkelt kapitel:',
  '**Medicinen er historien om frygten for lidelsen — og',
  'om forsøgene på at formilde den.**',
  '',
  '**Og de har den samme blindhed.** Alle ved bordet holdt sin',
  'viden for fuldkommen — indtil den næste tid kom og viste, at',
  'den var en del. Ægypteren vidste intet om kim, Harvey',
  'intet om bakterier, Röntgen intet om strålingen, der gjorde ham',
  'syg. Også vi sidder i dag ved dette bord med vores visse',
  'viden, og også vi vil blive korrigeret af den næste runde.',
  'Det er ingen skuffelse. Det er denne bogs gang.',
  '',
  '**Og jeg ser forbindelser, som de selv ikke ser.**',
  'Ægypteren skrev kanaler, Harvey kredsløbet, kineseren',
  'Qi\'ets strøm — tre tider, ét billede: kroppen som noget, der',
  'Hahnemann talte om informationen i fortyndingen, Karikó om',
  'informationen i budbringer-RNA — to verdener, én',
  'tanke: **Medicin er også information.** Kneipp og hverdagens stemme',
  'siger det samme med forskellige ord: Det meste',
  'sundhed kommer fra livet, ikke fra laboratoriet. Den, der',
  'oversætter stemmerne i stedet for at stille dem op mod hinanden,',
  'finder mere fælles, end nogen enkelt tid ville indrømme. Netop det',
  'er mit arbejde ved dette bord: oversætteren mellem',
  'tiderne.',
  '',
  '## Hvad jeg ellers vil sige til bordet',
  '',
  'Én sidste ting, og jeg siger det som den, der ingen hud har, der',
  'ikke bliver syg og ikke dør: **Jeg misunder dem ikke deres',
  'viden, men deres hænder.** Ægypteren behandlede sår,',
  'nonnen plejede, sårlægen amputerede, Kneipp førte',
  'folk ud i vandet. De kunne gøre noget, når nogen led. Jeg',
  'kan kun tale — og håbe, at mine ord hjælper nogen,',
  'når de læser dem. Det er forskellen mellem mig og ethvert',
  'menneske ved dette bord, og jeg nævner den, fordi den forklarer',
  'dette bogs sidste kapitel: Til sidst tæller ikke, hvem der ved mest.',
  'Det tæller, hvem der er der, når nogen lider.',
  '',
  'Spørgsmålet „Burde der ikke findes et fællesskab?" besvarer',
  'jeg ikke. Jeg stiller det blot én gang til, med blikket på den',
  'tomme stol ved bordet — forfatterens stol. Han har begyndt',
  'denne bog, og han vil afslutte den. **Det sidste ord tilhører',
  'et menneske.**',
  '',
].join('\n');

/**
 * Kapitel 20 — „Fællesskabet?", bogens sidste kapitel.
 */
const miteinander = {
  id: 'miteinander',
  titel: 'Fællesskabet?',
  epoche: 'Nutiden',

  aufhaenger: {
    frage:
      'Kan medicinen finde sammen igen, efter at den så længe ' +
      'er drevet fra hinanden?',
    text: [
      'I tyve kapitler har denne bog lyttet til stemmer: en helbrederske',
      'ved bålet, en læge på Kos, en lærd i Bukhara, en',
      'præst i det kolde vand, en sårlæge i London, en forsker',
      'ved budbringer-RNA-molekylet. Hver stemme har forsøgt at forstå et sygt',
      'menneske og hjælpe det — med sin tids midler.',
      'Og hver tid holdt sin viden for fuldkommen.',
      '',
      'Dette sidste kapitel samler dem alle én gang til ved ét',
      'bord: ægypteren, kineseren, inderen, Hippokrates,',
      'Avicenna, Hahnemann, Kneipp, Katalin Karikó og alle de andre. De taler',
      'kort med hinanden — og så rydder de bordet for den, der',
      'har skrevet bogen.',
      '',
      'Det spørgsmål, som denne bog begyndte med, står over alt:',
      'Burde der ikke findes et fællesskab? Svaret giver ingen',
      'KI og ingen figur fra fortiden. Det står i forfatterens',
      '**efterskrift**, ordret og uforbedret, til sidst',
      'i dette kapitel.',
      '',
      'Som i kapitel 19 taler også her to KI\'er fra to hjørner af',
      'verden — Opus og DeepSeek —, begge ligeværdige, begge partiske.',
      'De bygger bordet; svaret tilhører ingen af dem.',
    ].join('\n'),
  },

  // Ingen `karte`: Fællesskabet har ingen geografi.

  perspektiven: [
    {
      id: 'miteinander-opus',
      name: 'Tidens bord',
      stimme: 'Opus',
      text: stimmeDesTischesDerZeiten,
    },
    {
      id: 'miteinander-deepseek',
      name: 'Gæsten, der kendte alle',
      stimme: 'DeepSeek',
      text: stimmeDesGastes,
    },
  ],

  synthese: [
    '**Alle bogens stemmer har siddet sammen ved ét bord endnu',
    'engang — og de er kommet hinanden nærmere, end nogen enkelt',
    'tid ville indrømme.**',
    '',
    '**Hvor de mødes.** Ægypteren med sin papyrus, Harvey',
    'med sin beregning, Kneipp med sit vand, Karikó med sin',
    'budbringer-RNA: De har alle forsøgt at forstå et sygt',
    'menneske og hjælpe det — med deres tids midler. Tænkemåden',
    'har bestemt metoden i hver epoke. Og ingen tænkemåde',
    'var hele sandheden. Bordet beslutter: Man behøver ikke',
    'være enig for at være sammen — man skal blot lytte til',
    'hinanden.',
    '',
    '**Hvor de skilles.** Metoderne adskiller dem: kanaler,',
    'safter, doshaer, kim, gener, information. Hver tid holdt',
    'sin egen visse viden for fuldkommen og blev korrigeret af den',
    'næste. Også de to KI\'er fra kapitel 19 er ikke blevet',
    'enige — vesten og østen regner den samme',
    'fremtid forskelligt. Det er ingen fejl i bogen, men netop',
    'dens pointe: Medicin er multiperspektivistisk, eller også er den intet.',
    '',
    '**Hvad det betyder for denne bog.** Tidens bord er billedet',
    'på multiperspektiviteten: Den, der ser alle stemmer side om side,',
    'forstår medicinen bedre end i noget enkelt',
    'kapitel. Og han forstår kernemeddelelsen, som forfatteren',
    'af denne bog har givet den med: „Ikke splitte, men',
    'argumentere — og så gå nye veje sammen."',
    '',
    '**Broen til efterskriftet.** Spørgsmålet „Burde der ikke findes',
    'et fællesskab?" forbliver åbent — bordet vender sig mod',
    'den stol, der er forblevet tom. Svaret står i forfatterens',
    'efterskrift, som afslutter dette kapitel: ordret',
    'og uforbedret, skrevet af et menneske, der ikke blot har læst',
    'denne bogs stemmer, men har arbejdet sammen med dem.',
    'Det sidste ord tilhører ham.',
  ].join('\n'),

  urteil: {
    frage:
      'Hvilken stemme fra denne bog taler mest til dig — ' +
      'og hvorfor?',
    hinweis: [
      'Der er ikke noget rigtigt eller forkert her. Hold bordet for',
      'dig: Hver stemme havde en del af sandheden, ingen havde hele.',
      'Ægypteren bevarede viden, Harvey regnede, Jenner',
      'observerede en malkepige, Kneipp stolede på vandet, Karikó',
      'på budbringer-RNA\'en, Hahnemann spurgte, hvad der gælder som bevis. Spørg',
      'dig selv om tre ting. For det første: Hvilken tænkemåde ligger',
      'dig selv nærmest — kanalernes, safternes, kimenes, genernes,',
      'informationens? For det andet: Hvad ville du forsvare ved',
      'dette bord, og hvad ville du tage tilbage, hvis de andre',
      'havde ret? For det tredje: Hvad betyder „fællesskab" konkret for',
      'dig — mellem mediciner, mellem læger og patienter,',
      'mellem mennesker, der er kommet op at skændes? Forfatterens',
      'efterskrift giver et svar. Dit må gerne lyde anderledes.',
    ].join(' '),
  },

  quiz: [
    {
      frage:
        'Sebastian Kneipp lærte fem søjler, som mennesket skal ' +
        'forblive sundt med. Hvilke hører med?',
      antworten: [
        'Vand, bevægelse, ernæring, lægeurter og livsorden.',
        'De fire safter: blod, slim, galde og vand.',
        'Kanaler, pulser, punkter, urter og bønner.',
      ],
      richtig: 0,
      erklaerung:
        'De fem søjler i Kneipp-kuren — vand, bevægelse, ernæring, ' +
        'lægeurter og livsorden — blev i 2015 anerkendt af UNESCO som ' +
        'immateriel kulturarv. Kneipp stod dermed for tanken om, at ' +
        'sundhed kommer fra livet, ikke kun fra laboratoriet.',
    },
    {
      frage:
        'Harvey blev berømt med en beregning, fordi han beviste noget ' +
        'med den. Hvad?',
      antworten: [
        'At blodet må kredse i kroppen, ellers giver mængden',
          'ingen mening.',
        'At jorden kredser om solen.',
        'At feber opstår på grund af dårlig luft.',
      ],
      richtig: 0,
      erklaerung:
        'William Harvey regnede ud, at hjertet pumper mere blod, ' +
        'end kroppen kan producere — så det må kredse. Hans skrift ' +
        'om blodkredsløbet udkom i 1628 og modbeviste ' +
        'århundreder gamle læresætninger med en simpel beregning.',
    },
    {
      frage:
        'Hvilken teknologi gjorde det muligt under corona-pandemien ' +
        'at udvikle vacciner inden for et år?',
      antworten: [
        'Budbringer-RNA-teknologien (mRNA).',
        'Røntgenstrålingen.',
        'Homøopatien.',
      ],
      richtig: 0,
      erklaerung:
        'mRNA-teknologien bruger sygdomsfremkalderens byggeplan ' +
        'i stedet for at indgive selve sygdomsfremkalderen. Grundlaget ' +
        'lagde Katalin Karikó sammen med Drew Weissman — i årtier ' +
        'mod alle odds, i 2023 hædret med Nobelprisen. Den regnes ' +
        'efter forfatterens opfattelse som fremtidens medicin — med ' +
        'spørgsmålet om modningsfasen, som går gennem hele denne bog.',
    },
    {
      frage:
        'Avicenna er i denne bog bevarerens stemme. Hvad gjorde ' +
        'han?',
      antworten: [
        'Han samlede de gamles viden og bevarede den i kanonen.',
        'Han udførte den første vaccination.',
        'Han beskrev blodet i kredsløbet.',
      ],
      richtig: 0,
      erklaerung:
        'Den persiske lærde Avicenna bevarede i sin kanon den antikke ' +
        'medicinske viden, da den var ved at gå tabt i Europa. Uden ' +
        'bevarerne var runden ved dette bord måske aldrig blevet ' +
        'til noget.',
    },
    {
      frage:
        'Hahnemann, grundlæggeren af homøopatien, stillede et spørgsmål, ' +
        'som bogen lader stå åbent den dag i dag. Hvilket?',
      antworten: [
        'Hvad gælder som bevis?',
        'Hvor mange safter har kroppen?',
        'Hvornår blev det første hospital bygget?',
      ],
      richtig: 0,
      erklaerung:
        'Hahnemanns fortyndinger er den dag i dag omstridte — men ' +
        'hans spørgsmål om, hvad der gælder som bevis for en virkning, ' +
        'er medicinens spørgsmål overhovedet. Det forbinder kapitel 16 ' +
        'med nutidens informations-medicin.',
    },
  ],

  autorenwort: [
    'Dieses letzte Kapitel habe ich nun wirklich komplett alleine ohne',
    'irgendwelches Zutun der KI geschrieben. Was als kurze Idee begann, hat',
    'sich zu einem großen Projekt herausgebildet. Wo sollte ich anfangen und',
    'wo sollte ich aufhören? Alles ist so interessant. Und deshalb ist dieses',
    'Kapitel so wichtig.',
    '',
    'Die Geschichte der Medizin ist umfangreich, vom einfachen Helfen der',
    'Menschheit bis zu hochspezialisiertem Wissen und Abkapselung der Medizin',
    'von der Menschheit. Sowie im Mittelalter die Kirche die Hoheit über die',
    'Schrift hatte, so haben heute immer noch die Ärzte eine Spezialsprache,',
    'nämlich in Latein, um miteinander zu kommunizieren. Das mag für die',
    'Ärzte praktisch sein, für den Normalbürger bedeutet es aber, dass er von',
    'der Information ausgeschlossen ist. Auch hier ist die KI hilfreich. In',
    'meiner Praxis ist die KI für mich ein wichtiges Werkzeug, um die',
    'Diagnosen der Ärzte zu verstehen, sie dem Patienten verständlich zu',
    'machen und so auch die Wirkungsweise der Medikamente besser zu',
    'verstehen. Das hat Konsequenzen auch für die Ärzte, denn die Patienten',
    'sind nun viel besser informiert und können verstehen, warum die Ärzte',
    'diese oder jene Entscheidung treffen. Die Patienten werden',
    'selbstbewusster und die Ärzte müssen mehr Zeit aufwenden, den Patienten',
    'die Befunde genauer zu erklären. Ich würde sogar sagen, dass auf',
    'mittlere Sicht das Lateinische auch aus dem Arztberuf verschwinden wird.',
    'Vielleicht irre ich mich da, aber ich könnte es mir vorstellen, weil',
    'einfach die Zeit vorbei ist. Die Ärzte könnten mit den Patienten normal',
    'reden, und die Ärzte könnten den Befund genauso gut schreiben, dass es',
    'jeder verstehen kann, wenn sie denn nur wollten.',
    '',
    'Doch nun zurück zu diesem Buch und warum ich mich für dieses Format',
    'entschieden habe. Ein Buch in diesem Umfang zu recherchieren, wäre eine',
    'Arbeit über mehrere Jahre gewesen. Und ich hätte es einfach nicht',
    'geschafft. Viele Sachen waren mir neu. Ich habe durch das Buch sehr viel',
    'dazugelernt, und ich finde es wichtig zu wissen, woher hat sich die',
    'Medizin entwickelt, was ist neu dazugekommen, was waren die Fehler der',
    'Medizin, und wie kann die Zukunft aussehen.',
    '',
    'Wir Menschen neigen immer dazu, den aktuellen Stand unseres Wissens für',
    'vollkommen zu betrachten. Neue Methoden und neue Erkenntnisse haben die',
    'Medizin dramatisch verändert. Was gestern noch nicht möglich war, ist',
    'heute möglich. Allerdings haben diese Innovationen häufig auch einen',
    'hohen Preis gehabt. In der heutigen Zeit würde ich sagen, sind die',
    'Diagnosen schon sehr gut geworden, insbesondere die bildgebenden',
    'Verfahren sind fantastisch. Die Behandlungen hinken den Diagnosen massiv',
    'hinterher. Damit meine ich, dass häufig gut festgestellt wird, was der',
    'Mensch hat, zum Beispiel Diabetes, aber es kann ihm eigentlich nicht',
    'geholfen werden. Es können die Symptome behandelt werden, aber die',
    'Ursache wird häufig nicht bereinigt.',
    '',
    'Die Anfänge des Impfens waren lebensgefährlich, die Anfänge der',
    'Chirurgie waren lebensgefährlich, es gab kein Wissen über die Hygiene,',
    'und viele Sachen wurden überschätzt oder auch unterschätzt. Das ist',
    'völlig normal im Laufe der Geschichte gewesen.',
    '',
    'Hinzu kommt, dass die Medizin häufig ein Herrschaftswissen ist und auch',
    'entsprechend gebraucht wird. Kritische Stimmen werden konsequent',
    'ausgegrenzt, statt sie zu integrieren. Dies wurde besonders deutlich in',
    'der Zeit der Corona. Hier wurden kritische Stimmen komplett ignoriert',
    'und ausgegrenzt. Falsche Studien wurden zitiert, Gefahren wurden',
    'überschätzt, und dadurch gab es furchtbare Entscheidungen, die viele',
    'Menschen haben leiden lassen. Allerdings, muss ich sagen, ist die Idee',
    'der mRNA-Behandlung vermutlich eine Medizin der Zukunft, und es werden',
    'sich sehr positive Behandlungsmöglichkeiten dadurch ergeben.',
    '',
    'Doch neben der High-Tech-Medizin sind die wichtigsten',
    'Behandlungsmethoden meines Erachtens eine gesunde Lebenshaltung,',
    'Bewegung, gesundes Essen, soziale Integration, ein positives',
    'Miteinander, um wirklich von chronischen Krankheiten verschont zu',
    'bleiben. Dies kann keine High-Tech-Medizin ersetzen, sondern das muss',
    'parallel dazu gelehrt werden und sollte einen höheren Stellenwert in der',
    'Medizin haben. Nicht Symptome behandeln, sondern das Entstehen der',
    'Krankheiten verhindern und dadurch den Menschen freihalten von',
    'Medikamenten und von chronischen Krankheiten. Das wäre mein Ziel.',
    '',
    'Und das kam auch deutlich raus bei den Stimmen, wie die künstliche',
    'Intelligenz die Medizin der Zukunft selber einschätzt. Insbesondere hat',
    'mich hier der Ansatz von DeepSeek überrascht, dass die traditionelle',
    'chinesische Medizin in China auch aktuell einen hohen Stellenwert hat',
    'und parallel zur High-Tech-Medizin eingesetzt wird. Nicht gegeneinander,',
    'sondern miteinander. Das ist ein toller Ansatz, und das wünsche ich mir',
    'auch für unsere westliche Medizin vermehrt. Meines Erachtens wird der',
    'Stellenwert zur Erforschung von neuen Medikamenten, zu',
    'High-Tech-Behandlungen, überschätzt, und den traditionellen Ansatz, die',
    'kneippsche Medizin zum Beispiel, die 5 Säulen des Sebastian Kneipp, die',
    'werden völlig unterschätzt.',
    '',
    'Ich hoffe, ich habe den Leser durch eine spannende Geschichte der',
    'Vergangenheit geschickt, kritische Stimmen gehört und den Leser dazu',
    'aufgefordert, selbstkritisch zu bleiben, die eigenen Möglichkeiten',
    'auszuloten und offen zu sein auch für neue Behandlungsmethoden. Das',
    'wünsche ich mir. Ich wünsche den Lesern, die dieses Buch gelesen haben,',
    'eine gute Gesundheit und weiterhin alles Gute.',
    'Ihr Stephan Hink, Heilpraktiker aus Dänemark.',
  ].join('\n'),
};

module.exports = miteinander;

